### ISSUE TITLE
Support multiple Author attributes per test

### ISSUE THREAD

**Issue by DerekSMorin** [nunit/nunit#1000]
Support multiple Author attributes per test

https://github.com/nunit/nunit/wiki/Author-Attribute

Note: you can currently only have one Author attribute per fixture or test.

**Comment by CharliePoole** [comment]
@nunit/contributors Here's another that has been waiting for comments for a year. Let's clean up!

**Comment by rprouse** [comment]
I don't have a strong opinion on this. I can see the use and I don't see the implementation being much different than allowing multiple categories on a test.

**Comment by immeraufdemhund** [comment]
I don't like the idea of having an `AuthorAttribute` as I've subscribed to the notion that all code you touch becomes your responsibility to a certain degree. Another reason I don't like it is because of source control. If I *REALLLY* have to find out who was the first person to write this I can use history. Lastly if it really is that important to know who the author(s) is than why isn't there an automated header on each file that was inserted on creation that you could scroll up to and read/modify. My vote is strongly against having any `AuthorAttribute`.

**Comment by CharliePoole** [comment]
Speaking as a coach, I agree with you. I would not like to see any of my
teams use this.

Speaking as a tool developer, i have to take a different view. Some folks
asked for the attribute and we agreed to provide it. Different teams work
in different ways.

The attribute has existed for a number of releases and I don't see removing
it as an option. This issue is about allowing it to appear multiple times.
I'm in favor because restricting it feels arbitrary.

Thanks for your comment. It has given me an idea about writing something
from my personal point of view about how I think NUnit should be used.

**Comment by CharliePoole** [comment]
@rprouse I'd say allow it. Again, we don't use the attribute, so it should be no more than changing a property on the attribute usage.

**Comment by JustinRChou** [comment]
Is this still relevant?

So the recommended way of adding authors is using the AuthorAttribute?
The Test author property can be ignored?

**Comment by CharliePoole** [comment]
@JustinRChou Yes, it has been marked as an enhancement and added to the Backlog. Nobody is working on it. You can take it if you want it, therefore. 😄 

The Author property on tests is set by adding the AuthorAttribute to the test method. Currently, it is only allowed to appear once. If you change it to allow multiple Author attributes the only other thing needed is to see how the property is used. PropertyBag allows adding multiple values with the same key but only if you use the right method to do it. See Set versus Add methods.

**Comment by JustinRChou** [comment]
I was referring to the following usage.

` [Test(Author = "Rob Prouse")]`

I don't see how would it work unless for use a delimiter, or add a Authors property.

**Comment by CharliePoole** [comment]
I forgot we did that! We could make the two work together or we could deprecate the property. Alternatively we could ignore or overwrite one of them.

Since it's low priority, we shouldn't get too complicated.

**Comment by JustinRChou** [comment]
I would be fine with fixing the AuthorAttribute and updating the documentation to recommend using it.

**Comment by JustinRChou** [comment]
I just noticed that the TestCaseSource doesn't have the Author property? 

And just making a note here.
I don't think it would be common if someone wants to author a TestCase like so
` [TestCase(5, Author = "Charlie Poole"), Author("Rob Prouse"), Author("NUnit")]`
which would only apply "Charlie Poole" to the TestCase while "Rob Prouse" and "NUnit" are applied to the TestMethod.
