### ISSUE TITLE
Poor formatting of results for Assert.AreEqual(DateTimeOffset, DateTimeOffset)

### ISSUE THREAD

**Issue by JohanLarsson** [nunit/nunit#1004]
This test fails as expected:

    [Test]
    public void DateTimeOffsetsNotEqual()
    {
        var expected = DateTimeOffset.MinValue + TimeSpan.FromTicks(1);
        Assert.AreEqual(expected, DateTimeOffset.MinValue);
    }

The output is a little confusing:

    Expected: 01/01/0001 00:00:00 +00:00
    But was:  01/01/0001 00:00:00 +00:00

I don't have time to write a PR for this right now, hence this issue.

**Comment by CharliePoole** [comment]
Thanks, we like issues. :-)

I'm not sure how we should display the values in this case, but it's worth thinking about.

**Comment by JohanLarsson** [comment]
Simplest is perhaps:
```
time.ToString("O")
```
It formats according to [ISO8601](https://en.wikipedia.org/wiki/ISO_8601)
Sample:

    Expected: 0001-01-01T00:00:00.0000001+00:00
    But was:  0001-01-01T00:00:00.0000000+00:00

**Comment by appel1** [comment]
Perhaps there should be some more generic object formatting system in place with default implementations for common types and that make it possible to override existing or provide new ones for types under test where ToString isn't enough.

**Comment by oznetmaster** [comment]
Even with the addition of the new formatting capabilities, I still think that DateTimeOffset should have its own default formatter which is different then the DateTime formatter.

DateTimeOffset is a basic type in .NET since 3.5 (3.0?) and is actually recommended to be used instead of DateTime, so it would seem prudent to support it.

I have had this in my CF build for a long time (I fully support DateTimeOffset in CF), exactly for the reasons given in this issue.  I also use the "O" format as the default.

**Comment by oznetmaster** [comment]
Interesting issue this brings up.  DateTime uses a custom format ("yyyy-MM-dd HH:mm:ss.fff") with the InvariantCulture rather then a standard one (like "O").

Which approach is better?  Does it matter?

**Comment by CharliePoole** [comment]
@oznetmaster Agreed. This is an accepted bug.

We generally have used InvariantCulture for things like this.

**Comment by CharliePoole** [comment]
It's an especially easy fix now that we are using a chain of formatters.

**Comment by rprouse** [comment]
To the invariant culture vs current culture, my preference is invariant in a standard format so that the test results are the same no matter what machine you run them on. When we are finally able to run tests on different machines and devices, we don't want different formats coming back from the various machines that the tests might be running on.

Just my opinion, like the decision to use UTC time everywhere. I'm sure others will disagree :smile:

**Comment by oznetmaster** [comment]
The fix is virtually identical as it was before.  Still need formatting string and formatting method.  They are unchanged.  Just need to invoke the factory in the static constructor.

**Comment by oznetmaster** [comment]
I fully agree that all default formatting should be against the invariant culture, even more so now that it is easy to change if desired.

What I was really asking was should we use standard format string vs custom ones for things like DateTime and DateTimeOffset.  For instance, "O" (which is the round-trip format) is always invariant, and is always the same.

**Comment by CharliePoole** [comment]
Since we are talking about NUnit 3, I feel like we can still change this if
desired. For DateTime, I used a hard-coded format that I thought would be
easier for people to deal with in XSL. However, I'm not an expert in XSL
and hope never to have to be one. :-)

I'm happy to go whatever way you guys think is best, but we should be
consistent between the two types.

**Comment by oznetmaster** [comment]
So we need to decide what format to use for both data types.  We could just leave the current one for DateTime, or we could standardize on "O" for both, or some other format for both.

It appears that "O" provides the most detail on the value, and is culture invariant.  It is also the only standard format that appears to differentiate between DateTime and DateTimeOffset.

It is defined as "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK" for DateTime, and "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffzzz" for DateTimeOffset.

Changing to "O" for DateTime would involve changing a few of the tests as well, since some do embed date time output strings in their Assert for results..

**Comment by CharliePoole** [comment]
Are we only talking about messages here? Or are we also talking about how we format DateTime fields in the XML result file?

**Comment by oznetmaster** [comment]
I am talking about the XML result file, which was what this whole issue started with.

**Comment by CharliePoole** [comment]
@oznetmaster Any progress on this?

**Comment by oznetmaster** [comment]
I have been waiting for input on which format to use.  @CharliePoole  You had never responded to the answers I gave to your questions.

**Comment by CharliePoole** [comment]
Not sure what you need resolved. I have no particular opinion on the format and figured we would get into it as part of the code review. My only concern was for changing the format in the XML file anyplace except for messages (e.g. start time). You answered that.

You may have noticed that I often have to take the lead in pressing people when I'm waiting for input on an issue or PR. That's basically part of the process: the person who takes on a task has to keep it moving forward.

Is there any other question for which you are waiting for me or others?

**Comment by JohanLarsson** [comment]
Any chance of adding this to a 2.6.4.1? I have tried 3.x a couple of times but it was not ready for use.

**Comment by rprouse** [comment]
@JohanLarsson, we are not planning on a new 2.6 release. It is not always a simple back-port since they are different code bases. Why do you feel that 3.x is not ready for use? Is it lack of third party support?

**Comment by JohanLarsson** [comment]
@rprouse I have tried 3.x a couple of times on different projects, had all kinds of problems:
- All tests not run.
- Running one test starts another.

I don't have a complete list nor repro but in fact it was very little that worked. Colleges and friends have had similar experiences.

- VS2015 Update 1
- Resharper 10.2
- Running tests using Rehsarper's runner.

**Comment by CharliePoole** [comment]
We have reports of all tests not being run but not of running one test starts another. If you can replicate this with the NUnit adapter or console runner, please file an issue. If it's only using Resharper's runner, then it's an issue for JetBrains.

**Comment by JohanLarsson** [comment]
I never use anything but Resharper's runner, that leaves me with 2.6.4 or xunit. Not a big problem as 2.6.4 is nice.

**Comment by CharliePoole** [comment]
Based on google searches, I am not able to determine whether Resharper 10.2 actually uses the latest version of NUnit 3.0 (3.0.1) - there are at least some indications on the web that they may use an older release and they don't really tell us these things.

**Comment by JohanLarsson** [comment]
Yes, the testrunner has always been shaky but the integration is nice. There are and have been issues on Resharper's version of connect about it.
