### ISSUE TITLE
MsTest and xunit compatibility extensions

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1023]
I was wondering about the efficacy of providing compatibility extensions/libraries that would allow MsTest and xunit test assemblies to compile and run with nunit.

I find myself doing conversions all the time.

If it were a simple matter of changing the using statements, and recompiling, it would encourage the migration to nunit.

**Comment by CharliePoole** [comment]
It's possible to create an extension with a driver for some other framework. What's required in the driver is code to 
1. Call into the foreign framework to make it load, run tests, etc.
2. Translate any filters to the form required by the foreign framework.
3. Translate discovered tests and results back to NUnit format as they arrive.
Our NUnit V2 driver provides an example of doing this.

It would be moderately easy to create an extension for either of these but it might not be legal for MSTest, since it requires bundling assemblies from the framework.

Using statements have been used in the past. They provide for all the simple cases, but usually end up falling short at least part of the time.

**Comment by oznetmaster** [comment]
You are thinking backwards.  I want to be able to compile and run test written for the foreign frameworks under nunit.

**Comment by CharliePoole** [comment]
Well, one of us is. :-) I was fooled by your using the word "extension" which is what we call the things I described - in the engine. So I guess you are talking about some sort of adaptation layer that makes code written against the foreign framework compile with NUnit instead?

That's an interesting idea and is much better for us in terms of moving people to NUnit.

**Comment by oznetmaster** [comment]
Yes, that is what I meant.

**Comment by rprouse** [comment]
I am not sure how well this would work for xUnit which constructs the class for every test method execution. Wouldn't we need to somehow treat the constructor as a [SetUp] if running using xUnit attributes?

**Comment by oznetmaster** [comment]
Yes

**Comment by oznetmaster** [comment]
And the destructor as a [TearDown]

**Comment by CharliePoole** [comment]
If we are discussing... I don't like the idea. It's something I did a fair bit of in the very distant past. It was easy to get simple tests to work and I was able to run mstest and csunit tests under NUnit quite well. The difficulty was in taking it beyond 95% compatibility, which I found required extensive time investment for diminishing returns.

I think this is a project for somebody to undertake separately from nunit... if it's to be done at all.

**Comment by rprouse** [comment]
I agree with @CharliePoole on this. I think that there are so many subtleties between the way we run tests and the way that other test frameworks run them that there will be many 'bug' reports from users that expect it to just work.

If anything, I could see someone writing an xUnit driver for the engine and properly executing xUnit tests, but I think that if you are going to port your tests, you should do it properly. I am going to close this issue, but anyone is welcome to create their own library to do this as long as they are willing to support it 😄
