### ISSUE TITLE
ExpectedException used by TestCase

### ISSUE THREAD

**Issue by gilescope** [nunit/nunit#1028]
Hi, just testing out NUnit3 on our testbase, and have encountered something that seems a downgrade from previous versions:

[Test]
[TestCase(0, ExpectedException = typeof(ArgumentException))]
[TestCase(1)]
[TestCase(2)]

For 'normal' ExpectedExceptions it makes perfect sense to use Assert.Throws<>, but here it feels like something is lost. In Nunit 3 I'm guessing the only option is to split the test method into two with one having test cases that throw an exception and another having test cases that do not. Is there a more elegant way of expressing the above in NUnit3?

With kind regards,

Giles

**Comment by CharliePoole** [comment]
Yes, the idea of this feature (or lack of it) is to encourage you to split the tests since they are testing different things. Let's say the method being tested is a square root. A test that handles data >= 0 might be called "SquareRootWorksCorrectly." But the one that handles data <0 would be something like "SquareRootOfNegativeValueThrowsAnException."

Of course, you can probably invent a name that covers both cases, but the fact remains that the tests prove two different things. Anyway, that's the outlook that led to the removal of this property.
