### ISSUE TITLE
Should we update Nunit.Runners package to 3.0?

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#1030]
Several people have been complaining on twitter because they have updated their projects to use the NUnit 3 framework, but there is no corresponding update for NUnit.Runners. They do not realize that they need to switch to the new NUnit.Console NuGet package.

Even when you search NuGet for NUnit, the new NUnit.Console package is the 43'rd entry and on the third page. Most people won't find it. NUnit.Runners is the 2nd entry right after NUnit, so it is what everyone sees.

Even if we put the information out on as many channels as we control (mailing list, website, twitter, etc) it will only reach a small fraction of developers who use NUnit.

Should we create an update for the NUnit.Runners nuget package that contains the same binaries as the current NUnit.Console package? Once we have additional runners like the GUI, we can include them in that package and leave NUnit.Console as the lightweight, console only package.

I think we should deal with this soon. NUnit 3 has only been showing up as a non-prerelease update for a couple of days. I think many people are going to be upgrading soon and running into the same problem.

- https://www.nuget.org/packages/NUnit.Console/
- https://www.nuget.org/packages/NUnit.Runners/

**Comment by CharliePoole** [comment]
I agree. At one time, I had planned to use a different id for **every** package, so that people would not be automatically upgraded to 3.0. There are arguments each way, but the main framework package now has the same id as V2, so folks have a right to expect other things to work as well. The automatic update will be enough of a shock to some of them! We'll have to be ready to answer questions.

I'll make the nunit.runners package depend on nunit.console, which should have the same effect. As for the gui, I'm not sure it belongs there but we can cross that bridge when we get to it.

**Comment by CharliePoole** [comment]
I made this milestone 3.2 for reporting purposes, but I'll push to nuget right away.

**Comment by rprouse** [comment]
Do you think a dependency is the right solution? That will end up pulling down the v2 nunit-console and the v3 nunit3-console. I expect users will continue to try to run the v2 console because it is in the package they added, but it won't work for them.

The nunit3-console will run nunit 2 tests, so should we release a new nunit.runners package that contains it instead of what it used to contain?

**Comment by CharliePoole** [comment]
I meant a dependency on nunit.console alone. It would be a 'virtual' package.
