### ISSUE TITLE
"No arguments were provided" with Theory and Values combination

### ISSUE THREAD

**Issue by seraphim207** [nunit/nunit#1033]
Having such test definition I recieve "No arguments were provided" error:

```
[Theory]
public void ShouldGenerateForAnyTimePeriod(
   bool isCoApplicant,
   SomeEnum timePeriodInputType,
   [Values(0, 2)] Int32 years,
   [Values(0, 5, 15)] Int32 months)
{
...
}
```
If I remove first two arguments or last two arguments NUnit behaves as expected. I tried to declare Datapoints, but this did not change the result:

```
[Datapoints]
public Boolean[] bools = { true, false };

[Datapoints]
public TimePeriodInputType[] timePeriodInputTypes = { TimePeriodInputType.FromTo, TimePeriodInputType.YearsMonths };
```
NUnit v3.0, test runner v3.

**Comment by constructor-igor** [comment]
NUnit v3 console returns error message:

![image](https://cloud.githubusercontent.com/assets/1849690/11402691/dc403dc0-93a1-11e5-8636-d7d9123d5d52.png)

NUnit v2.6.4 executed the test
![image](https://cloud.githubusercontent.com/assets/1849690/11402709/f81c5060-93a1-11e5-896c-6c445ef8ce74.png)

**Comment by CharliePoole** [comment]
Thanks @constructor-igor I removed the status:confirm.

**Comment by CharliePoole** [comment]
This is a much more general problem than the example initially suggested. NUnit 2.6.4 allows a Theory to combine data provided by a parameter attribute with data supplied by a datapoint. NUnit 3.0 is not allowing that - the data must be entirely supplied by attributes or entirely by datapoints.

To complicate things, when I initially wrote a test for this, it passed! Turns out that the running of tests at the second level using TestBuilder uses a slightly different implementation. So this issue is not seen by the unit tests at all!

**Comment by seraphim207** [comment]
Great, thank you!
