### ISSUE TITLE
NUnit Official website is vulnerable with HTML Injection

### ISSUE THREAD

**Issue by raad9** [nunit/nunit#1034]
i am able to inject any html code with this vulnerability on this page : http://nunit.org/?p=

the variable "p" is vulnerable .

So what i can do with this ? it's easy to help me steal users cookies , by injecting an "img" tag with attribute "src" that reffer to some page i made it to steal cookies .

Example : 
http://nunit.org/?p=<img src="some page"/>

**Comment by CharliePoole** [comment]
Thanks for pointing that out. I'll run some tests.

**Comment by raad9** [comment]
you are welcome :)

**Comment by rprouse** [comment]
While it is vulnerable to that attack, AFAIK, there are no cookies that are of any value on the NUnit website. I think the only cookies that get stored are your preferred programming language for the code examples.

Also, there is no way for users to post comments on the site, so I believe that the only way to exercise this vulnerability is through cross-site links as above.

Am I missing a way of exploiting this that exposes more sensitive information? I guess they could possibly inject javascript to rewrite some of the dom to inject links or text that looks like it came from us.

We should fix this, but I would rather see it fixed by finally getting the new website out :smile:

**Comment by CharliePoole** [comment]
I figured I'd step through and see what we do with the two or three variables we pull from the URL.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit.org #44](https://github.com/nunit/nunit.org/issues/44) via [**ZenHub**](https://www.zenhub.com/)
