### ISSUE TITLE
Nunit-console.exe and Nunit3-console.exe are 32-bit applications causing /process:Single to fail with 64-bit test assemblies.

### ISSUE THREAD

**Issue by basbossink** [nunit/nunit#1043]
When using the /process:Single command-line switch of Nunit-console.exe no nunit-agent is used. However the fact that both nunit-console.exe and nunit-console-x86.exe exist suggests that these applications are themselves 64-bit and 32-bit applications respectively. However when running a 64-bit assembly with the /process:Single switch the run fails with a BadImageFormatException. Looking at the output of dumpbin shows that both nunit-console.exe and nunit3-console.exe are actually 32-bit applications. Could they both be build as 64-bit applications?

The /process:Single is handy when debugging a memory problem caused by native code that gets called while running a specific test. Now nunit-agent.exe crashes and nunit-console.exe only reports the fact that it can not reach the process .

**Comment by CharliePoole** [comment]
First, let's clarify something. NUnit-Console and NUnit3-Console are neither 32 nor 64 bit applications. Rather, they are pure managed apps that run in a 32-bit process on a 32-bit system and a 64-bit process on a 64-bit system. NUnit-console-x86.exe (V2) is also pure IL, but has a flag set that tells it to run in a 32-bit process.

The philosophy we followed with command-line options for NUnit3-console is that it's possible to enter contradictory options, which give rise to an error. This seems the simplest way to do it for an audience of quite knowledgeable users. So, if you tell NUnit to run in process in a situation where it is not possible, it tries to do so and fails. Similarly, if you tell it to run under a runtime framework version that isn't installed, it will fail. If you tell it to run two test assemblies with the same assembly name in the same AppDomain, it will fail. You get the idea. :-)

We could have followed a different philosophy, one of analyzing the specific combination of options in the context of each assembly on the command-line and giving you a message like "Sorry, I can't do that..." However, such analysis would involve almost the same work as actually trying to run the test. We would have to create the separate processes and domains, try to load the tests, etc. Given the nature of our user base, we picked the simplest approach.

For NUnit V2, you can run a 32-bit test in process by executing nunit-console-x86.exe. A 64-bit test will run just fine using nunit-console-x64.exe. It's the flags on the executable that determine whether the process is 32-bit or 64-bit and the nunit code is a sort of "universal donor" i.e. it's pure IL.

With V3, it is no longer possible to run a 32 bit test in process. You should specify the --x86 option so that it uses the x86 agent. The --debug option makes it trivial to debug the tests when running in an agent. You have probably noticed that running in a separate process is now the default. What you may not have noticed is that other options, like --debug, make it easier to use that default.

I'm not seeing a bug in all this anywhere. If I missed something, feel free to clarify!
