### ISSUE TITLE
After upgrading to Nunit 3.0, the VS Test runner is missing tests

### ISSUE THREAD

**Issue by ericnewton76** [nunit/nunit#1079]
Just upgraded to NUnit v3.0.0 from NUnit v2.6.4 via nuget update, but now the tests don't show up in VS Test Runner extension...

Also made sure that build configuration for x64/x86 was correct but no dice?

**Comment by rprouse** [comment]
For anyone else who finds this issue, you must install the new NUnit3 Test Adapter. The original NUnit2 adapter only runs v2 tests and the new NUnit3 adapter only runs v3 tests.

https://visualstudiogallery.msdn.microsoft.com/0da0f6bd-9bb6-4ae3-87a8-537788622f2d

If you will only be using NUnit 3.0 going forward, I would recommend that you also uninstall or disable the old NUnit Test Adapter so that one less test extension is searching for tests. They work together, but it slows you down a bit having adapters that aren't used.

**Comment by danieltharris** [comment]
Is it no longer possible to install the Test Adapter via NuGet for v3? If not that's fine, I'll just add it to our documentation and indicate that the extension is a requirement for the relevant projects but I couldn't find a definitive answer.

**Comment by rprouse** [comment]
@danieltharris you can still install the adapter for the projects, but you need to use the new v3 adapter, not the old adapter. Remove the NuGet reference for `NUnitTestAdapter` and add one for `NUnit3TestAdapter`

**Comment by danieltharris** [comment]
@rprouse Thanks I've found that now and got it working. It's much easier this way versus VISX extensions. Glad it's still possible with v3. Not sure how I missed the package in the NuGet explorer the first few times
