### ISSUE TITLE
3.0.1

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1088]
How is anyone going to distinguish 3.0.1 from 3.0, since there is no difference in any human or machine readable version number that I can see?

This references back to the whole version numbering scheme for these releases.

I still feel we need to go to a "major, minor, revision, build" versioning scheme.

**Comment by rprouse** [comment]
I agree that we should switch versioning, but we can't do so until we increment the minor. Until then, most people just see the nuget version and the revision will be higher.

**Comment by CharliePoole** [comment]
@oznetmaster I feel you are overstating the case and may end up confusing people who read this issue. It is not true that there is no visual difference... but it may be the case that there is insufficient difference for the convenience of our users. 

I agree that we may want to change this when possible. However, here's what we now have:

1. If you downloaded and installed version 3.0.1, then that's what you have! The only time this is not the case is for users who install the framework via nuget and who have their projects set up so that all updates are automatically downloaded. I don't know if this is the most common case.

2. The Console displays a version number of 3.0.5797 for the 3.0 release. My latest build shows 3.0.5811 and the 3.0.1 release will have something higher. There is a page on the wiki that correlates these assembly versions to package versions.

3. NUnitLite displays the same version number as the console runner.

4. The TestResult.xml file shows the engine version as an attribute of the test-run element and the framework version as an attribute of each assembly's environment element. These may, of course, be different.

Could you explain what you suggest we do? You say that we should go to a "major, minor, revision, build" versioning scheme but all .NET versions have those components, including ours. How would you propose to use them?

**Comment by CharliePoole** [comment]
Should we do something for this release, to force the display of "3.0.1" by the runners?

**Comment by rprouse** [comment]
I am inclined to leave it for 3.0.1 and go for the easy fix in 3.1/3.2.
Once we increment the minor, then we can hard code the revision and leave
the build as * without breaking the MSI or putting some sort of hack into
the runners.

On 29 November 2015 at 12:30, CharliePoole <notifications@github.com> wrote:

> Should we do something for this release, to force the display of "3.0.1"
> by the runners?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nunit/nunit/issues/1088#issuecomment-160433594>.
>



-- 

Rob Prouse



I welcome VSRE emails. Learn more at http://vsre.info/

**Comment by rprouse** [comment]
Should we leave this discussion to #981 and close this issue as a duplicate?

**Comment by CharliePoole** [comment]
I'm OK with that. I'm also willing to make the console put out a hard-coded "3.0.1" somewhere, if that seems like it would help people in the interim.

**Comment by rprouse** [comment]
I am going to close this. 3.0.1 is out. We can make changes in conjunction with #981
