### ISSUE TITLE
nUnit gui not in 3.0 ?

### ISSUE THREAD

**Issue by fonthardcore** [nunit/nunit#1095]
Am I missing something? The nUnit gui that featured in 2.6.4 isn't in 3.0 anymore. Has it been depreciated? Is it part of a seperate project?

Thanks,.

http://www.nunit.org/index.php?p=nunit-gui&r=2.6.4

**Comment by fonthardcore** [comment]
I see from here that it is not developed yet... https://github.com/nunit/nunit/issues/1052

Would be nice to update the release notes to stipulate this.

**Comment by CharliePoole** [comment]
Good idea. We should probably also have an introduction explaining that 3.0 is more than a new version - it's a complete reworking of NUnit. Folks who have followed the development for years already now that, but now that we have released there is an entirely new audience to deal with.

**Comment by matthew56** [comment]
Is there any target for when this might be done? Or is this new version so new and improved, that the gui is not feasible in the near term?

**Comment by CharliePoole** [comment]
Have you looked at the project Milestones?

The new gui is indeed new. :-) That is, the code has nothing whatsoever to do with the old one. I believe it's improved as well. :-)

Milestone 0.1, which will be version 0.1, is slated for January, but it could end up delayed because there is one outstanding issue that prevents our creating a usable package that includes extensions to the engine. Even so, it's numbered 0.1 to give you an idea of how complete it is. :-)

How long it takes to get to a production release depends on how many folks sign up to work on it. Right now, it's a prototype that you can build and comment on if you like.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/docs #73](https://github.com/nunit/docs/issues/73) via [**ZenHub.io**](https://www.zenhub.io/)
