### ISSUE TITLE
Can't pick up a TestFixture from the Command Line

### ISSUE THREAD

**Issue by BryanBarn** [nunit/nunit#1097]
I'm having problems getting NUnit 3.0 to pick up my TestFixtures from the Command line.

I have a Test Class that uses the Fixture to specify the type of browser I want to test:
namespace ReportsItems
{
    [TestFixture("Chrome", false)] //Feed the browser and useproxy into the test as parameters
    [TestFixture("Firefox", false)]
    [TestFixture("InternetExplorer", false)]
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Interface | AttributeTargets.Method | AttributeTargets.Assembly, AllowMultiple = true)]
    public class ReportsTests : PropertyAttribute
    {
	...
		[TestCase(TestName = "Rep39")]
        [Category("Reports"), Category("Daily_Report"), Category("Rep39")]
        public void Daily_Report_Rep39()
        {
		...
		}
	}
}

In NUnit V2.6.4 I could use the run to specify the Fixture on the Command line:
"C:\Program Files (x86)\NUnit 2.6.4\bin\nunit-console.exe" "%cd%\ReportsItems\bin\Debug\ReportsItems.dll" /run:ReportsItems.ReportsTests(\"Chrome\",False) /include:Reports

Now I've tried various combinations in NUnit 3.0 but I can't get it to pick up the Fixture - it's running all browsers when I only want it to run Chrome browser tests.

--explore shows the test name as ReportsItems.ReportsTests(\"Chrome\",False).testname

I've tried combo's in the --where of name, class, method and test with regex but no joy.

I don't particularly want to have to specify every test by name in a file.

I'm thinking this may be a bug or functionality shortfall?

**Comment by CharliePoole** [comment]
You haven't said what OS you are using and command-line escaping is OS-dependent. Here are some options for where that ought to work on Windows:

--test "ReportItems.ReportTests(\"Chrome\",false)"
--where "test==ReportItems.ReportTests(\"Crome\"),false)"

I've made some changes to the where logic for 3.0.1, so if these don't work, let me know and I'll experiment further.

**Comment by BryanBarn** [comment]
OS is Windows 7.

I'm using backslash to escape the quotes:
ReportsItems.ReportsTests(\"Chrome\",False)

Thanks Charlie :)

**Comment by CharliePoole** [comment]
So is it now working? :-)

**Comment by BryanBarn** [comment]
It's not complaining about the escape and is showing what appears to be correct in the Test Filters section in the cmd window.

It's just not obeying what it's showing.

If I use:
--where "test=~ReportsItems.ReportsTests(\"Chrome\",False)"
it runs all tests all browsers, ie ignores the where.

If I use just 
--where cat=Rep39 
it runs that test for all 3 browsers.


But if I use an and with the cat
--where "test=~ReportsItems.ReportsTests(\"Chrome\",False) and cat=Rep39"
...it runs all tests, all browsers.

It shows this in the cmd window:
Test Filters
    Where: test=~ReportsItems.ReportsTests("Chrome",False) and cat=Rep39

I tried \"" as well but no difference.

If I use an = for the test it doesn't find anything:
Test Filters
    Where: test=ReportsItems.ReportsTests("Chrome",False) and cat=Rep39

**Comment by CharliePoole** [comment]
Most of your regular expressions have errors. The characters '.', '(' and ')' have special meaning in regular expressions and must be escaped.

I notice you are using False rather than false. I think you need the latter.

[This is very complicated since there are multiple levels of escaping needed: command-line, XML and regular expression. Let's say I want to run tests that include "some.thing" I need a regular expression match like test=~/some\.thing/ because . has special meaning in a regex unless escaped. But to get the \ in through the command=line, it needs to be escaped and, in some settings, the = must be either escaped or in quotes. So my argument becomes --where "test=~/some\\.thing/" ]

Try replacing \" with \&quot; - the XML encoding should really be done for you but isn't in 3.0. That's a fix in 3.0.1.

**Comment by BryanBarn** [comment]
I tried the &quot; as well but no change.

Adding escapes before the brackets throws an unhandled exception.

Adding escapes before the comma or dot make no difference.

I've also tried adding a .* to the end to try a wilcard, but no change.

I'm running out of ideas and time. I'm going to stick with V2.6.4 until I can return to this later.

All I want to do is replicate what works in V2.6.4:
 /run:ReportsItems.ReportsTests(\"Chrome\",False) /include:cat

**Comment by CharliePoole** [comment]
@BryanBarn I'm afraid you are flailing a bit here. :-) Some of the things you are "trying" have no possible reason to work. If you don't have time to help me replicate this, we can close it until somebody else runs into the problem. But if we could replicate it, then we would prevent others from experiencing the same frustration.

If you want to continue with this, I ask that you try the specific items that we would expect to work in TSL. Each time you try something, you should post the actual text of what you tried, rather than describing it in words. I should do the same thing, giving you specific filters to try.

So far, I have suggested only two ways to do this:

--test "ReportItems.ReportTests(\"Chrome\",false)"
--where "test==ReportItems.ReportTests(\"Crome\",false)"

I still haven't heard if you tried them and what the results were. These are working for me regularly on my own tests. I have seen that you used something like these, but with False rather than false. This is C#-inspired, so everything is case-sensitive.

I strongly suggest you **stop** trying various regular expressions. Getting a regex to match is **much** more complicated than a simple equals and your case is a very simple one, which should work.

As I said, if you prefer to close this, that's OK as well. You may also want to wait until 3.0.1 is released this evening and try again with that version. It could be that I have not been able to exactly match the version you are using in my experiments.

**Comment by BryanBarn** [comment]
I'm not flailing - I'm just trying to do what I am doing in V2.6.4.

I'll close this issue until later.

**Comment by CharliePoole** [comment]
"Flailing" was probably a bit harsh. Sorry. What I mean is I see you
spending effort trying a wide range of filters that are not related to your
problem. The intent of the --test option is that it work exactly like the
old -run option. --where "test==..." is intended to work exactly like
--test. Stuff like wild cards is never going to work, since we don't
implement it - as you can see from the docs.

When you are ready to try this again, make sure you use 3.0.1, which
resolves the known bugs with filtering. If your particular case doesn't
work, you can help us fix it by sticking with a single approach, at least
for the purpose of the issue.

Good luck!

**Comment by BryanBarn** [comment]
Thanks Charlie for your patience and getting back to us. I know you're busy.

Well timed with the update to this issue as I've just upgraded to V3.0.1 as well.

Trying the V2.6.4 /run:ReportsItems.ReportsTests(\"Chrome\",False) in the test=~/ReportsItems.ReportsTests("Chrome",False)/  doesn't find any tests.

So that's a break from V2.6.4. Does this count as a wildcard though? I don't think so (no *'s?).

So I've tried some regex expressions to make sure what I was entering on the command line should work with the test=~.

I've gone to url http://regexr.com/ and tried various expressions for what I'm after whilst entering into the text window the output from the --explore listing the tests that NUnit3 finds.

My tests have some parameterised test inputs as well as fixed inputs (which is why I want to avoid explicitly stating the tests to run in a file).

Using a cmd window with line length set to 512 to avoid any CRs the --explore returns:

ReportsItems.ReportsTests("Chrome",False).ReportsTest("Rep07","ITSUK-157","Surrey","LIVE","Cumulative TMA","A_Month_Ago","7:00","A_Month_Ago","11:59","AKS - Arriva","AKS GF - Arriva Garage GF","Not_Used","Not_Used","Early: true; Compliant: true; Late: true","AKS 3; AKS 34","Not_Used","Not_Used","Not_Used","PDF","false","150","Maintain Column Alignment: true; Page...","60.0","Formatted","Enable Separated Pages: false; Has Pa...")
ReportsItems.ReportsTests("Chrome",False).ReportsTest("Rep08","ITSUK-158","Surrey","TEST","Cumulative TMA","A_Month_And_A_Day_Ago","7:00","A_Month_And_A_Day_Ago","11:59","AKS - Arriva","AKS GF - Arriva Garage GF","Not_Used","Not_Used","Early: true; Compliant: true; Late: true","AKS 3; AKS 34","Not_Used","Not_Used","Not_Used","PDF","false","150","Maintain Column Alignment: true; Page...","60.0","Formatted","Enable Separated Pages: false; Has Pa...")
ReportsItems.ReportsTests("Chrome",False).Rep39
ReportsItems.ReportsTests("Chrome",False).Rep40
ReportsItems.ReportsTests("Firefox",False).ReportsTest("Rep07","ITSUK-157","Surrey","LIVE","Cumulative TMA","A_Month_Ago","7:00","A_Month_Ago","11:59","AKS - Arriva","AKS GF - Arriva Garage GF","Not_Used","Not_Used","Early: true; Compliant: true; Late: true","AKS 3; AKS 34","Not_Used","Not_Used","Not_Used","PDF","false","150","Maintain Column Alignment: true; Page...","60.0","Formatted","Enable Separated Pages: false; Has Pa...")
ReportsItems.ReportsTests("Firefox",False).ReportsTest("Rep08","ITSUK-158","Surrey","TEST","Cumulative TMA","A_Month_And_A_Day_Ago","7:00","A_Month_And_A_Day_Ago","11:59","AKS - Arriva","AKS GF - Arriva Garage GF","Not_Used","Not_Used","Early: true; Compliant: true; Late: true","AKS 3; AKS 34","Not_Used","Not_Used","Not_Used","PDF","false","150","Maintain Column Alignment: true; Page...","60.0","Formatted","Enable Separated Pages: false; Has Pa...")
ReportsItems.ReportsTests("Firefox",False).Rep39
ReportsItems.ReportsTests("Firefox",False).Rep40
ReportsItems.ReportsTests("InternetExplorer",False).ReportsTest("Rep07","ITSUK-157","Surrey","LIVE","Cumulative TMA","A_Month_Ago","7:00","A_Month_Ago","11:59","AKS - Arriva","AKS GF - Arriva Garage GF","Not_Used","Not_Used","Early: true; Compliant: true; Late: true","AKS 3; AKS 34","Not_Used","Not_Used","Not_Used","PDF","false","150","Maintain Column Alignment: true; Page...","60.0","Formatted","Enable Separated Pages: false; Has Pa...")
ReportsItems.ReportsTests("InternetExplorer",False).ReportsTest("Rep08","ITSUK-158","Surrey","TEST","Cumulative TMA","A_Month_And_A_Day_Ago","7:00","A_Month_And_A_Day_Ago","11:59","AKS - Arriva","AKS GF - Arriva Garage GF","Not_Used","Not_Used","Early: true; Compliant: true; Late: true","AKS 3; AKS 34","Not_Used","Not_Used","Not_Used","PDF","false","150","Maintain Column Alignment: true; Page...","60.0","Formatted","Enable Separated Pages: false; Has Pa...")
ReportsItems.ReportsTests("InternetExplorer",False).Rep39
ReportsItems.ReportsTests("InternetExplorer",False).Rep40

Putting that into the Text frame of the regex page along with other text (just to make sure it picks it up) the regex that seems to work is:
/(ReportsItems\.ReportsTests\(\WChrome\W,False\)\.(.*\s))+/

The \W seems to handle the quotes nicely too.

So this gives me confidence that I'm using the right regex.

Then running this on the Command line I get:
E:\Utils\NUnit\NUnit3\Visual Studio 2012_NUnit3>"C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" "%cd%\ReportsItems\bin\Debug\ReportsItems.dll" --where "test=~/ReportsItems\.ReportsTests\(\WChrome\W,False\)\.(.*\s))+/"
NUnit Console Runner 3.0.5813
Copyright (C) 2015 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
  CLR Version: 4.0.30319.18444

Test Files
    E:\Utils\NUnit\NUnit3\Visual Studio 2012_NUnit3\ReportsItems\bin\Debug\ReportsItems.dll

Test Filters
    Where: test=~/ReportsItems\.ReportsTests\(\WChrome\W,False\)\.(.*\s))+/


Unhandled Exception: System.ArgumentException: parsing "ReportsItems.ReportsTests(WChromeW,False).(.*s))+" - Too many )'s.
   at System.Text.RegularExpressions.RegexParser.ScanRegex()
   at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
   at NUnit.Framework.Internal.Filters.ValueMatchFilter.Match(String input)
   at NUnit.Framework.Internal.TestFilter.Pass(ITest test)
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.CreateChildWorkItems()
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork()
   at NUnit.Framework.Internal.Execution.WorkItem.RunTest()
   at NUnit.Framework.Internal.Execution.TestWorker.TestWorkerThreadProc()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()


Let me know what you think? 

I'm out for a few days so won't be able to get back to you until Tuesday next week (UK time).

Hope this helps, 

B

**Comment by BryanBarn** [comment]
Just noticed that entering the regex into this GitHub removes the backslash from in front of curved brackets.
/(ReportsItems\.ReportsTests<backslash>(\WChrome\W,False<backslash>)\.(.*\s))+/

**Comment by BryanBarn** [comment]
Also is there any way of using the /g regex operator for a global search?

Putting the /g at the end of the regex in NUnit gives an error of:
Unexpected token 'g' at position 64 in selection expression.

**Comment by oznetmaster** [comment]
NUnit 3 TSL uses the .NET Regex language syntax.  /g is part of the JavaScript regex syntax.  It does not exist in  .NET Regex laguage.  There are equivalent option in the .NET syntax.

**Comment by BryanBarn** [comment]
Finally got this to work.

I think NUnit3 is stripping out backslashes but the --where clause I needed was:
test =~ /(.star backslash.ReportsTests backslash ("Chrome",False backslash)).[backslash S]star/ and cat = /Parameterised_Reports/

To get NUnit to use this I had to add extra backslashes on the command line:
--where "test =~ /(.star backslash backslash.ReportsTests backslash backslash(backslash backslash backslash "Chrome backslash backslash backslash",False backslash backslash backslash)).[backslash backslash S]star/ and cat = /Parameterised_Reports/"

Note that the GitHub editor removes backslashes as well, which really doesn't help!!
Hence typing the words in.

Found this by looking at what was shown in the TestResult.xml and comparing to what I'd entered on the command line.

**Comment by CharliePoole** [comment]
If you want to use regular expressions from the command-line, you need to take into account...

 * which characters are stripped or have special meaning on your command-line (OS-dependent) and how to escape them so they get through.

 * which characters have special meaning in a regular expression and so need escaping.

 * which characters have special meaning to NUnit itself!

So it's not simple. The reason we added a lot of different options to the where clause is so you can pick one that works easily in each case, but that requires understanding each of the three levels.

In NUnit's case, the only special character you should need to worry about is the terminal quote. Since NUnit allows you to inclose the regex in /.../, "..." or '...' , you should either pick one that is not in your expression or escape it within the expression. I find that / works best for most cases.

In regular expressions, lots of things have special meaning. For example, '.' means "any character." To use it as a normal character, you must escape it. Consult .Net's regex documentation for more info, not a reference for using regex on some other platform.

A hint for posting on GitHub: put your expression inside a "fence", like this:

```
--where "test =~ /(.*\\.ReportsTests\\(\\\"Chrome\\\",False\\\)).[\\S]*/ and cat = /Parameterised_Reports/"
```

You probably figured out that (for example) regex needs `\.` for a litteral '.' but the command-line removes backslashes unless you double them. Hence `\\.` - three chars instead of one! Folks working with regular expressions all the time do this as a matter of course. Probably, this is not the easiest application for learning about them. :-(
