### ISSUE TITLE
Move various Assembly Info files under Properties for CF

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1106]
None of the .csproj files for the CF build were changed to matchthe "structure" of the other builds -  moving the CommonAssemblyInfo.cs and FrameworkVersion.cs file links into the Properties folder.

**Comment by rprouse** [comment]
I renamed this issue to reflect the task that needs to be completed.

**Comment by constructor-igor** [comment]
@rprouse please, could you understand me the issue. I want to try to implement it.
I find all AssemblyInfo.cs, CommonAssemblyInfo.cs and FrameworkVersion.cs files in Properties folders only.

**Comment by CharliePoole** [comment]
@constructor-igor The issue refers to the compact framework solution. I moved AssemblyInfo.cs into the properties folders but not the linked CommonAssemblyInfo.cs or FrameworkVersion.cs.

You would need VS2008 to do this. I don't recommend installing it merely for this fix but if you already have it, just open the NUnitCF35 solution and you'll see what is meant.

**Comment by chrischou** [comment]
@CharliePoole I happen to have vs2008 installed and got the changes in. However it seems I don't have permission to create a pull request. Can you please give me a hand? 
![image](https://cloud.githubusercontent.com/assets/429067/18032436/ea830a7a-6d58-11e6-81df-29846879dd1a.png)

**Comment by rprouse** [comment]
@chrischou it looks like you are using GitHub for Windows. I can't give you specific instructions for that since I don't use it, but I can help.

The problem is that you have cloned this repository which you don't have write permissions. That is why you cannot push your changes. You need to fork this repository into your account and clone your copy. You then push the changes to your copy and create the pull request from there.

Here is a good overview using the command line, https://gist.github.com/Chaser324/ce0505fbed06b947d962

A basic overview is as follows,

Fork NUnit,

![image](https://cloud.githubusercontent.com/assets/493828/18033933/c6944508-6cfd-11e6-8598-5a044a74fd30.png)

Clone your fork,

![image](https://cloud.githubusercontent.com/assets/493828/18033942/f2dd385e-6cfd-11e6-8515-d52b1a661628.png)

Create a branch, make your changes and push them to your fork.

Go back to your fork on GitHub, you should now see a yellow panel at the top of the repo with a Create Pull Request button. Just click it and fill in the info.

**Comment by chrischou** [comment]
Thanks heaps for the instruction @rprouse. Pull req re-submitted.

**Comment by ChrisMaddock** [comment]
Looks like #1772 closes this 😃
