### ISSUE TITLE
Different current/working folder in NUnit 3

### ISSUE THREAD

**Issue by jeremymeng** [nunit/nunit#1110]
With NUnit 2.6.4, the working directory is the same as the test assembly folder.  For example, `fileinfo.Fullname` would be something like `...\bin\Debug\test.log`.

```csharp
        [Test]
        public void TestFilePath()
        {
            var filename = "test.log";
            var fileinfo = new FileInfo(filename);
            Assert.AreNotEqual(filename, fileinfo.FullName);
        }
```

However with NUnit 3.0.1, it is `C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\TESTWINDOW\test.log` when running the test from the VS test explorer.  This could cause problems when the test tries to create a file.

**Comment by CharliePoole** [comment]
This is by design. NUnit no longer changes the current directory. See the breaking changes page in the documentation.

TestContext defines both WorkDirectory and TestDirectory for different purposes. You can create the path using one of those.

**Comment by yanekk** [comment]
I agree completely, but my case is slightly different. In my scenario I have to access current test directory not in the test itself, but in the addin which is used to create test cases. My class inherits from ITestBuilder and its logic is being run before actuall tests. Therefore, test context is not yet instatiated and calling TestContext.CurrentContext.TestDirectory or WorkDirectory throws NRE :-(. I kindly ask to rethink this issue as it breaks functionality from 2.x runner and it would be really helpful for me to leave it as it was before.

**Comment by CharliePoole** [comment]
Two levels of advice here, explained in more detail below:
1. Don't do this.
2. If you must, here's a workaround.

1. What you are asking NUnit to do is really not possible in the general case. When processing a single test assembly, we could change the current directory to that of the assembly while loading the tests. We could do it for multiple assemblies if each one were in a separate process. But a feature that only works correctly when used with a particular set of (supposedly orgthogonal) options is really not a very good design for usability.

When using the GUI, the current directory would be changed intermittently each time assemblies were reloaded. And even a partial feature would not survive the introduction of parallel assembly loading, which is something we have discussed for the future.

I think your best approach, if you can make it work, is to only perform operations at load time that do not require the directory. That would mean storing a file name or relative path when creating the test and expanding the information immediately before the execution of the test, using one of the interfaces that executes at that point in time. I don't know exactly what you are doing, but a possible choice might be IApplyToContext.

2. One place where the above will not work is if the actual names and number of the contained test cases depends on directory information.

In that case, I suggest you examine the logic by which NUnit determines the test directory and replicate it in your custom attribute. If you start tracing through the code of TestContext.TestDirectory, you will eventually arrive at the XmlHelper method that figures out the path. If you do this, you should plan on removing it once NUnit implements dynamic test cases, discovered at the point of execution rather than earlier.

Hope this helps.
