### ISSUE TITLE
Backwards compatibility for Atlassian Bamboo?

### ISSUE THREAD

**Issue by neal007** [nunit/nunit#1112]
I upgraded to NUnit 3.0.1 and it doesn't work with Atlassian Bamboo's NUnit Runner which drives the console.  I created a stack overflow post if anyone can help and/or consider a fix in a future update so Bamboo can work again.

http://stackoverflow.com/questions/34053704/how-to-run-nunit-runner-in-atlassian-bamboo-with-nunit-3

Thanks

**Comment by rprouse** [comment]
I have answered your question on StackOverflow. Hopefully that will point you in the right direction. I don't know Bamboo, but we have managed to get NUnit 3 running tests on most other CI systems including TeamCity, Travis, AppVeyor and CruiseControl.NET, so you should be able to modify your Bamboo configuration accordingly, likely by executing the nunit3-console directly instead of using a test task.

NUnit 3 is a major rewrite of NUnit 2 with many changes, including breaking changes. Supporting backwards compatibility would be difficult and we have no plans to do so.
