### ISSUE TITLE
Addin Replacement in NUnit 3

### ISSUE THREAD

**Issue by elv1s42** [nunit/nunit#1125]
Is there any way for full addin replacement from NUnit 2.6 to NUnit 3.0?

In NUnit 2.6 I could use **AddIns** with the following *interface*:
```csharp
public interface EventListener
  {
    void RunStarted(string name, int testCount);
    void RunFinished(TestResult result);
    void RunFinished(Exception exception);
    void TestStarted(TestName testName);
    void TestFinished(TestResult result);
    void SuiteStarted(TestName testName);
    void SuiteFinished(TestResult result);
    void UnhandledException(Exception exception);
    void TestOutput(TestOutput testOutput);
  }
```

Is it possible to replace all of this methods with **Action Attributes**? How can I get text output from the test?

**Comment by CharliePoole** [comment]
The old NUnit.Addins are not supported in NUnit 3.0, by design. See https://github.com/nunit/nunit/wiki/Breaking-Changes

For info on how to extend NUnit 3.0, see the docs at https://github.com/nunit/nunit/wiki under the heading Extending NUnit.

You could conceivably replace the TestStarted, TestFinished, SuiteStarted and SuiteFinished with an Action Attribute. Text output is avaialable at the time the test finishes.

I suggest you describe what you are trying to accomplish on the nunit-discuss list, where you should be able to get lots of advice on how to do it.
