### ISSUE TITLE
Call specific testcases

### ISSUE THREAD

**Issue by newinNbi** [nunit/nunit#1129]
if run in cmd. 

C:\Program Files (x86)\NUnit 2.6.4\bin>nunit.exe "path.nunit" /config:nameconfigfile /run:"name of test case"

the program cant identify the name of specific testcases to run
This is not working. it is supported for nunit or is not supported?

**Comment by CharliePoole** [comment]
This has worked for many years, and the code has not been changed, so it's probably due to not being able to predict the name that NUnit will give to the test.

Can you provide the specific test name and what you are entering?

**Comment by newinNbi** [comment]
Im using Calendar

**Comment by CharliePoole** [comment]
"Calendar" doesn't seem like the name of  a test case. I would expect something like
   some.name.space.classname.methodname(args)
or
   some.name.space.classname.alternatename

What is the test class and method you are attempting to run? If it's an individual test case, what are the args? Have you assigned it an alternate name?

**Comment by newinNbi** [comment]
I'm working with nbits files, this file have all test cases inside testsuite, it's a set of test cases

<test name="Calendar">
<system-under-test><execution><query><![CDATA[select * from tab1]]></query></execution></system-under-test>
<assert><equalTo><query><![CDATA[select * from tab2]]></query></equalTo></assert>
</test>

**Comment by CharliePoole** [comment]
From Google I learned that nbits files have something to do with Gallio. That's all I know about it. NUnit most certainly doesn't understand them.

To predict the name NUnit will give a test, you need to have the code for that test. If you have some code, just post an example of the test case method you are trying to execute.

**Comment by newinNbi** [comment]
Also i'm trying with this name "NBi.NUnit.Runtime.TestSuite.Calendar"
In theory Nbi and nbits files it's a complement for nunit,

this is an example just a compassion

![testcase](https://cloud.githubusercontent.com/assets/14896910/11730935/b2c8e7fe-9f5d-11e5-8f9d-bf1dbb868d02.PNG)

**Comment by CharliePoole** [comment]
What a horrible way to write tests! You have my sympathy. :-)

Is some actual C# code generated as a result of this file? If we had that, we could predict the name that NUnit will assign.

Alternatively, does this generate an assembly? You have to have some test assembly in order to run the tests with NUnit. What if you run all the tests using --labels:All? That should produce a list of every test name.

OTOH, if nbits doesn't generate tests for NUnit - if it merely simulates the running of multiple tests under a single (to NUnit) name - then no selection is possible. Using --labels:All would tell us which is the case.

**Comment by Seddryck** [comment]
NBi simulates multiples tests by creating TestCases from a parametrized Test decorated by a TestCaseSource.When building the ITestCaseData, the property TestCaseName is set to the name declared in the nbits file (here "Calendar").

@newinNbi: apparently it works on my side if I use ```C:\Program Files (x86)\NUnit 2.6.4\bin>nunit.exe "C:\Testing\UnitTests.nunit" /config:UnitConfig /run:NBi.NUnit.Runtime.TestSuite.Calendar```

@CharliePoole About the horrible way to write tests, it's just a question of point of view. When developing a C# solution, I like to write my tests in C# but when developing a BI solution, I want to remove as much as possible noise and I prefer to focus on the SQL, MDX and ETL tested and if I can avoid a C# compiler to write my tests I'm just happy.

**Comment by CharliePoole** [comment]
@Seddryck Actually, it's only with your post that I figured out that NBi is a "thing." All I could find in my first search was something relevant to Gallio. 

@newinNbi You should assume that all the developers of NUnit are really smart about NUnit, C#, etc. and totally ignorant of any 3rd party thing you happen to be using. It will usually be true. :-) 

In this case, you might have started out saying "NBi is a program that generates tests for NUnit to run!" Don't feel bad though - you are far from the first person to have made assumptions about our knowing of the existence of a third-party runner or test generator. And probably not the last either!

The NBi page has this "Your tests are written in xml by the means of a useful and intuitive syntax." Sorry, but I have to laugh at that. However, it's clear that the audience is different from the usual NUnit audience. The trouble is, when something doesn't work, you may have to explain what your problem is in NUnit terms.

**Comment by newinNbi** [comment]
@CharliePoole  I should have start there "NBi is a program that generates tests for NUnit!", Thanks for your help. I will modify the framework probably for do that i need it, its a little bit late for change to c#, but sometimes its better. Adventure with new code. 

@Seddryck Maybe i have something different because not work for me, but i will try to fix it, thanks for your help

**Comment by CharliePoole** [comment]
@newinNbi No problem... that was mostly intended as a warning to others who assume we know everything. :-) 

You should take the suggestion from @Seddryck as generic. Your own setup may generate a different name, but it will look somewhat like that. To see the exact names for all your tests, simply use the --labels option as described earlier.
