### ISSUE TITLE
Change nunitlite TextRunner to prioritze command line over provided test assembly

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1152]
Currently, in nunitlite, TextRunner gives priority to the passed in test assembly (if one is provided) over the command line in determining which test assembly to run.

It would seem that if there was a test assembly provided in the command line, it should be used instead of any test assembly passed to the TextRunner constructor.

**Comment by CharliePoole** [comment]
An alternative is to make it impossible to specify anything on the command-line when an assembly has been passed in. That's the approach I was planning when I wrote that there were some loose ends to clean up.

**Comment by oznetmaster** [comment]
Why?

**Comment by CharliePoole** [comment]
Because the calling assembly is only passed in by AutoRun and isn't intended for any other use. When using a self-executing test assembly, it makes no sense to specify a different assembly whose tests should be executed. That's the purpose of nunitlite-runner, which the user can easily use if it's desirable to execute assemblies from the command-line.

In my view, accepting an argument and then ignoring it is confusing to the user. For now, we are ignoring any InputFiles when an assembly is specified, but we should instead give a message.

**Comment by rprouse** [comment]
Nobody has picked this up and nobody else has asked for this so closing.
