### ISSUE TITLE
Report Invalid TestFixtures in Console Summary

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#1156]
Invalid TestFixtures are not currently reported in the "Test Run Summary" in the console. This can give a mis-leading summary showing that all tests were run and passed, but the overall result was still a fail.

From a quick look it appears that invalid fixtures are already tallyed up, just not displayed, so this may just be a view issue.

````
Test Run Summary
    Overall result: Failed
   Tests run: 7886, Passed: 7886, Errors: 0, Failures: 0, Inconclusive: 0
     Not run: 0, Invalid: 0, Ignored: 0, Explicit: 0, Skipped: 0
  Start time: 2015-12-23 16:17:07Z
    End time: 2015-12-23 16:18:39Z
    Duration: 92.372 seconds
````

**Comment by CharliePoole** [comment]
Are you using NUnit 3.0.1 both for the framework and console runner?

The intent is to display any invalid fixtures in the errors and failures report, although they do not contribute to the counts of tests run because NUnit has traditionally counted test cases. The overall failed result should be triggering an errors and failures report and it should contain an entry for the invalid fixture.

If it's not a question of using the latest version, try this: modify one of your test cases (in a different fixture) to force a failure. Does the report that displays now include the invalid fixture?

**Comment by ChrisMaddock** [comment]
Yes to NUnit 3.0.1.

Apologies, should have clarified - the error is shown under the "Errors and Failures" section. So is it intentional that this is then excluded from the Test Run Summary? I assumed the invalid tests should show under "Not run" in the Test Run Summary.

**Comment by CharliePoole** [comment]
Historically, NUnit has given a summary of test cases - originally test methods, before we had parameterized tests. As more fixture- and higher-level features were added, it became possible to have errors that were not counted at all.

For a while, we listed and counted all the test cases under a fixture with an error as failures. With 3.0, we decided that this gave us too cluttered a report. In addition, there are some kinds of errors, such as invalid fixtures, where it may not be possible to even identify the test cases.

Right before the 3.0 release, I implemented a compromise solution: we count test cases but we list higher level failures. The summary report only reflects the failure in the overall result.

**Comment by rprouse** [comment]
@ChrisMaddock is this still an issue? I would like to close confirm issues that don't have any progress.

**Comment by CharliePoole** [comment]
@rprouse This really isn't a confirm issue. In the discussion back in December we saw what was happening and @ChrisMaddock explained why it was confusing. I had the idea that we should look at the report at some future time to decide whether there is a need for another line in the summary report that shows errors and failures __not__ caused by a test case, but by the fixture itself. I really should have changed the description at that time.

Nothing has come of it so I don't think we need to keep this issue. We'll no doubt look at reporting formats at some future point anyway.

**Comment by ChrisMaddock** [comment]
Sure - it hasn't bothered me enough to fix it myself, so I guess that's as good a reason as any to close it! :-) Doing that now...
