### ISSUE TITLE
NUnit3-Console should disallow the combination of --inprocess and --x86, giving an error message

### ISSUE THREAD

**Issue by mdsolver** [nunit/nunit#1161]
I have ran into peculiar issue, that I feel is worth reporting.

Using NUnit.Console.3.0.1
Executing tests for example test library: Tests.DLL
With following arguments:
C:\Example\packages\NUnit.Console.3.0.1\tools\nunit3-console.exe C:\Example\Tests\bin\Release\QsehEiJfpnSP7yg5NCqm1zISM1sgEwqS.nunit --work=C:\Example --noresult --noheader --x86 --framework=net-4.0 --process=InProcess

QsehEiJfpnSP7yg5NCqm1zISM1sgEwqS.nunit is an autogenerated TeamCity .nunit project file, with contents:

```xml
<NUnitProject>
<Settings activeconfig="active" appbase="C:\Example"/>
<Config binpath="Tests\bin\Release" configfile="Tests\bin\Release\Tests.dll.config" name="active">
<assembly path="Tests\bin\Release\Tests.dll"/>
</Config>
</NUnitProject>
```

**Case 1:**

Tests.dll is compiled for AnyCPU and is a NET4.5 unit test library, 
Tests.dll references App.exe, which is compiled for x86 and is a NET4.5 WinForms application
App.exe references App.Core.dll, which is compiled for x86 and is a NET4.5 code library

Console runner exits with code -2 and error message:
*Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information*
There is no binding debug output.

App.Core.dll is now recompiled for AnyCPU, App.exe is still compiled for x86

Console runner works correctly and runs all tests.

**Case 2:**

Same as Case 1, except Tests.dll is compiled for x86

In this case, console runner fails with exception System.BadImageFormatException for Tests.dll, with binding error: Failed to complete setup of assembly (hr = 0x8007000b). Probing terminated.

Is this a bug or is console runner unable to load x86 compiled dlls?

**Comment by CharliePoole** [comment]
Your command-line uses two contradictory options.

The --inprocess option tells NUnit to run the tests in the same process as NUnit.
The --x86 option tells NUnit to run the tests in a 32-bit process. 

Since NUnit is compiled as IL only, it isn't possible to do both of these things. NUnit ignores the --x86 option and runs in process, which leads to a failure in your case.

In general, it's very difficult for the runner to predict whether a given set of options will fail. It can require a very detailed analysis of all the assemblies that will be loaded by the test.

Rather than doing that, we generally try to do the best we can with non-default options, following the options you enter on the command-line and, I'm afraid, allowing you to shoot yourself in the foot in some cases. For example, you can tell NUnit to ignore the fact that some assembly is compiled for .NET 4.5 and tell it to run it under .NET 2.0. NUnit will try to do it and will of course fail.

In this case, however, we could give an error message. That's because there seems to be **no** situation in which the combination of --inprocess and --x86 might be acceptable.

I'm completely changing the title of this issue to reflect what we need to do.

Your workaround is simply to remove the --inprocess option. Is that possible or is the the command-line also created for you by TeamCity? If so, there are most likely some options you can set to make it come out correctly.

**Comment by PeterAldur** [comment]
Hi CharliePoole.

Thank you for the analysis. I was not aware in-process behaves in such way. TeamCity runner config was inherited from NUnit 2 during upgrade. It appears NUnit 2 runner was also running tests in process, however the main process was started as x86 and thus it worked. 

I have followed your recommendations and found an appropriate TeamCity option, to run each test in separate assembly. By using this option, the generated command has no --inprocess flag and executes Case 1 correctly.

About Case 2, may I suggest another special error message, for when x86 unit test DLL is targeted with console runner using --inprocess flag on 64bit processor? This combination would also appear to be unsupported, as console runner seems to always JIT into 64bit if available. Alternatively it might be TeamCity issue, as --inprocess flag is added by their runner by default.

In either case, my build issue is solved. Thank you.

**Comment by CharliePoole** [comment]
Yes, the console runner runs in a 64-bit process on a 64-bit machine. If you run with all defaults, it runs each assembly in a different process. In that case, it checks the test assembly to determine whether a 32-bit process is needed. It also checks to find out the target framework under which to run the test. If instead you force the tests to run in the console process, it won't work if the tests need a 32-bit process.

If I understand you correctly, you are suggesting that we give an error message not only when --inprocess and --x86 are used together but also when --inprocess is used with an x86 assembly in the absence of the --x86 option. That makes sense and NUnit is already examining the assembly to ensure that the runtime is available, so we'll try to fix that case as well.

You should report this as a bug to the TC folks as well, since fixing this bug will end up causing an error message with their setup. They should never be using an --inprocess option without being told to do so by the user. In fact, any non-default options that specify how to load our run the test should depend on user input. The NUnit 3.0 default values are much better than those for NUnit 2.x and most things should just work using them.

**Comment by PeterAldur** [comment]
I have attached this suggestion to identical issue already reported at TeamCity issue tracker, available here:
https://youtrack.jetbrains.com/issue/TW-43636
