### ISSUE TITLE
A bug when using Assert.That() with Is.Not.Empty

### ISSUE THREAD

**Issue by Robot1que** [nunit/nunit#1171]
I've noticed some unexpected behaviour when I use the following code:

```
// EXPECTED - throws NUnit.Framework.AssertionException
Assert.That(null, Is.Not.Null);

// UNEXPECTED - throws System.ArgumentException
Assert.That(null, Is.Not.Empty);

// EXPECTED - throws NUnit.Framework.AssertionException
Assert.That("", Is.Not.Empty)

// UNEXPECTED - throws System.ArgumentException
Assert.That(null, Is.Not.Null.Or.Empty)

// UNEXPECTED - doesn't throw exception at all
Assert.That("", Is.Not.Null.Or.Empty)
```

Note that in all cases I would expect `NUnit.Framework.AssertionException` to be thrown.

I guess this is a bug and I'm wondering if the code marked with `// UNEXPECTED` has been unit tested?

**Comment by jhamm** [comment]
Based on my understanding, the last condition `Assert.That("", Is.Not.Null.Or.Empty)` is not an issue. That test roughly translates to:
````
var expected = "";
if (expected != null || expected == "")
{
	// all ok
}
else
{
	throw AssertionException();
}
````

If it were rewritten as `Assert.That("", Is.Not.Null.And.Not.Empty));`, the test passes. I can understand the confusion because it is similar to the string.IsNullOrEmpty(), which is how I also first read this test.

**Comment by Robot1que** [comment]
@jhamm oh yes, you're right! It should be `Is.Not.Null.And.Not.Empty`. But still there is a bug with throwing `System.ArgumentException` instead of `NUnit.Framework.AssertionException` when `null` is passed.

**Comment by CharliePoole** [comment]
@Robot1que It's not a bug, in that the constraint is defined to require non-null in its argument. As the message with the exception says "Requires non-null string... etc."

However, it's possible that was not a good decision on our part. Is there a reason to be passing a null to Empty?

**Comment by jhamm** [comment]
I am working on a PR that will allow a test to be written like this:
````
string actual = null;
Assert.That(actual, Is.Empty);

//or

Assert.That((string)null, Is.Empty);
````

If the tests were written as `Assert.That(null, Is.Empty)`, they would continue to fail.

With out the type information, .NET is not able to determine the type of the value. Ex:
`null` _(does not know you intend it to be a string)_
`(string)null` _(works because .NET sees this as a string that is null)._

**Comment by CharliePoole** [comment]
I get that. But I'm asking for a deeper reason... that is, why would you want to do that?

Clearly, you don't want to write `Assert.That(null, Is.Empty)` since that's silly. So what kinds of real-world situations come up where you want to test a null to see if it's an empty string?

**Comment by rprouse** [comment]
@jhamm, wouldn't it be more semantically correct to test that as `Is.Null.Or.Empty`?

**Comment by Robot1que** [comment]
Yes, if method knows the type than it correctly throws `NUnit.Framework.AssertionException`. And yes, usually actual value is a variable or property with a known type. So it was my mistake.

The only problem (or misunderstanding) left is that `Assert.That((string)null, Is.Not.Empty)` throws `System.ArgumentException`. Still I would expect to get `AssertionException` because logically the actual value doesn't match expectation and it's a requirement exception which means that maybe it should be handled by test-runner in a special way.

**Comment by jhamm** [comment]
My expectation is that Is.Empty and Is.Not.Empty would behave the same as `actual == string.Empty` and `actual != string.Empty`. These do not throw an ArgumentException and they return false then true.

When using the equalivent EmptyConstraint comparisons for the same inputs, both throw ArgumentException indicating that the null string cannot be compared.

**Comment by CharliePoole** [comment]
Except that Is.Empty is not the equivalent of equality. Compare these two statements:
```C#
Assert.That(null, Is.EqualTo(string.Empty));
Assert.IsEmpty(null);
```

The first matches the behavior of the `==` operator, just as the name of the constraint would suggest. The second is basically it's own thing, with it's own definition and it's own constraints. That's not to say we can't discuss what that definition ought to be, but just that it has nothing to do with equality.

EmptyConstraint is basically an adapter that selects one of three constraints: EmptyStringConstraint, EmptyDirectoryConstraint, EmptyCollectionConstraint. Of the three, only the first one is even close to an equality test. When designing the behavior of EmptyConstraint, I decided that it's argument should meet the needs of all the alternatives. Null definitely does not work for directories or collections. In case it's not obvious why, those two have to throw an exception because, if they simply failed, NotConstraint(EmptyDirectoryConstraint()) would succeed, possibly leading one to think that they have a non-empty directory when what they have is a null. This rule of throwing rather than failing is followed pretty uniformly throughout NUnit.

I grant that it is a reasonable option to allow a null __string__ to be handled correctly. But we can't uniformly accept null for all of the three alternatives for which Empty is used. Note that we don't know which of the three actual constraints will be used until after we have an actual value.

**Comment by jhamm** [comment]
I see you point. Right now I don't have an opinion either way, so I will defer to your vision on this one.

**Comment by CharliePoole** [comment]
One possibility would be to treat unqualified null as a string and do the comparison. But even that might be a misleading result if one didn't expect it.

I don't think we can really decide without some actual use cases. Since you would never actually use a manifest null as the actual value in any assertion (except to test assert), what would be an example of an actual use of Is.Empty, where an unqualified null should be accepted?

To be clear, I am OK with accepting a typed null and acting accordingly. It would have to be typed as a string, IEnumerable or DirectoryInfo to avoid an argument exception.

**Comment by CharliePoole** [comment]
@rprouse What's your take on how this ought to work? Should we move back to the PR and evaluate what it actually is doing?

**Comment by rprouse** [comment]
I don't like that `Assert.That((string)null, Is.Not.Empty)` throws `System.ArgumentException`, but I don't want to add behaviour where a null string is considered an empty string. 

So, IMHO, the above assert should fail by throwing an AssertException with a message something like "Expected an empty string but was null".

>My expectation is that Is.Empty and Is.Not.Empty would behave the same as `actual == string.Empty` and `actual != string.Empty`. These do not throw an ArgumentException and they return false then true.

Like @CharliePoole, I don't think this is a valid example. We are not testing equality, we are testing if the string is empty.

So, my call is that we should be able to pass in a typed null and get a valid failure, not an ArgumentException. I need to review the code again, but I think it is close to that now isn't it?

**Comment by CharliePoole** [comment]
Summarizing as I understand it:
 * Non-null actuals should work as they now do, including throwing an argument exception if they are not one of the supproted types.
 * Null typed as string should fail with an assertion exception.
 * Null typed as DirectoryInfo or IEnumerable should throw an  argument exception. This could be done in EmptyConstraint or in the two underlying constraints.
 * Any other nulls (including untyped) should result in the argument exception.

OK?

**Comment by Robot1que** [comment]
I see the point made by @CharliePoole and I agree. My `Assert.That((string)null, Is.Empty)` test is not a real-world use case.

So after @jhamm explained to me that I have to use `Is.Not.Null.And.Not.Empty` instead of `Is.Not.Null.Or.Empty` I have no complains any more.

**Comment by rprouse** [comment]
We have closed the PR #1240. Should this issue be closed too? Is there anything outstanding in this issue that anyone thinks should be addressed?

**Comment by jhamm** [comment]
I think this can be closed.
Thanks!

**Comment by CharliePoole** [comment]
Based on code inspection, one item in my summary above is not satisfied:

 * Null typed as string should fail with an assertion exception.

I believe it currently throws an ArgumentException.

Do we want to fix this?

**Comment by jhamm** [comment]
I think that #1240 satisfies the last item.

**Comment by CharliePoole** [comment]
I'll look at the code again tomorrow.

**Comment by CharliePoole** [comment]
Since the original PR is closed and the branch deleted, I created a new branch and PR to resolve what is left of this, pulling some code from the old one. I used @jhamm 's idea of testing the type parameter instead of the argument, to detect that a null typed as a string has been passed in.
