### ISSUE TITLE
No ICommandDecorator interface

### ISSUE THREAD

**Issue by Loydik** [nunit/nunit#1178]
Hi, I've been upgrading our project to NUnit 3.0, and we need to replace our Jira addin(previously implemented as TestDecorator) with a custom attribute.
Here, in wiki, you say "An attribute that implements ICommandDecorator is able to contribute to add additional commands to be executed when running the test". However, this interface is nowhere to be found!
We need a way to ignore tests which have an issue opened for them in Jira, and previously we were able to achieve this using ITestDecorator and setting test.RunState = RunState.Ignored.
Now, we do not have a way to efficiently achieve this.

Link to wiki: https://github.com/nunit/nunit/wiki/Addin-Replacement-in-the-Framework#testdecorators

**Comment by rprouse** [comment]
I will look at the docs later and check if they are correct, but in the meantime, take a look at the IgnoreAttribute in the NUnit Framework. It has a new property Until that ignores tests until a certain date. You can copy the code for the IgnoreAttribute to create your own attribute that ignores the test if there is an issue open. If you would prefer the test to not show up as a warning, just take a look at the way the ExplicitAttribute does it.

**Comment by Loydik** [comment]
Thank you very much for a reply, it is a nice hint! :)
However, there is still an error in documentation, so please take a look at it. Thanks!

**Comment by CharliePoole** [comment]
@Loydik Actually, the page in question was headed "DRAFT IN PROCESS."  In case that was not strong enough, I changed it to "OUT OF DATE - WORK IN PROCESS." :-)

I'm sorry to say that our extensibility documentation is incomplete. Various pages reflect different stages of development. I have tried to put warning notices on all of them for that reason but, of course, the best solution is to complete them.

Since you used a decorator before, it's understandable that you would look at that first. However, since all you want to do is to ignore the test, you should use the IApplyToTest interface. That allows the internal representation of the test to be modified, causing it to be skipped.

**Comment by Loydik** [comment]
Thanks for the response!
I have tried IApplyToTest interface, but for some reason it caused some bugs in the NunitTestAdapter, tests just started disappearing. Maybe because I forgot to mention IgnoreReason,  but that's another story and I am going to try again soon. Thank you!

**Comment by CharliePoole** [comment]
IgnoreReason is required and it's presence may be assumed in some places.
An extension can get around the requirement, potentially causing an issue.
Of course, the code  should really not make assumptions for that very
reason.
