### ISSUE TITLE
NUnit 3 classic assertions are not binary compatible with NUnit 2

### ISSUE THREAD

**Issue by stephen-swensen** [nunit/nunit#1180]
For example, NUnit 2 has a method like
```
Assert.True(bool condition, string message); 
```
Whereas NUnit 3 only has
```
Assert.True(bool condition, string message, params object[] parms);
```
While the NUnit 3 version provides syntactic backwards compatibility with the C# compiler, it does not provide binary compatibility. i.e. programs that try to load `Assert.True(bool condition, string message);` via reflection will fail. See https://github.com/SwensenSoftware/unquote/issues/120 for example.

**Comment by CharliePoole** [comment]
It may be that I don't quite understand what your issue is. However... 

NUnit 3 is **not** intended to be backward compatible with NUnit 2. That's why it's a major version change. It does attempt to be "close enough" for users to easily modify their tests but there are lots of changes, even at the C# level. See the Breaking Changes page in the docs.

What is the use case you are trying to allow for? Specifically, it sounds as if you want to load code by reflection without regard to whether it is NUnit 2 or 3. Since NUnit itself can't even run V2 and v3 tests using the same code, this seems like a bit of a stretch.

Users (test writers) can get away with treating NUnit 3 as "almost compatible" with 2. If you are writing extensions or utilities that work with NUnit, you really need to treat it as a separate framework. We do that in the engine by looking at the major version component of the assembly reference.

I'll leave this open for a bit to give you a chance to respond.

**Comment by stephen-swensen** [comment]
Hi @CharliePoole - yes I understand and appreciate that NUnit 3 cannot be expected to be completely backwards compatible with NUnit 2, however I wanted to bring this particular case to your attention in case there was some appetite to improve the story even further.

Specifically, Unquote would have been blissfully unaware of the differences between v2 and v3 had v3 implemented `Assert.True(bool condition, string message)` (since yes it would be ideal if it could load code by reflection without regard to NUnit version, at least until I am able to implement v3 optimized code and Unquote users are able to upgrade in turn). 

I am OK with closing this issue if you don't see this case as particularly compelling. And perhaps lesson learned I need to be stricter with assembly versions in Unquote's use of reflection here.

**Comment by CharliePoole** [comment]
I looked at unquote only briefly. I'm guessing that your DSL is implemented by means of reflected calls into NUnit's assertions. Is that the case? If so, it's certainly not a use case we ever planned on! 

I would lean towards closing this myself. What do you think @rprouse ?

**Comment by rprouse** [comment]
I also lean towards closing this. We never stated that 3.0 would be compatible in any way with 2.6 other than migration of test suites should be as painless as possible. 3rd Party runners were always expected to have to make changes and distinguish between the two frameworks. Unquote is close enough to a 3rd party runner that I feel it falls into that bucket. @stephen-swensen, if you need any help adding NUnit 3 support, just let us know.

You state that Unquote would have been blissfully unaware of the differences, but I expect that if you go through the asserts, you will likely find more differences. Maybe Unquote just isn't using those asserts.

**Comment by stephen-swensen** [comment]
Thanks for consideration.

To clarify, Unquote is designed to be decoupled from any particular assertion framework. It uses F# quotations to capture expression trees and evaluate them via plain-old .NET reflection. Then, if a test framework like NUnit (or xUnit.net, etc.) is detected, it uses a single appropriate assertion method (like `Assert.True`) to convey the result of the quotation evaluation (including a rich step-by-step reduction message decompiled from the quotation meta-data) to the test runner being used so that the assertion message is presently cleanly to the user. If no assertion framework is detected, then Unquote just throws an exception to convey the failure message (which typically works for any exception based test framework, but the messaging is not as clean).

So the extent of Unquote's dependency on NUnit is literally "if assembly 'nunit.framework' is loaded into the current app domain, use Assert.True(boolean, string) to convey assertion failures". I should be able to tweak that pretty easily to support both NUnit 2 and NUnit 3.

Anyhow, no worries, I do appreciate your time and prompt consideration.
