### ISSUE TITLE
BadImageFormatException when no extensions and unmanaged dll in directory

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#1181]
If there is no .addins file in the test directory, the ExtensionService looks though all dlls in that directory for the ExtensionAttribute. If there is an unmanaged dll in the directory, a BadImageException is thrown. (Running under the console runner)

Workaround is to include a blank .addins file.

````
System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
   at Mono.Cecil.PE.ImageReader.ReadOptionalHeaders(UInt16& subsystem, UInt16& dll_characteristics)
   at Mono.Cecil.PE.ImageReader.ReadImage()
   at Mono.Cecil.PE.ImageReader.ReadImageFrom(Stream stream)
   at Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at NUnit.Engine.Services.ExtensionService.FindExtensionsInAssembly(String assemblyName)
   at NUnit.Engine.Services.ExtensionService.FindExtensionsInDirectory(DirectoryInfo startDir)
   at NUnit.Engine.Services.ExtensionService.StartService()
   at NUnit.Engine.Services.ServiceManager.StartServices()
   at NUnit.Engine.TestEngine.NUnit.Engine.ITestEngine.get_Services()
   at NUnit.ConsoleRunner.ConsoleRunner..ctor(ITestEngine engine, ConsoleOptions options, ExtendedTextWriter writer)
   at NUnit.ConsoleRunner.Program.Main(String[] args)
````

**Comment by rprouse** [comment]
Why is there a 32 bit assembly in the addins directory? I am inclined to close this because we cannot anticipate handling everything someone might drop into the addins directory. Can you explain your use case?

**Comment by ChrisMaddock** [comment]
Hi,

There is no addins directory - the ExtensionService appears to search the directory of the executing assembly. Looking at the nuget package, it's only seems to be redirected to an addins directory by the content of the .addins file?

We are referencing the nunit3-console.dll and copying local, so it is in the same directory as all our other dlls. I do however seem to have been too quick to jump to the 32-bit conclusion, Mono seems to be able to handle those. (Which makes sense.) Will close this temporarily until I can pin down exactly what's unusual about the particular dll causing the crash.

**Comment by ChrisMaddock** [comment]
@rprouse - An update: I believe the crash is caused by an unmanaged dll, not a 32-bit dll, apologies my mistake there.

To clarify, the dll is simply in the same directory as nunit-console.exe at the time of running, as are all other dlls for the project. It isn't used by the tests at all. Debugging this, I came across the NUnitConfiguration.AddinDirectory property - which appears to be unused? That references an addins directory, although as said - the current ExtensionService appears to use the executing directory, and paths to /addins/ are specified in the .addins file.

**Comment by CharliePoole** [comment]
Yes, that's how it works. The directory containing the engine assembly is found via GetExecutingAssembly. It is searched for any files matching *.addins and those files are used to find extensions. If no such file is found, the directory itself is searched for files of type .dll.

The search is recursive. That is, the addins file might point to some other directory, which is in turn searched using the same logic as the starting directory. It's actually at this point that examining all dlls in the directory becomes particularly useful. A .addins file can simply point to a directory and all assemblies in it will be treated as extensions.

We probably need to make this more bulletproof. That said, a failure at this point normally would indicate an error in how NUnit is installed. By copying certain NUnit assemblies, you are in effect replacing our installation logic with your own. Can you explain why you are doing this?

BTW, we ran into this issue before with the VS adapter. The adapter now includes an empty *.addins file to avoid the search.

We might consider changing the initial default to look for an addins directory rather than searching the executing directory. If we do that, subsequent iterations should still follow the existing logic.

**Comment by CharliePoole** [comment]
@ChrisMaddock Regarding your update: To be clear, it's the location of nunit.engine.dll that is relevant, not that of nunit3-console.exe. In the normal installation, these two directories are the same, but I don't know how it is as you have copied the assemblies.

If the unmanaged dll is not used by your tests, where is it coming from? Not that we should be crashing upon encountering it, but it seems a bit strange. Since the crash occurs in Cecil, I think that this is an instance of issue #1009.

NUnitConfiguration.AddinDirectory is dead code left over from NUnit V2, which required all addins to be in one directory. I'll get it out of there.

**Comment by ChrisMaddock** [comment]
Hi Charlie,

Perhaps we are using the dll's in a way other than strictly intended then. Our intention was to turn our test project into an executable which would run the console on itself, and additionally not require an installed version of NUnit. To do this, we pulled the NUnit.Console Nuget package, and referenced nunit.console, nunit.engine and nunit.engine.api from the project. These are then copy-local'd to bin on build, and the tests run within the program through `Nunit.Console.Program.Main(args)`. (So both nunit3-console.exe and nunit.engine.dll are in /bin/, along with the other dll's required for the project)

Should I take from your reply that this sort of set-up isn't supported, and we should instead be referencing an installed version? Regarding #1009 - it sounds like this should be wrapped in a try/catch anyway, although if there is the assumption that there are no external dll's in NUnit directory, I can see why this wouldn't be necessary.


> If the unmanaged dll is not used by your tests, where is it coming from? Not that we should be crashing upon encountering it, but it seems a bit strange.

Sorry, I've added additional confusion here. In our specific case, the unmanaged dll was an unused reference so we could just remove it - but we thought the bug (or perhaps not, as it seems.) was still worth a report.

**Comment by CharliePoole** [comment]
Let's just say it's not a use case we ever envisioned. Whether it's actually supported, time will tell. :-)

Do you require any addins? Assuming not, you may want to consider using NUnitLite. There are two ways to use it...

1. Reference both nunit.framework and nunitlite from your executable test.
2. In your main, call into NUnitLite - see the docs for the call to insert.

That's it. No console, no engine. The limitations are that you need a single test assembly and you lose everyting the engine gives you: addins, running out of process, combining results from several assemblies, opening nunit projects,... those are the main features.

**Comment by ChrisMaddock** [comment]
Thanks Charlie. In our case, we require the nunit-v2-result-writer.dll..however, if we create an .addins file to reference that, that of course prevents the crash!

We'll have a think about how we're going to handle this at our end, if there isn't a 'standard-method' to achieve what we're aiming for! Thanks for your advice.

**Comment by dten** [comment]
I tried it with NUnitLite and it works just fine :) `format=nunit2` seems to work with it
also the dll was not unused, it's just `PInvoke`

**Comment by CharliePoole** [comment]
The only remaining problem seems to be that we aren't handling the exception. Since that's covered by #1009 to which this one is linked, I'm closing this.
