### ISSUE TITLE
Visual Studio Test Runner does not discover tests when using NUnit 3.0.5813.39031

### ISSUE THREAD

**Issue by urbanhop** [nunit/nunit#1182]
As of today, when using the nuget package of nunit 3 and the current test runner extension, tests are not discovered.

(With Resharper, tests are discovered after customizing the version of NUnit3)

**Comment by OsirisTerje** [comment]
Try the NUnit3 test adapter  https://visualstudiogallery.msdn.microsoft.com/0da0f6bd-9bb6-4ae3-87a8-537788622f2d 
The adapter for NUnit2 does not work with NUnit 3

**Comment by CharliePoole** [comment]
@urbanhop Were you using the original adapter? (nunit-vs-adapter)

If so, there should be a reasonably clear message about this in the output window. Let us know if it needs to be fixed.

I'm closing this since it's not an NUnit issue. This is the repository for NUnit. The repository for the NUnit 3 VS adapter is at https://github.com/nunit/nunit3-vs-adapter

**Comment by urbanhop** [comment]
i used the nunit3 adapter. but this is certainly an issue there. (the link to the package info of the adapter led to this repo, will mention this there as well.)

btw i find nunit 3 very well designed, excellent.

thank you!
