### ISSUE TITLE
What language level is supported?

### ISSUE THREAD

**Issue by alfeg** [nunit/nunit#1183]
I have look for `nunit/dev` and there is statement, that 

> In coding for NUnit, we limit ourselves to C# 3.0 features. We want to keep the code buildable by folks who don't necessarily have the latest compilers.

As far as I can see it's not true anymore, i.e. async/await usage is from language version 5.

It's possible to limit language level in project settings, we have done this to prevent folks from use of C# 6 language features until all our CI servers not updated. 

Should `nunit` project explicitly define what language version it's allowed to use?

**Comment by CharliePoole** [comment]
This definitely needs re-writing because it's much more complicated than just setting a single level. The dev wiki is used for all the projects under the nunit organization, not just nunit itself and that statement doesn't apply to all projects.

Neither does it apply to all parts of NUnit. Some features are only present in certain builds. I should point out, however, that NUnit does **not** use async/await in any of it's code. It **supports** async/await in the code that is being tested and certain NUnit tests therefore have to use it.

I'll see if I can come up with something that is not too complicated, but which describes the actual situation. One benefit of a simple, absolute statement like we have is that it works for all cases. When we were less absolute, users often introduced wrinkles to the code based on personal preference. A great examlpe is the use of Linq in code that has to be built for .NET 2.0. When a user does this, they are not normally working in 2.0, so they don't see a problem.

BTW, we also try to keep the code as unified as possible. So, using the Linq example, we don't create conditional code that uses Linq in one build and a different approach in another build. Rather, we use the lowest common denominator of code features in all cases. This can make it a bit annoying to work on the NUnit code, but it's part of what keeps it portable.

@rprouse This should really be on the dev wiki repo rather than NUnit, but since it's here I'll deal with it here outside of any milestone to avoid confusion.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/docs #70](https://github.com/nunit/docs/issues/70) via [**ZenHub.io**](https://www.zenhub.io/)
