### ISSUE TITLE
Custom value formatter for v3 via MsgUtils

### ISSUE THREAD

**Issue by et1975** [nunit/nunit#1196]
I'm trying to implement custom value formatting for fsprojects/FsUnit#82 and looking at MsgUtils that seems to be the place to get it working for all constraints.
I'd like to be able to inject a custom formatter that, if present, would be invoked from FormatValue(); something like:
```
    public static Func<object,string> CustomValueFormatter;
``` 

Edit: just noticed MsgUtils is internal... looking for alternatives then.

**Comment by rprouse** [comment]
Just because MsgUtils is internal doesn't mean we couldn't provide a method for you to inject a formatter. Can you explain more about how you would want to reformat messages and why it is needed for FsUnit?

One thing that you need to be aware of is that NUnit needs to compile back to .NET 2.0, so you won't be able to use a Func, but will need to create a new delegate.

I am tagging this as an idea for discussion and design.

**Comment by et1975** [comment]
F# has a few types (records, tuples, discriminated unions) that from .NET perspective are just objects. These types however have nice support when F#'s own [printf mudule functions](https://msdn.microsoft.com/en-us/library/ee370560.aspx) are used to format the values.

So, for example, asserting the equality of two records of type MyRecord (all of the above mentioned types are equattable in F#, btw) with default .NET formatting will tell me something like "[MyRecord] is not equal to [MyRecord]", while formatted with printf will be a lot more informative: "{field1:10} is not equal to {field1:20}".

In general though, you'd be able to address large group of "this format is not to my liking" scenarios, like #1004 with a pluggable formatter.

**Comment by rprouse** [comment]
That sounds reasonable. I would accept a pull request for that, but first I would like to get an idea on how you would propose adding this. I am changing the milestone to backlog and the status to design.

Instead of a Func/delegate what about an interface for a custom formatter with a format method and a property or method that specifies the `Type` that the formatter handles? End users could implement the interface and pass the `Type` to NUnit which would instantiate it and call it where needed. This type could be passed in an assembly attribute or NUnit could also find all implementations of the interface when it explores the tests.

Another option could be an assembly attribute that takes a delegate and a .NET type that the delegate should format.

**Comment by CharliePoole** [comment]
@rprouse Alternatively, we could leave the feature out of the .NET 2.0 build.

**Comment by et1975** [comment]
I'd argue that interface+supported types would be great for introspection and dynamic lookup, but also an overkill for the use case.

The custom delegate type compiles just fine for .NET 2.0, and it's composable and statically verified if one wanted to include multiple formatters, chain-of-responsibility style.
How about something like this...

Given the delegate types:
``` csharp
    public delegate string ValueFormatter(object val);
    public delegate ValueFormatter ValueFormatterFactory(ValueFormatter next);
```
with MsgUtil having an aggregator in MsgUtil:
``` csharp
    static ValueFormatter ValueFormatter = val => string.Format(Fmt_Default, val);
    public static void AddFormatter(ValueFormatterFactory formatterFactory)
    {
        ValueFormatter = formatterFactory(ValueFormatter);
    }
```
one could add any number of formatters to the pipeline, like this:
``` csharp
   MsgUtils.AddFormatter(next => val => (val is String) ? "val" : next(val));
```

**Comment by CharliePoole** [comment]
Functional thinking! Cool!

**Comment by rprouse** [comment]
It may be overkill for this use case, but this might be useful for NUnit itself. I could see us migrating all of our formatters out to a custom formatter per type while still allowing end users to override or add their own formatters.

So, as long as users can add to an already existing chain of formatters, I would be cool with it.

**Comment by oznetmaster** [comment]
Perhaps while massive changes are being made to MsgUtils, #1004 can be addressed at the same time?

Just need to add FormatDateTimeOffset method and the appropriate factory call for it to add it to the formatter chain.

**Comment by CharliePoole** [comment]
Usually, we do better with many small issues and PRs but that one might be small enough to slip in here. This PR already combines two things, but the implementations were mutually influencing each other so I decided to keep them together.
