### ISSUE TITLE
Apartment on assembly level broken

### ISSUE THREAD

**Issue by radiy** [nunit/nunit#1208]
test below fail on nunit 3.0.1

```
using System;
using System.Threading;
using NUnit.Framework;
[assembly:Apartment(ApartmentState.STA)]//broken

namespace ClassLibrary2
{
	//[TestFixture, Apartment(ApartmentState.STA)] - works
	[TestFixture]
  public class Class1
  {
		[Test]
		//[Apartment(ApartmentState.STA)] - works
		public void Apartment()
		{
			Assert.AreEqual(ApartmentState.STA, Thread.CurrentThread.GetApartmentState());
		}
  }
}
```

**Comment by CharliePoole** [comment]
I stepped through the code to confirm this. What happens is that the OneTimeSetUp for the assembly runs in the STA, but every child test runs in the MTA because ApartmentState is not one of the properties we pass along in the TestExecutionContext.

This will be a critical problem once we implement parallel test case execution. For now, it's not so high a priority because it only applies to specifications of the ApartmentState at the assembly or SetUpFixture level.

The resolution is probably to handle this as we do ParallelScope. Alternatively, we could define an entire category of properties, which pass "down" through the TestExecutionContext. My tendency would be to first check if there are other such attributes and only generalize on the third occurence.

**Comment by CharliePoole** [comment]
Fixed by PR #1345

**Comment by rinubaby** [comment]
[assembly: Apartment(ApartmentState.STA)] is broken in 3.8.0 and 3.8.1, it seems to work in 3.7.1.

**Comment by ChrisMaddock** [comment]
@rinubaby - This is being tracked here: https://github.com/nunit/nunit/issues/2426

**Comment by rinubaby** [comment]
Thanks!
