### ISSUE TITLE
confusing simplifiations brought by AssertionHelper

### ISSUE THREAD

**Issue by MSK61** [nunit/nunit#1211]
This isn't exactly a bug, but probably rather a nuisance. Consider this example:

```
class TestClass : AssertionHelper
{
    [Test]
    public void RunTest()
    {
        Expect(() => 5, InstanceOf<int>());// Here I mean Is.InstanceOf.
        Expect(() => { throw new Exception(); }, InstanceOf<Exception>());// Here however I mean Throws.InstaceOf.
    }
}
```

Intellisense would happily suggest InstanceOf in both cases, and I'd probably be fooled into thinking that intellisense got my intentions right for Throws.InstanceOf case until I too late find out while analyzing test failures. Of course if I carefully read the description accompanying intellisense hint I might notice, but who cares to read the description if you just find what you're looking for? :grinning:

I know that any regressions in this feature will definitely cause existing code to break, but I just wanted to raise this issue for the moment. Maybe there'll be some decent solution one day to alleviate the confusion.

**Comment by CharliePoole** [comment]
I checked and determined that the last substantive change to AssertionHelper was in 2009! That means it actually predates Throws and ThrowsConstraint.

Because it's not much used (based on frequency of questions and issues) and because I don't use it myself, the class doesn't get much attention. I debated whether to drop it from 3.0 but in the end retained it, essentially unchanged since NUnit 2.4.

Essentially, support for throws would be an enhancement, probably implemented by adding a new member. Suggestions are welcome, although it would be a rather low priority. I'm going to start another issue to discuss whether we should retain AssertionHelper at all.

**Comment by rprouse** [comment]
@MSK61, since AssertionHelper is a forgotten class that isn't being kept up to date, we are discussing removing it in issue #1212.

You brought this to our attention, so you are probably a good person to ask. Are you using AssertionHelper extensively in your tests? Do you think we should maintain it and bring it up to date, remove it, or move it out to a community maintained package separate from NUnit?

**Comment by MSK61** [comment]
@rprouse please see my comment there https://github.com/nunit/nunit/issues/1212#issuecomment-175823298.

**Comment by ChrisMaddock** [comment]
AssertionHelper has now been removed from the framework. Closing...
