### ISSUE TITLE
Unable to run .net core project tests via nunitlite in TeamCity

### ISSUE THREAD

**Issue by dtretyakov** [nunit/nunit#1224]
Currently `--teamcity` option is not recognized by nunitlite runner when running tests in [.net core project](http://www.alteridem.net/2015/11/04/testing-net-core-using-nunit-3/). It was removed for some reason in the issue #611.

Could you please explain what was the root cause to do it and is it possible to return it back?

**Comment by rprouse** [comment]
The teamcity command line option was removed because it didn't do anything in nunitlite. This sounds like a valid use for the option though, so it could be added back and then plumbed through. We would need to to walk through the code to make sure nothing is missing in the portable build that would be required.

I am going to mark this as an enhancement since it was never supported in the past.

Isn't there a workaround? We used to use TeamCity without any extra command line option and we manage to test in other CI services without special integration. Doesn't the teamcity command line option just provide better integration with TeamCity?

**Comment by dtretyakov** [comment]
@rprouse, this option, which is available in nunit, enables tight integration with TeamCity. [It converts](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/nunitlite/TeamCityEventListener.cs) test runner messages to the TeamCity's [build messages](https://confluence.jetbrains.com/display/TCDL/Build+Script+Interaction+with+TeamCity) which allows to keep statistics and perform test analysis.

**Comment by rprouse** [comment]
Sure, I just wanted to make sure I understand the priority of this issue. It doesn't block running the tests in TeamCity, but it provides a much better experience.

**Comment by CharliePoole** [comment]
If we implement #1225 this could be affected. 

I'd like to see us get out of the business of supporting 3rd party software directly, while giving users a way to contribute such support. Extensions allow that for the engine, but currently not for nunitlite.

**Comment by roji** [comment]
+1 for this, am also currently using nunitlite to run tests for CoreCLR, and being able to communicate test results to TeamCity is important.

**Comment by dmitriyse** [comment]
+1 this is really required feature. There no any option with out this feature to Analyze CoreCLR test results in TeamCity. Also TestResult.xml generated by NUnitLite is not recognized by TeamCity (9.0.1).

**Comment by CharliePoole** [comment]
@dmitriyse That "also" is potentially a pretty big deal! Perhaps we need a separate issue in which you outline what the problem is.... that is, unless it's that you are using the default nunit3 output format. If you are using nunit2 format and TC doesn't recognize it, an explanation of the exact problem may get this solved.

In general, features were originally left out of portable nunitlite for two entirely different reasons:

1. The feature could not be supported in portable. In that case, not much to do.

2. I didn't imagine the feature would be used in portable or, in some cases, in any build of nunitlite. If something is only missing because of a failure of my imagination, we should revisit it. :-)

**Comment by dmitriyse** [comment]
I created TeamCity feature requirest https://youtrack.jetbrains.com/issue/TW-46195. Possibly JetBrains guys will solve the problem from their side.

But ability to use different output reportes (for example TeamCity) is very usefull feature. Also some one guy already have some code: https://gist.github.com/JohannesRudolph/5433368.
I cannot figure out how i can plug this code into toolset. If it not difficult, could you provide some instruction?

**Comment by CharliePoole** [comment]
I don't see the problem. We already have code in nunitlite similar to the gist you posted. I just enabled it for the portable build. I'll find and post the issue reference.

WRT the XML format, it's a question of understanding the problem. NUnitlite supports the same basic formats as does the console runner.  Please explain what difference you are referring to.

**Comment by CharliePoole** [comment]
See #1681

**Comment by dmitriyse** [comment]
Thank's for your help. I will wait same improvement for .netstandard.

In attachments two nuint.line and nunit TestResult.xml versions for the same test code.
[TestResult.zip](https://github.com/nunit/nunit/files/369494/TestResult.zip)

**Comment by dmitriyse** [comment]
Hi guys. I recently published specific version of dotnet-test-nunit package - https://www.nuget.org/packages/dotnet-test-nunit-teamcity/3.4.0-beta-3
it has  --teamcity option
also you need to modify project.json like this
```json
{
  "version": "0.1.0-*",
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.1.0"
    },
    "Microsoft.Net.Test.Sdk": {
      "version": "15.0.0-preview-20161216-01"
    },
    "dotnet-test-nunit-teamcity": "3.4.0-beta-3",
    "NUnit": "3.5.0"
  },
  "testRunner": "nunit-teamcity",
  "frameworks": {
    "netcoreapp1.1": {
      "imports": "dnxcore50"
    }
  }
}

```

**Comment by mikkelbu** [comment]
@rprouse Should this issue be closed? As far as I can tell one is able to pass `--teamcity` to nunitlite now, also it seems that this issue is dated.

**Comment by rprouse** [comment]
Nobody has asked for this in three years, so yes...
