### ISSUE TITLE
Real-time test progress information

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1226]
It is easy to track the progress through the tests (start/finish)  by using the methods of the ITestListener interface.

However, there seems to be no mechanism to allow a single test to provide real-time progress (e.g. percent completed) information to something like an ITestListener.

It would seem useful to add a property to the TestContext such as PercentComplete that a test could set while it was running.  Each call to the setter would in turn call a TestProgress method on the ITestListener interface, with an ITestProgress as the argument (which would contain appropriate information about the test - perhaps just ITest + Progress).

This would seem useful for the GUI, and for other runners as well.

**Comment by oznetmaster** [comment]
My CF build is used on some pretty slow devices, and a single TestMethod can run for a long time (I have some test assemblies where running all the test can take > 24 hours!).

It has been requested that my GUI be able to show the progress of each TestMethod if the test is written to do so.

For this reason, I am going to implement this capability in my build.  I would like to do so in a manner which would easily allow it to be added to the master branch if desired.

So ignoring whether this is a good idea for the standard NUnit 3 framework, I have a single question.

What is the best format for specifying a percentage complete:  int, short, byte, float, double or decimal?  And if int or short, should it be percent * 10 so a decimal point is possible?

Also, Nullable<T> was available in 2.0, but was T? available then as well?  I want to make the PercentComplete property nullable so it is easy to determine if it is set or not.

**Comment by CharliePoole** [comment]
All feedback from the framework is in the form of a string, usually XML-formatted. If we decided to have a progress indicator, it would presumably be a new XML element and would have to include the identity of the test plus some progress value. That value could be the string representation of pretty much any numeric value.

However, it's a bit academic, until we decide we want such a thing.

You never categorized this issue in any way, so I just marked it as an idea.

**Comment by oznetmaster** [comment]
I was proposing that this be a new method for a ITestListener2 method that extends ITestListener.

Similar to the ITestListener methods, it would have a single argument, ITestProgress, which would have an ITest Test property (the test reporting its progress) and a PercentComplete property, and nothing more. (Neither of the other two methods are passed Xml).

What the ITestListener2 does with this information would be up to it.

This would perhaps converted to Xml in some cases, but that is up to the ITestListener2.

Hence the question about the actual data type to use to pass the information.

**Comment by rprouse** [comment]
I don't mind the idea, I just don't like the idea of this in practice. To implement, it would require us to write a new interface, then modify all test runners to show test progress, then users would need to instrument their tests to see any progress beyond 0/100%.

For your environment, this wouldn't be a problem, you have control over the entire toolchain. The problem I see is that we won't be able to get all 3rd party runners to implement the new progress, so users who do instrument their code will complain to us when it doesn't work.

The other option to give feedback is the often requested #1139 to give continuous feedback as the test is running. I would much rather do that, then for this issue maybe just provide a simple api on TestContext to print out test completion percentages? Or even just leave it up to the user to do so if they wish?

**Comment by oznetmaster** [comment]
#1139 sounds similar, but it does not really allow the test to report its progress itself.  It is sort of an implicit progress rather than an explicit one.

I want the GUI to be able to have a progress bar that shows the percent complete in some fashion.  I am not sure that can be gotten from #1139, but maybe they could be combined in some way.

For test that do not report progress, the GUI will just say that the test does not report its progress.  Should be no confusion.

**Comment by rprouse** [comment]
My point is that you have control over your GUI, so it isn't a problem for you to add the feature, but general users of the framework expect all features to work across all runners and I doubt it will be a widely used enough feature that we can get other 3rd Party runners to implement it.

**Comment by oznetmaster** [comment]
How is the GUI that is currently being written going to handle real time reporting of test progress, or is it not going to?

**Comment by CharliePoole** [comment]
I don't see us making any use of this in either the console runner or (our) gui. NUnit has always reported progress on the basis of number of tests completed and users (except for Neil, now) have never asked for more. And he isn't asking for any NUnit runner to do it, just to add an interface to the framework.

I don't think we should do this, but Neil has asked for comments on how it might be done. So...

I would not add this to the ITestAssemblyRunner interface or create a separate copy of the interface. We already have a progress interface, which sends an xml string. Each of them is a single element and they are distinguished by the element name. All that we would need to do, were we to do this, would be to define a new xml element representing progress within a test.

Taking this thought experiment a step farther, we would have to completely redefine the gui form in order to display both overall progress and progress within the current test. I think it would probably require a separate dialog box while tests are running, which we do not now do. In the VS adapter, there is no possibility to display anything except test by test progress.

If a true interface were needed, in order to report progress to runners that actually reference the runner, I would define a separate IProgress interface, which included a single Progress event. Doing it that way, the framework would not have to be aware of whether the particular runner wanted to get progress info and runners that do nothing would not have to change. Interested runners could check to see if IProgress were implemented and act accordingly.

For me, this is totally a thought experiment - I don't want to add it.

**Comment by CharliePoole** [comment]
@oznetmaster The new gui will report progress using the existing progress notices: start-test and end-test. This is functionally equivalent to what the old gui does. 

Some people want to record the progress within long-running test cases. We have accepted #1139 for that purpose. This is a bit more than a progress bar type notification, since it includes text and since the output will be part of the recorded test result. My assumption is that folks will use it to send messages that indicate how far the test got in a long-running series of operations.

**Comment by oznetmaster** [comment]
That does not solve the problem I am addressing.

If a specific TestMethod takes 4 hours between its start and its first nunit assertion, the real time recording of that assertion will not indicate progress through the test.

If the test wants to report progress every minute, that will be 240 "messages" recorded in the test result, all of which are actually useless once the test is completed.

The concept of a IProgress interface is that the information is available real-time, can be ignored if desired, and is transitory.  It could be called every second if the test wanted to (that would be 12,240 "messages"), and it would have no affect on the recorded test result.

As to the GUI, in my GUI, the progress bar is in the test tree, next to the test name (only for terminal leaves of the tree).  It only appears while the test is running.  Once the test is completed, the tree node indicates the test result and the progress bar goes away.  So with parallel tests, multiple tests can have progress bars until they complete.

**Comment by oznetmaster** [comment]
I am also confused as to the value of recording real-time information permanently in the test result as proposed in #1139.  Once the test has completed, either successfully or with some failure, what value does that information have?  Why burden the test result with it permanently?

**Comment by CharliePoole** [comment]
One user has said that he would like to see it saved, so I'm considering it. But one swallow is not a summer, as the saying goes.

If the user is writing out useful information as part of the progress report, then saving it makes sense. If it just said 10% complete, etc. then it would make no sense. As usual, this stuff gets resolved as we work on it and interact with the users.

**Comment by oznetmaster** [comment]
I reread #1193 again, and it is really totally different then what I am suggesting.  The only similarities are that each of them requires the addition of a property to TestContext (LiveOut or similar in #1193 and Progress in my case), and each of them requires a modification to the test itself to provide the progress information.

In both cases, runners that are not aware of the additional information will not display it.

The #1193 solution allows arbitrary strings to be written to the property.  This is good if some form of message is desired to be displayed, but it is pretty useless for any standardized GUI or other runner that only wants to display test progress.  No way to get from an arbitrary test defined message to a percent complete.

The advantage of a completion percentage is that it is always the same data format.  Also, it is a very small piece of data, easily sent from a device being remotely tested to the test runner.  Sending an arbitrary stream of text of unknown size is more complex.

I think that there is a valid reason for both approaches.

Personally, I see far more use for the percent complete then the live message concept, but perhaps that is because of the kinds of tests I am working with.  I most cases, a single test method that runs for 4 hours is merely processing a lot of data, and does not have distinct information about its progress except as a percentage of the total data processed.

BTW.. and this could become a new issue/idea, once there is real-time feedback of any sort, then it seems logical that there should be a way to abort a given test without aborting the entire test run.  Perhaps a  new StopTest method, taking an ITest as an argument.  It would abort the test if it was running, or keep it from running if it were not.  No other test would be affected.  Pretty easy to do in the current architecture.

**Comment by CharliePoole** [comment]
Yes, they have always been entirely separate issues and your comparison of the two is accurate. Issue #1193 is intended to give back a text display feature we took away when we moved away from NUnit 2.x. Issue #1226 is a new idea.

Regarding cancelling a single test, past experience has shown that with asynchronous messages, we can't ever know what test is running at a given moment. However, it might be possible to send a message to abort a particular test by id (since ITest is not shared outside the framework) and simply ignore it if that test had already terminated. In fact, we could do that now if there were a demand for it, but I'm not in favor of simply inventing features when there is such a large backlog of actually requested features waiting for somebody to implement them.

**Comment by oznetmaster** [comment]
That was why I indicated it would only make sense in the context of having a real-time progress indication. By id, do you mean the test name displayed in a GUI, for instance?  That would make sense since the process for stopping a test would be to select the test to be stopped, and click "stop test", either in a menu or a right-click context menu.

If the selected test had already completed, this would have no affect.  If it had not started, it would just never run.  If it was still running, then it would be aborted.

Given the discussion about tests that run in hour orders of magnitudes, this would make sense no matter how asynchronous things are.

**Comment by CharliePoole** [comment]
The id is an attribute of the test, which defines it uniquely for the duration of the run. When run by the engine, it has the format m-n, where m uniquely identifies the assembly and n uniquely identifies the test within that assembly. The current implementation uses an integer as the source of m and n, but the id itself is a string. All selection of tests from the gui uses the test id - that's what it's for.

While you have said that some of your tests run for hours, I'm don't think it's a general need. Your requirement may simply be too specialized for our user base.

**Comment by oznetmaster** [comment]
Some of the other people who have commented on #1193  talk about tests that run for hours as well.

It does not appear this is an isolated situation.

**Comment by rprouse** [comment]
There has been no discussion on this since 2016, so I am going to close. It can be reopened if someone wants to move it forward.
