### ISSUE TITLE
Running unit tests with a main loop

### ISSUE THREAD

**Issue by alanmcgovern** [nunit/nunit#1227]
Back in July 2013 I forked nunit lite to use a base for a test runner which can execute it's tests in co-operation with a UI main loop. The main use cases where:
1) Write tests for github.com/mono/monodevelop which is a Gtk# application. Our preexisting code has Gtk.Application.BegInvoke calls and misc things like that so we kinda needed the gtk main loop to be running in order to write tests.

2) Write tests for MonoMac/Xamarin.Mac/Xamarin.iOS applications where some native APIs require an AppKit main loop to be running. AppKit applications require NSApplication.Terminate to be invoked in order to shut down properly so we had to make sure all the relevant logs were written/flushed before the process is terminated.

3) Every method marked as [Test], [Setup], [Teardown] etc  should be allowed to use a Task<T> return to allow async/await to work everywhere.

I hacked up a new TestRunner.cs using an interface called IMainLoop which gave us this support. The general idea was that when the Main method was invoked, we'd spin off a thread which would iterate over all the fixtures/tests/etc as per normal and begin executing the relevant methods. Every method invocation was wrapped in an `IMainLoop.InvokeOnMainThread` and if the invoked method returned a `System.Thread.Task` the test runner would call `.Wait ()` on it to wait for it to complete.

The main thread would then call `IMainLoopIntegrate.RunMainLoop` which would call `Gtk.Application.Run` or `NSApplication.Run`, `Wpf.Application.Run`, or whatever to start the main loop. 

I would love to get this work integrated with upstream NUnit3 so I was wondering what would be the best way go about re-implementing this behaviour so that it could be upstreamed, or more easily maintained.

My current fork is here: https://github.com/mono/guiunit/tree/master/src/framework/GuiUnit .

The full diff is here: https://github.com/mono/guiunit/compare/070d1eb3de5872c86d8f3c024f3116fe517c0b13...ad28ae12928cce579ae2f9450291dd7648dad76b

**Comment by alanmcgovern** [comment]
The other thing the commit added was a way to write the test output to a socket as the tests ran. This was useful for IDEs to provide progress updates as tests ran. I did the integration with Xamarin studio as one of my other requirements was that the tests I'm writing on a day to day basis needed to be runnable from inside XS :)

One thing I never tried was to implement support to launch xamarin.ios/xamarin.android applications and have their tests be executable via the Xamarin Studio unit test panel. Figuring out the best way to support that with nunit 3 could be a separate discussion though :)

**Comment by CharliePoole** [comment]
Sounds like a great idea! I think you may first need to get familiar with some NUnit 3 changes - if you are not already - in order to talk about this. I'll start by listing what comes to mind...

1. The old NUnitLite, which we released as 1.0 in September 2013, was a variant build of the nunit framework with added code to allow creation of self-executing tests. In NUnit 3.0, there is only one framework, with variant builds for different platforms. We have re-defined NUnitLite to be that extra code, which allows simple test execution. So your changes would either go into the framework itself or into the nunitlite component.

2. The framework now supports parallel test execution, based on an #if in the builds. My guess is that you would want to turn this off for your purposes, at least when doing UI tests.

3. We now have a portable framework build. It would simplify things if you are able to use it. That depends, of course, on whether the features you need can be built into our PCL.

It seems to me that we will need to break the necessary changes into a set of separate commits, such that it is relatively easy to review them. I'll read through the code with that in mind.

**Comment by alanmcgovern** [comment]
This was mostly a PoC at the time which I meant to clean up and upstream in some form. I'm finally ready for that now ;) 

I'm happy to rewrite it in another form if you have any preference/thoughts on how to best do it

**Comment by CharliePoole** [comment]
Just so you understand that there's a whole new upstream to deal with. :-) 

I plan to go through your changes and comment in some detail about how various bits of code may relate to NUnit 3.0, but right now I'm working on another branch that I have to finish up.

**Comment by alanmcgovern** [comment]
Just pinging again on this. I did review the existing code and rebasing my changes on top of a more recent nunit, in a manner similar to how i've already done it, would be  pretty doable. If that approach is acceptable then I'll go ahead and do it. If an alternative approach is needed then I'd need some guidance as to what I should be aiming for.

Thanks!

**Comment by CharliePoole** [comment]
Our slowness here is because it's a review of a fork of obsolete code. I'm basically the only one who ever worked on that code. Still, you've been waiting a long time, so I took a look...

* AdditionalAsserts are all present in the current build.
* XmlTestListener does what we now do in the framework except, of course, our XML is different. In addition, we use an internal class to bridge the differences between XML implementations on differing platforms.
* The rest of the code - it seems this is your major change - is to do with running in the main gui loop. We don't have experience with that, so I think we would need your help to integrate it.

I think that going forward would involve your creating some PRs to make a set of incremental changes to our existing code base. I say incremental, because that makes it more likely they will be reviewed and accepted.

If I were doing it, I'd try to figure out what changes can be made first, independent of the main loop feature but facilitating it. IOW some small steps before the  big step.

One key question: can the way of running the tests be separated out from the framework or does it need to be actually in the framework?

**Comment by alanmcgovern** [comment]
I would love to make incremental changes to your existing codebase. Right now I don't have a good enough high level understanding of the current codebase to know what the correct way of implementing this kind of change would be.

Here's one possible approach (in psuedocode):

* Ship this interface as part of the core
```
public interface IMainLoopIntegration
{
	void InitializeToolkit ();
	void InvokeOnMainLoop (InvokerHelper helper);
	void RunMainLoop ();
	void Shutdown ();
}
```

* Ship this assembly level attribute as part of the core
```
[AttributeUsage(AttributeTargets.Assembly)]
public class RequiresMainLoopAttribute : Attribute
{
    public RequiresMainLoopAttribute (Type type){}
}
```

You'd apply the attribute like this to your test assembly, where the `XwtMainLoopIntegration` class is an implementation of `IMainLoopIntegration` also contained in your test assembly.
```
[assembly: RequiresMainLoopAttribute (typeof (XwtMainLoopIntegration))]
```

The normal test runner will look for this assembly level attribute on startup and instantiate the referenced type. We'd then hit a codepath like this:
```
// If there was no RequiresMainLoop attribute on the assembly, do the normal thing.
if (MainLoop == null) {
	RunTests (filter);
} else {
	// There was a `RequiresMainLoop` attribute, so initialize our toolkit, start running the tests
	// on the background thread and then kick off the main loop.
	MainLoop.InitializeToolkit ();
	System.Threading.ThreadPool.QueueUserWorkItem (d => {
		RunTests (filter);
		Shutdown ();
	});
	MainLoop.RunMainLoop ();
}
```

The final piece of the puzzle is that anywhere where the test runner would normally invoke a method marked with [Setup], [Test], [Teardown] etc it would hit a codepath like this. Note: InvokerHelper is just to make sure we propagate some NUnit data from our background thread to the main thread(  https://github.com/mono/guiunit/compare/070d1eb3de5872c86d8f3c024f3116fe517c0b13...ad28ae12928cce579ae2f9450291dd7648dad76b#diff-1bf349792ee25daa33384733d37dd40aR1 ):

```
object result = null;
// If we do not have main loop integration enabled, run the method normally
if (GuiUnit.TestRunner.MainLoop == null) {
	result = method.Invoke (fixture, args);
} else {
	// We're using a main loop so invoke `method` on the main thread.
	var invokeHelper = new GuiUnit.InvokerHelper {
		Context = TestExecutionContext.CurrentContext,
		Func = () => method.Invoke( fixture, args )
	};

	GuiUnit.TestRunner.MainLoop.InvokeOnMainLoop (invokeHelper);
	// Block execution of this thread until `method.Invoke (fixture, args)` has been run
	// on the main thread and the result of that invocation has been stored.
	invokeHelper.Waiter.WaitOne ();

	// If we received an exception, just rethrow it
	if (invokeHelper.ex != null)
		Rethrow (invokeHelper.ex);
	result = invokeHelper.Result;
}

// If the method we invoked returned a `Task` then we should wait for it to complete.
// This allows us to handle any method marked as `async Task`. The `.Wait ()` invocation
// will throw an Exception if the method we invoked throws an exception. 
if (result is System.Threading.Tasks.Task)
	((System.Threading.Tasks.Task) result).Wait ();
return result;
```

**Comment by CharliePoole** [comment]
@alanmcgovern We'll discuss this a bit among the committers and get back to you.

One question: your pseudocode has indications that you are still working with NUnit V2 code. Is that correct? There is pretty much no chance that we will issue a new V2 release.

**Comment by alanmcgovern** [comment]
I think that just shows I don't have a good understanding of how nunit3 hooks together. I'd like this to eventaully end up in the master branch. I definitely don't want new releases of the obsolete nunit-lite code, or nunit 2 code.

**Comment by rprouse** [comment]
@alanmcgovern our current Xamarin runner has a UI loop running because it is a UI app. I run the tests on a background thread and then marshal the results back to the UI thread. We also have preliminary support for writing the results back to a host machine over TCP. Eventually we would like to get to the point where we can deploy and run the tests from the desktop, but will need some help getting there.

So far, tests that I have created for Xamarin run fine on a background thread. I assume that any tests that must be run on the UI thread, the developer will marshal it. We have seen reports of this being done in various web and WPF tests, so I would think it is common knowledge. Am I missing use cases?

Based on that, I am not sure we need or want those enhancements in the framework itself. I think that it should be the developer's responsibility to marshal back to the UI thread if required. Also, how you run the main loop or marshal back the UI thread is different for every target platform. Wouldn't this mean pulling in dependencies on various platforms?

I could see a series of NUnit addons that provide helpers for all of this to be more useful. My thinking would be one extension per platform, NUnit.UI.Helpers.Xamarin.Android for example. They could include an attribute that starts the main UI thread on a background thread and runs the message pump, then attributes or helper methods that would marshal test execution back to the UI thread if desired. I don't think we need to mess with our internal threading and running to do this.

Am I misunderstanding the problem you are trying to solve?

**Comment by alanmcgovern** [comment]
> I run the tests on a background thread

This means you cannot interact with the a huge portion of the AppKit/UIKit/Gtk/WPF/Android APIs, especially ones related to the UI, because you're on the wrong thread.

> I assume that any tests that must be run on the UI thread, the developer will marshal it
That is precisely what my patch is all about - it removes the burden of adding explicit marshalling to every test, setup method, teardown method etc.

> how you run the main loop or marshal back the UI thread is different for every target platform
That's what the interface I've described does. It's platform agnostic and works for all of the UI toolkits I've mentioned.

> They could include an attribute that starts the main UI thread on a background thread
That's not possible for iOS (and others). Even if it were possible, it would still require explicit marshalling on a per-method basis. You still have your tests running on one thread and the main loop running on a second thread.

**Comment by alanmcgovern** [comment]
Perhaps it would be better for me to just describe my ideal situation and then you tell me how i can accomplish it, using either existing components or by writing new components:

- I want my tests to run co-operatively with a main loop. It should be possible to execute my tests without blocking the UI thread. This will allow AppKit/UIKit/Gtk to free memory while test runs are running because freeing a widget requires a task to execute on the main thread. If the thread can't pump while the fixture is running no memory can be freed until the test fixture ends.

It also allows existing applications which have not cleanly separated their UI code and their non-UI code to be more easily testable.

- I want to be able to run my tests when the main loop is thread 0, the first thread created by the application. Some UI toolkits like iOS do not support initializing on another thread. 

- I want my test methods (Setup, Teardown, Test, etc) to work 'as expected' when using async/await. i.e. i can use await anywhere and the await will resume execution on the main thread.

- I want to be able to send updates to a remote application while the test fixture is executing, so things like MonoDevelop's test unit pad can show up-to-date progress as the tests run.

- I want my test runner to exit reliably. This means using `NSApplication.Terminate` or `Environment.Exit`. AppKit can create threads which are not marked as background threads, and so can keep the process alive forever if you just let the main function return. iOS applications do not have an API to terminate, our test runner there currently p/invokes `exit (0);` in order to exit.

**Comment by Mazyod** [comment]
I came here hoping for a more elegant way to run my tests without blocking the main UI than running in a background thread, but as @rprouse suggests, as long as your tests are eventually just a bunch of `Assert` statements, the "interesting" data you'd want to assert on can be selected from the background thread, executed asynchronously on the main thread, which generates a result that the background thread can then act upon.

I'd say this feature is highly desirable, but a viable workaround is available.

**Comment by decriptor** [comment]
@Mazyod you might be interested in this https://github.com/garuma/GuiUnitNg

**Comment by decriptor** [comment]
I figured it'd be worth posting this here as well. It is an updated version of guiunit based on 3.x.
https://github.com/garuma/GuiUnitNg

**Comment by rprouse** [comment]
I am closing old Idea issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.

**Comment by decriptor** [comment]
@rprouse I'm not sure where this stands. This is an old issue, but it'd be nice if it was resolved instead. At one point @jnm2 had it as part of the `Async improvements` project https://github.com/nunit/nunit/projects/1

**Comment by jnm2** [comment]
Indeed, I do currently have this on my OSS list (which is moving at a glacial pace). I've been tracking it here: https://github.com/nunit/nunit/issues/2917
