### ISSUE TITLE
No plugin found which can import settings file with extension '.nunit'. Either select a new settings file or install an extension which understands this settings file extension.

### ISSUE THREAD

**Issue by denfromufa** [nunit/nunit#1235]
VS 2015 Pro + NUnit Test Adaptor installed. Then Build.

**Comment by denfromufa** [comment]
https://github.com/pythonnet/pythonnet/blob/develop/src/embed_tests/Embeddingtest.nunit

**Comment by CharliePoole** [comment]
Can you add some info about what you are actually doing in order to get this message? In particulary, how (and with what software) are you trying to run your tests. If it's from the command-line, what are the arguments.

Background:

The .nunit file is not a settings file, it's an nunit project, which can encapsulate one or more assemblies. Since you only have one test assembly and use default settings there's no particular reason to create one.

In your particular example, you defined a release configuration with no assemblies. That's definitely an odd thing to do. Normally, you simply would not have a configuration if you don't intend to use it.

**Comment by denfromufa** [comment]
I updated the text above. I tried again and output is empty.

**Comment by denfromufa** [comment]
After pushing build in Visual Studio:

------ Discover test started ------
No plugin found which can import settings file with extension '.nunit'. Either select a new settings file or install an extension which understands this settings file extension.
========== Discover test finished: 0 found (0:00:00.0019531) ==========

**Comment by rprouse** [comment]
Are you trying to set the .nunit file as a Visual Studio Test Setting file? They are not compatible. You don't need a .nunit file to run NUnit tests in Visual Studio, you just need the NUnit Visual Studio Test Adapter (of which there are two, one for NUnit 2 and one for NUnit 3).

**Comment by CharliePoole** [comment]
@denfromufa Not only don't you need a .nunit file as @rprouse says, you can't have one! If you are using one of the nunit adapters to run tests in the test window, NUnit doesn't control what tests are run, Visual Studio  does. Get rid of the .nunit file!

**Comment by denfromufa** [comment]
OK the issue was nunit 2 VS 3 tests.

**Comment by rprouse** [comment]
Glad you got it working. I am closing this issue.
