### ISSUE TITLE
3rd-party dependencies should be downloaded on demand rather than kept in the repository

### ISSUE THREAD

**Issue by simoneb** [nunit/nunit#125]
With #75 NUnit started needing to reference third party components in some of its projects. This requires that the dependencies are downloaded from somewhere and put alongside the NUnit files. NuGet did not give encouraging results when used on non-Windows platforms and was discarded initially, but keeping the dependencies in the repository is not a good option either.

Solving this issue means either making NuGet work cross-platform without too many hacks or finding an alternative solution to download dependencies on demand.

**Comment by chris-smith-zocdoc** [comment]
Has the NuGet situation improved at all in the last year? I would assume Microsoft is making some advances with the non Windows support for .net

**Comment by CharliePoole** [comment]
@chris-smith-zocdoc Coincidentally, I just added a new package to the build, which brought this issue to my attention again. We really have a lot of binaries in the repo because of this issue.

This would be a good time to address the issue. NuGet provides three different ways to synchronize, so it seems like one of them ought to work.

In case you want to experiment with this, we need to be able to work in four different cases:
1. Building using Visual Studio on Windows.
2. Building using MonoDevelop on Linux.
3. Building with our msbuild script on Windows.
4. Building with out msbuild script on Linux.

For experimentation on a branch, I would select just one package initially, remove it's binaries from the repo and then try to make each of these work. While it's possible to do the Linux testing via our Travis build, it's probably easier if you actually have a Linux machine.

PS: I'm not sure what MS non-Windows support would have to  do with this one.

**Comment by rprouse** [comment]
I  think the biggest problem we may run into is with NuGet packages that
contain Powershell scripts. Probably none for what we use.
