### ISSUE TITLE
New Custom Constraints documentation

### ISSUE THREAD

**Issue by samuelneff** [nunit/nunit#1255]
Attached is new Custom Constraint documentation that matches the new syntax and provides a lot more details. I didn't see any way to do a PR for the wiki, so hopefully this works well enough.

[Custom-Constraints.md.txt](https://github.com/nunit/nunit/files/120940/Custom-Constraints.md.txt)

You can view the updated page on my fork here:

https://github.com/samuelneff/docs/wiki/Custom-Constraints

Thanks,

Sam

**Comment by rprouse** [comment]
Thanks. I have copied these into the new docs wiki. https://github.com/nunit/docs/wiki/Custom-Constraints

**Comment by CharliePoole** [comment]
@samuelneff I made a few corrections to the text...

 * Page is still under development
 * Tried to clarify the use of arguments to constraints
 * Removed use of Expect except when talking about AssertionHelper
 * Added note about the pending removal of AssertionHelper

If you see any other docs you would like to work on, you are welcome to do so. You should file an issue under the nunit/doc project rather than here, preferably before actually writing the page. There will be a process for submitting changes in the near future. Additionally, there will be some issues available for self-assignment in that repo - at least as soon as I get around to creating them.

**Comment by samuelneff** [comment]
Thanks for the review and updates. I didn't know `AssertionHelper` is being removed. I like that class. :-)

**Comment by CharliePoole** [comment]
There's a strong chance it will end up available separately. See #1212.
