### ISSUE TITLE
Nunit needs to handle COM security and thread model for tests for COM applications on Windows

### ISSUE THREAD

**Issue by himan-k** [nunit/nunit#1269]
Please check out this discussion for reference,
https://groups.google.com/forum/#!topic/nunit-discuss/uu9PQMhn3FY

**Comment by CharliePoole** [comment]
How will NUnit know that this is necessary? The choice seems to be between some sort of command-line option and use of attributes on the assembly. Attributes would probably give the most flexibility.

@himan-k What exactly would you want to specify? What variations do you think may be needed by other folks? (It's been at least 15 years since I worked with COM)

**Comment by rprouse** [comment]
@himan-k I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.
