### ISSUE TITLE
parameters to configure test runner so that it runs in ui thread - calling thread

### ISSUE THREAD

**Issue by jmecosta** [nunit/nunit#1275]
hi,

we have adapted the visual studio adapter, to run nunit tests inside our product. we have a requirement now that we need to test some ui code, and for this to happen we need,
 . run tests in same appdomain as our product
 . run tests in the same thread, UI with STA set.

For the appdomain, we fixed it in the test adapter. For the thread it is a bit harder and i am ensure about the parameters that we can use to set this in the Nunit engine. we look at the doc about the RequiresThread Attribute but from reading looks like the engine always creates a thread, and this we would like to avoid.

is this possible?

thanks in advance.

br,
jorge costa

**Comment by rprouse** [comment]
The tests run by default in a different app domain as nunit itself, but all of your application and test code is in one AppDomain.

As for UI threads, first, mark your tests as requiring STA, then you will need to marshal your test code back to the UI thread. How you do that depends on the UI framework, but is usually something like `control.BeginInvoke(() => // run tests)`.

I am closing this issue as a question. Feel free to continue posting. I am also sorry that we did not get back to you sooner, we will try to do better in the future.

**Comment by CharliePoole** [comment]
We should also note that 3.2 is running each test on a separate thread. This is fixed in the source. The 3.0.1 release is friendlier in this respect. Also in the latest source, take look at the SingleThreaded attribute.

**Comment by jmecosta** [comment]
@rprouse  yep, i was afraid we would not be able to disable all domain, thread from our side. and creating code to marshal unmarshal is not something we want to maintain. So we decided to create are own simple runner that just read test attribute and run those without changing any domains. fortunately all nunit assert are working also so we are not blocked. 

@CharliePoole we havent move to 3.2 yet, so good to know once we move the other tests we have using nunit runner thanks.

**Comment by CharliePoole** [comment]
Once the engine has run your tests (called by the console runner or some other runner) everything is under control of nunit.framework. There is no code in the framework to create new domains or processes - that's higher level in the NUnit architecture. There is code to run on threads and to create new threads at your request. But tests all run on the thread used by their fixture unless you apply an attribute (e.g. RequiresThread) to the test method to force use of a new thread.

The new SingleThreadedAttribute is applied to a fixture and is intended to guarantee that everything in that fixture runs on the same thread. It will be in the next release.

I repeat from above that NUnit 3.2 is broken for your purposes, since it creates a new thread for every test case. Use 3.0.1 or wait for 3.2.1 or higher.

**Comment by jmecosta** [comment]
Ok so if I understodd then it should work, so I will wait for 3.2.1 and
give it another go.

**Comment by CharliePoole** [comment]
Yes. 3.0.1 should also work. Even though there isn't the "guarantee" of SingleThreadedAttribute, we don't actually create any new threads below the fixture level unless you tell us to.

**Comment by jmecosta** [comment]
ok, we can also try 3.0.1 we are running 3.0.0 now. so maybe thats the reason why it did not work

**Comment by CharliePoole** [comment]
Good luck. Feel free to come up with a test that we should try to make run in our new code. The way I usually test such things is to record the thread id in a onetimesetup and then have every test check that it is running on the same thread.
