### ISSUE TITLE
TestCase using Params Behaves Oddly

### ISSUE THREAD

**Issue by lundmikkel** [nunit/nunit#1282]
I have a test method that takes an integer array. I use `params` to make writing test cases easier:
```csharp
[Test]
[TestCase()]
[TestCase(1)] // <-- this test case misbehaves
[TestCase(1, 2, 3)]
public void TestMethod(params int[] array) {
    Assert.That(array.Length, Is.Not.EqualTo(1)); // Fail arrays of length 1 (see below)
}
```
However, the middle test case above behaves oddly. To make the test case stand more out here, I've made the test fail only for that test case.

When running the tests inside VS using NUnit Adapter 3.0.8.0 the test shows up as follows:
<img width="212" src="https://cloud.githubusercontent.com/assets/1230950/13225067/89844c90-d98b-11e5-92af-ae61cb1384ea.png">
As oppose to the others that show up as `TestMethod()`and `TestMethod(1, 2, 3)`, the middle test case is given as an array: `TestMethod(System.Int32[])`. I would expect it to show `TestMethod(1)`.

If I use ReSharper to run the tests (which I normally do), the test case shows up twice:
<img width="420" src="https://cloud.githubusercontent.com/assets/1230950/13225192/178034f0-d98c-11e5-9ac2-ea06234342d0.png">
One time as a failed test `TestMethod(System.Int32[])`, and one time as a pending test `TestMethod(1)`. It seems to write the right thing for the pending test, but not the failed one.

**Comment by CharliePoole** [comment]
I accepted this without separate confirmation because I know we have some special code for a single array argument. We may not deal correctly with a single params argument.

We're close to releasing 3.2, so this may not make the cut, but we ought to try.

**Comment by lundmikkel** [comment]
That would be great. It currently leaves my Continuous Testing Session in an unfinished state with 1 dirty (pending) test:
<img width="384" src="https://cloud.githubusercontent.com/assets/1230950/13233793/c364c956-d9b5-11e5-8c9c-cde984a15d61.png">

The problem is not there, when I use a "proper" array:
```csharp
[Test]
[TestCase(new int[] { })]
[TestCase(new int[] { 1 })]
[TestCase(new int[] { 1, 2, 3 })]
public void TestMethod(int[] array)
{
    Assert.That(array, Is.Not.Null);
}
```
But that makes it difficult to read, as all test cases show up as three test cases with the same signature of `TestCase(System.Int32[])`, which makes them difficult to differentiate.

With VS and NUnit test adapter:
<img width="503" src="https://cloud.githubusercontent.com/assets/1230950/13233856/140d24de-d9b6-11e5-8afb-23fd47e3e3d8.png">
And with ReSharper:
<img width="359" src="https://cloud.githubusercontent.com/assets/1230950/13233831/e75b69b4-d9b5-11e5-9cf0-9357802f5cd6.png">

Slightly off topic: is there a way to see when 3.2 is planned for?

**Comment by CharliePoole** [comment]
@lundmikkel For 3.2, see https://github.com/nunit/nunit/milestones/3.2

**Comment by lundmikkel** [comment]
Thanks.

**Comment by CharliePoole** [comment]
@lundmikkel Looking back at this, I noticed your reference to a "Pending" test in R#. What is a "pending test?" It's not a term I've used and definitely not an NUnit test status.

**Comment by CharliePoole** [comment]
This turns out to be a test naming irregularity in NUnit itself, not merely in the adapter. Fixing it may actually help R# as well.

My guess about "Pending" is that it's a test that was found by R# in the source but was never run. I'm assuming that it's R#'s logic that applies in finding the test and our code for reporting it as run. If that's true, the R# error should be fixed by correcting the name NUnit generates for the test.

**Comment by lundmikkel** [comment]
I honestly don't know what pending tests are (Google search didn't help a lot). All I know is that pending tests are a nightmare. I have no clue what causes them in general. I've seen pending tests with `TestCase`s, where the individual `TestCase`s are not run, unless you run them individually/manually.

I'm not sure how this relates to the issure, but it seems you might have a better idea :) It would be great if you find a fix for NUnit that fixes ReSharper as well.

**Comment by CharliePoole** [comment]
As a semi-intelligent guess, I'd say it's a test that R# expected to see run but which was never reported. Instead, an unexpected test (with the array argument) is reported. To ensure that nothing is forgotten, it reports on both the expected-but-not-reported and the unexpected test. Visual Studio will do the same if a test is discovered under one name but executed under another. It doesn't happen in this case, because NUnit performs both operations for VS.

I can see what's causing this in our code, so it's matter of doing some refactoring and putting in the fix for NUnit 3.2. The next release of the NUnit 3 VS Test Adapter will reflect the change. If it's possible for you to substitute NUnit 3.2 for the version used by R#, then you should see the impact there as well. Same goes for any other 3rd party tools.

**Comment by lundmikkel** [comment]
@CharliePoole I made you a very small example of a case where ReSharper marks a test as pending:
```csharp
using NUnit.Framework;

namespace PendingTests
{
    [TestFixture]
    public abstract class AbstractParent {
        [Test]
        public void TestMethod() {
            Assert.Pass();
        }
    }

    [TestFixture]
    public class TestFixture : AbstractParent {}
}
```
The `TestFixture` class inherits its tests from a parent class. With ReSharper, the code looks like this inside VS2015:
<img width="341" src="https://cloud.githubusercontent.com/assets/1230950/13401963/7bf15338-df0e-11e5-8bca-699b536f08df.png">

I can run all the tests in `TestFixture` (including those in its parent classes – in this case `AbstractParent`'s `TestMethod`) using ReSharper by clicking the icon left of the class:
<img width="371" src="https://cloud.githubusercontent.com/assets/1230950/13402031/c7e75602-df0e-11e5-9e81-ef75668b9c70.png">

That very breifly looks like this:
<img width="377" src="https://cloud.githubusercontent.com/assets/1230950/13402086/051f4ca0-df0f-11e5-8172-6c6a6095500b.png">
Before changing to:
<img width="354" src="https://cloud.githubusercontent.com/assets/1230950/13402128/2ec2e8be-df0f-11e5-801e-a3c98fdc7c94.png">

Notice that both the state, name and wall clock time changes and the test – now called `AbstractParent.TestMethod` – is marked as pending. The icon <img width="22" src="https://cloud.githubusercontent.com/assets/1230950/13402447/98dd3424-df10-11e5-8edf-c54ab3f79667.png"> is for an "unknown" test. Removing `[TestFixture]` from either class has no effect. Neither does making `AbstractParent` a concrete class.

Whether this is an NUnit or a ReSharper issue is difficult for me to say.

**Comment by CharliePoole** [comment]
I'd say this last example is a problem with Resharper failing to understand how NUnit names tests. They are assuming a naming convention that was used with NUnit V2, where the name of the base class was added to the name. This is not done in V3.

The original problem was a case where NUnit was not correctly following it's own naming conventions. That is fixed in the PR referenced above, which is currently being reviewed.

**Comment by lundmikkel** [comment]
Okay, I think I'll create an issue with ReSharper then.
