### ISSUE TITLE
Revision numbers across builds of the same package

### ISSUE THREAD

**Issue by ploeh** [nunit/nunit#1295]
When installing NUnit 3.0.1, the identities of the .NET assemblies differ:

- **dotnet:** `nunit.framework, Version=3.0.5813.39035, Culture=neutral, PublicKeyToken=2638cd05610744eb`
- **net20:** `nunit.framework, Version=3.0.5813.39033, Culture=neutral, PublicKeyToken=2638cd05610744eb`
- **net40:** `nunit.framework, Version=3.0.5813.39032, Culture=neutral, PublicKeyToken=2638cd05610744eb`
- **net45:** `nunit.framework, Version=3.0.5813.39031, Culture=neutral, PublicKeyToken=2638cd05610744eb`
- **portable-net45+win8+wp8+wpa81+Xamarin.Mac+MonoAndroid10+MonoTouch10+Xamarin.iOS10:** `nunit.framework, Version=3.0.5813.39035, Culture=neutral, PublicKeyToken=2638cd05610744eb`

The major, minor, and build version numbers are all identical, but the revision numbers differ. Is this by design? If so: why?

An additional question is why the assembly version number doesn't correspond to the package number; i.e. why isn't the assembly number `3.0.1(.0)`?

If this is by design, then why do the revision numbers _descend_ as the .NET versions ascend?

The reason for asking is that we're [currently developing AutoFixture.NUnit3](https://github.com/AutoFixture/AutoFixture/issues/522), and we're running into problems with versioning. Specifically, AutoFixture.NUnit3 is a Glue Library currently compiled against NUnit 3.0.1. Since AutoFixture itself currently targets .NET 4.0, AutoFixture.NUnit3 is also targeted against .NET 4.0.

This causes problems with certain end-user configurations:

1. Create a new .NET library project.
2. Target .NET 4.5.
3. Install the NUnit NuGet package. A reference to the .NET 4.5 version of NUnit is added.
4. Add references to AutoFixture and AutoFixture.NUnit3.

When you attempt to compile, Visual Studio produces this error message:

> Assembly 'Ploeh.AutoFixture.NUnit3' with identity 'Ploeh.AutoFixture.NUnit3, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b24654c590009d4f' uses 'nunit.framework, Version=3.0.5813.39032, Culture=neutral, PublicKeyToken=2638cd05610744eb' which has a higher version than referenced assembly 'nunit.framework' with identity 'nunit.framework, Version=3.0.5813.39031, Culture=neutral, PublicKeyToken=2638cd05610744eb'	NUnitAutoFixtureOn45

Since this is a compile-time error, it can't be solved with a binding redirect.

Normally, the compiler is happy when you have a version of a dependency that's _higher_ than expected, but the issue here is that the .NET 4.5 version of `nunit.framework` is _lower_ than the version for .NET 4.0.

If there's a way around this compiler issue, I haven't found it yet.

**Comment by CharliePoole** [comment]
This actually duplicates issue #1108, although it provides a bit more detail. Actual work is being done under issue #981, which deals with versioning more generally.

**Comment by CharliePoole** [comment]
Answers to questions in the description:

1. Build and revision numbers are generated by the compiler, using "3.0.*.*" Since revision is generated based on time of day, it may over the course of the build. We knew this would happen, but not that it would cause anyone a problem, since one set of tests only deals with one framework.

2. We decided to keep the package numbers ascending, while the assembly versions fall as they may. This has, in fact been the way NUnit has packaged for many years.

3. As it happens, we build in the order 4.5, 4.0, 2.0... which causes the revision numbers to get smaller as we go. This is purely an accident of how the build is set up.

For 3.2, we plan to have all framework builds that are packaged together use the same assembly version. Note that we package separately for both Silverlight 5.0 and Compact Framework 3.5, so they will not necessarily match the versions of the other framework builds.

**Comment by ploeh** [comment]
Sorry about posting a duplicate. I did try to search through the existing issue list, but I'm too bad at using GitHub's search features to be able to find much of use, apparently.

Thank you for responding.
