### ISSUE TITLE
Test fixture properties are not inherited by tests

### ISSUE THREAD

**Issue by yaakov-h** [nunit/nunit#1299]
I'm trying to add an attribute to my unit tests to say "this test must be run as administrator", and in test helper code that requires administrative privileges (e.g. start a server), throw an error if the developer has not applied this attribute to their test.

I have a custom attributes that implements `IApplyToTest` to set a property in the test's `IPropertyBag`, and then I have the test helper code reading this property and throwing an exception if it is not set.

If I apply this property to the test method, then I can read it within the test from `TestContext.CurrentContext.Test.Properties`.

If I apply this property to the test fixture, then it does not appear in `TestContext.CurrentContext.Test.Properties`.

I can work around this by adding `IApplyToContext`and then recursively adding the property  to `context.CurrentTest`'s `Tests`, however:

Are properties supposed to be inherited?

If not, is there a better way to achieve my goal with NUnit?

**Comment by CharliePoole** [comment]
This will be better handled in the discussion group where we can go back and forth and where many people participate and can give suggestions. Creating an issue / bug for each question you have is not really as good for either working out your problem or for getting a range of suggestions.

That said: You can use IApplyToTest when you want to change something about a test, including the properties. Each test has an individual property bag with the properties that have applied to it. Properties are not currently inherited although some of them appear to function as if they were. For example, if you apply an attribute to a fixture that causes it to run in the STA, then that's where the test cases will all run as well - not because the property is inherited, but because tests run in the same apartment as their containing fixuture unless annotated to run elsewhere. Many attributes work that way.

We have had some discussion about creating a type of property that is actually inherited, so you may see that in a future release.

Reading the value of a property in your test obviously requires code in your test. You could do the same thing in a OneTimeSetUp method and fail the OneTimeSetUp if you found you were not running as administrator. It would be lots easier to simply create an ActionAttribute that contains the code itself, so that all you would have to do is apply it where needed.
