### ISSUE TITLE
Assert.AreNotSame evaluates ToString unnecessarily

### ISSUE THREAD

**Issue by sharwell** [nunit/nunit#1301]
We have an object where `ToString()` cannot return a meaningful result at runtime. We implemented this method to throw an exception in debug builds so our unit tests catch cases where the object is passed to methods like `string.Format` that implicitly call `ToString()`.

When switching from NUnit 2 to NUnit 3, many of our tests started to fail. This is caused by the fact that in NUnit 3 `Assert.AreNotSame` and `Assert.AreSame` call `ToString()` on the object *even when the assertion succeeds*. In addition to causing unnecessary performance overhead during testing, this is notably problematic for our code. Here is a stack trace showing the manner in which this occurs:

![image](https://cloud.githubusercontent.com/assets/1408396/13401062/4069061e-ded0-11e5-9541-a801cf2b2a5f.png)

**Comment by sharwell** [comment]
:memo: The same problem occurs for `Assert.AreEqual`.

**Comment by rprouse** [comment]
It is inefficient to be creating the messages if they are not needed. I am trying to get 3.2 out this week. I will try to get this in, but no promises :smile:

**Comment by CharliePoole** [comment]
This occurs in ConstraintResult's constructor, when it executes

```C#
this.Description = constraint.Description;
```

Both SameAsConstraint and EqualConstraint override Description in a way that only does work when the Description is actually needed. However, ConstraintResult is getting it whether it will need it or not, since it is only accessed in case of failure, at least currently.

This could be mitigated by having ConstraintResult store the constraint rather than its description and pass the get request for Description through to the constraint. This would fix the success case but not the failure case, which would trigger the exception that these folks create when ToString is used.

IMO, this is low pri and the fix to the success case is sufficient. It's entirely reasonable to assume that ToString() can be called on any object.

**Comment by sharwell** [comment]
> This would fix the success case but not the failure case, which would trigger the exception that these folks create when ToString is used.

I am only worried about fixing the success case. Failure is failure so it doesn't matter one way or the other. :smile:
