### ISSUE TITLE
Root Folder Structure Change suggestion

### ISSUE THREAD

**Issue by dicko2** [nunit/nunit#1303]
Hi Guys,

I am hoping i won't get too flamed for suggesting this as i know that folder structure discussion can be a bit touchy, so just throwing this out there :)

The root of the project is starting to get a lot of files. Most of them are build related, as time goes and we get more build automation i think this will only grow.

I would suggest moving the build related files to a build sub folder.

specifically the tools folder and all files starting with build* (build.cake, build.ps1, etc)

In the work I'm doing on the compact frame work build in appveyor i've trialed this already, and with a couple of modifications to the cake file it works fine.

One thing I noticed though is that there was an exclusion in the original .gitignore for a build folder. Not sure why. But another option that I have used in another project is to call the folder ".build".

What are peoples thoughts? and does anyone know why we had the exclusion for "build" in the gitignore?

Thanks,
Dicko

**Comment by CharliePoole** [comment]
I hate to use the reasoning "We've always done it this way." Let's say that there is a history behind this and it impacts __all__ of the nunit organization projects, not just nunit itself. We try to keep the structure fairly similar.

Actually, in nunit v2, I tried moving the NAnt scripts that did the build into a subdirectory. This turned out to be somewhat inconvenient when working from the command-line, so for 3.0 I kept them in the root. It may be possible to move some secondary files - those not invoked from the command line - to a subfolder, modifying the calling commands to find them there. I think we should do this on a case by case basis.

As far as solutions go, I've done it both ways. There's a lot to be said for a solutions folder, but it means that most of the source ends up in a directory that is not under the solution. Also, when somebody downloads the source, I think having the solution in the root is a bit more understandable for some users.

That's not to completely blow away the idea... I think we should remove some cruft  from the root and see what's left before working further on this. It should probably wait till after we branch the release though.

In working on your CF build, please don't combine it with this restructuring. We generally like to do one thing at a time as much as possible. If you combine two things and the review decides we need to merge one and hold off on the other then it causes extra work.

The build exclusion in .gitignore is a hold-over from V2 where we used the build directory to store the results of the NAnt build as opposed to bin, which was used by the VS projects.

**Comment by CharliePoole** [comment]
One problem with solutions in the root is that you also get a lot of files that go where the solution goes... .suo, etc. @rprouse what do you think of moving the install solution under install and the nunit solutions under src?

**Comment by rprouse** [comment]
Hmm, I like the idea of a clean folder, but it would also tend to conflict with the way I work on NUnit. My tendency is to launch a command prompt to the root folder. From there I can build, tests, open the solution in Visual Studio, run git commands, etc. without changing directories.

I could run the build by adding the directory and I could open the solutions by specifying the subdirectory they are in, but is the constant extra typing more friction than having the files in the root directory?

We also use `$(SolutionDir)` in many projects and walk down from there. If we move the solution files to the root of src for example, we will need to edit all of our project files. I also find having to put parent directories into our project files a bit distasteful, ``$(SolutionDir)..\bin\$(Configuration)` for example.

Also, if we end up splitting the repo, we will have fewer files in the root. I also think some files should always be in the root like CONTRIBUTING, LICENSE, etc.

I merged @charliepoole's PR removing unneeded files. I would also be fine with cleaning up a bit more like pushing the C++ mock assembly project closer to it's project files, moving the ICO, etc., but I'm not a fan of making it harder to find and/or use files for the sake of cleanliness.

Hope I am not flaming you too much, but I'm not a huge fan of the idea :smile:

**Comment by CharliePoole** [comment]
Moving the CPP solution would help a lot. It creates a number of side files.

**Comment by dicko2** [comment]
I think the solution in the root is fine for now, i understand the relative path dependencies would be a big change for msbuild to work, my concern was around the build related scripts, I'm going to pull out my crystal ball and say that we are going to get more of them. I've added one for the installing of CF framework on the build agent, I don't know what is over the horizon though, but with me hanging around I'm sure we'll get more build automation :+1: 

If you use the command line you would still need to be in the root you would just run "./build/build.ps1 -target testall" instead of "./build.ps1 -target testall". so "b" tab "b" tab tab tab instead of  "b" tab tab tab tab :smile: 

Is this a productivity loss though or irritating? I Guess is the question.

Might be one we can leave until it becomes an issue, but i've already done the work in a branch if we want it, wont be hard to redo in future.

**Comment by CharliePoole** [comment]
I'd be more inclined to leave the commands we actually type in the root and put any second-level commands used by them in a subdirectory. I suspect, however that different folks use different top.level commands. I tend to use build.cmd rather than the ps1 script, for example.

If you do any work on this, I suggest treating the rest of us as your users and finding out what we use. :-)

**Comment by dicko2** [comment]
Yep ok :smile: 

If we leave the script files in the root we'll end up back where we started i think. as files like the build.cake need to be (or its easier if they are) in the same folder as build, build.ps1, etc.

I can create the build folder though and start to stick any new scripts in there as you suggested, at the moment though there is only one new one, so at the point of adding more i'll do it then. Maybe able to move the tools folder in their that cake uses to make it a bit neater as well, but again i'll tackle that when I've got a new script to add next.

You guys don't run any command lines straight out of the tools folder yea? always via the build scripts in the root?

**Comment by rprouse** [comment]
I have switched to almost always using PowerShell as my command prompt, so I always use build.ps1. It is nice because it auto-completes the arguments for me. For example, if I type, `.\build.ps1 -T<TAB>` it auto-completes the `-Target`.

That said, is the build file really needed? It is just a script the calls build.sh which you can already run directly can't you?

**Comment by CharliePoole** [comment]
I primarily wrote build.cmd because I didn't want to be in powershell all
the time. I'm definitely a holdout as far as the benefits of powershell go.
Additionally, I wanted to be able to set the -Experimental option globally
on my 32-bit system rather than always typing it in. Other folks working on
nunit might have the same preference and/or problem.

I created the build shell script just to be consistent. It also allows for
fixed arguments set into an environment variable but I haven't really used
it that way. It could probably be dropped.
