### ISSUE TITLE
Drop support for void async methods

### ISSUE THREAD

**Issue by simoneb** [nunit/nunit#132]
I hate doing this but I've come to the conclusion that it's probably better to remove support for `async void` rather than trying to handle the corner cases that we might come across while supporting it, like #74.

The longer explanation is that although `async void` is designed to be used mainly or exclusively for event handlers, that is, operations that are invoked but not awaited, fire and forget, there is a way to wait until they are completed, but it's by means of non public APIs that involve replacing the synchronization context in which the tests run. 
As you can imagine this can have unintended consequences that are difficult to predict, one is #74 which is actually pretty simple but it's not something we had covered, that is using `Assert.That(async () => [some async lambda body]`) inside an `async void` method. That's because it mixes void and non void operations in the same context and the two don't play well together because the `async void` synchronization context tries to handle the non-void operations too, which is not what we want.

Now, there might be a way to solve this specific issue (although I didn't find it yet) and there is certainly a way to detect it and fail early, but I'm wondering if it wouldn't be better to just stop supporting `async void` in v3.

**Comment by onovotny** [comment]
Old issue but MSTest *does* support async void tests as does xUnit. xUnit does it by using a custom sync context to track it: https://github.com/xunit/xunit/blob/master/src/xunit.execution/Sdk/AsyncTestSyncContext.cs

**Comment by CharliePoole** [comment]
@onovotny Yup, that's how we supported it as well, until we decided to remove it, primarily because it introduces complexities and didn't seem to serve any useful purpose.

**Comment by onovotny** [comment]
Not really sure what the complexities were/are but the way I see it, it helps catch/prevent false passing tests.

I would certainly agree that it's bad form to have `async void` in a test method, but there's nothing that prevents it either. An `async void` test would also show as passing as no assertion exception would be caught by the time the method under test finished...that'd be wrong too.

Mostly having it there just serves to prevent people from accidently shooting themselves in the foot.

**Comment by CharliePoole** [comment]
It was a while back, and I can't quite remember either. Simone explains some of it in the comments here. We also had the impression, apparently wrong, that nobody else supported it.

You should now get an error message forcing you to make the method async Task so I don't see how it would would lead to false positives.

**Comment by onovotny** [comment]
Fair enough. I kind of figure that between logic to detect/warn against it or "just do it right", might as well just do it. Either way :)

**Comment by CharliePoole** [comment]
Yes, I can see you would think that, particularly since we had already implemented it once. But the incremental value of fixing the various problems with things like nested async lambdas versus just removing it pushed us to the latter. 

Bear in mind, back when we did this, we had to fly blind, without any documentation, prior art or guidance. So "just do it right" meant reverse engineering .NET. MS was telling us not to support it, because async void is just for "fire and forget" stuff. We probably did it in part because they said not to! Things change, I guess, since you say MSTest now supports it.

I don't see any particular benefit of revisiting it now though. Do you?

**Comment by onovotny** [comment]
I'd say that since you already have a warning system, there's no pressing need to change anything. That said, I'd say that since the other test frameworks do support it, it might be unexpected from someone migrating from MSTest. 

My personal opinion is that I didn't want to tell ppl what do do -- if we can engineer a solution that helps people avoid common mistakes then great. Just one less thing to trip people up.

**Comment by CharliePoole** [comment]
Yeah... my initial feeling when we implemented async void was that it was the most natural thing for people to do when first encountering async. That is, if someone has a public void test and they have to await something in it, the first thing they would think of would be async void!

It ran well while we had it (2.9.6 and 2.9.7 I think) except for conflicts when a void async method contained calls to async methods returning a task. As this issue explains, we gave it up as too much effort over a year ago. Notice that the issue was open for about six months without any user comments either pro or con. Sometimes you just have to make tradeoffs.

**Comment by rprouse** [comment]
According to the MSDN article, [Async Programming : Unit Testing Asynchronous Code](https://msdn.microsoft.com/en-us/magazine/dn818493.aspx), MSTest issues a warning for async void tests and that it does not provide a syncronization context leading me to believe that async void tests would not work properly under MSTest. Has this changed or am I reading it wrong?

The author, Steven Cleary also seems to agree with our decision stating that providing a SyncronizationContext changes the system under test. This and the difficult to solve edge cases we were running into were the main reasons we made the decision to drop async void support.

I also felt at the time that supporting async void sends the wrong message to developers and that issuing an error leads developers into the pit of success.

**Comment by rprouse** [comment]
I created the following tests using MSTest. If the test method is `async void` then no tests are found. It works if I change it to `async Task`.

```C#
[TestMethod]
public async void TestMethod1()
{
    var result = await LengthyOperationAsync();
    Assert.AreEqual(256, result);
}

public async Task<int> LengthyOperationAsync()
{
    await Task.Delay(1000);
    return 42;
}
```

**Comment by CharliePoole** [comment]
@rprouse Well there's certainly nothing like a test for getting at the heart of things :-)

**Comment by SoulFireMage** [comment]
I really needed this void support guys: extremely limited use case yet it was quite important. Is there no get around?

An area I need to test absolutely does not need to return anything but I can't structure the test to try it out. I'm working with the file system, have to use async and isCompleted to know when to get to the next operation as it fails by trying to carry on before the copy file stuff has been done.

It's a pain that this was dropped tbh - isn't there a work around for edge cases like mine?
