### ISSUE TITLE
Long testcase parameter name truncation makes reliable test identification impossible

### ISSUE THREAD

**Issue by remcomulder** [nunit/nunit#1331]
This issue was reported to me by an NCrunch user - http://forum.ncrunch.net/yaf_postsm8281_NUnit-duplicate-name-warning-without-duplicate-names.aspx#post8281

Basically, NUnit3 has code that truncates test case parameter names when they exceed a certain number of characters.  It's understood that this is for good reason - if someone writes a book in their testcase parameter, we don't want this cluttering up the UI with a really long test name.

Unfortunately, when more than one test case exists with the first few characters of a long parameter being the same, there is no way to tell these tests apart from each other across multiple discovery and execution runs.

Consider the following example:

```
using NUnit.Framework;

namespace NUnit.TestData
{
    public class TestCaseWithLongParameterName
    {
        [Test]
        [TestCase("1234567890 1234567890 1234567890 1234567890 AA", "1234567890")]
        [TestCase("1234567890 1234567890 1234567890 1234567890 BB", "1234567890")]
        public void ParameterizedTest(string a, string b)
        {
            StringAssert.Contains(b, a);
        }
    }
}
```

This code will report the following XML from the NUnit3 discovery:
`
 <test-suite type="TestFixture" id="1102" name="TestCaseWithLongParameterName" fullname="NUnit.TestData.TestCaseWithLongParameterName" classname="NUnit.TestData.TestCaseWithLongParameterName" runstate="Runnable" testcasecount="2">
            <test-suite type="ParameterizedMethod" id="1105" name="ParameterizedTest" fullname="NUnit.TestData.TestCaseWithLongParameterName.ParameterizedTest" runstate="Runnable" testcasecount="2">
               <test-case id="1103" name="ParameterizedTest(&quot;1234567890 1234567890 1234567890 123...&quot;,&quot;1234567890&quot;)" fullname="NUnit.TestData.TestCaseWithLongParameterName.ParameterizedTest(&quot;1234567890 1234567890 1234567890 123...&quot;,&quot;1234567890&quot;)" methodname="ParameterizedTest" classname="NUnit.TestData.TestCaseWithLongParameterName" runstate="Runnable" seed="965381202" />
               <test-case id="1104" name="ParameterizedTest(&quot;1234567890 1234567890 1234567890 123...&quot;,&quot;1234567890&quot;)" fullname="NUnit.TestData.TestCaseWithLongParameterName.ParameterizedTest(&quot;1234567890 1234567890 1234567890 123...&quot;,&quot;1234567890&quot;)" methodname="ParameterizedTest" classname="NUnit.TestData.TestCaseWithLongParameterName" runstate="Runnable" seed="2123137215" />
            </test-suite>
         </test-suite>
`
Note that aside from the 'seed' attribute (which is random) and the 'id' attribute (which cannot be relied on across different versions of a test assembly), both of these test cases are reported with exactly the same data.  This creates a problem for test runners such as NCrunch, as we have no way to correlate data for these test cases across sessions.

If there was a way we could report the full name of the test without truncation, perhaps as a separate attribute in the XML, it would be possible to solve this problem.

Something Xunit and Gallio both do is to algorithmically generate a unique identifier for each test based on all relevant input parameters (i.e. a hash).  In this way, the test can always be uniquely identified and have its data correlated even when other tests are added to suite or the test project is extensively changed.

**Comment by CharliePoole** [comment]
Users have complete control over how names are generated on a test by test basis. See https://github.com/nunit/dev/wiki/Generation-of-Test-Names In the case of the example you gave, you could set the test name to `{m}{a}` for the desired effect. We could consider exposing this more broadly, so that you didn't have to do it on each test case.

The id we use is an implementation detail that can be changed. Have you an algorithm to propose? I don't want to look at any source code that can't be used under our MIT license - although I could probably ask Jim or Brad to let me use there's in NUnit.

Potentially, we have more than one issue here, but let's see where we go with this first.

**Comment by remcomulder** [comment]
It's great that users are able to control the naming behaviour.  Unfortunately, most of them won't consider the post-processed names to be an important element in test identification under the hood, so I expect that the few people hit by this problem will still find it very confusing.

It would seem to me that we have three possible solutions to this:

1. Try to educate people on the relationship between test names and test identification, so that when they encounter this problem, there is a way that they can immediately resolve the problem.  I'll make sure that the NCrunch forum thread contains a solution to this, so for NCrunch purposes at least, I think we can consider this done - though I'm not sure if other runners experience a similar problem.

2. Implement a workaround in which there is an XML attribute containing the 'raw' name of the test without any processing.  This is rather ugly, though it would give us an immediate solution to the problem with probably not too much effort required.

3. Solve the test identification problem using a generated identifier.  This is by far the more complicated option with the greater risk of knock-on effects on test runners (I'm not sure how others are using the IDs at the moment).  The easiest way to do this is to just generate an MD5 or SHA1 hash using every element of the test that can make it unique (i.e. namespace, fixture class name, method name, parameter type names, parameter constant values, generic arguments, etc).  The hardest part of this will be making sure everything is reliably included in the hash.  The identifier for a test would probably then become a BASE64 encoded string that could be passed around in the same manner as the existing numeric IDs.

In present context, I would consider this to be a very niche problem.  I'm not sure how many people are specifying test case arguments that match for the first 40 characters and not for the rest.  I have no hard data on this.  I expect that implementing hash-based ID generation would likely give a 'stronger' model that would have advantages in future, though this is the only hole that I know currently impacts the NCrunch implementation.

**Comment by CharliePoole** [comment]
For item 1, the NUnit gui (under development) doesn't use the test names
for any purpose except display. Test selection always uses the id - as it
did in V2 as well. The console runner requires some use of test names or
other characteristics to select the test to run on the command line. That
poses a problem if you want to run just one test but i think most people
find ways to combine test name, class name, method name, category, etc. to
select the tests they want. And of course, they can give their tests a name
that doesn't even look like a method name if they like, and select
according to that. Visual Studio is the worst problem because it insists
that it must be possible to determine the identity of a test from it's
name. We already live with that though.

Item 2: If we were to add anything to the xml, I think it would be the
representation of the separate arguments. We already have className and
methodName attributes and there really is no such a thing as the "raw" test
name in nunit. Conceptually, a test name is a string that names a test and
nunit puts no requirements on it at all, not even uniqueness.

Item 3: The id we have is a simplification for the initial release. The
console runner has no need for it at all and the gui runner will initially
only need a unique id valid until the assembly is changed and reloaded.
That's all we ever had in V2, in fact. Externally, we define the id as a
string, which uniquely identifies a test across the set of assemblies being
run together. Any implementation that meets that minimum requirement can be
used. If some runner is assuming it will always be a string representation
of an integer, they are wrong and we'll be happy to break them. :-) I'd be
glad to have a stronger ID, one that could be used across reloads of the
tests, for example. A hash could do it if there wouldn't be any problem
with collisions, or if we could allow for them.

**Comment by CharliePoole** [comment]
I think we have two potential issues here:

1. Provide a global way to specify the naming pattern used by NUnit (command-line option, nunit setting, other?)

2. Modify test ID so that it remains valid for a given assembly, class, method and arguments, even if the assembly is modified and rebuilt.

I think both of these are useful features. @rprouse what do you think?

**Comment by CharliePoole** [comment]
Since the title of this one already references the name, I'll create a new issue.

**Comment by rprouse** [comment]
Nobody has picked this up and nobody else has asked for this so closing.
