### ISSUE TITLE
Collision on System.Func from nunit.framework with System.Core in .Net 3.5 (CS0433)

### ISSUE THREAD

**Issue by cdrnet** [nunit/nunit#1349]
**Problem**
When migrating the .Net 3.5 build of my test project from NUnit 2 to NUnit 3.2.0 I ran into the issue that `Func<T1,T2,TResult>` is defined twice, once in `nunit.framework` and once in `System.Core`. This lead to a compile time error whenever I'm trying to use this Func delegate directly within the test project:

> CS0433	The type 'Func<T1, T2, TResult>' exists in both 'System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'nunit.framework, Version=3.2.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb'

I cannot drop the reference to System.Core since it is apparently being added automatically by the build tools.

**Cause**
NUnit backports `Func<T1,T2,TResult>` in [Net20Compatibility.cs](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Compatibility/Net20Compatibility.cs#L35) because in .Net 2.0 it was not available yet. But it is part of System.Core since .Net 3.5.

NUnit used to have a build specifically for .Net 3.5 where this type was not back-ported, so everything worked fine. Unfortunately the .Net 3.5 build was removed in #512 #516, resulting in the .Net 2.0 build being used for .Net 3.5 and hence the collision.

**Workaround**
Might be possible to resolve the conflict with `extern alias` (currently verifying).

**Comment by cdrnet** [comment]
Update: technically the workaround works, but is quite ugly. Essentially I have to alias `nunit.framework` e.g. to `NUnitFramework`, and then in every file with test fixtures replace:

    using NUnit.Framework;

with

    extern alias NUnitFramework;
    using NUnitFramework.NUnit.Framework;

**Comment by rprouse** [comment]
Thanks for letting us know. Obviously, this was an unintended side-effect. When we add compatibility to the framework targeting 2.0, we sometimes forget that it will also be used in 3.0 and 3.5 projects.

I don't suppose that updating just your test projects to 4.0 is possible as a simpler workaround? Just asking because I want to better understand the reasons our users are continuing to use older versions of the .NET framework.

**Comment by cdrnet** [comment]
For context, this is for a [multi-platform library](http://numerics.mathdotnet.com/Compatibility.html) with a NuGet structure similar to NUnit.Framework, i.e. separate builds for .Net 3.5, .Net 4.0 and several PCL profiles. For each of those library builds we also have a matching unit test suite builds.

I could compile the 3.5 test cases against 4.0, but this would mean we would no longer test against the runtime and framework that it is actually used with and might miss some weird corner cases. Indeed, floating point numerics and functions can behave differently between platform versions (even more so on Mono).

Unfortunately we don't have much data, but it seems we still have quite a few .Net 3.5 users left (e.g. related to Unity3d) and would like to make sure we don't accidentally break anything for them.

**Comment by CharliePoole** [comment]
@rprouse I wonder how much we really gained in simplification in removing this build. Of course, it removed eight projects from the solution, but the differences in code were pretty small. Should we consider putting it back as the simplest way around this?

In this case, the alternatives are to replace Func with some delegate of our own or to put our definition into a different namespace. However, that wouldn't help @cdrnet until we do a new release, whereas we could put out a new package for 3.5 right away.

**Comment by SpaceKaya** [comment]
I am encounter this issue while migrating a .Net 4.6.1 test project to Nunit 2.6 to Nunit 3.2.0.0.

> CS0433	The type 'Func<T1, T2, TResult>' exists in both 'nunit.framework, Version=3.2.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

**Comment by rprouse** [comment]
Make sure your test project is referencing the .NET 4.5 version of the framework, not the 2.0 version. That will cause the error. If using NuGet, try removing and re-adding the reference. 

On Mar 28, 2016 9:42 PM, SpaceKaya <notifications@github.com> wrote:

I am encounter this issue while migrating a .Net 4.6.1 test project to Nunit 2.6 to Nunit 3.2.0.0.

CS0433 The type 'Func' exists in both 'nunit.framework, Version=3.2.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

**Comment by SpaceKaya** [comment]
Yup i check target framework is 4.6.1 not 2.0.

**Comment by nzain** [comment]
Coming from #44 (which may be invalid, can't compile because of this issue), I have the same problem not with Func<..> but with the class `ExtensionAttribute`.

@rprouse asked
> I don't suppose that updating just your test projects to 4.0 is possible as a simpler workaround? Just asking because I want to better understand the reasons our users are continuing to use older versions of the .NET framework.

I'm in such a miserable situation: Our customers use a set of expensive hardware (up to $200000 or more) for building construction sites. One part of this set is a customized Windows Phone 6.5 device. Windows Phone 6.5 support was dropped in VS 2010. Thus, our mobile solutions are stuck on VS2008 and, obviously, compact framework and net35. Shared code with recent projects needs to be backwards compatible... a nightmare, exactly.

Nevertheless, nunit is a great project with strong compatibility. Is it eventually possible to have your eight net20 projects target net35 instead and trigger builds for net35, net20 via MSBuild? You would have to include the `Net20Compatibility.cs` class conditionally for net20 builds via compilation symbols. 

    #if NET20
    ... compatibility class
    #endif

and then tell MSBuild to either compile for 3.5 or 2.0 (and then also add the compilation symbol to activate the compatibility class).
  
    msbuild YourSolution.sln /p:TargetFrameworkVersion=v3.5
    msbuild YourSolution.sln /p:TargetFrameworkVersion=v2.0 /p:DefineConstants="NET20"

Target different frameworks:
http://stackoverflow.com/questions/2419585/target-specific-version-of-net-with-msbuild

Define compilation symbols from MSBuild CLI
http://stackoverflow.com/questions/479979/msbuild-defining-conditional-compilation-symbols

**Comment by rprouse** [comment]
We originally removed the .NET 3.5 build of NUnit to make it easier to maintain the project. We analyzed the code and noticed that we had no .NET 3.5 specific code, so we thought it was safe to drop. In retrospect, that was a bad decision with unforeseen consequences as people are unfortunately finding.

NUnit has a strong culture of backwards compatibility, so I am going to move this into the 3.4 milestone and commit to restoring the .NET 3.5 build target. Users who need 3.5 support can expect a release by late June. Any users that need the functionality sooner will be able to use a 3.3 dev release once this issue is closed. Our builds of the master branch tend to be very stable, so I wouldn't hesitate to recommend them to users who need features early and understand the risks.

**Comment by nzain** [comment]
I've just built current master by simply removing the net20 compatibility class and switching to net35. I confirm, that this resolves my issue.

**Comment by bbi-yoyo** [comment]
I've just run into this issue as well. We target .NET 3.5 because we are building code for use with Unity 3D, as @cdrnet mentioned.

It surprised me that I couldn't resolve the error by adding explicit namespace resolution, e.g. "System.Func<double, double, double>", but I now see that nunit.framework.dll defines Func in the System namespace. My workaround was to redefine the Func delegate myself.

**Comment by rprouse** [comment]
@bbi-yoyo sorry for the problems. This will be fixed in 3.4 which will hopefully be out by the end of the month.

**Comment by bbi-yoyo** [comment]
Sounds good. I only had the issue in one source file, so the workaround was pretty simple once I figured out what to do.

**Comment by dlemon** [comment]
I have the same issue but in framework 4.5 and System.Collections.Concurrent.: error CS0433: The type 'System.Collections.Concurrent.ConcurrentQueue<T>' exists in both 'c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll' and 'b:\SuCo\test\SucoUnitTest\assets\nunit\bin\addins\tests\nunit.framework.dll'

**Comment by CharliePoole** [comment]
Please do not pile on to an issue with a different set of symptoms,
especially a closed issue. Your problem is with a different class and an
entirely different build of .NET. If we make a fix,it will involve changing
different code.

This (closed) issue was resolved by creating a separate build for .NET 3.5.

I have looked at the code and it doesn't appear that ConcurrentCollection
is part of our 4.5 framework build, it's only in the 2.0 and 3.5 builds.
Are you sure you are referencing the 4.5 build?

If you continue to think this is an issue, we can look into it further if
you'll create a new issue with the specific symptoms you have found.



2016-09-15 5:26 GMT-07:00 Dennis Lemon <notifications@github.com>:

**Comment by dlemon** [comment]
Hi Charlie,

It was a reference problem from my side, so actually the problem between
chair and terminal. Thank you for the hints and have a good weekend!

Mvg,

Dennis Lemon

Dumpling IT Services B.V.
Luchthavenweg 81
5657 EA Eindhoven

tel: +31 6 54357499
web:  http://dumpling.nl
encryption: my public key
<http://minsky.surfnet.nl:11371/pks/lookup?op=get&search=0x6D7767E3F63A308E>

2016-09-15 18:13 GMT+02:00 CharliePoole <notifications@github.com>:
