### ISSUE TITLE
Tests losing data setup on thread

### ISSUE THREAD

**Issue by rolyv** [nunit/nunit#1352]
After upgrading to 3.2, tests that expected mocks setup on the thread (i.e. System.Web.HttpContext.Current = SomeMockContext) start failing. The OneTimeSetup is setting correctly, but it's gone in the test. I'm getting NullReferenceExceptions in tests that were expecting it. These tests run fine after downgrading back to 3.0.1

**Comment by rprouse** [comment]
I believe this is happening because in 3.2, every test runs on a different thread. In 3.0.1, each test only runs on a different thread if it has to, for example if it requires a different apartment state, or has a timeout. Does this sound right?

We may want to add an attribute that forces all tests onto a single thread. As a workaround, can you set the MockContext in the SetUp?

**Comment by CharliePoole** [comment]
@rolyv What build of the framework are you using? Net-4.5? Portable? etc.

**Comment by rolyv** [comment]
NuGet package: <package id="NUnit" version="3.0.1" targetFramework="net461" />

So that references the nunit dll under lib/net45

**Comment by CharliePoole** [comment]
@rolyv @rprouse If we were to have an attribute on the fixture that meant "This fixture and all it's test methods must run on the same thread" what would we call it? I've thought of SingleThread, RunTestsOnSameThread, RunTests(RunTestsFlags.SameThread)

Would we also want one that said "Run all the methods on the same test worker?" We had a need for this in the issue that led to putting WorkerId in the TestContext. Possibilities: SingleAgent, SameWorker, RunTestsOnSameAgent, RunTests(RunTestsFlags.SameAgent)

I'm thinking it may also be time to rename RequiresThread attribute, which could be confusing in the context of these others. I'm thinking of OwnThread or SeparateThread. 

SameThread, of course, would imply SameAgent. My thinking is that we would make running on the same thread a default for non-parallel test case execution, provided that no test method attributes contradicted it. If we specified same thread, then we could give an error when such a contradictory attribute was used.

I'm not wedded to any names, but it does have to be unambiguous. For example, if we used SameThread, that might mean "Run me on the same thread as my parent" or "Run my children on the same thread that I'm using" and so it's not a good name.

What do you guys think? This won't all get done at once, but starting out with some names that go together will smooth the path forward.

**Comment by rolyv** [comment]
@CharliePoole @rprouse I guess I don't understand enough of all the permutations to give useful feedback. I'm having a hard time visualizing the hierarchy. Is it something like this:

    Agent
      |- Worker
           |- Thread

So a test running on same thread implies same worker and same agent?

**Comment by CharliePoole** [comment]
I was using "agent" too loosely to mean a TestWorker. It's really like:

```
Worker
  |- Worker Thread
       |- "Per-test" Thread
```

where "Per-test thread" is something I just made up. :-) The worker thread basically creates an extra thread to run the test under specific circumstances:
 * It needs to run in a different apartment
 * It has a timeout
 * It has a RequiresThread attribute, meaning it needs a separate thread no matter what

That's how it worked in 3.0.1 and will work again after I fix this issue. In 3.2, we started creating the extra thread under all circumstances, which is the source of the bug.

It's possible that the default behavior will be good enough for you, once I fix it. However, it seems like a good idea to let you specify on the fixture that all the tests __must__ run in the same thread so we can verify that's what is happening.

Specifying the same worker to be used for all tests would be useful for somebody who was using the worker id as a key to a dictionary, perhaps one that is created in a setup fixture. We had a separate issue about this. Probably SameAgent is a bad idea for a name, given that agent means something else in the NUnit architecture.

**Comment by CharliePoole** [comment]
It would be helpful to have a simplified example of one of your tests, showing what gets done in any SetUpFixture, in the TestFixture OneTimeSetUp, in SetUp and in the test itself.

**Comment by rprouse** [comment]
@CharliePoole, @rolyv's tests use `System.Web.HttpContext.Current` so likely aren't useful for us beyond external tests. What about pushing something into thread local storage in OneTimeSetup and testing it in the threads? Then again, I think the tests you have to ensure same thread are probably enough for these scenarios.

**Comment by CharliePoole** [comment]
Yes, but he is mocking it. So I'm wondering if certain Mock Object frameworks use TLS.

Additionally, if the user is the one using TLS, we might be able to provide them something else, a logical equivalent, that passes down through the TestContext and/or is associated with the active TestWorker.

Of course, we could just call it a day with what I have done and see what else comes up later. :-)

**Comment by rprouse** [comment]
I thought that it was `System.Web.HttpContext.Current` that was using TLS, I think that is how it gets the Current out of a static.

**Comment by CharliePoole** [comment]
That makes sense. If we could get the overall shape of where @rolyv is doing what, I could emulate the same behavior in a test class. It would be more of a functional test than a unit test, but still could be useful.

Any thoughts about allowing the test to make a demand for this behavior through an attribute?

**Comment by rprouse** [comment]
For the attribute, we have `RequiresThread`, so if we implement an Attribute to demand the current behaviour, then I would vote for the opposite of `SameThread`. Since it is the standard behaviour as we are now defining it, would it be in place to raise errors if the user attempts to use attributes that conflict with the behaviour like `Timeout`?

**Comment by CharliePoole** [comment]
I added a test using TestCase and removed some duplication.

**Comment by CharliePoole** [comment]
So, if you put SameThread on a fixture, is it supposed to mean "Run all my children on the same thread I use for one time setup?" Or does it mean "Run this fixture on the same thread as any higher-level setups?" That's the ambiguity I see. On the PR, I listed some alternatives. I like the names like RunTestsOnSameThread because they clarify (for me anyway) that we are talking about how the tests under this fixture get run. I could also go for a RunTests attribute that takes some flags we define. Depends on how many flags or separate attributes we may end up with.

RequiresThread isn't so ambiguous, but I think the name could be confusing once we added some other thread-related attributes. I lean toward deprecating it and coming up with a better name at some point.

**Comment by CharliePoole** [comment]
Yes, I think we should give an error, for examle, if you specify that all should run on one thread but then put on a timeout or a RequiresThread. Alternatively, we could just give a warning, skipping the test.

Probably, some user will want to run all the tests on one thread except for some tests. :-) I'd have to think about that.

**Comment by rprouse** [comment]
I don't want to over-engineer this too much and I also dislike the idea of deprecating attributes this early into 3.x. I don't remember anyone ever requesting that anything except a fixture run on a single thread. Maybe we need more, but I think the common scenario is like what we are seeing, expecting a test to run on the same thread as `OneTimeSetup`. I think our levels of parallelism confuse people a bit so don't want to add to that.

I think the new attribute should apply to methods to demand same thread as my fixture and on a fixture to demand that all children run on the same thread. Or maybe even just on the fixture since this is mainly for tests to run on the same thread as `OneTimeSetup`? If you don't like `SameThread`, what about `SingleThreaded` to imply all my children will run on the same thread?

We should probably add some tests with nested fixtures too.

**Comment by rolyv** [comment]
Regarding the question about my specific test, all I'm doing is:

     var context = new HttpContext(new HttpRequest(null, "http://fakeurl.com", null), new HttpResponse(null));
     System.Web.HttpContext.Current = context

I'm not entirely sure how System.Web.HttpContext is implemented. I don't think it's just straightforward TLS, since they do some magic Context switching stuff too. As you can see, I'm not using any mocking for this piece. And I'm skeptical that mocking would run into a problem with TLS.

**Comment by CharliePoole** [comment]
@rprouse RequiresThread isn't a new attribute. It has been around for a long time in V2. I considered removing it in 3.0 and didn't - probably should have. It's only use is for a test that would mess up other tests if it didn't get it's own thread. IOW, I don't think it has a big audience. I was trying to think of a name that would not tempt folks who are not part of that audience to use it. But it's a separate issue so long as none of our new attributes depend on it.

SingleThreaded would work for me on a fixture. Another option I just thought of is SingleThreadedTestFixtureAttribute, which would work just like TestFixtureAttribute but require everything to run on a single thread. That's an interesting approach. Both of these alternatives tell me that it's the fixture itself requiring a certain behavior. I could go with either one.

Allowing an attribute on the method seems unnecessary but if we had one I think it should be different. An attribute that has different meanings on a fixture versus a method sounds confusing.

Currently, we don't treat nested fixtures as being "under" the parent fixture although issue #25 saays that we should. So, right now there is no relation between the OneTimeSetUp of the enclosing fixture and the nested fixture. Ideally, there should be, but it's a major change in how we run tests.

**Comment by CharliePoole** [comment]
So you set the context in the OneTimeSetUp and expect to retrieve it in the tests?

**Comment by rolyv** [comment]
Yes, when testing code related to MVC framework, I suspect it must be common to have code that looks at the HttpContext. My test was calling an Action that happened to look for something on the HttpContext. Not sure if there are other/better ways, but we've been doing that for a while and it's worked for us.

**Comment by CharliePoole** [comment]
Great! Thanks for the info. Not a web guy myself.

**Comment by rprouse** [comment]
I like the idea of `SingleThreadedTestFixtureAttribute` or maybe a Property on `TestFixture` so we don't pollute the namespace too much? `TestFixture( SingleThreaded = true )`?

**Comment by CharliePoole** [comment]
If you have a parameterized fixture, you would have to specify that property on every fixture, which is a bit inconvenient. If you have a separate attribute __and__ we make that attribute applies to each fixture, then you just need the one.

We have been inconsistent about this in the past but I am thinking that something that may need to have different values for each test case or fixture instance should be a property of the attribute that creates instances (TestFixture, TestCase, etc.) while anything that has to be the same for all instances or cases ought to be an attribute.

This business of needing everything to run on the same thread is intrinsic to the way that the user has implemented the fixture, so I think it ought to be a separte attribute. This may require a bit of work in ensuring that it applies to each fixture rather than the suite containing all the fixtures. In that way it's analogous to #548, which deals with test cases rather than fixtures.

**Comment by CharliePoole** [comment]
Following my logic above, I guess I'm back to @rprouse 's original suggestion of `SingleThreaded`. I'll build some code using that and we can see how it looks to us.

**Comment by luca-piccioni** [comment]
I'd like to push more on this issue. Since I've upgraded my tests to NUnit 3.2 (from nuget, just like the OP), I noticed that the test methods OneTimeSetUp, SetUp OneTimeTearDown and the Test methods runs on different threads. Indeed I'm here to expose my issues related with this behavior.

For my use, it is ESSENTIAL that all methods related to a TestFixture runs on the very same thread. Since some OS resources are very sensitive about the calling thread (especially graphical resources, such as device contexts, GPU contexts, ...).

Additionally I use heavily TLS ([i.e.](https://github.com/luca-piccioni/OpenGL.Net/blob/master/OpenGL.Net/Gl.Delegates.cs)).

**Comment by CharliePoole** [comment]
Strangely, your comment only shows up in email, not on GitHub. So I'll
reply the same way.

We are definitely doing this. PR #1357 has the code. Best thing you can do
is review what I've done and comment on it.

Charlie

**Comment by CharliePoole** [comment]
I've merged it as is. If any tests under a SingleThreaded fixture has any attributes that would normally cause the test to run on a separate thread, the attribute is silently ignored. I'm pretty sure we are going to want to mark these as NotRunnable at some point, but I haven't done it.

The cancellation issue raised in the PR discussion by @oznetmaster will need to be dealt with as soon as we have some reproducible failures.
