### ISSUE TITLE
TestContext.CurrentContext.Test.Properties does not contain value(s) from PropertyAttribute when using TestCaseAttribute

### ISSUE THREAD

**Issue by corsairmarks** [nunit/nunit#1358]
NUnit version: 3.2.0 (from[ NuGet](https://www.nuget.org/packages/NUnit/3.2.0))

Test execution: Visual Studio adapter

Steps to reproduce:
1. Create a test method marked with `[TestCase]` and `[Property("key", "value")]`
2. Executed the test
3. Inspect the value of `TestContext.Current.Test.Properties` - it will be an empty collection, where it should have 1 value

Code example (failing test):

``` csharp
[TestCase(5)]
[Property("Answer", 42)]
public void TestCaseCanAccessItsOwnProperties(int x)
{
    Assert.That(TestContext.CurrentContext.Test.Properties.Get("Answer"), Is.EqualTo(42));
}
```

Previously reported on [LaunchPad](https://bugs.launchpad.net/nunit-3.0/+bug/1082039)

This does not appear to be the same bug as #548 or #796.

**Comment by corsairmarks** [comment]
I am working on this issue, my work can be previewed here: corsairmarks/nunit@a2baec0d138ff151f4a9041ae6041f482cdf4de1

I'm not sure this is the right approach, so I am currently looking through the NUnit source and learning how and build-up of a `[TestCase]` differs from a `[Test]`.

**Comment by corsairmarks** [comment]
I have now also tested this with the console runner.

nunit3-console.exe version: 3.2.0 (installed using with Windows msi installer)
Command: `nunit3-console.exe .\Sample.Test.dll`
Code that was executed: corsairmarks/sample-test-framework@1e30e2b6462326bbf9943164c61f68b23bc3571e

Output (note how `test-suite` "TestMethod4_TestCaseAttribute" shows the properties at the suite level, but they do not show for the `test-case` "TestMethod4_TestCaseAttribute()"):

```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="2" testcasecount="6" result="Passed" total="6" passed="6" failed="0" inconclusive="0" skipped="0" asserts="6" engine-version="3.2.0.0" clr-version="4.0.30319.42000" start-time="2016-03-18 17:42:44Z" end-time="2016-03-18 17:42:44Z" duration="0.128479">
  <command-line><![CDATA["C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" .\Sample.Test.dll]]></command-line>
  <test-suite type="Assembly" id="0-1010" name="Sample.Test.dll" fullname="C:\Source\git\sample-test-framework\src\Sample.Test\bin\Debug\Sample.Test.dll" runstate="Runnable" testcasecount="6" result="Passed" start-time="2016-03-18 17:42:44Z" end-time="2016-03-18 17:42:44Z" duration="0.039621" total="6" passed="6" failed="0" inconclusive="0" skipped="0" asserts="6">
    <environment framework-version="3.2.0.0" clr-version="4.0.30319.42000" os-version="Microsoft Windows NT 10.0.10586.0" platform="Win32NT" cwd="C:\Source\git\sample-test-framework\src\Sample.Test\bin\Debug" machine-name="DURANDAL" user="butchern" user-domain="DURANDAL" culture="en-US" uiculture="en-US" os-architecture="x64" />
    <settings>
      <setting name="WorkDirectory" value="C:\Source\git\sample-test-framework\src\Sample.Test\bin\Debug" />
      <setting name="ImageRuntimeVersion" value="4.0.30319" />
      <setting name="ImageTargetFrameworkName" value=".NETFramework,Version=v4.5" />
      <setting name="ImageRequiresX86" value="False" />
      <setting name="ImageRequiresDefaultAppDomainAssemblyResolver" value="False" />
      <setting name="NumberOfTestWorkers" value="8" />
    </settings>
    <properties>
      <property name="_PID" value="26364" />
      <property name="_APPDOMAIN" value="test-domain-" />
    </properties>
    <test-suite type="TestSuite" id="0-1011" name="Sample" fullname="Sample" runstate="Runnable" testcasecount="6" result="Passed" start-time="2016-03-18 17:42:44Z" end-time="2016-03-18 17:42:44Z" duration="0.029111" total="6" passed="6" failed="0" inconclusive="0" skipped="0" asserts="6">
      <test-suite type="TestSuite" id="0-1012" name="Test" fullname="Sample.Test" runstate="Runnable" testcasecount="6" result="Passed" start-time="2016-03-18 17:42:44Z" end-time="2016-03-18 17:42:44Z" duration="0.028970" total="6" passed="6" failed="0" inconclusive="0" skipped="0" asserts="6">
        <test-suite type="TestFixture" id="0-1000" name="NUnitAttributeExample" fullname="Sample.Test.NUnitAttributeExample" classname="Sample.Test.NUnitAttributeExample" runstate="Runnable" testcasecount="4" result="Passed" start-time="2016-03-18 17:42:44Z" end-time="2016-03-18 17:42:44Z" duration="0.024032" total="4" passed="4" failed="0" inconclusive="0" skipped="0" asserts="4">
          <properties>
            <property name="TestOf" value="Sample.Foo" />
          </properties>
          <test-case id="0-1001" name="TestMethod1" fullname="Sample.Test.NUnitAttributeExample.TestMethod1" methodname="TestMethod1" classname="Sample.Test.NUnitAttributeExample" runstate="Runnable" seed="798259755" result="Passed" start-time="2016-03-18 17:42:44Z" end-time="2016-03-18 17:42:44Z" duration="0.009839" asserts="1">
            <properties>
              <property name="TestIdPropertyKey" value="WorkItem1" />
            </properties>
            <output><![CDATA[Prepare() TestMethod1 (TestMethod1): WorkItem1
Complete()
]]></output>
          </test-case>
          <test-case id="0-1002" name="TestMethod2" fullname="Sample.Test.NUnitAttributeExample.TestMethod2" methodname="TestMethod2" classname="Sample.Test.NUnitAttributeExample" runstate="Runnable" seed="1630670862" result="Passed" start-time="2016-03-18 17:42:44Z" end-time="2016-03-18 17:42:44Z" duration="0.000263" asserts="1">
            <properties>
              <property name="TestIdPropertyKey" value="WorkItem2" />
            </properties>
            <output><![CDATA[Prepare() TestMethod2 (TestMethod2): WorkItem2
Complete()
]]></output>
          </test-case>
          <test-case id="0-1003" name="TestMethod3_TestAttribute" fullname="Sample.Test.NUnitAttributeExample.TestMethod3_TestAttribute" methodname="TestMethod3_TestAttribute" classname="Sample.Test.NUnitAttributeExample" runstate="Runnable" seed="993609143" result="Passed" start-time="2016-03-18 17:42:44Z" end-time="2016-03-18 17:42:44Z" duration="0.000279" asserts="1">
            <properties>
              <property name="TestIdPropertyKey" value="WorkItem3" />
            </properties>
            <output><![CDATA[Prepare() TestMethod3_TestAttribute (TestMethod3_TestAttribute): WorkItem3
Complete()
]]></output>
          </test-case>
          <test-suite type="ParameterizedMethod" id="0-1005" name="TestMethod3_TestCaseAttribute" fullname="Sample.Test.NUnitAttributeExample.TestMethod3_TestCaseAttribute" runstate="Runnable" testcasecount="1" result="Passed" start-time="2016-03-18 17:42:44Z" end-time="2016-03-18 17:42:44Z" duration="0.002440" total="1" passed="1" failed="0" inconclusive="0" skipped="0" asserts="1">
            <properties>
              <property name="TestIdPropertyKey" value="WorkItem3" />
            </properties>
            <test-case id="0-1004" name="TestMethod3_TestCaseAttribute()" fullname="Sample.Test.NUnitAttributeExample.TestMethod3_TestCaseAttribute()" methodname="TestMethod3_TestCaseAttribute" classname="Sample.Test.NUnitAttributeExample" runstate="Runnable" seed="277322916" result="Passed" start-time="2016-03-18 17:42:44Z" end-time="2016-03-18 17:42:44Z" duration="0.000283" asserts="1">
              <output><![CDATA[Prepare() TestMethod3_TestCaseAttribute() (TestMethod3_TestCaseAttribute): 
Complete()
]]></output>
            </test-case>
          </test-suite>
        </test-suite>
        <test-suite type="TestFixture" id="0-1006" name="NUnitSetUpTearDownExample" fullname="Sample.Test.NUnitSetUpTearDownExample" classname="Sample.Test.NUnitSetUpTearDownExample" runstate="Runnable" testcasecount="2" result="Passed" start-time="2016-03-18 17:42:44Z" end-time="2016-03-18 17:42:44Z" duration="0.002920" total="2" passed="2" failed="0" inconclusive="0" skipped="0" asserts="2">
          <properties>
            <property name="TestOf" value="Sample.Foo" />
          </properties>
          <test-case id="0-1007" name="TestMethod4_TestAttribute" fullname="Sample.Test.NUnitSetUpTearDownExample.TestMethod4_TestAttribute" methodname="TestMethod4_TestAttribute" classname="Sample.Test.NUnitSetUpTearDownExample" runstate="Runnable" seed="994105559" result="Passed" start-time="2016-03-18 17:42:44Z" end-time="2016-03-18 17:42:44Z" duration="0.001717" asserts="1">
            <properties>
              <property name="TestIdPropertyKey" value="WorkItem4" />
            </properties>
            <output><![CDATA[Prepare() TestMethod4_TestAttribute (TestMethod4_TestAttribute): WorkItem4
Complete()
]]></output>
          </test-case>
          <test-suite type="ParameterizedMethod" id="0-1009" name="TestMethod4_TestCaseAttribute" fullname="Sample.Test.NUnitSetUpTearDownExample.TestMethod4_TestCaseAttribute" runstate="Runnable" testcasecount="1" result="Passed" start-time="2016-03-18 17:42:44Z" end-time="2016-03-18 17:42:44Z" duration="0.000477" total="1" passed="1" failed="0" inconclusive="0" skipped="0" asserts="1">
            <properties>
              <property name="TestIdPropertyKey" value="WorkItem4" />
            </properties>
            <test-case id="0-1008" name="TestMethod4_TestCaseAttribute()" fullname="Sample.Test.NUnitSetUpTearDownExample.TestMethod4_TestCaseAttribute()" methodname="TestMethod4_TestCaseAttribute" classname="Sample.Test.NUnitSetUpTearDownExample" runstate="Runnable" seed="1553621128" result="Passed" start-time="2016-03-18 17:42:44Z" end-time="2016-03-18 17:42:44Z" duration="0.000215" asserts="1">
              <output><![CDATA[Prepare() TestMethod4_TestCaseAttribute() (TestMethod4_TestCaseAttribute): 
Complete()
]]></output>
            </test-case>
          </test-suite>
        </test-suite>
      </test-suite>
    </test-suite>
  </test-suite>
</test-run>
```

**Comment by CharliePoole** [comment]
First off, could you explain why you don't feel this is the same as #548? 

Also, in terms of the approach, note that your code introduces the Properties of the test into DefaultNUnitTestCaseBuilder, which previously didn't know about properties. That's because it's the attributes themselves that are responsible for applying values to tests.

So, if we were to take your approach of "updating" each test with it's parent attributes, we would be more likely to do something like

```C#
foreach (TestMethod test in tests)
{
    test.ApplyAttributesToTest(method.MethodInfo);
}
```

The question is whether this should be in addition to or in place of the existing line of code that precedes your addition. If we keep that line, the each attribute will have to decide how to handle collisions of values. I think most of them already do that, but it will require a lot of testing.

I've given this some thought and it seems to me that this is a fairly broad issue. If we have a bunch of test cases (TestCaseAttribute, TestCaseSourceAttribute) along with other property-related attributes on a method. Are those properties intended to apply to the containing suite or to each of the individual tests?

Currently, we follow the literal approach and apply them to the test suite that corresponds to the method - not to the individual cases that correspond to the method plus its arguments. In many cases, we may be wrong about this choice. So should we go the other way?

I would say... Maybe! I think it's probably a case for examining each individual attribute. However, applying them to the test case will probably break somebody's code. We will look into it further, for sure and I'd be happy for you to keep working with us on it.

**Comment by CharliePoole** [comment]
In general, all attributes that modify the test work the same way. They implement `IApplyToTest`, which is the interface called at the point in time when we have created a test and want to apply attributes to it. The difference with test cases is that they are grouped in a suite. It's a question of how the interface is called, which determines what test they apply themselves to.

**Comment by corsairmarks** [comment]
It ultimately seems to be related to the same code and hierarchical issues raised in #548.  I considered this separate because the Google group discussion for #548 seemed to be desiring attributes from a fixture to be inherited by its member tests.  In this case, I'm interested in ensuring the inheritance of attributes from a `TestCase` to all of its parameterized children that are constructed as tests (which is an implementation detail from my view as a consumer).  I viewed the difference between a `TestFixture` and `TestCase` as significant.

My (potentially flawed) understanding is that a `TestAttribute` and `TestCaseAttribute` are both supposed to signal a test execution, they both live inside a fixture, and the significant difference is parameterization.  Thus the correct level to add properties for all TestCases using a given method seemed to be on the method itself.

Thanks for the tip on `IApplyToTest` - I originally took the approach you noted (`test.ApplyAttributesToTest(method.MethodInfo)`) and all the NUnit tests still passed.  However, I was very leery that it could cause a lot of unintended side-effects by applying everything from a TestCase so I opted to propose Property copying only.  This does introduce knowledge of property inheritance, which I also dislike, but it was a targeted change with less change of unexpected side-effects.

Your reasoning for not jumping to make the change is strong - it would change existing behavior pretty significantly.  What can I do to help test this?  Look at the potential impacts of applying `IApplyToTest` to any descendant tests?  Would making the code change you indicate have implications for building a fixture?  I spent some time in the code, but it wasn't apparent to me whether the same code would be called building a fixture or a test suite for a TestCase.

Or should this be sidestepped by an approach similar to previous proposals to add a "ParentContext" to `TestContext`?  I saw on your notes for #548 and you seemed to reject this approach because of the nesting implications and tests potentially querying up the chain.

**Comment by CharliePoole** [comment]
Actually, #548 deals with the ParameterizedMethodSuite that is created when you use a parameterized test case. It's a suite without a fixture that represents the method and all it's individual cases. Issue #796 addresses the issue of properties set on a test fixture.

You're right to say that the two issues are analogous. They need to be solved in the same way to avoid confusing users. The key difference is that properties on a test fixture are available to your tests in the OneTImeSetUp method while those on a ParameterizedMethodSuite are not user-accessible at all, which makes the matter somewhat more difficult for the user!

I don't see this as an entirely simple problem in the general case. Any property that influences how a test is executed should really not be copied to it's children. If the test case builder were to contain the knowledge of which properties are in this category it would be a violation of the SRP. It's the attributes themselves that are supposed to know what they do and how they are applied, not some external builder. On a practical level, this would mean that the builder would have to be modified as new attributes were introduced. Of course, this isn't possible in the case of custom attributes created by the user. So we need a way for attributes to apply to the child tests either instead of or in addition to the test on which they are placed. Probably, this calls for the introduction of a new interface similar to IApplyToTest. In some ways it's a more complex situation, but if it preserves NUnit's capacity to be extended by users it's worth the extra complexity. Plus, it makes the builder simpler!

Since NUnit 3.0 is relatively new, we can probably focus most heavily on the behavior of our existing attributes. Basically, we need to do some design grudge work: listing all the attributes that use IApplyToTest and deciding if it's appropriate to apply that attribute to children when on a fixture or a parameterized test method. In the case of fixtures, we have to consider simple, parameterized and generic fixtures as well.

Example (very easy one): DescriptionAttribute. IMO...
 * It should apply to a simple TestFixture
 * It should apply to every instance of a parameterized or generic fixture
 * It should not apply to the test methods contained in the fixture

Once we have examined all this, we will be able to generalize categories of behavior. Of course, many devs would start out by generalizing. I call this generalizing from no cases. :-)

One way to examine this is to just do it on (e-)paper. Another way, since we are coders after all, would be to add tests for how we think it should be done to ApplyToTestTests.

**Comment by corsairmarks** [comment]
I'll plan to get started on some unit tests to indicate how I think the various `IApplyToTest` implementations should (or should not) be inherited.  With the code in hand, it should be easy for me to do a little write-up here too.

As for a new interface, I would initially consider something like `IApplyToChildTests` that inherits from `IApplyToTest` with a method like `ApplyToChildTests(ITest)` or `ApplyToChildTests(IList<ITest>)`.  I'll think on it as I am going through all the current attributes.

**Comment by CharliePoole** [comment]
Sounds like a good start with the tests. Even if some currently fail, they will provide a spec for how this should work.

As for interfaces, I've been thinking in the same terms. We'll see what we need.

**Comment by neodim4ik** [comment]
Hi,
Are there any updates on this? 
I'm faced with this issue, can't use "Properties" and "TestCase" attributes in the same test.

**Comment by rprouse** [comment]
Sorry, nobody has looked at this yet, but we do take PRs if it is important to you.

**Comment by jnm2** [comment]
@CharliePoole This is another use case where an API would be helpful to find the nearest value of a given property, starting with the current test node and moving upwards to the root of the tree.

**Comment by neodim4ik** [comment]
@rprouse , thanks for quick reply.I think this is not important any more for me, I find out workaround.

Previously I used attribute Property for tagging tests and process test tag in Tear Down section, but now I added my own attribute and do processing inside attribute class, so I don't have problems with getting attribute value.

**Comment by CharliePoole** [comment]
@jnm2 It could be treated that way. However I kept it open rather than marking it duplicate because this seems like a special case. The fact that we create a suite for all the cases under the method is an arbitrary decision we made. We could have placed the cases directly under the fixture. Since the position of the attribute makes it look to the user as if it will apply to all the cases, I wondered if we might make it a bit easier in the particular case. I haven't figured out the details, it's just a sense I have that this use is somewhat different.

**Comment by OlegBaslak** [comment]
Hi all,
Are there still no updates on the issue?

**Comment by CharliePoole** [comment]
No one has assigned it to themselves or offered a PR, which I'd basically how low priority issues get resolved.

**Comment by jnm2** [comment]
Confirming, what we want to do is copy all properties from parameterized method suite tests to each child test case?

And parameterized fixture suites are different, so this doesn't apply to them. They go directly inside the namespace suite IIRC. (Though that is something I've often wished would change to be like parameterized methods.)

**Comment by CharliePoole** [comment]
Reading back, I have to laugh at this, by me: "Since NUnit 3.0 is relatively new, ..." That was much more true 2.5 years ago when I wrote it!

This issue is about parameterized method suites. Back in 2016, I suggested that somebody go through all our attributes, which apply to methods, and evaluate whether they could all be handled by copying to the child cases. I gave the example of one attribute, `DescriptionAttribute` where that would not make sense in my view. Since then, nobody has taken on the task. We have a relatively small set of attributes to look at. Doesn't anyone want to do the analysis of what happens if we do the copy in each case? That would free this up for somebody to work on.

**Comment by jnm2** [comment]
@CharliePoole 

> Doesn't anyone want to do the analysis of what happens if we do the copy in each case? That would free this up for somebody to work on.

Absolutely, will do.  My first question though is how we know whether to copy properties added by users' custom attributes. Would we need a way to allow such attributes to opt in or out of this, or could we just copy all except a hardcoded list?

**Comment by CharliePoole** [comment]
@jnm2 I don't have an immediate opinion. If all of our own attributes fall definitively into one category or the other (copyable vs non-copyable) then I would be willing to bet that user attributes can go the same way. If our own attributes are split, then an option is needed for both kinds of attributes.

I feel like there is a strong likelihood that __for parameterized method suites__ the attributes will all be copyable. IMO, it's not so simple for test fixtures, if we get to that. But let's make a list and see.

**Comment by nvborisenko** [comment]
I am surprised that test item doesn't "inherit" parent's attributes (categories, properties). Usually I use these attributes to describe tests. Then I would apply some logic in test based on attributes. To quickly apply attributes for all "test items" in class, I apply them to class, and expect that all inner tests will have attributes. I was wrong.

At second time I was surprised when saw how many github issues are related to this topic.

Hmm. And now I am blocked with task how to copy attributes from parents.

**Comment by CharliePoole** [comment]
@nvborisenko Consider the simple example I gave a few years back. A Description you apply to a fixture might be "Tests of the XYZ Class." Individual Tests in that fixture might be described as "Make sure XYZ.SomeMethod works correctly" or they might not have a description at all. So I would __not__ expect that attribute to be "inherited." If anything, I would want to access it through something like `TestContext.Fixture.Properties`.

Other attributes have inherited behavior, so we could allow them to be inherited without a problem. Still others inherit behavior but that behavior may be overridden.

Additionally, some attributes might accumulate (you could have more than one of the) while others would be unique, so lower level attributes would have to override them or be forbidden.

IMO, it has to be decided on an attribute by attribute basis for existing built-in attributes. That would give us a model upon which to build, I believe. It's a simple idea but nobody has been willing to take on the task so far... care to try? :smiling_imp: 

Deciding how to do it first, without looking at the individual cases, would be an example of what I often refer to in my coaching as "generalization from no cases." :smile:

**Comment by CharliePoole** [comment]
@nvborisenko BTW... in the specific case of Categories, inheriting them would completely change the logic of how tests are selected to be run. It could have been done that way up front, but it wasn't and I'm doubtful it can be done now without breaking existing behavior.

The category on a fixture may determine that that fixture is run. But other categories on the individual tests could cause them to be skipped.

This issue around inheritance of attributes is something I'm thinking hard about for my next framework.

**Comment by nvborisenko** [comment]
Honestly it's quite clear for me the "inheritance" of properties from end user. I use properties/categories as tagging tests with "labels/tags". When I tag fixture/suite/class, I expect that it is applied to children too.

Let's be more specific:
```csharp
[Category(Cat1)]
class A
{
  public void Test()
  {  }
}
```
Regarding filtering tests for execution: it's not clear how the inheritance impacts the selection of tests for execution because I am able explicitly set the same category to test like
```csharp
[Category(Cat1)]
class A
{
  [Category(Cat1)]
  public void Test()
  {  }
}
```
If I use this code, should I break a behavior of tests filtering? Not sure.. even if I break something it should be existing bug in nunit. So I assume that explicit assigning categories to tests should not introduce bugs in framework. If this is true, we can move forward, otherwise let's move forward with issues.

What if we let users to decide whether "inherit" properties/categories or not.
```csharp
[Category("Cat1", ApplyToChildren = true)] // or some enumeration of strategies of inheritance (like concatenate, replace, anything, just to be more flexible in inheritance topic)
```
This is not a breaking change, supports previous behavior, and introduces possibility to apply categories to inner tests **implicitly**. Seems easy to implement.

@CharliePoole just my thoughts, might be stupid, sorry for that.

**Comment by CharliePoole** [comment]
@nvborisenko You seem to be arguing the merits of allowing some sort of inheritance. However, that's already been accepted for some time... this is after all an accepted issue! Your implementation suggestions are all reasonable as well.

I don't have time to work on this but I threw in my ideas for an approach for the benefit of whomever steps up to do it. Basically, I think a few hours spent in problem space would be useful before moving to to design and implement a solution. I'd like to see a list of existing "standard" properties that shows how each would / should be affected. But that's really up to the person who takes on the issue.

This is a volunteer project. For better or worse, nobody assigns issues to people. Rather, they are always self-assigned. So we need to wait for somebody to take the issue on. That could be a team member or an outside contributor. To get my vote, whoever does step up should first do that bit of review of existing properties I suggested.
