### ISSUE TITLE
NUnitLite Output Feature (PORTABLE) 

### ISSUE THREAD

**Issue by SMASH1337** [nunit/nunit#1364]
NUnitLite isn't able to output to a file (XML) and it should be able to.

**Comment by CharliePoole** [comment]
Please include the command line you used and the environment under which you used it.

**Comment by SMASH1337** [comment]
Sorry, looking at the source it looks like this was done on purpose and to do it would be a feature.

cmd: dotnet run
os: Windows 7
target: dnxcore50

**Comment by CharliePoole** [comment]
What do you actually type at the command-line?  `dotnet run` isn't a command-line for running nunitlite or your tests.

Let's start by figuring out what you have installed and how and where the source is located that you are looking at, since NUnitLite definitely supports writing the XML output file.

**Comment by SMASH1337** [comment]
So this is a dnxcore50 (PORTABLE) targeted project with NUnitLite. NUnitLite is ran buy running the application with "dotnet run".

Basically followed your tutorial: http://www.alteridem.net/2015/11/04/testing-net-core-using-nunit-3/
but instead of using coreclr I'm using dotnet (which is basically the same thing).

https://github.com/nunit/nunit/blob/master/src/NUnitFramework/nunitlite/TextRunner.cs#L279

Here is where you can see that build type PORTABLE is excluded from being able to output to xml.

Sorry, I wasn't very clear this is all about PORTABLE targets. Updated the title.

**Comment by CharliePoole** [comment]
OK, that explains it. it's not my tutorial but @rprouse 's, on his personal blog. Essentially Rob is showing you how to re-purpose NUnitLite as a temporary measure for running dnx tests until we get something that allows us to run such tests from the console runner. My guess is that the "something" we come up with while have nothing to do with NUnitLite.

When I was creating NUnitLite, I considered not even having a portable build since it seems clear that every individual runner will need to be non-portable. However, it seemed like a good idea to put as many of the building blocks of NUnitLite into a PCL in order that others might build runners based on it. 

As an example of what's possible - even though you can't use it directly - take a look at the nunitlite-runner for Silverlight. It's a net-4.5 console application but it links runs tests built against Silverlight. I can't tell you if the same sort of thing is doable with dnx, since that's not my platform, but it's a good example of how nunitlite is used as the base of an nunitlite-runner, with the runner providing features (console output in this case) that are not avaialable in the original platform.

@rprouse can you give some better info that's more directly applicable?

**Comment by rprouse** [comment]
As @CharliePoole says, the portable version of NUnitLite is intended to allow people to write their own lightweight test runners for platforms that we don't fully support yet. Not being able to write out the output is a known issue right now. It is #defined out in the code that you found because the file API's NUnit uses were not available in PCL. I've been planning on revisiting this once .NET Core settles down. As I'm sure you know if you are working with it, it has been a moving target.

It is getting pretty stable now, so I think I will circle back soon, probably after the announcements at //build at the end of the month.

**Comment by jorgebay** [comment]
As dotnet cli does not support filtering tests (https://github.com/dotnet/cli/issues/2252) yet, the only good way to run NUnit tests based on categories or other filters on .NET Core is NUnitLite.

To move forward with supporting output files in NUnitLite for PCL, we can either use an IO abstraction like https://github.com/dsplaisted/PCLStorage or write the output in a stream, passing the stream as `AutoRun.Execute()` method parameter.

**Comment by rprouse** [comment]
@jorgebay `dotnet test` does not support filtering tests using a common syntax for all runners, but it does pass command line options through to our runner which does support the `--where` command line option, so you **can** filter tests using `dotnet-test-nunit`.

Sorry, not well documented since `dotnet test` hides `dotnet-nunit-tests`'s command line help, but see nunit/dotnet-test-nunit#46 and nunit/dotnet-test-nunit#4 for how to do use our command line options and see what is supported.

**Comment by jorgebay** [comment]
Woot @rprouse that's really helpful, just what I needed!

**Comment by rprouse** [comment]
Glad I could help. The next beta of `dotnet-nunit-test` will have a `/?` command line option that bypasses the `dotnet` help and shows the NUnit help.

**Comment by CharliePoole** [comment]
@rprouse As we are dropping the portable build, can this be closed?

**Comment by rprouse** [comment]
@CharliePoole many of these Portable issues will be the same when it is converted to .NET Standard 1.0 or 1.3 with the difference that several of the issues can be fixed. That said, I think this one can be closed.
