### ISSUE TITLE
External comparer is not used when specifying tolerance via .Within

### ISSUE THREAD

**Issue by Karpuscul** [nunit/nunit#1369]
I see that when I specify tolerance the comparison is done by the default comparer. Here is my code:
 
`Assert.That(actualDateTime, Is.EqualTo(expectedDateTime).Using(new MyComparer()).Within(TimeSpan.FromMinutes(5));`

**Comment by rprouse** [comment]
This is an interesting edge case that would take some design. There is no way to pass the tolerance into your `IComparer` for you to use in your comparison. We could possible provide an `INunitComparer`, but that seems a bit contrived.

As a workaround, you could modify your comparer to construct it with the tolerance. That might be less fluent, but more explicit. Not all combinations of the fluent interface can work together, so I might be inclined to close as won't fix. Do you think the workaround is acceptable?

```C#
Assert.That(actualDateTime, Is.EqualTo(expectedDateTime).Using(new MyComparer(TimeSpan.FromMinutes(5));
```

**Comment by Karpuscul** [comment]
@rprouse Since you use Within and Using as decorators I believe you should provide support for both of them being used at the same time. Also, I don't think adding tolerance into my comparer would make sense. IComparer<T> interface should just answer the question if the value is exactly equal, greater than or less than the other value. Failing asserts with such comparator implementing tolerance would not have descriptive messages with the reason why the failure happened.

**Comment by rprouse** [comment]
I would disagree. You are saying that you want to compare equality using the `IComparer` that you provide but you also want NUnit to change the functionality of your equality comparison with a tolerance?

When you give NUnit an `IComparer` and apply it to an `EqualTo`, we assume that you are taking responsibility for the comparison. Unless we add the tolerance from the Within statement into the comparer, NUnit would have to handle the Within by performing multiple comparisons using your comparer and the expected value +/- the tolerance. That is possible for simple types and we tend to handle it for common types like DateTime, but the whole point of the `Using` statement is to support more complex types which NUnit has no knowledge of and cannot perform the tolerance calculations on.

To be honest, I'm not sure why you would even be providing your own `IComparer` for a `DateTime`. Can you provide more details on your actual use case?

**Comment by CharliePoole** [comment]
Up to now, we have not checked constraint modifiers (that's what .Using and .Within are) for consistency. We could do so for scalar comparisons, such as DateTime, but it's almost impossible to do for collections, since you can supply different comparers for use with each of several types that may be encountered.

Up to now, this hasn't been a problem for people. I think the question that @rprouse asks is the key one: why are you doing this and what do you expect NUnit to do? It seems like the only choices available are:
1. Ignore the tolerance
2. Ignore the using
3. Flag the whole thing as an error

From your description, it seems that you want the two approaches to cooperate in some way, but it's not clear how you believe that should work.

**Comment by CharliePoole** [comment]
Hypothetically, I suppose we could calculate the range of acceptibility for the value within tolerance and then use the IComparer for the greater than / less  than comparisons. But that seems like a highly unusual scenario. More important, in the case of DateTime, it seems unnecessary. However, if there is a reason you want to do this, please try to help us see it.

**Comment by rprouse** [comment]
I agree with @CharliePoole that the only possible solution using a straight IComparer is rare use case. I am going to close this as won't fix because there are several workarounds and I don't feel it is a good use of our time and it would make the code more complex and less maintainable.

@Karpuscul if you can provide us with a design and a good use case, I will be happy to reconsider.
