### ISSUE TITLE
Nunit3 console locking dll 

### ISSUE THREAD

**Issue by bhupeshdahal** [nunit/nunit#1385]
Hello, 

I am running test using nunit3 console and generating xml in old nunit2 format. When i build my project as the test's are running, i get an error on copy dll. Build works fine if i kill nunit processes.

**Comment by CharliePoole** [comment]
NUnit V2 used shadow copy by default so that you could modify an assembly while it's copy was still executing. NUnit 3 has it off by default but individual runners can turn it on.

The new NUnit 3 gui will turn on shadow copy because users often want to rebuild while the gui is up. In the case of the console runner, however, we didn't see such a need. You can turn on shadow copy when running the console runner by use of the `--shadowcopy` option.
