### ISSUE TITLE
Write out full exception details in failed / inconclusive test results

### ISSUE THREAD

**Issue by dandrejvv** [nunit/nunit#139]
Currently the NUnit exception output only prints out the **very basic exception message details**.
For the _summary view_ it is OK to just get the base exception's message, but please can the full output view write out ALL Exception information? (Information that encompass the entire exception hierarchy)

On some exceptions you will find "non standard" Exception class properties that contains very important and useful information.
An example would be Entity Framework: When it throws an `DbEntityValidationException` it has all the validation errors in a `ValidationErrors` property. 
Another more occurring exception is `FileNotFoundException` which has the `FileName` property that has the filename that cannot be found.

This will make spotting the issue much faster as you don't have to code additional try/catches in your tests or require you to fire up the debugger to check.

**Comment by Mitesh56** [comment]
Hello Charile,

i have some dependent test cases running in Nunit test framework.
I want to know if i can display the failure of any dependent test cases in the Errors and failures tab just below the Progress bar on running my testcase having dependency.

Thanks,
Mitesh

**Comment by rprouse** [comment]
@Mitesh56, how are you running your tests? If you are talking about the visual studio adapter, we don't have any control over the look of the test window or where information is displayed. The test window is part of visual studio and we just provide a plugin for it that allows it to run our tests.

**Comment by CharliePoole** [comment]
@rprouse Based on the mention of the errors and failures tab, my guess is that @Mitesh56 is talking about the NUnit 2.x GUI runner.

@Mitesh56 If that's the case, a similar answer applies. The GUI can only display what it receives from the NUnit core. It isn't handling an exception, but a message that was created by the core from the exception. So I think this really boils down to a question about how much info is provided in the case an exception.

Of course, we no longer work on NUnit 2.x and NUnit 3.0 does not have a gui but the same principle will apply: no runner can display anything unless the framework gives it the information.

If you would like to pursue this issue, it will have to be in NUnit 3.0. A separate issue from this closed one would make it simpler, but we can discuss it a while here to clarify.

My question is what do you mean by dependent test cases? NUnit doesn't have a dependency feature in 2.x and doesn't have one **yet** in 3.0. How would NUnit know that your test failed because of a dependency. IOW, what would you like to be able to do in your code?

**Comment by Mitesh56** [comment]
@CharliePoole and @rprouse You are right , i am using the Nunit 2.6 verison and i wanted to display information of failure of some dependent test cases in the Nunit GUI.

Regarding @CharliePoole  what i mean about dependent test cases is that i have created my own custom attributes which takes care of dependent test cases in Nunit similar to what JUnit dependson has.

Thanks for the reply
