### ISSUE TITLE
Class Level Category Missing from TestContext

### ISSUE THREAD

**Issue by brianhyder** [nunit/nunit#1396]
NUnit Version 3.2.0
Re-Sharper 10
VS: 2013 Update 4

Preface:
I did not know a good way to run purely through nunit3-console.exe to verify so please fee free to chastise me.

Issue:
We are looking upgrade from 2.6.4 to 3.2.0.  We were putting together a small class to demonstrate that we could leverage test categories to power some of the setup.  In the setup we leverage the `TestContext` in order to attempt to get the categories associated withe currently executing test.  The category attributes on the test class do not get put into the test context.  

Example class:

```
    [TestFixture][Category("a")]
    public class SampleTest
    {

        [SetUp]
        public void SetUp()
        {
            var properties = TestContext.CurrentContext.Test.Properties;

           //categories will only contain a single element, "b"
            var categories = properties["Category"] as IList <object>;
        }

        [Test]
        [Category("b")]
        public void SomeSampleTest()
        {
            //some test code
        }
    }
```

We tried running the test from the context of the class and the context of the single test method.  Neither of which seemed to change the result.  What we see is that only category "b" is inside of the test context, never "a"

**Comment by rprouse** [comment]
I've done some testing on this. You are correct that tests do not inherit the categories from their parent context, but this is the same behaviour as in 2.6. I am going to mark this issue as an idea for an enhancement. I can see it might be useful in some situations, can you explain how you would use it and what problems it solves for you?

As I see it, if we provided this, we could do one of two things, first, inherit properties from the parent, or expose the parent context from the current context so you can walk up the chain. I would be more inclined to do the later.

**Comment by rprouse** [comment]
@CharliePoole what do you think of the idea of adding the parent test to the TestContext to give people the flexibility to walk up the test hierarchy if they need to?

**Comment by CharliePoole** [comment]
@rprouse I think that's probably the best solution as it requires some extra work on the part of the user. :-) I say that because simply copying the categories could potentially be confusing and would also break the behavior of Explicit. Currently, an Explicit test under a fixture with a selected category is not run. If we copied the category, it would be run.

That said, I think that we should keep this as an idea to be fleshed out when somebody is actually willing to spend time on it. "Stuff" may come up in working the issue that pushes for a different direction.

I think this actually duplicates issue #796 even though #796 deals with Properties. Categories, of course, are implemented as a property.

Issues #1194 and #1358 deals essentially with the same thing, but from the point of view of a test case with properties on the method. I think that this may require slightly different handling, however.

We may want to straighten out some of the duplication here. I think that both problems, the one dealing with fixtures and the other with parameterized test cases, are things we want to fix and so are probably more than ideas. The uncertainty in this case is about how we want to fix them. I'll leave it to you to figure out how to categorize them but I would hope that anyone who works on them would propose an approach before giving us code to review.

**Comment by nadvolod** [comment]
Hello everyone, has there been any progress on this or any kind of work around? I'm dealing with this same issue. I'm using Author, Category, and a custom property attribute at the class level to better identify my test suite. However, all of these apply to each of the test methods and I'd love to be able to access that class data for each test method.

**Comment by CharliePoole** [comment]
This is still labelled as an idea, which is our way of saying we're considering it but it's not ready for anyone to work on. As I commented earlier, I think it's more than that.

@rprouse what's your thinking? Can this be a backlog item?

**Comment by fgreunen** [comment]
I've done the following and it works:

`protected TestContext fixtureContext;
        [TestFixtureSetUp]
        public void TestFixtureSetup()
        {
            fixtureContext = TestContext.CurrentContext;
        }
private ArrayList GetTestCategories()
        {
            return (ArrayList)fixtureContext.Test.Properties["_CATEGORIES"];
        }
`

**Comment by CharliePoole** [comment]
Yes, that certainly works.
