### ISSUE TITLE
Warning assertions?

### ISSUE THREAD

**Issue by ig-sinicyn** [nunit/nunit#1414]
Hi!

We are using the NUnit VS test runner to run some performance tests. Sometimes there is some information that should be passed to user (e.g. if test is run under old x64 JIT the results should not be used as a reason to change the code).
I do not want to fail the test just to notify user that he should ignore the output. Instead I'd prefrer to add a warning to the test results.

Is there any public API to do this? If no, any plans to add it?

Thanks!

**Comment by CharliePoole** [comment]
This duplicates #406.

However, once warning level assertions are added, there may still not be a satisfactory way to display them using the NUnit 3 VS Test Adapter. That's because VS already has fewer possible test outcomes than NUnit and having a warning level result would give us one more outcome that VS cannot distinguish.

**Comment by ig-sinicyn** [comment]
@CharliePoole 
>having a warning level result would give us one more outcome that VS cannot distinguish.
Agreed. However, that's better than nothing:)

P.S. It's actually possible to report warnings, although it's undocumented. Just throw an `IgnoreException` at the end of the test.

**Comment by CharliePoole** [comment]
That's sort of true. Except we can't be throwing anything in the adapter. We have to send a result to VS. For Ignored results we report a warning because VS doesn't understand Ignored and also because ignored tests are thought of as a type of warning.

When we have actual warnings, they will be displayed differently on the gui but mixed with ignored under VS.

As you say, it's better than nothing.:-)
