### ISSUE TITLE
SingleThreaded attribute should raise an error if a thread is required

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#1423]
The new `SingleThreaded` attribute would be more useful if it raised an error if a conflicting attribute that required a thread was used on a child test. Examples of such attributes are `Timeout` and the various thread related attributes, but it should be more generic and look at the requires thread property.

**Comment by CharliePoole** [comment]
Currently, we have the following implementation options:

1. Mark such a test as Invalid due to the conflicting attribute. It will be reported as an error and not executed. Most GUIs will display in red and count it as a failed/error test.

2. March such a test as Ignored for the same reason. It will be reported as a a warning and not executed. Most GUIs will report it in yellow and count it as a warning/ignored test.

We can try to detect it at load/discovery time but the easiest is to detect at run time. The difference is that with the runtime approach, the red/yellow in a GUI won't show up until the test is run. I'll try to do it at load time but fall back to run time if it's too complicated for now.

Note that we can't run the test with a warning because we don't have any Warning result state other than Ignore. In future we may have that ability too.

@nunit/core-team @nunit/contributors What do you think is best?

**Comment by rprouse** [comment]
Personally, I would call it an error since you specified single thread, but we cannot do it. I am not firm on that though. Do we have other attributes that do the same sort of thing? If so, we should be consistent.

**Comment by CharliePoole** [comment]
Nope, this is the first, which is why I wanted to raise the question... it
may set a precedent. I'm OK calling it an error, Failed:Invalid with a
message saying you can't do this in a single-threaded fixture.

**Comment by ChrisMaddock** [comment]
I'd also agree with Error/Invalid. It's programmer-implemented invalid state, from what I understand. If tests won't be run, that seems more serious with a warning. If you set up a Testcasesource with a non-static field, that makes an invalid test-suite, I think? This seems similar in my eyes, impossible config which can't be caught at compile time. Just at test level, rather than suite.

**Comment by ChrisMaddock** [comment]
Also, an ignored test would still return 0 through a console run, is that correct? That doesn't seem ideal.

**Comment by agray** [comment]
Hi Charlie, I would vote for Option 2 - mark as Warning.

Regards,

Andrew

**Comment by rprouse** [comment]
@agray why do you think it should only be a warning? I agree with @ChrisMaddock that it is a developer introduced error that should be flagged and dealt with as soon as possible since it is an incorrect test. Not trying to put you on the spot, but your reasoning will help with the final decision.

**Comment by oznetmaster** [comment]
I think it should be an error.

**Comment by agray** [comment]
I just felt that a skipped test would highlight that something was wrong,
happy to be overruled.

**Comment by CharliePoole** [comment]
I'll go with error then.
