### ISSUE TITLE
TestObjects are retained for lifetime of test run, causing high memory usage

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#1430]
This is the same symptoms as #1247 - with 3.2.1, we're finding the same high memory usage, and TestObjects not being disposed again. I'm not sure yet if this is a regression, or if #1367 was never disposing correctly.

Background: we run a patched version of 3.0.1, which disposes of the test objects, and test fixture reference in `WorkItem.WorkItemComplete()`. This manages the memory 'correctly'. In #1367, we moved this to `OneTimeTearDown()` to be more semantically correct, which seemed like it would be addressing the same problem. I don't know if freeing the references in OneTimeTearDown rather than WorkItemComplete caused a problem, or if this is a separate regression. 

Have a busy couple of weeks at work, but can look at this in the future - unless anyone else is able to beat me to it!

**Comment by CharliePoole** [comment]
@CrisMaddock it's OK to assign something to yourself but that means nobody will "beat you to it" because we don't work on stuff assigned to other people. So it depends on what you want to happen. I'll be on vacation. :-)

**Comment by ChrisMaddock** [comment]
@CharliePoole - Exactly why I didn't assign it myself. :-) More than happy for someone else to look in to it in the meantime, but I'll get round to it if not!

**Comment by CharliePoole** [comment]
@ChrisMaddock I thought I read something where you said you assigned it to yourself... must have been looking at too many different ones too quickly!

**Comment by YannTrevin** [comment]
Just to confirm that I still see too the same high memory usage in 3.2.1 as in 3.2.0. Like in the previous version, the memory load seems to increase more or less proportionally to the number of tests run, until an OutOfMemory exception is eventually thrown.

**Comment by chris-smith-zocdoc** [comment]
I performed some analysis using dotMemory and found two gc roots that could account for this, one from `TestMethod` and another at `TestExecutionContext`
![image](https://cloud.githubusercontent.com/assets/2537809/15812913/3c230c4e-2b88-11e6-81a6-2349510a0562.png)

The `TestMethod` root is the shortest 
![image](https://cloud.githubusercontent.com/assets/2537809/15812938/87ecedb6-2b88-11e6-9407-0c9c2f7fc062.png)


At a later point in time, well after I would have expected this fixture to have been gc'd, the gc roots have changed to this 
![image](https://cloud.githubusercontent.com/assets/2537809/15812976/fd4ac74a-2b88-11e6-8821-757954d133e0.png)



I'm only vaguely familiar with object graph inside nunit so I'd need more direction into where to look next. Happy to help out where I can

**Comment by CharliePoole** [comment]
I have verified that the fix made in PR #1367 is still in place.

See my last comment on issue #1247 for a possible hint at the source of the problem. My suspicion is that the two chains of references reinforce one another in such a way that the objects are never released. 

It's odd that #1367, which was a brute force fix, didn't do anything. One possibility is that OneTimeTearDown is not getting called as early as possible.

**Comment by chris-smith-zocdoc** [comment]
>  two chains of references reinforce one another in such a way that the objects are never released.

This appears to be the case. I believe the real culprit is either that [Test has a reference to Fixture](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/Tests/Test.cs#L275) or that [TestResult has a reference to Test](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/Results/TestResult.cs#L116)

The reason the user's test classes stick around so long is because they are rooted by the TestResults that the [TopLevelWorkItem](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Api/NUnitTestAssemblyRunner.cs#L227) references. 

```
NUnitTestAssemblyRunner > WorkItem > TestResult > Test > Fixture
```

The reason why the previous fix didn't work is because there are other test contexts, test results, and test fixtures that have (in)direct references to the test class. [Here's a copied context where the ref is never cleared](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/Execution/CompositeWorkItem.cs#L235)

Example of a test class being rooted by the suite result
![image](https://cloud.githubusercontent.com/assets/2537809/15883448/3958b7b8-2d16-11e6-9b92-b4fab02e8660.png)

**Comment by CharliePoole** [comment]
The reference to Fixture in Test is something I had hoped to eliminate. It's mostly redundant but I ran into trouble when I made a quick attempt at eliminating it. I rolled my changes back for another time. The clearing of the Fixture property was supposed to take care of this, but it looks like it's only happening for fixtures, not test cases.
