### ISSUE TITLE
 TestResult class needs to be thread-safe

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1434]
As any test finishes, on its own thread, it updates its own test result and adds that result to the parent Result. This is an obvious point where different threads can come into conflict, so the Children property of TestSuiteResult needs to be thread-safe. For the last child test of a parent, additional updates are done, which can ripple up the result hierarchy all the way to the top.

Additionally, the SetResult method should be examined since it is called on other occasions in addition to a call from within AddResult.

If it's reasonably easy, the whole class could be made thread-safe, but the above items seem to represent the minimum.

I'm calling this a bug, even though we have not had problems reported, since it's obvious that threading conflicts can occur. This should be fixed before we attempt to run test cases in parallel within a fixture, since that would increase the probability of a collision significantly.

**Comment by CharliePoole** [comment]
@oznetmaster If it's OK with you, let's move on to this issue, which seems to be the most critical one, continuing our discussion from #1425 here.

My participation is getting more and more limited as my trip approaches, but I'll try to keep responding where I can. @rprouse will have to take over my role generally.

The volume of usage of AddResult, as explained above, is rather significant, since every test but the topmost Assembly suite has to add it's result to the parent. Adding a child result changes the collection of child results, the resultstate and possibly message and the various totals that are maintained (passed, failed, etc.). So this method definitely needs a lock of it's own and would need it even if the collection itself were thread-safe.

Can you take a look and tell me what other info I can  give you so as to drive a decision?

**Comment by oznetmaster** [comment]
I am not sure the entire class needs a lock, if thread safe collections are used.

It appears that only AddResult and SetResult are an issue.

AddResult needs to be thread safe, for sure.  How that is accomplished depends on the decision about concurrent collections.

SetResult might need a lock, but since it only sets properties, and that setting is not dependent on anything except the parameters to SetResult, it may not be.  The only possible problem would be an inconsistent set of property values (ResultState, Message, StackTrace) if two different threads called SetResult at the same time.  With a lock, the values from the latest call would always be used.

Does AddToXml need to be thread safe?  I am not sure about its usage.

It does not seem that any other method or property has a thread safety issue.

**Comment by oznetmaster** [comment]
TestSuiteResult has its own thread safety issues, independent of TestResult which it derives from.  Specifically, the various properties which are count accumulators.  But those can be easily handled by the Interlocked class.

Does TestSuiteResult require thread safety as well?  Are there other classes derived from TestResult that might also have related thread safety issues?

**Comment by CharliePoole** [comment]
It may be that all the locking requirements have now moved to TestSuiteResult, since that's where AddResult is now located.

AddResult looks at the existing result and may it based on what is being added. For example, a failing result added to a passing result makes that parent result failing as well. Additionally, this is where all the counters are updated.

Off the top of my head, I would say that calls to SetResult or to initialize the counters in the first place that take place outside of AddResult are probably pretty safe. Only one thread, the owning thread, ever initiaizes a given result. The more I think about it, the more I suspect that AddResult is actually our sole problem. Of course, all the references to the other methods would have to be examined to ensure that that's true.

**Comment by oznetmaster** [comment]
Have you given any more thought to the inclusion of the mono or corefx concurrent collection in the builds prior to 4.0?

Once that is decided, I will start to make changes.

I have also been trying to figure out how to unit test these threading issues.  It does not seem trivial :(

**Comment by CharliePoole** [comment]
I thought I had succeeded in tossing that back to you. :-) I don't want to add any new libraries without a specific use. It sounds like you want us to make the decision in the abstract, in advance. I don't know how to do that without having some specific plan to use it. That's what we did with Mono.Cecil, for example.

As far as I understand it, we would be taking in some new source code, not a package, right? In that case, shouldn't we be doing it on a class-by-class basis, as we need specific collections?

**Comment by CharliePoole** [comment]
@rprouse With my imminent departure, you will have to step in and resolve this. :-)

**Comment by oznetmaster** [comment]
I would like to suggest we add just the mono ConcurrentQueue class to the pre 4.0 builds.  It will be very useful in making TestSuiteResult thread safe, as well as the dispatch queues.  It may be the only concurrent class we need to make available in those builds which do not have it.

**Comment by CharliePoole** [comment]
So the existing list of child results would become a queue? Have you verified that all our current calls to list methods will continue to work?

Presumably AddResult would still need a lock, since adding to the list is not all it does.

For the dispatch queues you would replace the existing lock? Do you see a maintenance advantage?

These are questions that come to mind for me. @rprouse will have to decide in the end.

**Comment by oznetmaster** [comment]
Yes, the existing list of child results would become a queue.  As far as I can tell, all we do is add results to the end of the list, enumerate over the list, and examine the front of the list, all of which can be done with a queue.

I think that AddResult could be done without a lock, since the updates to the aggregates could be done using Interlocked.Add.  If we use a lock on the method, then there may be no need for the ConcurrentQueue.

As to the dispatch queue, there is both a maintenance advantage (no need to worry about deadlock or possible missed thread issues), and a possible performance advantage.  However, using a ReadWriteLock may be a good solution as well.   I need to look more closely.  Using lock/Monitor is not the best solution, however.

**Comment by oznetmaster** [comment]
I still have no idea as to the best way to unit test these threading issues.  Any thoughts?

**Comment by CharliePoole** [comment]
Well, by definition, of course, it's not a unit test. However, we could throw a lot of data at it. See EventQueueTests as an example.
