### ISSUE TITLE
Cannot use Testcase attribute

### ISSUE THREAD

**Issue by warpten09025** [nunit/nunit#1440]
I read documentation at : http://nunit.org/index.php?p=testCase&r=2.5
but i cannot use [TestCase] like that . I'm using latest NUnit version .. Please help , i'm new to NUnit and i have multiple test data ..

**Comment by lundmikkel** [comment]
If you use the newest version of NUnit (3.2.1), you should read the newest documentation: https://github.com/nunit/docs/wiki/TestCase-Attribute.

**Comment by rprouse** [comment]
@warpten09025 you need to give us some example code to go by. I am going to close this because it isn't an issue but a question, but please feel free to post some code that we can help you with and what errors you are getting.

**Comment by warpten09025** [comment]
![image](https://cloud.githubusercontent.com/assets/15846336/14748950/e93fd566-08e6-11e6-82c5-c016aba37152.png)

Please take a look at this image please !

**Comment by warpten09025** [comment]
Nevermind !    I just  found NUnit.Framework and after using it , TestCase Attribute works now !

**Comment by warpten09025** [comment]
Hello guys ! I'm still having problem Test Result only show result for method NoParamConstructor() not show result for method DivideTest()  ???

**Comment by rprouse** [comment]
@warpten09025, you have added a reference to `Microsoft.VisualStudio.QualityTools` which is the Microsoft test framework. It is probably there because you created a new test project which is a Microsoft specific project type. This is causing your tests to be Microsoft tests, not NUnit tests.

I would suggest starting again.

- Delete your test project (delete from Visual Studio, then from Explorer)
- Install the NUnit test runner and templates, go to `Tools | Extensions`, search for NUnit

![image](https://cloud.githubusercontent.com/assets/493828/14753117/2f77802e-08a1-11e6-9273-06ff55087230.png)

- Restart Visual Studio
- Add a new project, `Visual C# | Test | NUnit 3 Unit Test Project`

![image](https://cloud.githubusercontent.com/assets/493828/14753163/75c69c36-08a1-11e6-8b48-1f02ea5cbd4b.png)

- Now you can add your DivideTest

**Comment by warpten09025** [comment]
Thank you very much rprouse . This solution totally solve my problem !!!
