### ISSUE TITLE
NunitLite (SL50) cannot be used in CI (params not working)

### ISSUE THREAD

**Issue by Stift** [nunit/nunit#1462]
Currently the NunitLite Runner for Silverlight does not work as expected. Parameters like --output or --teamcity do not work, because when they are actually used in the code by the runner, they are ignored because the specific code parts are excluded with directives.
Unfortunately the --help page shows these options as enabled.

The problem is that I don't get any result that can be parsed by any CI server. Neither XML or console ouput.

**Comment by CharliePoole** [comment]
That runner is very simple and was primarily created so we could run our own CI tests. As you probably noticed, it's not even mentionned in the docs.

The runner is a .NET 4.5 console application, but links to the Silverlight builds of nunitlite and nunit.framework. Silverlight, of course, doesn't support the console but does direct it's output back to the runner, which prints it.

Bottom line, to make these options work, we would have to implement them in the runner, probably copying the code from nunitlite to do so. It's doable but we need to figure out if we want to support the silverlight runner for general use.

**Comment by Stift** [comment]
I'm relatively sure, that I read in the docs that for silverlight you definetly have to take the nunitlite stuff (https://github.com/nunit/docs/wiki/Installation). I understand that you struggle with silverlight support, I think that is common sense nowadays. But currently you distribute nunit.sl50 and nunitlite.sl50 with nearly the latest version. How are they intended to use then, when there is no runner? For a silverlight project I can't create an exe, and the console-runner also does not work.

**Comment by CharliePoole** [comment]
The question of how to run Silorverlight tests has always been a rather open one, even in the original NUnitLite implementation. That's because we have never had any contributors who actually work in Silverlight. At one time I had a primitive implementation that worked with the Microsoft runner but we settled on the technique we use ourselves to test nunit - Silverlight tests are expected to be Silverlight applications that use NUnitLite. If you look at the nunit framework tests for silverlight, you will see that approach.

However, that only works on the desktop, not as a CI runner. So, a few months ago, I added the silverlight "runner", a console app that references silverlight and runs the tests m.ostly using Silverlight - but with a console available for display.

Neither approach to running Silverlight tests is documented, I'm afraid, so your confusion is understandable. To put it another way... we've  been waiting to hear from some Silverlight devs. :-)

**Comment by CharliePoole** [comment]
I'd definitely like to see us document what we do have and maybe add output redirection to the runner. In the longer run, I'd like to be able to run Silverlight tests from the console runern. Even though little new work is done with Silverlight these days, the exercise of making it work with the console runner would teach us something about the best way to interact with other platforms.

**Comment by rprouse** [comment]
Thanks for the idea, but we are spinning SL out into it's own repository and putting it into maintenance mode unless someone from the SL community wants to pick it up and move it forward.

**Comment by rprouse** [comment]
I have moved this issue to the SL repo if anyone decides to continue work on it.
