### ISSUE TITLE
Unable to load bcrypt.dll – NUnit 3.2.1

### ISSUE THREAD

**Issue by asherber** [nunit/nunit#1467]
Using NUnit 3.2.1, VS 2015 Update 2, Test Adapter 3.0.10. I have lately started getting this error when I try to run some unit tests:
```
Exception System.DllNotFoundException, Exception thrown executing tests in xxxTests.dll
Unable to load DLL 'bcrypt.dll': The specified path is invalid. (Exception from HRESULT: 0x800700A1)
```
If I go to the Test Explorer and choose Run All, then all my tests run fine. But if I choose a single test or group of tests, either in the Test Explorer or from a class file in the IDE, either run or debug, I get the bcrypt error.

This may have started after I installed the VS 2015 Update 2. Maybe I'll try uninstalling that.

**Comment by rprouse** [comment]
This issue might belong in the adapter repo, but let's leave it here until we can determine the root cause. Have you tried running all tests from the command line and then filtering tests on the command line? bcrypt is native and should always be in your path AFAIK (in Windows/System32). What sort of crypto calls are you making and through what library/api?

**Comment by asherber** [comment]
Thanks, I hadn't thought of the console runner. I can run the entire suite fine from the console, as well as individual tests, making this seem more likely to be an adapter issue.

I do have bcrypt.dll in c:\windows\system32. I'm not calling crypto directly, but I am using AWSSDK v3.

**Comment by asherber** [comment]
I am not able to replicate this with the same solution on other systems, so it must be something on my machine. Closing the issue.

**Comment by rprouse** [comment]
Thanks for letting us know.
