### ISSUE TITLE
This version of NUnit 3 is not a release version and is not compatible with TeamCity. 

### ISSUE THREAD

**Issue by Ashtonian** [nunit/nunit#1475]
Attempting to setup a project with an NUnit step in TC 9.1.6 and I get the following error:

"This version of NUnit 3 is not a release version and is not compatible with TeamCity. Please update NUnit to a newer release version." 

I installed nunit.install from choco which uses the latest .msi so I am a bit confused?

**Comment by rprouse** [comment]
I think TC had hard-coded version checking looking for 3.0.x, giving you that error if you use a newer version. Not sure if has been fixed. @NikolayPianikov can you confirm?

I am going to close this since it is a TeamCity issue, not an NUnit issue, but feel free to continue to discuss in this issue.

**Comment by NikolayPianikov** [comment]
Fixed in TC 9.1.7 and 10, see https://youtrack.jetbrains.com/issue/TW-44554

**Comment by rprouse** [comment]
Thanks @NikolayPianikov
