### ISSUE TITLE
Examine need for "synchronous" events in event queue

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1476]
Transferred from #1472.

Repeating @CharliePoole:

We should come back to this and examine the use or non-use of "synchronous" events. The whole idea of isolating test events through this queue is that they should be handled asynchronously and independently. I think the code for synchronous events may be left over from earlier implementations and may no longer be used.

**Comment by CharliePoole** [comment]
Here is the result of my review. @oznetmaster especially, please comment.

In NUnit V2 the three start events (RunStarted, SuiteStarted, TestStarted) are synchronous. That means it's not even possible to enqueue (for example) a TestStarted event unitl the SuiteStarted event has been pulled from the queue by the pumping thread.

The need for this arose when some users created TestListener addins that contained Console.Write statements. Such a statement would create a TestOutput event, which would then be enqueued. In order to avoid deadlock, it was necessary that the processing thread, which had dequeued the event, continue to hold a lock. That allowed it to enqueue further events.

Currently, we don't have output events, so this would not be a problem. I could remove the code now and I'm confident it won't cause a problem. However, I'm about to put the TestOutput event back in the system in order to deal with issue #1139, continuous test output.

@oznetmaster To my understanding, the changes you made to the queue should prevent such a deadlock from occuring. Consequently, I think I can remove the manual reset event and the whole notion of synchronous events from the code. To be safe, we should also add some tests where the dequeuing thread tries to enqueue a new event. Would you agree?

@NikolayPianikov You proposed replacing the entire queue structure with your ThreadScheduler code. How do you think it would perform in the situation described? If we do this, it will be at a later stage - I'm a big believer in taking small steps. :-)

**Comment by oznetmaster** [comment]
I believe that is the case.  I never understood why they were there in the first place, but I left them untouched.

**Comment by CharliePoole** [comment]
In that case, I'm removing it. High pri because it impacts other stuff being worked on.
