### ISSUE TITLE
Don't enforce [Timeout] when debugger is attached

### ISSUE THREAD

**Issue by roji** [nunit/nunit#1479]
When debugging a unit test, the [Timeout] attribute is a great pain as tests fail just because the programmer spends some time in a breakpoint. It probably make sense to disable [Timeout] (and probably also [Maxtime]) when a debugger is attached.

**Comment by oznetmaster** [comment]
Then how do you debug the Timeout attribute?

**Comment by roji** [comment]
How do you mean? Nothing's stopping you from debugging the test and looking at the time - but does it make sense for nunit to abort your thread while in debugging?

**Comment by rprouse** [comment]
I agree that this could be useful. We disable parallel runs in the adapter when debugging tests to stop jumping between tests as you step through code. We could look at `Debugger.IsAttached`, but I wonder if that will produce false positives in some situations? For example, we sometimes use ADPlus to create crash dumps on some types of exceptions to track down problems.

We could key it off the `--debug` command line in the console, but that wouldn't work for 3rd-Party tools.

I am going to mark this as design so that people can discuss how this should be implemented.

**Comment by roji** [comment]
Ah, I wasn't aware you guys sometimes attach a debugger in non-interactive scenarios.

I guess you could add a flag to control whether [Timeout] and [MaxTime] are respected.

**Comment by rprouse** [comment]
When I said 'we attach ADPlus' I was refering the the 'we' at work, not the NUnit team :smile: 

I was just trying to open for discussion times when `Debugger.IsAttached` may not work, but they might be such edge cases that we don't care.

**Comment by CharliePoole** [comment]
I could be wrong but I think we may have had code for this already, in WorkIng.cs. If so, it may have been dropped by mistake.

**Comment by ChrisSmith** [comment]
`Debugger.IsAttached` is how this feature is implemented in [System.Web](http://referencesource.microsoft.com/#System.Web/HttpContext.cs,1826) 

It looks like this was in [nunit v2](https://github.com/nunit/nunitv2/blob/1b549f4f8b067518c7b54a5b263679adb83ccda4/src/NUnitCore/core/TestThread.cs#L170) at some point but doesn't appear to be in nunit 3 AFAICT.  [WorkItem](https://github.com/nunit/nunit/blob/2827ff71007692301b638da3abdb5e42f159640a/src/NUnitFramework/framework/Internal/Execution/WorkItem.cs#L306) is probably where I would expect to see it

**Comment by CharliePoole** [comment]
@ChrisSmith Since WorkItem is a new class in V3, it may not have been implemented. As you know, V3 was new code and some features that seemed less essential were not implemented, figuring they would be requested if they were important.

I missed seeing @rprouse 's comment a wile back about Debugger.IsAttached. That approach always worked well for us before. @rprouse Shall we take this out of the idea category and make it a backlog item?

**Comment by rprouse** [comment]
Promoted to the backlog

**Comment by oznetmaster** [comment]
Commented in the commit, but no one seems to have noticed :(

I have a number of problems with this.

First, it should be optional (command line option perhaps?).

Second, it can totally hang the program if a debugger is attached. If there test is in a loop, say, and has timed out, then its thread is till running (the join did not take place). Therefore, calling thread.Join() now hangs the program on that Join call, which may never return.

**Comment by CharliePoole** [comment]
Commenting in already made commits is not only less likely to be noticed but a bit annoying. Commenting on the (closed) PR or on the issue preserves context, makes it easier to respond and is more likely to draw attention. Of course, the ideal solution would be to comment on the issue before the work is done or on the PR during it's review period, before it is actually merged!

As to the meat of your comment, NUnit has suppressed timeouts under the debugger since Version 2.5.5, which was released in April, 2010. The feature was added on user request, because it's difficult to step through the code in the presence of an active timeout. I know of no problems that have been reported as a result. With NUnit 3.0, we had neglected to include this feature, so I felt we were merely correcting an error with the current issue.

I haven't compared the code of the two (V2 and V3) implementations. Is there something different about the implementation in PR #1785 that causes your concerns, or are you objecting to the concept itself?

**Comment by rprouse** [comment]
I also don't think it should be a command line option. Most users who want this are using the Visual Studio adapter or third party runners that won't be setting command line options or test run properties.

By hang the program, do you mean that a test that should time out but is in an infinite loop will never end? If that is the case, then that is part of the point of this PR. The debugger is attached so you can just break execution and find out where it is hung without having to race to do so before the timeout.

Or am I missing something? As I said, I would expect that thread.Join() to hang until I finish debugging or kill the process. Does anything in this PR cause you not to be able to do that?
