### ISSUE TITLE
"Exception has been thrown by the target of an invocation" when running tests in NUnit.ConsoleRunner.3.2.1

### ISSUE THREAD

**Issue by JoshuaBurns** [nunit/nunit#1509]
For the last week I have been trying to move my tests to run in TeamCity. I am struggling to get test to 'finish' when I run them through NUnit.ConsoleRunner.3.2.1. What I am seeing when I run them locally through the Console runner is the tests appear to complete all their actions and my log files show that all test cases (and the `OneTimeTearDown`) are finishing. And yet when the Console Runner is supposed to generate results for me I get this. 
![nunitrunnerfailure](https://cloud.githubusercontent.com/assets/19497855/15443465/62b91e22-1e9d-11e6-8844-c4ccc0723914.PNG)

I would like to qualify this with this does not happen on every test suite I run in the Console Runner. Some finish and generate results, but I cannot find a pattern to this/what is triggering this. 

I am using NuGet for all the packages ![packages](https://cloud.githubusercontent.com/assets/19497855/15443418/fce1c356-1e9c-11e6-96bd-14438ac48939.PNG)

**Comment by CharliePoole** [comment]
If you're running with the console runner, why do you reference the adapter package?

**Comment by JoshuaBurns** [comment]
I am writing and running the tests also in VS and you suggested it to me in a StackOverflow question. 
http://stackoverflow.com/questions/36750830/webdriver-test-failing-setup-in-ie

**Comment by CharliePoole** [comment]
Sure... but the SO question was about the adapter.

I have actually never installed the nuget adapter package and the console package together in the same project. In principle, it should work so long as both packages use the same version of the engine, but that's not the case here. The final 3.0 adapter release (3.10) uses the 3.0 build of the engine because of an outstanding bug that only affects the adapter. The 3.2.1 console runner uses the 3.2.1 build of the engine.

My guess is that one or the other engine is ending up in your bin directory, depending on what actually gets built. Try temporarily removing the adapter package to confirm whether this is the source of your problem.

I have to admit that I never thought about this issue, since it doesn't match how I personally work. :-(

**Comment by CharliePoole** [comment]
@JoshuaBurns Have you tried the suggestion? Does it change anything?

**Comment by JoshuaBurns** [comment]
@CharliePoole  Sorry life came up and I will not be able to test this until tomorrow. Ill let you know how it goes.

**Comment by JoshuaBurns** [comment]
So I tested the suggestion of removing the adapter package and I am still getting the error. I am noticing that the issue always come up when output to the Console runner has stops coming through. I ran my suite multiple times today and sometimes it passed and when it did I was getting output (in the console runner) the entire time the test was running. And the tests that threw the exception all had their output randomly stop. The place where the output stopped seemed to change with each run.

**Comment by CharliePoole** [comment]
Is this all under TeamCity or sometimes standalone?

**Comment by JoshuaBurns** [comment]
standalone, I am running them the Console Runner through powershell

**Comment by CharliePoole** [comment]
What if you use the runner directly - i.e. is PS adding anything to the problem?

**Comment by JoshuaBurns** [comment]
Getting the same results

**Comment by CharliePoole** [comment]
We need more info about what actually causes the exception.

Is there any more info in the XML file?

Try running in process (--inprocess) and see if a verbose internal trace will give more info (--trace:Debug)

**Comment by JoshuaBurns** [comment]
So I am seeing interesting results when I run the tests with those options enabled. The tests are reporting! I have been testing this all morning different suites and with the options and without, and so far everytime I run the suite with `--inprocess --trace=Debug` I am not getting the "Exception has been thrown by the target of an invocation". And when I run the test without those options I am getting it. So far this has held true for each run today. Which is about 7 runs with options and 3 runs without. Would you still be interested in the xml reports for each of the different runs?

**Comment by CharliePoole** [comment]
So we know that this only happens when you run tests in a separate process, which happens to be the default! I'd be interested in seeing the output from that separate process, which you can get by using `--trace=Debug` (but not `--inprocess`). Several logs will be created... One for nunit3-console, one for the agent and one for the test domain created within the agent. It would be simplest if you reviewed them first as they can be large.

**Comment by JoshuaBurns** [comment]
Where should these logs be located I am having a hard time finding them.

**Comment by JoshuaBurns** [comment]
Not sure if I am looking in the right spot, in my '\packages\NUnit.ConsoleRunner.3.2.1' directory I am not seeing any logs and nothing is getting created in the '\packages\NUnit.ConsoleRunner.3.2.1\tools' either.

**Comment by CharliePoole** [comment]
I'm on my phone so I can't give you an exact location, but it's under Application Data. Look for NUnit.

**Comment by JoshuaBurns** [comment]
Hmm in my AppData\Roaming I have nothing for NUnit, and in the AppData\Local there is a folder but it does not contain any meaningful logs just Nunit30Settings.xml.

**Comment by CharliePoole** [comment]
AppData\Local should have a logs subdirectory. However, some versions of NUnit saved the logs in the directory from which you ran the tests - the same one that has TestResult.xml. I'm still not where I can look at the code very easily, unfortunately.

**Comment by JoshuaBurns** [comment]
Well, I am not sure where any of the logs are getting stored now. I removed old TestResult.xml files and a debug.log I found from the ConsoleRunner package directory and reran tests this morning both with `inprocess` and without. I am not seeing any new logs created in either the appdata\Local\NUnit dir or the Test Suite working dir. I also just tried searching my C:\ for "TestResult.xml" and it did not find anything :confused:

**Comment by CharliePoole** [comment]
Default is `--trace:Off` so no logs are created anywhere. Your console output tells you where TestResult.xml is getting saved. Your output indicates it's in the current directory at the time of execution.

**Comment by JoshuaBurns** [comment]
This was the only thing I could see that looked like it may be of some value. 
````
14:07:48.214 Debug [ 9] WorkItemDispatcher: Directly executing RegisterAndActivateNewUser
14:11:33.944 Error [ 8] TestProgressReporter: Exception processing POMAuctivaTest.TestSuite.NewUserTestSuite<FirefoxDriver>.RegisterAndActivateNewUser
System.Runtime.Remoting.RemotingException: Object '/3742bc21_6eb6_4710_861d_d06e30e9469f/gzkc3ewv3ziqu3co_sd1geil_1.rem' has been disconnected or does not exist at the server.

Server stack trace: 
   at System.Runtime.Remoting.Channels.ChannelServices.CheckDisconnectedOrCreateWellKnownObject(IMessage msg)
   at System.Runtime.Remoting.Channels.ChannelServices.DispatchMessage(IServerChannelSinkStack sinkStack, IMessage msg, IMessage& replyMsg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Engine.ITestEventListener.OnTestEvent(String report)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [1]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at System.Web.UI.ICallbackEventHandler.RaiseCallbackEvent(String eventArgument)
   at NUnit.Framework.Internal.TestProgressReporter.TestFinished(ITestResult result)
14:11:35.213 Info  [ 9] TestWorker: Worker#STA_NP executing PostSaleTestSuite<ChromeDriver>
14:11:35.217 Error [ 8] TestProgressReporter: Exception processing POMAuctivaTest.TestSuite.NewUserTestSuite<FirefoxDriver>
System.Runtime.Remoting.RemotingException: Object '/3742bc21_6eb6_4710_861d_d06e30e9469f/gzkc3ewv3ziqu3co_sd1geil_1.rem' has been disconnected or does not exist at the server.
````

**Comment by CharliePoole** [comment]
Well, that's definitely an NUnit log! It gives us some useful info, in part because of what's not there.

Notice that RegisterAndActivateNewUser starts to run at 14:07:48.214. About five minutes later, it tries to send a message back through TestProgressReporter. This indicates the test either succeeded or failed, and was returning from the remoting call. However, it isn't able to do so because the remote object (the console runner) has been disconnected.

This is the other side of the original error shown in your first post, where the agent process could no longer be reached. Since neither stack trace shows any actual error, we can conclude that the connection itself terminated. Most likely, it timed out.

I believe this is the same error fixed recently by PR #1489. To confirm that, you would have to either wait for a new release or download from our AppVeyor feed at http://ci.appveyor.com/nuget/nunit (take the latest build of master you find there)

**Comment by ivanball** [comment]
Good morning. Where can I download an nunit console with this issue fixed?

**Comment by CharliePoole** [comment]
This is an open issue, hence not fixed yet.

**Comment by DanZee** [comment]
For what it's worth - we had the same stack trace, also while running running under TeamCity. The issue appears to be fixed an by upgrade to 3.4.1 (from 3.2.1). Probably as per PR #1489?

**Comment by CharliePoole** [comment]
@DanZee Thanks, I'm going to take that as confirmation that it's fixed, not having heard from from the OP for a while. @JoshuaBurns If you find that 3.4.1 has not fixed this for you, let us know and we can revisit this.

**Comment by gonzalonewton** [comment]
I have similar error runing Nunit-Console 3.11.1

**Comment by mikkelbu** [comment]
Do you get the same strack-trace or the same message "Exception has been thrown by the target of an invocation" (meaning that an exception was thrown in reflected code). In either case it will be better to create a new issue, as the code has changed a lot the last 4 years.

**Comment by CharliePoole** [comment]
@gonzalonewton I'm afraid you won't get much attention by posting a short comment on a closed issue from 2016!

Longer explanation:
 * An NRE is probably the single most common exception that any piece of software throws. Just getting one isn't enough similiarity to help understand it. :disappointed: 
 * That particular problem was closed because the user didn't provide any response when asked, so even the original post didn't have enough information! :cry: 
 * As the comments show we felt it was a user-caused error anyway. So if you really had the same error, we would have to tell you the same thing. :sob: 
 * Unless you are running some very old versions, the underlying software is substantially different today than it was in 2016. :frowning_face: 

What to do: File an issue giving full information about what software you are using and what actually happens. :smiley:

**Comment by gonzalonewton** [comment]
Ok, I am Sorry, I'll open another issue. Thanks

**Comment by CharliePoole** [comment]
Not a big deal, but a common problem. Maybe I'll publish my list of points more widely. :smile:
