### ISSUE TITLE
Write partial results XML as tests happen instead of at the end

### ISSUE THREAD

**Issue by xen2** [nunit/nunit#1514]
Wouldn't it be good to write the .xml as tests are run instead of writing everything at the end? (and risk a process crash before we have a chance to write it)

Some Continuous Integration tools support reading partial xml, so it would also allow to display results earlier.

**Comment by CharliePoole** [comment]
Can you point to some tools that display partial XML?

**Comment by xen2** [comment]
So far TeamCity XML reporter does it (https://confluence.jetbrains.com/display/TCD9/XML+Report+Processing)

Note: I know there is a separate TeamCity mode existing already, but:
- this would make it work with other CI servers -- might need some work on CI plugins though (jenkins, etc...)
- also, our use case was that we run tests on Android and forward result back to our windows test runner and write XML (act like if Android unit tests ran locally). However, it might be that the new TcpWriter mode can support those cases. Does this new mode report results as they come or wait full completion?

**Comment by CharliePoole** [comment]
I thought we had discussed this previously, deciding that some sort of log was better than incremental XML. As it turns out, I had to go back to a discussion on the defunct nunit-users list in 2008 in order to find the discussion. Since it's no longer available online, I posted some excerpts here:

> Mark Mayo asked:
> Alternatively, a means of saving the results as it goes, or possibly
changing Nunit to write incremental XML output files?

> My response:
> We don't write the xml file incrementally although a feature
request was submitted just a few days ago asking for this.

>Pros (as I see them):
* If the test run hangs or crashes, we can see how far
  it got.
* Software (CI for example) can "watch" the progress
  of the tests

>Cons:
* It needs to be carefully thought out so we don't end
  up with XML-creation code all over the place.
* Using the most naïve implementation, the XML file would
  be invalid until we terminated it - which means we
  would need a smarter approach.

>One possibility is to NOT do this with the XML file but
to simply write a log of some kind. I'm not sure that
this would satisfy everyone though.

>Comment by Chris Wright
>That cannot be done incrementally. I take it nunit's xml is more
friendly to incremental output, if you're even mentioning the
possibility. But it would still be ugly. I think I prefer logging via
some non-XML format, on the whole.

A fair amount of discussion ensued and I ended up with the notion that we should implement some sort of log file that is written incrementally and is not in XML format. That would allow it to be viewed as text, without any special handling needed.

However, it doesn't look as if anything has actually been done on this since 2008. The Sourceforge Feature Request was never moved to Launchpad and therefore was not subsequently moved to GitHub.

I agree that we need something to refer to when the test run crashes or hangs. We do have an internal trace, but it aims more at recording errors in NUnit itself rather than test results.

The problems with creating our TestResult.xml file incrementally have actually grown. Now you can have multiple processes with multiple threads in each of them running tests. However, individual results are still sent back to the engine sequentially and from there to the console runner. We could write some sort of text record of the events. In fact, it could even be a `.txt` file containing the xml, which we already have. That would allow folks like me to just double-click it to view, which won't work with a partially complete xml file.

Is that an approach you can live with?

**Comment by rprouse** [comment]
One issue with this approach is that the NUnit test result file is hierarchical. In other words, a opening xml test node contains the overall result and test counts for all of it's children and so on down to the individual test. This would mean that we would have to constantly go back and update the parent nodes as tests completed. This would likely be very inefficient.

As I type this, I see @CharliePoole has also responded. I like the test log concept where we write out as each test completes and maybe when each test starts. It is complicated a bit by parallel execution, but I think it could work.

For now, I am going to mark this as idea and requires design so that we can flesh the idea out before implementing.

**Comment by CharliePoole** [comment]
@rprouse This relates - oddly enough - to the teamcity issue we have been discussing, where I brought up the idea of serializing all events that are issued by TestEventHandler. If that were first done, then logging would become trivial and could be done as an engine extension.

@xen2 tell us what you think about this direction.

**Comment by xen2** [comment]
Yes the idea sounds good, something similar to the TeamCityEventListener then (except this one doesn't mark stdout properly, we might want that if we want parallel output to be properly processed)

**Comment by CharliePoole** [comment]
@xen2 We'll follow up on the issue then.

As an aside, what do you mean by "this one doesn't forward stdout"

**Comment by xen2** [comment]
Sorry, I meant TeamCityEventListener doesn't process stdout (which would be a problem if they were running multithreaded, a listener wouldn't be sure what belong to what test -- but since it is single threaded it works fine)

**Comment by CharliePoole** [comment]
Here's a question... should NUnit __always__ log? Or should it be a command-line setting?

**Comment by CharliePoole** [comment]
@xen2 Actually, NUnit doesn't send stdout from tests to stdout. It captures it. All that goes out are events and all events are tagged with a test id.

**Comment by fandrei** [comment]
It also would be useful to write the textual output (into the file specified by the --out param) continuously.

**Comment by CharliePoole** [comment]
@fandrei NUnit results and textual output are handled by different parts of NUnit. For text output, see issue #1139 which was closed by PR #1536. The change will appear in the 3.4 release.

**Comment by bicarbon8** [comment]
Given this discussion ended a year ago there's probably been many changes, but it would seem you could output multiple .xml results files (one per parallel grouping) such that test methods run in parallel each get their own .xml (one .xml file per test method or _TestCase_ in the case of Data Driven test methods) while test assemblies run serially, but in parallel with other test assemblies would output each to their own .xml file (one .xml per assembly). A final step of the report generator could be to combine all these into one (though I'm not entirely sure that is needed given CI tools such as Jenkins can read in and collate results from multiple NUnit XML files).

**Comment by CharliePoole** [comment]
@bicarbon8 In a way, that's what we already do, minus the actual file. 😄 

Every test sends an XML result to the runner, which can do whatever it wants with it. None of our runners write them as files and I don't know of any third-party runner that does either, but it's certainly possible.

In our architecture, it's not the job of the framework to write files.

**Comment by rprouse** [comment]
I am closing old Idea issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
