### ISSUE TITLE
Microsoft.Jet.OLEDB.4.0 provider not registered only shows up on running test from Console

### ISSUE THREAD

**Issue by smfinvest** [nunit/nunit#1516]
I have a solution that uses Microsoft.Jet.OLEDB.4.0 to read Excel files into a C# program. When I run the tests in VS2015 it works splendidly. When I run it from a command line or through a Nant.build it fails as follows: System.InvalidOperationException : The 'Microsoft.ACE.12.0' provider is not registered on the local machine.
![image](https://cloud.githubusercontent.com/assets/10522764/15518309/f4003b8c-21c1-11e6-94f7-09a223d9abcc.png)
![image](https://cloud.githubusercontent.com/assets/10522764/15518526/f7727ebe-21c2-11e6-8ecf-e260e170dbd7.png)

My first thought was the issue with Mixed mode assemblies, but I have various config files modified with: (which helped get it to work on VS2015).

![image](https://cloud.githubusercontent.com/assets/10522764/15518475/ad08987c-21c2-11e6-9928-1332e7f3ec6e.png)

Not sure where to go from here.

**Comment by nzgh** [comment]
Looks like a 32-/64-bit issue. When you run your tests in VS2015 (32-bit application), they work because there is a 32-bit version of the Jet Engine installed on your system. When you run them from the command line (supposingly 64-bit), your tests fail because there is no 64-bit version of the Jet Engine installed.

**Suggestion 1:** Open 32-bit command prompt using **%windir%\SysWoW64\cmd.exe** and run your tests from there (in 32-bit mode).

**Suggestion 2:** Download and install Microsoft Access Database Engine 64-bit from
[https://www.microsoft.com/en-US/download/details.aspx?id=13255](url)

Hope this helps.

**Comment by rprouse** [comment]
Thanks for investigating @nzgh. :+1: 

@smfinvest can you let us know if this works for you so we can close this issue? Thanks.

**Comment by smfinvest** [comment]
Thanks so much. Suggestion 3 did the trick for us.

**Comment by eg-novelt** [comment]
Hello & thank you

This tickets comments helped me find a similar issue to a "provider is not registered" error due to 64 vs 32 bit (for the record it was a Microsoft.ACE.OLEDB.12.0 dll).

What worked though was not a flag but using the x86 version of the xunit runner:

`packages\xunit.runner.console.2.4.1\tools\net472\xunit.console.x86.exe`
