### ISSUE TITLE
Unable to acquire remote process agent calling MasterTestRunner.load()

### ISSUE THREAD

**Issue by ethantang95** [nunit/nunit#1527]
I am trying to execute NUnit programatically inside my C# code so I tried to create an runner instance inside the code itself to execute and run the tests.

The code snipplet is as such
`            
var testPackage = new TestPackage(@"C:\Users\ettang\Downloads\nunit-release-3.2.1\nunit-release-3.2.1\NUnitHackBox.cs\bin\Debug\NUnitHackBox.cs.exe");

    var serviceContext = new ServiceContext();

    serviceContext.Add(new ExtensionService());

    serviceContext.Add(new RuntimeFrameworkService());

    serviceContext.Add(new DefaultTestRunnerFactory());

    serviceContext.Add(new ProjectService());

    serviceContext.Add(new TestAgency());

    var testRunner = new MasterTestRunner(serviceContext, testPackage);

    testRunner.Load();

    var testResult = testRunner.Run(new TestListener(), TestFilter.Empty);
`

when calling testRunner.Load(), after 30 seconds, I get hit with unable to acquire remote process agent with the stack trace:

System.Exception: Unable to acquire remote process agent
   at NUnit.Engine.Runners.ProcessRunner.LoadPackage() in C:\Users\ettang\Downloads\nunit-release-3.2.1\nunit-release-3.2.1\src\NUnitEngine\nunit.engine\Runners\ProcessRunner.cs:line 111
   at NUnit.Engine.Runners.AbstractTestRunner.Load() in C:\Users\ettang\Downloads\nunit-release-3.2.1\nunit-release-3.2.1\src\NUnitEngine\nunit.engine\Runners\AbstractTestRunner.cs:line 183
   at NUnit.Engine.Runners.MasterTestRunner.LoadPackage() in C:\Users\ettang\Downloads\nunit-release-3.2.1\nunit-release-3.2.1\src\NUnitEngine\nunit.engine\Runners\MasterTestRunner.cs:line 100
   at NUnit.Engine.Runners.AbstractTestRunner.Load() in C:\Users\ettang\Downloads\nunit-release-3.2.1\nunit-release-3.2.1\src\NUnitEngine\nunit.engine\Runners\AbstractTestRunner.cs:line 183
   at NUnitHackBox.cs.Program.Main(String[] args) in C:\Users\ettang\Downloads\nunit-release-3.2.1\nunit-release-3.2.1\NUnitHackBox.cs\Program.cs:line 32

This is inside a windows environment running dotNET 4.5

Upon inspecting how the nunit-agent-x86.exe was being started, this is the passed on argument:
"219ce643-f132-4f0f-81e4-7831b0949218 tcp://127.0.0.1:0/TestAgency "

The executable nunit-agent-x86.exe is residing inside my bin/Debug folder for my project that I have copied from building a copy of this project.

Further inspecting into the execution of nunit-agent-x86.exe, it threw an exception when it is calling

`
Agency = Activator.GetObject(typeof(ITestAgency), AgencyUrl) as ITestAgency;
`

with the exception of {"Tcp channel url must have a port number: tcp://127.0.0.1:0/TestAgency"}

Any suggestions as to how should I get this working? Is the MasterTestRunner designed for such usage?

Overall, what I am trying to do is to invoke NUnit to run programatically inside my C# code. This is because I am writing an application to test projects using NUnit as its backbone testing framework.

**Comment by CharliePoole** [comment]
No MasterTestRunner is not designed to be used this way - or to be used by any external code for that matter.

In the past (NUnit V2) there was no published API for using NUnit programatically. So folks would ferret out a selection of internal classes and cobble something together. Sometimes it worked, sometimes not. We helped where we could, always warning against the use of undocumented, internal classes and methods, because there was no other alternative for those folks.

NUnit 3, on the other hand, does have a public and published API for running tests. That's what you should be using. If it doesn't do something you need, create an issue. If you can't figure it out, please ask on our discussion list.

The Engine API is  documented at https://github.com/nunit/docs/wiki/Test-Engine-API-Spec In spite of the comment at the top of the page, it's pretty accurate. You should not reference or construct any classes in the nunit.engine assembly. Only the nunit.engine.api assembly is intended to be referenced by your runner. Even our own console and gui runners use it that way. Use TestEngineActivator to get an interface to a an engine, which will be initialized automatically, and use that engine to get other interfaces, such as ITestRunner.

If you intend your runner to always use a specific engine version, you will want to make that engine available in your own code. OTOH, if you want to make use of whatever version of the engine is already installed on a system, you should not include any assemblies other than the api assembly.

**Comment by ethantang95** [comment]
Thank you, I managed to get it working but I am still a bit overwhelmed by the return values of the test results. Specifically, is there an API that parse the XML into some format that is better to work with or do I have to manually parse the XML itself?

**Comment by CharliePoole** [comment]
It's a design tradeoff we made. Having an object-based API that reflects the XML content would mean that changes in the framework had to be echoed on the client side as well.

I have done some work in the nunit-gui project, creating a very light-weight object wrapper around the XML. It only provides the most common properties directly, with additional methods for accessing other elements of the XML. It's a work in progress, but you can look at it's current state at 
 * https://github.com/nunit/nunit-gui/blob/master/src/nunit-gui/Model/TestNode.cs
 * https://github.com/nunit/nunit-gui/blob/master/src/nunit-gui/Model/ResultNode.cs

You'll find that with a few extra helper methods, working with the XML directly isn't that difficult. If you create your own object model, keep in mind that the XML format is designed to be flexible. New stuff may appear in every release.
