### ISSUE TITLE
Use of Sleep(0) in NUnit

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1528]
There seems to be a lot of use of Sleep(0) throughout NUnit.

Microsoft seems to really indicate that this is a bad practice:

[http://joeduffyblog.com/2006/08/22/priorityinduced-starvation-why-sleep1-is-better-than-sleep0-and-the-windows-balance-set-manager/](url)

Should we examine the usage and adjust accordingly?

**Comment by oznetmaster** [comment]
One possibility would be to replace Thread.Sleep(0) with Thread.Yield, but that is only available in .NET 4.0 and above.

A compatibility class could be added that does a Yield in 4.0 and above builds, and a Sleep(1) in other builds.

Not sure if this would make any difference in most NUnit usage or not.

**Comment by CharliePoole** [comment]
Based on the article (good find) I would replace all our `Sleep(0)` calls
with `Sleep(1)`. I'd be less inclined to use a compatibility class here,
since it would hide the fact that there is different behavior on the part
of the scheduler in each case. We could use brute force #if statements to
do a `Yield` on higher platforms, but I don't see a lot of payback form
that.

**Comment by oznetmaster** [comment]
Apparently, the only use of Sleep(0) is in EventQueue.cs!  So this is not really a relevant issue, since in that case both threads are always running at the same priority.

**Comment by oznetmaster** [comment]
Sleep(1) is used in in the framework tests in one place, so that is correct.
