### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1529]
Settings are always created as a `Dictionary<string, object>`, but are often passed as an` IDictionary`.  Sometime they are passed correctly as an `IDictionary<string, object>`.

I would think that all references to the Settings should be `IDictionary<string, object>`.

This will improve compile time checking, and will also improve the quality of the code generated when the Settings are accessed.

**Comment by CharliePoole** [comment]
I'm not completely sure which settings you mean as we use the name for several different dictionaries. But I agree with the general notion of always passing the interface. Perhaps the simplest explanation would be a pull request.

**Comment by oznetmaster** [comment]
Most of the time, the Interface is passed as IDictionary.  I think it should be passed as IDictionary<string, object>.  That is all that I am suggesting.

I will create a pull request.

**Comment by CharliePoole** [comment]
@oznetmaster I'm sorry to say I didn't understand your original proposal. If look at it online in GitHub, you will see that all the angle braces and everything between them disappear. So it seemed as if you were saying we were passing Dictionary rather than IDictionary.

From the code, I now see that you wanted to use `IDictionary<string, object>` rather than IDictionary. That takes a bit more thought, I think. I used IDictionary in the API deliberately, since it is a sort of lowest common denominator. If we change it to use the generic interface, then we have to be absolutely certain that we never will want to support a framework that doesn't have it. I'm not taking a side on the issue, but merely saying it's a pretty important one.

BTW, I have not edited your description to make the angle brackets appear, because I wanted you to see what it looks like and how I misunderstood what you wanted to do.

**Comment by CharliePoole** [comment]
@rprouse The semantics of the generic dictionary differ from that of the non-generic one. Among other things, the non-generic dictionary interface returns null when something is not found. Consequently, the code has to be examined when making this change.

**Comment by oznetmaster** [comment]
Yes, and it uncovered a single place where this caused a problem, and I fixed it.  Everywhere else that I can find, the code already correctly checks if the key is there before using it.

From my point of view, returning a null is a bad thing.  It can cover up a problem.

What frameworks do not have generic collections?

**Comment by oznetmaster** [comment]
If we ever find a framework which does not have IDictionary<TKey, TValue>, we can add the mono version if we need to.  But except for .NET 1.0, where is there such a framework?

**Comment by CharliePoole** [comment]
It would be silly for us to argue about whether `IDictionary<string, object>` is better. That's obvious.

However, we have suffered with obsolete interfaces for many years in order to maintain backward compatibility, and we'll suffer with other things in the future in order to keep providing useful software to users. The question is whether this is such a case and it's not appropriate that we failed to even ask the question but simply went ahead with the newer implementation because we like it better.

The two questions I laid out are what we have to answer, especially the first. If we are not changing the published API, then there is no reason not to do this. If we are changing it, then I would say it's out of the question, given that we only just established that API. Changing things just because you want to, without regard for compatibility, is what Microsoft and Google do - not, I would hope, nunit.

I deliberately didn't answer my own questions for two reasons:

1. It seemed most respectful of your work to give you the first shot.
2. I don't have an advance opinion - I would have to do a fairly detailed review to be sure.

Perhaps I'm wrong, but you seem to have an advance opinion on the matter. That's disturbing. I'd rather you lay out the facts first.

**Comment by oznetmaster** [comment]
Please read my comments in #1531

**Comment by CharliePoole** [comment]
@oznetmaster We are reviewing your code. I asked a question. "Does this change break our published API or frameworks or framework drivers?" Call me crazy, but it seems like the quickest way to resolve this would be for you to answer the question!

Very recently - with the 3.0 release - we published several APIs...
1. A framework API, which we invited third parties to use -and which some are using.
2. A driver API, which allows anybody to write a driver for some foreign framework. 
3. An Engine API, which allows folks to load and run tests programmatically at a high level.

I'm assuming that you are familiar with those APIs and I'm simply asking if you have broken any of them with this change. If you have, then we need to get into it further to figure out whether it's a change we want to make. If you haven't, then the discussion is over.

All your answers so far don't actually seem to be answers. Rather, you are asking me why I care about the question. I care because we just published some APIs and we should only change them deliberately and with due care.

The best starting point for reviewing the APIs is probably this page...
   https://github.com/nunit/docs/wiki/Test-Discovery-and-Execution-API-Spec

**Comment by oznetmaster** [comment]
I thought I had answered the questions.  Perhaps i have misunderstood them.

**Comment by oznetmaster** [comment]
I referred to the User Docs - Extending NUnit documentation.  I have never seen the one you refer to.

**Comment by oznetmaster** [comment]
The one relevant section in that document seems to be FrameworkController which states:

settings is an IDictionary containing the settings to be used in loading and running this assembly. A non-generic dictionary is used to allow for implementation of the framework on platforms that don't support Generics. [However, this may be changed.]

Perhaps this is the time to change it?

**Comment by oznetmaster** [comment]
Also, it is confusing that the constructor for the FrameworkController defined in that document does not even exist!  So changing the definition does not seem to be an issue.

`public FrameworkController(string assemblyPath, IDictionary settings)` is not currently a valid constructor for the FrameworkController class.

**Comment by oznetmaster** [comment]
The documentation for IFrameworkDriver in that document also does not conform to the existing implementation.  I am very confused.  Is this document only  a roadmap for the future of NUnit, or is it supposed to be accurate for the existing NUnit interfaces and classes?

**Comment by CharliePoole** [comment]
The Extensibility APIs (framework and engine) could probably be added to that page rather than kept separate. However, the three on that page are the ones we have always considered our primary APIs.

I'm pretty sure the line about "this may be changed" implied "this may be changed for the 3.0 release" when I wrote it. Clearly we didn't change it.

That's not to say we can't change it, but if your code makes it impossible to call FrameworkController with a non-generic dictionary, then we will need to re-contact the third-party folks on our list. At least one of them is using that API rather than the engine (which I would have preferred).

I'm not surprised that the docs are out of sync with the code. See the note at the top of the page. Obviously, if there is third-party code using it, they are using an existing constructor.

**Comment by oznetmaster** [comment]
As I said, it is easy to add a backward compatible constructor for the FrameworkController if that is the only issue.It will simple construct an `IDictionary<string, object>` from the `IDictionary`, and call the current constructor.

I will add it to the PR.

**Comment by rprouse** [comment]
Sorry guys, I am away this weekend with limited access,so I don't have full access to the code. I think this change is a good one if as @carliepoole says, it does not change the API. By published API, I am concerned with code  not documentation. Let me look at this on my computer when I get a chance. 

On May 28, 2016 9:21 PM, CharliePoole <notifications@github.com> wrote:

The Extensibility APIs (framework and engine) could probably be added to that page rather than kept separate. However, the three on that page are the ones we have always considered our primary APIs.

I'm pretty sure the line about "this may be changed" implied "this may be changed for the 3.0 release" when I wrote it. Clearly we didn't change it.

That's not to say we can't change it, but if your code makes it impossible to call FrameworkController with a non-generic dictionary, then we will need to re-contact the third-party folks on our list. At least one of them is using that API rather than the engine (which I would have preferred).

I'm not surprised that the docs are out of sync with the code. See the note at the top of the page. Obviously, if there is third-party code using it, they are using an existing constructor.

**Comment by CharliePoole** [comment]
@oznetmaster "This page is a specification that was used as a starting point for creating the feature in NUnit. It needs to be reviewed and revised in order to accurately reflect what was actually built."

We worked with third-party vendors to help them use the framework and engine. We can't undercut them, no matter what the docs say. What would help the most would be a statement of what breaking changes result from the PR. Then we can evaluate them.

**Comment by CharliePoole** [comment]
Another scenario of concern is backward compatibility for NUnit itself. AFAICS it's not an issue, but check my logic...

The engine has been using the generic dictionary all along. It passes a generic dictionary to the framework using a non-generic interface. If we make this change, the 3.4 engine, when running 3.2 or earlier tests, will pass an object (as it now does) to the constructor of the framework object. The 3.2 framework will cast that object to `IDictionary`, the 3.4 framework will cast it to `IDictionary<string, object>` and both casts will succeed.

If  one uses the 3.2 engine to run a 3.4 test. the cast will still work, since the 3.2 engine is actually using a generic dicitonary.

@oznetmaster Is that how you see it as well?

**Comment by oznetmaster** [comment]
Yes.

In my changes to provide backward compatibility, I test this, I think.  I will be updating the PR shortly.

**Comment by oznetmaster** [comment]
Backward compatibility is harder then I originally thought.

No problem having seperate constructors that take` IDictionary` and `IDictionary<string, object>`.

However, `Dictionary<string, object>` implements both `IDictionary` and `IDictionary<string, object>` :(

So passing a `Hashtable` or an interface works fine, but passing a `Dictionary<string, object>` results in an ambiguous method call.

Need to try a different approach

**Comment by oznetmaster** [comment]
So I have updated the PR to keep the FrameworkController constructor API unchanged.  It now checks for the type of settings object passed to it and does the right thing, converting a non-generic `IDictionary` to a generic `IDictionary<string, object>`.

Only remaining concern.is anyone who is using FrameworkController.Settings, which is now a `IDictionary<string, object>'.  As was pointed out, a missing key now will throw an exception rather then returning null, and FrameworkController.Setting.Contains will not compile, requiring a change to FrameworkController.Settings.ContainsKey.

I am not sure how many people, if any, this will affect.

In NUnit itself, the only place the Settings property is used in inside the FrameworkController class, and in FrameworkControllerTests.  However, the property is public.  Maybe it shouldn't be?  Anyone who creates a FrameworkController has the settings anyway, since they are passed to the constructor.

**Comment by oznetmaster** [comment]
Perhaps there should be two properties for the FrameworkController, Settings and InternalSettings.

Settings would remain unchanged, and InternalSettings  would be the `IDictionary<string, object>`, which seeming could be internal, since it is only used by the FrameworkController class itself, and the tests.

Since Settings is internally implemented as a `Dictionary<string, object>`, the same object can be returned for both properties.

I think I will make this change in the PR, which will leave full "published API" compatibility.

**Comment by CharliePoole** [comment]
Two properties seem inordinately complicated, especially as it solves a
problem we have not yet confirmed to exist!

**Comment by oznetmaster** [comment]
No way to confirm it without talking to every user of the class :(

My implementation makes it a non-issue.

It can be addressed again when the issue of internal/private vs public is solved.

**Comment by oznetmaster** [comment]
In all other classes that have a Settings property, it is private and initialized in the constructor.

But they are not part of the "published API".

**Comment by oznetmaster** [comment]
So the PR is ready for code review again.
