### ISSUE TITLE
Blank name attribute in nunit2-formatted XML result file test-run element

### ISSUE THREAD

**Issue by anilrepala505** [nunit/nunit#1543]
When we use nunit 3.2.1 version to test and output is generated in 2.x format, 'name' attribute is getting empty in 'test-results' node.

Used command as follows:
nunit3-console.exe C:\Selenium\UI_Selenium\bin\Release\UI_Selenium.dll -result:C:\Selenium\UI_Selenium\bin\Release\Results.xml;format=nunit2

**Comment by ChrisMaddock** [comment]
The equivalent top level attribute in the nunit 3 format isn't present either - as the FullName property is never set on the TestPackage. The name is piped through to the results, just not written out if it is null - although I'm not sure if this is intentional, or an oversight. @CharliePoole?

**Comment by CharliePoole** [comment]
I have verified this error - I don't think we always had it, but I could be wrong.

@ChrisMaddock The test-result element is approximately equivalent to the NUnit 3 test-run but not quite. It holds the name of the first or only assembly entered on the command-line. The fact that subsequent assemblies are not listed (they are listed later in the file) was a long-standing issue that we never fixed because of compatibility concerns.

With NUnit 3, I removed any name from the test-run element. Anyone wanting the names of projects or assemblies has to read the file to find them. However, we also added a subordinate element that contains the command-line.

@anilrepala505 It will be a bit tricky to duplicate this behavior, but not impossible. Is the presence of the first or only file name important to you? How do you use it?

**Comment by ChrisMaddock** [comment]
@CharliePoole I suspected it might be something along those lines, you mentioned it being approximately equivalent before.

Would it make sense to remove the unused FullName property on TestPackage then, to avoid confusion? Or am I missing something about how it's used?

**Comment by CharliePoole** [comment]
It's not unused, it's optional. But the top-level package that represents a command-line is always anonymous.

**Comment by ChrisMaddock** [comment]
Ah - I'd missed it was a public property on the API. Never mind, thanks.

**Comment by anilrepala505** [comment]
@CharliePoole we need file name in the 'name' attribute of 'test-results' node, as VSTS is expecting it in 'Publish Test Results' step.

<test-results name="" total="1" errors="0" failures="0" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2016-05-20" time="07:17:21">

**Comment by CharliePoole** [comment]
That's new to me as I am not a cats user. Does it cause an error on the publishing step then? Also, how does cats handle an nunit2 file with multiple assemblies?

**Comment by anilrepala505** [comment]
@CharliePoole Publish test results step works only with single assembly.

Single assembly file needs name attribute in "test-results" node to generate test reports in VSTS.

 When we use multiple assemblies output file its throwing an error as "##[warning]Invalid results file. Please make sure the Test Result Format field in the task matches the result format of the file: D:\mutliple.xml".

**Comment by CharliePoole** [comment]
OK then it sounds like this is an important issue!
