### ISSUE TITLE
Assert.AreEqual method is extremely slow when comparing arrays

### ISSUE THREAD

**Issue by fandrei** [nunit/nunit#1552]
This code:

```
        [Test]
        public void NUnitAssertBenchmark()
        {
            var testData = new List<Tuple<byte[], byte[]>>();
            for (int i = 0; i < 100000; i++)
            {
                testData.Add(new Tuple<byte[], byte[]>(new byte[256], new byte[256]));
            }

            {
                var watch = Stopwatch.StartNew();
                foreach (var cur in testData)
                {
                    Assert.AreEqual(cur.Item1, cur.Item2);
                }
                watch.Stop();
                Trace.WriteLine(watch.Elapsed.TotalSeconds);
            }

            {
                var watch = Stopwatch.StartNew();
                foreach (var cur in testData)
                {
                    Assert.IsTrue(cur.Item1.SequenceEqual(cur.Item2));
                }
                watch.Stop();
                Trace.WriteLine(watch.Elapsed.TotalSeconds);
            }
        }
```

Gives the following results:
7.2920849
0.3781902

i.e. NUnit's collection comparer is ~20 times slower than CLR's SequenceEqual() method.

**Comment by fandrei** [comment]
PS NUnit 3.2.1

**Comment by CharliePoole** [comment]
We can take some time to look into this but it's not entirely surprising. Since NUnit treats each item in a collection separately, It has to stop and determine the type of each one before proceeding. For arrays and generic enumerations it could determine the type at the collection level and do something optimized, like using SequenceEqual itself.

The downside of such an approach would be the increased code complexity and it might not even be feasible, since arrays of a given type might contain elements of a derived type that has it's own definition of equality. That's probably not an issue with byte arrays, but may be for other types.

I've marked this as an idea for us to investigate, the specific idea being "maybe we could make this more efficient for homogeneous collections of certain types."

**Comment by stevenaw** [comment]
I'm unsure if this is still an issue, but some related optimizations have been done within the UniqueItemsConstraint that could be useful here. They seem to more or less match the suggestion from @CharliePoole above

**Comment by watsonsong** [comment]
> I'm unsure if this is still an issue, but some related optimizations have been done within the UniqueItemsConstraint that could be useful here. They seem to more or less match the suggestion from @CharliePoole above

How about the "UniqueItemsConstraint"? Is it provide a way to compare two byte array equality?

**Comment by stevenaw** [comment]
Hi @watsonsong 
It does indeed, the code example above should give a relatively quick way to compare byte arrays. Some performance improvements have been made in recent releases, so I'd recommend using the latest stable version of NUnit (3.13.2 at this time). As Charlie mentioned, NUnit does some internal convenience helpers so it may not exactly match the performance of `SequenceEquals()`.

Since this is an old issue, I'm going to close it, however we'll continue to see any comments here. If you encounter any issue when the latest code however, I'd recommend opening a new issue so that it can have up-to-date info and be given the appropriate attention.

**Comment by stevenaw** [comment]
Update: I've taken a look at the current performance of this and there's still a decent gap. I've opened a new issue (https://github.com/nunit/nunit/issues/3985) to continue the discussion of Charlie's comment above

**Comment by CharliePoole** [comment]
Wow! Nice that my ancient comment is still useful. :-)
