### ISSUE TITLE
Escaping control chars in custom message

### ISSUE THREAD

**Issue by Chisamba** [nunit/nunit#1575]
Assert.That<TActual>(TActual actual, IResolveConstraint expression, string message, params object[] args)

In this method Nunit escapes control chars in message.
Can you explain why it's necessary? And can I turn off it?

**Comment by CharliePoole** [comment]
NUnit doesn't escape control characters in the user message by design, so if it's happening it's a bug. Can you provide a repro test case?

**Comment by CharliePoole** [comment]
BTW, as a part of the repro, please indicate where the erroneous output appears. We've already had a separate report of this but were never able to find out that information.

**Comment by CharliePoole** [comment]
No need to repro, I see the problem. Somebody fixed issue #41 "Check for zeroes in assert messages" by leveraging a method designed for a different purpose, which escapes __all__ control characters. Specifically, the intent of that method was to be used for the display of expected versus actual values, in which case it's necessary to see all control characters in order to make a visual comparison.

Clearly, we have to escape nulls, even in the user-provided message, in order to avoid errors in the display. Any thoughts on what else - if anything - we should escape?  The method currently being used is here: https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Constraints/MsgUtils.cs#L314

**Comment by Chisamba** [comment]
No idea what else :)

**Comment by CharliePoole** [comment]
OK, we'll figure out something. I suggest you review the PR when it's available.

**Comment by lpszBuffer** [comment]
Hey guys, let me know if you think PR #1659 looks suitable.

**Comment by 13xforever** [comment]
Would it be possible to push this fix as a 3.4.2 hotfix on nuget?

**Comment by rprouse** [comment]
@13xforever we will not release this as a hotfix, but if you need this fix, you can use our CI NuGet feed until the next release. To do so, add a NuGet.config file to the root of your solution and add our CI NuGet feed to it as an [additional package source](https://docs.nuget.org/consume/nuget-config-file#package-sources). The address for our feed is, https://ci.appveyor.com/nuget/nunit

Once you do that, if you select pre-release in the package explorer, you can upgrade NUnit to version 3.5.0-CI-3020-master which contains this fix.

**Comment by jnm2** [comment]
Wow, awesome! I could really use this fix.
