### ISSUE TITLE
NUnit v3 dangerously overrides COMPLUS_Version environment variable

### ISSUE THREAD

**Issue by ww898** [nunit/nunit#1579]
Why? All child processes will inherit it and TRY running under CLR v4.0.30319, but in fact some of them can't. Please remove it from your code or tell me the big reason why you did it. Now we should remove COMPLUS_Version  before run our tests...

**Comment by hypersw** [comment]
We are testing IIS Express which is a native entry point and it's instructed to run with CLR2. When managed code starts running within it with CLR2, it tries to favor the env variable and load CLR4 assemblies, and it causes the server to fail. That's now it seems now.

Also this env variable would affect all of the child processes run from within the test process, which is hardly a right thing to do because their CLR version selection is not in sync with the NUnit test CLR selection.

The agent should probably clear this env variable when it starts — I assume it's only set there to run the agent in the right CLR. Or maybe we could have a set of agents for different CLRs as before, because this hack with env vars turns out to have side-effects.

**Comment by CharliePoole** [comment]
A little more information please...

We set COMPLUS_Version for the agent process because that's the accepted way to run a program using a specific framework. We do this whenever we are the tests running in a separate process either based on the user-specified `--framework` option or the target framework of the test assembly. The agent itself will never start a subprocess, so that can only happen if your own code does it. Most likely, you are allowing environment settings from the current process when you create a subprocess.

What I'm missing is this: If you need to test something under .NET 2.0, why are your tests targetting .NET 4? What you are calling the "NUnit test CLR selection" is actually selected by the user.

But it's quite possible I'm missing something here. Please explain if so.

**Comment by jcansdale** [comment]
I can see this being an issue if you want to run tools as part of your tests. I've run into this kind of issue before (building test assemblies with an older version of csc.exe). Could the agent nuke the `COMPLUS_Version` variable when it starts? That's the way TestDriven.Net handles it.

**Comment by hypersw** [comment]
There're lots of accepted ways for CLR selection, like `ICLRMetaHost` and `.config`. and so on, all of them non-viral for child processes. The problem with this one is that it affects any child processes run from tests in a totally unexpected way. But this can be mitigated if the agent process restores the state of the env vars after they have played their role.

The tests are targeting CLR4 because the test code is written with targetfx 4, like the rest of R# codebase, and cannot run on CLR2. The processes which have to be run to perform the activities being tested, including totally third-party ones like IIS Express, might well be targeting CLR2. In this case we need to run those child processes specifically in CLR2 to test our interaction with CLR2 processes.

I guess that generally everybody is allowing environment variables to be inherited by the child process. The opposite is quite a rare case. You will have problems running a process with its env totally empty, including the well-known system stuff, and passing them selectively is a nontrivial procedure which is hardly ever needed.

The point is that this env var, which is a technical detail of nunit's selecting agent's clr version, should be kept to the agent itself and prevented from leaking into the users' code. Which should be easy to achieve in the agent startup code.

**Comment by jcansdale** [comment]
@hypersw Interesting. Do you know if ICLRMetaHost can be used from managed code?

**Comment by ww898** [comment]
I think you can try to load another CLR from managed code: start CLR v2 from CLR v4. See `ICorRuntimeHost::Start()`. However, easier to write native x86/x64 executables which starts specific CLR from native code.

**Comment by hypersw** [comment]
@jcansdale: I've only used it from native code; I can see no immediate problems for managed code, but that's no guarantee because native and managed APIs are in no specific relation to each other.

**Comment by CharliePoole** [comment]
Sounds like the easiest thing is to clear the environment setting in the agent start-up sequence.

**Comment by CharliePoole** [comment]
What's interesting is that this has never come up before. We've been doing it this way since .NET 4.0 came out.

**Comment by CharliePoole** [comment]
If somebody does a quick fix on this it _might_ make it into 3.4.

**Comment by hypersw** [comment]
@CharliePoole: the "never come up before" thing: we've been running these tests with TeamCity runner v2.x, and probably they were run in-process by default. We're OK with runner itself using the latest available framework, and it didn't affect the child processes. There used to be nunit runners x86/x64 as separate entry points, so running the agent were not as much required to ensure the CPU. Now we switched to using out-of-process runs because of the CPU.

**Comment by CharliePoole** [comment]
@hypersw I don't doubt that it's a problem, but it is surprising that nobody else noted it, since we've been doing it this way for a number of years. As you say, maybe the changes between 2 and 3 make it more likely to come up.

**Comment by hypersw** [comment]
We wouldn't have noted it either — were it not for IIS Express against which the profiler has to be tested. Only these tests have shown up. All the rest supposedly testing CLR2 just ran silently with CLR4, as it almost always works OK this way. Smb could have lost half the tests the same way, but there's no telling.

**Comment by CharliePoole** [comment]
Fixed by #1585
