### ISSUE TITLE
NUnit doesn't handle FaultExceptions?

### ISSUE THREAD

**Issue by ghnunit** [nunit/nunit#1584]
FaultExceptions don't seem to be handled correctly. Instead of the test failing, the debugger just stops at the exception, unless you turn of this exception in VS or use the workaround below.

Is this intended behaviour?
Please take a look at the follwing code:

    using System.ServiceModel;
    using NUnit.Framework;

	namespace NUnitLite.Tests
	{
		public class Program
		{
			public static int Main(string[] args)
			{
				args = new string[1];
				args[0] = "--wait";
				return new AutoRun().Execute(args);
			}

			[Test]
			public void Foo()
			{
				//stops execution with "An exception of type 'System.ServiceModel.FaultException`1' occurred in ... but was not handled in user code"
				Assert.Throws<FaultException>( () => Bar());

				//also stops with the same message
				var nunitCatchedException = Assert.Catch(() => Foo());
				Assert.IsInstanceOf<FaultException>(nunitCatchedException);

				//as a workaround the following works as expected:
				bool exception = false;
				try
				{
					Bar();
				}
				catch (FaultException)
				{
					exception = true;
				}
				Assert.That(exception);
			}

			public void Bar()
			{
				throw new FaultException("fault");
			}
		}
	}

**Comment by CharliePoole** [comment]
I assume you are running under the debugger in VS.

This is just how the VS debugger works. When we test NUnit, with some tests expected to fail, we get a break on every AssertionException. Then we continue and NUnit handles it.

Note that VS seems to define "unhandled" a bit differently from other contexts. It means unhandled in the method that throws.

There's nothing NUnit can do about this. I don't advise using your workaround because it will just clutter your code.
