### ISSUE TITLE
NUnit3 Fails on DLL with no Tests, Unlike NUnit2

### ISSUE THREAD

**Issue by hypersw** [nunit/nunit#1586]
Some projects of our codebase are for test purposes only, though not all of them have test cases (some got only mocking infrastructure code).

With NUnit1-NUnit2, we used to submit all of the DLLs from the test area, and NUnit would run all the tests it could find.

With NUnit3, it fails with an error like this:
```
Errors and Failures
1) Invalid : xxx.dll
No suitable tests found in 'xxx.dll'.
Either assembly contains no tests or proper test driver has not been found.
```
And returns the `ERRORLEVEL` of `FFFFFFFE`.

This is a breaking change from NUnit2, from how I see it.
We didn't think up a workaround yet.
Is it possible to get the previous version behavior, with an option or something?

**Comment by hypersw** [comment]
Errorlevel looks like `NUnit.ConsoleRunner.ConsoleRunner::INVALID_ASSEMBLY`.

**Comment by hypersw** [comment]
The error is probably triggered in `NUnit.Engine.Services.DriverService::GetDriver`.

**Comment by hypersw** [comment]
Looks like it actually checks by referenced assemblies only rather than presence of the actual test cases.
That's something I could also check in the build script before spawning tests for each DLL.
Might be useful to be able to batch-submit them though, as you'd not always have a build script capable of reading thru assembly references like in our case.

**Comment by hypersw** [comment]
I've prototyped a fix at https://github.com/JetBrains/nunit/commit/ad29539dca76c87dd11e2491cf8537f01a9e38e3 for us to try nunit3 full-scale without missing test errors.
Might not be a good idea doing this by default (even though this seems to be a breaking change from nunit2), but could prove useful if under an option.

**Comment by CharliePoole** [comment]
Well, it's 3.x versus 2.x, so it has a ton of breaking changes. Minimum "fix" for this issue would be to make sure the change is listed on the Breaking Changes page. :-)

That said, I think this is a correct change. In most usage, passing a non-test assembly to NUnit is an error of some kind. It could be a simple, ignorable error as in your case. OTOH, it could be that you are using some third-party framework without installing the driver extension for that framework. There is no way for NUnit to know what is the cause.

This has already given us a lot of trouble with the VS adapter because VS passes us __all__ the assemblies in a solution and it's also a problem for users who try to run the solution from the command line. We deal with the first by special checks in the adapter. The second is the subject of a separate issue (#668), which we will probably take care of by passing in some info about the source.

So, for various reasons, a package setting of "IgnoreNonTestAssemblies" is probably in the future. Once that's available, we could add a console option to activate it.

Note: This should be worked on in conjunction with #668.

**Comment by DanHarman** [comment]
Is there any further thinking on this? My particular scenario is passing in a glob to my teamcity nunit build step for:

`**\bin\Release\*Tests.dll`

As this means we don't need to keep adding test projects into the build server manually (I've already failed to do this once...) However we also have mstest projects in the build which also have *Tests.dll extension, and nunit console test runner errors out as soon as it encounters one. Ideally I'd like a command line param to not error out if it is passed a dll without any tests it understands.

**Comment by CharliePoole** [comment]
Well, as a result of earlier discussion, we accepted this as a feature request and added it to our backlog.

The next thing you can watch for is for somebody to take it on as an assignment. That could be a team member or an outside contributor who wants it badly. :smile:

**Comment by rprouse** [comment]
If we decide to change this, we should do the same in the .NET Core runner. There is a duplicate issue there with a couple of requests, nunit/dotnet-test-nunit#77

**Comment by rprouse** [comment]
This is also a Console issue, I am going to move this issue there.

**Comment by rprouse** [comment]
Issue moved to [nunit/nunit-console #62](https://github.com/nunit/nunit-console/issues/62) via [**ZenHub**](https://www.zenhub.com/)
