### ISSUE TITLE
Move Silverlight to a separate project

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1601]
This needs to be evaluated as an idea. 

Reasons to do it:
 * Silverlight is now a legacy platform with a small community.
 * We could release on a separate cycle.
 
Arguments against:
 * We would have to deal with keeping the separate project in sync - or let them go out of sync.
 * It's not clear who would manage the separate project.
 * We could simply stop supporting Silverlight.

**Comment by rprouse** [comment]
As a plan of attack, once we split out the console/engine and this repository contains only the framework and nunitlite, one of us can clone the repo, add a new remote for `nunit.silverlight`, push to there and then clean up. I **think** that if we do that, we could cherry pick commits from either repo and push them to the other. We would have to try it, but it is similar to the approach I took with the portable agent.

Another possible way to do it would be to fork this repo into one of our personal accounts, rename it, then transfer ownership back to the NUnit organization. That would then maintain the fact that it is a fork.

As for keeping it in sync, my feeling is that for 3.6, we release a new nunit.silverlight nuget package and track its usage. We then let the community dictate it's release cycle. If people report issues and ask for fixes, then we can schedule newer releases, if not, then we just let the projects go out of sync.

**Comment by rprouse** [comment]
One other thing I did when I split out the portable agent was truncate the history back at the 3.2.1 release. This makes it easier to clone the repo by making it much smaller. 3.2.1 was a good cut off for the portable agent because that is around when work started on it. We can use different tags for each repo we split out, or decide not to truncate for some like the console/engine.

**Comment by CharliePoole** [comment]
Seems to me we have already discussed this enough and are now ready to make it a feature in the backlog.

**Comment by CharliePoole** [comment]
@rprouse I agree with the approach you outlined. Some thoughts...

 * I like the idea of forking it first. Maybe I should have done that with the extensions, although I don't want to backtrack now.
 * Assuming we get no bug reports that impact it, the 3.6 release should really just be the same code with a lot of the conditional stuff removed. That would allow other people to fork it and improve it later.
 * The new repo would not get any new features that we add to the framework unless someone explicitly asked for it. In that case we would evaluate.
 * Bug fixes to the framework above a certain level (high or critical?) could be ported if we felt it necessary, but I think this too could depend on user feedback.
 * We should get this one done and then evaluate whether the same approach will work for CF, which has added complications.

**Comment by rprouse** [comment]
I am assigning to myself and to the 3.6 milestone. I would like to get this out of the way to evaluate the process for CF and I also think it will make adding a netstandard version of the framework a bit easier with fewer conditionals.

**Comment by CharliePoole** [comment]
We could leave the SILVERLIGHT conditionals in place in the nunit repo for now and remove both SILVERLIGHT and CF in one pass later. I think we should remove the project and build step as part of this one, however.

**Comment by rprouse** [comment]
I tried to fork the nunit repository to my account, then renamed it to nunit-silverlight, then tried to assign ownership back to nunit, but GitHub would not allow that. I think that since it is a fork and you can't fork to the same organization, it won't allow it.

I am going back to the multiple origin approach.

**Comment by CharliePoole** [comment]
I created a new clone of the nunit repo locally. My plan is to reset origin to the new repo, remove all branches except master and push it. Does that sound reasonable?

**Comment by rprouse** [comment]
That is what I did. Forgot to remove the release beaches though, will do
that.

On Oct 13, 2016 5:54 PM, "CharliePoole" <notifications@github.com> wrote:

I created a new clone of the nunit repo locally. My plan is to reset origin
to the new repo, remove all branches except master and push it. Does that
sound reasonable?

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/nunit/nunit/issues/1601#issuecomment-253650133>, or mute
the thread

**Comment by rprouse** [comment]
@CharliePoole I am starting the branch in this repo to remove the SilverLight projects. I will remove the CF projects at the same time. No use both of us doing it. If your clone that you are going to move to another repo isn't up to date, we can hold off merging my PR until you get latest.

**Comment by CharliePoole** [comment]
I'm out and about on my phone right now. Will check when I get home.
