### ISSUE TITLE
Request to add a switch to set time locale

### ISSUE THREAD

**Issue by msyusuf** [nunit/nunit#1603]
There are no parameters to change the timezone in NUnit. In NUnit 3, all times are reported in UTC. It would be helpful to set timezone to local time so that messages can be compared with other logs that also have a (local) timestamp.

**Comment by rprouse** [comment]
Assuming we only support local time, I think this is a reasonable request assuming the time is output including the offset. Internally, we would continue to use UTC time and only make the change in the output to the test results.

**Comment by CharliePoole** [comment]
Sounds like it ought to be a global setting rather than a command-line option.

**Comment by oznetmaster** [comment]
No global settings in nunitlite, so command line would be needed there.

**Comment by CharliePoole** [comment]
@rprouse Just noticed your comment about changing the output "to the test results." I think that the XML file needs to remain UTC because people may depend on it and have transforms that assume UTC. For logs and test reports we create in plain text format, I can see the point and that seems to satisfy the original request, which refers to logs.

**Comment by jplebre** [comment]
@CharliePoole what about say CI runners? the logs would be in local time and that could be in another time zone (for remote teams)
maybe I misunderstood this? :)

**Comment by CharliePoole** [comment]
@jplebre Good point. The logs I was referring to (our only logs) are internal trace logs, usually only activated in debugging. I haven't used them for CI at all myself, but only locally. However, I can see there might be some situations where you wanted them to reflect a different time.

@rprouse Reading back over this, I find I have lost track of exactly what we are proposing to change.

**Comment by rprouse** [comment]
@CharliePoole some users want the time in the test results to be in local time. I am against the idea because CI servers could be anywhere and remote CI servers almost always run UTC anyway, but a couple of people would prefer some control.

If we do this, I think we should continue to represent time throughout the run in UTC and then maybe only change it on output to the test results or to the console.

**Comment by msyusuf** [comment]
I submitted the request, but now I find that I don’t have a need for it. I created by own logs which worked for me. 

 

Saleem

**Comment by CharliePoole** [comment]
I'd be inclined to make this a "won't fix"

**Comment by msyusuf** [comment]
And I have to objections. I appreciate that you did look into it.

 

Thanks,

 

Saleem

**Comment by rprouse** [comment]
@CharliePoole I agree, I am closing.
