### ISSUE TITLE
nunit.nuget.addins discovery pattern is wrong then restored through project.json

### ISSUE THREAD

**Issue by maximpashuk** [nunit/nunit#1607]
I have project.json file

``` json

{
  "version": "0.0.0",

  "frameworks": {
    "net461": { }
  },

  "dependencies": {
    "NUnit.ConsoleRunner": "[3.2.1]",
    "NUnit.Extension.NUnitV2ResultWriter": "[3.2.1]",
    "NUnit.Extension.NUnitV2Driver": "[3.2.1]"
  }

}

```

Then I restore it through NuGet3

```
nuget restore project.json
```

I receive folder structure

```
%UserProfile%
    .nuget
        packages
            NUnit.ConsoleRunner
                3.2.1
                    tools
                        nunit.nuget.addins
            NUnit.Extension.NUnitV2Driver
                3.2.1
                    tools
            NUnit.Extension.NUnitV2ResultWriter
                3.2.1
                    tools
```

```nunit.nuget.addins``` file have filter ```../../NUnit.Extension.*/tools/``` which is fine for NuGet2&packages.config case.
In case of NuGet3&project.json filter is wrong, no extensions is loaded automatically
This is bug.

I think in this case pattern should be like ```%UserProfile%/.nuget/packages/NUnit.Extension.*/**/tools/```.

So to work correctly in NUnit3&project.json case, please add one more search pattern in ```nunit.nuget.addins``` file

**Comment by CharliePoole** [comment]
Thanks for letting us know about that. The problem with the solution you are suggesting is that %UserProfile% won't be recognized on all environments. I think the second pattern would have to be `../../../NUnit.Extension.*/**/tools` in order to work.

Meanwhile, you should of course simply edit the `.addins` file, which is intended to be user-modified. In a future release, we may remove these entries in favor of a programmed search for the packages directory.
