### ISSUE TITLE
Appveyor error in TestCF

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#1615]
The TestCF section of the CI build is currently logging an `Immediate Error Message`. It seems to have been doing this for a while, although didn't throw the error when the `TestCF` task was originally added.

https://ci.appveyor.com/project/CharliePoole/nunit/build/3.3.0-CI-2887-issue-1607#L1302

I don't have the CF tools installed, so can't currently verify if this happens locally or not. It also appears to still be running the actual tests, so potentially isn't an important error, but we should probably investigate. (And look in to why it isn't error-ing the build, if it should be.)

**Comment by rprouse** [comment]
The text makes me think it is related to the immediate output @charliepoole added

**Comment by CharliePoole** [comment]
Yes, that's what it is. I had noticed it but since it didn't cause an error in the build I left it alone. What's happening is that we are writing to stderr, which AppVeyor is taking to mean there's an error. 

If this is confusing, we should simply make the tests that actually produce the output Explicit or exclude them in the CF build.

**Comment by ChrisMaddock** [comment]
Ah ok - if it's a recognised non-error, than that's ok - I wasn't aware that's what it was. @CharliePoole - will leave you to decide and close/repurpose this issue as approriate. :-)

**Comment by CharliePoole** [comment]
What I don't entirely understand is why it only happens in the CF tests. Guess i should take a look.
