### ISSUE TITLE
NUnit 3.4 is not integrated with TeamCity

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/nunit#1623]
TeamCityEventListener is not activated by the call `            _extensionService.EnableExtension("NUnit.Engine.Listeners.TeamCityEventListener", _options.TeamCity);`
TeamCityEventListener has this attribute `[Extension(Enabled = false, EngineVersion = "3.6")]`
But `ENGINE_VERSION = 3.5.0.0`

**Comment by CharliePoole** [comment]
This is a bad one! I verified that both the master and the 3.4.0 release use 3.4. That means the team-listener extension will never actually be used.

The value should be 3.4. I changed it back and forth several times in order to test it manually. I don't know how 3.6 got into the release undetected, because we have tests that verify the proper extensions are detected.

Seems like a critical bug, since nobody will be able to use 3.4 under TeamCity till it's fixed. This would probably call for an immediate 3.4.1 release if the error were in any other component. However, since we already planned to release this extension separately, maybe we should should accelerate releasing the process. @rprouse What do you want to do about this?

**Comment by rprouse** [comment]
I assume that this only made it into the Team City extension? We can release an update to this extension, but I think we need to also release an update to at least the NUnit.Runners meta package. It has specified all of the dependencies as `=` not `>=` so it won't pick up the update.

![image](https://cloud.githubusercontent.com/assets/493828/16385171/c2125120-3c59-11e6-86d5-0b6b6f5974d7.png)

**Comment by rprouse** [comment]
https://github.com/nunit/nunit/blob/master/nuget/runners/nunit.console-runner-with-extensions.nuspec should just have `version="$version$"` not `version="[$version$]"` to take the default behaviour. 

https://docs.nuget.org/create/versioning#Specifying-Version-Ranges-in-.nuspec-Files

**Comment by rprouse** [comment]
Should we be doing a 3.4.1 of the runners and extensions?

**Comment by rprouse** [comment]
I can probably knock out a quick 3.4.1 release tonight. We should branch off the `release\3.4.0` branch and update the `nuspec` files to use `>=` and pull in the updated extensions that need it. Unfortunately, I think we would need to update all the extensions because we use the single `$version$` in the nuspec files. Or if the other extensions don't need updates, hack it and hard code `3.4.0` for those extensions in this branch only.

@CharliePoole if you have time to get some of the groundwork done, it would help.

**Comment by CharliePoole** [comment]
The change is in the engine itself. Versions prior to 3.4 don't know about the attribute so they don't check at all. E.g. the 3.2.1 engine would load the teamcity extension.

The teamcity extension is the only one that uses the attribute because it would say 3.0 for any of the others, which is basically a noop. If we produce new versions of any extension that requires a particular engine version > 3.0, then we would add the attribute to that version.

Regarding the [$version$] entries, should they be changed for __all__ dependencies of console runner, or only the teamcity version? Maybe if we made everything just =$version$ then we wouldn't have to keep re-releasing ConsoleRunner for every version... only when we change dependencies. Is there any best practice for virtual packages?

**Comment by CharliePoole** [comment]
If we are going to do a 3.4 release, then let's also take a look at what else is coming in as issues. At first glance, #1623 looks like a problem. I'll try to comment on that one and then I have to disappear for a few hours. :-)

If we are going to do a 3.4.1 release, then I'll work on the changes we need rather than trying to split out the teamcity event listener into it's own repo, which would take a bit longer.

**Comment by rprouse** [comment]
I am going to have limited time this week. I am kicking off a new project at work and have friends over from Sweden, so will be fairly busy.

It looks to me like we may only need to do a 3.4.1 release for the meta packages and the team city extension. I think all of the dependencies for the meta package should by `>=`, then we can release fixes for the extensions when and as they are needed. We may actually want to start hard-coding all of them to the current release numbers if we are not going to be updating them regularly.

**Comment by CharliePoole** [comment]
I'll work on the packages.

**Comment by CharliePoole** [comment]
Why the tests didn't catch this: Our tests all use fake extensions and ensure that we load them. They say nothing about the actual extensions! Our unit tests of extensions do not load them, they reference them directly as good unit tests should!

**Comment by CharliePoole** [comment]
Fixed in release branch by #1630

**Comment by stryczekk** [comment]
@CharliePoole  Could you tell me when you plan release this fix?
Is important for teamcity users.

**Comment by CharliePoole** [comment]
Although this issue is done and merged, there are a few other issues for 3.4.1. We hope to have it out during the day today, US Pacific time that is.

I was going to send you to our MyGet feed, but I realized that, because of a change in how we do hotfix releases, the packages are not going there. You can get the fix for this issue from our AppVeyor feed, ci.appveyor.com/nuget/nunit. The package is NUnit.Extension.TeamCityEventListener and you want CI build 2945. You'll have to browse for the specific build, since that feed is a bit of jumble with "latest" not really meaning anything.

**Comment by stryczekk** [comment]
OK, thanks !

**Comment by CharliePoole** [comment]
All packages for 3.4.1 are now available at https://github.com/nunit/nunit/releases

**Comment by Kazark** [comment]
@CharliePoole I appreciate your work on this. I'm not sure what I'm missing, but it's still not working for me. When I updated to 3.4.1, I did not see the tests show up in TeamCity, so I ran the console runner locally with the `--teamcity` option. No service messages appeared. After downgrading to 3.2.1, the service messages do appear with the `--teamcity` option. What am I missing?

**Comment by CharliePoole** [comment]
Did you install the TeamCityEventListener extension? See the Breaking Changes page.

Sometimes we work on this stuff for months before it's released. In this case, I kind of forgot that the extension is new to you in the release. I take it that we are not giving an error message in the console? If not, I think that's a bug. We should simply tell you you can't use that option because the extension isn't installed.

**Comment by Kazark** [comment]
@CharliePoole thanks so much. I'll look into that and report back.

**Comment by Kazark** [comment]
Oh, by the way, as you suggested, this fixed the issue:

    paket add nuget NUnit.Extension.TeamCityEventListener
