### ISSUE TITLE
NUni3 fails to run test derived from a class in another assembly

### ISSUE THREAD

**Issue by estrizhok** [nunit/nunit#1633]
In BaseProject.csproj:
```
public abstract class BaseFixture
{
      [Test]
      public void Test() { }
 }
```

In DerivedProject.csproj:
```
public class DerivedFixture : BaseFixture {}
```

Steps to reproduce:
1. Compile
2. Run with nunit3-console.exe DerivedProject.dll

Expected result:
1. One tests is executed and passed

Actual result:
1) Error is reported:
Invalid : c:\Users\Eugene.Strizhok\Documents\nunit-320\DerivedProject.dll
No suitable tests found in 'c:\Users\Eugene.Strizhok\Documents\nunit-320\DerivedProject.dll'.
Either assembly contains no tests or proper test driver has not been found.

**Comment by rprouse** [comment]
Are you using any NUnit attributes in DerivedProject? Does it work if you add a `[TestFixture]` attribute to `DerivedFixture`?

**Comment by estrizhok** [comment]
If I add the [TestFixture] to the derived class, then it works.
However, in NUnit2.6.4 the same setup works without it.

**Comment by rprouse** [comment]
Are you using any other NUnit attributes or code in the derived project? If not, we don't find the NUnit reference so don't know which test driver to use (v2 or v3).

**Comment by CharliePoole** [comment]
Add an Assert to the method and I imagine it will work... 

The difference from 2.6.4 is that NUnit 2 only runs tests that use the NUnit framework. NUnit 3 has to figure out what framework is in use and it can't do that if there isn't code that creates a reference to the framework. (We support two frameworks, NUnit 2 and NUnit 3 but other people could add drivers that support other frameworks.)

**Comment by kevinkuszyk** [comment]
I think I'm seeing this behavior too using NUnit 3 with my [test framework](https://github.com/kevinkuszyk/test-framework/) which is compiled against NUnit  2.

I've narrowed it down to the following scenarios:

1. If the test base class doesn't use any attributes from NUnit 2, the NUnit 3 runner can discover tests even if the base class project references NUnit 2.
2. If the test base class uses NUnit 2 attributes (I use `[Setup]` in test framework), the NUnit 3 runner can't find tests which derive from the base class.

Is this something you might fix?  In the meantime I'm considering just upgrading my test framework to support NUnit 3.

**Comment by CharliePoole** [comment]
Those cases are both _by design_. The only way NUnit has to tell what framework is being used (V2 and V3 are different frameworks) is to examine the references. In the situations you describe the test assemblies don't have any references, so we never even try to examine it further.

More detail: this happens when we are deciding what driver to use to access the test assembly. Drivers are built into or added as extensions to the engine. They map one-to-one to frameworks. There is a driver for NUnit V2 and another for V3. Pretty soon, I think there will be several different V3 drivers and possibly one for a foreign framework as a proof of concept. If NUnit can't figure out a suitable driver, it returns a special one that always fails with the message you see!

So, you could make this work even by adding e.g. a DescriptionAttribute somewhere. You can even add an assembly-level attribute. So long as it ends up giving us a reference, then we will figure out how to run it.

Obviously, we could solve this by doing an in-depth search of the assemblies that your test assembly refers to. We have chosen not to do that for efficiency reasons. 

If your framework __always__ implies NUnit, we could add it's name to what we are checking. That's a slippery slope, however. Maybe what we need is a very simple extension point that defines alternate assembly names and versions and translates them to the "real" framework driver we need to use. Your test framework could host that extension itself... the details need working out.

Alternatively, just tell your users to add an NUnit attribute or other call somewhere in their tests.

BTW, this is now documented on our Breaking Changes page.

**Comment by kevinkuszyk** [comment]
Thanks again for another thorough answer!

I think I may have hijacked the OP's thread - the behavior I'm seeing is  subtly different.  My test class has the `[TestFixture]` and `[Test]` attributes on it from NUnit 3, but it derives from a base class which has `[SetUp]` from NUnit 2.

From what you explained above, it sounds like the NUnit 3 runner should discover my tests - it has NUnit 3 attributes on it (I think the OP did not).

I've pushed a sample repro which shows this here: 
https://github.com/kevinkuszyk/nunit-3-with-nunit-2-base-class.

> If your framework always implies NUnit, we could add it's name to what we are checking. That's a slippery slope ... 

I agree, hard coding in support for 3rd party frameworks doesn't sound like the way to fix this.

If you agree that the runner should discover these tests, do you want me to open a new issue to track this?

**Comment by CharliePoole** [comment]
Yes, I think we are getting well beyond the intent of this issue. :-) If we need to continue after this, perhaps you could create a new one... but I wonder if we can continue.

The behavior I would expect from NUnit in your test case is this...

1. If you give it the assembly from TestProject, it should find your test. It should not find the tests in the base class and the base setup should be completely invisible to it.

2. If you give it the assembly from BaseProject the result would depend on whether the V2 driver extension is installed. If it is, NUnit should run the tests from the assembly through the extension. If it is not installed, NUnit should report that it can't find any driver for the assembly - message probably says something like "Either it's not a test assembly or the driver isn't installed."

I wrote those two points without looking back at your initial post. Now, looking back, your first point is as I would expect. Your second point is rather surprising to me. I don't think I read it correctly the first time through. The (NUnit3) Test attribute is visible and the test should be found. The only way it would not be found is if some hidden exception is occuring at the fixture level, which is not reported to you. Run the TestProject assembly under nunit3-console and look at the XML result file to see if that's the case.

Is there some reason you want to support NUnit3 tests on a base of NUnit2? Are you trying to hide the differences between the two from your users? Since we (the nunit team) consider NUnit3 to be a completely new framework with a strong surface resemblance to NUnit2, that may be a losing game. :-)

Whatever you decide, I'd be curious to know what's happening in your example. We really gave no thought to the co-existence of the two frameworks. Since the assemblies both have the same name, a user is generally going to have one or the other of them copied into the output directory. We explicitly decided you could not write test assemblies that mixed the two types. Your use of inheritance introduces a new wrinkle.

One explanation just came to me as I was about to sign off... In examining your assembly, NUnit would look at all the methods in the base class. It could be throwing when it reaches some NUnit2 attributes. If so, something should be found in the XML output.

Charlie

**Comment by ChrisMaddock** [comment]
> Is there some reason you want to support NUnit3 tests on a base of NUnit2? Are you trying to hide the differences between the two from your users? Since we (the nunit team) consider NUnit3 to be a completely new framework with a strong surface resemblance to NUnit2, that may be a losing game. :-)

Just to comment on this - we had the same issue with our internal framework. Since the framework is used by software products across the company, a straight upgrade to NUnit 3 wasn't an option. We instead now build two versions, one referencing NUnit 2, and one referencing NUnit 3. We now have a .shproj, with the v2/3 specific bits excluded with compilation symbols as necessary.

Whether that's a useful approach or not, I imagine depends on the size of your test framework. :-)

**Comment by CharliePoole** [comment]
Well, a useful data point is that we ourselves didn't attempt to make NUnit3 able to handle NUnit2 tests! We supply an extension that can do it but that contains virtually all of NUnit2!

**Comment by kevinkuszyk** [comment]
Yes, the more I think about this, the less sense it makes.  You've always made it clear that NUnit 2 and Nunit 3 are different frameworks, so trying to use attributes from one in another shouldn't be expected to work.

> Is there some reason you want to support NUnit3 tests on a base of NUnit2?

Just laziness on my part.  I was hoping one version of my test framework would work with NUnit 2 and 3.  I'll just have to get on with shipping a 2.x version which supports NUnit 3.

> One explanation just came to me as I was about to sign off... In examining your assembly, NUnit would look at all the methods in the base class. It could be throwing when it reaches some NUnit2 attributes. If so, something should be found in the XML output.

Here's the XML output - there's no exceptions:

```xml
﻿<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="2" testcasecount="1" result="Passed" total="1" passed="1" failed="0" inconclusive="0" skipped="0" asserts="1" engine-version="3.4.1.0" clr-version="4.0.30319.42000" start-time="2016-07-05 08:08:17Z" end-time="2016-07-05 08:08:17Z" duration="0.100558">
  <command-line><![CDATA[packages\NUnit.ConsoleRunner.3.4.1\tools\nunit3-console.exe  src\TestProject\bin\Debug\TestProject.dll]]></command-line>
  <test-suite type="Assembly" id="0-1004" name="TestProject.dll" fullname="C:\projects\github\NUnit 3 with NUnit 2 base class\src\TestProject\bin\Debug\TestProject.dll" runstate="Runnable" testcasecount="1" result="Passed" start-time="2016-07-05 08:08:17Z" end-time="2016-07-05 08:08:17Z" duration="0.056142" total="1" passed="1" failed="0" inconclusive="0" skipped="0" asserts="1">
    <environment framework-version="3.4.1.0" clr-version="4.0.30319.42000" os-version="Microsoft Windows NT 10.0.10240.0" platform="Win32NT" cwd="C:\projects\github\NUnit 3 with NUnit 2 base class" machine-name="" user="" user-domain="" culture="en-GB" uiculture="en-US" os-architecture="x64" />
    <settings>
      <setting name="WorkDirectory" value="C:\projects\github\NUnit 3 with NUnit 2 base class" />
      <setting name="ImageRuntimeVersion" value="4.0.30319" />
      <setting name="ImageTargetFrameworkName" value=".NETFramework,Version=v4.5.2" />
      <setting name="ImageRequiresX86" value="False" />
      <setting name="ImageRequiresDefaultAppDomainAssemblyResolver" value="False" />
      <setting name="NumberOfTestWorkers" value="2" />
    </settings>
    <properties>
      <property name="_PID" value="5848" />
      <property name="_APPDOMAIN" value="test-domain-" />
    </properties>
    <test-suite type="TestSuite" id="0-1005" name="TestProject" fullname="TestProject" runstate="Runnable" testcasecount="1" result="Passed" start-time="2016-07-05 08:08:17Z" end-time="2016-07-05 08:08:17Z" duration="0.031355" total="1" passed="1" failed="0" inconclusive="0" skipped="0" asserts="1">
      <test-suite type="TestFixture" id="0-1002" name="Tests" fullname="TestProject.Tests" classname="TestProject.Tests" runstate="Runnable" testcasecount="1" result="Passed" start-time="2016-07-05 08:08:17Z" end-time="2016-07-05 08:08:17Z" duration="0.024388" total="1" passed="1" failed="0" inconclusive="0" skipped="0" asserts="1">
        <test-case id="0-1003" name="NUnit3_test_should_pass" fullname="TestProject.Tests.NUnit3_test_should_pass" methodname="NUnit3_test_should_pass" classname="TestProject.Tests" runstate="Runnable" seed="1698082794" result="Passed" start-time="2016-07-05 08:08:17Z" end-time="2016-07-05 08:08:17Z" duration="0.010085" asserts="1" />
      </test-suite>
    </test-suite>
  </test-suite>
</test-run>
```

Thanks again for your help.

**Comment by CharliePoole** [comment]
@kevinkuszyk Well, the output looks as I would expect anyway. Good luck with the migration - let us know if you run into anything we can help with.

@estrizhok Your original problem seems to be covered by the new behavior - assembly must have a direct reference to the nunit3 framework. I added this to the docs under breaking changes.
