### ISSUE TITLE
Running nunit-console on a large solution (.sln)

### ISSUE THREAD

**Issue by SariNusier** [nunit/nunit#1653]
Is it possible to run nunit-console on an .sln file? I've tried it but I get the following exception:
System.NullReferenceException: Object reference not set to an instance of an obj
ect.
   at NUnit.Util.ProjectConverters.VisualStudioConverter.ConvertVSSolution(Strin
g path)
   at NUnit.Util.ProjectConverters.VisualStudioConverter.ConvertFrom(String path
)
   at NUnit.Util.ProjectService.ConvertFrom(String path)
   at NUnit.Util.ProjectService.LoadProject(String path)
   at NUnit.ConsoleRunner.ConsoleUi.MakeTestPackage(ConsoleOptions options)
   at NUnit.ConsoleRunner.ConsoleUi.Execute(ConsoleOptions options)
   at NUnit.ConsoleRunner.Runner.Main(String[] args)
The solution is quite large (>600 projects) and I am trying to run the unit test from a batch file. I have made a script to run nuint-console on each project, but I can't summarise the results. Is there anyway I can do this better?

**Comment by rprouse** [comment]
We are constantly playing catch-up with support for solution files as Microsoft tweaks the format and support for more and more project types is added. I would highly recommend creating an NUnit project file for your solution and running your tests using that. If you are not adding test projects too frequently, you can just do it once by searching for CSPROJ files and filtering out non-test projects. If your tests change more frequently **and** your tests have some sort of identifiable naming structure, you could script the creation of the project file.

**Comment by CharliePoole** [comment]
The ability to load a solution comes from NUnit V2. Back then, we never thought people would actually run solutions, but we wanted them to be able to load a solution, save a `.nunit` project from it and then edit the project. As time passed, we have realized that people actually want to run from a solution file to avoid the overhead of having to maintain an extra file. We're looking at options but it frankly isn't the highest priority.

In case you wonder why this is not trivial... when we started, there were basically only four project types to deal with. As more were added we added code to exclude them. But project types have so proliferated that there is no easy way for us to guarantee that we know how to convert each one. I'm not sure what the right "solution" is for this.

In the interim, I recommend you create a .nunit file with your test assemblies. Since you have so many projects, I suggest using the nunit 2.6.4 gui to initially generate and edit the project file. Subsequently, you can install the standalone project editor to maintain it or you can use any XML editor. The advantage of the nunit editor is that it understands the semantics of various entries.

I see that @rprouse answered while I was typing this. I'll send this anyway. Seems we were thinking along the same lines. :-)

**Comment by CharliePoole** [comment]
@rprouse What if we just caught exceptions and ignored anything we could not process? We would have to do that only in the context of a solution file of course. Any bad VS project passed on the command-line should not fail silently.

**Comment by jcansdale** [comment]
We might even be able to use MSBuild.

It is now open source:
https://github.com/microsoft/msbuild

> The solution is quite large (>600 projects) and I am trying to run the
unit test from a batch file. I have made a script to run nuint-console on
each project, but I can't summarise the results. Is there anyway I can do
this better?

I hope you meant >60?!?

**Comment by CharliePoole** [comment]
@jcansdale Are you suggesting the VS Project Loader extension use msbuild in some way? Can you enlarge on what you mean?

**Comment by jcansdale** [comment]
Visual Studio solutions and projects are now pretty much all loaded by MSBuild (not sure about the status of C++ projects). The property group are resolved when a project first loads without running any targets. It may be possible to get all the information that we need from these properties. The trick would be determining which version of MSBuild to use.

**Comment by CharliePoole** [comment]
Interesting!

**Comment by yaakov-h** [comment]
FYI there's a public class now in MSBuild 14.0 (I think maybe 12.0 as well) - `Microsoft.Build.Construction.SolutionFile` that can load a solution. Chances are that most of the projects will be `SolutionProjectType.KnownToBeMSBuildFormat` though, so that may or may not be any use.

**Comment by ChrisMaddock** [comment]
@SariNusier - is it correct that you were looking at this with the NUnit v2 console? Do you see the same problem with NUnit v3? v3 can still run v2 tests.

**Comment by SariNusier** [comment]
We haven't tried using V3 yet. I manged to make it work with what the others suggested (creaitng an unit project file). Thank you all for your help :+1:

**Comment by ChrisMaddock** [comment]
There's not sufficient information here to fix this - I'm going to close.

If we can get a repro, we can reopen.
