### ISSUE TITLE
Request for Has.FewerThan

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#1667]
`Has.Exactly(expectedCount).With.Condition` is a great pattern. I have just as much need in my tests of using `Has.FewerThan`.

Here's what I'm thinking:

`Has.FewerThan(count)` - `<`
`Has.MoreThan(count)` - `>`
`Has.AtMost(count)` - `<=` (or possibly `Has.NoMoreThan`)
`Has.AtLeast(count)` - `>=` (or possibly `Has.NoFewerThan`)

The second part of the request is to be able to use `FewerThan` without an added condition. 
`Assert.That(collection, Has.FewerThan(3))` reads better than `Assert.That(collection.Count, Is.LessThan(3))` and gives a better failure message. It's also more consistent next to `Assert.That(collection, Has.FewerThan(2).With.Condition)`.

Currently this same thing is not possible with `Has.Exactly`, but the same logic would apply as applies to `Has.FewerThan` and so I would request that as well.

**Comment by CharliePoole** [comment]
At first glance, this looks like a very unusual need and hence a very low (or no) priority. Perhaps if you explained how it would be used, other people would jump in to say they need it too. :-)

As for the second part. It happens that expressions that can be used either independently or followed by further conditions are quite a bit more work to develop than those that work one way or another. We call them ResolvableConstraintExpressions, because they serve as a front end for several constraints and we have to wait to see the following context in order to decide what constraint is actually needed. This difficulty will play into our prioritization of the issue.

As it stands, without further info, I would call this a "won't fix" but we'll wait to see what comes up. :-)

**Comment by jnm2** [comment]
Is really unusual to assert that `collection.Count <` a certain number?

**Comment by jnm2** [comment]
Is it really unusual to assert that `collection.Count` < a certain number? Or that an enumerable has at least a certain number of items? With or without an additional item constraint, I would think it would see quite a bit of use.

**Comment by CharliePoole** [comment]
My comment about it's being unusual related to the first part of your request - which I took to be the primary request. I tried to make that clear but perhaps didn't.

The second part is more to do with a syntax you would prefer to use, while the first part asks for a new capability that isn't available without looping through the collection.

**Comment by jnm2** [comment]
Granted, I was hoping we'd get the combined benefits of both parts. :-)

Let's address the 'syntax I'd prefer to use.' If I didn't care about the message or I wanted to write message duplicating the logic, I would do this:
Assert.That(collection.Count(_ => _.Enabled) < 2)`

In order to get a nice automatic message I have to be a bit more verbose. This is the minimum verbosity, but I can't do it:
`Assert.That(collection, Has.FewerThan(2).With.Property(nameof(Node.Enabled)).EqualTo(true))`

So it's not about syntax. I'm not aware of anything I *can* do today that provides all the semantics for NUnit to construct an automatic message.

**Comment by CharliePoole** [comment]
Yes, I understand that you can't test for a minimum count of items that match a given condition using the existing syntax. You are asking for new syntax, using four key words. That was the first part of your request. 

We have different views as to how often such a feature might be used. I'm not going to repeat my opinion, because it won't change your mind. Repetition on your part won't change mine either.

In order to __help__ you get this feature, I suggested an approach whereby you give some use cases here in order to get other people to chime in with +1 or some such thing. It's not me, or the nunit devs in general, whom you need to convince, although admittedly convincing one person to actually write the code is also a strategy that can work. :-)

By a use case, in this context, I mean some sort of real situation where you need to verify that a condition is met at least three (or some other number) times. Nothing comes to my mind. That's how we added Exactly: somebody described the situation in which it was needed.

The second part of your request - using the same syntax without a following condition - appeared to me to duplicate other syntax. However, as you apply it to enumerables, it is also a new feature.

My point about the extra work of implementing the same syntax both with and without a following condition was only informational - both for you and for whomever might end up implementing this.

Hope that's clear. If you would like to see this, I suggest attracting some support from other users by explaining what it's good for.

**Comment by CharliePoole** [comment]
@jnm2 BTW, now that you have explained it, the "second part" seems more useful to me.

**Comment by jnm2** [comment]
> By a use case, in this context, I mean some sort of real situation where you need to verify that a condition is met at least three (or some other number) times. Nothing comes to my mind.

Here's one real life scenario. I have a tree data structure that represents reporting data relations. Each node can be enabled or disabled. In some scenarios, any number of roots may be enabled. In other scenarios, no more than one root may be enabled. 0 or 1 is fine. Therefore, I need to assert for multiple instances of these structures that the number of root nodes that are enabled is less than 2.

**Comment by CharliePoole** [comment]
Current syntax for this isn't great...

```C#
Assert.That(nodes, Has.No.Property("Enabled").EqualTo(true)
                     .Or.Exactly(1).Property("Enabled").EqualTo(true));
```

Do other folks see a need to do tests like this?


The consideration of level of effort is clearly not the main thing, but it is important in practical terms. It's fairly easy to placate one's users by just putting stuff on the backlog and never getting to them. I don't want to do that though.

**Comment by jnm2** [comment]
But even that syntax will make a mess of the failure message. I may as well not try to use the fluent interface at all.

**Comment by rprouse** [comment]
This one seems fairly edge case to me. I have never written tests in that way and if I would, I would probably use a linq expression to extract the result I want and test that.

We can keep chasing things like this, but I don't think we will ever satisfy every possible use case. In my mind, better to keep the interface to a reasonable size, which may be a boundary we have already crossed :smile:

**Comment by rprouse** [comment]
How far do we go with this? `Has.One.Property("Enabled").Not.EqualTo(true)`, `Has.Two`, `Has.LessThan.Zero`, `Has.Items.ThatAre.Null`...

**Comment by jnm2** [comment]
@rprouse Very true. What spurred this is that it seems inconsistent to have `Has.Exactly(count).With.Property("Enabled").EqualTo(true)` but no analog that allows you to work with other count comparisons. The request isn't that far from existing code or concepts used in `Has.Exactly`.

**Comment by CharliePoole** [comment]
I'm OK with dropping this. If we deal with the equality case, which is a separate issue, I don't think there is much more benefit here.

**Comment by rprouse** [comment]
Thanks for the idea, but this isn't in keeping with our vision of where we want to take NUnit, so I am closing.
