### ISSUE TITLE
packaging NUnit 3.0.1 for portage

### ISSUE THREAD

**Issue by ArsenShnurkov** [nunit/nunit#1708]
I need to package NUnit.Engine, it is required by Monodevelop-6 or one of it's dependencies.

looking to https://github.com/nunit/nunit/blob/master/nuget/engine/nunit.engine.nuspec
i have following questions:
1) what is the purpose of 2 versions of nunit-agent (raw and x86), do I need them both or not
2) who uses list of addins from file "nunit.nuget.addins"
3) why cecil.dll is packaged into package (do I need 2 versions, or I can use the one global version)

**Comment by CharliePoole** [comment]
To your queestions...

1) The agent is used when running a test in a separate process. You need these if the host will exercise that ability. Some IDEs manage processes themselves, so they may not be needed. Of course, if you are creating a general package, it may be used in ways that you don't anticipate. The -x86 version of the agent is used to run tests as a 32-bit process under a 64-bit operating system. We distribute both agents on linux as well as windows, but I've never been 100% sure if the -x86 version is truly necessary in the linux environment. We've had no issues filed about it, anyway.

2) The file "nunit.nuget.addins" actually contains a list of directories, not addins. It is used strictly in the nuget package to allow an engine installed as a package to find extensions, which have been installed as separate packages. We distribute other .addins files with other package types. I suggest getting the engine to work first without any extensions and then determining whether or how extensions will be supported in your environment. In a global environment (as opposed to nuget packaging) we only provide an addins file if we are packaging the extensions together with the engine in one installation. Note that defining exactly how the engine finds extensions is a big issue for us right now.

3) We package cecil on Windows because there is no package management system on Windows. :-) We don't separately package for linux, so you get the same thing there. A second reason, is that our engine targets .NET 2.0. We had some concern that cecil would stop supporting it soon, although that hasn't happened yet.

You should note that consumers of the engine do not normally reference it. Rather, they reference the nunit.engine.api assembly, which contains a class that understands how to find the engine and get a reference to its ITestEngine interface. The steps that we go through to find the engine are currently quite windows-oriented and we would be glad to take PRs that improve engine locatability on Linux.

I'll keep this issue open for any follow-up discussion we need. I'd be happy to hear how this works out, as I'm considering doing some debian packaging of nunit components myself. While portage is a different envioronment, the issue of how things are split up and accessed is common to all distros.

**Comment by CharliePoole** [comment]
Is this working out OK? Shall I close the issue?

**Comment by ArsenShnurkov** [comment]
yes, works somehow (I still don't acquire full skills to work with nunit myself)
