### ISSUE TITLE
Feature Request: Allow overriding TextMessageWriter.DEFAULT_LINE_LENGTH

### ISSUE THREAD

**Issue by mwaddell** [nunit/nunit#1710]
Currently, TextMessageWriter.DEFAULT_LINE_LENGTH is a constant set to 78.  Since TextMessageWriter instances are created and destroyed as needed during NUnit execution, the only way to override this is to extend both the Assume and Assert classes.

There are many instances where allowing a larger amount of data to be displayed is useful for debugging.  In Python, this is achieved using an optional "maxDiff" property on the test class (https://docs.python.org/2.7/library/unittest.html). 

My quick-and-dirty approach to achieve this is in PR #1709, though I admit that this approach is not ideal.  The cleanest approach would be to have a call within the SetUp method of a test class which overrides the default, but then the default is automatically reverted back for the next class (e.g. the change is scoped to the particular test class).

PS: I'm primarily a Java and Python coder, so please forgive me if my approach is backwards from a .NET perspective.

**Comment by CharliePoole** [comment]
Did you miss my comment that the issue isn't necessary since you had already started with a PR? We just need a discussion of what we are trying to do here, followed by a little on how to do it, followed by code. It's kind of like gathering around the white board when doing some big change... doesn't matter what language you are using.

Anyway, feel free to answer my questions from PR #1709 either here or their. :-)

**Comment by mwaddell** [comment]
@CharliePoole - Sorry, I read your comment after I created the issue based on @rprouse 's comment about this being better suited to an issue.  I just replied to your comment within the PR instead.

**Comment by CharliePoole** [comment]
I think Rob was suggesting a better way to handle such things "next time." :-)
