### ISSUE TITLE
Re-add include and exclude parameters

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#1715]
@MgSam commented on [Fri Jul 29 2016](https://github.com/nunit/docs/issues/94)

It's super confusing that from v2 -> v3 the `include` and `exclude` parameters disappeared in favor of `where`. I think `where` is valuable, but its still overly verbose to handle the extremely common use case of including/excluding categories.

---

@rprouse commented on [Fri Jul 29 2016](https://github.com/nunit/docs/issues/94#issuecomment-236272319)

@MgSam this repository's issues are for NUnit documentation changes. I am moving the issue to the NUnit framework repository.

**Comment by CharliePoole** [comment]
V3 is an entirely new program, seven years in it's development, extensively discussed online especially with regard to changes like this that impact users. We don't want to back out changes we already made and I doubt we would be doing most users a favor by trying to support two different ways of doing things wrt categories. For example what happens if you give a where expression, possibly with categories and also use include or exclude? You could only find out by trying it.

OTOH we could consider improvements to TSL syntax to help you. Can you give us some examples of your usage?

**Comment by MgSam** [comment]
I don't think you should back out any new features; just provide the legacy options where it doesn't hurt anything so that upgrading and using V3 is more seamless. If the legacy options conflict with the  where expression, just throw an error.

DSLs can be really powerful, but they should also be a last resort, IMHO. When every single framework and/or component invents its own DSL, it makes them more complex to use, not less. I think the most common use cases should be supported directly by command line parameters (which include and exclude do).

This issue is aggravated even more because the documentation on the [NUnit website](http://www.nunit.org/index.php?p=consoleCommandLine&r=2.5) is old (and with the breaking changes, incorrect). There is nothing there even hinting that you should be looking at Github for the current documentation. 

Just look at the confusion this had generated on StackOverflow:
http://stackoverflow.com/questions/34511846/nunit-3-0-console-doesnt-work-with-include-parameter

**Comment by rprouse** [comment]
@Sam, you are looking at the 2.5 documentation which is fairly old. We maintain documentation for every 2.x version and do not go back and update older versions with newer information. It is also clearly 2.5 documentation if you look at the menu on the right.

If you go to the documentation link, the link to the 3.0 documentation is fairly clear. http://www.nunit.org/index.php?p=documentation

**Comment by CharliePoole** [comment]
@MgSam See Rob's comment above. When he says "old" that's 15 releases back - May, 2009! Maybe we should add some indication to the older docs that they are legacy! :-)

Regarding the change to the command-line, it was a hard decision discussed at length in the community. Some people agreed with your point of view but most didn't. We kept some things for compatibility but include/exclude just didn't make the cut. It has been gone for about nine months now.

If you have time for it, you can keep abreast of development by following our nunit-discuss list and chime in when changes are being discussed that will impact you.

**Comment by CharliePoole** [comment]
@rprouse I'm thinking that at least the docs home page and the right-hand menu for older versions should say "NUnit 2.5 (Legacy)" or something similar.

Additionally, it would be possible to label every page in some way if we wanted to go that far, by changing the template that builds the pages.

WRT 2.6.4 I'm not sure if that's the way to go, since it's still the current V2 release.

**Comment by MgSam** [comment]
You should definitely make the page much more clear that this is legacy and does not apply to the current version and provide links to the current version docs. A Google search for NUnit brings you straight to those old doc pages.

**Comment by CharliePoole** [comment]
We'll do what we can to clarify this in the docs. 

In the meantime, I suggest taking note of what version of NUnit you are viewing in the documentation. There are docs for every version since NUnit 2.0, released in 2000, on the site. Each page indicates what version it is for both in the URL and at the top of the right-hand menu. Through NUnit 2.6.4, you may be able to find the correct version by modifying the url, although this won't work if the name of the page has changed. 

For NUnit 3.0 and later, we use the wiki, so your best bet is to click Documentation at the top of the page and navigate from there to the correct information. NUnit 3.0 introduced a different structure for the docs, so we no longer maintain separate pages for 3.0, 3.2, 3.4, etc. but merely describe changes in the text.

**Comment by rprouse** [comment]
@MgSam I created nunit/docs#96 to add a warning banner to the top of legacy docs. Thanks for the suggestion.

**Comment by CharliePoole** [comment]
@rprouse Shall we close this one?

**Comment by rprouse** [comment]
Closing, the decision was extensively discussed when the work was done. I appreciate that not everyone agrees, but I do not want to readd command line options that do the same thing in a different format.
