### ISSUE TITLE
Restore teamcity extension to NUnit.Console and NUnit.Runners packages

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#1719]
Even though the extension is in a separate repo, we still want to include the latest version of it as a dependency for our runner packages, as requested by JetBrains.

**Comment by ChrisMaddock** [comment]
I still think that these two packages would fit really neatly in to a separate distribution repo with the msi. (Which would also take care of this issue.)

What are your thoughts, Charlie?

**Comment by ChrisMaddock** [comment]
I should also maybe add that it would be trivial to add this into what's proposed in #1716, basically just copying the nuspec and cake task over.

**Comment by CharliePoole** [comment]
I don't understand why we should want to move these. We aren't trying to move __all__ packages out.

**Comment by ChrisMaddock** [comment]
My feeling was that anything which will be packaging across multiple repositories, should live 'somewhere else', and not in one of the multiple repositories it packages.

How do you envisage the release cycle for these combined packages? Will they be released only when the engine has an update, or additionally whenever any referenced add-in has an update?

**Comment by rprouse** [comment]
@ChrisMaddock I agree with @CharliePoole, the main purpose of the split was so that we could start releasing the console/engine on a different release cycle than the framework. A secondary goal is to possibly split the CF and SL versions of the framework out to their own repositories so they can start moving at their own pace.

As for when they get distributed, I expect that the MSI for the console/engine will pull them in at it's schedule, but we might distribute NuGet packages of individual extensions as needed and separately. I believe the engine nuspec now uses `>= version` for the extensions, so it will pull newer ones in. I see us moving to NuGet as our primary distribution channel with the MSI as a backup for people that need it.

I am kind of viewing this like database normalization. We can refactor everything out until it is fully normalized, but we need to balance that with the increased complexity and potential loss of efficiency for the team.

**Comment by ChrisMaddock** [comment]
> I believe the engine nuspec now uses >= version for the extensions, so it will pull newer ones in. 

I don't _think_ that is the case. I believe >= will always pull the lowest possible version in - meaning we would still need to do a release of Runners/Console for each sub-package release, if we want these packages to install the latest versions.

The [NuGet docs](http://docs.nuget.org/create/versioning#Specifying_Version_Ranges_in_.nuspec_Files) are ambiguous on this, but [this blog](https://weblog.west-wind.com/posts/2014/Jun/19/Nuget-Dependencies-and-latest-Versions) covers the problem. I don't believe behaviour has been changed since...

Just to clarify, I'm not suggesting at all that we move all packaging out of it's own repos, but that each repo handles it's own 'base-level' NuGet package, and that all multi-repo packaging (Msi/NuGet.Runners/NuGet.Console) is handled in a single place, outside of any other repo.

**Comment by ChrisMaddock** [comment]
Perhaps where this differs from the msi (which I hadn't thought through) is that Runners/Console don't need any actual dll's to package, so if they do stay in the engine, there's not the same issue with copying around assemblies we face otherwise.

It would mean however, that doing an addin release would mean doing a separate PR for the engine repository, to update the version number here in the Runners/Console nuspec. That feels odd.

**Comment by CharliePoole** [comment]
@ChrisMaddock There are two fundamental reasons as to why we are splitting out repos...

1. To allow releases to take place on different schedules.

2. To allow different people or organizations to take responsibility for each component.

The teamcity extension is a perfect example. JetBrains has agreed to maintain it. They can do releases on any schedule that's convenient. If we want to bundle the extension with our console runner, then we might need to do a new release but only if we wanted to force users to use the new extension version.

I think nuget works as it needs to work for true dependencies. It always wants to do the safest thing, which usually means the lowest version. In this case there is no true dependency. The runner has no need of any extensions. We are simply using dependency to create a sort of meta-package because nuget doesn't have any other way to do it.

So I agree that this is a gap in what nuget supports but I think we can live with it for now.

**Comment by CharliePoole** [comment]
I should add that I didn't remove teamcity from the console package because of any technical problem. I did so because I thought that was what the teamcity guys had agreed to. I'm putting it back because it turns out that's what they prefer. Either way will work - it's just a policy decision.

**Comment by ChrisMaddock** [comment]
Fair enough. At least the add-ins seem stable enough the limit the number of times this is an issue. 

Agreed it's a shame NuGet don't offer a proper 'meta-package' to cover this sort of thing.

**Comment by CharliePoole** [comment]
Good discussion anyway! I think the take-away is that we shouldn't split things if we want to keep them synchronized. :-)
