### ISSUE TITLE
`--domain=Multiple` fails running in the agent (separate process).

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#1742]
Run multiple unit tests with `--domain=Multiple` and it fails with,

```
  Overall result: System.NullReferenceException: Object reference not set to an instance of an object.
   at NUnit.Common.ColorConsoleWriter.WriteLabel(String label, Object option, ColorStyle valueStyle)
   at NUnit.Common.ColorConsoleWriter.WriteLabelLine(String label, Object option, ColorStyle valueStyle)
   at NUnit.ConsoleRunner.ResultReporter.WriteSummaryReport()
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
   at NUnit.ConsoleRunner.Program.Main(String[] args)
```

It works however with `--inprocess --domain=Multiple`. This was found in 3.4.1, we should retest with latest master as @CharliePoole may have fixed this with recent changes.

**Comment by CharliePoole** [comment]
I think this is a repetition of #1732 except that it was originally reported using only one assembly.

**Comment by CharliePoole** [comment]
I replicated the problem with my current master. In fact, the key difference is the use of two assemblies. I think that's because `domain=Multiple` is actually ignored if there is only one assembly.

While this is probably not critical in itself, it bothers me because I don't understand what is happening here. The issue now only arises when you force domain:Multiple in a situation where you are running in a separate process per assembly and there is therefore only one assembly in the domain anyway. This has always been handled gracefully before. Let me take a closer look.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit-console #29](https://github.com/nunit/nunit-console/issues/29) via [**ZenHub**](https://www.zenhub.com/)
