### ISSUE TITLE
Why Directory.GetCurrentDirectory() return @"C:\Windows\system32" not TestAssembly Directory?

### ISSUE THREAD

**Issue by bobdog1986** [nunit/nunit#1768]
Hello everyone!
I use NUnit V3.4.1 in a WPF Solution, vs2015, window7-32bit.
When I call Directory.GetCurrentDirectory()  in a TestMethod, it return @"C:\Windows"\system32 instead of the TestAssembly's value.
Is it the way NUnit design to be?
Follow are screenshot and code.
![1](https://cloud.githubusercontent.com/assets/9330555/17955090/26a3ff22-6ab2-11e6-824f-1575a8561d23.png)
![2](https://cloud.githubusercontent.com/assets/9330555/17955098/4ca128a8-6ab2-11e6-9a3f-ee7a0240ef08.png)

**Comment by CharliePoole** [comment]
This is covered in the Breaking Changes page of the docs. It's a decision we made when we created NUnit 3.0.

NUnit V2 had a guarantee that the current directory would be the directory that contains your test assembly. In order to guarantee this, we had to change the current directory each time a new assembly was loaded or run. We decided that this was a bad idea, for several reasons:

1. In general, if you start a program with a certain CD, it really should not be changing it.

2. It becomes particularly problematic with the introduction of parallel execution.

As explained in the docs, if you need to find out the directory in which the assembly resides, you can use TestContext.CurrentContext.TestDirectory. 

Note that if you are using the directory for output, you should use WorkDirectory rather than TestDirectory. WorkDirectory usually is the same as TestDirectory but can be changed from the command-line.

**Comment by bobdog1986** [comment]
Thank you for reply.
