### ISSUE TITLE
Failed unit test is hidden for TeamCity

### ISSUE THREAD

**Issue by soetes** [nunit/nunit#1779]
Case:

Project has 302 unit tests, after building this in TeamCity is only shows 301 passed tests.
One (failed) test is hidden, this is only visible in build log from NUnit.

Build log:

[11:54:28][Step 6/10] Test Run Summary
[11:54:28][Step 6/10]   Overall result: Failed
[11:54:28][Step 6/10]   Test Count: 302, Passed: 301, Failed: 1, Inconclusive: 0, Skipped: 0
[11:54:28][Step 6/10]     Failed Tests - Failures: 0, Errors: 1, Invalid: 0
[11:54:28][Step 6/10]   Start time: 2016-09-01 09:54:25Z
[11:54:28][Step 6/10]     End time: 2016-09-01 09:54:28Z
[11:54:28][Step 6/10]     Duration: 3,481 seconds

TeamCity:

![image](https://cloud.githubusercontent.com/assets/21643827/18164904/b492ecc2-7042-11e6-8ef5-a88a387e5f5f.png)

Versions:

- TeamCity Enterprise 9.1.7 (build 37573)
- NUnit 3

**Comment by CharliePoole** [comment]
We can't tell what the problem is without more info...

* What is the output for the failed (hidden) test in the XML report that NUnit produces.
  * Alternatively, can you run the test under NUnit3-console directly and show us the console output?
* What actual versions of the nunit framework and console runner are you using? (e.g.: 3.4.1)

**Comment by NikolayPianikov** [comment]
@stijnsoete also could you run these tests from the command line with the argument "--teamcity" and to attach the console output to this issue?

**Comment by stijnsoete** [comment]
@CharliePoole 

NUnit engine v3.2.0.0
Console runner v4.0.30319.42000

[CharliePoole_ConsoleOutput.txt](https://github.com/nunit/nunit/files/451392/CharliePoole_ConsoleOutput.txt)
[CharliePoole_TestResult.xml.txt](https://github.com/nunit/nunit/files/451398/CharliePoole_TestResult.xml.txt)

@NikolayPianikov 

[NikolayPianikov_Output.txt](https://github.com/nunit/nunit/files/451394/NikolayPianikov_Output.txt)
[NikolayPianikov_TestResult.xml.txt](https://github.com/nunit/nunit/files/451399/NikolayPianikov_TestResult.xml.txt)

**Comment by NikolayPianikov** [comment]
@stijnsoete I see that NikolayPianikov_Output.txt is fully consistent with result from the file NikolayPianikov_TestResult.xml.txt. and as I understand it is not the same case as described in the first message? But what is strange it is different runnings give different results:

Test Count: 48, Passed: 48, Failed: 0, Inconclusive: 0, Skipped: 0
using TC

Test Count: 48, Passed: 47, Failed: 1, Inconclusive: 0, Skipped: 0
without TC

It could be a race condition. Does the testing code use threads or a time in the logic?

**Comment by stijnsoete** [comment]
These unit tests are combination of sync / async When actions. 
No threads / time logic has been used.

**Comment by NikolayPianikov** [comment]
@stijnsoete Could you check only failed test using filter without TC:
`nunit3-console.exe  D:\TeamCity\BuildAgent\temp\buildTmp\TUyIfzELSkHSoHCBNZFTK89gfS2PR1Nd2.nunit --work=D:\TeamCity\BuildAgent\work\7182a01b06a867e6 --where "method=Billing.ContractBilling.Tests.NextPeriodInvoicing.WhenInvoicingANextPeriodWhichIsPartiallyInvoiced.ShouldSavedInvoiceContainAllQuotes"`

**Comment by stijnsoete** [comment]
@NikolayPianikov 

[NikolayPianikov_Output2.txt](https://github.com/nunit/nunit/files/451642/NikolayPianikov_Output2.txt)
[NikolayPianikov_TestResult2.xml.txt](https://github.com/nunit/nunit/files/451648/NikolayPianikov_TestResult2.xml.txt)

**Comment by NikolayPianikov** [comment]
@stijnsoete try 2 equal sign: method==

**Comment by CharliePoole** [comment]
Double or single equal sign are equivalent but the entire argument "method=..." should probably be quoted on the command-line.

The output you did for me shows one test failure and it is reported on the console output by name. It's a mocking failure, which shows up as an NUnit failed test rather than error. That indicates that either your code or the mocking framework is handling the exception and triggering an Assert.Fail or equivalent. I don't know if that's relevant... just mentioning it.

As far as I can see, NUnit handled this case correctly even though it did not show up in TC. You seem to have two problems: (1) an intermittent test failure (2) the failure info is not shown in team city. Looking at the output you gave Nikolay, it appears that was a run that did not fail. You need to give him output from a run that includes the failure, as you produced for me.

@NikolayPianikov I'll leave this one to you to continue with.

**Comment by soetes** [comment]
@NikolayPianikov are there any next steps?

**Comment by NikolayPianikov** [comment]
@soetes let's find a scenario that effect on the fact when one test works successfully under --teamcity but does not work without it:
1. Run only failed (using https://github.com/nunit/docs/wiki/Test-Selection-Language) test with the argument --teamcity to check scenario when some other tests could affect the failed test
2. Run tests with 2 additional arguments --inprocess --teamcity
3. Add RepeatAttribute to the failed test to run it 100 times and run tests using --teamcity

**Comment by NikolayPianikov** [comment]
@soetes do you have any updates?

**Comment by rprouse** [comment]
@soetes I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.
