### ISSUE TITLE
Equivalent to xUnit Assert.Single in nUnit

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#1790]
xUnit has an `Assert.Single (IEnumerable<T>)` and `Assert.Single (IEnumerable)` that each test for the existence of a single element, and throw an exception if not, but return the single element if there is one.

Is there an easy equivalent to this in nUnit?

If not, is this a useful kind of assertion?

**Comment by rprouse** [comment]
I could see the use of this for Linq queries where you expect to only get one item back to ensure you only get one back. 

Working it out, we could change this

```C#
var users = from u in Users where u.Id == id;
Assert.That(users, Has.Exactly(1).Items);
var user = users.First();
Assert.That(user.Name, Is.EqualTo("Rob");
```

to

```C#
var users = from u in Users where u.Id == id;
var user = Assert.Single(users);
Assert.That(user.Name, Is.EqualTo("Rob");
```

It is a bit cleaner and I work with Linq queries that I expect to return a single item often, so I like the idea even though it is a small gain.

My only issue is that the call will hide the fact that the query will get executed twice, once to get the count and once to fetch the item. The first code does the same, but it is more explicit.

**Comment by JustinRChou** [comment]
I suppose this related to what is being fixed in #1668?

But shouldn't it be possible to allow a lambda expression for the filter?

**Comment by jnm2** [comment]
I'd find `Assert.Single` and `Assert.SingleOrDefault` very useful.

**Comment by JustinRChou** [comment]
So far I have the following method signatures

```
public static void Single(IEnumerable collection)
public static void Single(Predicate<object> predicate, IEnumerable collection)
public static void Single(object expected, IEnumerable collection)
```
Should there also be generic methods for those?

I am having trouble understanding how SingleOrDefault would work.
So when there is a null and the expected value, would it count as 2 and fail or pass?

**Comment by CharliePoole** [comment]
@JustinRChou This is labeled as an idea and is in our Discussion pipeline rather than Backlog. Both things mean that it's not yet something we have decided to implement. Normally, after discussion, we would either accept a feature into the backlog or close it as won't fix. It looks as if there is some degree of agreement with this, but we should close the discussion and decide what to implement first.

Since you have commit authority in the framework project, GitHub will let you do all that stuff yourself, but it's not the way we have been doing things. Up to now, either Rob or I have been having the final word on what gets into the backlog as well as into each release. We're working on some documents to clarify that and also to spread it around a bit, but you know how it is with documentation. 😞 

I have a feeling we will probably be doing this one - at least in part - but I didn't want you to spend time on coding it until we were sure.

**Comment by JustinRChou** [comment]
I was seeing it as a really easy implementation so I jumped the gun on this one.

**Comment by ChrisMaddock** [comment]
This would be helpful for us. I'd like to be able to further shorten Rob's example from:
```
var users = from u in Users where u.Id == id;
var user = Assert.Single(users);
Assert.That(user.Name, Is.EqualTo("Rob");
```
to:
```
var users = from u in Users where u.Id == id;
var user = Assert.Single(users).Has.Property("Name").EqualTo("Rob");
```

I presume that's what @oznetmaster meant by "return the single element if there is one"?

> I'd find Assert.Single and Assert.SingleOrDefault very useful.
@jnm2 - Can you clarify the usage of `Assert.SingleOrDefault`?

**Comment by CharliePoole** [comment]
I see this as a big change in direction and not one I'd like to take. First off it gets us back in the business of inventing new classic-form asserts, which we have moved away from over the years in favor of the fluent syntax. Secondly, it introduces an assert that returns a value, which so far we have only done for Assert.Throws. Assert.Single would also be an anomaly in the set of assertions we support by being the only one not built on the constraint model.

I'd prefer to see us extend the Exactly syntax to accomplish the example in a single statement. We can actually do it already but the syntax is labored....

Assert.That(users, Has.Exactly(1).Items.And.Exactly(1).Property("Name").EqualTo("Rob"));

It's the middle of the night and I'm on my phone! I'll continue in the morning.

**Comment by ChrisMaddock** [comment]
You're right, of course this should be constraint based instead. My previous example should have been:

    Assert.That(users, Is.Single().And.Property("Name").EqualTo("Rob")

I quite liked the Single keyword - but you're right, now we have `Exactly()` with a similar purpose, it's less than ideal. Although we do already have `Is.Zero` as a shorthand `Is.EqualTo(0)` - maybe we could have something similar here. That makes it a much smaller issue however, and we'd have to consider if it's worth further expanding the api for a small use-case - I'd be tempted to think not.

**Comment by CharliePoole** [comment]
That looks nicer. But Single is actually more than an equivalent of Exactly(1) because it asserts two things at once:
1. That the collection has just one item
2. That the item matches a constraint

Alternatives

```C#
Assert.That(users, Is.Single.[With.]Property("Name").EqualTo("Rob"));
Assert.Single(users, Has.Property("Name").EqualTo("Rob"));
```

The second option is obviously different from xUnit.net's Assert.Single and might confuse some people.

Shorthands we might want to consider (potentially separate issues):
* Has.One == Has.Exactly(1)
* Has.Size(n) == Has.Exactly(n).Items

**Comment by jnm2** [comment]
I like `Has.One`, almost started a request for exactly that last week.

I agree about not liking to add classic-form asserts. 

Since you asked, here's what I was saying about `Assert.SingleOrDefault` is the logical extension of LINQ's `Single` to `SingleOrDefault`:

```c#
var users = from u in Users where u.Id == id;
Assert.That(users, Has.FewerThan(2).Items, "message");
var user = users.SingleOrDefault();
Assert.That(user.Name, Is.EqualTo("Rob");
```

Becomes:

```c#
var users = from u in Users where u.Id == id;
var user = Assert.SingleOrDefault(users, "message");
Assert.That(user.Name, Is.EqualTo("Rob");
```

That's my use case. The only benefit I see that `Assert.Single` gives over `Enumerable.Single` is the ability to specify a message. Otherwise, who really cares if the exception is an `InvalidOperationException` or an assertion exception?

**Comment by JustinRChou** [comment]
I was plainly looking at `Assert.Single(collection)` being equivalent to `Assert.That(collection,Has.Exactly(1).Items)`.

But in the case of running a Linq query to filter the collection, wouldn't it be better to just write it into the where clause?

```
var users = from u in Users where u.Id == id && i.Name == "Rob";
Assert.Single(users);
```

**Comment by CharliePoole** [comment]
Does anyone want to propose doing something with this or shall we close it?

**Comment by JustinRChou** [comment]
`Has.One()` as a shortcut for `Has.Exactly(1).Items` makes sense.

Would be great if you could pass the object to be checked for equality.

**Comment by CharliePoole** [comment]
So, is this what you mean?

Short Form                | Long Form
----------------------|----------------------------------
Has.One                    | Has.Exactly(1).Items
Has.One.EqualTo("X") | Has.Exactly(1).Items.EqualTo("X")

(I see no reason to make `One` a method.)

**Comment by JustinRChou** [comment]
I was thinking it to be `Has.One(object)` which I guess would be syntactically odd.

But the issue remains of the new method returning the item that isn't solved by `Has.One`.

`Has.One` probably should still be added since `Has.None` exists.

**Comment by rprouse** [comment]
I am fine with Has.One.

**Comment by CharliePoole** [comment]
I created an issue for `Has.One`

Based on the discussion, I'm closing this issue - if anyone disagrees we can always re-open it.
