### ISSUE TITLE
Allow a custom comparer for expected result when using TestCaseData

### ISSUE THREAD

**Issue by pjquirk** [nunit/nunit#1794]
When using `TestCaseData` to encapsulate test cases, it is not possible to specify a custom comparison for the expected result.  I believe this could be added fairly easily by adding either an overload of `Returns`: 

    IComparer comparer = StringComparer.OrdinalIgnoreCase;
    var data = new TestCaseData("foo").Returns("FOO", comparer);

or by adding another fluent-style method:

    IComparer comparer = StringComparer.OrdinalIgnoreCase;
    var data = new TestCaseData("foo").Returns("FOO").Using(comparer);

Inspired by [this question on SO](http://stackoverflow.com/q/39494989/1698557).

**Comment by pjquirk** [comment]
AFAICT, the comparison to the expected return value is made in `TestMethodCommand.Execute`:

    object result = RunTestMethod(context);
    if (testMethod.HasExpectedResult)
        NUnit.Framework.Assert.AreEqual(testMethod.ExpectedResult, result);

I imagine it could be modified to something like the following:

    object result = RunTestMethod(context);
    if (testMethod.HasExpectedResult)
    {
        if (testMethod.HasExpectedResultComparer)
            NUnit.Framework.Assert.That(result, Is.EqualTo(testMethod.ExpectedResult).Using(testMethod.ExpectedResultComparer));
        else
            NUnit.Framework.Assert.That(result, Is.EqualTo(testMethod.ExpectedResult));
    }

**Comment by CharliePoole** [comment]
While this is entirely feasible, I think it's a very low-usage case and would clutter the definition of TestCaseData in a slightly confusing way. The user can already work around this in one of two ways: by adding an override of Equals to a user class or by making the Assert explicitly in the test itself.

Furthermore, adding this to  `TestCaseData` would mean that only tests using the `TestCaseSource` attribute could use it. It's not feasible to add it to either the `TestCase` or `Test` attributes because of limitations in the types of arguments allowed on attributes. This difference would be another source of confusion for users, I think.

However, I'm not the only one here (I hope) with an opinion. 

@nunit/core-team @nunit/contributors  What do you think?

**Comment by immeraufdemhund** [comment]
I agree with @CharliePoole  on this one. I've used `TestCaseData` and `TestCaseSource` frequently and I have found that returning a class as an expected object does indeed confuse things. If I truly need to I'll pass in the expected object and then use my custom compare class. This allows me to re-use my test case source (I make my sources a different class) and then for different scenarios I'll then use different comparers.

**Comment by Sebazzz** [comment]
I agree. I would go even further, in the opposite direction, and say that the Result parameter (`TestCaseSourceAttribute`) and result (for `TestCaseData`) should be deprecated since they add limited value and (imho) confuse because they don't exactly match other NUnit assertion-like api's.

**Comment by immeraufdemhund** [comment]
I'd cry if those were deprecated. Maybe limit the type to value types only? Then either a slight rename to add clarity (or make it a generic `Result` limiting to value types).

OHHH I just thought. If you have result, then expect a `Constraint` to be set as well.... maybe not. I can't think of how that would be clean. Almost feels like it is violating the Dependency Inversion principle.

**Comment by CharliePoole** [comment]
@immeraufdemhund Could you clarify your comment about lack of clarity? :-)

`TestAttribute`, `TestCaseAttribute` and `TestCaseData` all use an `ExpectedResult` property, which has always seemed pretty clear to me. `TestCaseData` also supports the fluent syntax `.Returns(value)`, which of course can't be done for attributes.

**Comment by immeraufdemhund** [comment]
@CharliePoole I'm saying that **if** `ExpectedResult` where to be limited to only value types instead of either value or reference types then maybe it could possibly stand to have a better name to imply that only value are expected in the `ExpectedResult`. As it works right now it is clear as could be.

**Comment by CharliePoole** [comment]
@immeraufdemhund I see. Makes sense now.

**Comment by pjquirk** [comment]
Your reasons against make sense.  Thanks for the consideration!

**Comment by CharliePoole** [comment]
Closing this. As always, it can be re-opened if some new info comes to light.

**Comment by deni35** [comment]
I think for reference-type we need a special function containing all asserts.
And set this function via special attribute. In this case you will not confuse TestCaseData and prevent different logic in one test.

For example:
```
private static readonly TestCaseData[] items = new TestCaseData[] {
   new TestCaseData(...).Returns( new CheckMyResultClass(...) );
};

[TestCaseSource( nameof( items ) )]
[TestResultChecker( nameof(CheckMyResultClass ) )]
public MyResultClass Test(Item[] items) {
   return ...;
}

private static void CheckMyResultClass(MyResultClass expected, MyResultClass actual) {
   Assert....;
}
```

**Comment by CharliePoole** [comment]
@deni35 
Just a heads up... this issue was closed many months ago and really isn't on anyone's radar now. Making a comment here is OK, but won't cause anything to happen. 

There are two ways to go to have a chance for some action.

1) Request this to be re-opened, presenting new reasons we didn't consider in the earlier comments. You should do this if you want us to do pretty much everything that was already turned down. The arguments have to be new ones - not just a statement that you disagree.

2) File a new issue that describes a modified - probably simpler - change that you want along with the reasons. We'll definitely consider that on the merits.

As far as I understand what you wrote above, I guess you are more in the second category. 😄
