### ISSUE TITLE
No way to specify floating point precision for comparison constraints (GreaterThan, GreaterThanOrEqual, etc...)

### ISSUE THREAD

**Issue by stecydube** [nunit/nunit#1804]
Same for version 2.6.4 (which is, sadly, no longer maintained) and version 3 (according to the docs). I haven't had the chance to convert my tests and use it on teamcity.

**Comment by CharliePoole** [comment]
Can you say a little more about what you want to do? You can definitely use do values with those constraints.

**Comment by stecydube** [comment]
I am trying the following test:

```csharp
Assert.That (2.0001, Is.GreaterThanOrEqualTo (2).Within (0.001));
```

Unfortunately there is no `Within()` method that can be used at this point.

**Comment by CharliePoole** [comment]
NUnit's `Within` syntax is used on EqualConstraints to specify a tolerance. `Within(0.001)` is equivalent to writing "plus or minus 0.001." It is only available for equality constraints.

An expression such as the one you wrote could mean a number of things. I am assuming you would expect it to mean ">= 2.001" but somebody else might think it means ">= 1.999"

You can implement what you want by simply adding or subtracting the tolerance form the value.

I agree that it's unfortunate you are able to compile the expression and have it not recognized. We allow it because some constraints involve nested equality comparisons that could use the specified tolerance. Perhaps we should try to make this more restricted in it's application.

**Comment by stecydube** [comment]
I've fix my issue by adding an `.Or.IsEqual ` to the constraint.

**Comment by rprouse** [comment]
@stecydube thanks for the update. I am going to close this as won't fix.
