### ISSUE TITLE
TestContext.Progress.Write writes new line

### ISSUE THREAD

**Issue by yoyos06** [nunit/nunit#1819]
Hi,

The TestContext.Progress.Write method now works exactly the same as TestContext.Progress.WriteLine because it writes a newline character at the end.

**Comment by rprouse** [comment]
Thanks for the report, we will look into it.

**Comment by CharliePoole** [comment]
@yoyos06 Actually, TestContext.Progress.Write doesn't write a newline after the text. It's done in NUnit console.

That might seem like an academic distinction, but it's actually important. The framework puts out events which are received and handled by runners. Each runner may handle them in a different way. For example, some gui might have a special text box that received all the "Progress" output.

In the case of the console runner, the output is handled in a line-oriented way. Every write currently gets a newline because of some earlier errors where lines intended to be separate were run together. We need to be a little smarter about this.

What needs to happen (I'm writing this for whomever implements the fix) is that no newline should be written until it's actually needed. That means the console's TestEventHandler class has to maintain a bit of state regarding whether the last bit of output had a newline attached. When output arrives from some other test it should supply the newline, if it wasn't there already, before writing the new output. It's potentially complicated, but doable.

Since this is a console issue, I'm copying this there. I'm leaving this issue open to deal with NUnitLite, which no doubt has the same problem.

**Comment by MoFtZ** [comment]
Have raised a pull request to fix this issue. Refer #2129
