### ISSUE TITLE
RemotingException from TestContext when using TestCaseSource and multiple assemblies

### ISSUE THREAD

**Issue by flcdrg** [nunit/nunit#1824]
Given multiple test assemblies where at least one assembly has a test method that uses the `TestCaseSource` attribute, and the method linked to by TestCaseSource makes a call to `TestContext.CurrentContext.TestDirectory`,

the test fails with a RemotingException

```
1) Invalid : Second.Tests.UnitTest1.TestMethod1
System.Runtime.Remoting.RemotingException : This remoting proxy has no channel sink which means either the server has no registered server channels that are listening, or this application has no suitable client channel to talk to the server.
   at System.Runtime.Remoting.Proxies.RemotingProxy.InternalInvoke(IMethodCallMessage reqMcmMsg, Boolean useDispatchMessage, Int32 callType)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Framework.Internal.TestExecutionContext.get_CurrentTest()
   at NUnit.Framework.TestContext.get_TestDirectory()
   at Second.Tests.UnitTest1.<MyTestCaseSource>d__0.MoveNext() in D:\dev\Sandbox\NUnitMultipleRemoteException\Second.Tests\UnitTest1.cs:line 14
   at NUnit.Framework.TestCaseSourceAttribute.GetTestCasesFor(IMethodInfo method)
```

I have created a minimal repro here - https://github.com/flcdrg/NUnit-Issue1824.

If I run a single assembly at a time, I don't see the problem. It's only when the test runner spins up multiple agents that it seems to experience this issue.

**Comment by jnm2** [comment]
@nunit/engine-team I don't think this would have been fixed by https://github.com/nunit/nunit-console/pull/223, but I will take this on when I have a chance in case it's related.

@flcdrg Minimal repros are amazing. Thank you!

**Comment by jnm2** [comment]
@flcdrg By running your amazing minimal repro, I see this appears to have been fixed in console 3.6.0. Please try the latest, 3.6.1, and let us know if this fixes your issue.

**Comment by rprouse** [comment]
I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.

**Comment by flcdrg** [comment]
Sorry about not responding previously. Thanks for the fix. We're running the latest version and not having any problems.

**Comment by BlythMeister** [comment]
@rprouse can i request this is re-opened.

We have just upgraded to 3.7.0.0 and get fairly consistent errors with:
```
System.TypeInitializationException : The type initializer for 'MyTest' threw an exception.
  ----> System.Runtime.Remoting.RemotingException : This remoting proxy has no channel sink which means either the server has no registered server channels that are listening, or this application has no suitable client channel to talk to the server.
at FifteenBelow.CWT.CBR.Translation.Tests.SchemaTest.<Tests>d__2.MoveNext() in E:\ba1\comSrc\MyTest.cs:line 23
   at NUnit.Framework.TestCaseSourceAttribute.GetTestCasesFor(IMethodInfo method)
--RemotingException
   at System.Runtime.Remoting.Proxies.RemotingProxy.InternalInvoke(IMethodCallMessage reqMcmMsg, Boolean useDispatchMessage, Int32 callType)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NUnit.Framework.Internal.TestExecutionContext.get_CurrentTest()
   at NUnit.Framework.TestContext.get_TestDirectory()
   at MyTest..cctor() in E:\ba1\comSrc\MyTest.cs:line 14
```

**Comment by rprouse** [comment]
@BlythMeister can you please run with `--inprocess` to see if you get a better error? I would also suggest updating to 3.9.

When you updated to 3.7, what did you update from? Or are you talking about the NUnit Console 3.7?

**Comment by BlythMeister** [comment]
Sorry:
NUnit (3.9)
NUnit.Console (3.7)

We run with multiple agents, inprocess will prevent this i think?

**Comment by rprouse** [comment]
`--inprocess` might prevent this, or it might give us more information why the type initializer threw an exception for `MyTest`. Your error is slightly different than the one above. We need to figure out what is causing the `TypeInitializationException` that I believe is crashing the agent.

**Comment by CharliePoole** [comment]
@BlythMeister Your error doesn't appear related to this issue but looks like a combination of framework / user error. The user error is that `TestDirectory` doesn't work in the constructor because no context for the test has been established yet. The framework error is that we should probably make this completely static so that it does work. 😄 

On your side, a good workaround would be to get the  test directory in a `OneTimeSetUp` method, when a context has been correctly set up. I'm pretty sure that will work for you.

On our side, I think that `TestContext.TestDirectory` should avoid using `TestExecutionContext.CurrentContext` without error checking. We currently use `?.` to avoid null references, but that doesn't stop exceptions from being thrown.

It would be possible to make this completely static if we are willing to use the directory of the calling assembly, assuming that it is the test assembly, since it accesses the context. At least any errors arising from that assumption would be easy to explain.

**Comment by BlythMeister** [comment]
@CharliePoole that would make sense...is that recent change as I only started getting error when going from 3.7 to 3.9.

I'll update my test(s) and try again

**Comment by CharliePoole** [comment]
@BlythMeister We modified `TestDirectory` to make it work in the context of loading tests (in a `TestCaseSource` method, for example) and we may have broken it in this context.

@nunit/framework-team I'm in favor of saying we will support `TestContext.TestDirectory` anywhere it occurs if possible. It's the directory of the test assembly, so it shouldn't really be changing. The only problem is that you can be running multiple test assemblies in the same domain (a rare use, I think) and they may not all be in the same directory due to use of a private probing path. So we do need to know which assembly we are in when return this value. We might have to pick and choose what we are willing to support here.

**Comment by BlythMeister** [comment]
@CharliePoole perfect explanation as to why I have only just come across this with the update 👍

There is a strong argument that what I have is wrong anyway, how can you get the current test directory when not in the scope of a test...and I am impartial as it's not my test...I'm just trying to do our nuget updates 😀

**Comment by jnm2** [comment]
Test runners that do shadow copying like NCrunch and ReSharper will also isolate each assembly in its own hash-named folder. Maybe we could detect the cross assembly case by `Assembly.GetCallingAssembly()`? That's not super great for perf though; if I remember right it reads the previous stack frame so we'd have to use `[MethodImpl(MethodImplOptions.NoInlining)]`.

**Comment by BlythMeister** [comment]
@jnm2 it would be used only in the edge case whereby someone is doing something silly like getting the test directory when not in the scope of a test....and yes, my scenario is in that silly camp 😂

**Comment by CharliePoole** [comment]
@BlythMeister A counter-argument might be that many developers think that they are in the scope of a test when in the constructor of a `TestFixture`. To allow for that, we could check the context and return the directory of the calling assembly when no context exists. Of course, if we throw an exception, we won't get that far.

@jnm2 The Shadow copy problem is easy to avoid. NUnit itself avoids it and I've posted code for it before - which I can't find right now. 😄 Basically, it involves ignoring `Assembly.Location` and working from `Assembly.Codebase` instead. Provided the codebase is a `//file:` you can easily get the true location from which the assembly was loaded. That's usually what people want, since they have other files stored in the same directory.

**Comment by BlythMeister** [comment]
@CharliePoole i've also got this error when trying to access the TestDirectory as part of a TestCaseSource function.
Is this also not allowed?

**Comment by CharliePoole** [comment]
@BlythMeister It's supposed to work but it sounds as if it's not fixed or newly broken.

 @jnm2 That's as much as I can help him from my phone. Can you take a look at it?

**Comment by BlythMeister** [comment]
Unfortunately the code is in a closed source project.
I'll try and mock up an example for you which mirrors what we have.

**Comment by jnm2** [comment]
You know, repeatedly halving the project till you get a minimal repro is super helpful even when the original project is open source. 😃

**Comment by BlythMeister** [comment]
I'm starting with something huge....I might need to go more than half 😂

**Comment by jnm2** [comment]
So true! Tactical halving then 😆
This probably isn't your case, but half the time I've done this I end up answering my own question by discovering that it was user error xD.

**Comment by BlythMeister** [comment]
Having tried to repo this small scale, i cannot.
I also cannot repo the issue of using the test directory in a constructor.

Additional to this, i'm also not able to 100% repeat this issue on large scale.
Sometimes it works, sometimes it doesn't...

This is a copy of what i have that fails but in small scale, and it fails sometimes on large scale tests, but never in small scale:
```
[TestFixture]
    public class Class1
    {
        private static readonly string Dir = TestContext.CurrentContext.TestDirectory;

        public static IEnumerable<TestCaseData> GetCases()
        {
            var files = Directory.GetFiles(Dir, "*.*");
            foreach (var file in files)
            {
                yield return new TestCaseData(file);
            }
        }

        [Test, TestCaseSource("GetCases")]
        public void TestName(string caseName)
        {
            Console.WriteLine(caseName);
            Assert.Pass();
        }
    }
```
i also have real tests like this, and same issue with repo
```
[TestFixture]
    public class Class1
    {
        public static IEnumerable<TestCaseData> GetCases()
        {
            var files = Directory.GetFiles(TestContext.CurrentContext.TestDirectory, "*.*");
            foreach (var file in files)
            {
                yield return new TestCaseData(file);
            }
        }

        [Test, TestCaseSource("GetCases")]
        public void TestName(string caseName)
        {
            Console.WriteLine(caseName);
            Assert.Pass();
        }
    }
```
So i'm at a complete loss as to how i manage to get that error...ever :p

**Comment by jnm2** [comment]
Ugh. Intermittent errors. That's the worst kind.

When you say scale- do you think if I just duplicated your `TestName` method here several hundred times that it might start showing up for me?

**Comment by BlythMeister** [comment]
Our CI has 20k tests....I will try with copy/paste tests 🙄
