### ISSUE TITLE
ConcurrentQueue is duplicate with System.Threading.dll package

### ISSUE THREAD

**Issue by NN---** [nunit/nunit#1859]
Make .NET 3.5 project.
Install both NUnit package and System.Threading.dll package (https://www.nuget.org/packages/System.Threading.dll/)

System.Collections.Concurrent.ConcurrentQueue defined in both assemblies.

**Comment by CharliePoole** [comment]
This class is in the 2.0 and 3.5 builds of the framework. One solution would be to put it into our own namespace, since it is only used internally. That will require some aliasing where it's used. We could also experiment with changing it's visibility - not sure that will remove the conflict. A third solution would be for us to use the same package ourselves, although it most likely contains stuff we don't need.

**Comment by CharliePoole** [comment]
As a workaround, you can use an alias on the reference to System.Threading.dll. Or make your test project target .NET 4.0 or higher.

**Comment by NN---** [comment]
@CharliePoole If it is used internally then mark it internal and it will solve the issue.
Thanks.

**Comment by CharliePoole** [comment]
@NN Certainly the easiest if it works. I guess I'm slightly distrustful of VS doing the logical thing. :smile: 

We kept these classes taken from Mono public simply because we didn't want to modify the source, but in retrospect maybe they should all be internal.

**Comment by NN---** [comment]
Thanks
Waiting for the update.

**Comment by hknielsen** [comment]
@CharliePoole we had same issue, with clash of classes. So I made a PR resolving this, with the solution that @NN--- and you talked about. And that fixed it.
