### ISSUE TITLE
LogicalCallContext lost with async SetUp methods

### ISSUE THREAD

**Issue by oliverhanappi** [nunit/nunit#1895]
In NUnit 3.5.0 running on .NET 4.5: The logical call context set during async SetUp methods is lost when running tests. See the following failing unit test `PreservesLogicalCallContextOnAsyncSetUp`. Note that `PreservesLogicalCallContextOnSyncSetUp` works without problems.

    [TestFixture]
    public class LogicalCallContextTest
    {
      [SetUp]
      public void SyncSetUp()
      {
        CallContext.LogicalSetData ("MySyncKey", 123);
      }

      [SetUp]
      public async Task AsyncSetUp ()
      {
        CallContext.LogicalSetData ("MyAsyncKey", 456);
      }

      [Test]
      public void PreservesLogicalCallContextOnSyncSetUp ()
      {
        var data = CallContext.LogicalGetData ("MySyncKey");
        Assert.That (data, Is.EqualTo (123));
      }

      [Test]
      public void PreservesLogicalCallContextOnAsyncSetUp ()
      {
        var data = CallContext.LogicalGetData ("MyAsyncKey");
        Assert.That (data, Is.EqualTo (456));
      }
    }

**Comment by rprouse** [comment]
Sorry that we haven't responded earlier. Have you debugged these tests? Is the `AsyncSetup` getting called?

**Comment by oliverhanappi** [comment]
Yes, the method `AsyncSetUp` is getting called. The issue also occurs if there is only a single setup method in the test fixture.

**Comment by oliverhanappi** [comment]
@rprouse Any updates on this issue?

**Comment by rprouse** [comment]
@oliverhanappi nobody has triaged this issue yet.

**Comment by jnm2** [comment]
This looks like a duplicate, but it has a workaround: https://github.com/nunit/nunit/issues/1200#issuecomment-312119597

@rprouse This, like #1200, connects to that async PR of mine. I'll get some movement on that today.

**Comment by jnm2** [comment]
My Kraken X62 came just now, so first I'm going to get my dev machine back up and running 😃

**Comment by jnm2** [comment]
Short story is, the CPU is damaged from the prior pump failure.

**Comment by jnm2** [comment]
@oliverhanappi This behavior you're seeing is not specific to NUnit as far as I can tell. 

When you mark your method `async`, the async method builder (since .NET 4.5) puts the logical call context into copy-on-write mode. That means that any `LogicalSetData` calls you make can never be seen by your caller. This applies to async SetUp methods too; the `async` keyword wipes out any `LogicalSetData` changes by the time it gets back to NUnit.

Here's a demonstration which does not require NUnit:

```cs
using System;
using System.Runtime.Remoting.Messaging;
using System.Threading.Tasks;

public static class Program
{
    public static async Task Main()
    {
        await Call();
        Console.WriteLine("Main: " + CallContext.LogicalGetData("SomeData"));
    }

    public static async Task Call()
    {
        CallContext.LogicalSetData("SomeData", 42);

        await InnerCall();
        Console.WriteLine("Call (after await): " + CallContext.LogicalGetData("SomeData"));
    }

    public static async Task InnerCall()
    {
        Console.WriteLine("InnerCall: " + CallContext.LogicalGetData("SomeData"));
    }
}
```

This will output:

```
InnerCall: 42
Call (after await): 42
Main:
```

`"SomeData"` does not exist in `Main`. For more information, see http://blog.stephencleary.com/2013/04/implicit-async-context-asynclocal.html.

💡 As a workaround, consider removing the `async` keyword from your setup. You can still return `Task`.
