### ISSUE TITLE
Support predicate type argument for TestCaseData Returns property

### ISSUE THREAD

**Issue by WattsC-90** [nunit/nunit#1903]
I have been trying to find a way to get Returns to support a condition, rather than an absolute value in my TestCaseData factory.
As opposed to setting say `.Returns(10)` (its current format), i would like to be able to say: `.Returns(x=>x > 5)`. 
The scenario I have is that I do not care what number is returned, as long as the number is greater than 0. I am trying not to use multiple tests because I don't think i should have to as the test is doing the same thing. I have tried to find a way round it but unable to.

**Comment by rprouse** [comment]
As you know, NUnit only does equality checking on the return value. This is an interesting idea, but it would require us to have special code that skips equality checking for the various varieties of `Func<TReturn>`, `Func<T, TReturn>`, etc. and use those instead of doing equality checking. This would complicate the code and there is a workaround.

To support this in your test, instead of using the `.Returns` to pass in your lambda, add an additional parameter `Func<int, bool> expected` to your test method and add the lambda to the parameters in your `TestCaseData`. Your test method will return void and your last line will instead be `Assert.That(expected(x), Is.True);`

As an example,

```C#
[TestCaseSource(nameof(TestData))]
public void TestExpectedLambda(int x, Func<int, bool> expected)
{
    Assert.That(expected(x), Is.True);
}

static IEnumerable TestData()
{
    yield return new TestCaseData(10, new Func<int, bool>(x => x > 5));
    yield return new TestCaseData(2, new Func<int, bool>(x => x < 3));
}
```

Since we have a workaround and I am reluctant to add complexity to the code, I am going to make this an idea and open it to the @nunit/contributors to comment. As I see it, we have three options,

1. Allow `Returns` to return a `Func` that we evaluated (as requested)
2. Allow the overrides of `TestCaseData` to take delegates to make the workaround easier
3. Do nothing and use the workaround

My vote is for the third option.

**Comment by WattsC-90** [comment]
Hi Rob, 
That workaround was exactly what i put in, passing a predicate through and doing the assert in the test as opposed to relying on the framework to do the assertion.

Like you say, the third option (iv included my code below as an alternative) seems to work nicely and isolates the assert case from the test code which was the whole purpose of my question.

Thanks for your time! Much appreciated having someone who understands the framework to confirm what I was thinking!

'public static IEnumerable AddNew 
{
    get
    {
        yield return new TestCaseData(CreatemyObject(), new Predicate<int>(x => x > 0));
    }
}'

'public void AddCategory(myObject obj, Predicate<int> validator )
{
    // do something
    Assert.True(validator(ret));
}'

**Comment by CharliePoole** [comment]
I'm for the third option as well. I view Returns as a bit of syntactic sugar that you use when it's handy, otherwise pass an argument.
