### ISSUE TITLE
SetUpAttribute attribute not allowed in a SetUpFixture - base class and derived class implementation

### ISSUE THREAD

**Issue by gachu16** [nunit/nunit#1906]
I upgraded Nunit from 2.6.4 to 3.2.1, and the tests which were using inheritance have started to fail with the message "OneTimeSetUp: SetUpAttribute attribute not allowed in a SetUpFixture".

The code is as follows:
[NUnit.txt](https://github.com/nunit/nunit/files/600805/NUnit.txt)

Note:
Except for "FixtureBase" class,all the other classes are in the same namespace.

It was working perfectly in Nuni.2.6.2, not sure how to make this work in 3.2.1, any help will be really helpful.

Thanks

**Comment by CharliePoole** [comment]
SetUpFixture now uses the OneTimeSetUp attribute for this purpose. See "Breaking Changes" in the docs.

**Comment by gachu16** [comment]
I tried the OneTimeSetUp, but i still received the same error message.
Since there are two abstract classes, not sure in which one i need to use OneTimeSetUp

**Comment by CharliePoole** [comment]
Your supplied code does not contain a SetUpFixture, only TestFixtures. Does the autotest software create one?

**Comment by CharliePoole** [comment]
IOW are you using software that only works with nunit 2?

**Comment by gachu16** [comment]
I am using Resharper to run the tests and it supports Nunit 3.0, also i wasnt using SetUpFixture anywhere in my tests, and it worked perfectlt in Nunit2.6.4.
Will the upgrade to Nunit3.2.1 require changes to class to use SetUpFixture?

**Comment by CharliePoole** [comment]
You must have a SetUpFixture somewhere in order to get that error message.

Your test uses something called Auto fixture. That's what I am suspecting.

**Comment by BermudaLamb** [comment]
I don't see a resolution for this issue. I'm using NUnit 3.11.0
SetUpAttribute attribute not allowed in a SetUpFixture
  Exception doesn't have a stacktrace
My code looks like this:

`   [SetUpFixture]
    public class CCIOneTimeSetup : GMSignoffTestBase
    {
        internal static Dictionary<eOpportunityType, Configuration> Configurations { get; set; }
        internal static Dictionary<eOpportunityType, int> OpportunityCount { get; set; }
        internal static Dictionary<eOpportunityType, bool> HasOpportunities { get; set; }

        [OneTimeSetUp]
        public void Init()
        {
`

**Comment by CharliePoole** [comment]
@BermudaLamb I added "fences" to your code so it would all display correctly.

This issue was about an error in a `SetUpFixture`with the message that `SetUpAttribute` was not allowed. The original poster was not actually using `SetUpFixture` and we think the message have been caused by generated code that was not posted. Without full info, @rprouse closed the issue without further action.

The code you posted does not seem to have anything in common with this issue except that it has to do with a `SetUpFixture`. It would be better to create a new issue and fully describe the problem. I can see in your sample that you have a `SetUpFixture` with a `OneTimeSetUp` (not `SetUp`) attribute. Is that your full code that causes the problem? (It looks like it's cut off)

If you post an issue, please tell us (1) what software you use to run the tests, including versions, (2) what you expected to happen and (3) what actually happened, i.e. the error message. That way, we can try to help resolve the problem rather than just closing the issue has we had to do with the original post.
