### ISSUE TITLE
NullReferenceException when null arguments are used in TestFixtureAttribute

### ISSUE THREAD

**Issue by sir-wilhelm** [nunit/nunit#1934]
This seems to be related to #1507. We started getting several errors after moving from 3.4 to 3.5. The errors can be seen in the Visual Studio test runner and the nunit3-console runner. The errors are all similar to the following:
```
1) Invalid : Tests.Controls.iBus.When_the_passed_in_domain_is_null
An exception was thrown while loading the test.
System.NullReferenceException: Object reference not set to an instance of an object.
   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.HasArguments(IFixtureBuilder attr)
   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.GetFixtureBuilderAttributes(ITypeInfo typeInfo)
   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(ITypeInfo typeInfo)
```

This is one example of the test fixtures/constructors that are failing again:
```
[TestFixture(null)]
[TestFixture("")]
[TestFixture(" ")]
[TestFixture("\t")]
public class When_the_passed_in_domain_is_null : BasePresenterTest
{
    private readonly string _domain;

    public When_the_passed_in_domain_is_null(string domain)
    {
        _domain = domain;
    }
}
```

**Comment by GCichosz** [comment]
How a confirmation of that kind of issue should look like? I got similar results using console runner build from the newest sources. Is that enough to start working on this issue?

**Comment by ChrisMaddock** [comment]
Yup - that's great @GCichosz. 😄 

Issues are generally marked with [confirm] when they're first reported - if anyone else can repro them they're considered confirmed. It often makes a good triage-stage, which rules out some errors users report specific to their own machines machine/tests suites, and catches issues where there isn't enough information to reproduce the problem.

I've assigned you to this one. I'm not sure if you've already dug through the history, but looks like is a regression which may have been caused by https://github.com/nunit/nunit/pull/1508 - maybe worth a look at what went on there.

**Comment by GCichosz** [comment]
Sorry to ask, but how do I debug nunit.framework through nunit3-console? I tried copying nunit.framework.dll and starting nunit3-console as an external process, but that doesn't seem to work.

**Comment by ChrisMaddock** [comment]
I normally find it easier to use the nunitlite-runner, rather than the nunit-console from debugging framework issues.

I do everything in the VS solution. First I add a test that hits the problem to nunit.framework.tests-2.0. Then I pass the path of the the nunit.framework.tests-2.0.dll as a command line argument to the nunitlite-runner-2.0 project, and set that as my startup project.

The nunit.framework.tests projects are built against the relative framework in the soultion, so doing that allows you to hit breakpoints in the framework. 😄

We should maybe write this up somewhere, not the console and framework are in different repositories.
