### ISSUE TITLE
ExpectedExceptionAttribute

### ISSUE THREAD

**Issue by oleoleg** [nunit/nunit#1938]
I'm using in VS2013 nunit.framework 3.5.0.0 taken from NuGet packages. What do I need to connect the lib so I could test using the attribute: [ExpectedException (typeof (ArgumentException))]?

**Comment by CharliePoole** [comment]
ExpectedExceptionAttribute was removed from NUnit at the time of creating NUnit 3. This is explained in the docs, particularly the BreakingChanges page (if you are upgrading from 2.0).

You should use Assert.Throws in your tests at the point where you expect the exception rather than trying to annotate the test as a whole. This ensures that the exception is encountered where you expected it and not in some other code in the test.
