### ISSUE TITLE
"Method has non-void return value, but no result is expected"

### ISSUE THREAD

**Issue by Nullstr1ng** [nunit/nunit#1974]
I am trying to unit test for the first time and I choose NUnit.

I am using Visual Studio 2015 Update 2
NUnit version 3.6.00
NUnit 3 Test Adapter 3.6.1.0

`using NUnit.Framework;

namespace ConsoleApplication1.test
{
    [TestFixture]
    public class math_test
    {
        [TestCase]
        public void DoAdd()
        {
            int result = Add(1, 2);
        }

        [Test]
        public int Add(int x, int y)
        {
            int z = x + y;

            return z;
        }
    }
}`

I tried a very simple test code and I got confused on the result for Add
"Method has non-void return value, but no result is expected"
Why is that?

**Comment by JustinRChou** [comment]
Remove test attribute from add

And in doadd, add a Assert.AreEquals(3, Add(1,2));

**Comment by JustinRChou** [comment]
Wait, you ould replace the doadd code with my suggestion and see if it works.

**Comment by Nullstr1ng** [comment]
I tried Microsoft.VisualStudio.TestTools.UnitTesting and it passed. 
view: http://screencast.com/t/DwLM5H3AWyE

I am not sure why NUnit returning that message

**Comment by Nullstr1ng** [comment]
Assert.AreEqual(3, Add(1, 2)); // passed
https://www.screencast.com/t/Lm5e853rh

**Comment by JustinRChou** [comment]
You could look at the samples here 
https://github.com/nunit/nunit-csharp-samples/blob/master/syntax/AssertSyntaxTests.cs

**Comment by CharliePoole** [comment]
@Nullstr1ng Replying to your original message...

Your Add method is not a test. It's the thing you are testing. It should not have any NUnit attributes or asserts because the thing you are testing doesn't know anything about NUnit. The error message you got is because of the Test attribute, which you should remove.

Your test is DoAdd1. It's not a TestCase (which requires parameters) but a Test. Use the Test attribute.
As @JustinRChou advises, you need to have an Assert in the method. Otherwise, it's not actually testing anything.

If I may be brutally frank, it looks as if you haven't bothered to read up on how to use NUnit before using it. The docs are here: https://github.com/nunit/docs/wiki/NUnit-Documentation

I suggest reading up on both NUnit and MSTest before deciding which one you want to use.

Charlie

**Comment by CharliePoole** [comment]
Closing this, but feel free to ask follow-up questions here. We'll see them.

**Comment by CharliePoole** [comment]
If you tell NUnit a method is a test, then you are telling NUnit to run it. But in this case, a value is returned and NUnit has no idea what to do with that value.

@bhavnajoshi1989 

NUnit supports non-void test functions if you tell NUnit what the result should be through an attribute. Check the docs for `TestAttribute`or `TestCaseAttribute`.

However, that's not relevant to this specific case.

The method `sampletest` is marked as a test, but it isn't one. You only have one test, `isnotequal`, which calls `sampletest`. The method `sampletest` is the thing you are testing, not the test. Normally, of course, it would be a method in your application but putting it right in the test class as a way to see how NUnit works is certainly OK.

Continue to use [Test] on your actual tests, which should be public void methods. Once you are a little more familiar with NUnit, look up parameterized tests to see how NUnit can use return values.

Now for a gentle (i hope) hint about asking questions. If this answer sounds familiar, it's because it repeats the answer I gave above in this same thread. Please read the answers as well as the questions!
