### ISSUE TITLE
Exception thrown by other thread

### ISSUE THREAD

**Issue by HollyDOL** [nunit/nunit#1988]
During upgrade to NUnit 3.5.0 (from 2.x) I have found out some tests don't fail, but throw exceptions on console (Console runner execution) while the test itself passes. After investigation I figured out why.

Test method creates an object, which inside creates thread and runs WaitHandle.WaitAny(waiters) in that thread... the issue here is one waiter is null and thanks to that, this throws an exception. But, because it is running in different thread and following asserts don't check on anything related to this thread, test passes.

Putting aside this proves the code is obviously badly designed, are there any possibilities to be able to catch such exceptions from the NUnit side? I am quite doubtful it's possible at all, but maybe you know a way?

**Comment by CharliePoole** [comment]
This is a long-standing testing issue in NUnit and other test frameworks. A test an create a thread and that thread runs without any reference to the test. It may even keep running long after the test completed, making it impossible to know what test was the original cause of the exception.

The general advice for avoiding this is not to do it. :smile: However, that may not be possible if it's the system under test that is creating the thread. At some point in the future, we may come up with a feature that tracks threads, but that would be fairly major.

Was the NUnit V2 reporting better on this? In the V2 Gui, I believe we were catching unexpected exceptions and displaying something - it has been a while since I looked at it. If the V2 reporting made things easier for you, we could look at introducing something similar in the current NUnit. That might be easier than actually solving the problem of associating the exceptions with specific tests.

**Comment by HollyDOL** [comment]
I don't have old v2 reports at hand, but I'll get them and check. According to build engineer though those exceptions from other thread didn't make it through anywhere in v2 (btw thanks to v3 already revealed multiple bugs that v2 didn't point out). Not sure about gui, we only use resharper runner from VS and console runner from Jenkins build machines.

If the foreign threads exceptions could be made to get catched in the reporting instead of Console.Error (even without specific test) it would be of a significant help.

**Comment by jnm2** [comment]
There is no way to prevent an unhandled exception in a thread from crashing your process. The only solution is to manage the catching and reporting yourself, since you're managing the thread yourself. (If you use Task, it does this for you with AppDomain.UnhandledException, and GUI message pumps have their own equivalent.)

Typically a component that creates a thread also provides some sort of notification about what it's doing so other threads can interact with the component.

The simplest way to handle it is to wrap the entire threadstart in a try...catch...finally and set a TaskCompletionSource in the catch (SetException) and in the finally (SetResult) and expose the .Task so that anyone can await it, say at the end of their test, which will throw the exception inside the test.

**Comment by jnm2** [comment]
One example:

```c#
InvokeOnNewThread(() => MessageBox.Show("Example")).GetAwaiter().GetResult(); // Block
await InvokeOnNewThread(() => MessageBox.Show("Example")); // Or await

public static Task InvokeOnNewThread(Action action, ApartmentState? apartmentState = null)
{
    var completionSource = new TaskCompletionSource<object>(null);

    var thread = new Thread(() =>
    {
        try
        {
            action.Invoke();
            completionSource.SetResult(null);
        }
        catch (Exception ex)
        {
            completionSource.SetException(ex);
        }
    });
    if (apartmentState != null) thread.SetApartmentState(apartmentState.Value);
    thread.Start();

    return completionSource.Task;
}
```

**Comment by jnm2** [comment]
Here's an example:

```c#
[Test]
public static async Task ExampleTest()
{
    var component = new ExampleComponent();
    await component.WhenWinished;
}

public class ExampleComponent
{
    private readonly TaskCompletionSource<object> threadCompletionSource = new TaskCompletionSource<object>();

    public ExampleComponent()
    {
        new Thread(ThreadStart) { Name = nameof(ExampleComponent) }.Start();
    }

    private void ThreadStart()
    {
        try
        {
            // ...

            WaitHandle.WaitAny(new[]
            {
                (WaitHandle)null // Oops
            });

            // ...

            threadCompletionSource.SetResult(null);
        }
        catch (Exception ex)
        {
            threadCompletionSource.SetException(ex);
        }
    }

    public Task WhenWinished => threadCompletionSource.Task;
}
```

**Comment by jnm2** [comment]
More cleanly factored:

```c#
[Test]
public static async Task ExampleTest()
{
    var component = new ExampleComponent();
    await component.WhenFinished;
}

[Test]
public static void ExampleTestNoAsync()
{
    var component = new ExampleComponent();
    component.WhenFinished.GetAwaiter().GetResult(); // If you hate async; just don't use Task.Wait, it wraps the exception
}

public static Task RunOnNewThread(Action action, ApartmentState apartmentState = ApartmentState.MTA)
{
    var completionSource = new TaskCompletionSource<object>();
    var thread = new Thread(() =>
    {
        try
        {
            action.Invoke();
            completionSource.SetResult(null);
        }
        catch (Exception ex)
        {
            completionSource.SetException(ex);
        }
    }) { Name = $"{nameof(RunOnNewThread)}({action.Method.Name})"};
    thread.SetApartmentState(apartmentState);
    thread.Start();

    return completionSource.Task;
}

public class ExampleComponent
{
    public ExampleComponent()
    {
        WhenFinished = RunOnNewThread(ActualWork);
    }

    private void ActualWork()
    {
        // ...

        WaitHandle.WaitAny(new[]
        {
            (WaitHandle)null // Oops
        });

        // ...
    }

    public Task WhenFinished { get; }
}
```

**Comment by jnm2** [comment]
@HollyDOL Also, this may or may not apply here, but you may be interested in using [ThreadPool.RegisterWaitForSingleObject](https://msdn.microsoft.com/en-us/library/system.threading.threadpool.registerwaitforsingleobject.aspx) on each wait handle instead of creating a thread and blocking it using `WaitHandle.WaitAny` or `WaitHandle.WaitAll`.

ThreadPool.RegisterWaitForSingleObject scales much better because you don't create a blocked thread; you use the CLR's dedicated unmanaged thread for this purpose.

**Comment by HollyDOL** [comment]
Hello! Thanks for the tips. If I could I would have changed both tests and code, which both are... let's say not ideal, I am aware of it. Unfortunately though I don't have enough leverage currently to push such a change through (it's an antipattern repeated over almost 500MB of source code).

**Comment by jnm2** [comment]
😢 That's no fun. They created a thread with no top level exception reporting, so your hands are tied. Maybe you can point them this way. If you can't change much, maybe you can at least convince them to wrap the threadstart in `try...catch` and expose a simple event much like `Appdomain.UnhandledException`.

**Comment by rprouse** [comment]
This has been inactive for awhile and is a question, so I am closing. Please comment if there are any updates.
