### ISSUE TITLE
3.6 Console runner hanging on unit tests

### ISSUE THREAD

**Issue by agray** [nunit/nunit#2006]
I followed these steps:
1. Uninstalled NUnit 3.5
2. Installed  NUnit Console 3.6
3. Downloaded NUnit 3.6 zip and copied 4.5 directory to "C:\Program Files (x86)\NUnit.org\"
4. Executed the following command (unchanged from last release) in both Jenkins and from an administrator command prompt:

     `"C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" Saucery\NUnit\Version3\UnitTests\bin\Release\UnitTests.dll --result:nunit-unittests-testsuite.xml;format=nunit2`

It displays:

    NUnit Console Runner 3.6.0 
    Copyright (C) 2017 Charlie Poole

    Runtime Environment
       OS Version: Microsoft Windows NT 10.0.14393.0
      CLR Version: 4.0.30319.42000

    Test Files
        Saucery\NUnit\Version3\UnitTests\bin\Release\UnitTests.dll

then  just hangs .

This command was working with NUnit 3.5 console runner and would take seconds to complete.

Should I have installed NUnit 3.6 Framework?  Is there an installer for the framework anymore?  What am I missing?

**Comment by CharliePoole** [comment]
There is no longer an installer for the framework. Uninstalling the old msi removed the framework that was being referenced by your tests. Installing the zip should work if you changed the references in your test assembly to use the new framework and recompiled. Did you do that?

FYI, the intention is that folks will not remove old framework versions until they are no longer in use. For manual installation, I would suggest using something like `nunit.org\framework\<version>` as the location. New console runners work with older frameworks until you are ready to upgrade.

It's unfortunate that uninstalling the combined msi removes the old framework. That's one of the main reasons why we took the framework out of the msi. One alternative to installing the framework manually in a central location is to use the appropriate version of the nuget package in each project.

**Comment by agray** [comment]
3,6 binaries were an in place replacement from 3.5 (yes).  same name and number of files in **C:\Program Files (x86)\NUnit.org\net-4.5**
    
    mock-assembly.exe
    nunit.framework.dll
    nunit.framework.tests.dll
    nunit.framework.xml
    nunit.testdata.dll
    nunitlite-runner.exe
    nunitlite.dll
    nunitlite.tests.exe
    slow-nunit-tests.dll

In Jenkins the command I run from a Windows Batch command step is:

    "C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" Saucery\NUnit\Version3\UnitTests\bin\Release\UnitTests.dll --result:nunit-unittests-testsuite.xml;format=nunit2
    exit %%ERRORLEVEL%%

Why is the console.exe not finding nunit.framework.dll?

**Comment by ChrisMaddock** [comment]
I'm not entirely convinced this is related to the framework reference. Three reasons:

1. The framework was first removed from the installer in 3.5. The changes to the installer between 3.5 and 3.6 were minimal.
2. Not being able to locate the framework would normally result in the console exiting with the INVALID_ASSEMBLY exit code, rather than the console hanging.
3. If the Test Adapter can run the tests, then the assembly must be referencing the framework. If nothing has changed with your build between running with the adapter and the console, then it's unclear why the console wouldn't be able to find the framework.

I wonder if a change to the console between the two versions is malfunctioning under some case specific to your tests. Have you tried looking at debug logs?

> Attempting to install nunit 3.4.1 doesn't work because it says that a later version is installed.

If you uninstall v3.6 manually first, this should work. If not, that's a bug we should log.

**Comment by agray** [comment]
Hi @ChrisMaddock,  Tests have not changed.  Not at all.   The ran fine under NUnit 3.5

I would suggest we REALLY need some Step by Step CLEAR documentation on how to install and upgrade all the myriad components of NUnit on Windows.  I honestly have no idea, if I had to explain it to someone, the correct way to do this and I am worried that my registry is messed up in some way now.

How do I see debug logs?  I tried adding --trace=Verbose and --trace=Debug to no effect whatsoever. I'd give more details of the issue if I could get NUnit to spit any out.

I finally found the 3.6 console MSI and managed to install that.  No effect: still hangs.

How do I recover a running system?

Failing that: Is there a way to COMPLETELY AND UTTERLY uninstall ALL NUnit components from my machine and WIPE ALL references from the registry without FORMAT C:\ ?  I'd then like to see some documentation that explains what to install in what order to install NUnit properly.

**Comment by CharliePoole** [comment]
@agray Well, in this case "myriad components" - as far as I can tell - means two software products: the NUnit framework and the console runner.

The framework is what you are referencing in your tests. Only you know what version that is. Whatever version you built the tests with, that's the one that has to be available to your tests at runtime. If you built the tests with the 3.5 framework, make sure it's still available. It may not be if you installded it using the old msi, which is now uninstallled. Alternatively, recompile with the 3.6 framework and make sure that one is available to your assembly at run time.

In addition to the framework, you need exactly one runner. It sounds as if you are using the console runner. Install the runner in whatever way you like: msi, nuget package, zip file. Run the runner, pointing it at your test assembly.

The internal trace logs are saved in the work directory. That is, the same directory in which your test result is saved if you don't specify a different path.

**Comment by rprouse** [comment]
I noticed recently that if I have the console installed and in my path, but
then try to run another copy, say from nuget, the runner appears to hang.
Eventually the communication channel with the agent times out. It looks to
me like the agent fails to start or crashes, but I haven't had time to
investigate.

On Feb 6, 2017 7:55 PM, "CharliePoole" <notifications@github.com> wrote:

@agray <https://github.com/agray> Well, in this case "myriad components" -
as far as I can tell - means two software products: the NUnit framework and
the console runner.

The framework is what you are referencing in your tests. Only you know what
version that is. Whatever version you built the tests with, that's the one
that has to be available to your tests at runtime. If you built the tests
with the 3.5 framework, make sure it's still available. It may not be if
you installded it using the old msi, which is now uninstallled.
Alternatively, recompile with the 3.6 framework and make sure that one is
available to your assembly at run time.

In addition to the framework, you need exactly one runner. It sounds as if
you are using the console runner. Install the runner in whatever way you
like: msi, nuget package, zip file. Run the runner, pointing it at your
test assembly.

The internal trace logs are saved in the work directory. That is, the same
directory in which your test result is saved if you don't specify a
different path.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nunit/nunit/issues/2006#issuecomment-277864873>, or mute
the thread

**Comment by agray** [comment]
With NUnit 3.5 my tests ran in both Jenkins and from the VS Test Adapter.  The only NUnit related nuget package my solution pulled in was NUnit 3.5 and the V2 results writer extension as can be seen in the dependencies section [here](https://www.nuget.org/packages/saucery3).

I had NUnit 3.5 MSI installed on the machine and I ran the tests in Jenkins using the nunit3-console.exe in C:\Program Files (x86)\NUnit.org\nunit-console.

Currently I have NUnit 3.6 Console MSI installed on the machine and my solution is depending on the following NuGet packages:

    NUnit 3.6 (with extensions)
    NUnit Console 3.6
    NUnit.Engine 3.6

NUnit Console is not and has never been in my Path.  I have always specified the full path in Jenkins to nunit3-console.exe.

The only console output I get is:

    C:\Jenkins\workspace\FullCircle\Saucery\Saucery3NUnit\saucery\NUnit\Version3>"c:\Program Files 
    (x86)\NUnit.org\nunit-console\nunit3-console.exe" UnitTests\bin\Release\UnitTests.dll trace=Verbose
    NUnit Console Runner 3.6.0
    Copyright (C) 2017 Charlie Poole

    Runtime Environment
       OS Version: Microsoft Windows NT 10.0.14393.0
      CLR Version: 4.0.30319.42000

    Test Files
        UnitTests\bin\Release\UnitTests.dll
        trace=Verbose

The only output to file is TestResult.xml containing:

    <?xml version="1.0" encoding="utf-8" standalone="no"?>
      <test-run start-time="2017-02-08 10:13:12Z">
       <command-line><![CDATA["c:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe"  UnitTests\bin\Release\UnitTests.dll trace=Verbose]]></command-line>
     </test-run>

  Other than that it just hangs.

What have I done wrong?  What's the right way it upgrade from 3.5 to 3.6?

Appreciate your help, Saucery is dead in the water (to upgrades) until this can be resolved.

**Comment by ChrisMaddock** [comment]
@agray - From your console output, your `trace=Verbose` is being read as a test file. You need to mark it as an option with `--`

`"c:\Program Files 
(x86)\NUnit.org\nunit-console\nunit3-console.exe" UnitTests\bin\Release\UnitTests.dll --trace=Verbose`

Hopefully that will provide some logs, which may give some clues.

**Comment by agray** [comment]
@ChrisMaddock: Went back to basics and looked at my last working release which pulled in NUnit 3.5 and the V2Writer Extension.  I uninstalled all NUnit nuget packages and the reinstalled NUnit 3.6 package only to replace the NUnit 3.5 package that is there in the released version 3.5.8.

As you suggested Chris I ran the correct command 

    "c:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" UnitTests\bin\Release\UnitTests.dll --trace=Verbose

from a administrator cmd prompt from the same directory that Jenkins would run from and got three files output: 

    InternalTrace.2932.UnitTests.dll.log
    InternalTrace.4696.log
    nunit-agent_2932.log

these files are attached (changed extension to txt so github would attach them
[InternalTrace.2932.UnitTests.dll.log.txt](https://github.com/nunit/nunit/files/760468/InternalTrace.2932.UnitTests.dll.log.txt)
[InternalTrace.4696.log.txt](https://github.com/nunit/nunit/files/760470/InternalTrace.4696.log.txt)
[nunit-agent_2932.log.txt](https://github.com/nunit/nunit/files/760469/nunit-agent_2932.log.txt)


).

Please advise.

**Comment by ChrisMaddock** [comment]
@agray - Take a look at `InternalTrace.2932.UnitTests.dll.log.txt`. You can see it starts running tests, and then gets stuck on `FlowControlTest`. Maybe rerun those logs a couple of times, to check it's consistently that tests it stops on - and not just a coincidence. If so - can you share what's going on in that test?

Aware you've said the tests themselves haven't changed recently - but both the console and framework have had a number of changes - and it's definitely possible some of your tests could be exposing a bug in either console or framework that nobody else has encountered yet.

**Comment by agray** [comment]
Thanks @ChrisMaddock, leave it with me, I'll get my stuff together and report back

**Comment by agray** [comment]
Ok....So I have managed to get both the UnitTests and SauceLabs Tests to execute and pass.

What I need to do now is find out how to change to use the JUnit plugin to publish the nunit3 XML results.

Any help you could offer with this last step?

**Comment by agray** [comment]
This is sorted. Used the nunit3-junit transform. Thanks Paul.  works well.

**Comment by Arya-Sri** [comment]
hi agray, 
I was using selenium 2.53 and NUnit 3.5 and used Jenkins to run tests using the same kind of console command to execute tests in GRID environment, which was work from last 2.5 years. Now I have tried to upgrade to Selenium 3.13 and NUnit 3.8 console (Installed in my Hub machine) and 10.0.3 Framework in my tests, the tests were running executing and stopped at some point but the Jenkins hangs. Could you please help me what have you done to solve your issue? thanks in advance.
