### ISSUE TITLE
TestCase and Values do not correctly convert DateTime string in current culture

### ISSUE THREAD

**Issue by morgen2009** [nunit/nunit#2008]
Converting `string` into `DateTime` the `TestCase`, `Values` attributes use invariant culture `System.Globalization.CultureInfo.InvariantCulture`. I expect that when I change the `TestExecutionContext.CurrentCulture` using `SetCultureAttribute` for test / test fixture, the converter should use the new culture info. What do you think about?

The following tests fail

```c#
[TestCase("12.10.1942")]
[SetCulture("de-DE")]
public void CanConvertStringToDateTimeInCurrentCulture(DateTime dt)
{
     Assert.AreEqual(new DateTime(1942, 10, 12), dt);
}

[Test]
[SetCulture("de-DE")]
public void CanConvertStringToDateTimeInCurrentCulture([Values("12.10.1942")] DateTime dt)
{
     Assert.AreEqual(new DateTime(1942, 10, 12), dt);
}
```

**Comment by pgrawehr** [comment]
It seems to dependent on the user settings, especially if the user has overridden some locale settings. 
Adding 
CultureInfo.CurrentCulture = new CultureInfo("de-DE", **false**)
at the beginning of a test has solved many similar issues for me. 
-> The fix is probably to have NUnit use this constructor for CultureInfo when applying a SetCulture attribute.

**Comment by CharliePoole** [comment]
The problem here is that NUnit uses various attributes at different points in the life cycle of the test.

In your case, the TestCase, Test and Values attributes are used to create the test. At a later stage - in the case of a gui, it could be much later - the test is executed. At that point, the SetCulture attribute sets the current culture of the execution thread.

By using a string argument but making the test parameter a DateTime, you're forcing the conversion to take place at the earliest stage, when the test is created. If you used a string parameter and converted it in your test, it would work as you expect.

Alternatively, you could use a TestCaseSource attribute on a method that yields DateTimes constructed in any way you like.

**Comment by morgen2009** [comment]
Thank everyone for quick response. `TestCaseSource` "just" for converting seems for me a bit overhead, I would prefer to have test parameter values closer to the test method header. As well repeating the same code in each constructor. Now my code looks like ...

```c#
[TestCase("01.02.2013")]
public void TestFeature(string dateString) {
  var date = DateTime.Parse(dateString);
}
```

I saw again the `TestCaseAttribute `and `ValuesAttribute` classes. Why to not use `System.Globalization.CultureInfo.CurrentCulture` instead of `System.Globalization.CultureInfo.InvariantCulture`?

**Comment by CharliePoole** [comment]
Ok... so having given some workarounds, which I agree are not ideal, are there options to "fix" this or is it something we don't want to fix. @nunit/core-team @nunit/framework-team please chime in with your thoughts.

TestCase attribute and ValuesAttribute do a special conversion from string to DateTime when needed, because it's not possible to specify a DateTime value to an attribute. Currently, this uses the Invariant culture. We could use the current culture as @morgen2009 suggests. However, as I already explained, at the time we are doing the conversion, the culture has not yet been changed to match the SetCulture attribute. We could also change it to use the system culture, but that would not help either, since the culture you are trying to use may not be the system culture.

To fully "fix" this, the TestCase and Values attributes would have to be aware of the test property that SetCulture attribute. They would have to anticipate that what the SetCulture attribute means and what it is going to do at the time the test is run. This seems like a rather ugly solution!

Another possibility, which might be better from a backward compatibility point of view is that we give the TestCase and Values attributes optional Culture properties that will be used when converting from a string. So you could then use...

```C#
[TestCase("12.10.1942", Culture="de-DE")]
```

Hmmm... that may be the solution. In the case of this example, the SetCulture attribute would no longer be needed. In some other cases, however, it might be.

@morgen2009 Are you sure your tests fail? That's a bit surprising as I would expect them to be invalid due to a failure to convert from string to DateTime. It makes a significant difference to how this might be remedied.

**Comment by CharliePoole** [comment]
Another idea: define an interface which, if implemented, causes a method of the attribute to be called __at the time the test is being loaded__. That would be a general solution for many cases and is consistent with the framework architecture.

Currently, for example, SetCulture implements two interfaces. The `IApplyToTest` interface is used to set a property on the test, which indicates the culture used for reporting purposes. The IApplyToContext interface is used to set the culture of the thread being used to run the test when execution starts. A third interface (IApplyToDiscovery?) could be used to set the culture when the test is being loaded. [In this example, it would do the same thing that it does at execution time, but that might not be the case for every attribute.]

What do folks think of this?

**Comment by jnm2** [comment]
I don't like `[TestCase("12.10.1942", Culture="de-DE")]` because it's pure noise for multiple test cases.

Which is better during test creation- actually setting the thread's culture, or using `DateTime.Parse` and passing in the correct `CultureInfo`? I prefer the latter.

I like the architecture where `SetCultureAttribute` sets a `CultureInfo` property on the test before the stage where `TestCase` parses the string to DateTime.

**Comment by jnm2** [comment]
Since we can't actually instantiate the test until `BuildFrom` is finished, it would be cool if `BuildFrom` was passed some common currency such as `IMethodTestSettings` in addition to `IMethodInfo`. `SetCultureAttribute` could set `IMethodTestSettings.CultureInfo` and `TestCaseAttribute.BuildFrom` could read it when converting strings to dates.

**Comment by morgen2009** [comment]
@CharliePoole It fails on assertion, because I expect the string date in `DD.MM.YYYY` format and converter interpretes it as `MM.DD.YYYY`

**Comment by jnm2** [comment]
> It fails on assertion, because I expect the string date in DD.MM.YYYY format and converter interpretes it as MM.DD.YYYY

I refuse to specify date formats at all unless I can put the year first, then the month, then the day. Whether typed or or handwritten. But that's a different story.

**Comment by CharliePoole** [comment]
@morgen2009 Two questions:

1. Your example can easily be fixed if you merely change the data to what NUnit expects in the first place. But of course, it's just an example you created to illustrate the problem. Are there other cases where that's not a valid solution? Or is it just a matter of being able to use the format you are familiar with?

2. As an immediate fix, how do you fell about specifying the culture on each test case? That's something we could do rather quickly even if it isn't the full answer.

**Comment by ChrisMaddock** [comment]
`IApplyToDiscovery` is the nicest idea suggested so far imo. I'd also prefer to avoid doing anything based on current culture - we've been bit before by different cultures on different machines - sounds like we allowed this inside the test building logic, it could take a bit of untangling.

I haven't investigated much at all - but I can see the method which converts the TestCaseAttribute parameters is also passed the parent suite Test. If we made SetCultureAttribute implement `IApplyToTest` instead of `IApplyToContext` - would it be possible to ensure the attribute is evaluated in time, for the culture to be set on the parent, and then retrieved as the child tests are being built? What breaks if the culture is initially stored on the test, before being copied over to the execution context?

**Comment by jnm2** [comment]
> but I can see the method which converts the TestCaseAttribute parameters is also passed the parent suite Test.

I ran into this in a previous PR. The parent suite test is the grandparent of the test cases and the shared parent of each method, so for TestCaseAttribute it's always the entire fixture. Setting the culture for that would not be thread-safe. That's why I was envisioning an `IMethodTestSettings` because at the point where `BuildFrom` is called, the method-level test instance has not been instantiated yet.

**Comment by ChrisMaddock** [comment]
Thought there must be something else too it - that's irritating! Thanks. 😄

**Comment by CharliePoole** [comment]
There's no threading issue here, since this is not run at execution time. The discovery/loading/construction of tests always takes place on the same thread. We can't use various threads because until the test is constructed, we don't know how it is supposed to be run.

Also, the hierarchy is not helpful here, since all tests are constructed before any tests are run.

**Comment by ChrisMaddock** [comment]
@jnm2 - just looking at that section of the TestBuilder you linked to - I wonder if the child tests need to be created before the ParameterizedMethodSuite, or if that could be created first, and passed down to BuildFrom so the culture information is available. I haven't looked at any other ITestBuilders to see if it would affect anything else.

> Also, the hierarchy is not helpful here, since all tests are constructed before any tests are run.
Was this related to my point Charlie? I'm not sure what you mean.

**Comment by morgen2009** [comment]
1. No, for me this is just one use case "date/time in familar format". For other types supported by `Convert` class there are no problems with different cultures
2. Personally I will not resist to specify `Culture` for each `TestFixture `or for `TestCase`. But I would prefer, that convertion takes something like Culture from `TestFixture` (what you discused before), then  `Assembly.CultureInfo`, then `InvariantCulture` if previous ones are not specified.

**Comment by CharliePoole** [comment]
@ChrisMaddock @jnm2 While "How could we implement this" is interesting, I'm still at "Should we?"

What will it break for users?

**Comment by ChrisMaddock** [comment]
> While "How could we implement this" is interesting, I'm still at "Should we?"

Sorry - I noticed I hadn't answered that question, but thought the conversation had moved on further. 😄 

Yes - I think is should be fixed for @morgen2009's case when the culture is explicitly set. Otherwise, it should continue to use Invariant culture.

As above, I'm less of a fan of using current culture for anything - now you mention it, backwards compatibility is another good reason not to do that.

If we do change - then it may cause issues for anyone who's previously encountered this problem and just worked around it - but my thoughts are that 'fixing' this would be a 'less-surprising' approach.

**Comment by CharliePoole** [comment]
Here's a more detailled breakdown of what happens at test load time...

1. The test builder interface is called to create the test. This is when the arguments are accessed, so this is when the DateTime would be parsed.
2. The IApplyToTest interface is used __after__ the test is created, setting a test property to the desired culture.

This order has never mattered before, because the property is not used for anything except being reported in the test result.

This sequence is followed at every level: assembly, class and method. So the set culture should appear as a property of the parameterized method suite. However, as has been mentioned, the method suite is not built until after all the tests are built. If we could build it first, then the property would be accessible at the point where we are building the tests.

**Comment by CharliePoole** [comment]
I'm also inclined to think that backward compatibility is not a big problem in this case. It would only apply if somebody used SetCulture on a parameterized method and actually expected the set culture to be ignored at load time and not used till run time. I can't imagine anyone would expect that, although they may have discovered it works that way and compensated for it. So, not a big issue IMO.

@ChrisMaddock I was asking the question because it seems to me we should have some standard approach when we are about to make a change that could impact some people. Maybe a notice on the nunit-discuss list with a specified time to respond? I know I've been wrong in the past when I thought some change would not have an impact on many people. 😞

**Comment by oznetmaster** [comment]
I think that this implicitly re-raises the issue (which I cannot find) of a command line option to set the culture for all the tests currently being run, so that the same test suite can be run for multiple cultures without modifying the test suite.

**Comment by oznetmaster** [comment]
This would allow CurrentCulture to be used for all test where culture mattered, and CurrentCulture would be the culture set on the command line. 

Alternatively, if the command line option were specified, then that culture would be automatically used instead of the InvariantCulture wherever appropriate.

**Comment by CharliePoole** [comment]
I can't find such an issue - or even remember one. There may have been discussion somewhere, without creating an issue. I wouldn't be against it as a console feature for those who need it. It's basically equivalent to setting the culture at the assembly level, which is already supported. 

That wouldn't eliminate this issue, of course, which applies to situations where the user wants to set the culture on an individual test case.

**Comment by rprouse** [comment]
I don't understand the point of this? What is wrong with NUnit using invariant culture to parse the `TestCase`? Asking that the developer use invariant culture does not change the tests in any way and also ensures that tests run the same way on all machines. Personally, adding this ability adds unneeded complexity to our code and will end up confusing as many people as it satisfies.

As far as I am concerned, the culture that is set on the test should only change the behaviour of the test code itself. As far as I am concerned, the attributes that feed the test are NUnit code and should be invariant.

**Comment by ChrisMaddock** [comment]
> and also ensures that tests run the same way on all machines.

Definitely not suggesting we change that! I'd suggest the culture used is either invariant _or_ explicitly set by the user - I don't think it's a good idea to bring CurrentCulture into this at all. 

> As far as I am concerned, the attributes that feed the test are NUnit code and should be invariant.

Is this not something of an implementation detail? I can understand the confusion of defining a test to be `de-DE`, and then finding part of that test actually uses Invariant culture. Especially as NUnit is already implicitly converting the string to a DateTime - ignoring NUnit's own culture definition here seems inconsistent.

**Comment by CharliePoole** [comment]
Well, I can see both sides.

Requiring invariant for the data arguments is clear and consistent.

Letting a SetCulture change which culture is used for data arguments also
has a certain logic, since the cases and the SetCulture attribute are so
close together in the source. I wouldn't do it, however, if it required a
lot of work to make the change - it's just not worth it.

I'm good with either decision.

Charlie

**Comment by morgen2009** [comment]
@ChrisMaddock 
>  I'd suggest the culture used is either invariant or explicitly set by the user
This would be great, if would be possible (for example by giving assembly culture)
>   ... ignoring NUnit's own culture definition here seems inconsistent
For me the unit tests are a contract specification. They are read by humans and humans prefer their local language :) Any way, the solution should be clear and consistent

**Comment by jnm2** [comment]
I'm also in favor of parsing them invariantly unless there is a `SetCulture` attribute and then using the given culture.

**Comment by CharliePoole** [comment]
@jnm2 That would mean very big changes unless we added explicit knowledge of those attributes at load-time. How it now works...

1. The test cases are created.
2. Any attributes that modify the test case run. In this case, setting a property in the test.

Since the cases are created by many different attributes, each one of them would need to be aware of the presence of a SetCultureAttribute and act on it.

One simple way to deal with this at a user level is to pass a string argument and convert to a culture-dependent value within the test itself.

**Comment by jnm2** [comment]
It would mean big changes which I'd be in favor of. I've been noticing us hitting a ceiling with various aspects of the current system in recent issues and ever since one of my first PRs. Perhaps what we should do is collect all such issues and review their disparate needs when we plan the v4 API in the distant future.

**Comment by jnm2** [comment]
Again, I saw your, Chris' and my support for the idea. Perhaps I moved it to backlog too soon.

**Comment by CharliePoole** [comment]
@jnm2 I'm not sure what you saw me supporting. As I read the thread, Rob and I came out against the idea, you and Chris for it. That's not consensus.

Another problem we have in these long-running threads is that we talk about multiple proposals that change over time. It's very hard to figure out who is where on an issue in that case, so I can understand how anyone could get confused.

**Comment by CharliePoole** [comment]
@jnm2 I'd like to hear more about your feeling of hitting a ceiling. IMO we have a lot of power in the existing design along with a few flaws I would love to fix in some future major release. I spend almost no time thinking about those flaws most of the time because there is too much to do. We have 200+ outstanding issues, many quite important. My guess is that we might find a dozen or so that are blocked by the basic design within which we are working. But that leaves a lot of work we can accomplish.

To be sure, completing so many issues would mean thinking in terms of how NUnit __now__ works and fitting our changes into that framework. If we focus on how we wish we had done it, there will be a great many more that are "impossible" to do. My comments often tend toward pointing out how NUnit works right now, not because I think it's perfect, but only because it is what it is.

When the time comes to think about the next release, I want to be 100% focused on that.

**Comment by jnm2** [comment]
@CharliePoole Gotcha. You said you could see the logic of either side and you would do it if it wasn't a lot of work. However, this reminds me of a [very similar thread](https://github.com/nunit/nunit/issues/2280#issuecomment-311450408) in which we trade places.

**Comment by CharliePoole** [comment]
@jnm2 I wrote that immediately after the line that states my preference for the opposite. I __can__ see the logic of your view. That doesn't put me in agreement with you. I expect you, as my teammate, to make sure you see the logic of my view too.

**Comment by rprouse** [comment]
I would vote to close this. Users passing in strings and us converting them to dates is a convenience that NUnit provides because the values in test case attributes must be const. In the example code above, all the user is effectively testing is how NUnit converts dates. We should support invariant culture for date strings and nothing else. This allows tests to run on any machine no matter the culture.

If users really want to convert strings to dates using a culture, they can do it themselves in a `TestCaseSource`.

**Comment by jnm2** [comment]
'Invariant-or-follow-SetCulture' as well as 'invariant-only' allows the tests to run on any machine no matter the culture settings of the machine.

But the more I think about it, the less obvious the decision between the two seems. :+1:
