### ISSUE TITLE
Assert.That(length, Is.PowerOfTwo)

### ISSUE THREAD

**Issue by NUnitTester** [nunit/nunit#2013]
In some cases it is important that an input or an output has a power of 2.
Not many developers know how to check this easily.
I wish that integrated and readable in NUnit, something like
`Assert.That(length, Is.PowerOfTwo)`
Needed for all integer types, also int, long and decimal because Length/Count of CollectionTypes is int.

I use the following easy method (for unsigned only, signed needs cast)
`private static bool IsPowerOfTwo(uint x)
{
    return x > 0 && (x & (x - 1)) == 0;
}`

**Comment by jnm2** [comment]
It's fairly common for me to wish I had a specialized constraint to assert that would print a nice message but I settle for `Assert.That(bool)` because I have to use a method like `IsPowerOfTwo`.

If only we had `Assert.That(actual, Satisfies.Contraint(IsPowerOfTwo));` which would output `Expected: IsPowerOfTwo But was: {actual}`.

**Comment by jnm2** [comment]
Actually I think I can implement that without it being in NUnit itself.

**Comment by ChrisMaddock** [comment]
This is the sort of thing I'd personally implement as a custom constraint. We do this for quite a few domain-specific things.

**Comment by CharliePoole** [comment]
I'd say it's too specialized for us to add to NUnit. A great example for a simple custom constraint though.
