### ISSUE TITLE
TestFixtureSourceAttribute doesn't work with items implementing ITestFixtureData

### ISSUE THREAD

**Issue by dajuris** [nunit/nunit#2019]
Consider the following test:

```
namespace MyTestProject
{
    [TestFixtureSource(typeof(SourceProvider), "FixtureArgs")]
    public class MyTestClass
    {
        public MyTestClass(string word, int num)
        {
        }

        [Test]
        public void Test()
        {
        }
    }

    public class SourceProvider
    {
        static object[] FixtureArgs =
            {
                new MyTestFixtureData("Question", 1),
                new MyTestFixtureData("Answer", 42),
            };
    }

    public class MyTestFixtureData : ITestFixtureData
    {
        ...
    }
}
```

Console runner fails with `System.InvalidCastException`:

```
NUnit Console Runner 3.6.0
Copyright (C) 2017 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.10586.0
  CLR Version: 4.0.30319.42000

Test Files
    MyTestProject.dll


Errors, Failures and Warnings

1) Invalid : MyTestProject.MyTestClass
An exception was thrown while loading the test.
System.InvalidCastException: Unable to cast object of type 'MyTestProject.MyTestFixtureData' to type 'NUnit.Framework.Internal.TestFixtureParameters'.
   at NUnit.Framework.TestFixtureSourceAttribute.<BuildFrom>d__17.MoveNext()
   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(ITypeInfo typeInfo)
```

According to [documentation](https://github.com/nunit/docs/wiki/TestFixtureSource-Attribute) for `TestFixtureSourceAttribute` this should be supported scenario.

I have used NUnit and NUnit.Console 3.6.0.

**Comment by rprouse** [comment]
Yes, that is what the documentation says. It looks like we let a cast to the concrete type rather than the interface slip through a code review.

In `TestFixuteSourceAttribute.BuildFrom()`

```C#
            foreach (TestFixtureParameters parms in GetParametersFor(sourceType))
                yield return _builder.BuildFrom(typeInfo, parms);
```

**Comment by CharliePoole** [comment]
I marked this for discussion temporarily, as I think it could be a documentation error.

Over the past few releases - I haven't searched to  see exactly when - I modified TestCaseSourceAttribute to require the use of TestCaseParameters type, rather than just an interface. When I added TestFixtureSourceAttribute, I set it up the same way.

The docs were never updated for TestCaseSourceAttribute and simply got copied and edited for TestFixtureSourceAttribute.

We can go either way, but I think we should do the same thing in both cases. Either

1. Accept the interface. If we do that, let's be sure to tell people about the existence of the user-oriented types that are designed to implement it: TestFixtureData and TestCaseData.

2. Require an object of the type we provide. This would be either TestFixtureData or TestCaseData. In that case, this would be purely a documentation bug.

IIRC, the second approach simplified the internal processing enormously. Internally, we create an object of type TestFixtureParameters/TestCaseParameters from whatever the user provides. These are the base classes of TestFixtureData/TestCaseData so we can use those easily. For an arbitrary implementation of the interfaces, we need to create the parameters classes specially from the interface.

I don't see that requiring or allowing the user to implement an interface is of any benefit here. Any extra features they add to their class will not be known to or used by NUnit. The interface is actually a hold-over from NUnit V2, by the way.

OTOH, there's no harm of allowing the interface __if it really only requires a simple fix__. Somebody could dig in and find out.

**Comment by GCichosz** [comment]
I did a little digging. `TestFixtureSourceAttribute` case is a simple fix, because the underlying `NUnuitTestFixtureBuilder.BuildFrom()` method already operates on `ITestFixtureData` interface. `TestCaseSourceAttribute` case is not a simple fix, because it's `BuildFrom()` method as well as the underlying `NUnitTestCaseBuilder.BuildTestMethod()` method use members specific for `TestCaseParameters`, or from other interface it implements. Specifically it's about `IApplyToTest.ApplyToTest()` method and `TestParameters.OriginalAttributes` property in the following code fragment:
```csharp
if (parms != null)
{
    parms.ApplyToTest(testMethod);

    if (parms.TestName != null)
    {
        // The test is simply for efficiency
        testMethod.Name = parms.TestName.Contains("{")
            ? new TestNameGenerator(parms.TestName).GetDisplayName(testMethod, parms.OriginalArguments)
            : parms.TestName;
    }
    else
    {
        testMethod.Name = _nameGenerator.GetDisplayName(testMethod, parms.OriginalArguments);
    }
}
```

**Comment by heshamamin** [comment]
Hi
I'll pick the TestFixtureSourceAttribute issue as it seems simple. I think we should create another issue for TestCaseSourceAttribute.

**Comment by CharliePoole** [comment]
@heshamamin Please hold off working on this. See my long comment above when I moved this from backlog to discussion.

@nunit-core-team 
As I indicated, I'm dubious about fixing this except wrt the docs. Thoughts?

**Comment by ChrisMaddock** [comment]
@heshamamin and @dajuris - do either of you have a use-case which can't be implemented with TestFixtureData instead of the interface? 

I haven't looked at the code here - happy to defer to your judgement as to the simplicity benefits @CharliePoole . This would potentially being a substantial breaking change for some users...although if it's been broken since 3.5, perhaps it's not that well used. (I never have!) Although I am a little wary of making a breaking change purely for internal code simplicity.

**Comment by CharliePoole** [comment]
@ChrisMaddock it can't be a breaking change for fixture data since it has never worked AFAIK.

**Comment by ChrisMaddock** [comment]
Oh, sorry! I took from @rprouse's comment earlier it was just a bug that had slipped through code review.

In that case, yes, just changing the docs seems sensible - we can consider it as a feature request, should that come up.

**Comment by CharliePoole** [comment]
Yes, I was hoping @rprouse would respond to my initial comment as it contradicts his.

Just so you know , here's the history...

1. Nunit 2 used the interface ITestCaseData, accessing it by reflection of course.

2. With NUnit 3, the test execution code moved into the framework and much of our reflection code became unnecessary. I decided to require use of the class as a basis for test case data. Users can, of course, extend it if they choose. This has occasioned no complaints but the docs were left out of sync.

3. When I implemented TestFixtureSource, I used the same approach. However, the docs are just an edited copy of those for test cases and contain the same error.

So, I'm basically asking for review of that chain of decisions before we proceed.

**Comment by rprouse** [comment]
I am fine with just fixing the documentation.

**Comment by CharliePoole** [comment]
Added back to the backlog and made it a docs bug. I assigned it to myself, since I caused it in the first place.

**Comment by BrunoJuchli** [comment]
I'd like to use `[TestFixtureSource]` to provide fixtures with arguments *and* Type arguments.
However, `[TestFixtureSource]` only supports `TestFixtureData : TestFixtureParameters`. Now while there is a `TestFixtureData.TypeArgument` property it's setter is `internal`.

As far as I understand, this is one of the use cases "broken" by missing support for `ITestFixtureData`.
Now, it's not necessary to re-introduce support for `ITestFixtureData` just to support type arguments.
Instead one could do any of:

- make `TestFixtureData.TypeArgument` setter public. Makes the type externally mutable, though (why isn't the property currently read-only?)
- introduce a new ctor on `[TestFixtureSource`]: `public ctor(Type[] typeArguments, object[] arguments)`
--> this is a breaking change for all usages of `ctor(params object[] args)` where it was used like `new (Type[], object[])`. Don't think it was used very often like this, though...
--> the breaking change could be circumvented by creating a new type which itself holds on to the type arguments and the other arguments. That would be a bit ugly, though
- support `CustomAttribute : NUnitAttribute, IFixtureBuilder` which could be used instead of `TextFixtureSource` (I'm actually not certain if that's already the case).
    
What do you think?
I'd be happy to create a PR.

**Comment by CharliePoole** [comment]
@BrunoJuchli Although motivated by this closed issue, what you are suggesting seems to be an entirely new change, worthy of its own issue. 😸 That would at least give us a place to discuss it without confusion.

On one point ... "As far as I understand, this is a use cases "broken" by missing support for ITestFixtureData." ... that's a mis-statement. TestFixtureData is a class that is used to package instructions for NUnit about how to instantiate your fixtures. It's not intended to be passed into the fixture constructor or used to call your own methods. This issue was closed because the OP had a misunderstanding about the intent of the class.

I have some thoughts on the approaches you are suggesting, but I'd rather not put them here where they will end up being lost in future discussions. It's important that people can find the reasoning behind why we make a change.

That's not to say that your issue isn't valid. From the description,  I see that you want some capabilities that we don't support, so let's have an issue that describes your needs and alternate solutions rather than branching off a documentation issue that's based on a misunderstanding!

**Comment by BrunoJuchli** [comment]
@CharliePoole 
Thanks for taking the time. I've created a new issue: https://github.com/nunit/nunit/issues/2958
