### ISSUE TITLE
Nameof refactor

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2033]
In the [C# version conversation](https://groups.google.com/forum/#!topic/nunit-developer/m00Oeo9bSqA), I asked if we'd be interested in doing a total `nameof` refactor now that the keyword is available. The core reason is well stated by @ChrisMaddock:

>  I'd personally be a fan of doing it globally for nameof(), if nothing else. nameof adds compile time checking where there currently is none, which would be great of all the reflection code within the framework. It would be some nice extra security for future refactors.
>
> When we first moved to VS 2015, nameof was the only thing we 'bulk converted', and it caught a couple of bugs in rotten-code. I'm sure NUnit is better maintained, but I feel it could be justified as a 'code enhancement' rather than just a syntactic nicety.

Besides the security, I've also noticed it makes navigation to the related member *so much easier*. Whether it's a TestCaseSource or it's an NUnit test which references a method in a helper test fixture, a single F12 press jumps you right where to want to be. I guess CodeLens would also pick up on it and provide navigation in the opposite direction.

As noted, the refactor itself is not difficult, especially with ReSharper. It would involve a single click to take care of attributes such as `TestCaseSource`. However, we'd need to manually check all call sites of `TestAssert.IsRunnable` and Properties keys and similar methods. I volunteer because this is something I really want to see happen. Of course extra eyes on the same hunt couldn't hurt. Maybe I can twist the arm of @ChrisMaddock's inner perfectionist. :smile:

**Comment by jnm2** [comment]
However, we'd need to manually check all call sites of `TestAssert.IsRunnable` and similar methods. I volunteer because this is something I really want to see happen, and of course extra eyes on the same hunt couldn't hurt.

**Comment by CharliePoole** [comment]
Reposting steps I suggested in the discussion on the mail list...

0. Decide if we even need such a standard or if we will view it as a
matter of individual style.
1. If yes, try to devise a standard that tells people when to use nameof.
2. Get it approved by either a project team or the core team. This has
to wait a little till we are organized, but I hope not long.
3. Examine the standard to see if it's even capable of being automated.
4. Decide project by project whether to do a mass (possibly automated)
approach or to leave it to the brains of the developers.

I marked this for discussion. Please, no PRs till we make it a backlog item.

If we were to merely allow Resharper to decide what to change, I believe we would be adopting by default a standard that says "Developers are required to use nameof whenever it is possible." That isn't a standard statement I would agree with and I suspect most of us wouldn't either.

As I indicated there, I think deciding what should be standardized and by whom is a very important activity for a team. Trying to put the standard into words is a valuable exercise on its own. There's no reason to think it will take a long time. And it answers the obvious question "What happens after the mass conversion?"

As for item 0, I personally think this is important enough to be a standard. That is, I don't think it's 100% a matter of individual style, as many other things are. I believe devs should have some guideline that tells them when to use nameof rather than a hard-coded string. Somebody ought to try to write that, IMO. That would potentially take care of items 1 and 2 as well.

My guess is that the standard we adopt will not be capable of being completely automated. However, that still leaves open the possibility of a mass change followed by the use of judgement in reviewing the results.

**Comment by CharliePoole** [comment]
By the way, we are talking about the framework project here, so it makes sense that the folks working on the framework project express opinions. Whether there will be some __global__ standards that all projects __must__ follow is another matter. It has to be addressed by the Core Team, but that's not yet possible, because we are still working on the governance model for the overall organization. 

This isn't to say we can't deal with this at all, just that there is a part that will come later - a few weeks perhaps.

**Comment by jnm2** [comment]
I think nameof fits the bill as one of the extremely few things worth setting as a standard.

Pros:
 * You get autocomplete and typo correction (less work)
 * You get refactoring guarantees (less work + safety, it's easy to miss things, unit tests don't catch everything)
 * You get to follow the promptings of the IDE which almost everyone uses (less work)
 * You get F12 navigation and CodeLens (less work)
 * Intent can be *much* clearer in my experience (readability)

All these benefit not just me as my individual style. If this is the status quo, anyone who comes along needing to debug or edit code will find them very convenient.

Cons:
 * It's either a hard or soft convention to follow (more work)
 * ?

You have a convention around var but allow me some room to use my judgment.
Nameof could have the same philosophy: it's encouraged because of the convenience and safety, but if I really think that a string literal is more aesthetically desirable (say, in DebuggerDisplayAttribute), I can make the tradeoff and opt out of the convenience and safety.

**Comment by jnm2** [comment]
My guess is we'll find that nameof is very popular and we won't have to encourage new contributers to use it.

**Comment by CharliePoole** [comment]
@jnm2 Do you want to propose some language?

**Comment by CharliePoole** [comment]
@jnm2 I don't understand your third point about the promptings of the IDE.

**Comment by jnm2** [comment]
I can try proposing some language. Let me read https://github.com/nunit/docs/wiki/Coding-Standards thoroughly.
I clarified my third point in-place.

**Comment by jnm2** [comment]
Re:

> For example, we don't need a standard that tells us to always dispose of disposable objects because that's part of the normal "standard" for C# programming.

An argument could be made 😆 that using `nameof` is part of the normal standard for C# 6 programming, just like using `await` rather than `.ContinueWith` with callbacks (C# 4) is part of the normal standard for C# 5 programming. But I should read the C# 6 spec before I make that argument seriously.

**Comment by CharliePoole** [comment]
@jnm2 A different way to put it is that coding standards are about style. They are the aspects of style that we decide to standardize in order to foster better communication. Curly braces are a great example. You and I can differ in our preferences, but one of us agrees to give in because how braces are laid out makes an enormous impact when reading a program. Neither of us (if we differed) would own the "right" style or "best" style, But we would have an "agreed" style. But other matters of style are not worth standardizing although your internal style police may try to do so. IOW, I think the coding standard is about matters that are sufficiently trivial that we can easily give in to one another.

OTOH, disposing of objects is simply required by good programming. It's not a matter of style at all. We don't put that in the standard because it's not the job of the standard to teach you how to program.

BTW, this attitude toward the coding standard is typical XP. If you don't like XP, you won't like my definition. :smile:

**Comment by jnm2** [comment]
I do agree with everything you said. I'm just seeing the possibility that `nameof` is not even in that category- less of a style and more of a Dispose-like programming _practice_, or more analogously, more of an `await`-like programming practice.
You wouldn't say writing `try-finally Dispose` instead of `using` was personal style, even though the end result is identical. We've always had `using` though- we haven't always had `await` or `nameof`. As soon as `await` became available, it was better to use `await` than `.ContinueWith` with callbacks even though the end result is identical. In my mind, there's a possibility that as soon as `nameof` became available, it was better to use `nameof` than string literals even though the end result is identical.

Oops, I made the argument. 🙄 I'm not sure how relevant this argument is to our purpose. It's a perspective I guess.

**Comment by jnm2** [comment]
Draft of language:

----

### Use of the `nameof` keyword

The `nameof` keyword should generally be used wherever possible, with some freedom of personal judgment (see below). Usage of the `nameof` keyword allows everyone debugging or editing the code to use quick F12 navigation and CodeLens and Find All References. It provides guarantees when editing and refactoring- there are things which both people and unit tests miss which the compiler can catch via `nameof`. In a few cases, it even communicates intent to future editors where a string literal could be been ambiguous.

In principle, `nameof` trades [connascence of value](http://connascence.io/value.html) for the more weaker (thus more preferable) [connascence of name](http://connascence.io/name.html).

The most important places:

 * [`TestCaseSource`](https://github.com/nunit/docs/wiki/TestCaseSource-Attribute) and similar attributes which name a member
 * [`Has.Property`](https://github.com/nunit/docs/wiki/PropertyConstraint) and similar constraints which name a property or other member
 * `TestAssert` and `TestBuilder` methods which name a test method
 * Any time reflection is used on public members
 * Any identifier names in public-facing end user messages, such as exception messages or test skip reasons. This is a form of public-facing documentation and we don't want to tell people they're misusing enum members or methods that don't even exist.
   (As a corollary, use `<see cref=""/>` and `<paramref name=""/>` in XML documentation for the exact same reasons)
 * **Any place where the [connascence locality](http://connascence.io/locality.html) is low**- The further apart the two ends of the coupling are in the codebase, the more important it is to use `nameof`.

Less important places, where you are more free to decide whether or not to trade off the navigation and safety benefits of `nameof` for aesthetics:

 * Names of parameters in small methods, where there is no ambiguity
 * [`DebuggerDisplay`](https://blogs.msdn.microsoft.com/jaredpar/2011/03/18/debuggerdisplay-attribute-best-practices/) member references- ReSharper will suggest this, but if you don't find the attribute-constant string composition easy to read, that's an example of when you might opt to value aesthetics over the navigation and safety. For this attribute the risk is typically low to none. You're never going to rename `ToString`, for example.
 * **Any place where the [connascence locality](http://connascence.io/locality.html) is high**- The closer together the two ends of the coupling are in the codebase, the less risky it is to use an unverified string literal rather than `nameof`.

----

**Comment by JustinRChou** [comment]
So basically, part of the refactor would involve changing something like
```
    [TestCaseSource(typeof(AnotherClass), nameof(DivideCases)]
    public void DivideTest(int n, int d, int q)
    {
        Assert.AreEqual( q, n / d );
        Assert.That(someObject, Has.Property(nameof(someObject.Version)).EqualTo("2.0"));
    }
```
Don't quite get 

> Identifier names in public-facing end user messages ... we don't want to tell people they're misusing enum members or methods that don't even exist.

**Comment by jnm2** [comment]
@JustinRChou

> Don't quite get 
>
>> Identifier names in public-facing end user messages ... we don't want to tell people they're misusing enum members or methods that don't even exist.

For example, in a recent PR @CharliePoole was about to leave a test skip reason which would show up in the UI, "A test cannot be both Parallel and NonParallel ", but those were no longer enum members. If end users search the documentation for them, they will end up lost. Things like that (if we don't catch them) can waste people's time. They are a form of documentation. Preferable would be:

```c#
$"A test cannot be both {nameof(ParallelScope.Parallel)} and {nameof(ParallelScope.NonParallel)}"
```

because the compiler stops you if you forget to update it.

**Comment by jnm2** [comment]
I'll try to think of a clearer wording. Do you have a suggestion for that?

**Comment by JustinRChou** [comment]
I think I get it now. I think I was being confused by the term public-facing but that is just me.
So you're just forcing an error if anything changes which is being used in a string literal as a message.

I think in that case then it should be a standard.

**Comment by CharliePoole** [comment]
@jnm2 Except that example is purely hypothetical, since the message (which we changed) was not intended to refer to public-facing enums. I don't think we actually have many messages that contain the names of enums - maybe not any.

@JustinRChou In your example, I would use nameof in attribute argument and not in the property value., because...
1. nameof(someproperty.Version) is about three times as long as "Version" and doesn't add to the clarity.
2. It's a test, so the name is made up anyway... nothing to refactor.
3. Our tests need to be made both ways, since some users will use strings and some nameof.
4. There's an issue to fix Has.Property to take a lambda, which would be better all around than nameof.

@jnm2 I'll get back to review your text soon.

**Comment by ChrisMaddock** [comment]
I agree with the general idea that `nameof` should simply be considered good programming practice, rather than a style choice, and therefore not need a standard. But I'm more interested in seeing the change in place, and if we decide a standard is needed to do that - that's fine by me!

> Maybe I can twist the arm of @ChrisMaddock's inner perfectionist. 

Sure! Busy week this week, but happy to help. 😄
