### ISSUE TITLE
NUnitlite-runner crashes if no file is provided

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#2045]
If you run nunitlite-runner without a file argument, it crashes. It should actually check and give an error message, just like nunit3-console.

This is slightly tricky because nunitlite-runner passes the arguments on to nunitlite. NUnitlite is often called without a file argument because the tests are in the failing exe. We need to fix this issue without breaking the behavior when nunitlite is called form a test. Most likely, we need a separate entry point.

**Comment by GCichosz** [comment]
@CharliePoole what do you mean by 

> the behavior when nunitlite is called form a test

? Is it about calling nunitlite through it's `AutoRun` class? If so, the difference is that when calling nunitlite through `AutoRun` an assembly is provided (unless `AutoRun` is constructed intentionally like `Autorun(null)`), and nunitlite can figure out what needs to be tested. In the case of nunitlite-runner no assembly is provided by default, and if none is pointed by arguments it fails, because there is nothing to test. Maybe a simple condition whether nunitlite knows what to test would suffice?

**Comment by CharliePoole** [comment]
Exactly. NUnitlite doesn't know it is being called by the runner so it looks for tests in the runner.

I think the cleanest way to tell it would be to add a special entry point.

When called by the runner, it shouldp

**Comment by GCichosz** [comment]
And by entry point you mean?

**Comment by CharliePoole** [comment]
Currently, nunitlite-runner calls into nunitlite using two different overloads of `TextRunner.Execute()` depending on the platform. Self-executing tests call `Autorun.Execute()`.

So far, so good, except... `Autorun.Execute()` calls `TextRunner.Execute()`, merging the two execution paths.

I was thinking we needed a new entry point for the runner in nunitlite, rather than calling `TestRunner.Execute()` directly. An alternative, however, would be for `AutoRun` to condition the `TextRunner` so that it knows it is not looking for an assembly in the list of arguments.

Are you thinking of taking this on?

**Comment by GCichosz** [comment]
Yes, I already did some investigation, and tried some code. I'll open a pull request to show what solution I was thinking of, and if it's not suitable, I'll try with entry points you mentioned. Can you assign me to this issue? I seem to be unable to do so.

**Comment by CharliePoole** [comment]
@GCichosz I assigned you. Looking forward to the PR.

**Comment by CharliePoole** [comment]
@GCichosz I assigned you. Looking forward to the PR.
