### ISSUE TITLE
NUnit 3.6.0 problem on Xamarin platforms

### ISSUE THREAD

**Issue by gabornemeth** [nunit/nunit#2054]
I experience the following issue in my own [testrunner project](https://github.com/gabornemeth/NUnit.XForms):
Calling `Assert.True(false);` causes NullReferenceException:
`  at NUnit.Framework.Assert.ReportFailure(String message)
   at NUnit.Framework.Assert.ReportFailure(ConstraintResult result, String message, Object[] args)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.True(Boolean condition)
   at Sample.MyTest.Fail()`

I came across it, when added FsUnit test support. FsUnit 3.0.0-beta1 supports .NET Standard 1.6 and this requires NUnit 3.6.0.
Until NUnit 3.5.0 I have experienced no problem.

In a Xamarin Android or iOS project, or even in a UWP project the problem appears with .NET Standard version, I suppose. If I update the NUnit NuGet package from 3.5.0 to 3.6.0 in one of the [samples](https://github.com/gabornemeth/NUnit.XForms/tree/master/Samples), it breaks.
What am I missing?

The easiest way to reproduce the issue is using the UWP sample. Just bump the NUnit package version in project.json from 3.5.0 to 3.6.0 and run the app.  The problem occurs at the test named 'Fail'

**Comment by ChrisMaddock** [comment]
This coincided with my lunch break - so I took a quick look. 😄 

If I'm understanding correctly, you execute the tests by invoking the method name via reflection, and then catching any exceptions?

There was a change in NUnit exception handling behaviour in 3.6 to support multiple assertions - to save repeating the details, take a look here: https://github.com/nunit/nunit/issues/2043. Long story short - I think your runner is relying on some implementation details of NUnit which are not intended to be part of the public interface, and the behaviour change 3.6 has caused this issue. 

As this has had more widespread effects than first thought, there's intended to be a 3.6.1 hotfix released soon, to revert back to original behaviour. I think the long term plan on where to go with this is still a little up in the air - so sharing your use-case/thoughts on #2043 would be welcome, I'm sure! If you're interested in the 'more formal' way to communicate with the framework, you may be interested in taking a look at the [nunit.xamarin runner](https://github.com/nunit/nunit.xamarin), or possibly the [portable agent](https://github.com/nunit/nunit.portable.agent). Both of these are likely to receive some changes over the coming months however, as .NET Standard support is built into the full engine.

Try the NuGet package from this CI build which should have the relevant fix - see if my guesswork falls in to place! https://ci.appveyor.com/project/CharliePoole/nunit/build/3.6.0-ci-03685-issue-2043/artifacts

**Comment by CharliePoole** [comment]
The interfaces used by the xamarin runner and the portable agent should probably be seen as experimental for now. The canonical approach is still the documented API used by the framework driver, unless you need to work with platforms it doesn't support.

To be brutally clear... running tests by merely calling them has not been supported since NUnit 3.0. The latest release merely added another reason to the long list of reasons it doesn't work. The hotfix will fix a problem with a particular common technique used in tests but it won't change the basic fact that you can't expect NUnit to work fully using this approach.

**Comment by gabornemeth** [comment]
Thank you very much for the quick response.
You were right, with the hotfix, it is working the same as before.

I ran through https://github.com/nunit/nunit/issues/2043. In my runner I used reflection - as you observed - to avoid referencing any framework assembly. This way it worked for both NUnit and NUnitLite. I planned it to be a lightweight solution :)
I think I have to revise my solution and dig into the codes you suggested to discover how to correctly communicate with the framework.
Thank you for your help.

**Comment by CharliePoole** [comment]
I'm nunit v2, there were two frameworks, nunit.framework and nunitlite. In NUnit 3, there is only one framework and nunitlite no longer contains framework code.

**Comment by gabornemeth** [comment]
@CharliePoole You mean using the NUnit.Framework.ApiFrameworkController as recommended method? As NUnit 3.6 now supports .NET Standard 1.6, I think it is appropriate for me.

Yeah, I started my runner back then with NUnit v2.

**Comment by CharliePoole** [comment]
The current docs for the Framework API are here: https://github.com/nunit/docs/wiki/Framework-Api-Spec and (in case you want to use it) the Engine API is here: https://github.com/nunit/docs/wiki/Test-Engine-API-Spec

Note the warning at the top of each page!

The framework API can't be used if the runner platform doesn't support the `System.Web.UI.ICallbackEventHandler` interface, which is why some other undocumented methods were added. If necessary for your usage, @rprouse can give more info. Eventually, we'll merge some of those methods into the "official" API.

**Comment by ChrisMaddock** [comment]
I'm going to close this issue as nothing-to-fix, thanks for the feedback @gabornemeth. 😄
