### ISSUE TITLE
Convert .NET Standard Projects to VS2017

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#2073]
VS2017 was released this week along with the updated .NET Core tooling which switches from the project.json format to CSPROJ. We will need to update the .NET Standard projects to the new format soon because I am pretty sure installing the new tooling will make the old tooling inoperable, so any developer who installs .NET Core with VS2017 will no longer be able to build.

Before we make the change, we need to make sure that AppVeyor has VS2017 images available and the core NUnit team has VS2017 installed.

**Comment by CharliePoole** [comment]
Does this imply that folks with only VS2015 will no longer be able to contribute? If so, that sucks! We only just decided to require VS2015 rather than 2012 or 2013.

There are many (generally non-technical) reasons that some developers have to keep working with an older compiler. Often, the decision is out of their control Historically, we have been welcoming to those developers if they wanted to contribute. I hate to see us abandoning that in favor of the view (unfortunately typical in the industry) that requires people to always upgrade to the latest tools.

So let me ask this: __if__ the change is going to be required, how can we mitigate it for folks with older tools? Perhaps a separate solution that only has the desktop platforms?

Also, before we do this, somebody should make sure we can build with the community edition of VS2017.

**Comment by rprouse** [comment]
I just tested on VS2015 and 2017 and we are okay for now. We are using a hybrid CSPROJ/project.json format that works in both versions of Visual Studio. When they stated that the project.json would be automatically updated and no longer supported, I thought that would apply to our approach too. Luckily it doesn't. I am going to close this for now since I don't think we need to do this.

**Comment by CharliePoole** [comment]
Fantastic!
