### ISSUE TITLE
Agents and workers not being respected

### ISSUE THREAD

**Issue by llaskin** [nunit/nunit#2076]
I have a specflow project which I run using the NUnit3 console runner.  I set --workers=5 and --agents=5 in the command line as well, and have the Parallelizable(ParaallelScopeFixtures) value set in my AssemblyInfo file.  However, when I run this, it spins up more then 5 simultaneous threads.

**Comment by CharliePoole** [comment]
First, let's deal with --agents. That setting controls how many different processes are run simultaneously if you are running multiple test assemblies in parallel. It doesn't relate to the number of worker threads used to run tests in each assembly and had no effect if there is only one assembly.

The --workers option controls the number of test worker threads created by nunit. What are you seeing that indicates more are being used?

**Comment by llaskin** [comment]
I am testing Selenium based tests, and seeing mor ethen the number of workers(or agents) spun up at the same time.  I am expecting a max of 5 simultaneous browsers to spin up.

**Comment by CharliePoole** [comment]
First, please decide if it's workers (threads) or agents (processes) that concern you. I'm guessing it's threads but I can't see your code and the resolution would be entirely different for these two different problems.

In either case, we still have to understand your problem. But my next questions will be different depending on which it is.

**Comment by llaskin** [comment]
Most likely threads, not processes.  I tried them each separately and then tried combining them.

**Comment by CharliePoole** [comment]
Well do you have multiple test assemblies you are running simultaneously?

**Comment by CharliePoole** [comment]
How do you start up each browser, I.e. where in your test code? Where do you dispose of it?

**Comment by llaskin** [comment]
1 test assembly, with multiple fixtures(hence the parallelizable scope)
I start the browser up in the [BeforeScenario] section and end the browser in the [AfterScenario]

**Comment by CharliePoole** [comment]
All right... then it's workers. I can give you a guess as to what is happening and it would be great to get some input from the SpecFlow folks to confirm it.

[Unfortunately (for you) none of us actually use SpecFlow. Like most Open Source devs, we believe in "eating our own dog-food" so we stick with using straight NUnit to test NUnit. It would be great to have more interaction with third-party runners that use NUnit, so we might have some understanding of how they work with us and, consequently, what they may need from us. But right now, we're a bit in the dark.]

If a Scenario translates into a single NUnit TestFixture, then everything should work fine. Since it isn't, my guess is that there are multiple fixtures involved.  You should be able to verify my guesses by looking at the C# code that SpecFlow generates for you.

For example, let's suppose that each Scenario generates a set of multiple [TestFixture] classes in the same namespace together with a [SetUpFixture] to do the one-time initialization and cleanup. [I have no idea this is what they do, but it's what I would probably if I were doing it.] Let's further suppose that you have ten different browsers, of which you only want five to be active at a time. Parallel execution is not completely deterministic, but here is one way it could go...

1. All the SetUpFixtures are queued first.
      Queue: 10 setup fixtures.
2. Five workers start up five browsers and then add the individual fixtures for those browsers to the queue.
      Queue: 5 setup fixtures plus a bunch of test fixtures for the first five browsers.
3. The workers start up five more browsers and add all the fixtures under them to the queue.
      Queue: All the test fixtures for the 10 browsers
4. The workers continue to run fixtures. When the last fixture for any browser is finished, a OneTimeTearDown task for that browser is scheduled.
      Queue: Remaining test fixtures (e.g. for 8 browsers) plus teardowns (for 2 browers)
5. Eventually, all TestFixtures have run and the queue only has the teardown tasks.
      Queue: 10 tasks to clean up the 10 browsers.

6. The workers run till all 10 browsers are shut down.

As you can see from the above, it's entirely possible to have more 10 browsers active with only 5 threads. Bear in mind, that my example based only on a __guess__ of how SpecFlow makes use of NUnit. They haven't told us. Can you figure it out by looking at the generated code? Otherwise, if you can attach the files, I'll be glad to take a look. I would need both the feature file and the generated C#.

**Comment by CharliePoole** [comment]
@nunit/core-team We have had a number of issues around SpecFlow. I think I'll use this one to try to understand better how they make use of NUnit so we can give better answers than I'm giving @llaskin !

**Comment by CharliePoole** [comment]
Hmmm... The SpecFlow docs say "SpecFlow generates a unit test class for the feature element, with the class name derived from the name of the feature" and "SpecFlow generates a unit test method for each scenario, with the method name derived from the name of the scenario."

Assuming those docs still are accurate, my guess above is wrong. 😞  

So, it looks as if [BeforeScenario] would initialize a new browser __for each test__. Is that what you want? Or do you want to initialize it for each feature?

**Comment by llaskin** [comment]
for each test.

**Comment by CharliePoole** [comment]
In that case, I can't see why it is not working. Are you sure your [AfterScenario] is actually shutting down the browser?

Beyond that question, I would need to have some code to help you further.

**Comment by llaskin** [comment]
I'll work on getting you a working snippet.

**Comment by llaskin** [comment]
Charlie,
Can NUnit parallelize on the method level in each feature?  Parallel fixtures are by class, not by method right(currently) so beforeScenario won't work here, for workers to be respected on a per test basis(and lets say we are calling 5 workers), we need to have 5 features/classes and swap out the BeforeScenario tag for a BeforeFeature.  This might be an issue of how specflow converts/handles the BeforeScenario tag

**Comment by CharliePoole** [comment]
No, we currently only parallelize down to the fixture level. The very old #164, which I am currently working on, deals with per test parallelism.

Most people seem to use parameterized fixtures for browser testing. I'm not sure how - or even if - toucan do that under SpecFlow, but you might try BeforeFeature.
