### ISSUE TITLE
HttpMock.dll(1.3.3) Has no TestFixtures with Nunit3-console.exe  

### ISSUE THREAD

**Issue by LiyueWang** [nunit/nunit#2082]
Hi,

We have a project depends on HttpMock, recently I upgrade the Nunit from 2.6.4 to 3.6.1, HttpMock from 1.1.5 to 1.3.3. As the project is under AppVeyor which will detect HttpMock.dll as a test assembly, then I got this error:

>NUnit Console Runner 3.5.0 
Copyright (C) 2016 Charlie Poole
Runtime Environment
   OS Version: Microsoft Windows NT 6.3.9600.0
  CLR Version: 4.0.30319.42000
Test Files
    C:\projects\d2l-security-oauth2\src\D2L.Security.OAuth2.TestFramework\bin\Debug\HttpMock.dll
    C:\projects\d2l-security-oauth2\test\D2L.Security.OAuth2.IntegrationTests\bin\Debug\D2L.Security.OAuth2.IntegrationTests.dll
    C:\projects\d2l-security-oauth2\test\D2L.Security.OAuth2.UnitTests\bin\Debug\D2L.Security.OAuth2.UnitTests.dll

>Errors and Failures
>1) Invalid : C:\projects\d2l-security-oauth2\src\D2L.Security.OAuth2.TestFramework\bin\Debug\HttpMock.dll
Has no TestFixtures

But it worked fine with HttpMock 1.1.5 before. not sure if it is the problem with Nunit3 or HttpMock1.3.3?

**Comment by ChrisMaddock** [comment]
Look at the three dll's listed under "Test Files" - those are the three assemblies being passed to the NUnit runner. As you (or Appveyor!) have passed a dll which contains no tests (HttpMock.dll) - the console alerts you of this, by throwing the error. My guess, is that, by default, Appveyor passes anything which references the nunit.framework assembly to the console runner.

You have several ways around this:

1. Have the authors of HttpMock add a `NUnit.Framework.NonTestAssemblyAttribute` to their assembly. This is probably ideal, as it means the console runner will detect always that HttpMock is a library that references NUnit, rather than something with it's own tests.
2. Pass the test assemblies you want to test explicitly to Appveyor. You haven't shared your appveyor config, so I'm not sure exactly what you're doing at the moment, but I'd guess you're letting Appveyor discover NUnit assemblies for itself, which is incorrectly trying to test HttpMock.
3. Use the console option `--skipnontestassemblies`. This will prevent the failure, but is risky - what if, in future you're adding another assembly, but make a typo in the command - you'll be suppressing any possibly error message.


I'll close this issue now, as I don't think there's any change to be made here - let us know how you get on though. 😄

**Comment by LiyueWang** [comment]
@ChrisMaddock  Thanks for your quick response!
Yes, option 1 is ideal. But I am still curious that why nunit3-console with HttpMock 1.2.1 works? 
> Test Run Summary
  Overall result: Inconclusive
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0

I tried option 2 now to skip run HttpMock.dll :)
For option 3, I tried to use `--skipnontestassemblies` with HttpMock 1.3.3 but still the same error.

**Comment by CharliePoole** [comment]
@LiyueWang Are you sure it works with the __same__ version of NUnit3-console? I suspect that the error on non-test assemblies was added at some point because the inconclusive result was confusing people. 

If you are relying on AppVeyor to run NUnit automatically, it may be using a different version of the engine and console than what you use locally.

**Comment by LiyueWang** [comment]
@CharliePoole 
You are right, they are different version of nunit3-console.
I used a local nunit-console-runner 3.6.1 which works fine with httpmock 1.2.1
and the same runner with `--skipnontestassemblies` to process httpmock 1.3.3, which I got the same `Has no TestFixtures` error.

The nunit3-console of AppVeyor is 3.5.0

**Comment by ChrisMaddock** [comment]
HttpMock 1.2.1 references NUnit 2.6.4 - I believe this only relates to assemblies which reference NUnit 3.0+. 

(Unless you have the NUnit v2 framework driver installed, in which case, I imagine you have the same result?)

Apologies, I was incorrect on `--skipnontestassemblies`. Options 1 & 3 need to be in place together it looks like: the library has to have the NonTestAssemblyAttribute AND the user use the `--skipnontestassemblies` flag.

**Comment by ChrisMaddock** [comment]
Wait, hang on, the logic around `--skipnontestassemblies` has confused me a little. Here's the cases I see, I think:

1. If an assembly DOESN'T reference nunit.framework and NO `--skipnontestassemblies` - then it will be invalid.
2. If an assembly DOESN'T reference nunit.framework and HAS `--skipnontestassemblies` - then it will be skipped.
3. If an assembly DOES reference nunit.framework and NO `--skipnontestassemblies` - then it will be invalid.
4. If an assembly DOES reference nunit.framework and HAS `--skipnontestassemblies` and the assembly HAS a NonTestAssemblyAttribute, then it will be skipped.
5. If an assembly DOES reference nunit.framework and HAS `--skipnontestassemblies` and the assembly DOES NOT HAVE a NonTestAssemblyAttribute, then it will be invalid.

@CharliePoole - this issue perhaps raises an interesting point. @LiyueWang can't currently skip the HttpMocks library, without having the author agree to add a NonTestAssemblyAttribute. Is this something that should be possible?

Please feel free to verify the above - I may have missed something!

**Comment by CharliePoole** [comment]
@ChrisMaddock Take a look at our discussion around this in issue nunit/nunit-console#62 and PR nunit/nunit-console#150. Do we not seem to be doing what we said? Or was what we said wrong?

As a refresher... __if__ HttpMocks references the nunit.framework assembly __and__ it is passed to the runner on the command-line, __then__ the runner is obliged to treat it as a test assembly unless the author explicitly adds the attribute.

Regarding your five cases, I want to note that number 1 is invalid for a different reason from numbers 3 and 5. Case 1 is invalid because the assembly was entered on the command line and doesn't appear to be any kind of test assembly - although it could hypothetically be for a framework that isn't installed, like NUnit V2, xunit or junit (just kidding about the last two, at least till someone writes an extension). Numbers 3 and 5 are invalid because the assembly is __claiming__ to be an NUnit 3 test assembly, but no tests are found. The user has to leave them off the command-line to avoid the problem.

To my mind, things are working the way we said they should work, but I'm open to argument.

**Comment by ChrisMaddock** [comment]
Looks like this bit was decided later on, in the pull request. To clarify, it's the difference between 2 and 5 I find a little odd, I'd expected `--skiptestassemblies` to skip all non-test assemblies, regardless of whether they do or don't reference the framework. Likewise, I'd expected `NonTestAssemblyAttribute` to never be run, regardless of what flags the used on the command line.

I can understand the motivation behind it however, and looks like I did have plenty of time to comment a few months ago, so let's leave it as is unless it actually becomes an issue. 😄

**Comment by LiyueWang** [comment]
@ChrisMaddock  Agree, I'd also prefer the behavior that with `--skiptestassemblies` to skip all non-test assemblies, regardless of whether they do or don't reference the framework. But totally understand and respect your decisions. 

I could workaround with the appveyor config file to skip HttpMock for my problem. 

Thank you both!
