### ISSUE TITLE
Extend use of tolerance to ComparisonConstraints

### ISSUE THREAD

**Issue by NUnitTester** [nunit/nunit#2095]
The WithIn Option is available for Is.EqualTo. That's fine, but it is missing for the other ones:
`double x = ...;
Assert.That(x, Is.GreaterThan(1.0).WithIn(1.0e-12));`

The interpretation is:
  `if (x <= 1.0 - 1.0e-12) Assert.Fail(...);`
It is expected to have this for:
GreaterThan
GreaterThanOrEqualTo
LessThan
LessThanOrEqualTo
AtLeast
AtMost

**Comment by jnm2** [comment]
It's capitalized `WithIn`? That's a bug in and of itself...

**Comment by CharliePoole** [comment]
@NUnitTester I'd like to first clarify that this isn't a bug but how the feature is designed to work...

The `Within` modifier is available on `EqualConstraint` in order to specify a tolerance (plus or minus) for defining equality. It may be used without regard to the Type of the actual or expected value, so it has nothing particular to do with float or double. If specified, it is used whenever the type being compared is numeric, a TimeSpan or a DateTime. It takes further modifiers that allow you to tell the constraint to use the value given as a percent, a number of minutes, etc. When used on collections, the tolerance only comes into play when the members of the collection are of a type where it makes sense. For example, if you compare two object arrays that hold both ints and strings in different positions, the tolerance is only used for the ints.

I outline all this so you can understand that the features of `WithIn` are very much bound up with the features of `EqualConstraint`. It was designed for equality comparisons and was never intended to work with other constraints. The idea was certainly considered when we designed it, but we didn't see a strong need and would have had to implement it a bit differently in any case.

With a comparison constraint, you always have the choice of specifying the exact value to be used, just as you did in your example.

```C#
Assert.That(x, Is.GreaterThan(1.0 - 1.0e-12);
```

I will grant that the use of Within would provide a bit better documentation of what you are testing and might avoid errors in choosing whether to add or subtract the tolerance amount, depending on the type of comparison.

My judgement is that this would be a relatively low priority new feature and probably one we would invite an interested contributor to take on. As a start, my suggestion is that you state more precisely what you would like to work with comparison constraints:
 * Simple Within plus a number?
 * DateTime?
 * Other modifiers that are permitted after Within on EqualConstraint? (see docs)
Once we know what we are aiming for, we can decide whether to add this to our backlog.

**Comment by NUnitTester** [comment]
Sorry for the late answer. I not thought about a bug, it is a feature request. I like Within, but I cannot use it if I need GreaterOrEqual and it is a great feature to make clear, that mathematically correct is 1.0, but numerically it is only nearby and expected to have a maximum error of 1.0e-12.

- Simple within plus number? - I don't know what else is possible. Might be I don't understand.
- DateTime: Yes, that will be great to for performance issues. 1 second within 20 milliseconds.
- Modifiers like percent and ulps? Yes, should be like in EqualConstraint.

**Comment by CharliePoole** [comment]
So it appears that @NUnitTester is suggesting pretty much the same accepted syntax for comparison constraints that we use for EqualsConstraint. That probably means refactoring into a common base.

@nunit/framework-team @nunit/core-team I'm in favor of this. What do you guy think?

**Comment by rprouse** [comment]
I am in favor if it doesn't introduce too much complexity into the existing constraints 👍

**Comment by NUnitTester** [comment]
Fine. I'm happy for that!

**Comment by CharliePoole** [comment]
@nunit/framework-team Here is a simplifying idea for implementation. Does it make sense?

Rather than the obvious implementation for comparison within a tolerance, I could use the __existing__ code for equality within a tolerance. That is, when a tolerance is provided and expected and actual are equal within that tolerance, all four comparisons would pass. Otherwise, we would use the normal comparison without tolerance. My only concern would be boundary issues, which we have already with equality, since there is no way to specify whether a range is inclusive or exclusive. Thoughts?

**Comment by CharliePoole** [comment]
@nunit/core-team What about an error message for this feature?

For equality within a tolerance we display something like

```
  Expected: 5.0d +/- 0.01
```

But `+/-` might not seem correct in this context. What do you think?

**Comment by jnm2** [comment]
By boundary issues with equality, do you mean `GreaterThan(x).Within(y)` vs `GreaterThanOrEqualTo(x).Within(y)` won't work properly?

I don't like `±` when there is only one side. I'd prefer `Expected: < 5.0d + 0.01` and `Expected: > 5.0d - 0.01`

**Comment by CharliePoole** [comment]
Exactly so... Using that approach, these will pass, although they should fail...

```C#
Assert.That(5.05, Is.LessThan(5.0).Within(.05));
Assert.That(195, Is.GreaterThan(200).Within(5));
```

In the case of floating point, it's almost forgivable, but with an integer the error is obvious. It's too bad, because it was a very easy approach.

Using '+' or '-' selectively is a bit of a pain, since the code is currently in the common base class, but should be doable anyway. I guess the alternative would be to use "within"

**Comment by jnm2** [comment]
> I guess the alternative would be to use "within"

I think that's clearer than `+` and `-` or `±`.

**Comment by NUnitTester** [comment]
> Exactly so... Using that approach, these will pass, although they should fail...
> Assert.That(5.05, Is.LessThan(5.0).Within(.05));
> Assert.That(195, Is.GreaterThan(200).Within(5));

The exact numerical approach must be extended with the numerical accuracy of the double or float value:
`Assert.That(value, Is.GreaterThan(expected).Within(tolerance));`
must be calculated:
value >(expected - tolerance) * (1 - epsilon)  ---- or (1 + epsilon) in other cases
and epsilon = machine epsilon, which represents the upper bound of the relative error due to rounding in floating-point arithmetic. (NOT Double.Epsilon)

**Comment by jnm2** [comment]
@NUnitTester The relative error accumulates the more math operations you switch between, isn't it? So this epsilon would be totally dependent on how the value was calculated?

**Comment by CharliePoole** [comment]
@jnm2 That's the reason why NUnit has always simply left tolerance up to the user. Theoretically, we could come up with some additional allowance based on the calculations we do ourselves in testing the value, but we don't. :smile:

**Comment by NUnitTester** [comment]
@jnm2 Of course, if we do many numerical operations the relative error is bigger or how it is done. Some algorithms are stable other are not very stable. If you are interested in, look at [condition number of a matrix](https://en.wikipedia.org/wiki/Condition_number)
But this is the reason why tolerance is needed. Epsilon in my formular is needed because the values cannot stored accurate. It depends only of the type so it is different for float and for double. There are numbers which are exact in decimal system, but not in binary system. The error for double is about 1.0e-16. You can calculate it by running: 1.0 + epsTest = 1.0, if so, epsilon = epsTest * 2. Start epsTest with 0.5 and in each iteration take the half.

@CharliePoole I'm not sure what you mean.

**Comment by CharliePoole** [comment]
@NUnitTester I think I may not have been sure what you meant either. :smile: However, I thought you were saying that the NUnit code itself, which backs up the various constraints, accumulates a certain degree of error and that we need to change our formulas to allow for it.

If the epsilon you are using is simply the representational error, which is the traditional meaning, then I would say there is no need for us to apply it in our formulas. Anything within the representational error is already seen as equal.

Note that if you are doing the type of work that requires it, we already allow specifying the error within a certain number of ULPS for the equality constraint. I didn't implement that for comparison constraints, but it could be done.

If we want to take this discussion further, I think we should refer to our actual code to make it clearer.

**Comment by NUnitTester** [comment]
@CharliePoole then why have you wrote this?
> Exactly so... Using that approach, these will pass, although they should fail...
> Assert.That(5.05, Is.LessThan(5.0).Within(.05));
> Assert.That(195, Is.GreaterThan(200).Within(5));

**Comment by CharliePoole** [comment]
It was a discussion of a specific adhoc approach to this issue, which I used in the early commits while working on the structure. It's not in the current code, which @jnm2 reviewed.

Since this has been merged, I was taking your comments to refer to the actual implementation, which you can see in PR #2126. I'd be happy to have your comments on it for future improvements.

**Comment by CharliePoole** [comment]
@NUnitTester BTW, notice that the second example you quoted is with ints, not floating point, so the issue of representational accuracy doesn't arise. Rather, it was a basic flaw in the algorithm, now removed.

**Comment by NUnitTester** [comment]
Ok, thanks for clearify.
