### ISSUE TITLE
Category not available in TestContext when using TestCase

### ISSUE THREAD

**Issue by oskaruitdebos** [nunit/nunit#2107]
I have noticed that when using a testcase instead of a test, the category of the test is not available through the testcontext. So lets view some code:

```
[TestFixture]
public class FormTests : BrowserTests
{
    [TestCase("/some-url/", FormType.ContactForm), Category("form")]
    [TestCase("/some-other-url/", FormType.ContactForm), Category("form")]
    public void AssertFormIsSubmittable(string url, FormType formType)
    {
        Browser.OpenPage($"{BaseUrl}{url}", true);
        Browser.Action(FormActions.EnterFormFields(formType));
        Browser.Action(FormActions.Submit());

        var isSuccesfullySubmitted = Browser.Verify(FormState.IsSubmitted());
        Assert.IsTrue(isSuccesfullySubmitted);
    }

    [Test, Category("form")]
    public void FunctionToTestIfCategoryIsWorking()
    {
        Browser.OpenPage($"{BaseUrl}", true);
        Browser.Action(FormActions.EnterFormFields(FormType.ContactForm));
        Browser.Action(FormActions.Submit());

        var isSuccesfullySubmitted = Browser.Verify(FormState.IsSubmitted());
        Assert.IsTrue(isSuccesfullySubmitted);
    }
}

```
When running the AssertFormIsSubmittable (with the testcases), within the BrowserTests base class, when I execute:var category = TestContext.CurrentContext.Test.Properties.Get("Category"); the result is null.

When i execute FunctionToTestIfCategoryIsWorking, the same line of code has "form" as a result. That's the expected result. Somehow, when using a TestCase, it doesn't work anymore.

I tried to change the attributes to:

```
[TestCase("/some-url/", FormType.ContactForm)]
[TestCase("/some-other-url/", FormType.ContactForm)]
[Category("form")]
```

And:
```

[Category("form")]
[TestCase("/some-url/", FormType.ContactForm)]
[TestCase("/some-other-url/", FormType.ContactForm)]

```
And:

```
[Test, Category("form")]
[TestCase("/some-url/", FormType.ContactForm)]
[TestCase("/some-other-url/", FormType.ContactForm)]
```

All with the same result (a null when calling TestContext.CurrentContext.Test.Properties.Get("Category")).

**Comment by CharliePoole** [comment]
As far as NUnit is concerned, all the variations you tried are the same, with the exception of the first one,, which adds the category twice. In the case of attributes, order and layout are not relevant. That, there is no difference among all the layouts here:

```C#
[AttributeA, AttributeB]

[AttributeB, AttributeA]

[AttributeA][AttributeB]

[AttributeB][AttributeA]

[AttributeA]
[AttributeB]

[AttributeB]
[AttributeA]
```

In each case, the two attributes apply to the following method and the program using the attributes has no information about the layout of the source code.

In your example, the category attribute applies to the method as a whole. All information about which test case the category attribute was "associated with" disappears - I put that in quotes because the association is only in the mind of the programmer and is not represented in any way by the code.

Within NUnit, the method is associated with a test suite that contains all of your individual test cases. That suite has the Category on it and if you select the category from the command line, it will run together with all the contained tests. Since that's the primary purpose of categories, it's generally not a problem. However, if you want to access the categories in the test it won't work because the "test" that has the category is the higher level suite represented by the method and that's not available to you.

This is explained in more detail in issues #548 and #1358, which is why I'm closing this as a duplicate.

A few comments on your specific case:

1. Accessing the categories on a test seems like an odd thing to do. The information is right there in the source code!  If you are hoping to discover the category among several possible ones that __caused__ the test to be executed, you will not get that info. You will only get the categories specified on the test, which, as the programmer, you already know. If you want it for reporting, it's already in the XML output.

2. In order to allow individual test cases to have different categories, TestCaseAttribute supports the named property Category, which allows you to set the  test case category like this:

```C#
[TestCase("/some-url/", FormType.ContactForm, Category="form")]
```

This would allow you to access the category from within the test case code.
