### ISSUE TITLE
NullReferenceException when getting TestDirectory from TestContext

### ISSUE THREAD

**Issue by reeflog** [nunit/nunit#2110]
Hello !

In the context of an attribute implementing ITestAction applied at assembly level, I'm receiving NullReferenceException when calling TestContext.CurrentContext.TestDirectory in AfterTest method.

I've provided a project as a sample.
[ClassLibrary22.zip](https://github.com/nunit/nunit/files/896583/ClassLibrary22.zip)

As work around, I'm doing:
AssemblyHelper.GetDirectoryName(Assembly.GetCallingAssembly())

Is there another way to get the test directory at this moment ?

Regards,
Florian

**Comment by CharliePoole** [comment]
This line of code in TestContext.cs is at fault:

```C#
                    return AssemblyHelper.GetDirectoryName(test.TypeInfo.Assembly);
```

Use of `TypeInfo` implies that the test is implemented by a method or class. That's true for everything except the top-level assembly. We can either add special code to detect that it's a test assembly and cast in order to get the Assembly or - even simpler - arrange to fall through to the following code that uses `GetCallingAssembly`.

**Comment by reeflog** [comment]
Thanks for the quick answer and the fix.
