### ISSUE TITLE
Update nunit.linux.sln

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#2117]
The latest Mono releases drop .NET 2.0 targeting. The nunit.linux.sln should be updated to remove the 2.0 and 3.5 builds of the framework. It should also be possible to add the two .NET Standard builds, if they can be built in MonoDevelop or VS for Mac, which I'm not 100% sure of.

--------------------

Original post, since updated:

The Linux solution currently seems to include the portable build (which I didn't think could be built on Linux?), and not the .NET Standard build - which I think should be there?

This said, post-https://github.com/nunit/nunit/issues/2092 - with only .NET Framework and .NET Standard builds, then I think the Windows and Linux solutions could be the same - so perhaps we can just remove it instead? Unless the Linux solution is specifically for MonoDevelop? I don't use it, and don't know what it can and can't build.

**Comment by CharliePoole** [comment]
It would be great to remove it, but let's be sure first.

At some point, my understanding was that portable should build on Linux, so I put it there. I think it built at the start but then stopped building. I changed the build to skip it in CI. Since we are not planning to keep this build, I'd say to drop it.

In the case of .NET Standard, I have never been able to make it build. If you want to take that on, that would be great, IMO. If you do it, you should use the linux solutiion until we know it works. I can also take a look at it after I get my linux system back up - I have not been able to use it for a few weeks now after a change in my network connection.

Removing that solution also implies a number of changes to the build script, which checks what OS it is running on. It will be a pain to put them back if we end up needing them again. @rprouse do you envision any future platforms that won't run on linux?

**Comment by ChrisMaddock** [comment]
This actually came up because I was trying to add .NET Standard to our Travis build.

Currently, the nunit.Linux solution isn't actually used anywhere in our build script - it's an unused variable. 

I don't know what Mono supports in terms of PCLs, I didn't know it used to work! Hopefully not an issue for much longer, however!

**Comment by CharliePoole** [comment]
SOLUTION_FILE was originally used for building and for loading packages. We stopped building the solution in favor of building specific projects a long time ago. The last use - for packages - was removed about five months ago. In that case, I see no reason to keep either the variable or the solution file.

**Comment by CharliePoole** [comment]
Second thoughts... I expect we will be dropping 2.0 and 3.5 from the Linux build some time. Folks who work on Linux will need that solution, even though our CI script doesn't use it.

**Comment by rprouse** [comment]
Excellent point @CharliePoole . As I discovered, with the recent Mono releases dropping 2.0 targeting, users who start with a fresh Linux system may not be able to build the older targets. As you say, we may need to further pare down the Linux solution in the future.

**Comment by ChrisMaddock** [comment]
Renamed this to instead update linux.sln, based on this discussion. 🙂

**Comment by jnm2** [comment]
@ChrisMaddock this is marked easyfix but I'm not sure I understand what work needs to be done or how to do it. Can you review whether this issue should have easyfix and/or up-for-grabs?

**Comment by ChrisMaddock** [comment]
Thanks @jnm2 - it's due an update anyway, as things have moved on. I'll comment here, and update the opening post.

The latest Mono releases drop .NET 2.0 targeting. The nunit.linux.sln should be updated to remove the 2.0 and 3.5 builds of the framework. It should also be possible to add the two .NET Standard builds, if they can be built in MonoDevelop or VS for Mac, which I'm not 100% sure of.

I don't actually use Linux at all. @CharliePoole - do you think that is a correct assessment of what should be done here?

**Comment by CharliePoole** [comment]
I think we'll want to drop .NET 2.0 and 3.5 at some point for sure. The thing is, we are a test framework and lots of users stay behind the curve on new adoption. The historical NUnit approach has been to keep support for a long time. NUnit 2.6.4, for example has. support for .NET 1.0 and we still support .NET 2.0 in NUnit 3.

So, now may be the right time, but it's a major project decision to make. IMO we could drop support for __building__ with 2.0, 3.5 and 4.0 under Mono but we should still support running those profiles using older versions of Mono. That will mean adjusting how we test, i.e. using a Windows build to test on Linux.

If we actually wanted to drop support for __running__ under older Mono versions, then I think that's a breaking change for a major release. @rprouse What do you think?

**Comment by ChrisMaddock** [comment]
I only intended this to relate to dropping .NET 2/3.5/whatever's-necessary from the nunit.linux.sln - to allow developers running newer mono version to have a solution the can build straight off. The builds would still be ran in CI (which _doesn't_ use nunit.linux.sln), and still 'supported' - at least as I meant the me comment above.

If that's not an issue, imo we should just remove nunit.linux.sln, and recreate it at such a time as we need it. I only originally intended this issue to be about PCL/.NET Standard - which seems to now be resolved.

**Comment by CharliePoole** [comment]
Those of us who build under Linux need the solution, of course. 

I just followed you by enlarging the issue even further. 😄 

Since the __binaries__ we distribute are built on Windows, anyone who uses them on Linux is technically getting untested assemblies. In principle, we should be testing the binaries we distribute on all platforms but that's not something we are as yet set up to do. I'd like to do some work on that, at least for Linux, when I come back from vacation.

Whether we do it here or on another issue, I think it would be a good idea to decide on the timing of dropping the pre-4.5 support for building on Linux.

**Comment by ChrisMaddock** [comment]
@CharliePoole - at this point, I think I'm going to bow out of discussion. Neither building nor testing on Linux myself, this isn't a topic I have much to contribute on! 😄 

I've retagged as design - will leave it with those more interested in this area.

**Comment by CharliePoole** [comment]
That seems OK. Whoever works this can decide whether to do the dropping, adding or both in a PR.

**Comment by rprouse** [comment]
I think dropping building pre-4.5 on Linux will likely come soon. Mono dropped support in 4.0 and they are now on 5.x. I think we will need to drop support once the common distros start shipping with Mono 4+ if that hasn't happened already. I can't build NUnit in Linux on some of my machines, so it is coming...

**Comment by rprouse** [comment]
I wonder if the name of the solution is incorrect. The Linux build isn't really a Linux only, it is for users of Mono on Linux or Mac. Should we have a Mono solution that just builds what current versions of Mono can build and maybe a NetCore solution for users on those platforms that have .NET Core installed instead of mono?

**Comment by rprouse** [comment]
Closing, we are dropping the Linux specific solution in #2380 which switches to multi-targeted `csproj` files. @jnm2 has managed to get all of our projects and targets building on all platforms.
