### ISSUE TITLE
Running fixtures in parallel with fixtures of other assembly only

### ISSUE THREAD

**Issue by LazyPotato** [nunit/nunit#2128]
Hi,
I've got this simplified configuration:
1. WhiteAssembly
     -  WhiteFixtureOne
     -  WhiteFixtureTwo
2. BlackAssembly
     -  BlackFixtureOne

Now my goal is to run WhiteFixtureOne in parallel with BlackFixtureOne, but not with WhiteFixtureTwo. I have tried different combinations of Parallelizable attributes and ParallelScope parameters without success. Is this possible?
Thanks in advance.

**Comment by CharliePoole** [comment]
The key to understanding this is to realize that parallel execution __between__ assemblies and parallel execution __within__ an assembly are two entirely different things in NUnit.

`[Parallelizable]` and `[NonParallelizable]` in your test code only impact how the framework runs tests within that assembly. To avoid parallel execution of fixtures within your assembly, you can simply not use `[Parallelizable]` at all, since the default is that nothing runs in parallel.

Parallelism between two different assemblies depends on the runner, not the framework. Runners that support parallel execution of assemblies do so by creating separate instances of the framework in different processes. That's what `nunit3-console` does, for example. If you run your two assemblies under `nunit3-console` with default options, the two test assemblies are run in parallel.

For a more detailed explanation, see the docs at https://github.com/nunit/docs/wiki/Parallel-Test-Execution

**Comment by CharliePoole** [comment]
Feel free to follow-up here if you are using some other runner besides `nunit3-console`.

**Comment by LazyPotato** [comment]
Thanks for your detailed response, things became much more clear now! 
Also i defined the cause of my problem. We are using Teamcity 10 to run tests and execution using cmd line wih bare call to `nunit3-console` succeeds (assemblies run in parallel as expected), while using NUnit runner type results in consecutive execution of assemblies. 
So i suppose that is more a Teamcity issue. Thanks for your help again.
