### ISSUE TITLE
Assert.That with a Throws constraint does not provide as much info as Assert.Throws

### ISSUE THREAD

**Issue by a-ctor** [nunit/nunit#2146]
When using `Assert.Throws` and an unexpected exception is thrown nunit provides information about the unexpected exception. 

```csharp
[Test]
public void UnexpectedExceptionWithInfo()
{
  Assert.Throws<IOException>(() =>
  {
    throw new FormatException("This is a format exception.");
  });
}
```

This test expects an `IOException` to be thrown but instead a `FormatException` is thrown. This provides the following output:

```
 Expected: <System.IO.IOException>
  But was:  <System.FormatException: This is a format exception.
   at Testit.Tests.<>c.<UnexpectedExceptionWithInfo>b__0_0() in Program.cs:line 23
   at NUnit.Framework.Assert.Throws(IResolveConstraint expression, TestDelegate code, String message, Object[] args)>

at Testit.Tests.UnexpectedExceptionWithInfo() in Program.cs:line 21
```

It is providing information about the unexpected `FormatException` (message + stack trace). The problem is that in our codebase we are using `Assert.That` with a `Throws.TypeOf<>` constraint like this:

```
[Test]
public void UnexpectedExceptionWithoutInfo()
{
  Assert.That(() =>
  {
    throw new FormatException("This is a format exception.");
  }, Throws.TypeOf<IOException>());
}
```

But when this example encounters the unexpected `FormatException` the following is output:

```
  Expected: <System.IO.IOException>
  But was:  <System.FormatException>

at Testit.Tests.UnexpectedExceptionWithoutInfo() in Program.cs:line 30
```

Note here that the information about the unexpected exception (message + stack trace) is gone. But exactly those two exception details would be relavant for debugging the failed test.

Is this behaiviour intended? And if yes are there easy ways to fix this issue?

My current workaround is to use a `ThrowsConstraint` with an `ExceptionTypeConstraint` as base constraint: 

```
[Test]
public void UnexpectedExceptionFixedInfo()
{
  Assert.That(() =>
  {
    throw new FormatException("This is a format exception.");
  }, new ThrowsConstraint(new ExceptionTypeConstraint(typeof(IOException))));
}
```

**Comment by rprouse** [comment]
Great report, thanks. I have labelled and added to the backlog.

**Comment by CharliePoole** [comment]
Nice! This is interesting because we actually test for the proper message. However, in our test we use `ExceptionTypeConstraint` directly, which is not what the syntax creates for us. Classic downside of isolated tests! I'm looking at this since it caught my interest.

**Comment by CharliePoole** [comment]
There are complications here that could lead us deep in to the building of constraint expressions. However, I can see two pretty simple solutions.

1. `Throws.TypeOf` could return an `ExceptionTypeConstraint` rather than an `ExactTypeConstraint`. That will fix the exact case reported but will not fix either  `Throws.Exception.TypeOf` or `Throws.InstanceOf`, which display the same problem. It would, however, be an improvement.

2. We could modify `ConstraintResult.WriteActualValueTo` so it works just like the corresponding method in `ExceptionTypeConstraintResult` when the actual value is an exception. This is a wide-reaching change so we would have to check to see if there are any problems. I can't think of a situation where the actual value would be an exception and we __wouldn't__ want to see message and stack trace, but there could be one. If we take this approach, we could consider marking `ExceptionTypeConstraint` as obsolete, since it will no longer be necessary.

I'm taking my name off this and marking it as an easy fix. I recommend trying approach 2 first.

**Comment by GCichosz** [comment]
Up for grabs?

**Comment by CharliePoole** [comment]
All yours. 😄 

What I suggest is that you try the second approach on your fork and see if the more global change breaks anything. If not, we can go ahead with it. If it does, I think the first approach is good enough.

**Comment by gcichosz** [comment]
The problem with the second approach is that the actual value could be an exception only in case of `ExceptionTypeConstraintResult`, but in fact even there it isn't. In case of `ExactTypeConstraint`, which `Throws.TypeOf` uses, the actual value is a type, and that makes sense, since it's a type constraint. I see no simple and decent way of modifying `ConstraintResult.WriteActualValueTo` so that works similar to `ExceptionTypeConstraintResult.WriteActualValueTo`. @CharliePoole please tell me if I miss, or misunderstand something. If not, I'm going with the first approach.

**Comment by gcichosz** [comment]
Unfortunately the first approach doesn't work either. `Throws.TypeOf` uses `ConstraintExpression.TypeOf` under the hood. It's return type can't be changed to `ExceptionTypeConstraint`, because `ConstraintExpression.TypeOf` constraint is suppose to work with types other than `Exception`. @CharliePoole correct me if I'm wrong.

That issue just stopped looking like an easyfix to me :wink:

**Comment by gcichosz** [comment]
Please unassign me from this issue, for a while I wasn't able to find time to do it.

**Comment by ChrisMaddock** [comment]
Done, no worries. 🙂

**Comment by BlakeWills** [comment]
I'd quite like to pick this up as my first contribution, could you assign me please? :)

**Comment by mikkelbu** [comment]
@rprouse Can you invite @BlakeWills, so we can assign the issue to him

**Comment by BlakeWills** [comment]
I thought I had a solution to this, but as already mentioned above, the fundamental problem here is that `Throws.TypeOf()` returns `ExactTypeConstraint`, rather than `ExceptionTypeConstraint`.

This is a problem because `ThrowsConstraint.ApplyTo()` returns an instance of `ThrowsConstraintResult`, with the base result set to the caught exceptions type (rather than the actual exception). As mentioned before, this makes sense for a `TypeConstraint`.

I thought that we could get around this by creating a new instance of `ConstraintResult` with the caught exception, instead of calling `BaseConstraint.ApplyTo()` when we create the `ThrowsConstraintResult`, inside `ThrowsConstraint.ApplyTo()`.

The problem with this approach (aside from it being a bit hacky), is that there is no way of comparing the caught exception type to the expected exception type. (Because we don't have direct access to the expected type; this lives within `ExactTypeConstraint`.

I think a potential fix to this issue is to introduce a new `ExceptionConstraintExpression`, who's `TypeOf()` methods return `ExceptionTypeConstraint`, rather than `ExactTypeConstraint`. (This may well be a dumb idea, as it's the first time I've looked at the code, so I don't really understand the architecture / internals.)

**Comment by rprouse** [comment]
@BlakeWills I am going to assign this to @mikkelbu to work with you on this issue.

As for your analysis, I would need to look at the code, but your analysis and possible solution sound like a good start.

**Comment by jnm2** [comment]
@BlakeWills Still interested in this one?

**Comment by ZenonBuratta** [comment]
Haven't seen any activity on this for a while. Mind if I take a look?

**Comment by jnm2** [comment]
Please do! @mikkelbu would you like to stay assigned to help out with anything @ZenonBuratta needs?

**Comment by ZenonBuratta** [comment]
Thanks @jnm2.

I have taken a look into this and I agree with all the previous points made. To recap:

1. "Throws.TypeOf could return an ExceptionTypeConstraint rather than an ExactTypeConstraint"
This does not seem like a good approach as TypeOf is designed to work with all types not just   exceptions. Also because of syntax like Throws.Exception.TypeOf, it makes it difficult to cover all cases cleanly.
2. "We could modify ConstraintResult.WriteActualValueTo so it works just like the corresponding method in ExceptionTypeConstraintResult" 
This feels far too low level when this really only affects type comparisons.

What seems like an easy win is to modify the ApplyTo method in the TypeConstraint to check if the actual type was an exception. If so, pass the exception as the actual value instead of the type. 

I am not a huge fan of type checking, however, seeing as we are already comparing types in this area I think it is a reasonable result.

Attempting to do this broke a lot of tests, not sure if they were all change related, but after checking a few at random it appears the tests need updating to accept having the exception message in the output. As Charlie Poole states, I can't see a senario where someone wouldn't want to see the exception messgage. If you are happy with this approach so far, I will continue to look into the failing unit tests at the weekend to see if anything unexpected has broken as a result.

**Comment by mikkelbu** [comment]
> Please do! @mikkelbu would you like to stay assigned to help out with anything @ZenonBuratta needs?

Sure.

**Comment by jnm2** [comment]
Thank you! 😊
