### ISSUE TITLE
The Idiomatic Way to Aggregate NUnit XML Result Files?

### ISSUE THREAD

**Issue by leasunhy** [nunit/nunit#2155]
Because currently `NUnit Console Runner` does not support .NET Core, we choose to wrap `NUnitLite` into a _test runner_ and a _meta runner_ (pls excuse my bad naming... : D) to implement testcase-level process isolation and timeout.

[Test Runner](https://github.com/leasunhy/GraphEngine/blob/test-nunit/tests/nunit_tools/nunit_test_runner/Program.cs)

[Meta Runner](https://github.com/leasunhy/GraphEngine/blob/test-nunit/tests/nunit_tools/nunit_meta_runner/Program.cs)

Currently both process isolation and timeout work well.
There remains only one problem: Now that the runner generates a result file for each test case, __what is the idiomatic way to aggregate the NUnit XML result files into only one file?__ Or, is there a better way to implement process isolation and timeout under .NET Core?

Thank you 😄

**Comment by rprouse** [comment]
@leasunhy why did you close this issue?

**Comment by CharliePoole** [comment]
Also, the answer depends to some degree on what exactly you are doing to "wrap" NUnitlite.

**Comment by leasunhy** [comment]
@rprouse Sorry for closing the issue without an explanation... The reason is that I've started writing a tool to merge the result files to suit my needs. Thank you! 😄

**Comment by CharliePoole** [comment]
FWIW, if I were writing the "meta runner" you describe, I wouldn't create files for each test and then merge them. Rather, I'd just grab the test result internally and build a tree to eventually save as a file.

**Comment by JustinRChou** [comment]
I was under the impression that you could use an `@file` and it would all be in one result file?

**Comment by CharliePoole** [comment]
He is running each test in a separate process, which is not something supported by any of our runners yet.

**Comment by leasunhy** [comment]
@CharliePoole I'm not sure whether I've got what you meant... Did you mean to grab the XML node representing the result for the test case, via IPC?
@JustinRChou Isn't `@file` for specifying command line arguments?

**Comment by JustinRChou** [comment]
@leasunhy 
I was thinking if it was possible to input a `@file` with all the tests that you are going to run to see if it just outputs one xml file instead of executing each test using the loop.

**Comment by CharliePoole** [comment]
@leasunhy Yes, that's essentially what the console runner does to combine output from multiple processes. However, I see you're running .NET core, which the console runner doesn't support yet.

**Comment by leasunhy** [comment]
@JustinRChou Ok 😄 
@CharliePoole Yes, after experimenting with the merger, I think the approach you've mentioned is the optimal way :D BTW, is there a public API in NUnitLite or the NUnit Framework to get the XML result without writing a file?

**Comment by CharliePoole** [comment]
With respect to the framework, it depends on whether you are running tests through reflection or using a direct reference. The published Framework API uses reflection and is documented call the same API as NUNitLIte, documented only in the source code. See interface ITestAssembly.

NUnitLite itself doesn't have an API, as it isn't designed to be called by users except through self-executing tests, which use the AutoRun class. You can examine the source code to find things to call, but since NUnitLite is really only about interfacing with the tests, you'll probably get more use out of it as an example of code.

The nunit engine is able to run tests out of process and is what I would actually use in your situation were it not for the fact that you have some .NET Core tests to run.
