### ISSUE TITLE
Issues running Nunit tests from Windows OS CMD using Test Selectors

### ISSUE THREAD

**Issue by garp2100** [nunit/nunit#2162]
Hello,

I'm trying to run tests remotely. I'm using PSExec from a windows server 2012 environment to remotely run a batch file in a windows 10 machine.

The inside of the .bat file has 

`C:\Unit\NUnit3\nunit3-console.exe C:\Folder\MyTests.dll --result=C:\MyDirectory --where:cat=Testing`

If I double click the .bat file directly it runs and picks up the "where" clause and runs the tests with that category in their fixture as shown in the screenshot below.
![1](https://cloud.githubusercontent.com/assets/22939665/25922412/253ec390-35a7-11e7-92e9-507e0571023a.jpg)

If I run the same .bat file using CMD as an administrator it skips that "where" clause altogether as shown in the second screenshot below.
![2](https://cloud.githubusercontent.com/assets/22939665/25922488/65683a50-35a7-11e7-9472-30e26b504c8a.jpg)

Apologies if I'm missing any details, will be more than glad to fill out what I missed out.

Any help with this issue is greatly appreciated.

Regards,

**Comment by CharliePoole** [comment]
Test Selection Language uses some special characters, which may need quoting or escaping to get through the command processor on a particular shell or OS. The character '=' is one of those.

I believe that your problem will be solved if you use

```
    --where "cat=Testing"
```

Other characters that may give you an issue are '|' and '&'. In those cases, you can use the alternate forms "or" and "and" but you will still need quotes since the expression will then contain spaces.

By the way... the --result option does not take a directory as it's argument. Check the help message from nunit3-console --help.

Closing this, but feel free to add more comments if you need more help.
