### ISSUE TITLE
NUnit3TestAdapter does not find ITestBuilder tests without other NUnit usage

### ISSUE THREAD

**Issue by derekgreer** [nunit/nunit#2163]
I have a library called NUnit.Specifications which utilizes```NUnitTestCaseBuilder``` to facilitate context/specification style tests.  For projects targeting .netapp1.1, the library works fine, but for projects targeting  .Net Framework 4.6.2 the NUnit3TestAdapter does not recognize tests created by ```NUnitTestCaseBuilder``` unless the project has at least 1 class which has an NUnit attribute (e.g. ```TestFixture```, ```Test```) or otherwise uses something from the NUnit library (e.g. something with a call to Assert.IsTrue(true);).

## Example:
```C#
using NUnit.Framework;
using NUnit.Specifications;
using Should;

namespace ClassLibrary1
{
    // uncommenting any of the below will cause the adapter to find the context/specification test

    //[TestFixture]
    public class ControlTests
    {
       // [Test]
        public void ValidateStandardNUnitTest()
        {
            // Assert.IsTrue(true);
        }
    }

    [Subject("some test")]
    public class when_running_context_specification_style : ContextSpecification
    {
        static int _results;

        Establish context = () => { _results = 0; };

        Because of = () => _results = 2;

        It should_work = () => _results.ShouldEqual(2);
    }
}
```

## packages.config:
```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.NET.Test.Sdk" version="15.0.0" targetFramework="net462" />
  <package id="Microsoft.TestPlatform.TestHost" version="15.0.0" targetFramework="net462" />
  <package id="NUnit" version="3.6.1" targetFramework="net462" />
  <package id="NUnit.Specifications" version="2.0.0" targetFramework="net462" />
  <package id="NUnit3TestAdapter" version="3.7.0" targetFramework="net462" />
  <package id="Should" version="1.1.20" targetFramework="net462" />
</packages>
```

**Comment by CharliePoole** [comment]
This has come up before with other frameworks layered on top of Nunit. It is an intrinsic part of the design of the NUnit engine, which is used by the VS adapter as well as the console and gui runners. The engine is designed to work with multiple frameworks. It determines  which framework driver to use by examining the references in the test assembly. In the situation you describe, it finds no reference and determines it cannot find tests within that assembly.

This situation would be treated as an error in most of the runners, but the VS adapter is an exception. Because of it's architecture, NUnit is passed many non-test assemblies as well as test assemblies - whatever assemblies your solution builds, in fact. Consequently, we pass over that situation with only a light warning in the output window.

Your tests should actually reference NUnit to be NUnit tests and for that reference to actually show up in the metadata, you should use at least one NUnit Assert, Attribute or other component.

**Comment by derekgreer** [comment]
That makes sense when considering the differences from one test runner to another, but I would expect the VS adaptor to behave the same between projects targeting net462 vs netcoreapp1.1.

As an aside, the base class the context/specification class inherits from is infact decorated as an NUnit test (i.e. it is decorated with the [TestFixture] attribute), so from an OO perspective is it an NUnit instance.  I assume you mean the actual concrete class needs to reference NUnit in some way, but it would be a welcomed enhancement to allow these attributes to be inherited.

**Comment by CharliePoole** [comment]
@derekgreer All our core runners use the same engine, so they all work the same. Unfortunately, the very latest beta adapter includes entirely different code for .NET Core, which was developed solely for use in .NET core and does not include the ability to use other frameworks than the NUnit 3 framework. Consequently, it can make assumptions that the mainline codebase can't make - in this case, it assumes that whatever you give it uses the NUnit3 framework.

[@rprouse please fact-check me in the above]

I think we are going to have to make some big decisions about the adapter. Possibly, there should be two different adapters, one for desktop .NET and one for .NET Core. You could install either one. Alternatively, the NUnit adapter could be rewritten to NOT use the engine but to directly interact with the NUnit3 framework. That wouldn't lose any current functionality, because most engine facilities are currently not exposed to the adapter. It would, however, make it impossible to use engine extensions from the adapter - a feature that we don't now have but have promised for the future.

As Rob wrote elsewhere, there is a conflict between continued support of older platforms - traditionally a big emphasis with NUnit - and rapid takeup of new platforms. I'm wondering now if trying to do both in the same package may have been a mistake on our part.

That gets us into a pretty big issue, which won't help you with your immediate problem. For now, no runner that uses the engine will be able to run your tests unless we can find a reference to the framework in the test assembly. In a past issue, we considered and rejected the idea of searching references recursively. Basically, if you want to build on NUnit, this is a requirement. The alternative would be to write a framework driver for your own framework and instruct users to install it.

This is an issue that virtually every framework such as yours has dealt with successfully in the past. In actual practice, it doesn't turn out to be a big burden on users to make some reference to NUnit in their tests. Often that happens naturally, because they want to use some feature. When it doesn't they simply need to be made aware of the need to do so.

BTW, the first time this came up, I considered an attribute like `NUnitTestAssemblyAttribute` to be put at the assembly level. However, it's really just as easy to add a `DescriptionAttribute` or a `LevelOfParallelismAttribute` and that does the job.

One more thing. You should add `NonTestAssemblyAttribute` to your own framework assembly. Otherwise, in some cases, it will get picked up by a user script and passed to NUnit, resulting in an error when no tests are found.

**Comment by rprouse** [comment]
The .NET Core version of the adapter works in the same way in that it checks if the given assembly references nunit.framework.dll. I think the difference is in the way .NET Core handles child dependencies.

It is late and I am tired, but if a test assembly references `Nunit.Specifications`, that NuGet package has a dependency on `NUnit`, so a reference will be added to the project. Why are we not able to find that reference and therefore identify the assembly as runnable by us even if it doesn't directly call any NUnit code? `DriverService` iterates through the references and the driver factory returns supported if the reference is NUnit. If NUnit is referenced, I thought it should be in the list. Are unused references stripped out of assemblies?

**Comment by CharliePoole** [comment]
Yes, unused references have never appeared in the assembly metadata. This issue has come up a number of times in the past. It is definitely confusing to naive users, who know they added the reference in VS, but it's not actually included if you make no use of it.

**Comment by CharliePoole** [comment]
@derekgreer Rereading my earlier comment, I can see it may be confusing because of the term "core runners" that I used. What I meant by that was our key, mainstream, long-available runners like nunit-console, the gui and the desktop .NET adapters. IOW, I was excluding the .NET Core runners from our so-called "core" runners. Not a good choice of words, I'm afraid.

**Comment by derekgreer** [comment]
@CharliePoole Thanks for all the info.  This has been really valuable in understanding what what going on with the test runners.

While I understand any reference will ensure the test project adds a dependency to NUnit.Framework.dll, thus ensuring it gets picked up, I'm considering adding a recommendation for my project to include an assembly attribute reference (as opposed to recommending that people decorate all specs with ```[TestFixture]```).  It would be great were there to be an assembly attribute specifically created to be the inverse of NonTestAssembly for consumers of frameworks such as mine (i.e. ```[assembly: NUnit.Framework.TestAssembly]```), but I see no such attribute.  In lieu of the availability of that, is there a particular attribute you would recommend being used?  I'm considering recommending that users create an "Attribute.cs" class which defines a default Category (e.g. ```[assembly: Category("NUnit.Specifications")]```), but I thought it might be best to get a recommendation from you.  Is there some innocuous assembly-level attribute that might be used for such a purpose?

**Comment by CharliePoole** [comment]
I thought of doing exactly that when I created `NonTestAssemblyAttribute` but it seemed like there were already attributes that did the job. I've been suggesting `Parallelizable`, `NonParallelizable`,  `LevelOfParallelism`, `Description` and `Property` as options. I'm suspicious of `Category` because it may lead users to believe it has some effect in selecting tests, whereas on the assembly I don't believe it will.

While you can place a category on the assembly, it seems like it
