### ISSUE TITLE
Platform exclude feels unnecessarily difficult

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2188]
This made sense to me, but I didn't realize for a few days that the test wasn't getting run on net45:
(Preprocessor because the attribute is not supported on those platforms.)

```c#
#if !(NETSTANDARD1_6 || PORTABLE)
        [Platform(Exclude = "Net-4.0", Reason = "Not supported by async polyfill.")]
#endif
```

This does not work because exclude takes precedence over include, and `Net-4.0` always applies to `net40` and above:

```c#
#if !(NETSTANDARD1_6 || PORTABLE)
        [Platform(Exclude = "Net-4.0", Include = "Net-4.5", Reason = "Not supported by async polyfill.")]
#endif
```

I could do this, but this becomes a maintenance problem as soon as netstandard and portable start supporting the attribute:

```c#
#if !(NETSTANDARD1_6 || PORTABLE)
        [Platform(Include = "Net-4.5", Reason = "Not supported by async polyfill for .NET 4.0.")]
#endif
```

-----

Edit: I have just realized that the net40 nunit framework is being tested under net4.5, so `Platform("Net-4.5")` does not exclude 4.0. So the attribute is not useful to be dogfooded on its own unless we guard it with preprocessor.

Guess I'll go with this:

```c#
#if NET_4_0
        [Platform(Exclude = "Net-4.0", Reason = "Not supported by async polyfill for .NET 4.0.")]
#endif
```

**Comment by CharliePoole** [comment]
I don't understand why you don't just use the preprocessor exclusively and forget about using the attribute.

Of course we have a deeper problem to solve in terms of recognizing which platform we are running under, but it seems you could bypass the problem here.

**Comment by rprouse** [comment]
The `Platform` attribute gets defined out of portable and .NET Standard because we originally had trouble identifying the platform in those targets. I've been meaning to start a discussion with the @nunit/core-team about the future of the `Platform` attribute. We've been doing a poor job of keeping it updated for new platforms and with the number of new platforms growing quickly with .NET Core, I think it is going to get even further out of date. I don't have a proposal yet, but wanted to see what others think.

**Comment by CharliePoole** [comment]
I'd like to see Platform and Culture attributes entirely replaced by Include/Exclude as described in https://github.com/nunit/docs/wiki/Include-and-Exclude-Attributes-Spec

Of course, that would just change syntax and we would still have to solve the problem of identifying the platform. When we had the compact framework and silverlight builds, we did it the easy way: they just returned hard-coded values, since they could only run in one environment. But that won't work with .NET standard unless we add some code to it to truly detect the platform as exactly as we allow users to specify it. 

It's interesting that we currently do a better job (though not perfect) in selecting the platform under which we want to run than we do in detecting that platform. For example, we can run targetting .NET 4.5 rather than 4.0, but the framework still can't tell the difference. One possibility in this case is for the engine to pass a setting to the framework that simply tells it what platform it is running on.

We need a bunch more work on this... I'm not sure however if it's the same issue @jnm2 was raising or an entirely different one.

**Comment by rprouse** [comment]
Once Portable is gone and we only have the .NET Standard targets, we could do framework and platform detection using `RuntimeInformation.FrameworkDescription` and `RuntimeInformation.OSDescription` assuming they are not localized so that we can parse info out of them.

**Comment by jnm2** [comment]
> I don't understand why you don't just use the preprocessor exclusively and forget about using the attribute.

It's important to me that framework differences like this are highly visible. It's documentation for future maintenance. The .NET team goes even further and would have added a second test demonstrating the net40 behavior, until fixed or indefinitely.

**Comment by CharliePoole** [comment]
@jnm2 I get that, but the PlatformAttribute doesn't give you that visibility. It's specifically designed to skip tests without highlighting in any way. So basically it's only a question of whether the test report counts this test as skipped or doesn't count it at all. It's not like it gets listed anywhere.

**Comment by jnm2** [comment]
@CharliePoole It stands out in the ReSharper test runner with a skipped icon and message, both in the skipped list and in the tree. The VSTest adapter also lists it as skipped. I haven't checked the nunit console runner yet. Anyway, it's much better than having that test name, icon and message not appear.

**Comment by CharliePoole** [comment]
@jnm2 Ironically, the console, which doesn't show it at all, is the one that is working as the property was designed to show up. Our adapter loses information in translating to what VS wants, so all Skipped tests appear as warnings. That's essentially a VS bug. How R# shows it is - how can I say this nicely - not something I think we should care about as a project, but comes from the same source: translating a richer set of outcomes to a parser test of outcomes.

When something is not run, that's either bad or good (or at least dont-care) We have a way to show things that are not run for a __bad__ reason: the Ignore attribute. The PlatformAttribute is intended for things that were never intended to work on a particular platform and which we will never need to do anything about. 

I guess I was assuming that the difference in .NET 4.0 in your case was in the second category, since you used PlatformAttribute for it. In fact, we have probably used it for the wrong reason ourselves in some places in our own tests, giving you a bad example to follow.

**Comment by jnm2** [comment]
@CharliePoole I get your point, but to be practical, how ReSharper shows it will continue to be all I typically see as a consumer unless NUnit adds a VS test runner extension with UI and a way to click Run and Debug next to the method name in the source code. To say nothing of live unit testing.

I see that I misunderstood the platform attribute. Having contributed to other projects that were not using NUnit, I was looking for an attribute that filtered tests based on platform which would show a visible skip message. It sounds like NUnit does not have this?

**Comment by CharliePoole** [comment]
It doesn't have it because the intent of PlatformAttribute is that it should be used for features not intended to be tested on a particular platform. So, skipping isn't an error or warning or even something you ever want to see. Culture works the same way: I write a test that __only__ works if I am running under a certain culture, so I don't want to see anything about it if I'm not running under that culture. Of course, I would probably have other tests that run under other cultures. Basically, any test that has a Skipped outcome is supposed to be something I don't care about, so NUnit doesn't see it. Sometimes people do use it in a different way, not understanding how it is intended.

The status we have that indicates a test was not run __as a warning__ is Ignore. If you have something that you want to call attention to, that's what you are expected to use. Many people don't do it because they don't like to see the warning status in their test runs. 

What we are lacking is a way to say, for example, don't run on a particular platform and issue a warning rather than merely skipping a test. That would be a significant enhancement, probably calling for the addition of some kinds of conditions to the IgnoreAttribute.

As the author of this issue, are you intending it to fix the particular problem you gave as an example, or are you looking to do something more general. I'm asking, because we are getting fairly far away from the test that you can't express the way you want to express it. Also, because I like to see issues focus on a particular problem. 😄

**Comment by jnm2** [comment]
In the specifics of my particular case, I need to know what target the async method was compiled against, not what runtime I'm on. So what I was doing was abuse of PlatformAttribute. What I really need is this:

```c#
#if NET_4_0
        [Ignore("Not supported by async polyfill for .NET 4.0.")]
#endif
```

With this issue though I'm looking for a bigger discussion on PlatformAttribute because the day will come when I need to know what runtime I'm on, and I'll want to be able to exclude `net40` without excluding `net45`. We should have a facility for this.

**Comment by jnm2** [comment]
And I'll want `Ignore`-like behavior.

**Comment by jnm2** [comment]
Since no one has an immediate need for `Ignore` behavior conditional on runtime platform detection, I'm closing this for now.
