### ISSUE TITLE
 Nunit console behaving differently then NUnit GUI (Version 2.6.3)

### ISSUE THREAD

**Issue by prashantc23** [nunit/nunit#2193]
we have configured tests to look for dlls (used by Test Assemblies) in specific directory (relative to current directory) using 'DLLImport'. When tests are executed from Nunit GUI (nunit-x86.exe) it looks at the specific directory for the dlls (verified using procmon) but when tests are executed using NUnit Console (nunit-console-x86.exe) it only looks at the specific directory if it does not find them in current directory. so behaviour between gui and console is different. Is there any way to configure NUnit console to look for dlls (referred by assemblies being tested) in specific directory?

**Comment by rprouse** [comment]
Sorry that nobody has responded, but very few people here are using NUnit 2 anymore. I hope you found a workaround, but I am going to close this because nobody was able to answer your question and we are not making updates to NUnit 2 anymore.

If you have anything further to add, just post here. We will see it.
