### ISSUE TITLE
Question about Randomizer.NextEnum(Type)

### ISSUE THREAD

**Issue by jp2masa** [nunit/nunit#2207]
Randomizer.NextEnum(Type) currently [gets the next int in range \[0, enums.Length\[](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/Randomizer.cs#L491), and enums.Length is the total number of declared elements in an enum. But there are elements with the same value, so the `enums` array can have duplicate values, resulting in higher chances for some enum values of being returned.

From [MSDN](https://msdn.microsoft.com/en-us/library/system.enum.getvalues(v=vs.110).aspx#Anchor_2):
> The GetValues method returns an array that contains a value for each member of the enumType enumeration. If multiple members have the same value, the returned array includes duplicate values. In this case, calling the GetName method with each value in the returned array does not restore the unique names assigned to members that have duplicate values. To retrieve all the names of enumeration members successfully, call the GetNames method. 

Example:
```cs
enum Test
{
    A,
    B,
    C,
    D = 2
}
```

Calling `Enum.GetValues(typeof(Test))` will return 4, so the values 0 and 1 have 25% chance each of being returned, while the value 2 has a 50% chance of being returned.

Is this the expected behaviour?

**Comment by jnm2** [comment]
I had the same question, as well as a question about what happens if you apply `[Flags]` to the enum.

For non-flags, I'd lean towards randomly picking out of `GetNames` and then looking up the value for the chosen name.

For flags, I'd lean towards ORing everyvalue together and using that as a mask over 32 random bits (or whatever the bit size of the enum is).

**Comment by CharliePoole** [comment]
Yes, this is as designed.

Randomizer is used in NUnit in two ways: to generate test cases and to allow users to get random values from the TestContext. It simply wraps Random and adds type safety plus the ability to get repeated runs with the same random values. That seems like a big enough job for a class. 😄 

When used with non-numeric types, the notion of randomness is little more than metaphoric. We do our best to generate a bunch of test cases for chars, strings, bytes and byte arrays, for example, but the user is likely to have certain values they want to test as well. For enums, we simply generate the underlying values, but I have to say that I was dubious about adding that feature. I can't think of a case where I would __not__ want to control precisely which values of an enum I wanted to use in my tests. Flags enums are not handled specially at all and I don't see much value in it for the future.

Hope this helps.

**Comment by jp2masa** [comment]
So it's by design that values declared by the most enum elements have a higher chance of being returned?

**Comment by CharliePoole** [comment]
It's more by not-having-given-it-much-thought... i.e. we implemented what somebody asked for. It works well in some uses, not in others. Perhaps something is needed in the docs.

If you want us to change how it works, feel free to file an issue with a proposal. But you will have to come up with a strong rationale, since random numbers are really not normally intended to apply to things like enumeration. One possibility is for us to supply some way for users to extend this.

Do you have a particular use case in mind?

**Comment by jp2masa** [comment]
No, thanks for the help.
