### ISSUE TITLE
BadImageFormatException when using NUnit with Accord.Video.FFMpeg

### ISSUE THREAD

**Issue by Jammy1986** [nunit/nunit#2210]
Hi, I'm getting a bizarre error when I try to use the Accord library with NUnit. I've attached a project demonstrating the problem. 

I added the Accord.Video.FFMpeg and NUnit packages using NuGet. If I use the microsoft.visualstudio.testtools test runner to get the type of a class in the accord package, then the 'test' passes, but if I use the NUnit test runner to do the exact same thing, then it throws a BadImageFormatException.

[NUnitAccordComboTest.zip](https://github.com/nunit/nunit/files/1045512/NUnitAccordComboTest.zip)

**Comment by CharliePoole** [comment]
I assume you mean this for the nunit 3 visual studio adapter?

Where is the accord video dll relative to the test assembly?

**Comment by Jammy1986** [comment]
Sorry, I'm not sure if this is for the nunit 3 visual studio adapter, if that's the NuGet dependency then no, I'm just using the plain NUnit dependency.

Assuming the test assembly is the built version placed in bin/Debug, then the dll is also placed in that directory.

I'm using Visual Studio 2015 if that helps.

**Comment by rprouse** [comment]
Is the `Accord.Video.FFMpeg` assembly compiled x86 or x64 as opposed to AnyCPU? If so, your tests should also target x86 or x64.

Also, how are you running your tests? Are you using `nunit3-console.exe`?

**Comment by Jammy1986** [comment]
Ahah, progress!

So if I choose x86, I get instead a FileNotFoundException.

I was trying both Rider, and Visual Studio, running the test by right clicking, and selecting 'Run Unit Tests'. However when trying just now, I noticed that Visual Studio actually has two options for running tests (unfortunately I can't upload an image for some reason). The first option reads 'Run Tests' instead of 'Run Unit Tests' and has a small green play button next to a partially full beaker instead of a large green play button.

I have never noticed or tried the first option, it doesn't recognise the NUnit test unless I also install the NUnit3TestAdapter using NuGet. Once I do this, the test runs as expected and produces no exceptions... I can't get it to run in Rider, but I guess this is because it has only implemented the second test run option, and not the first one?

**Comment by CharliePoole** [comment]
What is Rider?

**Comment by Jammy1986** [comment]
https://www.jetbrains.com/rider/

**Comment by CharliePoole** [comment]
We don't have any info about how Rider works. This is unsurprising, since we have never had any information from JetBrains about how Resharper interacts with NUnit. 😞 Obviously, they have not contacted us about how their new product will work with NUnit either.

From reading their published info, they seem to be competing in the same space as VS, but on a cross-platform basis. Sounds like a great idea! So perhaps looking at VS can tell you something.

Visual Studio has supported a notion of a "unit test" as a special kind of project for years. When the "unit test" language is used they generally mean that type of project, which involves use of MSTest exclusively as the testing framework.

Beginning with VS 2012, they introduced the Test Explorer window, which allowed integrating tests written against multiple open-source testing frameworks, like NUnit. Those projects are normal class libraries and are run from the test window - the green button you noticed - provided a special adapter is installed for the framework in question. NUnit provides the NUnit and NUnit 3 VS adapters for that purpose and that's the only way to get Visual Studio to run NUnit tests internally. Of course you can run them externally by setting up your Debug target to run the nunit console.

So in the case of Rider, I think you may have to wait and see to what extent JB will emulate the VS IDE versus their own R#, which does magically run NUnit tests from the source.

It sounds like your original problem is resolved, however. 😄

**Comment by Jammy1986** [comment]
Ah, thanks for the explanation that makes a lot of sense! I'll file a bug report with the Rider team to look into integration with NUnit. 

As for visual studio (not that it really matters), but do you have any idea why the test even runs with the other 'Run Unit Tests' option? I notice this option disappears when I remove the [Test] attribute, so what exactly is running (and consequently failing)? Is this a visual studio bug?

**Comment by CharliePoole** [comment]
I can't find that option on the system I'm using right now. If memory serves, it may only be on paid product versions. What are you using and where does it appear?

**Comment by CharliePoole** [comment]
Or are you running R#?

**Comment by Jammy1986** [comment]
Linkback, logged this issue here: https://youtrack.jetbrains.com/issue/RIDER-6929

**Comment by Jammy1986** [comment]
Yes I'm running ReSharper, it would make sense to come from there. Thanks for all your help. 👍
