### ISSUE TITLE
Assert.IsTrue - Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by markvantilburg** [nunit/nunit#2223]
Using v3.7.0/v3.7.1 from nuget.

This code does result in "Object reference not set to an instance of an object."

```
using NUnit.Framework;

namespace ConsoleApplication2
{
    class Program
    {
        static void Main(string[] args)
        {
            Assert.IsTrue(false,"error value is not true");
        }
    }
}
```

In version 3.6.1 This results in "Additional information:   error value is not true
  Expected: True"

Is this an intended breaking change?

**Comment by rprouse** [comment]
The change was intentional although I doubt we considered usage of the asserts outside of tests. The change in question was part of making our `TestExecutionContext` more thread safe. The old code did lazy instantiation of the `CurrentContext` (if null create a new one and return it) whereas the new code sets the current context as tests are being executed.

The asserts use the `TestExecutionContext.CurrentContext` to do things like capture output from the tests, increment the assert count and report results in a thread safe manner. With the old code, you were never informed about the incorrect usage and that information was lost. New features like Warning level asserts also would not work.

If you want to use the asserts outside of tests, then you need to create a `TestExecutionContext`. 

```C#
var context = new NUnit.Framework.Internal.TestExecutionContext();
context.EstablishExecutionEnvironment();
Assert.IsTrue(false, "error value is not true");
```

As you can see, this is NUnit internal code, so not a supported usage and more code will be needed if you are asserting on other threads, using warnings, etc.

Can you explain your use case that caused you to raise this issue? I am going to mark this issue as a question for now until we understand your usage.

**Comment by markvantilburg** [comment]
We test a "asp.net web site ( https://msdn.microsoft.com/en-us/library/dd547590(v=vs.110).aspx )" using the nunit framework, simply created some pages which contains methods to check if the right values are returned (which in turn are checked by Selenium checks to see if tests fail). 

Web site projects do not support unit tests and are much of a relic from the past. New projects are usually "asp.net web application" which has support for unit tests.

**Comment by rprouse** [comment]
I am going to close this as a question. If you have more questions, please comment, we will see them.

**Comment by vmachacek** [comment]
I have a question - how can I get currently running test and fail it from another thread? I have Playwright test which thru selenium registers callback to C# test run. And in this callback I need to fail the test.

**Comment by stevenaw** [comment]
@vmachacek It's difficult for the team to respond appropriately here as your question has been made in a closed issue.

Would you be able to please open a new issue and include a runnable code sample repro of what you're trying to do? It would be helpful to include version info about NUnit and any other dependencies too. You may want to make a PR into our issues repo as an easy way of sharing it all (http://github.com/nunit/nunit.issues/)
