### ISSUE TITLE
Need a special attribute to identify test assemblies that use NUnit indirectly

### ISSUE THREAD

**Issue by copypastedeveloper** [nunit/nunit#2230]
I wrote a [bdd framework](https://github.com/copypastedeveloper/given) a while back and one of the supported testing frameworks was nunit.  I recently decided to update it for the first time in quite a while and make it compatible with nunit 3.x.  What I'm noticing now is that when my (abstract) base class that has a `TestFixture` attribute is in a different assembly it seems to not get picked up on by the nunit runner.  

A simple example is [here](https://github.com/copypastedeveloper/given/blob/master/Given.NUnit.Example/when_building_a_toyota.cs).  The class `Scenario` that is being inherited from is located in the [Given.NUnit project](https://github.com/copypastedeveloper/given/blob/master/Given.NUnit/Scenario.cs)/assembly and is marked with the `TestFixture` attribute.  

This definitely worked in 2.6.3, the last version I had used previously.  Any ideas as to why this isn't working, or is this just not supported anymore?  I can work around it by inheriting from the `Scenario` class in each test project and marking it with `TestFixture` and then have all my tests inherit from that base instead, but I'd prefer not to have an empty class sitting around in each test project.

**Comment by CharliePoole** [comment]
Rather than "supported" in the past, I would have to say it "just happened to work." 😞 Neither NUnit V2 nor 3 was designed with much thought for cases where NUnit itself was not being used directly.

The NUnit 3 engine, which runs tests, looks at the test assembly in order to decide what framework it uses. It does so by calling all the installed framework drivers, asking "Can you run this?" We provide drivers for NUnit 2 and NUnit 3 but anyone could write a driver for some other framework. In the case of the NUnit 3 driver, the rule that is used is "Has a reference to nunit.framework with version >= 3."

There is a hard way and an easy way to deal with this:

1. Write a driver for the engine, distribute it to your users and tell them to install it. This is probably rather inconvenient for the users as well as requiring some work on your part.

2. Tell your users to make at least one reference to NUnit in their test assemblies. Note that this means more than just adding an assembly reference. Something actually has to be used in order for the reference to appear in the test assembly metadata. Any assertion or attribute would work, so long as it actually appears in the __user__ assembly. You could also tell users to add some assembly level attribute.

Some time back, we discussed creating an attribute just for that purpose - something like `[UsesNUnit]`. We didn't do that because we realized that any existing attribute could serve the same purpose. For example: `[Description]`, `[LevelOfParallelism]`, `[Parallelizable]`, '[NonParallelizable]`.

To avoid confusing users, I would suggest just telling them what to add rather than explaining the entire problem to them.

In a future release, we could add some special attribute for use with frameworks like yours. Or we could introduce some other way to recognize a framework based on NUnit, preferably without enumerating all the references your assembly contains. Any ideas?

**Comment by copypastedeveloper** [comment]
I'm honestly not familiar enough with all of the cases you guys have to optimize for.  I see you're using Mono.Cecil to inspect the IL and get the references, which explains why you don't see references without them being used.  I'm fine with the `[Description]` attribute idea mostly, but it might be nice to have an attribute that doesn't need anything passed in.  I personally prefer the idea of an `[NUnitAssembly]` attrirbute that inherits from description and just passes in something like 'NUnit Testing Assembly'.

Just out of curiosity, what made you all decide to use mono.cecil rather than loading the assembly and scanning for types and references?

**Comment by CharliePoole** [comment]
To load the assembly in the same process as the engine for inspection, we had to create and we unload an AppDomain. In addition, we could not load any assembly that was not compatible with the current runtime.

Of course, use of Mono.Cecil versus System.Reflection doesn't affect this issue one way or another. In either case, we would not see the reference.

Since you know the workaround already, I'm converting this issue into a feature request for `[NUnitAssembly]`.

**Comment by CharliePoole** [comment]
I'm in favor of @copypastedeveloper 's suggestion:

```C#
public class NUnitAssemblyAttribute : DescriptionAttribute 
{
   ...
}
```

It will be easier for third-party framework developers in this position to tell their users to use this attribute rather than telling them to use "some" attribute.

@copypastedeveloper Please consider using `[NonTestAssembly]` on your own assembly.

**Comment by jnm2** [comment]
@CharliePoole This may or may not be related like it was to https://github.com/nunit/nunit/issues/2163, but I think NUnit should discover test classes and methods which have attributes applied which inherit from TestFixture and Test, even though the test assembly itself does not directly reference NUnit.

If we agree and fix that, it may remove the need for an `NUnitAssemblyAttribute` for everyone or at least for some.

**Comment by copypastedeveloper** [comment]
Well, yes, obviously checking assembly  tyoes for attributes would be
ideal, but it seems like the point at which the engine makes the decision
is before the assembly is loaded into an app domain, so that level of
inspection isn't possible.  I could be wrong, I formed that opinion after
about 30 minutes of looking at the code.  :)

**Comment by jnm2** [comment]
Right, so to obtain the ideal outcome, we'd either check each test assembly's references recursively for NUnit before loading into an AppDomain and doing further checking to see if it is a test assembly, or we'd just always load it into an AppDomain and do further checking to see if it is a test assembly.

Actually checking references recursively is really simple and can be implemented quite efficiently, so that would be an optimization before doing more examination in an AppDomain to see if it is a test assembly.

**Comment by CharliePoole** [comment]
@jnm2 By default (and I think preferred usage) we run tests in a separate Process. Before setting up the process, we have to inspect the assembly to see what kind of process we will set up. In the general case, we have to allow for that process having a different runtime target and a different platform from the one we are on. In the future, it will be worse, since we will want to run on devices. 

That's why we need a very general way to examine assemblies, without loading them. Mono.Cecil was the simplest way to go. The alternative, which I had previously done, was to read the dll as a file and search for various flags, etc. inside it.

Doing a recursive check using Mono.Cecil is tricky but possible. We would have to figure out where the dependent assembly is and add create a path form mono.cecil to be able to find it. But what is the payback? It merely avoids one attribute being added by the user. All users pay a performance penalty for our recursively searching the references. It's an interesting problem but that's not a reason to do it.

In fact, if we were going to do anything more than coach the users, I would suggest giving the third-party guys some attribute to use that told us to use the nunit 3 framework driver.

BTW, not that it's either here or there, but we have already refused to do anything about this multiple times in the past. The attribute for users to use seemed to me like a big concession! 😄

**Comment by jnm2** [comment]
This just academic but I'd be interested to see which is actually less of a performance penalty, using Mono.Cecil to parse the IL or ReflectionOnlyLoad in a temporary AppDomain, and by how much.

The payback is that test frameworks like in https://github.com/nunit/nunit/issues/2163 that use NUnit underneath can stop being leaky abstractions. For what my personal instinct is worth, I'll always see the need for `NUnitAssemblyAttribute` or `DescriptionAttribute` as dirty and as a failure on our part.

**Comment by CharliePoole** [comment]
I'm somehow not being clear. It is __not possible__ for us to use Reflection in all cases because the engine is expected to examine assemblies that could not be loaded and/or run in the current process.

I guess one has to also ask if building abstractions on top of NUnit is something we want to support. I don't know that. It was never thought about in the past an we have never discussed it.

Supporting abstractions built on top of NUnit is not a goal of ours. It has never been proposed as a goal or discussed as a goal. I'm not saying I'm against it, just that it has to become one of our goals and be prioritized against other goals before we just jump to implementing anything serious. Creating an attribute is about all I would be willing to commit to without that discussion. Anyone, user or dev, is able to propose such a thing. But just jumping to it adhoc seems equally "dirty" to me.

A serious discussion of the topic - not here please - would involve identifying the kinds of extensions or abstractions over NUnit that we want to support versus those we don't want to support.

That said, it's hard for me to imagine that helping people write better frameworks on top of NUnit would take precedence over the rather long list of high-priority bugs, enhancements and new features we are not getting done for our actual users right now. When resources are short, compromise is needed.

And anyway, I'm pretty sure that the next step up from a user attribute is an attribute for the package-writer. That would tell us directly "I'm standing in for NUnit." We can't really assume that every assembly referencing an assembly that references nunit is a test assembly.

**Comment by CharliePoole** [comment]
@nunit/framework-team We're talking around this because nobody has actually added it to the backlog, much less self-assigned it. If we decide to fix it in the engine rather than as I proposed, then the issue should be moved there and the title changed.

**Comment by ChrisMaddock** [comment]
This issue has come up a few times. If it's possibly to fix it via recursive inspection of references, I'd be in favour of that over a special attribute, as that's the closes path to 'just works' for the user. That of course relies on someone being willing to implement such a thing!

**Comment by jnm2** [comment]
> That of course relies on someone being willing to implement such a thing!

Me 😈

**Comment by jnm2** [comment]
@CharliePoole I like to keep a clear delineation between "this is a direction we like in isolation" and "this is worth prioritizing over other work." They are separate conversations. If a design is agreed upon, it can sit on our backlog and be up for grabs if a passerby has a motivation to implement it. And if we determine we want it next year, we don't have to start the design conversation from square one.

**Comment by rprouse** [comment]
If we go with the recursive inspection, the graph for .NET Core applications can be quite large, so we should probably optimize it a bit. We need to keep track of assemblies that have already been visited and not revisit (probably obvious, but putting it out there) and we might want to skip dependent assemblies that start with `System.` or `Microsoft.`.

Might we also only want to walk out one level deep? My thinking there is that the most common use case is a base test framework that users derive all their tests from. This might be more dangerous though.

I expect that we can make the discovery fairly quick, but we need to handle the worst case scenarios like solutions with hundreds of projects.

**Comment by CharliePoole** [comment]
Remember also that Cecil has to read __every__ assembly you inspect into memory. This sounds to me like one of those things developers do because it's a cool challenge, without a strong payback. Projects that do things on that basis sometimes end up with fragile code - although I'm sure we could do it well if we did it.

The attribute is not elegant, but it's trivial.

Another approach is for the framework designer to create something in their framework that ends up forcing a reference to NUnit to be added. Could be something derived from NUnit or returning an nunit Type or taking one as an argument.

The third option is to simply create a framework driver and tell the users to install it.

A fourth option is for us to provide a way for such frameworks to register themselves with NUnit and be recognized.

THis is not the first time the issue has been raised, but the last time was about a year ago.

**Comment by jnm2** [comment]
Cecil doesn't provide a fast forward-only stream reader? I'm still fairly sure it could perform on par.
Can we at least experiment with that option before deciding on the less elegant option?

> Another approach is for the framework designer to create something in their framework that ends up forcing a reference to NUnit to be added.

References in .csproj are now transitive and I think it's a good mental model to be consistent with.

> The third option is to simply create a framework driver and tell the users to install it.

This would be my preference second to the elegant solution. However I think we have what may genuinely be considered a flaw: If `FancyFixtureAttribute : TestFixtureAttribute` and I'm referencing the assembly containing `FancyFixtureAttribute ` but not the NUnit framework assembly containing `TestFixtureAttribute`, and I use `[FancyFixtureAttribute]` on classes in my test assembly, I'd expect the NUnit engine to notice that I was using a `TestFixtureAttribute` even though it is a more derived instance.
Currently, it won't. Fixing this mental model inconsistency would actually be the same as implementing the aforementioned elegant solution.

**Comment by CharliePoole** [comment]
It's absolutely a flaw, but it's a fairly obscure flaw. You can use FancyFixtureAttribute from your separate assembly very happily and the NUnit framework will figure it out __unless__ you don't use any other NUnit attributes, assertions or other references. 

This is not something that users generally do unless they use a third-party framework that makes them do it. Third party devs can fix it easily and I have no problem making them do something inelegant if it helps their users. There is also an equally inelegant workaround that the users can put in while waiting.

In many cases like this in the past, we have done a quick fix and then gone on to do the better, longer-term solution at a later time. That's what I tried to do here. There is basic flaw in how we decide what driver to use. Knowing that fixing it would take a lot of time and effort from one of us, I created __this__ issue to describe the quick fix.

The fundamental issue is that drivers need to be responsible for deciding what they need to know in order to say that they can work with an assembly. That is only partially true in the current code. It's a long-standing problem that nobody has had time to fix and I can't see that changing soon.

I think we need the quick fix. I don't think it's a bad thing to do because it gives us a fallback whenever the algorithms in the drivers cause no framework or the wrong framework to be selected.

Are you arguing against a quick fix here? If you are simply trying to discuss the longer-term problems in the engine, let's figure out a way to do that without holding up fixes on bugs that we can get done in a matter of hours.

**Comment by jnm2** [comment]
Implementing the 'elegant' solution took about twenty minutes:
https://github.com/nunit/nunit-console/compare/master...jnm2:try_searching_deeper_references

**Comment by CharliePoole** [comment]
@jnm2 Knowing you, I'm not surprised. But when was it ever about whether you knew how to code it or how long it would take you?

Here's my two cents. If you have a strong opinion about how something should be done, then assign yourself the issue. In my book, that gives you extra credibility in how you implement something. I'm afraid I have shown my impatience too much in these abstract discussions we are having, for which I apologize.

I see two questions we have to answer to end the discussion... the same two we have had all along...
1. Do we want to implement the special attribute or a depth search? Or both?
2. Do we want to implement a solution that applies to all frameworks or just to nunit 3?

**Comment by rprouse** [comment]
> Do we want to implement the special attribute or a depth search? Or both?

I would be okay with a depth search provided it is fast. @jnm2 your code looks good, mind adding a stopwatch in there and possibly testing something with a lot of references like an ASP.NET Core project?

> Do we want to implement a solution that applies to all frameworks or just to nunit 3?

Personally, I think it is up to each driver to determine if it can run tests on an assembly in whatever way it sees fit. Technically, it may not even be related to references.

**Comment by CharliePoole** [comment]
Exactly. The bit about the driver is what I was calling the fundamental flaw. I'd like to see that fixed rather than adding additional code into the DirectRunner, which is assuming it knows how frameworks work.

**Comment by jnm2** [comment]
Ah... now that has sunk in, I'm with @CharliePoole. This isn't an ideal fix unless we can push it to the driver. I don't want the engine to be responsible for this.

And that is certainly not a quick fix, so if someone is having pain, let's do the band-aid fix.

**Comment by jnm2** [comment]
@CharliePoole complete aside. I'm catching myself rushing through and squeezing time to do this between other tasks, but not realizing that the effect is that I'm not spending the time to fully understand everything I read. I'm sorry. That can't be coming across well. I am making an effort to be more thorough.

**Comment by CharliePoole** [comment]
@jnm2 No problem, I'm just grumpy.

But seriously, I do have the impression you are going broad rather than deep. Which I count as too bad, because I think you could go very deep indeed, and we need depth.

**Comment by rprouse** [comment]
> I'm not spending the time to fully understand everything I read.

@jnm2 No worries there, I've been doing the same thing lately. Last night I sat down to over a hundred GitHub issues that I hadn't read, most with many comments. I misread or misinterpreted several as I was trying to catch up 😦

**Comment by jnm2** [comment]
Now of course the band-aid fix *could* be to put this recursive reference search in, but only have it apply to the NUnit 3 framework driver and keep the other drivers as-is. Then at our convenience we can move the responsibility which will require an API change to do cleanly.

**Comment by CharliePoole** [comment]
If we were sure that nobody else is using the driver API, we could just change it. We would need to modify our two drivers.

Otherwise, we have to maintain the old interface and create a new one beside it like you do in COM and we did in V2 for ISuiteBuillder.

My guess is that we would know if someone had actually published a driver, but someone could be working ion one without our knowledge. I'd take the chance and change it.

**Comment by CharliePoole** [comment]
If we were sure that nobody else is using the driver API, we could just change it. We would need to modify our two drivers.

Otherwise, we have to maintain the old interface and create a new one beside it like you do in COM and we did in V2 for ISuiteBuillder.

My guess is that we would know if someone had actually published a driver, but someone could be working ion one without our knowledge. I'd take the chance and change it.

**Comment by CharliePoole** [comment]
@rprouse What do you think? Is the driver API still flexible at this point? Or do we need to maintain it?

**Comment by CharliePoole** [comment]
FWIW I made the API work as it does because I didn't want to repeat the reflection in every driver that is tried out before one is found. No doubt that was premature optimization.

**Comment by jnm2** [comment]
I don't like repeating reflection either. We could still calculate the transitive closure of references, assuming that any driver would likely find that interesting, and hand that to each driver along with the assembly file location in case the driver wants to do additional examination.

**Comment by jnm2** [comment]
Even better, pass two enumerables, one for direct references and one for all transitive references. If no driver enumerates them, no work is done. If one driver enumerates, the contents (as far as it has gone) are cached in case the next driver enumerates so that the work is done no more than once. I have code sitting around that does this.

What we should probably do is pass an args object to prevent future breaking changes when we add things. The old EventArgs pattern. EF Core started using this for their dependency injection because signatures broke every time they added a dependency to a base class.

```c#
public sealed class DriverResolutionArgs
{
    public string AssemblyPath { get; }
    public IEnumerable<AssemblyName> DirectReferences { get; }
    public IEnumerable<AssemblyName> AllTransitiveReferences { get; }
}
```

**Comment by CharliePoole** [comment]
Good ideas. Let's wait for @rprouse 's view on changing versus doubling up on the API.

**Comment by jnm2** [comment]
Too bad we can't drop Mono.Cecil and reference https://www.nuget.org/packages/System.Reflection.Metadata/. I did a proof of concept for something unrelated at work and memory-mapping the assembly files and reading the assembly reference list is insanely fast. Problem is the NuGet package only works as far back as net45 (and netstandard11).

**Comment by rprouse** [comment]
I am okay with changing the driver interface at this point. Nobody has asked about or mentioned writing a driver in issues or in the mailing lists, so I doubt anyone has. It would also be a fairly easy update for people to change their driver to take in the extra arguments even though they don't use them. I think that the API we need to guard more religiously is the Engine API.

I actually wish we could remove the `AppDomain` from the driver because I think that should be the responsibility of the driver, possibly by passing in a settings collection. I say this because AppDomains aren't supported on several platforms or in .NET Standard/Core.

As for dropping Cecil in favor of a library supplied and maintained by Microsoft, I would love that too, but as you say, it is only good back to net45 ☹️

**Comment by CharliePoole** [comment]
Note that we are not actually talking about the driver interface here but the factory interface. For practical purposes, it has the same effect. I always expected to change this... just much sooner!

**Comment by CharliePoole** [comment]
The new interface should be as general as our runner, driver and framework interfaces. The driver should be the only place that knows the string representation of test container is actually an assembly with references etc. IMO, the factory interface should not depend on that.

The key issue is how to avoid each factory separately loading assemblies and finding references. That's why I preferred to avoid recursive references if possible. However, it makes sense to me to stop worrying about that performance issue and implement something of the desired shape first. For the moment, performance is hardly an issue, since there are only two existing framework drivers.

**Comment by CharliePoole** [comment]
@jnm2 You're correct about AppDomains but for the moment it's a necessary evil - one I'd like to make unnecessary and then remove. Drivers have no access to the services of the engine, so they cant create domains in the way we would prefer to see them created. Otherwise, they could just use a setting.

In fact, I think giving drivers a ServiceContext is the first step needed to move to a better interface. I did the same thing with Runners early on - that is, they originally didn't know about services but later needed them.

**Comment by CharliePoole** [comment]
@nunit/framework-team Here's another one of those issues where we have discussed three or four alternative features. It seems clear we are not going to do the one that's suggested by the title. Perhaps it would be clearer to close this.

**Comment by tgrossen** [comment]
Since this issue hasn't been marked as closed (not sure if just unintentionally left open or not), I thought I'd ask if there is an update on this. Particularly, I'm wondering if there is an Attribute or other method to indicate I'd like to search recursively for assertions, as I generally like to abstract my assertions into extension methods. I've traversed a number of issues just finding this one and it seems closest to what I'm trying to accomplish, so I'm just checking in to see if there is an update.

**Comment by CharliePoole** [comment]
This issue (which I advocated marking as closed in my prior comment) deals with visibility of Attributes. You are, of course, interested in assertions rather than attributes but both of those end up translating to your test assembly having reference to the NUnit framework.

So, here's the thing... in order to add an attribute to your actual tests, indicating that a recursive search should be used, you would need to reference the assembly in which that attribute is defined, i.e. the nunit framework assembly. But right now, that's all you actually have to do in order for your test assembly to be recognized. That's why we have never added such an attribute.

@nunit/framework-team I'm still in favor of closing this.

**Comment by rprouse** [comment]
I am closing old Idea issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
