### ISSUE TITLE
System.Runtime.Loader not available for iOS/Android

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#2237]
I'm not 100% clear on the latest NuGet behaviour - so would appreciate a second opinion on the below. This is what I think is going on in https://github.com/nunit/nunit.xamarin/issues/87.

Out .NET Standard 1.6 build relies on System.Runtime.Loader 4.3.0. If you unzip that NuGet package, the structure looks like this:

```
lib -> netstandard1.5    -> System.Runtime.Loader.dll
          net462         -> _._
          MonoAndroid10  -> _._
          MonoTouch10    -> _._
```

When this package is installed into an Android project (and I assume .NET Framework 4.6.2, or iOS also) - NuGet resolves to look in the `MonoAndroid10` directory, and finds the `_._` (and fails). As I understand (although I can't find anything official on the matter) - this is used as a placeholder, when an API isn't supported on a certain platform yet. See below:

https://github.com/dotnet/corefx/issues/8965#issuecomment-287138692
https://github.com/dotnet/corefx/issues/11023#issuecomment-244131549

If I'm understanding the above correctly, then our .NET Standard 1.6 NuGet package won't actually work for iOS, Android, or .NET 4.6.2. I'd assume we're only just discovering this as .NET Core is unaffected, which I imagine is the main use of the .NET Standard builds.

As a potential solution, perhaps we could package the NET Standard 1.3 build of NUnit (which _doesn't_ rely on System.Runtime.Loader) under a `monoandroid` directory in our NuGet package. (And of course additionally for the remaining affected frameworks.) Project.json unfortunately seems to ignore such subdirectories (unlike packages.config, which recognises them...) - but I wonder if that's the same issue we saw in https://github.com/nunit/nunit/issues/2165, which would be fixed by adding an empty dependency group for MonoAndroid etc. Not sure.

It's only the latest Android framework which pulls in .NET Standard I believe, which I imagine is why we didn't see this issue when Rob first created the .NET Standard 1.6 build. Unfortunately, unless someone knows a way to force project.json to look in a particular subdirectory for it's dependency, I think this could potentially be critical for both NUnit and nunit.xamarin.

**Comment by ChrisMaddock** [comment]
Reopening after a couple of hours more digging. Would appreciate a sanity check!

**Comment by ChrisMaddock** [comment]
I missed a bit.

The other potential solution in my eyes would be to drop the System.Runtime.Loader dependency. I'm haven't looked in to what relies on it, but if we can do without it for .NET Standard 1.3, perhaps we can here as well. That way, our .NET Standard 1.6 build would be closer to actually being .NET Standard. 😤 We should probably check the other dependency, and what that _actually_ supports at the same time...

**Comment by ChrisMaddock** [comment]
Ah, I found another reason we didn't see this before.

Between 3.6.1 and 3.7 - the version of the System.Runtime.Loader package was upgraded from 4.0.0 - 4.3.0. The former didn't include the 'placeholders' for MonoAndroid, the latter did. I wonder if it previously used to crash at runtime. :-/

https://github.com/nunit/nunit/commit/24c66b96bfdc6d81f8e196ae7e8e17de57f6940c#diff-ffc083106f0fb9a9c5b7faf1292fb6ecL33

**Comment by jalbertSyncroTech** [comment]
When upgrading our nunit.xamarin Android test projects from NUnit v3.6.1 to v3.7.1 I'm now getting this error with the latest stable VS2017:
`Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Perhaps it doesn't exist in the Mono for Android profile?`

I *did* get this error with previous NUnit versions, but the workaround I had been using is no longer working: We're using the new .csproj based <PackageReference> tags for NuGet in our projects, so I added an explicit NuGet reference to the "System.Runtime.Loader" package but with the additional ExcludeAssets All setting.  This satisfied NuGet but excluded the System.Runtime.Loader assembly from the actual build.  I verified that the relevant NUnit Android code didn't actually use System.Runtime.Loader so there wouldn't be any runtime issues.
`<PackageReference Include="System.Runtime.Loader"><ExcludeAssets>All</ExcludeAssets><Version>4.0.0</Version></PackageReference>`

This means until this issue is resolved we're stuck at the NUnit v3.6.1 release.

**Comment by jalbertSyncroTech** [comment]
I was able to get past the compile error by removing m ExcludeAssets work around, but this triggers the runtime error I had been getting previously with v3.6.1 without the work-around:
`06-14 15:35:46.296 F/monodroid-assembly( 3201): Could not load assembly 'System.Runtime.Loader' during startup registration.`
`06-14 15:35:46.296 F/monodroid-assembly( 3201): This might be due to an invalid debug installation.`
`06-14 15:35:46.296 F/monodroid-assembly( 3201): A common cause is to 'adb install' the app directly instead of doing from the IDE.`

**Comment by ChrisMaddock** [comment]
Been looking at this recently - what I'm trying to do to resolve this is use the .NET Standard 1.3 build for Android.

At the moment, I'm struggling to package appropriately to support all of packages.config, project.json and PackageReference. :-/ I've filed an issue with NuGet, over getting project.json to chose the correct build here: https://github.com/NuGet/Home/issues/5759

@jalbertSyncroTech - I haven't yet done much testing with PackageReference. Would you be able to try out the NuGet package in the zip below, and see if that works for your project? If so - we can get that into NUnit 3.8, and fix it for 2 out of the 3 versions of NuGet at least! 😆 

[AndroidVsNetStandard.zip](https://github.com/nunit/nunit/files/1228050/AndroidVsNetStandard.zip)

**Comment by jalbertSyncroTech** [comment]
Thanks for the update Chris!  The new package worked fine, I was able to install it, build, and run our Android tests successfully, and I read the Assembly Version back out just to verify it was in fact running with v3.8.  I should point out that I just upgraded to VS2017 15.3 yesterday, which also updated NuGet to v4.3 and Xamarin Visual Studio to v4.6.

**Comment by ChrisMaddock** [comment]
Thanks @jalbertSyncroTech. In that case, I'll PR this change at some point - which mean Android will work with packages.config, and PackageReference - so it's just project.json which is still an issue!

**Comment by ChrisMaddock** [comment]
I've got the package working for all NuGet 2.x-4.x...turns out it was a caching issue. 🙄 

There's one last issue I want to check - which is whether the System.Threading.Thread dependency used for DelayedConstraint and such will cause a runtime error on Android, or if that dependency is satisfied by the platform or something. What I'm currently unsure of, is why the System.Runtime.Loader dependency fails the compatibility check in NuGet 3.x, but System.Threading.Thread does not - so I just want to double check that all dependencies are actually satisfied, while we're here.
