### ISSUE TITLE
Running tests directly should never surface a NullReferenceException

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2242]
We're gathering a few bug reports around this issue. People try to manually run or debug an NUnit test and get a NullReferenceException. This sends the message to the user that this is a bug we do not know about. It would be better if we surfaced an exception with a helpful message getting the user on the right track.

Even better than that, I wish we could fall back gracefully and continue. That is going to be the user's expectation and it allows conveniences during development such as ad-hoc debugging into a test on F5 like what's manually done here:

```c#
public static class Program
{
    public static void Main() => new TheFixture().TheTest();
}

[TestFixture]
public sealed class TheFixture
{
    [Test]
    public void TheTest() => Assert.That(...);
}
```

**Comment by CharliePoole** [comment]
@jnm2 I had two reasons for the change of title:

1. The method is not actually being called through an API here. Of course, to be precise, Assert is an API, but that's not how we describe it when we tell people there are three APIs for running tests in the docs.

2. It's usually better to put issues in terms of the problem space rather than the solution space - i.e., the internal TestExecutionContext. Of course, our users are also programmers, so that makes it tricky.

**Comment by CharliePoole** [comment]
@jnm2 In our discussion about this you had raised the issue of figuring out how we were called and actually running successfully, rather than giving an intelligent error message. Have you given up on that?

**Comment by jnm2** [comment]
@CharliePoole 
> Have you given up on that?

Not if you think the idea has merit! 😃

**Comment by CharliePoole** [comment]
@jnm2 If you haven't already noticed :smiley: I'm big on JIT. I think this idea has merit but I don't know if it's feasible. If I decided to work on this, that point in time would be just-in-time for figuring out what's possible to do here. I'm just saying that we won't know until somebody takes on the issue.

Here's a bit of agilist propaganda for you...

One of the stated values of XP is Courage, which is taken to mean confidence in our skills and in being able to work things out as needed. Because of Courage, we don't have to plan things out in detail ahead of time, which we know doesn't work anyway. Of course, if your level of Courage doesn't match your actual abilities, you're toast. :smile:

Anyway, yes, I think someone taking this on should look beyond the title and see if there is anything that can be done to make it work without bastardizing the code to much.

**Comment by jnm2** [comment]
@CharliePoole I had given up on convincing the team because of the last few discussions we've had a while back. In that case, since that would be the preferred fix and I think it'll be conceptually on the same order of difficulty, I'll shoot for that first and fall back to giving a message only if it's not feasible.

**Comment by CharliePoole** [comment]
@jnm2 Absolutely! I merely expressed that I thought there could be difficulties. Nothing definitive about that. If there are difficulties, you'll probably notice them. 😄 It's different when you are planning to try yourself versus trying to convince someone else (maybe a contributor) to do it a certain way.

**Comment by rprouse** [comment]
Most of the issues I have seen reported seem to boil down to the `CurrentContext` being null. We would need to test it, but what if we switched the getter for the property to throw an `InvalidOperationException` with a more useful message when it is null? I did a quick scan of the code and we seldom check if `CurrentContext` is null because we used to do lazy instantiation if it was.

**Comment by CharliePoole** [comment]
@rprouse That's what I would do as well. But @jnm2 feels like he can make it work when null and I didn't want to discourage him. 😈

**Comment by rprouse** [comment]
@CharliePoole you assigned this to yourself. It sounds like you thought @jnm2 was doing it in the other issue. Are you working on this? If not, I can take it.

**Comment by CharliePoole** [comment]
I started looking. Seems simple but the test is a tad hard to construct, since we want to run the test outside of a test. 😕 I may just test it externally.

**Comment by jnm2** [comment]
@CharliePoole Why not spin up a new thread to test it? That's what I was going to do.

**Comment by jnm2** [comment]
Something like
```c#
public static class ThreadUtils
{
    public static void RunOnBareThread(Action action)
    {
        var exceptionDispatchInfo = (ExceptionDispatchInfo)null;
        var thread = new Thread(() =>
        {
            try
            {
                action.Invoke();
            }
            catch (Exception ex)
            {
                // Preserve the call stack
                exceptionDispatchInfo = ExceptionDispatchInfo.Capture(ex);
            }
        })
        {
            Name = "RunOnBareThread " + action.Method.Name
        };

        thread.Start();
        thread.Join();

        if (exceptionDispatchInfo != null)
            exceptionDispatchInfo.Throw();
    }
}
```

**Comment by jnm2** [comment]
And then `Assert.That(() => ThreadUtils.RunOnBareThread(Assert.Fail), Throws.TypeOf<CorrectExceptionType>());

**Comment by CharliePoole** [comment]
The TestExecutionContext follows the new thread. You would have to get a thread from elsewhere, not create it. Like a pool thread. However, I'm doing it another way. Did you forget you were busy? 😜

**Comment by jnm2** [comment]
@CharliePoole Hey, I'll blame you for nerd-sniping me :D I could hand over my tiny NativeThread implementation :D

**Comment by Jivko1212** [comment]
Hi, I ran into the issue of not being able to run tests directly. It used to work fine on 3.6.1. But now it throws  on the first Assert.AreEqual.

I find running one test directly when trying to debug it works better than the visual studio "DebugAllTestsInContext" shortcut. I have some tests that use events raised from Native API (via callback). The callbacks simply don't work when I try to debug the test using "DebugAllTestsInContext". I have been able to debug them by running them directly. Then they run fine using the Test Runner. However, I am unable to debug my tests now.

Please bring back ability to run test directly :)

**Comment by CharliePoole** [comment]
@Jivko1212 Note the labels and assignment. 😃 They tell you this is accepted to work on and is being worked on. There's a linked PR, which you are welcome to review. It will be merged as soon as another committer reviews it.

**Comment by CharliePoole** [comment]
@nunit/core-team See previous comment, where I was teasing @Jivko1212 a bit for not reading the labels. 

The fact is, however, that you need to read our developer docs to understand our process and interpret the labels correctly. It hadn't struck me before, but this can be viewed as a fault in our process. Maybe we should re-define labels in a way that it makes the status of any issue crystal clear to any user, without ZenHub and without having read to read any documentation.

**Comment by jnm2** [comment]
@CharliePoole I was thinking the same just now.

**Comment by jnm2** [comment]
`in-progress`?

**Comment by jnm2** [comment]
Or maybe `status:implementing` and `status:reviewing`?

**Comment by jnm2** [comment]
Would work with `status:design`.

**Comment by Jivko1212** [comment]
Hi, I was excited to see the same issue that I was having and decided to write about it. Will get more familiar with github labels.

It is really interesting though why NUnit fails when running tests for code that registers for a native callback. The same tests work fine from the console runner but do not work from the Visual studio IDE (the test adapter) or when debugging. Has there been similar issue before? It seems the native callback simply doesn't fire in the VS IDE when running Nunit. It works fine if I run the tests directly though.

Feel free to delete or move this if this is off-topic.

Thanks

**Comment by jnm2** [comment]
@Jivko1212 You're asserting inside native callbacks? That sounds like something I might do 😆 Can you expand on that in a new issue?

**Comment by CharliePoole** [comment]
@jivko1212 I'd suggest waiting to see if your situation works with the fix in PR#2279. My guess is that if it worked before 3.7, it will work with the new fix.

**Comment by jnm2** [comment]
@CharliePoole Weird that it would work in 3.7 from the console runner but not the VSTest adapter rhough, isn't it?

**Comment by CharliePoole** [comment]
Not if you've worked on the adapter. There are __so many__ things different about the environment when you run under the adapter, things that are out of our control, that I expect anything. 😄

**Comment by jnm2** [comment]
@CharliePoole I am an incurable empiricist as well as optimist. 😆

**Comment by Robot1que** [comment]
@CharliePoole @rprouse I'm very sorry for a potentially stupid question but what is the point of marking an issue as closed when there is no release that contains fix for the issue? (perhaps everyone in Github does it but then it doesn't mean I agree with this approach.)
Speaking of this particular problem - last release was on Jan 6 (NUnit 3.7.1) and the fix has been merged to `master` later in January. So more than half a year has passed since then and there is no release on NuGet that contains fix for `NullReferenceException` when `Assert.Then()` is used outside of the NUnit framework. I've copied implementation of the `AdhocContext` and set it to `TestExecutionContext.CurrentContext` by using reflection (the only way to set a value to a property with private setter I know).

**Comment by CharliePoole** [comment]
Our view is that a feature is "released" as soon as it is merged to master. At that point, it is available to anyone who needs it either by downloading the latest dev build from MyGet or building from source. Most people, of course, will wait for the next production release.

In this case, NUnit 3.7.1 was released on June 5 (not January 6). This issue was reported on June 12 and fixed on June 24., which is 12 days, not six months. All dev releases after June 24 contain the fix. The next production release is scheduled for August 31.

**Comment by Robot1que** [comment]
@CharliePoole sorry, I misread "Jun" (I read it as "Jan") and overreacted a bit. Ofcourse waiting until the end of the month is not a big problem.
Thought making local builds from `master` to get latest changes is not an option because we do not want to keep .dll files in the source control so every other developer gets it as well. Seting up local NuGet server where our team could upload packages manually could be an option but maitainig it would require additional resources. I've never used MyGet before, I need to read about it before making any conclusion.
Anyway thanks for a quick reply.

**Comment by rprouse** [comment]
@Robot1que we also have all builds of master available as a MyGet feed to be consumed by people that need it. You will need to modify a nuget.config file to pull from the new feed, but it is there if you need it.

https://www.myget.org/feed/Packages/nunit
