### ISSUE TITLE
Storing trace output

### ISSUE THREAD

**Issue by tgmayfield** [nunit/nunit#2250]
With NUnit 2.6.3 and earlier, I had logging configured to output to `Trace`. Most of the time, tests are run either from CI or from ReSharper, either of which let me dig down into that trace output if there was a problem or if I needed to investigate a test. The other common runner was from the command-line, to run the full test suite before committing or pushing changes.

I've upgraded to NUnit 3.7.1, and have lost that output entirely. I can see it when debugging a test from ReSharper but otherwise all my logging statements have disappeared. I experimented with changing my logging to output to the `Console` or `TestContext`, but then I'm inundated when running from the console (lots of integration tests that are setting up and tearing down temporary databases). Under the hood I'm using log4net, so it was quite easy to change how all my tests logged, but I'm not finding a satisfactory way of having the `Trace` output available only when I need it instead of displayed all the time in the console.

This seems to be something you've addressed, but for the programmers that needed to see immediate progress information, via `TestContext.Progress`, rather than having output available only when someone digs into it.

- #699 requests including the stdout, stderr, and trace output in the report file. I see that stdout and stderr are both included in my result XML file, but not trace messages
- #1139 requests immediate messages, which seems to have been resolved with `TestContext.Progress`.

I would like to find some way of capturing this trace-level output but not displaying it all the time.

**Comment by tgmayfield** [comment]
As I'm thinking about it, I would be perfectly fine with logging using `TestContext.WriteLine(...)`, if that output did not show when running from the console. Is that an option?

**Comment by CharliePoole** [comment]
It's pretty easy to capture trace output, as we did in NUnit V2. However, trace output is simply text and has no info attached that tell us which test produced it. In NUnit V2, we only ran one test at a time, so we could deduce which test had created the trace output. This was also true for log4net output.

In NUnit 3, with the possibility of multiple tests running in parallel, we can't associate the output with a particular test if we simply capture it. That's why we provide ways of using NUnit itself to generate output.

TestContext currently provides streams for Out, Error and Progress. They are all intended to display all the time. It would be possible to provide additional streams (like Trace) and to give you some way to turn them on and off from the command-line. That's a good-sized enhancement so we would want to know if it was really helpful to folks in general. Taking it a step further, we could simply allow you to create your own streams, in addition to the existing ones. That would be an enhancement on the enhancement. 

None of this would help with actual Windows Trace output. For example, your SUT might have trace statements embedded. So I think we need to decide first whether this is to be about some way of making extra "trace" output within the test or with capturing the real TRACE. Hope that makes sense. 😄

**Comment by tgmayfield** [comment]
I love the thought of having the ability to manage additional streams that get included in the report. It would prove very useful to have an explicitly-named log stream, SQL statement stream, etc.

For me, it's really about making a way of capturing additional trace output. I can see where developers would want to capture trace output from the SUT. Would that be possible based on trace categories? Maybe a `[CaptureTraceOutput("MyCategory)]` could make that possible for the executing test.

**Comment by CharliePoole** [comment]
Do you mean to turn it on and off at the test level?

**Comment by tgmayfield** [comment]
Assuming you have additional streams available, `[CaptureTraceOutput("MyCategory)]` would be an easy extension to write at the test level, yes. The NUnit extension would just grab that category of trace output while the test is executing and append it to the additional stream.

**Comment by CharliePoole** [comment]
That would get you any trace output produced while that test was executing, but not necessary trace output __caused__ by that test. I recognize that an approximation might be useful, but just wanted to point out that a general solution to capturing output based on the test that caused it is not possible unless the originator of the output somehow tags it. That's what we do when you do TestContext.Progress and related calls.

Maybe I'm misunderstanding you. Internally, we talk about "capturing" output when, for example, when we replace Console.Out. If you mean turning on and off the use of a particular stream that we add to TestContext, yes that's trivial.

**Comment by tgmayfield** [comment]
We got off into the weeds on what may be useful for existing Trace statements, just playing with ideas for capturing it when possible.

For my own needs, just having additional streams available (that don't output to the console) on the TestContext would have me taken care of. I can whip up a pull request toward that end, if you'd like.

**Comment by CharliePoole** [comment]
Maybe let's spec it out a bit here first. I was just trying to find out where this issue needed to go versus where the weeds are. 😄 

What would we add to TestContext as a user interface if we want to do this?

**Comment by tgmayfield** [comment]
I've been thinking about how I'd use it, and how that would result in changes to TestContext. My thought right now is to add `TextContext.GetOutputStream("name")`, and then including those additional results in the generated result file. For the standard file, it would generate additional `<output name="name">` elements.

**Comment by rprouse** [comment]
This issue is marked as an idea/design/discussion but hasn't had contributions in years so I am closing. If anyone is interested in working on this idea, post your interest and the team will consider reopening.
