### ISSUE TITLE
Question: Issue 2260 follow on 

### ISSUE THREAD

**Issue by agray** [nunit/nunit#2262]
Following on from #2260, which was closed:

Is [this](https://github.com/saucelabs-sample-test-frameworks/CSharp-Nunit-Selenium/blob/master/ParallelSelenium) an incorrect code example?

**Comment by CharliePoole** [comment]
Placing `[Parallelizable(ParallelScope.Fixtures)] on a test fixture triggers the bug in issue #2261. Just use `[Parallelizable]`.

There are so many options in the `ParallelizableAttribute` that users seem to be drawn to use as many as possible. I think this was an error in the API design, but it's too late to change, at least until 4.0.

`ParallelScope.Fixtures` is __intended__ to make any fixtures contained in the suite on which it is used run in parallel. It does that if you use it at the assembly level or on a SetUpFixture. I never imagined that it would be placed on the fixture itself, but I guess it's a natural thing to do, since you are not the first person to do it. At present (until the fix for #2261 is in) it still means "run fixtures below me in parallel" but a test fixture never has any other test fixtures below it, so that's useless.

Two warnings for parallel with the current release: Don't use ParallelScope.None on the assembly. Don't use ParallelScope.Fixtures on a TestFixture. Both will surprise you, I'm sorry to say.

WRT question issues... you don't have to keep filing new ones, just continue posting on the old one, even if closed so long as it's the same problem. We close it if we think we answered you. If we didn't, just keep asking.

**Comment by rprouse** [comment]
Closing this as answered.
