### ISSUE TITLE
Tests to run when opening solution file not clear

### ISSUE THREAD

**Issue by OmicronPersei** [nunit/nunit#2265]
The unit tests expected to be ran when opening the solution file is not clear.  I suggest updating the `BUILDING.md` file to make which projects' tests to run more clear.  We should probably also update the wiki to mention reading the `BUILDING.md` file for direction on which unit tests to run.

**Comment by jnm2** [comment]
This has crossed my mind a number of times. It would be nice for new contributors.

This may apply to other repos too.

**Comment by CharliePoole** [comment]
So, I have always thought of this as "obvious" since the actual tests are all in the tests directory. If anyone is having a problem, then it's clear I'm wrong, but since the two of you understand one another so well, could you explain where the confusion lies! 😺

**Comment by jnm2** [comment]
I think this issue is now fixed, at least for this repo. https://github.com/nunit/nunit/pull/2266#issuecomment-309523146

@CharliePoole The `tests` directory structure is not visible anywhere in Visual Studio, including Solution Explorer, the test window, and ReSharper's test session tabs.

Visual Studio populates its test window and ReSharper populates its test window using all loaded projects that are test projects, including `nunit.testdata` projects. "Run all tests in solution" does just that.

A fix might be to use solution folders to group the projects into `src` and `test` project directories.

**Comment by jnm2** [comment]
@CharliePoole So we have this documented, but it's still an irritation for me because my IDE makes the valid assumption that when I say "run all tests," it should directly test every test project in the solution.

Besides hitting cancel every time and using ReSharper to delete those project nodes, or changing the VSTest window view to group by projects and selecting all nodes and unselecting the testdata nodes for every run– the only way to deal with this irritation would be some attribute like [`assembly: NUnitNonTestAssembly]` together with some way to ignore that attribute when testing with `TestRunner.RunTest`.

Why not just use `build.ps1` whenever I need to run all tests?
1) context switch away from the IDE and code
2) can't double click on tests to jump to code
3) can't browse and filter nearly as nicely

**Comment by jnm2** [comment]
We could have a new `NUnitIndirectTestAssembly` attribute in the `Internal` namespace. It would make no sense for end uses to use it but it would be nice for NUnit development itself.

**Comment by CharliePoole** [comment]
I tried to comment on this several times but was not able to get my comments to post for some (probably network-related) reason. I really never understood what it was about until made a reference on a separate doc issue to the testdata tests. I guess you and the OP were on the same wavelength, but ideally he should have been made to spell out the problem.

If he had done that, we could have told him we do not recommend using the VS adapter to test the NUnit framework for exactly the reason described - among others. We have always told people this and the fact that it's not in the build.md is more a matter of history and authorship than anything else.

In the case of contributors and committers, we want them to use the build script to test. The info about  what to test is encapsulated there. For in-VS use, we have always told people to set up the console runner as the debug program for VS and to run the nunitlite tests directly.

I'm not saying that we can't change "what we have always done" but only that changing it should be explicit as well as prior to documenting the change.

BTW, I consider using the adapter to test the engine or the adapter itself as "not supported" rather than just "not recommended." Using the adapter in that case pulls in two different copies of the engine and at best breaks things, at worst gives untrustworthy results.

I guess we are moving to a large group and much of this stuff needs to be written down now. It sounds as if not all team members even realized that this was our past practice. 😞

**Comment by CharliePoole** [comment]
@jnm2 Our comments crossed. I'm sorry to say that the "rule" of not using the adapter for NUnit work is so ingrained in me that it never crossed my mind that anyone would do it. The adapter is a weak substitute for the console runner when testing NUnit because of poor performance and insufficient info contained in the output. It has been a disappointment to me to see how many NUnit users prefer the spurious convenience of running tests inside the IDE to the speed and accuracy of a dedicated runner. I've given some thought to writing an extension that "does it right" in terms of the concepts in NUnit, but I haven't yet gotten enough free time to work on it.

If you and others want the convenience of running selected tests quickly inside the browser, I would suggest using TD.Net for now. Of all the VS extensions, it seems to do the best job - i.e. most consistent with NUnit. I"m pretty sure @jcansdale would let us use it for nunit without charge if he were asked nicely. 😄 

For running all your tests, the script remains the way to go. Changing context to run a full set of tests does not seem like such a big deal to me

BTW, for my own selected tests within VS, I just use the console runner set up as the debug application. Us old guys are happy we can run tests at all. You kids are spoiled rotten. 😄

**Comment by jnm2** [comment]
> BTW, I consider using the adapter to test the engine or the adapter itself as "not supported" rather than just "not recommended." Using the adapter in that case pulls in two different copies of the engine and at best breaks things, at worst gives untrustworthy results.

Just my two cents. I strongly believe this should not be the case. If framework tests are erroneously failing or succeeding based on engine version, we have failed in our goal of separating the two projects.

> For in-VS use, we have always told people to set up the console runner as the debug program for VS and to run the nunitlite tests directly.

As I've also stated in the past, the convenience or a rapid feedback loop is worth breaking this rule ten times over. I only run `build.ps1` before I commit code. I believe that is all that is needed.
Again, if our VSTest adapter is not good enough to test NUnit itself in the IDE, I consider that a failure.

> Us old guys are happy we can run tests at all. You kids are spoiled rotten.

All due to the success of TDD. Efficiency is not a bad thing at all. This should be part of NUnit's vision. 😄 

> It has been a disappointment to me to see how many NUnit users prefer the spurious convenience of running tests inside the IDE to the speed and accuracy of a dedicated runner.

I have **not once** observed a speed or accuracy issue with the VSTest adapter and if I did, it's a bug that needs to be fixed in the adapter so that there is no speed or accuracy issue. I'm disappointed that the only way to get rapid running and debugging, navigation and code coverage is considered somehow rookie or deficient.  I'm sure you don't think NUnit should refuse its users these basic and effective considerations on principle, but that's the effect it has if you tell people not to use the VSTest adapter and yet don't provide any other kind of tight IDE integration.

> I'm not saying that we can't change "what we have always done" but only that changing it should be explicit as well as prior to documenting the change.

I'm not going to change my development practices of testing/debugging in VS because I'm at least three times as productive and it doesn't affect the NUnit team. I can insulate the supposed negative side effects by running build.ps1 just before committing.

But I believe we should go through the process of explicitly changing the rules for contributors as well.

**Comment by jnm2** [comment]
^ This is just a single vote as a member of the @nunit/framework-team. If others don't agree, all is well. =)

**Comment by CharliePoole** [comment]
@jnm2 This may be an "old vs new guard thing" which you guys will change in time.

I wrote the first adapter under strong encouragement from Microsoft. I'm sorry to say that I have always considered it as a sort of toy. It was dreadfully inefficient for many years and the inefficiency didn't lie in the adapter itself but in the environment that called it. If you don't see that now, then I'm pleasantly surprised, but the mismatch of concepts is still a problem.

I don't think the problem of the mismatch is insoluble, but it can actually only be solved on the VS side. It is not possible to "adapt" any arbitrary interface to another arbitrary interface. Both have to have sufficiently rich concepts to enable a translation without loss of data.

Regarding the failures you see in NUnit not being able to run it's "own" tests...

We test the engine using the engine and console. We test the console using the engine and console. However, in those cases, we are testing the engine and console using the same engine and console, which we just built. If we were to test the engine and console using the adapter, then we would be loading the engine using an older, released copy of the engine, which is bundled with the test adapter. It's not a failure of NUnit that you can't load two different engines at the same time. (There are advanced ways we could do that, but I don't think they would be worth the trouble.) As a time-saving thing, many years ago, we told ourselves "Let's just avoid that situation." IMO it's not an unreasonable decision. Traditionally, the NUnit developers put up with a lot of stuff - including limiting ourselves to .NET V2 (and V1  at one time) in order to give users the most flexibility. User convenience came first. We can try to make life easy for new contributors, but we need to consider the effort required __because that effort is subtracted from actual feature development.__

Re: use of nunit-console in VS - this has always given us an extremely rapid feedback loop at the minor expense of a bit of setup.

Re: providing an alternative to the adapter: My hope is to do that. I see the whole adapter concept in VS as flawed because the VS folks designed it on the basis of a lowest common denominator: their own test framework. My plan has been to develop an extension that works and I'm not giving up on that. I think eating our own dogfood would be a good objective for such an extension.

Re: Visions... we used to write github issues for visionary stuff we wanted to get to some day. I wrote bunches of them, which were removed a while back. I wasn't entirely happy with that, but again, it's old vs new guard. If @rprouse wanted to go back to having future issues, I'd be for it. Right now, github issues are for getting stuff onto our current backlog or otherwise closing them.

**Comment by CharliePoole** [comment]
I'm not sure it's a matter to "vote" on or just a question of opinion. It would take a fair bit of analysis to actually verify or disprove the assertions that each of us has made. That would give a factual basis to any decision. However, I'm not for a "vote" that just decides we wish this to happen some day. I'd be for an actual plan if it looked like it would work.

Neither of us works primarily on the adapter and it does have a project lead. So the first thing would be to hear what @OsirisTerje thinks of this.

As far as the current doc issue goes... I really think you have to document the current limitations, even if you don't like them for the long term. That's all we ever said to users before - it doesn't currently work.

**Comment by OmicronPersei** [comment]
If there are fundamental problems / actual bugs using the NUnit VS framework adapter to run the tests on the solution of NUnit, it should be documented as such.  Outside of that, with all due respect, all I really see is rationalized preference.

In the end, code is always going to hit the CI, so why does it really matter?  Your supposed benefits of the "speed and accuracy of a dedicated runner" are always going to be achieved with CI, correct?  

Additionally, why is it even relevant to say that an inside IDE testing platform is somehow incompetent and not recommended when there's little evidence (actually none that I can see) to suggest this is actually the case outside of verbosity?

The original intention of this was to suggest what the best/quick ways are to verify the integrity of the build within an IDE.  Perhaps there are some drawbacks to that, and maybe that should be documented.  As of yet, I've yet to see any evidence for them.

**Comment by CharliePoole** [comment]
@OmicronPersei It seems to me that we should be responsible to warn people - including possible contributors as well as those who are building from source for their own use - about ways of working that may lead to confusion or even give wrong results. 

This got a little off track, because the IDE wasn't mentioned originally and it only came up in a separate discussion I was having with @jnm2. I was kind of amazed to hear that you and he use the adapter for NUnit and was merely expressing my amazement. I'm the author of the original adapter and I worked on it for many years and I do not find it usable for NUnit development. If your experience is different, then that's fine.

Personally, I think that the docs should tell people to run the build script and leave it up to them to decide how to test incrementally in the IDE.
