### ISSUE TITLE
NUnit fixture skipped. Generic Test Fixtures with Parameters.

### ISSUE THREAD

**Issue by racharya** [nunit/nunit#2303]
I have a unit test class that has the following TestFixture
`[TestFixture(TypeArgs = new[] { typeof(<xxxxx>) })]`
When I run my unit tests on Resharper runner all of the tests comes out to be Inconclusive:Test not run
but when I run through Nunit adapter all of these tests passes. I am upgrading all of the unit tests that were written using NUnit 2.6.3 to NUnit 3.7.1.  I was wondering if this is an issue with TestFixture or Resharper or something else. Has anyone run into this? If so, what did you do to get around this.

**Version I am using**
NUnit: 3.7.1
Resharper: Resharper Ultimate 10.0.2
Nunit adapter 3

**Comment by CharliePoole** [comment]
I don't use Resharper, so I can't try this out. However, the test should work with NUnit itself and you confirm it does. In the case of Resharper, we don't really know how they make use of NUnit but I would have to guess that they are using NUnit in a way that doesn't actually run the tests because internally to NUnit Inconclusive is the default state of a test that has just been created.

**Comment by racharya** [comment]
Thank you Charlie. I was a bit curious if `TestFixtureAttribute` has anything to do with it. I am assured it's most probably ReSharper now.

**Comment by jnm2** [comment]
Please raise an issue with ReSharper. We need them to hear feedback like this. Much appreciated!

**Comment by jnm2** [comment]
https://confluence.jetbrains.com/display/ReSharper/ReSharper+Issue+Tracker
