### ISSUE TITLE
Ignored classes are not working as expected

### ISSUE THREAD

**Issue by owenniblock** [nunit/nunit#2362]
Hello,

I'm using NUnit 3.7.1 - running tests through Resharper's test runner (although investigating this issue with nunit-console and some other code which calls the NUnit framework directly).

We have a class with the Ignore attribute containing 2 tests (one ignored explicitly and one which I'd expect to be ignored based on the Class attribute):

```
[Ignore("Because I want to")]
public class MyIgnoredClass
{
    [Test]
    public void NotIgnoredMethod()
    {
        
    }

    [Test, Ignore("Intentional ignore")]
    public void IgnoredMethod()
    {
        
    }
}
```

However the `NotIgnoredMethod` gives the following XML output:
`<test-case id="0-1858" name="NotIgnoredMethod" fullname="Xamarin.UITest.Tests.AssemblyAnalysis.AnalysisTests+MyIgnoredClass.NotIgnoredMethod" methodname="NotIgnoredMethod" classname="Xamarin.UITest.Tests.AssemblyAnalysis.AnalysisTests+MyIgnoredClass" runstate="Runnable" seed="704490897" />`

[Reading the Wiki](https://github.com/nunit/docs/wiki/Ignore-Attribute) - I would expect both of these tests to return "Ignored" as the runstate.

Thanks,

Owen

**Comment by CharliePoole** [comment]
The RunState of a test does not change when it is executed. The RunState of that particular test is "Runnable" because it is capable of being run and is not ignored directly. It is not actually run because the containing suite is not run. In theory, this test could be run by selecting it with a filter.

This behavior probably needs some review. In particular, the test, because it was not run does not produce a result state in the XML. That means you would have to analyze the XML globally, rather than looking at the test method alone.

The documentation really says nothing about the XML content. It only states that a runner will report the test as ignored. Is that happening in your test runs? In any case, the doc page should be expanded.

**Comment by owenniblock** [comment]
It's an existing unit test to ensure we can correctly identify which tests are going to run based on the current filters etc. I believe we use this for reporting and progress indications when tests are pushed up to a cloud system and run remotely.

I would suggest that if "Ignored" doesn't properly describe the state of the test - adding a further RunState to expand the logic available to us might be a valid compromise? Something like `IgnoredByDefault` or the opposite: `RunnableExplicitly`?

**Comment by CharliePoole** [comment]
Actually, the state of the test without an `IgnoreAttribute` is `Runnable`, i.e. capable of being run. The set of RunStates are exactly those that NUnit needs in order to decide which tests to run in a given situation and are not really intended for any purpose beyond that. They have been stable for many years now.

If you can post some code that shows what you are trying to test, we might be able to suggest a workaround.

**Comment by owenniblock** [comment]
Your comment triggered an idea - don't know why I didn't think of this before.

I've updated our code to also check the parent node for Ignored. So if the parent node is reported as Ignored I flag the test as Ignored in our system.

Obviously this won't catch the edge case where a user explicitly runs a test which is Runnable but contained in an Ignored fixture but I don't _think_ that option is available to users of the system (I'll check during testing).

Happy to close this if you are.
