### ISSUE TITLE
Assert.AreEqual throwing an exception after migrate from 2.X to 3.X!

### ISSUE THREAD

**Issue by aytacasan** [nunit/nunit#2434]
Hi @CharliePoole 

After upgrade my NUnit package from 2.X to NUnit 3.X my some simple tests starts to fail.

I have a DataPoint class which has Value property (type is decimal).
I have a Indicator class which has Current property (type is DataPoint).
Both classes have implicit operator like below;
```
        // DataPoint
        public static implicit operator decimal(DataPoint instance)
        {
            return instance.Value;
        }

        // Indicator
        public static implicit operator decimal(Indicator instance)
        {
            return instance.Current;
        }
```

Here is my test;
```
        [Test]
        public void IndicatorTest()
        {
            var indicator = new Indicator();
            İndicator.Update(2m);

            Assert.AreEqual(2m, indicator);
        }
```

Actually above test successfully working when i use NUNit 2.X but after update to NUnit 3.X, it starts to fail (throwing AssertionException with message "Expected: 2m\r\n  But was:  <2,0>\r\n"). If i change test line to; Assert.AreEqual(2m, **(decimal)** indicator) then it'll start to successfully pass the test again. Why do I have to force type conversion? What is the difference NUnit 2.X & 3.X about this issue? Any idea about that?

Thanks

**Comment by rprouse** [comment]
I am adding the confirm label to this because I want to debug this and see how we are handling the equality. NUnit has many special cases for equality, so I want to see which is getting called.

**Comment by aytacasan** [comment]
@rprouse i see. If you need i can try to explain problem in detail. If so please inform me. Thanks.

**Comment by rprouse** [comment]
@aytacasan your explanation is good and provides enough information. I just wanted to walk through the code to confirm where it was happening. This is probably a misuse of the confirm label though, so I am going to switch to a bug.

**Comment by mikkelbu** [comment]
As far as I can tell the difference is that in Nunit v2 Assert.AreEqual had a lot of overloads. In particular, the overload `Assert.AreEqual(decimal, decimal)` which is the best match in the example above (due to overload resolution there is an implicit cast). Hence the logic in Nunit simply compares two decimals. 
Since we don't have the overload anymore in v3, we will call `Assert.AreEqual(object, object)` and our logic in `NumericsComparer` (or `Numerics`) does not check for implicit conversions.

The situation is similar to the one mentioned in 
https://groups.google.com/forum/#!topic/nunit-discuss/R7NvLst-uzw

**Comment by CharliePoole** [comment]
@mikkelbu Yes, that's correct. If we had kept the `Assert.AreEqual(decimal, decimal)` overload, then this would pass. However, that would introduce an inconsistency in behavior between these two asserts:

```C#
Assert.AreEqual(2m, indicator);
Assert.That(indicator, Is.EqualTo(2m));
```

While the overloads for numeric values are trivial in the case of the first assert, it's very hard to do for the second assert. Essentially, we would have to duplicate all the logic the compiler uses to decide to make a particular implicit cast. It's a bit much.

At some unspecified future time 😄 we might stop working with objects and use actual typed values. Of all the major changes we talk about, that's probably the most complex of all. A number of us have started on it in the past, only to get stuck and give it up.

**Comment by jnm2** [comment]
Sounds like this is by design and we are not open to having NUnit equality take implicit operators into consideration. The simplest workaround is to apply the implicit operator explicitly:

```cs
Assert.AreEqual(2m, (decimal)indicator);
```

You could also write a custom IEqualityComparer class that applies implicit operators to either the expected or actual values or both, according to the C# spec or any set of rules you prefer, and use this syntax:

```cs
Assert.That(indicator, Is.EqualTo(2m).Using(MyImplicitOperatorComparer.Instance));
```
