### ISSUE TITLE
[Request for help] .net core 2 framework, no nunit.framework.dll in the output directory

### ISSUE THREAD

**Issue by ig-sinicyn** [nunit/nunit#2456]
**How to reproduce:**

0. VS 2017 15.3.5, net core 2 SDK x64 installed.
1. Create an empty class library project, set targetframeworks to net461 & netcoreapp2.
2. Add a reference to nunit package:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.0;net461</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.8.1" />
  </ItemGroup>
</Project>
```
3. Build.

**Actual results:**
The `bin\net461` dir contains `nunit.framework.dll`; the `bin\netcoreapp2.0` does not.
When I try to run nunit console runner over the dlls i'm getting 
```
Could not load file or assembly 'nunit.framework' or one of its dependencies. The system cannot find the file specified
```
error.

**Expected results:**
The nunit.framework.dll should be in both dirs.

**Proof proj:** [NUnitTest1.zip](https://github.com/nunit/nunit/files/1326446/NUnitTest1.zip)

**Comment by rprouse** [comment]
If you are using the new CSPROJ format, I would recommend that you use `dotnet test` to run the tests. The console can run the .NET 4.6.1 tests, but not the .NET Core App 2.0 tests.

The reason the framework isn't copied into the bin directory is because that is the way .NET Core works ☹️ 

See https://github.com/nunit/docs/wiki/.NET-Core-and-.NET-Standard for info on how to setup your tests to get them running. Let me know if that gets you going.

**Comment by ig-sinicyn** [comment]
@rprouse thanks!

Yep, dotnet test works (dotnet vstest, to be precise - I need to run tests over already compiled dlls). The issue can be closed now:)
