### ISSUE TITLE
Parameterized fixture with Explicit attribute can not be run when selected by name

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#2477]
Given code like this...

```C#
    [TestFixtureSource(nameof(GetParallelSuites)), Explicit]
    public class ParallelExecutionTests
    {
        ...
    }
```

Running the console with a filter `--where test==Namespace.Of.ParallelExecutionTests` causes no tests to run. I think that's because we are running the suite that includes all the instances of the fixture but the attribute is applied to each fixture.

AFAIR this works correctly in the case of methods, so we should look at how we do it there.

Workaround for the above, BTW, is to use `--where test=~Namespace.Of.ParallelExecutionTests`.

**Comment by j4nw** [comment]
I'd like to look into this

**Comment by rprouse** [comment]
@j4nw the issue is yours. I am going to assign myself to mentor you on the issue if you have any issues. Please keep us up to date on your progress and let me know if you need any help.

**Comment by j4nw** [comment]
@rprouse just letting you know that I haven't forgotten about the issue, I haven't been able to find the time these past few days. Thank you

**Comment by Poimen** [comment]
Hi - I came across this bug.

After some digging yesterday, I traced up to the point of running the `PerformWork` function in CompositeWorkItem.cs https://github.com/nunit/nunit/blob/46f8b2ae280a6a6150e0f0bf86718a783d8b0c9d/src/NUnitFramework/framework/Internal/Execution/CompositeWorkItem.cs#L85

When a test fixture is parametric and the where condition is specified, `Filter` above is the `FullNameFilter`. This then attempts to compare the parametric fullname to the specified fullname.

As a way of an example (that is very silly):
```c#
    [TestFixtureSource(nameof(GetParallelSuites)), Explicit]
    public class SomeTestFixtureForExplicitIssue
    {
        public SomeTestFixtureForExplicitIssue(string word, int num)
        {
        }

        [Test]
        public void Test1()
        {
            Assert.That(1, Is.EqualTo(1));
        }

        static object[] GetParallelSuites = {
            new object[] { "Question", 1 },
            new object[] { "Answer", 42 }
        };
    }
```
The full name for one of these test fixtures becomes `ClassLibrary1.SomeTestFixtureForExplicitIssue("Answer",42)` due to it being parametric.

Hence when you run `--where test=ClassLibrary1.SomeTestFixtureForExplicitIssue` the match on the full name fails as it attempts to match the full name by direct comparison through the `ValueMatchFilter`:
https://github.com/nunit/nunit/blob/46f8b2ae280a6a6150e0f0bf86718a783d8b0c9d/src/NUnitFramework/framework/Internal/Filters/ValueMatchFilter.cs#L66

The reason using `--where test=~ClassLibrary1.SomeTestFixtureForExplicitIssue` works is that it detects the `~` and uses the RegEx code path in the `ValueMatchFilter` to match `ClassLibrary1.SomeTestFixtureForExplicitIssue` and matches against the full name starting with `ClassLibrary1.SomeTestFixtureForExplicitIssue` rather than the direct match:
https://github.com/nunit/nunit/blob/46f8b2ae280a6a6150e0f0bf86718a783d8b0c9d/src/NUnitFramework/framework/Internal/Filters/ValueMatchFilter.cs#L64

This leads to a couple of ways in solving the issue (that I could think of):
1. This is the way it is supposed to work and explicit fixtures should be specified (fix the parser to accept parametric fixtures because you can't do `--where test=ClassLibrary1.SomeTestFixtureForExplicitIssue("Answer",42)`)
2. Change the `FullnameFilter` to do a `StartsWith` check rather than a `==` - i.e.
https://github.com/nunit/nunit/blob/46f8b2ae280a6a6150e0f0bf86718a783d8b0c9d/src/NUnitFramework/framework/Internal/Filters/FullNameFilter.cs#L45
would need to change not to use `ValueMatchFilter` directly.
3. Introduce a partial name filter matcher that would do point 2 above


I could also be over simplifying the whole process as well.

Hence I was wondering what your take on this would be?


Thanks.

**Comment by CharliePoole** [comment]
Been a while since I submitted this but I believe what I was suggesting in the initial comment is that Explicit is being applied to each fixture rather than to the suite containing the two fixtures. This may not be consistent with how we handle the same situation for test methods. Someone would have to check.

In your example, I believe the suite is correctly selected and executed but since it contains only Explicit fixtures, nothing further is run.

IOW I don't think it's a problem with filters but with how Explicit is applied.

**Comment by Poimen** [comment]
I see your point. I was going too far down the rabbit hole.

So I can confirm a few things:
1. `TestCase` attributes apply explicit on the `ParameterizedMethodSuite` so the suite full name become the unparameterized version (e.g. `ClassLibrary1.SomeTestsForExplicitIssue.Test1`) and the decedent tests full names are parameterized but Explicit is applied to the suite not each case

2. `Test` attributes apply explicit on the `TestMethod` level

3. `TextFixture` attributes apply explicit on the `TextFixture` so the suite full name is `ClassLibrary1.SomeTestFixtureForExplicitIssue("Question",1)`.

What I'm thinking you are alluding to is that although the Explicit is against the Test Fixture it should  actually be against the `ParameterizedFixtureSuite` rather? 

This would mean that the Test Fixture building would have to ignore the Explicit attribute and not apply it to the fixtures, or should the `ParameterizedFixtureSuite` have all the attributes that would have been applied to the Test Fixture be applied to this then build the Test Fixtures individually without attributes? Having a look at the usages, it should be "ok" to apply the attributes to the `ParameterizedFixtureSuite`...

If the above is correct, then there is a corner case - a parametric fixture with a single source item. What happens then is the a `ParameterizedFixtureSuite` is not created and the fixture is used as is.

Am I on the right track here?

**Comment by Poimen** [comment]
Ok - so it wasn't too difficult to update the attributes to use the parameterized version, however, the `DefaultSuiteBuilder` also uses the same `ParameterizedFixtureSuite`:
https://github.com/nunit/nunit/blob/cbeffad907943d4219a2f0cdcea55830d267225e/src/NUnitFramework/framework/Internal/Builders/DefaultSuiteBuilder.cs#L131

With the builders for the fixtures now returning a single item, the switch here:
```c#
                switch (fixtures.Count)
                {
                    case 0:
                        return _defaultBuilder.BuildFrom(typeInfo, filter);
                    case 1:
                        return fixtures[0];
                    default:
                        return BuildMultipleFixtures(typeInfo, fixtures);
                }
```

doesn't appear to be needed, but I don't quite know enough of the use cases.

The reason I ask is that there are a few tests failing because they are expecting a single `ParameterizedFixtureSuite` and now there are two because it builds a `ParameterizedFixtureSuite` into a `ParameterizedFixtureSuite`.

I can fix the tests, but not sure if the above switch should just have a default case of `return fixtures[0];` - e.g.:
```c#
                switch (fixtures.Count)
                {
                    case 0:
                        return _defaultBuilder.BuildFrom(typeInfo, filter);
                    default:
                        return fixtures[0];
                }
```
?

**Comment by Poimen** [comment]
Ok - so I did some more testing and you can disregard my switch question. I didn't realise you can actually put two `TestFixture` attributes onto the same class...
