### ISSUE TITLE
Finalize XML Format for Test Results

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#254]
Get comments from the community.

Specific issues:
* Document the schema
* How to record result state: two attributes or one?

**Comment by CharliePoole** [comment]
I'm working on documenting the current state of the XML format. See https://github.com/nunit/nunit/wiki/Test-Result-XML-Format

I see one issue with the `<environment>` element. 

It shows up as a child of the `<test-run>` element, so there is only one for the entire run. However, a few of the attributes will vary when the test is run in another process. For example, the runtime version under which the test is running may not be the same one used for nunit itself and two different assemblies could be running under two different runtime versions. Should we move some of these values to the assembly level?

Additionally, if we once add a feature of running tests in another machine, many more of these values could potentially vary.

Ideas about how to deal with this are sought!

**Comment by CharliePoole** [comment]
The description of the result file is complete at https://github.com/nunit/nunit/wiki/Test-Result-XML-Format and needs a review.

@yetibrain @rprouse Would you take a look?

I'm planning to change the text content of  the output, message and stack-trace elements to CDATA sections. For attributes that have values provided or influenced by the user, I'm going to add code to replace any invalid XML characters, which will deal with issue #850 as well.

**Comment by ravichandranjv** [comment]
Hi Charlie,

> I see one issue with the `<environment>` element.

As you had suggested, moving some of the attributes to the "assembly" makes more sense as 'runtime versions' make more sense with the `<assembly>` than with the `<environment>` of the running "nunit-version".

I do not want to suggest anything that may cause a rework but **uncluttering** the XML format more, will increase the readability, cleanliness of the resultant XML file, and may also help refactor the design.  

Please ignore these below suggestions if they mean reworking the code and not refactoring the design.

SRP and DRY

1. Since the test-cases are maintaining the count of asserts and this conforms to the single responsibility principle as well, why have the attribute, **asserts** at the test-suite level? 

2. The attribute **total** seems to maintain the same information as **testcasecount** in a test suite.

*The output for your ready reference:*

```<test-suite type="Assembly" id="0-1003" name="test1.dll" fullname="E:\nunit3_tests\test1.dll" runstate="Runnable"``` **testcasecount="2"** ```result="Passed" start-time="2015-10-07 13:30:06Z" end-time="2015-10-07 13:30:07Z" duration="0.040075"``` **total="2"** ```passed="2" failed="0" inconclusive="0" skipped="0" asserts="0">```

as does the attribute **total** at the root level.

*The output for your ready reference:*
```<test-run id="2"``` **testcasecount="2"** ```result="Passed"``` **total="2"** ```passed="2" failed="0" inconclusive="0" skipped="0" asserts="0" start-time="2015-10-07 13:30:06Z" end-time="2015-10-07 13:30:07Z" duration="0.393900">```

Instead of **testcasecount** appearing as an attribute of **`<test-run>`**, would it not make more sense to have **testsuitecount** as an attribute of **`<test-run>`**, as a **test-case** is already **contained** within **test-suite**?

**Comment by CharliePoole** [comment]
Please let me clarify one thing: **all** changes to the format are programming changes. We have been producing XML output from NUnit 3.0 alphas and betas for a number of years. That's how we work. However, code is not steel and concrete. It can be changed if there is a reason to change it.

For your specific comments:

The asserts on a suite are equal to the number of asserts executed in all the test cases **plus** any asserts executed in the suite's OneTimeSetUp.

The testcasecount is the number of test cases found in a suite or assembly while the total is the number of test cases selected for execution. If no filter is used, then the values are the same, but they can easily be different.

I added info to the document explaining these points.

**Comment by CharliePoole** [comment]
This comment will serve as a ToDo list of changes for completing the issue. I'll edit it as we go.

1. Move some of the environment information to the assembly level.

2. Add a filter element to the test-run, which will essentially be a copy of the filter that was passed in.

**Comment by CharliePoole** [comment]
There will need to be future work on the environment element. I created issue #887 for that.
