### ISSUE TITLE
TestContext.WriteLine does not properly capture output when called by Process.OutputDataReceived

### ISSUE THREAD

**Issue by mzboray** [nunit/nunit#2558]
I'm seeing a case where NUnit does not properly capture test output and attach it to specific test cases. I think I've found a workaround so I'm creating this issue to mostly figure out if this is the best way and if it's possible for NUnit to handle it itself. I've created a [gist](https://gist.github.com/mzboray/842c4f49c490ba65bb4a48be40774336) demonstrating the issue. I'm using NUnit 3.9 with the VS NUnit3TestAdapater.

The issue I'm having is that when I call TestContext.WriteLine from Process.OutputDataReceived the output is lost and not attached to the specific test case. NUnit generally seems to be able to properly capture output when called from other threads spawned during the test so this caught me by surprise. I'm not sure what's different about the Process.OutputDataReceived event. Note that this is just a simplified version of my actual code where what I'm trying to do is capture all my internal logs (via NLog if that matters) and capture them in the test output.

My work around is to capture the current TestExecutionContext in the setup method and log directly to that. Uncomment the setup/teardown methods in the gist to see it working as intended. I will probably have to write a custom target for NLog in my code, but that's not hard. Is this the best way to do this? Is this something that NUnit could handle automatically? Why is NUnit able to handle other cases where threads are spawned in tests?

**Comment by CharliePoole** [comment]
Some of the details in this response pertain to the .NET Framework (desktop) builds of NUnit. In particular, the passing of the `TestExecutionContext` around is done differently in the .NET Standard builds.
 
As you found, test code has to execute under a valid `TestExecutionContext`, if one is not found, a fake one will be created but not all the members will be correctly set up, for the good reason that we won't have the information available necessary to set them up.

We pass the context around in the thread's `CallContext` and, since the `TestExecutionContext` class implements `ILogicalThreadAffininative`, it will be handed over to any other threads created by the original one and recursively as well. Any thread pool threads you create will pass it along as will any calls to `BeginInvoke`. 

Apparently - or perhaps obviously - this doesn't happen across processes. The initial thread created for a process has nothing to do with the thread that starts it. That's why you had to capture the output from the process and pass it on through the saved context.

As you no doubt noticed, the context associated with the `OneTimeSetUp` is that of the containing test f ixture. In order to have the output properly associated with the individual test, you have to use it's separate context, which is available in the `SetUp` and `TearDown` methods as well as in the test method itself.

What's not clear to me is whether the process you are running is your SUT or actually contains tests. If it's the former, then I think you are doing it the best way you can and it should work. If it's the latter, then I don't see how you will ever get back the result of any Asserts in the other process.

**Comment by mzboray** [comment]
Thanks for the quick response.

Yes, this is with the full desktop version of .NET Framework.

In a sense ProcessWrapper is the SUT. In my actual code I am attempting to start a somewhat heavy-weight process once and then send it commands over standard input and receive responses over standard output. The commands are the individual cases. I am inspecting the output and passing or failing my tests based on that. The other process contains no tests.

I think I get what is going on. I thought the issue was something specific with the Process class's events, but the same thing can happen whenever a thread created in OneTimeSetup. The TestContext that is flowed to the thread does not have the case associated with it and so when TestContext.WriteLine is called on that thread it is lost (or at least not associated with the current test case) even if the WriteLine only occurs in the context of a test case.

This behavior seems fair given that you probably want to support running cases in parallel, but perhaps it warrants a mention in the documentation.

**Comment by CharliePoole** [comment]
So, you are hypothesizing a test fixture that creates a thread in one-time setup and leaves it running. The individual tests would somehow communicate with that thread, which is running in the context of the fixture rather than the individual test. You would have to either (1) pass the test context in your messages to that thread or (2) directly receive output from the thread, which you then sent to the context yourself.

**Comment by mzboray** [comment]
Yes, I updated the gist with a simplified example that starts a thread in the one-time setup. It has the same behavior. I think the behavior is fair, but some additional documentation around the TestContext and OneTimeSetup attribute would be helpful. Alternatively, some kind of option around OneTimeSetup (perhaps a parameter to the attribute) would make this concern more visible.

I'll close this issue as I've satisfied myself that this isn't a bug and that this work around is the best way to get the behavior I want.
