### ISSUE TITLE
Add minClientVersion to .nuspec files

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#2564]
We recently discovered (https://github.com/nunit/nunit/issues/2369) that our NuGet packages require a NuGet client version of at least 2.12. We should add the `minClientVersion` element to our nuspecs, so users get a better experience for this.

Whoever looks into this should check that 2.12 is actually the correct version, and we're not using any features only added in later versions of the NuGet client.

**Comment by phillipsj** [comment]
I will take this one.  Makes better since to start here for me.

**Comment by phillipsj** [comment]
I just looked through all the NuGet releases.  Net Standard support wasn't added until version 2.12 so that would be the minimum to support that feature. 

I will download a version prior to 2.12 and 2.12 and try to install the package and see what happens.  If it works, I will add the nuspec element and submit the PR.

**Comment by ChrisMaddock** [comment]
Great, thanks @phillipsj!

**Comment by phillipsj** [comment]
I have confirmed the findings and it works for 2.12+ and that 2.8.6 doesn't work.  I will probably get the PR created tomorrow.
