### ISSUE TITLE
Suppport for --x86 and .nunit options in nunitlite-runner.exe 

### ISSUE THREAD

**Issue by SmokyLV** [nunit/nunit#2571]
For the latest versions of NUnit the nunitlite-runner.exe is used as the new default to execute tests.
Is there a chance to get support for NUnit project file (*.nunit) and --x86 option for this runner as well?

**Comment by CharliePoole** [comment]
@SmokyLV The nunitlite-runner.exe is merely a way to use a dll rather than an exe for a self-executing assembly. It's not intended to enable use of more than one assembly (as with a projectx file) and it doesn't launch any separate projects for running the tests.

Given those limitations, it doesn't make much sense to somehow support project files. WRT X86 execution, we would have to provide an X86 build of the runner.

@rprouse Where do you want to go with this?

**Comment by SmokyLV** [comment]
Thanks for response. Looks like I misunderstood a purpose of the nunitlite-runner.exe a bit.
The thing is that our CI is configured to run NUnit 3.7 tests with nunitlite-runner.exe. Now I see that I just need to ask CI admins to adjust configuration.
