### ISSUE TITLE
Is.Not.EquivalentTo is extremely slow

### ISSUE THREAD

**Issue by Jcomper** [nunit/nunit#2598]
Just updated my tests from NUnit 2.4.8 to 3.9.0 and noticed that tests have started running too long.
And here is a synthetic test with allows me to reproduce the problem:

> [Test]
> public void TestEquivalent()
> {
> 	byte[] data = new byte[0x80000 + 7];
> 	byte[] encrypted = new byte[0x80000 + 7];
> 	encrypted[0] = 2;
> 	encrypted[1] = 3;
> 
> 	var watch = Stopwatch.StartNew();
> 	Assert.That(encrypted, Is.Not.EquivalentTo(data));
> 	watch.Stop();
> 	Debug.WriteLine($"Takes: {watch.ElapsedMilliseconds} milliseconds");
> }
> 

It used to work fast (with version 2.4.8), but now it takes 123116 milliseconds to run on my computer. In real test when two arrays contain completely different values, it takes about 22 minutes to run. Any idea why is it so?

**Comment by mikkelbu** [comment]
I think it is because of #2337.

It is easy to discover that the arrays are different, but due to the tallying we need to "calculate" the differences, hence for each `0` in one of the arrays we need to remove a matching `0` from the other array, and since we do this from the beginning of the arrays a lot of reshuffling will have to be done (each deletion will have to move all the following elements). Using a better datastructure we could probably improve the performance quite a bit. Or we could run this algorithm from the end of the arrays.

Ps. Do you really mean `Is.Not.EquivalentTo` (unordered comparison) when you use words like `encrypted`?

**Comment by CharliePoole** [comment]
@mikkelbu 's last question is key. Ate you sure you want equivalence and not equality?

I implemented this s long time ago using a simple, unoptimized approach. I didn't figure it would ever be used for large arrays and that has seemed to be true so far. Once in a while someone complains and then discovers that our definitions of equality and equivalence are not what they thought!

**Comment by Jcomper** [comment]
@mikkelbu @CharliePoole Thanks! I'm not the owner of that code, so I can only guess.
 
 Original test generate array of bytes, encrypt it and then use in the following assert:

` Assert.That(encrypted, new NotConstraint(new CollectionEquivalentConstraint(data)), "Encrypted == Data for {0}", encryptor.GetType().Name);
` 

So I guess there should have been used equality definition and not equivalent as @CharliePoole pointed out.
 
 P.S. "Once in a while someone complains and then discovers that our definitions of equality and equivalence are not what they thought", I have tried to search similar issue before posting this one and didn't find any.

**Comment by CharliePoole** [comment]
Yes... Equivalence would mean that both arrays contained the same byte values without respect to order. Equality means simply that they contain the same values in the same order. Not, of course, negates either one of them.

Sounds like they were making a minimal test: that the encryption algorithm actually changed the value rather than leaving it the same. I'd use 

```
Assert.That(encrypted, Is.Not.EqualTo(data));
```

**Comment by Jcomper** [comment]
@CharliePoole I totally agree with you. Thanks!

**Comment by mikkelbu** [comment]
For the current chase - which is a bit artificial 😄 - it is possible to improve the performance from 3 minutes to 1 second on my computer by reversing the iteration such that we do not shift the element more than necessary.

**Comment by ChrisMaddock** [comment]
Really, just from reversing the iteration? 😱 I'm amazed it's that big a saving! Good find!

**Comment by mikkelbu** [comment]
When we delete from the end we do not have to shift any elements, and hence can just mark the list as being 1 element shorter. When we delete from the beginning we will have to move all subsequent elements. So in the example above the complexity of the first operation is linear, whereas the complexity of removing from the front is polynomial. An alternative approach could be to use a datastructure that supports deletion in constant time.

However, if there are only a few duplicate elements, then the performance of the old implementation and the reversed iteration will quite similar.

**Comment by mikkelbu** [comment]
@Jcomper Just being curious, but can try the package or zip from https://ci.appveyor.com/project/CharliePoole/nunit/build/3.10.0-ci-04919-reverse-ite/artifacts and see how it performs (in the real test and not just in the example given above)?

Ps. I agree with you and @CharliePoole that `Assert.That(encrypted, Is.Not.EqualTo(data));` is probably more correct.

**Comment by Jcomper** [comment]
@mikkelbu Test 128 kB array,
NUnit 3.9.0: 2 minutes 48 seconds
NUnit 3.10.0: 2 minutes 43 seconds
With Is.Not.EqualTo it takes about 5 milliseconds 👍

**Comment by jnm2** [comment]
Another killer might be that we're boxing each byte to an object on the heap.

**Comment by CharliePoole** [comment]
Yet another may be that we are doing a heck of a lot in this constraint. Maybe someone should come up with an algorithm benchmark to show it can be done more efficiently.

But even if it can, I'm not seeing the use for equivalence over large arrays. Never did. I think that's why we managed to go so long without having problems reported.
