### ISSUE TITLE
Parallel tests are loading 100% CPU when nested SetUpFixture exists

### ISSUE THREAD

**Issue by undron** [nunit/nunit#2632]
Using 3.9.0.0 NUnit framework and adapter,  I have similar to https://github.com/nunit/nunit/issues/2507 issue.

We have [SetUpFixture] class in root namespace and [SetUpFixture] class in nested namespace.

Please refer code in https://github.com/undron/NUnitHangsAtNestedSetUpFixture
When tests from namespace NUnitParallels.Some is running it is 100% CPU utilization:
![image](https://user-images.githubusercontent.com/1076685/34163099-da1e98e6-e4e6-11e7-82cb-ff77df9f36bd.png)

**Comment by CharliePoole** [comment]
Please run using the latest console runner with --trace:Info and post the framework trace output.

**Comment by undron** [comment]
[InternalTrace.26824.log](https://github.com/nunit/nunit/files/1574508/InternalTrace.26824.log)
[nunit-agent_4788.log](https://github.com/nunit/nunit/files/1574509/nunit-agent_4788.log)
[InternalTrace.4788.NUnitParallels.dll.log](https://github.com/nunit/nunit/files/1574510/InternalTrace.4788.NUnitParallels.dll.log)

**Comment by CharliePoole** [comment]
I don't see anything hanging here - all tests seem to finish correctly, the agent terminates normally and the console run closes normally.

Did you mean something different by "hanging"?

**Comment by undron** [comment]
Sorry, I just copied title from #2507. In fact, tests utilize 100% CPU as shown at the first picture.

**Comment by CharliePoole** [comment]
I see you have four cores but are running 30 test workers. I'd expect that to slow things down a bit for most tests. Have you experimented with the default and/or other manual settings?

I also see that the OneTimeSetUp and OneTImeTearDown for both SetUpFixtures are running on the non-parallel worker. Is that your intention?

**Comment by undron** [comment]
>I see you have four cores but are running 30 test workers.

My selenium tests a much slower, so it's OK.
The peak of CPU is when tests from NUnitParallels namespace are waiting for execution:
![image](https://user-images.githubusercontent.com/1076685/34258820-c31277a4-e670-11e7-99d3-363ec58d9f34.png)

> I also see that the OneTimeSetUp and OneTImeTearDown for both SetUpFixtures are running on the non-parallel worker. Is that your intention?

I need to perform some job before and after all tests in dll, and make some actions before and after some special tests, so they are in different namespace.

**Comment by CharliePoole** [comment]
Forgot to ask... did you observe the same 100% CPU when you ran under the console runner?

I downloaded your code and will give it a try myself.

**Comment by CharliePoole** [comment]
I'm seeing essentially the same behavior. I downloaded your code and switched the target to 4.6.1 as I don't have 4.7.1 on my laptop. Running under the console, it pegs at 83% while those same three classes are running. Commenting out the attribute on the nested setup fixture it doesn't happen! 

This is a bit of a mystery to me - an interesting one - so I'll keep looking at it. Essentially, neither setup fixture is executing when the test classes are running so it's not clear how they can be affecting anything.

**Comment by CharliePoole** [comment]
Commenting out all the code (progress write and sleep) in those three test methods, I still get extremely high utilization for a few seconds when they run!

**Comment by CharliePoole** [comment]
The only difference between those tests and the first-level tests is that as each test fixture completes, it has to notify the second-level setup fixture, while the first-level test fixtures notify the first-level setup fixture.

It's clear that this is an overhead issue. When I use the default of 4 workers on my laptop, the problem disappears but of course the test run takes much longer. If I use 10 rather than 30 it comes back. I want to blame the Sleep, but that doesn't make sense since commenting it out made no change. Obviously, NUnit imposes some overhead when you are running multiple workers. We need to figure out how the nesting is increasing this overhead.

**Comment by CharliePoole** [comment]
Very interesting! I commented out all the first-level tests (those in NUnitParallels namespace) but left in the nested SetUpFixtures. Problem disappears!

We know from the trace that the top-level fixtures get enqueued before the second-level fixtures execute. My working theory is that busy-waiting by the workers is using up the CPU cycles. I'll need to try this out with a debug build of the framework.

**Comment by CharliePoole** [comment]
That was it. I'll do a PR.

**Comment by jnm2** [comment]
I'm happy you're removing busy-waiting. I have a hunch that'll fix other crashes I've had which appear to be due to CPU pegging.

**Comment by CharliePoole** [comment]
Status report for anyone following along:

* Adding `[Parallelizable(ParallelScope.Self | ParallelScope.Fixtures)] to the second-level SetUpFixture removes the issue. Of course, this is not valid because the top and second level test fixtures are not supposed to run at the same time.

*  The heart of the problem is that we use a very simple algorithm to indicate whether any work is available in the queue: If the add count is greater than the remove count, then something is available. However, in adding multiple levels to the implementation, items that are in the queue may be locked up at a lower level and are not actually available. So one approach is to update these counts when saving and restoring the internal queues.

* A more fundamental problem, requiring a lot of design work first, is that the number of queues is fixed. In this example, we have 13 fixtures to run. We immediately enqueue 10 of them but then create a new set of queues for the inner setup fixture and enqueue 3 more. Only those 3 are available until we return to the set of original set of queues. But the whole time, there are 30 workers checking to see if any work is available! The solution would be to grow and shrink the number of workers dynamically as more or less work was available to run. It's a big change but one I had imagined we would want to implement eventually.

Strategy here, I think, is to try the easy fix first. If it works, we can create a new design issue to have the worker level change dynamically, which would be more efficient overall. If it doesn't, then we might want to consider upping the priority on the dynamic creation of workers.

**Comment by CharliePoole** [comment]
@oznetmaster Since you created the algorithm using spinwaits, I'd appreciate your comments on the above as well as on the eventual PR.

**Comment by CharliePoole** [comment]
@garuma I'd appreciate your comments as well in light of your proposed refactoring.
