### ISSUE TITLE
NUnit 3 - need guidance for implementation 

### ISSUE THREAD

**Issue by EtgarZ** [nunit/nunit#2634]
I am using nunit-console v3.6.1 with framework v3.8.1.
I need an advice for how to implement something.
I want that when running tests via nunit-console, the engine will dynamically create directory for the test run, based on command line argument. 
For example if I run from cmd: 'nunit-console.exe Test.dll --work:"C:\Runs"', for each run I want to create directory in "C:\Runs" and I will set the Environment.CurrentDiretory property to the dir created dynamically by engine.

How can I achieve this goal (which NUnit components should I implement)?
Can it be done by writing an engine extension?

**Comment by CharliePoole** [comment]
No extension is needed. The console runner should be creating the work directory if it doesn't exist. 

If you want the current directory set to that directory, you would have to do it in your test code. It's a design principle that we don't change the current directory at all. Usually, however, this is unnecessary, since the path to the work directory is available to you in the TestContext.

**Comment by rprouse** [comment]
@EtgarZ I believe @CharliePoole answered your question, so I am closing this issue. Please comment if you need more help.
