### ISSUE TITLE
Add Current Attempt indicator in TestContext for use with RetryAttribute

### ISSUE THREAD

**Issue by bicarbon8** [nunit/nunit#2647]
the RetryAttribute https://github.com/nunit/nunit/blob/638b4011b102e506a42f65baa515abb010710a2f/src/NUnitFramework/framework/Attributes/RetryAttribute.cs currently uses an internal _count_ variable within its _Execute_ method to track the remaining number of Attempts that can / should be made before giving up (in the case of a constantly failing test).

I would like to request that this instead be a _currentAttempt_ variable that is added to the TestContext so I can read the value from within my test. This would allow me to indicate in my test logs which attempt I am on thereby making debugging via logs an easier process. Additionally, I could use the field to conditionally try additional steps if the number of failures exceeds a certain threshold thereby allowing for additional mechanisms for ensuring robustness of tests

**Comment by CharliePoole** [comment]
I see you've done a PR. It's usually a good idea to wait for the issue to be accepted first, in order to avoid wasting your time. It's possible that the team may not want to make this change or may want to make it in a different way from what you propose.

Personally, I like this idea, although I can see some dangers in it. If tests have the retry count available, they may end up written to do something entirely different on each attempt. While that may be considered a feature, I'd call it an anti-pattern.  Nevertheless, the benefit of being able to log the count probably outweighs the dangers.

I made this a low-priority feature. If any @nunit/framework-team  member disagrees we should discuss.

That said, I note that your PR does __not__ implement this as proposed here. Rather than make the count a property of the context, you made it a property of the test. I'll comment on the implementation in #2648.

**Comment by jnm2** [comment]
Rather than exposing the value programmatically, what about automatically logging when retries (and repeats) happen?

**Comment by CharliePoole** [comment]
@jnm2 Could you expand on that idea? We don't really log anything else automatically, so it's a bit unclear to me.

**Comment by jnm2** [comment]
We could start automaticaly adding lines to the log such as "Try 1 of 3 [RetryAttribute]" or we could prefix every line "[retry 2]" though that doesn't scale as well. That solves the logging problem without making the antipattern easy.

**Comment by CharliePoole** [comment]
You mean the internal trace log?

**Comment by jnm2** [comment]
I was thinking `TestContext.WriteLine`. What if `RetryAttribute` defaulted to doing `TestContext.WriteLine("Try 2 of 3 [RetryAttribute]")` before each *re*try?

**Comment by bicarbon8** [comment]
@jnm2 , while the additional logging you've suggested wouldn't be a bad thing, our tests use custom log files (one for each test method) and so the addition of logging to the TestContext output buffer wouldn't solve the case we need whereby I'd like to have each retry / attempt log to it's own file. To do so I need to know which retry / attempt we are on from within the TestContext

**Comment by jnm2** [comment]
Cool, making sure we need it. Sounds good to expose the proposed property for the sake of custom logging.

**Comment by bicarbon8** [comment]
closing issue as this will be included in the next release to include https://github.com/nunit/nunit/pull/2648 which was merged
