### ISSUE TITLE
The test run attributes like passed and failed test cases are not correct in the xml file generated..however the values are correctly displayed in the command prompt console.

### ISSUE THREAD

**Issue by GayathriGopal** [nunit/nunit#2653]
The test run attributes like no of passed and failed tests are not correctly updated in the xml report generated..however the command prompt console shows these values correctly..what am i doing wrong

**Comment by ChrisMaddock** [comment]
This part of the report is generated by the NUnit Engine.

I'll move this issue over to that repository, and comment further over there.

**Comment by ChrisMaddock** [comment]
Issue moved to [nunit/nunit-console #342](https://github.com/nunit/nunit-console/issues/342) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CharliePoole** [comment]
Reopening this since the error has been demonstrated to not lie with the engine or console but most likely in the framework. See nunit/nunit-console#342.

**Comment by CharliePoole** [comment]
For future reference, the engine is responsible __only__ for the content of the test-run element. In the case of the counts, it simply adds up the values in the suites (generally assemblies or projects) directly under it.

The console output report doesn't use those counts at all because they are not sufficiently granular. Instead it goes through all the tests individually and creates its own counts. The two summaries should be consistent, of course.

**Comment by GayathriGopal** [comment]
The issue was resolved when i built the test dlls using the nunit 3 framework, and then generated the reports.The count is updated perfectly.Now the console and xml summaries are consistent.Thanks for the timely help@CharliePoole and @ChrisMaddock
