### ISSUE TITLE
TestFilters internal

### ISSUE THREAD

**Issue by danielmarbach** [nunit/nunit#2684]
I saw that 3.9 made all test filters internal https://github.com/nunit/nunit/commit/207b7535ea61e66eb2cfa3879835d98632841618

We used the FullNameFilter to run tests inside a Service Fabric cluster see https://github.com/Particular/NServiceBus.Persistence.ServiceFabric/blob/develop/src/TestRunner/CommunicationListener.cs#L74

What is now the recommended approach after these filters have been made internal? Do I need to copy paste now the filters locally?

**Comment by jnm2** [comment]
@CharliePoole Time to move them into a non-`Internal` namespace? Do we need any API work on it before we do that?

**Comment by CharliePoole** [comment]
@jnm2 Or time to make NUnitTestAssemblyBuilder internal?

@danielmarbach You are running tests directly using the framework, rather than the engine. That's unusual but supported provided you use the API, which accepts filters as strings containing properly formed XML. See https://github.com/nunit/docs/wiki/Framework-Api

NUnit itself uses the framework API with one exception: NUnitLite currently uses NUnitTestAssemblyRunner directly. That's why we have to build NUnitLite along with the framework for each new release. That's something I have been hoping to change, in fact.

@jnm2 Why the high priority?

**Comment by jnm2** [comment]
> Why the high priority?

We removed something that caused a real-world break, so I want to make sure this gets answered.

**Comment by CharliePoole** [comment]
Sorry... I agree with that statement. I took the combination of design and high to mean that the work item was accepted. I see now you put it into discussion.

Some meta-discussion: 

Since I am not always running ZenHub, I have discovered that the use of pipelines is not very helpful and can even lead to complete misunderstanding - as here - when there is no straight and simple GitHub way to know the status of an item. It's particularly problematic when using my phone, as I often do.

I think ZenHub pipelines are great but much of their benefit depends on the entire team (and in this case the open source community) using the product. That's why I stopped using it in my own projects. I'd go back to it in a second for any in-house team I worked with.

If NUnit keeps using ZenHub pipelines, I think there's a need for redundant info that everybody can see. I hate to suggest more labels at this point, but... maybe that's the only way.

**Comment by danielmarbach** [comment]
@CharliePoole 

> You are running tests directly using the framework, rather than the engine. That's unusual but supported provided you use the API, which accepts filters as strings containing properly formed XML. See https://github.com/nunit/docs/wiki/Framework-Api

Any recommendations how to do it otherwise? With ServiceFabric in order to get access to the real state manager etc. for integration tests. That's why we need to deploy the tests alongside with some infrastructure to the cluster and then from a client-side test create a client proxy that connects to the cluster and tells the runner which test to run as well as intercepting and marshaling back the results to the client side test.

**Comment by CharliePoole** [comment]
@danielmarbach I think I need to look at your app a little to completely understand the question. Today's a bad day for me, but I __will__ get back to this.

**Comment by danielmarbach** [comment]
Any chance to get back to this?

**Comment by CharliePoole** [comment]
Sorry not to have gotten back to this personally. Since I'm no longer very active with NUnit, another @nunit/framework-team member will need to follow through.

**Comment by jnm2** [comment]
We recently had a discussion on this: https://github.com/nunit/nunit/issues/2931

If I remember right, we explicitly do not want a user-facing filter builder API in the framework because we want people to go through the engine (currently at https://github.com/nunit/nunit-console) to drive the framework rather. Any test filter API would probably belong either in the `nunit.engine.api` or in a new assembly.

**Comment by CharliePoole** [comment]
IIRC, part of the rationale for not providing the API was also that they are trivial to implement on the user side. Seems like anyone who is getting down and dirty with direct access to the framework should be able to create them fairly trivially. In fact, I think we do that in our own tests all the time.

**Comment by danielmarbach** [comment]
I'm personally more than happy to switch to another approach as long is I can filter individual tests and run them as described below in the cluster. Since those API have been removed in a breaking way would anyone here be willing to point me in the right direction so that I can jump on the release train again and update nunit?

**Comment by jnm2** [comment]
@danielmarbach The recommended approach is to stop referencing NUnit's framework assembly and instead reference NUnit.Engine so that you can work with a wide variety of NUnit framework versions.

@CharliePoole Do we have docs on this path? I was hoping we had something at https://github.com/nunit/docs/wiki.

**Comment by danielmarbach** [comment]
I did now the following. I kept all my code but added

```
class FullNameFilter : ITestFilter
    {
        public FullNameFilter(string fullName)
        {
            this.fullName = fullName;
        }

        public TNode ToXml(bool recursive)
        {
            return TNode.FromXml($"<filter><test>{fullName}</test></filter>");
        }

        public TNode AddToXml(TNode parentNode, bool recursive)
        {
            parentNode.AddElement("test", fullName);
            return parentNode;
        }

        public bool Pass(ITest test)
        {
            return Match(test) || MatchParent(test) || MatchDescendant(test);
        }

        public bool IsExplicitMatch(ITest test)
        {
            return Match(test) || MatchDescendant(test);
        }

        bool MatchParent(ITest test)
        {
            return test.Parent != null && (Match(test.Parent) || MatchParent(test.Parent));
        }

        bool Match(ITest test)
        {
            return test.FullName.Equals(fullName);
        }

        private bool MatchDescendant(ITest test)
        {
            if (test.Tests == null)
            {
                return false;
            }

            foreach (var child in test.Tests)
            {
                if (Match(child) || MatchDescendant(child))
                {
                    return true;
                }
            }

            return false;
        }

        string fullName;
    }
```

**Comment by danielmarbach** [comment]
Works like a charm https://github.com/Particular/NServiceBus.Persistence.ServiceFabric/pull/76
