### ISSUE TITLE
Replace ZenHub with labels

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2686]
##### Quoting https://github.com/nunit/nunit/issues/2684#issuecomment-360506670 by @CharliePoole:

> Since I am not always running ZenHub, I have discovered that the use of pipelines is not very helpful and can even lead to complete misunderstanding - as here - when there is no straight and simple GitHub way to know the status of an item. It's particularly problematic when using my phone, as I often do.
> 
> I think ZenHub pipelines are great but much of their benefit depends on the entire team (and in this case the open source community) using the product. That's why I stopped using it in my own projects. I'd go back to it in a second for any in-house team I worked with.
> 
> If NUnit keeps using ZenHub pipelines, I think there's a need for redundant info that everybody can see. I hate to suggest more labels at this point, but... maybe that's the only way.

This has come up a lot and I agree. I just uninstalled ZenHub so that I can only see what the community sees.

Can we use `awaiting:discussion` on issues instead of the Discussion pipeline?
We also have `review` and `design` tags which might overlap.

What other pipelines are important to represent besides Discussion?

**Comment by CharliePoole** [comment]
Labels seem to be what people look at. A while back, we were using pseudo-milestones for discussions and people never seemed to notice. The visual presentation of labels on GitHub makes them more obvious.

I'm not super keen on the "awaiting" series of labels that we are trying out. My worry is that folks will just ignore anything with an "awaiting" as something they don't need to see. We'll find out as we try them, I guess.

But in any case, I'd rather not put discussion into that group because discussion should something we do, not something we wait for. How about just plain `discuss`?

Regarding the `design` label... I created it with very specific intent, which may no longer match how the team things. If so, it should probably be changed or re-defined. My view as an extreme programmer is that much of what we used to call design is best done by the programmer, while programming. So while everything needs some design thinking, not everything needs `design`, which I pretty much took to mean "This is so crucial to us and/or so technical that we can't rely on the person who implements it to simply design as they go." I also apply it to things that are part of our public API. The team may want to change how this is used, in which case I think it should be explicitly defined.

**Comment by rprouse** [comment]
I'm in favor of dropping ZenHub completely. I've found my use of it to be waning except for the move issue button. Recently I switched to Firefox which wasn't supported  until recently, so I haven't installed the extension.

For moving issues, there is also https://github-issue-mover.appspot.com/

We could replace Epics with GitHub projects and use labels for `design`, `discuss` and `ideas`.

**Comment by jnm2** [comment]
@rprouse We have `design`, `awaiting:discussion` and `is:idea`. Should we add new labels?

**Comment by rprouse** [comment]
I think we should just start applying the labels that we have for now. If we find something that we miss that everyone feels would help, we can add later. Was there a specific label you were thinking about?

**Comment by jnm2** [comment]
Nope, just making sure I can safely close this issue. :D
