### ISSUE TITLE
Feature Request: FileName Compare

### ISSUE THREAD

**Issue by NUnitTester** [nunit/nunit#2694]
Compare file names in deep using names generated by API function GetFinalPathNameByHandle.

Usecase: File name is given with path. But the directory used in is made with subst or contains link to an folder.

string fileName1 = @"H:\trunk\test\testfile.txt";   // H is made with subst
string fileName2 = @"D:\currentVersion\test\testfile.txt";  // currentVersion is a link
If you go to a console, both files are identical, because both show to the same file C:\dir1\dir2\trunk\test\testfile.txt. (not only the content is the same)

I want to write something like this:
`Assert.That(fileName1, Is.FileNameEqualTo(fileName2));`
and it must pass.

Or write something like:
`Assert.That(fileName1, Is.EqualTo(fileName2).Using(FileNameComparer));`

**Comment by CharliePoole** [comment]
Your first alternative would require an extension or addition to the NUnit syntax and a new constraint.

Your second option is already available, if the user provides `FileNameComparer'.

I do not know of any __platform-independent__ way to do what you want. Detection of links and the like is very dependent on the operating system and I don't believe that .NET gives us access to them. Does anybody else know a way this can be done through .NET?

All that said, if we __could__ figure out a way to do it, I think it belongs in the same family as `SamePathConstraint`, rather than calling this "equality." Something like `PathToSameFile` perhaps.

If you don't care about platform-independence, you could of course create a custom constraint.

**Comment by NUnitTester** [comment]
As far as I know there is no operating system independant solution, perhaps in .NET Core. Up to now I use the windows API direct. But why not make different implementations for all supported platforms?
PathToSameFile is nice.

**Comment by rprouse** [comment]
> But why not make different implementations for all supported platforms?

With .NET Core going to more and more devices, implementations for every supported platform would be very difficult to maintain and test. We already support Windows, Mac, Linux/Unix, Android and iOS. I've even run NUnit on Raspberry Pi. I expect that it probably works with Samsung's Tizen now that it is .NET Standard.

It is an interesting idea, but I think this falls into the bucket of best left as a custom constraint. Anyone on the @nunit/framework-team disagree?

**Comment by jnm2** [comment]
I think this would be best contributed to `https://github.com/dotnet/corefx/issues/1086` and just a custom user constraint or user comparer as far as NUnit is responsible.

**Comment by ChrisMaddock** [comment]
I agree - I think there’s so many potential variants, this is something we could really struggle to support properly in future.

I think the team are generally in agreement here, so I’ll close this issue. NUnitTester - I do think this would be a good place for a custom constraint however - one that you could write to handle your specific problems, without having to worry about generalisation.
