### ISSUE TITLE
Not able to use TestFixtureSource values in TestCaseSource object.

### ISSUE THREAD

**Issue by amittrehan44** [nunit/nunit#2707]
I am trying to use TestFixtureSource values and pass it in TestCaseSource but null value is passed.

namespace HybridFramework
{
    
   [TestFixtureSource("FixtureArgs")]
    public class ParameterExperiment
    {   
        static string eq1;

        static object[] FixtureArgs = {
        new object[] { "Question"},
        new object[] { "Answer"}
		};

        public ParameterExperiment(string eq1)
        {
            ParameterExperiment.eq1 = eq1;

        }

        [TestCaseSource("getFruit")]
        public void TestMethod(string fruit)
        {
            // TODO: Add your test code here
            Assert.Pass("Your first passing test"+fruit + eq1);
        }

        static object[] getFruit =
       {
        new object[] {"Apple" },
        new object[] { "Orange" },
        new object[] { ParameterExperiment.eq1 }
        };

    }
}

TestFixture "ParameterExperiment" has TestFixtureSource as "FixtureArgs" with two parameters 1)Question and 2)Answer

TestCase "TestMethod" has TestCaseSource as "getFruit" with three parameters
1)Apple
2)Orange
3)ParameterExperiment.eq1 (TestFixture Parameter)

Issue: If I am using eq1(TestFixture Parameter) in test method I am able to see TestFixture Parameter value passed
but if I am using eq1 in getFruit, null value is passed.

**Expected**:
ParameterExperiment("Question")
- TestMethod("Apple")
- TestMethod("Orange")
- TestMethod("Question")

ParameterExperiment("Answer")
- TestMethod("Apple")
- TestMethod("Orange")
- TestMethod("Answer")

**Actual**:
ParameterExperiment("Question")
- TestMethod("Apple")
- TestMethod("Orange")
- TestMethod(null)

ParameterExperiment("Answer")
- TestMethod("Apple")
- TestMethod("Orange")
- TestMethod(null)

**Comment by CharliePoole** [comment]
The sequence of events is as follows:

1. The fixture is discovered and the value of it's argument is saved.
2. Each method is discovered and the value if its argument is saved.
3. You run the tests
4. Your fixture constructor is called with the saved value of its argument passed to it.
5. Your constructor saves that argument in a field.
6. Each test method is called and the saved value of its argument is passed to it.

So the test method gets the argument that was saved at step 2. This is simply how it works.

If your test methods need access to the fixture constructor arguments, your constructor should save them in a field or property. In order for each instance of the fixture to have access to __different__ arguments, this should be an instance - not a static - field or property.

Hope this helped! I'm closing this question but you can ask followup questions here if you need to and we'll see them and answer.

**Comment by amittrehan44** [comment]
Thanks for the reply!! 
Could you please help to elaborate more on: "_In order for each instance of the fixture to have access to different arguments, this should be an instance - not a static - field or property._"

So as per your suggestion if I make eq1 as not static I cannot pass it in TestCaseSource - getFruit as its static and in nunit the source name specified on a TestCaseSource attribute must refer to static field or method.

I need to pass argument value from Step 1 to Step 2

**Comment by CharliePoole** [comment]
As explained, you cannot pass a value from step 1 to step 2. Not without rewriting parts of NUnit, anyway.

However, you don't __need__ to because the value of a member field is available to your method without being passed as an argument.

Consider __any__ class you have, whether a test class or not. If it has instance members - properties or fields - all the instance methods in that class have access to the value when they are executing. They also have access to their arguments, of course. If you need to combine the value of a member field with the value of an argument in some way, you do it inside the method.

You haven't given any example of code you would like to write that uses both the name of the fruit and the value of `eq1`. If the above is still not clear, please provide an example and I'll try to answer in context.

**Comment by CharliePoole** [comment]
A further point of explanation about why things are designed as they are...

The source methods (fixture or case) are designed to work as if they are not part of your class at all. In fact, they can be in an entirely separate class and some people think that makes for a cleaner design. That's the reason they are static and entirely separate from one another. It's entirely possible for your tests to be in one class, your `TestFixtureSource` in another and your `TestCaseSource` in a third.

Is that clarifying or confusing? 😄

**Comment by amittrehan44** [comment]
Thanks for all your help!! 
I understand what you explained but I am still not able to solve issue I have

Let me tell you exactly what I am trying to achieve:

I have several test cases passed as TestFixture args (TestCase1, TestCase2, TestCase3) and each test case need to be executed multiple times with different set of test parameters according to the test case passed by TestFixtureSource 

Now In TestCaseSource method "getTestData" I am trying to match the fixture argument passed in each instance and returned the test data parameters accordingly to that instance. 


The sequence I want:
1.	The fixture is discovered and the value of it's argument is saved. 
TestCase1, TestCase2 and  TestCase3
2.	Each method is discovered and the value if its argument is saved.
•	When TesCase1
            o	Test1dataParameter1
            o	Test1dataParameter2

•	TestCase2
            o	Test2dataParameter1
            o	Test2dataParameter2
            o	Test2dataParameter3

•	 TestCase3
            o	Test3dataParameter1

Code: 

  [TestFixtureSource("FixtureArgs")]
    public class FixtureTestParameter
    {
        string eq1;


        static object[] FixtureArgs = {
        new object[] { "TestCase1"},
        new object[] { "TestCase2"},
        new object[] { "TestCase3"}
    };

        public FixtureTestParameter(string eq1)
        {
            this.eq1 = eq1;

        }


        [TestCaseSource("getTestData")]
        public void TestMethod(string data)
        {
            // Common code for all testcases
        }


        public static object[] getTestData()
        {
            object[] testData = null;
            if(eq1 = "TestCase1")
            {
                testData = new object[2];
                testData[0] = "Test1dataParameter1";
                testData[1] = "Test1dataParameter2";

            }
            else if (eq1 = "TestCase2")
            {
                testData = new object[3];
                testData[0] = "Test2dataParameter1";
                testData[1] = "Test2dataParameter2";
                testData[2] = "Test2dataParameter3";

            }
            else if (eq1 = "TestCase3")
            {
                testData = new object[1];
                testData[0] = "Test3dataParameter1";
                

            }
            else
            {
                testData = new object[2];
                testData[0] = "defaultDataParameter1";
                testData[1] = "defaultDataParameter2";
            }
            return testData;
        }
    }

I am getting issue as object reference is required for non-static field eq1 when using in getTestData() method

I cannot make eq1 as static as we discussed above and also cannot make getTestData() as non-static because TestCaseSource attribute must refer to static field or method.

Please help to achieve above condition and let me know in case above is not clear and I could explain in more detail?

**Comment by CharliePoole** [comment]
As I explained, this is simply not possible. The flow of data is

```
    TestFixtureSource
                   v
          FixtureConstructor
                      v
                    Saved Data
                         v
                      Test Method
                       ^
                 Arguments
                   ^                                                       |                                                                   
       TestCaseSource
```
It's up to the test method to put the two sources together.

You have not shown any example of your test methods. Perhaps if you do that I can give you a better example to work from.

**Comment by jnm2** [comment]
@amittrehan44 I added [code fences](https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting) to help with the readability of your code blocks.

**Comment by akaer** [comment]
I think the point here is that the following **was** working with Nunit framework 2.6.4:

```C#
    [TestFixture("A")]
    [TestFixture("B")]
    [TestFixture("C")]
    public class DynamicTests
    {
        public string FixtureArgument;

        public DynamicTests(string fixtureArgument)
        {
            FixtureArgument = fixtureArgument;
        }

        [TestCaseSource(nameof(TestDataProvider))]
        public void SimpleTest(string testArgument)
        {
            Console.WriteLine("Test argument:" + testArgument);
            Assert.That(testArgument, Is.StringStarting(FixtureArgument));
        }

        public IEnumerable<TestCaseData> TestDataProvider()
        {
            yield return new TestCaseData(FixtureArgument + "_X");
            yield return new TestCaseData(FixtureArgument + "_Y");
            yield return new TestCaseData(FixtureArgument + "_Z");
        }
    }
```

But with the recent changes with TestCaseSource beeing static this won't work anymore.

**Comment by jnm2** [comment]
The change was released in https://github.com/nunit/nunit/releases/tag/3.0.0-beta-3.

Existing discussion is in the PR: https://github.com/nunit/nunit/issues/698

**Comment by akaer** [comment]
Yes I know but okay... my usage of "recent changes" wasn't such a good choice ;-)

Just for reference... I hacked together a working example for version 3.9 that misuses the properties

```C#
    [TestFixtureSource(nameof(FixtureDataProvider))]
    public class DynamicTests
    {
        private const string Storename = "dummy";

        public static string FixtureArgument;

        private static int _cntFixtureDataIterator = 1;

        public static IEnumerable<string> FixtureDataProvider()
        {
            TestContext.CurrentContext.Test.Properties.Add(Storename + 1, "A");
            yield return TestContext.CurrentContext.Test.Properties.Get(Storename + 1).ToString();

            TestContext.CurrentContext.Test.Properties.Set(Storename + 2, "B");
            yield return TestContext.CurrentContext.Test.Properties.Get(Storename + 2).ToString();

            TestContext.CurrentContext.Test.Properties.Set(Storename + 3, "C");
            yield return TestContext.CurrentContext.Test.Properties.Get(Storename + 3).ToString();
        }

        public DynamicTests(string fixtureArgument)
        {
            FixtureArgument = fixtureArgument;
        }

        [TestCaseSource(nameof(TestDataProvider))]
        public void SimpleTest(string testArgument)
        {
            Console.WriteLine("Test argument:" + testArgument);
            Assert.That(testArgument, Does.StartWith(FixtureArgument));
        }

        public static IEnumerable<TestCaseData> TestDataProvider()
        {
            var storeValue = TestContext.CurrentContext.Test.Properties.Get(Storename + _cntFixtureDataIterator);

            yield return new TestCaseData(storeValue + "_X");
            yield return new TestCaseData(storeValue + "_Y");
            yield return new TestCaseData(storeValue + "_Z");

            _cntFixtureDataIterator++;
        }
    }
```

**Comment by jnm2** [comment]
If you have a real-world use case, maybe we should start a feature request "Generating test cases depending on fixture arguments" so that we can consider options.
It would make sense to me to loosen the restriction so that `TestFixtureSource`  and `ValueSource` on constructor parameters require a static member, but `TestCaseSource` and `ValueSource` on test method parameters can be either static or instance.

**Comment by CharliePoole** [comment]
@akaer Yes. That would work in 2.6.4. But NUnit 3 was widely written about as a complete new start, with breaking changes and this was one of them. The problem with using instances of the test class to generate data is that it involved creating and caching multiple instances of the class during the load. Multiple because you might have more than one constructor. Cached, in case you used the same source in multiple methods. This was very complicated and was preventing progress on other features. In fact, `TestFixtureSource` __is__ one of those very features.

In retrospect, I think I should have removed the single argument form of `TestCaseSourceAttribute`, forcing you to specify the Type that contains the data source. That would have made it much clearer that data sourcing is __not part of the execution cycle__ of the test. NUnit has no problem handling static sources within the same test class, but it seems to end up confusing users! Be that as it may, we are not going to change now, although I wouldn't oppose deprecating the form.

WRT your nunit 3.9 example... if it's working, it is doing so because of a bug for which we haven't yet released a fix. It's not intended that you should be able to change the real test through `TestContext` and `TestContext.Text` is actually a facade for that reason. However, `TestContext.Test.Properties` is not. It accidentally exposes the internals of the `TestFixture` that is used to run your test. We're in the process of fixing that.

What's happening in the code is that you are storing the data in a pseudo-`TestExecutionContext` (pseudo because we are not actually running the tests yet) and retrieving it from the same place in your test case data generation. It's an accident of implementation that it works. However, if we change the implementation, you can do the same thing by creating a general context that is accessible to both the fixture source and the data source. I don't think what you are doing would work, however, if you tried to do it for more than one test fixture with different data. I believe they would all be using the same pseudo-context.

In the end, it's much simpler to use the framework as it's designed. Or write another framework. 😄

**Comment by CharliePoole** [comment]
@jnm2 That would be a step back to the chaos we had when we did allow the data source to be an instance variable. IMO, we need to move ahead, which probably involves implementing __true__ dynamism in test case generation as is described in several existing issues.

In terms of a test case for this particular usage, it would have to be one that cannot be handled otherwise. The example we have in front of us can be done pretty simply...

```C#
        [TestCaseSource(nameof(TestDataProvider))]
        public void SimpleTest(string testArgument)
        {
            var usefulValue = FixtureArgument + testArgument;
            // Proceed to use usefulValue
        }
```

That's how tests were intended to use fixture arguments.

**Comment by jnm2** [comment]
@CharliePoole What if the number of test cases should vary depending on fixture arguments? That's not hard for me to imagine. If someone ends up needing that in the real world, why not open that back up?

I'm not familiar with the chaos. So long as static members are still required for TestFixtureSource and for ValueSource on constructor parameters, where does the complexity come from?

> IMO, we need to move ahead, which probably involves implementing true dynamism in test case generation as is described in several existing issues.

Would you link them, please?

**Comment by CharliePoole** [comment]
@jnm2 The OP never seems to have demonstrated the need, as far as I can see. I understand that he is asking for us to provide a __solution__ that he wants to use, but we already have a different solution: the code in the test case itself makes any combination of member values and argument values that are needed. This seems to provide for everything necessary so long as we are still talking about static
test cases, generated before - possibly long before - execution time.

```
<meta>
Even though we all know about the "five why's" it's hard to get developers to talk about why 
they need something. It's up to us to make it happen when wearing our issue-reviewing hats.
</meta>
```

The chaos I'm talking about predates `TestFixtureSource`. Back then, we only had fixture arguments on the `TestFixtureAttribute`. We had the full range of argument attributes for test methods.

I can't briefly encapsulate years of discussion that took place on other platforms. Short story, however, is this... Test case generation takes place a long time before execution - in computer time, that is. You may generate the tests and display them in the gui and then go to lunch. When you come back you press run - silly example, but it has helped some people grok this.

The outcome of this time gap is that the instance of the fixture that was used to generate the test data is __not__ the same instance that will eventually be created in order to use it. It simply cannot be because the executing instance needs to be created in the context of the executing instances of higher level tests. 

Other things came along to make it more complicated as NUnit grew. At first, fixtures only had a default constructor. We would cache an instance of the fixture so we didn't have to generate the data more than once, at least for fields and simple properties. Then we added arguments to the constructor, so we had to modify the cache to allow for multiple instances, one per set of args. All of these instances were released at the end of the load phase, of course, but it was hard to get users to understand that.

If I could start from scratch, classes that generate data (factories) would be separate from the class containing the test in all cases except where the data is provided directly in the attribute constructor.

In NUnit design discussions, all of the above has always been called "static test case generation", including when we used instance members to do it. It's static because all the test data is generated once, before any execution starts. Then those tests are used, unchanged for each run.

Dynamic test case generation - in our context - has meant that no cases are generated until execution starts. So, in a gui for example, you might see just one node for the method until you ran the tests. That node would then be populated with the individual cases generated. When you re-ran the tests, you might get the same arguments or different arguments. There could be different attributes that did one or the other. This is one of the oldest issues in the entire project. See #7.

**Comment by jnm2** [comment]
> we already have a different solution: the code in the test case itself makes any combination of member values and argument values that are needed.

One of the reasons I was asking for test case parallelism was to enable dozens of long-running integration tests to run in parallel as test cases. There's also the convenience of repeatedly running or debugging just the test case(s) you want while developing. These things are very real to me. So even if the five whys determine for now that the user can stop using the test case feature because it's not flexible enough for that task, I'm still going to be aware of that as an unnecessary lack in the test case feature. I subjectively want the framework to feel nice to use and to feel rational.

For example, it's rational to me that an instance member is optimally located to provide test cases for test methods. Not because I expect the instance to be shared between them—I don't—but because the constructor arguments are stored as instance fields.

Re: going to lunch between discovery and execution. I deal with test case differences at discovery and execution time very frequently. The discrepancies which occur are not a problem. The discovery-time listing is so useful to me that I cannot imagine using a dynamic test case feature if it meant that test cases were not available at discovery time and I could not pin specific ones.

**Comment by amittrehan44** [comment]
>  The OP never seems to have demonstrated the need, as far as I can see. I understand that he is asking for us to provide a solution that he wants to use, but we already have a different solution: the code in the test case itself makes any combination of member values and argument values that are needed

In framework I am making using nunit, test cases vary depending on fixture arguments

Here is how I solved the issue by using conditional statement in test method, to compare text fixture source  value to test case source value and execute if they match and ignore if didn’t.
 
But issue here is each instance of test fixture will be execute test method number of times which I do not want and will affect performance and  if I get to use this conditional statement in testcase source method I do not have to return the parameters to assert ignore in test method

Example Below:
Test Fixture instance with “TestCase1” is executed 6 times for all parameters of other tests as well (TestCase2 and Test Case3) and have to use assert ignore in test method whereas if I can use fixture argument  TestCase1 in test case source method I could have run this test method only 2 times.

```c 
[TestFixtureSource("FixtureArgs")]
    public class FixtureTestParameter
    {
        string eq1;


        static object[] FixtureArgs = {
        new object[] { "TestCase1"},
        new object[] { "TestCase2"},
        new object[] { "TestCase3"}
    };

        public FixtureTestParameter(string eq1)
        {
            this.eq1 = eq1;

        }


        [TestCaseSource("getTestData")]
        public void TestMethod(string data, string testCaseName)
        {
            if (eq1 == testCaseName)
            {
                Assert.Pass("Matchfound: " + testCaseName);
            }
            else
            {
                Assert.Ignore("Not a right Match: " + eq1 + " and " + testCaseName);
            }
        }


        public static object[] getTestData()
        {
            object[][] testData = new object[6][]; ;

            testData[0] = new object[2];
            testData[0][0] = "Test1dataParameter1";
            testData[0][1] = "TestCase1";

            testData[1] = new object[2];
            testData[1][0] = "Test1dataParameter2";
            testData[1][1] = "TestCase1";

            testData[2] = new object[2];
            testData[2][0] = "Test2dataParameter1";
            testData[2][1] = "TestCase2";

            testData[3] = new object[2];
            testData[3][0] = "Test2dataParameter2";
            testData[3][1] = "TestCase2";

            testData[4] = new object[2];
            testData[4][0] = "Test2dataParameter3";
            testData[4][1] = "TestCase2";

            testData[5] = new object[2];
            testData[5][0] = "Test3dataParameter1";
            testData[5][1] = "TestCase3";

            return testData;
        }
    }

**Comment by CharliePoole** [comment]
@jnm2 It's as simple as this: I don't know what you want to do that can't be done fairly easily right now. This could be a failure of vision on my part. If so, it's your role __as a user__ to set me straight by providing a reasonable example of something you want to do. 

Of course, if the example is code you want to write that currently doesn't work, I may ask __why__ you want to do it that way, rather than to use the means already available. I might ask you up to five or more levels of recursion, in fact! That's where the five why's come in. They don't "determine" anything but are an information gathering technique when dealing with unexpressed needs. I'm strongly rooted in the belief that any reasonable need can be explained so others can understand it.

What kind of real-world problem makes it impossible to use the TestCase feature as you said?

@amittrehan44 Your particular use of the feature is not something we particularly want to support, IMO, at least if I understand correctly what you are doing. It looks as if you want one method to do the work of many different tests by doing different things depending on the arguments provided to the fixture. NUnit is designed around the idea that each different test is a different method. While it's possible for you to force NUnit to run all tests as a single method, it doesn't seem to me that we want to encourage such use. If I misunderstood, please set me straight. 😄 

That's not to say that there are no __other__ uses for combining fixture and test case arguments. I'm just trying to keep this issue down to the particular usage you wanted to make of it.

**Comment by glenner003** [comment]
Hi,

Can I provide a case to demonstrate the need for this feature?

We have a tool that creates documents with a variable set of pages.

We currently have a test fixture with one test case, that  generates a document and tests it page by page.
The test cases are generated by a TestCaseSource that fetches available sources to generate these documents from.

The issue we have is that when the test fails for a page, further pages remain untested, hiding possible other issues.

To resolve this, I was looking for a solution where I can have a test fixture per document, with a one time setup generating the document and a test case that is generated for each page in the document.

But since there is no valid way to pass information about the generated test fixture to the TestCaseSource  this is not possible.

**Comment by CharliePoole** [comment]
It's an interesting case, better than any I've seen so far.

For many years, we've had the goal of dynamic test cases, generated right before we run them. That feature, if it existed, would do the job for you.

But making fixture args available when generating test cases might be simpler in this case.

**Comment by glenner003** [comment]
I don't think the dynamic test case will help me here, since I want to generate the document only once and use it in a testcase per page.

With the dynamic test case I still have to recreate the document per test case.

According to the specs this would be the sequence used to generate test cases:

-  Create test fixture instance
-  Run TestFixtureSetUp
-  Generate dynamic test cases
-  For each test case
-      Run SetUp method
-      Run Test method
-      Run TearDown method
-  Run TestFixtureTearDown
-  Dispose and destroy the test fixture instance

While I would need something alike this:

- Generate test fixtures
- For each fixture 
-     Generate test cases
-     Create test fixture instance
-     Run TestFixtureSetUp
-     For each test case
-         Run SetUp method
-         Run Test method
-         Run TearDown method
-     Run TestFixtureTearDown
-     Dispose and destroy the test fixture instance

**Comment by mstancombe** [comment]
"But making fixture args available when generating test cases might be simpler in this case."

This is something that would have been handy for myself. I have a case where I want to enumerate a master directory recursively, then run tests for each item in each directory.  I would like each directory to be it's own fixture, and each item in the folder to be it's own test, as I could then parallelize the fixtures safely, (and it also looks nicer in test explorer).

From what I understand, the key thing required to make this happen would be for the TestCaseSource method to support taking the fixture args as well, potentially by convention or attributing a parameter.

Something like this would be very useful:

public static IEnumerable\<FolderSpec\> GetFoldersToProcess()
 {
 }

 public static IEnumerable\<TestSpec\> GetFilesToProcess([FixtureArguments] FolderSpec folderSpec)
 {
 }
 
 
Thoughts?

**Comment by jnm2** [comment]
Seems useful and no alternatives come to mind so far. @nunit/framework-team what do you think?

**Comment by ChrisMaddock** [comment]
FYI, there's an open issue which I believe is the same thing: https://github.com/nunit/nunit/issues/2950

If we can work out a clean way to implement this, I'm a fan. I want to use this feature myself! 😄
