### ISSUE TITLE
Issueing warning and failing a test from a TestCommand

### ISSUE THREAD

**Issue by MaxKot** [nunit/nunit#2716]
## Summary

`TestExecutionContext.CurrentResult.SetResult (ResultState.Failure)` does not seem to work if the test result contains warnings issued with `TestExecutionContext.CurrentResult.RecordAssertion (AssertionStatus.Warning, message)`.

## Details

I am testing a wrapper for a native library. I've created a custom attribute and a TestCommand wrapper that sets up a custom memory allocator that tracks allocations and deallocations. When the inner TestCommand finishes I issue a warning for each unfreed allocation and, if any, set test result to failure.

If I set test result to failure with `RecordAssertion (AssertionStatus.Error, message)` I get both the warnings and the failure.
If I use `SetResult (ResultState.Failure)` but don't add any warnings I receive the failure.
If I use `SetResult (ResultState.Failure)` and add warnings then I only get the warnings.

Is is a bug or this behavior is by design? If it is by design, is there any instruction in the Wiki on how extensions should inspect and modify test outcome?

**Comment by CharliePoole** [comment]
This is not something we have documented because the issue hasn't come up before. I hadn't assumed that user-created wrappers would call low-level methods like RecordAssertion, but that they would go through Assert.Fail instead.

What is happening is that your code is running to completion normally, without any exception thrown. NUnit then deduces the final result based on what assertions have been recorded. Calling SetResult is useless if there are any assertion results recorded because NUnit will actually use them to determine the final result of the test.

Since you want unfreed allocations to cause a failure, you should record assertions marked as failures. Error is better reserved for unexpected exceptions thrown, just as is used by NUnit. Assuming that your test otherwise passed, NUnit will still fail the test if there are failed assertions recorded. This functions exactly as if you had used an assertion within a multiple assert block.

In fact, I think you could actually do that. Use Assert.Multiple and Assert on each allocation having been freed. However, if done correctly, RecordAssertion will do the job.
