### ISSUE TITLE
Can TestContext capture the command line arguments passed in to the console runner?

### ISSUE THREAD

**Issue by ocmyhome** [nunit/nunit#2756]
I'd like to capture the command line arguments that are passed in to the console runner and was hoping TestContext could provide this information.  I've tried using TestContext.Parameters but didn't get what I needed.

Specifically I'd like to capture the "--where" parameter value, so it can be reported on what category(ies) were run for the test run

Thanks,

**Comment by CharliePoole** [comment]
`TestContext.Parameters` exposes what is entered on the command-line using the `--params` option. These are what we call "run parameters" and are intended to be interpreted and used by your tests.

General command-line parameters depend on the runner you are using, so having your test examine those parameters would mean that the test has to be written to be aware of all possible runners and their various options.

The console runner displays the `--where` filter in its output and also stores all the command-line options in the TestResult file that is saved. Ideally, you should use that XML result to report on the run, rather than trying to do it from inside your tests.

At the time your test is running in the framework, a filter has already been created, which is used to decide what tests to run. If really needed, I suppose that filter could be made available to the tests in some sort of text representation. However, since the info is already being published, it may make more sense for you to leverage that rather than trying to handle it within the tests.

**Comment by ocmyhome** [comment]
Thanks @CharliePoole for the input.  I think I'll simply put the category into a param and use it w/ in the test.  That should get me what I want.  I'll definitely look into using the XML result for logging going fwd.  Thanks!
