### ISSUE TITLE
Broken `char` comparison in v3.7 and higher

### ISSUE THREAD

**Issue by dgg** [nunit/nunit#2757]
Hi,

I just found out that there is a problem comparing chars that happened from 3.7.

Take this assertion:
```csharp
Assert.That('2', Is.GreaterThan('3'));
```

When run in 3.6.1, the assertion will (correctly) fail:
```sh
Test 'whatever' failed:   Expected: greater than '3'
  But was:  '2'
```

When the same assertion is run in 3.7.0 or higher, it will not fail, which, in my opinion, is wrong as '2' is definitely not greater than '3' and neither are their numeric values (50 and 51).

**Comment by rprouse** [comment]
The following also passes, so it seems like `GreaterThan` silently always passes with chars now.

```c#
Assert.That('3', Is.GreaterThan('2'));
```

**Comment by dgg** [comment]
@mikkelbu that line looks fishy as hell, but it was the way it is already in 3.6.1:

https://github.com/nunit/nunit/blob/3.6.1/src/NUnitFramework/framework/Constraints/NUnitComparer.cs#L58

And it worked back then.

**Comment by CharliePoole** [comment]
I think the code has been broken like this for as long as it has existed. In the past, it was only used for equality comparisons. GreaterThan and LessThan comparisons were made using operators.

Now this code is also used for GreaterThan and LessThan, so we have to return -1 as well when it's appropriate, not just 0 or 1.

**Comment by jnm2** [comment]
Would it make sense to remove those two lines so that it falls through to these lines?
https://github.com/nunit/nunit/blob/d03e93c8f25170a8ff48e80863a3fe6fd294613a/src/NUnitFramework/framework/Constraints/NUnitComparer.cs#L64-L65

**Comment by CharliePoole** [comment]
It won't fall through but will be treated as numeric. That's why the code is where it is. Numeric order is wrong for some cultures.

**Comment by jnm2** [comment]
Would it make sense to never consider it numeric, i.e. remove this line also?
https://github.com/nunit/nunit/blob/d03e93c8f25170a8ff48e80863a3fe6fd294613a/src/NUnitFramework/framework/Constraints/Numerics.cs#L80

**Comment by CharliePoole** [comment]
@jnm2 It's fairly common, especially in older code to compare characters to numbers...

```C#
if (c > 127)
    ...
Assert.That(c, Is.GreaterThan(127);
```

The code we have in NUnit is an outgrowth of people trying to do that sort of thing over the years. 

At some point, numerics were added ahead of everything else due to an issue. At some other point, chars were added to numerics due to an issue report. At yet another point, the char comparison was added due to an issue.

We can rethink the whole approach, but it's hard to duplicate years of both thinking and error reporting by users without a great deal of analysis.

Ideally, stuff like this should have been added with an explanatory comment. I guess we figured that somebody would always be around to remember the reason. 😞

**Comment by jnm2** [comment]
@CharliePoole Ah, that makes sense. We need to consider it numeric so that we do numeric type coercion between the expected and actual types.

If we remove only the two lines which I originally asked about, I think that (plus tests) would resolve the issue. Looks like it would fall through to this line which would do the right thing:

https://github.com/nunit/nunit/blob/d03e93c8f25170a8ff48e80863a3fe6fd294613a/src/NUnitFramework/framework/Constraints/Numerics.cs#L384

**Comment by CharliePoole** [comment]
No, I'm afraid it wouldn't, although it would take me a while to find the original example that caused this. We've been through several reorganizations of the code and at least two changes of where we host and record our issues since then.

IIRC the problem only arises when using certain cultures and or character sets. The upshot is that the desired "order" of two characters doesn't necessarily match the numeric order of their representation.

Any reason you can see not to make the obvious fix?

```C#
return (char)x == (char)y ? 0 : (char)x > (char)y ? 1 : -1; 
```

**Comment by jnm2** [comment]
I'd prefer `return x.CompareTo(y);` since that has always been [numeric (ordinal)](https://referencesource.microsoft.com/#mscorlib/system/char.cs,b0e89607f165d052), and therefore identical.

I'm pretty sure that `return Convert.ToInt32(x).CompareTo(Convert.ToInt32(y));` is also numeric. If so, the simple fix would seem to be deleting those lines. If there is any sensitivvity to culture, we should try to put tests on it.

**Comment by jnm2** [comment]
I wasn't thinking, but of course this is a numerical comparison:

https://github.com/nunit/nunit/blob/d03e93c8f25170a8ff48e80863a3fe6fd294613a/src/NUnitFramework/framework/Constraints/Numerics.cs#L384

Meaning that all the options we've discussed so far end up doing a numerical (ordinal) comparison.

**Comment by jnm2** [comment]
The reason I don't want to special-case `char` there is that `return (char)x == (char)y ? 0 : (char)x > (char)y ? 1 : -1; ` and [`return x.CompareTo(y);`](https://referencesource.microsoft.com/#mscorlib/system/char.cs,b0e89607f165d052) both behave as ordinal (numeric) comparisons no matter what the culture settings are, as well as:

https://github.com/nunit/nunit/blob/d03e93c8f25170a8ff48e80863a3fe6fd294613a/src/NUnitFramework/framework/Constraints/Numerics.cs#L384

Other than performance, all three behave the same in all circumstances so far as I can tell. So my hesitation with the manual calculation is that deleting code is awesome when we can get away with it, and that it seems inconsistent to special-case `char` and not, for example, `byte`.

**Comment by jnm2** [comment]
If our current behavior is wrong and we *are* supposed to be doing a culture-sensitive comparison, we'll have to do `x.ToString().CompareTo(y.ToString(), StringComparison.CurrentCulture)`. I had to do this once and remember being surprised that the heap allocation was the only way to to a correct comparison.

**Comment by CharliePoole** [comment]
Look, I'm not part of this but am only making observations, which may or may not be helpful, may or may not be what you want to hear. When it comes to two chars, I don't think we want a numeric comparison.

The fact is, `char` __is__ special. It has it's own rules of order. In any case, the code that's there was put in to fix a bug. I would assume that it should stay until somebody can determine that the bug it fixes will no longer arise. I think that whoever wants to fix this should do the research into why the code was put there in the first place.

**Comment by jnm2** [comment]
I can see that the culture-sensitive comparison would be a departure from the .NET Framework and the recent history of NUnit, but I don't really have a preference.

If we go with a culture-sensitive comparison, the implementation will be forced to `.ToString()` and I'd ask if `char` could be removed from our `Numerics` helper. On the other hand if we go with a numeric comparison, deleting those two lines (and adding tests) seems like the simplest fix.

The special case was added here: https://github.com/nunit/nunit/pull/657

**Comment by jnm2** [comment]
I can see that the culture-sensitive comparison would be a departure from the .NET Framework and the recent history of NUnit, but I don't really have a preference. Our string comparison already has non-standard defaults; it's just stuff people have to know about.

If we go with a culture-sensitive comparison, the implementation will be forced to `.ToString()` and I'd ask if `char` could be removed from our `Numerics` helper. On the other hand if we go with a numeric comparison, deleting those two lines (and adding tests) seems like the simplest fix.

This special case was added at the same time that [`char`](https://github.com/nunit/nunit/pull/657/files#diff-b70970ef2c30eded4abafb95604ebb92R57) was added to `Numeric`](https://github.com/nunit/nunit/pull/657/files#diff-098904f281a821598746ac9f8e65445cR79), in #657.

One of these two changes was redundant, but it wasn't caught during the review.

**Comment by jnm2** [comment]
This special case was [added at the same time](https://github.com/nunit/nunit/pull/657/files#diff-b70970ef2c30eded4abafb95604ebb92R57) that [`char` was added to `Numeric`](https://github.com/nunit/nunit/pull/657/files#diff-098904f281a821598746ac9f8e65445cR79), in #657. One of these two changes was redundant, but it wasn't caught during the review.

The issue that was being addressed was [int and char do not compare correctly?](https://github.com/nunit/nunit/issues/524), so it's these lines that been redundant since being introduced: 

https://github.com/nunit/nunit/blob/d03e93c8f25170a8ff48e80863a3fe6fd294613a/src/NUnitFramework/framework/Constraints/NUnitComparer.cs#L58-L59

Prior to this change, NUnit had been doing an ordinal (numeric) comparison:

https://github.com/nunit/nunit/blob/70ebabce2d23dd8789eb719bfba9dc793a4bc4e2/src/NUnitFramework/framework/Constraints/NUnitComparer.cs#L60-L61

**Comment by jnm2** [comment]
Last bit of history available to from here is that NUnit has been doing a numeric comparison for `char` since the [beginning of the source history](https://github.com/nunit/nunit/commit/e94d8a9ba9bd27fa302d2712d36a737afb172060#diff-65c094609d0bd5474b4c286f051c088cR65), starting from 2.9.1 or earlier and continuing to the current master.

**Comment by CharliePoole** [comment]
That's nice research! The two redundant changes are interesting.

**Comment by jnm2** [comment]
@CharliePoole In your estimation, should I submit the fix I was talking about and tests?

**Comment by CharliePoole** [comment]
Sounds good to me!
