### ISSUE TITLE
Test fails with "No arguments were provided" error when no values returned from IParameterDataSource

### ISSUE THREAD

**Issue by MaceWindu** [nunit/nunit#2759]
We have a test that takes two parameters, seeded with IParameterDataSource attributes.
One parameter is an enum and always has values, second parameter is a string and could have 0 to many values based on test run configuration.

Problem is that when this set is empty, nunit (both VS adapter and console runner) report failed/invalid test with "No arguments were provided" message.
For now I found workaround for it - return empty string as an extra value and return from test if such value passed to test method.

I think such tests should not fail test run (allways, or maybe add a boolean property to IParameterDataSource interface or new method attribute).

**Comment by CharliePoole** [comment]
This seems to duplicate #1933, which we had fixed. What happened?

**Comment by MaceWindu** [comment]
I will provide small repro in 5-10 minutes. Maybe there is something special in our test

**Comment by CharliePoole** [comment]
We went down a rabbit hole discussing Theories on #1933, so maybe we ended up missing something. However, it has tests that pass... 😕

**Comment by MaceWindu** [comment]
Ok, here you are:
```cs
using System.Collections;
using NUnit.Framework;
using NUnit.Framework.Interfaces;

public class Nunit2759Test
{
    public enum ValuesEnum
    {
        Value1
    }

    public class VariableValues : DataAttribute, IParameterDataSource
    {
        public int Count { get; set; }

        IEnumerable IParameterDataSource.GetData(IParameterInfo parameter)
        {
            for (var i = 0; i < Count; i++)
            {
                yield return i.ToString();
            }
        }
    }

    [Test]
    public void Test2759ShouldRun([VariableValues(Count = 1)] string context, [Values] ValuesEnum values)
    {
    }

    [Test]
    public void Test2759MustSkip([VariableValues(Count = 0)] string context, [Values] ValuesEnum values)
    {
    }
}
```

**Comment by MaceWindu** [comment]
Looks like #1933 doesn't cover this scenario

**Comment by CharliePoole** [comment]
Looks to me as if the #1933 fix only dealt with method attributes that don't return anything. Try adding `[Combinatorial]` explicitly on the test method to see if you can trick it. NUnit actually pretends there's one on it in order to generate the test cases, but the code in the #1933 fix is likely not aware of that.

**Comment by MaceWindu** [comment]
Yep, `[Combinatorial]` works!

**Comment by CharliePoole** [comment]
That's due to https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/Builders/DefaultTestCaseBuilder.cs#L148

Adding '[Combinatorial]` explicitly results in setting `hasBuildersSpecified` to `true'. Should be an easy fix for anyone who wants to take it on.

**Comment by DaiMichael** [comment]
Hello, I'm happy to look at this as a first issue.

I have a working solution but not 100% which option is wanted / best.

1) Add check for `[DataAttribute] `on method and use `BuildParameterizedMethodSuite` (https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/Builders/DefaultTestCaseBuilder.cs#L148), have a working solution (i.e. works as adding `[Combinatorial]`), passes tests and doesn't break any :)

2) Create new `ITestBuilder` for `[DataAttributes]` method and use that this builder, not done but looks straightforward.

Finally should this test be "skipped" with a comment or just ignored, currently if we put` [Combinatorial]` on the test it is just as if it isn't there. This behaviour IMHO would make it look like the test doesn't exist which might be confusing. I'd suggest it is marked "Skipped" and say message : "Skipped as 0 paramaters supplied." . If this is desired option 2 is best solution and happy to do it this way.

I have master pulled I assume I should create a branch for this issue?

Thanks for help / understanding / patients!

**Comment by rprouse** [comment]
@DaiMichael thanks for the offer of help. I am going to assign myself to this issue to work with you.

First, you say you have master pulled. If you haven't already, create a fork of the repository and work off your fork. From there you will create a branch to work on. You can't push branches to this repository unless you are a team member.

Don't set the results of tests with 0 parameters to "skipped", change the result to warning like was done for #1933. See that PR for more information.

Your solutions 1 and 2 are not entirely clear to me what you mean, but 1 seems most appropriate from what I understand. Please ensure that you have appropriate unit tests. Once again, look at the fix for #1933 if you need help there.

**Comment by DaiMichael** [comment]
@rprouse Thanks for the pointers. I re-set everything up correctly this time with my own fork and branch for the issue. I took a look at #1933 as well and I understand the "Skipping" or not wanting it now, that makes sense.

I have created a test cases
https://github.com/DaiMichael/nunit/blob/issue-2759/src/NUnitFramework/tests/Attributes/DataAttributeTests.cs

My original solution is very subobtimal, I will post up when I have a solution I'm happy with, next day or so.

**Comment by rprouse** [comment]
Thanks for the update. Let me know if you need any help.

**Comment by DaiMichael** [comment]
@rprouse I have checked in my change and it pasts the tests and doesn't break any.

https://github.com/DaiMichael/nunit/blob/issue-2759/src/NUnitFramework/framework/Internal/Builders/DefaultTestCaseBuilder.cs#L149

This was my original idea, hope it isn't terribe :)

**Comment by jnm2** [comment]
@DaiMichael Not terrible at all!

Sorry for the bother- we just merged a change that has some minor conflicts with your new code. `IMethodInfo` is replaced with `FixtureMethod` (`method.Method` will get you the `MethodInfo` if you want to pass just that to `HasMethodGotDataAttributeParameters`). `GetCustomAttributes` will become a cross-platform convenience extension method `HasAttribute`.

Rather than merging master into the PR branch, I recommend rebasing for PR branches. With merges, the master commits get included in the diff and it becomes hard to review on GitHub.
`git pull -r upstream master` will do everything for you, if you named the nunit/nunit remote `upstream`. There will be a merge conflict with a single line. It'll stop on the merge conflict to let you manually absorb the change in the underlying master branch. Visual Studio and VS Code have great interfaces for resolving them. After editing that and adding the changes, then `git rebase --continue`. If you have any questions please let us know!

**Comment by DaiMichael** [comment]
@jnm2 

No problem, usual with conflicts, I need to learn git a bit better anyway, using Mecurial in work at the moment but I'm old skool vc, so getting used to the distributed vc. 

https://github.com/DaiMichael/nunit/blob/issue-2759/src/NUnitFramework/framework/Internal/Builders/DefaultTestCaseBuilder.cs#L136

I had to make changes to the Tests as well.

https://github.com/DaiMichael/nunit/blob/issue-2759/src/NUnitFramework/tests/Attributes/DataAttributeTests.cs

All compiles, no broken tests and new ones work as previous.

Thanks for the advice / help on the rebase, let me know if I did something wrong, I'm reading the book as we speak. I'm happy to pick up some more issues, I'll take a look at the stack.

**Comment by jnm2** [comment]
@DaiMichael Great, thanks for doing that!

It looks like after you did the rebase, you merged the old branch and newly-rebased branch together:
[`master...DaiMichael:issue-2759`](https://github.com/nunit/nunit/compare/master...DaiMichael:issue-2759#commits_bucket) See you the four commits are repeated a second time and then the ninth commit is a merge commit joining the two sets of four? When you rebase, you expect to see just the new four. Not the old four, and not a merge (two-parent) commit.

The commit ID when you were finished rebasing was [`2560775`](https://github.com/nunit/nunit/commits/2560775524ac1e3d4e9b739da0d8e6a049a940f6). You can get it back to an ideal state by resetting the branch pointer to point at 2560775:`git checkout 2560775

**Comment by jnm2** [comment]
@DaiMichael Great, thanks for doing that!

It looks like after you did the rebase, you merged the old branch and newly-rebased branch together:
[`master...DaiMichael:issue-2759`](https://github.com/nunit/nunit/compare/master...DaiMichael:issue-2759#commits_bucket) See you the four commits are repeated a second time and then the ninth commit is a merge commit joining the two sets of four? When you rebase, you expect to see just the new four. Not the old four, and not a merge (two-parent) commit.

The commit ID when you were finished rebasing was [`2560775`](https://github.com/nunit/nunit/commits/2560775524ac1e3d4e9b739da0d8e6a049a940f6). You can get it back to an ideal state by resetting the branch pointer to point at 2560775:
```
git checkout 2560775 -B issue-2759
git push -f
```

The first command overwrites your current branch `issue-2759` with a new branch pointing at 2560775 as the new tip, and then it switches you to that branch.
The last command forces your `origin/issue-2759` branch to match your local branch. `-f` (`--force`) is needed because you are forcing the origin side to lose five commits. This is normal after a rebase; we want to lose the original four commits and just keep the new rebased ones. In your case, we will also lose the merge commit, which is good.

Does the above make sense? Git is notoriously hairy, and I wish the it wasn't such a hassle for people. You're new to it and handling it impressively.

When you're ready for the team to review your code, you use the GitHub website to start a pull request back to the master branch in this repo. Again please holler if you have any questions!

**Comment by DaiMichael** [comment]
@jnm2 Thanks again for the help and it is looking correct (fingers crossed) when I did the pull request back to master.
