### ISSUE TITLE
Add OneTimeTearException and OneTimeTearFailed attributes

### ISSUE THREAD

**Issue by antonGritsenko** [nunit/nunit#2779]
Hello all

When NUnit used as integration tests framework will be nice to have similar to OneTimeTearDown attribute, but executes when something goes wrong (test failed or exception occurred) during testing to clean up resources.

Any thoughts on this?

**Comment by CharliePoole** [comment]
Not impossible, but would be a bit of an oddity within NUnit. In general, NUnit provides attributes to mark code to run at a particular point - like after all the subordinate tests have completed.  We don't provide an option to run only when a certain result occurs. 

Rather, the user is expected to detect the result status and act accordingly. IMO, it will keep the interface a lot cleaner if we leave things that way. It only requires a conditional test in the code of your one time teardown.

**Comment by jnm2** [comment]
@CharliePoole Would implementing IDisposable in the fixture give @antonGritsenko guaranteed cleanup?

**Comment by CharliePoole** [comment]
@jnm2 Yes it would. NUnit calls Dispose in that case. However, that's no more no less than what OneTimeTearDown does.

**Comment by antonGritsenko** [comment]
@CharliePoole the problem with OneTimeTearDown is what I have no idea about was everything OK or not. Imaging cases when I need to create a complex object, update and remove it. Depends on something wrong or not logic in OneTimeTearDown  will be different.

**Comment by CharliePoole** [comment]
It's up to you, in designing the test class,  to leave behind sufficient info so that your TearDown code can make the proper decisions. NUnit can't do it for you because it doesn't have specific Information about your class.

I think the discussion might be helped if you could provide an example of code you want to be able to write.

**Comment by antonGritsenko** [comment]
I can't share exact code, but will try to explain. 
We are using NUnit for two purposes: integration testing and debugging based on integration tests (I know, this is not usual approach). At middleware, we have service with methods like "AddObject", "UpdateObject" and "RemoveObject" (and couple more similar). Each of those methods doing a lot of things in different backends (SQL, BLOB, Events etc). 
Also we have tests like "AddObject_Simple", "AddObject_Coplex", "UpdateObject_WihValue" and so on, 3-4 for each method in middleware.  Each test have own order and tests are executes on 1 CPU, so no tests running in same time.

When all those tests are running in batch (regular testing process) then object created, then updated and then removed. We no need to cleanup anything. 

But when tests are used for debug perspective, it could be that test will fail. And in this case we have to cleanup. At the moment this quite hard to implement, because we have no any info in TearDown about was it regular execution or something goes wrong. The only thing that I have in my mind is to wrap each and every test with try-catch and set some flag, but this is nightmare.
Of course, we can implement checking in backends in TearUp\TearDown, but this also not easy.

Hope its clear and make some sense.

**Comment by CharliePoole** [comment]
@antonGritsenko I wasn't asking for __your__ code, which I imagine you can't share, but for __some__ code. Try to create a bit of code that simulates what you do rather than trying to explain completely in words. As a framework written by and for developers, code is our friend. 😄 

Ideally, you would post the code you __wish you could write__, using the feature of NUnit that doesn't actually exist but which you are asking for.

My key lack in understanding this is what kind of checking (which as you say is hard to do) you want NUnit to perform for you. On the surface, it sounds unlikely that NUnit could automatically understand what went wrong in your backend code.

**Comment by rprouse** [comment]
I am closing old uncategorized issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
