### ISSUE TITLE
Extending Nunit framework for custom need?

### ISSUE THREAD

**Issue by HewittVS** [nunit/nunit#2791]
I need to be able to pass a reference object to a test class constructor and use that inside test initialize methods to use them within test methods. I also need to be able to configure test runner and run from some point of invocation like a console application or from button click in a form application. How to achieve this in NUnit framework? In short I need to pass a variable to test class and use it instead of declaring it inside and I should be able to run test runner from my own application. Is this possible? Any help is appreciated.

**Comment by rprouse** [comment]
You could pass strings into the test run using the `--params=Name=Value` command line option and then use those strings in a `TestFixtureSource` to create the reference objects you need and pass them into the constructor of your test class. Something similar to the following,

```C#
estFixtureSource(nameof(TestData))]
public class TestParamsInSource
{
    private readonly string _param;

    public TestParamsInSource(string param)
    {
        _param = param;
    }

    [Test]
    public void TestParameter()
    {
        TestContext.WriteLine($"Parameter: {_param}");
        Assert.That(_param, Is.Not.EqualTo("<unknown>"));
    }

    public static IEnumerable<string> TestData()
    {
        yield return TestContext.Parameters.Get("Param", "<unknown>");
    }
}
```

This just returns straight strings from the `TestData` method and passes them to the constructor, but you can construct any data type you want. You then pass the parameters on the command line like the following,

```bat
nunit3-console.exe -p=Param=Injected Test.dll
```

**Comment by HewittVS** [comment]
Thank you for your answer. I will try this. Any way I can use the test runner to run from my application?

**Comment by rprouse** [comment]
You could use the `NUnit.Engine` API to run the tests from your application, although getting it up and running is not as simple as a few lines of code. You could also use `NUnitLite` which allows you to create self executing tests. You could use that to run your tests from your application, but you will need to be careful because the tests will be running in-process and you can get unpredictable results if any of your code has statics because they will only get initialized on first run. That is just the way .NET works, not NUnit. You could setup AppDomains for your test run to work around that.

Lastly, you could just run the NUnit Console using `Process`, capture output if needed and check the return code to determine if your tests pass or fail. This is probably the simplest option.

I am closing this issue as a question. Feel free to keep posting, we will see your comments.
