### ISSUE TITLE
TestEngineActivator cannot create new TestEngine instances when executing in a .NET Core 2 environment.

### ISSUE THREAD

**Issue by inondle** [nunit/nunit#2794]
I'm having some trouble using the newer Engine API on an ASP.NET Core 2 application. I'm attempting to load a bunch of nunit fixtures from a different project and make their metadata available through a web API.

The failure occurs when attempting to create a new `NUnit.Engine.TestEngine` instance using the `TestEngineActivator.CreateInstance()` method.

When executed in the .NET Core 2 project the line fails with the following error message: `System.MissingMethodException: 'Method not found: 'System.Object System.AppDomain.CreateInstanceFromAndUnwrap(System.String, System.String)'.'`. When it's executed in the .NET Framework context it works as expected. 

I currently have my solution structured so that the code that interprets and loads the nunit data and the API code are in their own projects.

NunitLoader - Target Framework: .NET Framework 4.7.1, OutputType: Class Library
NunitAPI - Target Framework: .NET Core 2.0, OutputType: Console Application

**Comment by rprouse** [comment]
The `Nunit.Engine` is compiled .NET 2.0, so it cannot currently load or run .NET Core. There is a lighter weight .NET Core build of the engine called `nunit.engine.netstandard` that works the same at https://www.nuget.org/packages/nunit.engine.netstandard/

Be aware that there are minor differences in the interface because of differences between .NET Core and full framework. Also be aware that this package will likely be deprecated soon as we merge the work back into the main engine. Once we do that, to update, hopefully you will just need to switch your reference over to the `NUnit.Engine` package with no or minimal code changes.

**Comment by mikkelbu** [comment]
I am closing this as answered. If you have more questions, add it to this issue and we will reopen.
