### ISSUE TITLE
Allow Theory to specify the fields/method to use as Datapoint/DatapointSource

### ISSUE THREAD

**Issue by alexvy86** [nunit/nunit#2795]
I was wondering if there's a reason why `Theory`, `Datapoint` and `DatapointSource` don't work the same way as `Test` and `TestCaseSource`, in the sense that for a particular test, I can specify which field/method to use as its `TestCaseSource` (even field/methods outside of the `TestFixture`). I'd like to be able to do the same for theories.

The situation I ran into is that I'm converting two different tests in the same fixture to theories, they both have the same parameter types, but I want different sets of values passed to each one. Right now if I create two separate properties that return an `IEnumerable<MyType>` (both theories have a parameter of type `MyType`) with the `DatapointSource` attribute on them, both of them would be fed to both theories, which is not what I want to happen.

The workaround for now is to put each theory in its own `TestFixture` with its own `DatapointSource`, but it'd be nicer if we could specify the `DatapointSource` as part of the `Theory` attribute, so it works more like `TestCaseSource`.

**Comment by CharliePoole** [comment]
`Theory` is analogous to `Test`. They both identify a method that is used as a test. They don't specify data at all. `TestCase` and `TestCaseSource` provide sets of arguments to a test method. `Value` and `ValueSource` provide data for a test method parameter, which is combined with other parameters to form test cases.

`DataPoint` and `DatapointSource` are more like `Value` and `ValueSource` since they provide data for a single parameter. They may only be used with theories.

All of the data attributes that are used with a test may also be used with a theory.

When you decide you want to convert a test to a theory, you are deciding two things: 

1) You want the overall theory to pass or fail and only care about the individual case results if there is a failure.
2) You are giving up control of what data is passed via datapoints because your theory test is designed to filter out the data it can't handle by use of assumptions.

If both of those things don't apply, you really don't want to use a theory.

I'm marking this a question and closing it as answered, but feel free to ask for more info on this issue if you need it. We'll still see the comment and answer you.

**Comment by alexvy86** [comment]
Thanks @CharliePoole, your explanation does make sense. The key part for me was 

> All of the data attributes that are used with a test may also be used with a theory.

Which apparently includes `TestCase` and `TestCaseSource`, not just `Value` and `ValueSource`.

That said, I'm trying different approaches to this and noticed that even if I remove the `Theory` attribute and just use `TestCaseSource` as I was doing before, I can still use `Assume.That()` to filter out the sets of parameters that I know would make the test fail... is that expected? I didn't try this before because I was under the impression that `Assume` was only valid inside theories. That test seems to work the same with or without the `Theory` attribute next to the `TestCaseSource` attribute. Unless this turns out to be a bug, I think I'm happy to just use `TestCaseSource` and `Assume` inside the test method.

**Comment by CharliePoole** [comment]
Of the two special characteristics of Theories that I listed, the second is dependent on using datapoints. "In theory" we could add other ways to feed data to a theory automatically, but we haven't done so. The first point is a bit more subtle. The old NUnit GUI hid the individual cases under a theory, unless you asked to see them. In the console runner, all the errors display and in Visual Studio, there is no difference because VS doesn't understand theories.

There is one difference in the use of Assume. In a theory, if all your assumes fail, then the overall theory fails, since it is not proven. In a test, if all of your Assumes fail the result is inconclusive. For many people, the difference is subtle enough that the two are functionally equal.

**Comment by alexvy86** [comment]
Got it, that last part makes sense too.
