### ISSUE TITLE
Unclear how ITestFilterService, TestFilterBuilder, SelectWhere and TestFilter should work

### ISSUE THREAD

**Issue by abelbraaksma** [nunit/nunit#2812]
I have been trying to upgrade some old NUnit 2.6 projects that were hard to upgrade previously because of too many errors, new namespaces (NUnit.Core doesn't exist anymore, nor do the default filters like `NameTestFilter`) and the completely revised ways of writing a test runner yourself.

I've been over https://github.com/nunit/docs/wiki/Test-Engine-API a few times, and tried to search, check StackOverflow and other forums, but can't seem to figure out how this is supposed to work.

The docs explain how to run all tests, by using `TestFilter.Empty`. I searched for other test filters, but can't find any. I figured I had to roll one my own, but got stuck at either listing each and every test myself (time consuming and error prone), or by using `TestFilterBuilder.SelectWhere`. The info on `ITestFilterService` states _"Creates properly formed test filters for use by runners"_, but is silent on how to go about it.

But the latter takes a string and I can't find anywhere what would go into that string.

I hit similar walls with the other interfaces, i.e. `ILogger`, `ITestEventListener`, or `IResultService`. From the source code of the services I don't get much further (i.e., the result service says, on the `format` param: _"The name of the format to be used"_, but doesn't say what formats are supported, or where to find them, or how to make them yourself).

Now I understand that documentation is usually not the top priority, but it would help a lot if there's at least some examples around that are useful (meaning: that go beyond the bare minimum). Being able to host a runner yourself is a strong requirement in quite a few scenarios.

**Comment by CharliePoole** [comment]
Sounds like the docs need improvement. Within the general category of documentation, I'm afraid that technical docs for those who access NUnit programmatically tends to get the least attention. In this case, the answer to your question is "hidden in plain sight" in the user docs.

I'm afraid that the documentation for the filter service makes a big assumption: that you are already familiar with Test Selection Language as used with the `--where` option of the nunit console runner. You can find that here: https://github.com/nunit/docs/wiki/Test-Selection-Language We should add a reference in the description of the API.

In many cases, however, the docs for the engine don't tell you about implementation details for the simple reason that __those details are allowed to change__. In the case of filters, I could tell you about the layout the XML for various kinds of filters, but in doing so I'd be locking you into an implementation detail. The general idea is that you are not supposed to know what a filter looks like, but only how to create one.

The same is true for most of the other interfaces you mention...

 * ILogger is an internal interface used for the NUnit internal trace. It's not a published API.

 * IResultService can't tell you the names of the supported formats because it doesn't know. Result services are provided by extensions, so it depends on what extensions you have installed. If using the console runner, there is a `--list-extensions` option, which will tell you what is installed. It's also possible to ask the result service what is installed programmatically.

 *ITestEventListener is pretty well documented, but since it's an extensibility interface you have to implement the methods in an extension that you create and installs.

I do agree that we could document all this much better.

**Comment by abelbraaksma** [comment]
Thanks, @CharliePoole, I seem to have forgotten to update this post, but I did try your suggestions on the syntax and that did work. Though it would probably be nice if this got mentioned in the docs, indeed. 

I'm still puzzled how one could write its own filter through some kind of listener interface, which could filter by name, category etc, but from what I read you'd basically need to understand a lot of internals at this moment to get to that, so for now I'll skip that endeavor and stick with the methods available.

**Comment by rprouse** [comment]
I am closing old uncategorized issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.

**Comment by abelbraaksma** [comment]
I just checked the docs and they've greatly improved, I'm gonna try out implementing this again. Thanks, I think closing is the right thing here.

**Comment by CharliePoole** [comment]
@abelbraaksma Looking back at old comments, I see I never replied to one thing you mentioned.

The filter service is not extensible because there was no clear need to make it extensible. You can only filter on factors that are exposed by the ITest interface and the set of filters covered by TSL seems to handle all of them.
