### ISSUE TITLE
Setting default static readonly and constant field naming conventions

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2822]
This repo is configured to not check private or constant fields for style, so VS and ReSharper default to private/internal static readonly fields and constant fields being Pascal-cased. Especially in an age where I use IDEs to generate most of my fields, would we accept PRs which follow these defaults?

```cs
private static readonly MethodInfo GenericMethodInstantiation;
internal const string Foo = "foo";
```

➡ If either of the answers is no, we should alter our editorconfig and DotSettings so that contributors like me aren't spending their time constantly fixing this.

➡ If either of the answers is yes, we should add an exception to https://github.com/nunit/docs/wiki/Coding-Standards#naming for `static readonly` or `const` fields because our coding standard is misleading about what we'll really accept in a PR. I lean this way.

Might be worth mentioning that I'm only concerned with this repo and its config files for the time being. Others don't have to follow suit, though they might.

**Comment by ChrisMaddock** [comment]
Wider conventions (VS default) sounds sensible to me.

**Comment by jnm2** [comment]
@nunit/core-team: I am proposing loosening the org-wide coding standard so that individual repos have the freedom to **accept**, **prefer** or **require** any naming standard for private or internal fields.

In order to do that, I'd like to add a paragraph and change two rows ([text here](https://github.com/jnm2/nunit-docs-wiki/commit/0d23f808d04a648c91bb93d7fd51ef4d61810a23?short_path=3dd71bf#diff-3dd71bf28e5f2f4f4dcd86100b376373)) in https://github.com/nunit/docs/wiki/Coding-Standards#naming:

![image](https://user-images.githubusercontent.com/8040367/39389790-fa5bf35a-4a59-11e8-9b9c-4d58e7efd36b.png)

If I'm reading https://github.com/nunit/governance/blob/master/decisions.md#core-team-decisions correctly, this would require a majority vote by the @nunit/core-team. Is this issue as good a place as any to ask for a vote?

**Comment by CharliePoole** [comment]
Taking this point by point...

1. As far as I understand it, we do __not__ have an "organization-wide" coding standard. In our governance discussions, we stated that projects under the organization would be independent. We decided not to deal with the coding standard issue when we set up the governance document. If my memory serves, Rob decided that the projects of which he is the leader would follow the old NUnit coding standards and nobody objected.

2. I agree that if we __want__ to have an org-wide coding standard, then the core team has to vote on it. FWIW, I would argue against doing that, however, this is probably not the place to do it. OTOH, we don't need a vote to give projects the authority to set their own standards because they already have it. We only need to vote if we want to take away or limit their authority.

3. In order to have a record of Core Team decisions on governance issues (which are the only issues the Core Team decides about) it seems to me that we should put all such issues under the governance repo. 
But if we want to discuss the standards __for a particular project__ then we should probably do it in that project's repo.

4. For reference, the key document to read regarding the relation of the Core Team to individual projects is https://github.com/nunit/governance/blob/master/governance.md It pretty much describes a decentralized organization in which projects operate according to their own standards.

@jnm2 It would help me to know which projects are you thinking of. Since you put this in the framework project repo, I'm guessing that's one of them.

PS:

Of course, technically, the Core Team can decide anything because the Core Team gets to vote on what it's own role is. However, I would argue against the Core Team giving itself too much direct authority over projects. Fear of over-control can lead to projects not coming in or staying in the NUnit Community.

**Comment by CharliePoole** [comment]
@jnm2 Of course it only helps if others understand things in the same way. Hopefully the other Core Team members will comment. Extra-hopefully someone will add something to the governance docs about this.

I agree with you that the situation is potentially confusing. When I stepped down as Core Team chair, this was one of several things that had been on the to-do list for our governance docs. Everyone was of a mind to get back to programming, I think, so that's what we did.

My two cents on the coding standard... It has become too detailed and specific for us to impose it on projects.

**Comment by jnm2** [comment]
@rprouse If we removed the coding standard from the central wiki, would you want to maintain some or all of what it currently contains in a document in the framework repo, or not maintain one for the framework repo at all and rely on IDE config files and the preferences of the PR reviewers?

Or would you prefer to leave it in a central location, making clear that it was descriptive only and noting which repositories was describing?

**Comment by CharliePoole** [comment]
@jnm2 Removing the coding standard from the central wiki isn't the only way to clarify things, of course. The wiki does have sub-directories with separate menus. However, it would make sense to me that the docs wiki should only contain information that is aimed at users. Once a user becomes a contributor, they have to go to the individual repositories anyway, so that seems to be the place to put things that apply to a single repository.

**Comment by rprouse** [comment]
@jnm2 I think the changes that you proposed gives some flexibility to the coding standard. It was created when there were only a few projects and the team was fairly small. I agree that it shouldn't apply to all projects, but also don't want to delete the standard from the Wiki, so I think your changes are a good compromise. It can provide a baseline for projects which can then override in their own repos.

Shall we make the suggested changes and close this?

**Comment by jnm2** [comment]
If everyone thinks my proposed changes are a good step in the direction of flexibility, I am happy with keeping the wiki and taking this smaller step. If I'm hearing all of you correctly, no one would object to this change and some would like to have it. So yes, let's do it! 😃

**Comment by jnm2** [comment]
Wiki updated in https://github.com/nunit/docs/wiki/Coding-Standards/22607c3b2e23c2f6f560ea8dff72590e3cc4a09a.
