### ISSUE TITLE
Obsoletion warning for DataAttribute

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2829]
[Quoting Charlie,](
https://github.com/nunit/nunit/pull/2803/files#r184545757)

> DataAttribute is a class that was somewhat important in earlier versions of NUnit. Currently, it's a holdover and is not used in the code at all. We left it in the code to avoid needlessly breaking anything.

This seems like a good thing to document in the source. Can we document this using an obsoletion warning so that people who use it become aware?

```cs
[Obsolete("Holdover from NUnit v2. Please inherit from Attribute or PropertyAttribute and " +
          "implement IParameterDataSource.", error: false)]
```

**Comment by YuriyOborozhnyi** [comment]
Can I take it, guys?

**Comment by mikkelbu** [comment]
Sure @YuriyOborozhnyi. Just ask if you have any questions about the task.

**Comment by mikkelbu** [comment]
@YuriyOborozhnyi We can only assign issues to members of the project. Prior (approx. 1 year ago) we added each new contributor as a member of the project. The current approach is to assign a mentor/shepherd to non-members and then invite non-members to the project when they have contributed a couple of PRs (or otherwise been active within the project).

**Comment by YuriyOborozhnyi** [comment]
@mikkelbu, got it! Thank you for the detailed explanation!

**Comment by mikkelbu** [comment]
@YuriyOborozhnyi You are welcome, and sorry about the slow feedback 😄

**Comment by mikkelbu** [comment]
@YuriyOborozhnyi Don't be sorry. Since we do this in our spare time I fully understand that sometimes issues progress slower than planned (or than what we had hoped for). I have also written my part of comments like "I thought I had time to do this", "I did not have time to do this today, but tomorrow..." 😄.

**Comment by mikkelbu** [comment]
Thanks for the contribution @YuriyOborozhnyi. It is much appreciated.

**Comment by YuriyOborozhnyi** [comment]
@mikkelbu, you`re welcome! I am glad to help you more further!
