### ISSUE TITLE
Tag a test to have it run but if it fails, but not fail entire test run

### ISSUE THREAD

**Issue by mcgary-andrew** [nunit/nunit#2844]
If a test fails due to an issue in the software (an issue that will eventually get fixed) and not an issue with the test, we would like to be able to tag the test to have it still run but not fail the entire test run and log the results somewhere.

**Comment by CharliePoole** [comment]
Currently, you would have to change the asserts to warn. Alternatively, you could Ignore the test, possibly specifying an "Until" date.

It's certainly possible to have an attribute that would cause all Asserts to function as Warnings. Others will have to decide if it's a general enough feature to include in NUnit.

**Comment by mcgary-andrew** [comment]
Would the Warning be able to log to the TestResults if it would have passed or failed if it wasn't set to Warning?

**Comment by CharliePoole** [comment]
If you use warning as a workaround, it will show up as either as a passing result or with a warning if it fails. (That's what warnings do.) NUnit would not know that you actually intended this as a failure but it's not yet implemented but you could put something in the message to indicate that.

Note that the warning equivalent of `Assert.That` is typically `Warn.Unless` rather than `Warn.If`.

**Comment by jnm2** [comment]
@hazzik I wonder if you could do the same thing with an attribute implementing ITestAction?

**Comment by rprouse** [comment]
I am closing old uncategorized issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
