### ISSUE TITLE
Tests are green with exceptions thrown in async void inner method (test itself is async Task)

### ISSUE THREAD

**Issue by Belorus** [nunit/nunit#2851]
```
public class SomeClass
{
        private event Action MyEvent;

        public SomeClass()
        {
            MyEvent += OnMyEvent;
        }

        private async void OnMyEvent()
        {
            throw new NotImplementedException();
        }

        public void Fire()
        {
            MyEvent();
        }
}

public class Tests
{
        [Test]
        public async Task Foo()
        {
            var foo = new SomeClass();

            foo.Fire();

            Assert.True(true);
        }
}
```

If i debug this test (in Visual Studio or Rider) - it crashes with exception.
If i run this test - it is Green.

I read that NUnit v2 had a SynchronizationContext that waited until last message was handled. Can this behavior be enabled by some attribute ?

Workaround: Simply wrapping into `Nito.AsyncEx.AsyncContext.Run()` fixes that.

**Comment by Belorus** [comment]
I see https://github.com/nunit/nunit/pull/2818 is coming.  Great news!

**Comment by jnm2** [comment]
##### https://github.com/nunit/nunit/pull/2818#issuecomment-392316928:

> Hi @jnm2 
> 
> I tried package 05600 with your changes.
> https://github.com/nunit/nunit/issues/2851 - here i get 
> `
> System.InvalidOperationException : Shutting down SingleThreadedTestSynchronizationContext with work still in the queue.
> `
> This behavior makes perfect sense in very strict env where you wish to avoid async void methods anywhere in your code.
> 
> It would be really amazing to make a new configurable behavior that executes all delegates in SynchronizaitonContext that are left. This will make testing of `async void`  methods possible.
> 
> WDYT ? 

Great feedback, thanks for bringing my attention to this issue!

This isn't an absolute, but I think we're pretty sure that we don't want to directly enable magically making async void work. This is really about correctness for us. Relying on an async implementation detail, a spying SynchronizationContext, is sloppy and even prone to race conditions in some cases.
If it's important for outside code to be able to know when something has ended, a wait mechanism should be provided by `SomeClass`. Test code shouldn't be more special than other theoretical client code.

It's an interesting problem though. We don't want to make life unnecessarily difficult. I sort of want to see the real code to be able to determine what signalling mechanism would actually make sense in your scenario.

> Workaround: Simply wrapping into Nito.AsyncEx.AsyncContext.Run() fixes that.

Rather than encouraging async void methods, I do like that NUnit puts the burden on test writers to make sure they know logically when the test should end, and if something sloppy like a spy SynchronizationContext is needed, put the responsibility on the test writer to use that to determine the end of the test. So I'm happy there's such an easy workaround, yet NUnit doesn't have to be responsible for it.

> I read that NUnit v2 had a SynchronizationContext that waited until last message was handled. Can this behavior be enabled by some attribute ?

It did. This was removed in NUnit 3.0 and I'm happy about that decision. The attribute idea is interesting. I think you can actually accomplish what you want with a custom attribute implementing ITestAction. NUnit still keeps its hands clean of guessing at implementation details of async void methods, so I'm happy if this works too.

**Comment by jnm2** [comment]
Tested implementation:

<details>

```cs
using System;
using System.Collections.Concurrent;
using System.Threading;
using System.Threading.Tasks;
using NUnit.Framework;
using NUnit.Framework.Interfaces;

public class MyTests 
{
    [Test, SingleThreadedWithAsyncVoidWait]
    public void Foo()
    {
        _ = X();

        async Task X()
        {
            await Task.Delay(1000);
            Y();
        }

        async void Y()
        {
            await Task.Delay(1000);
            Assert.Pass("Waited");
        }
    }
}

[AttributeUsage(AttributeTargets.Assembly | AttributeTargets.Class | AttributeTargets.Method)]
public sealed class SingleThreadedWithAsyncVoidWait : Attribute, ITestAction
{
    public void BeforeTest(ITest test)
    {
        SynchronizationContext.SetSynchronizationContext(new SingleThreadedSynchronizationContext());
    }

    public void AfterTest(ITest test)
    {
        var context = SynchronizationContext.Current as SingleThreadedSynchronizationContext
            ?? throw new InvalidOperationException("The test changed the synchronization context.");

        context.Run();

        SynchronizationContext.SetSynchronizationContext(null);
    }

    public ActionTargets Targets => ActionTargets.Default;
}

public sealed class SingleThreadedSynchronizationContext : SynchronizationContext
{
    private readonly BlockingCollection<(SendOrPostCallback d, object state)> queue = new BlockingCollection<(SendOrPostCallback, object)>();

    public override void Post(SendOrPostCallback d, object state)
    {
        queue.Add((d, state));
    }

    public void Run()
    {
        while (queue.TryTake(out var work, Timeout.Infinite))
            work.d.Invoke(work.state);
    }
}
```

**Comment by stevenaw** [comment]
I think this can be closed.
I've verified the initial code snippet will show green but that applying the sample `SingleThreadedWithAsyncVoidWait` from @jnm2 in his reply will cause the test to instead fail by throwing the `NotImplementedException`
