### ISSUE TITLE
Skip executing TestCaseSources for tests which are not included in the filter

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2867]
I'm positive we already have an issue tracking this, but I've been looking across the whole org.

A work project has grown to the point where any test run incurs just shy of nine seconds of test discovery time before any tests are actually executed. I profiled and found the nine seconds to be dominated by the execution and iteration of TestCaseSources.
Some of the tests are integration tests using test case sources which query real databases to determine the number and parameters of test cases to generate. My intuition is that we don't incur that cost, so long as we don't run tests in the Integration category.

A workaround may be to split the integration tests into a separate assembly, but the same nine-second wait happens if I want to continually run a single unrelated integration test as part of my inner-loop development. (Think NCrunch, or ReSharper in continuous coverage mode.) So this workaround doesn't alleviate a lot of the problem.

**Comment by rprouse** [comment]
Might that be difficult because you can name tests in the returned `TestCaseData` classes, so you need to run the `TestCaseSource` to determine the generated names.

**Comment by jnm2** [comment]
Oh boy, I hadn't considered that. I wonder if we could do a prefilter based then. For example, if the test runner filters to `Namespace.FixtureA.TestMethod`, don't bother running the test case source needed by the methods in `Namespace.FixtureB` since there's no way the generated test cases can have a name starting with `Namespace.FixtureA`?

**Comment by rprouse** [comment]
We could do something like that. We will need to list all of the filters we support and then determine how they will be pre-filtered. It could get complicated and error prone with complex compound filters.

**Comment by jnm2** [comment]
Yes, it could. In the inner loop scenario, using ReSharper or Test Explorer with a UI selection, the filter will consist of ORed test names. So we could detect whether the filter comprises only ORed simple test name equality comparisons, and put all the parent names into a hash set. Then we could skip exploring any suite whose name doesn't appear in the hash set.

Technically we could also detect more complex variations, but at heart this is an optimization and we probably wouldn't want to add complexity prematurely.

Would you see it being worth trying and maybe adding to NUnit?

**Comment by jnm2** [comment]
@mikkelbu Yes! That's the one!

Would work be done framework-side, or shall I close this in favor of that one?

**Comment by ChrisMaddock** [comment]
The framework feature for loading specific classes/namespaces theoretically already exists - it just needs plugging in. Although I don't think it's ever been used (by us!) since v3 was released.

As I remember, the current `FrameworkPackageSettings.LOAD` feature is only set up for classes/namespaces - if you wanted to tackle other kinds of filters, more framework work would be required.

I only know all this as it's one of many things I once planned to do! 😆 There must be a third discussion on it somewhere, as my discussion (with Charlie, IIRC) don't seem to be on either issue!

**Comment by ChrisMaddock** [comment]
Here's the one! As Charlie said, our conversations there don't directly relate to what Charlie intended that issue to be: https://github.com/nunit/nunit/issues/3

**Comment by ChrisMaddock** [comment]
Heh, back in October 2017, yes! :-p

Sorry - it's off my radar at the moment. I'm moving/renovating flats right now (hence being on the quiet side!) - and once that's through, I'm hoping to spend some time carrying on improving engine/console .NET Standard support. There's plenty there to keep me busy for now, I'm afraid!

**Comment by jnm2** [comment]
Not problem! I'll keep it on my radar, unless someone else was hoping to do it.

**Comment by CharliePoole** [comment]
My old term of "dynamicly discovered tests" was basically shorthand for "the filter is in the test execution stack and is not applied till the test is executed" - among other things.

If we had such dynamic tests as a feature, then this problem would either not exist or be much easier to fix. However, we only have "statically discovered tests" - that's all that NUnit is about right now - so we have to solve this at the point in time before a true TestExecutionContext exists.

It __is__ confusing that we decided to create a sort of bastardized TestExecutionContext before we are actually executing tests in order to make a few things like runtime parameters and TestDirectory work at discovery time. IMO, we should eventually back that stuff out, but that's another matter.

Conceptually, I think there's something like a DiscoveryContext, which is created at discovery time and has nothing to do with any particular test. That might be another direction from which to approach this.

**Comment by jnm2** [comment]
For these integration tests, I don't want to wait until execution time to see the full list. But I also don't want to be slowed down by the discovery process when my filter doesn't include that namespace.

**Comment by CharliePoole** [comment]
@jnm2 Seeing all the tests, requires discovering tests in every namespace.

As I see it, this is a framework issue, so it's about providing the __capability__ to filter at discovery time. Each runner would have to decide how and when to use that capability.

The console runner provides the simplest way to prove that the feature works in the framework. Since it only loads tests once and then executes them once, it should be able to use the most efficient paradigm for any given filter that is provided by the user.

The adapter or any gui would have added problems. Currently, we discover all tests and display them. We have no way to filter before discovery - no way even to tell the runner that we want to filter before discovery. I can imagine ways, but they don't exist yet. 😸 

So, are you talking about the adapter? What would it look like from a user point of view if you could avoid generating tests for namespaces you were not interested in? Obviously, I'm not working on the adapter, but that may be the best way to visualize the desired end result.

**Comment by CharliePoole** [comment]
Sure. But that seems like "Discovery-time Filtering 501" rather than "101" 😄 We need some infrastructure first. Also, as currently used, the framework __has already discovered the tests__ before it ever sees the filter.

Once we get "101" and maybe "201" we might want to do different things depending on which runner we would like to help first. That's why I asked what runner was important to you.

**Comment by CharliePoole** [comment]
Probably the biggest new thing here is to apply a filter at discovery time, assuming someone has provided the filter.

Second biggest thing is to create a discovery filter, either from scratch or by transforming a runtime filter into two pieces. Currently, the framework does no filter creation. That's all in the engine, so it seems to make sense to keep it in the engine. That way, it's all in one place and every runner has access to it in the way they want.

Examples... a gui might want to discover all tests in order to display them. Or it might want to allow the user to specify a sort of pre-filter as part of loading an assembly. Or, it might not do filtering of subtrees until that node was actually expanded. Because of all that diversity, it doesn't seem to me to be such a good idea for the __framework__ to take any particular approach automatically.

I'm dealing with jet lag now that I'm home so maybe I can leverage that to write some code to illustrate what I mean better than words.

**Comment by jnm2** [comment]
I'm following now, sorry! Yes, your plan makes a lot of sense!

The runners where we are experiencing grief are the Test Explorer and ReSharper GUIs. We recently learned in the adapter repo that ReSharper is using the VSTest adapter now.

**Comment by CharliePoole** [comment]
Created #2876 to get this started under NUnitLite

**Comment by jnm2** [comment]
@CharliePoole Had a thought. This discovery filter would have to be application both at discovery time and at execution time because the TestCaseSources are all executed both times, right?

Would it make sense to tackle the execution time scenario first?

**Comment by jnm2** [comment]
@CharliePoole Had a thought. This discovery filter would have to be applied both at discovery time and at execution time because the TestCaseSources are all executed both times, right?

Would it make sense to tackle the execution time scenario first?

**Comment by jnm2** [comment]
For example, I believe the nine seconds of TestCaseSource execution that I'm measuring with dotTrace is all at execution time. I don't think I have an easy way to profile discovery time.

**Comment by jnm2** [comment]
I'm profiling by right clicking on a no-op test amd selecting Profile Unit Test, just like I nornally would for Run, Debug or Cover.

**Comment by jnm2** [comment]
I'm profiling by right clicking on a no-op test and selecting Profile Unit Test, just like I normally would for Run, Debug or Cover.

**Comment by CharliePoole** [comment]
I don't think we can get the distinction between execution and discovery that way, since NUnit's discovery has already run before you get anything to click on. So, what you are getting includes the second discovery plus the actual execution.

**Comment by jnm2** [comment]
Here's something else. The same TestCaseSource is executed and iterated once per usage, even though it's not parameterized. What if we added an enhancement that assumes that parameterless TestCaseSources can be evaluated once and shared by all tests?

**Comment by jnm2** [comment]
Actually, I can already accomplish this with manual caching.
What would be even cooler is supporting `Lazy<IEnumerable<>>` members so that you can opt in with minimal boilerplate. Worth an issue?

**Comment by CharliePoole** [comment]
We had that in V2 and even cached the instance of the fixture that we created for non-static sources. 

In NUnit 3, I decided to just use it each time on the basis that most sources don't need caching.

There's also the possibility that the source returns different things each time it's called, but that's probaly pathological.

**Comment by jnm2** [comment]
@CharliePoole Is there anything to do in the framework for this issue, besides https://github.com/nunit/nunit/issues/2876?

**Comment by CharliePoole** [comment]
Not in the framework but in other runners.

**Comment by jnm2** [comment]
I'm leaning towards closing as fixed. Is there any reason to keep a tracking issue in this repository?

**Comment by rprouse** [comment]
Closed. If there is nothing to do here there is no reason to keep it open.
