### ISSUE TITLE
Behavior-driven development using nunit

### ISSUE THREAD

**Issue by siyamandayubi** [nunit/nunit#2868]
Hi guys,

Is there any plan to support Behavior-driven development using nunit, for example supporting Gherkin
https://github.com/cucumber/cucumber/wiki/Gherkin
language.

Regards,

**Comment by ChrisMaddock** [comment]
In my opinion, there are some great BDD frameworks out there which make use of NUnit, and NUnit would be better placed to focus on supporting close integration with those frameworks, rather than implement our own BDD functionality within NUnit itself. Take a look at Specflow for example. (Here's a nice explanation of how the two work together, if you're not already familiar: https://stackoverflow.com/a/33920759/1768779)

I'll leave this issue open for others on the team to comment on first, but my opinion is that this isn't an area NUnit should go into itself.

**Comment by rprouse** [comment]
I agree fully with @ChrisMaddock. There are already great BDD frameworks. It is not our bread and butter, so we will leave it to those projects and work with them when necessary.

**Comment by siyamandayubi** [comment]
Thank you guys for the information
