### ISSUE TITLE
idea: allow anonymous objects instead of object[] for TestCaseSource

### ISSUE THREAD

**Issue by Dreamescaper** [nunit/nunit#2874]
If we have several test method parameters, and multiple parameters are present, it could be more readable to add names for arguments (without separate class creation). 
So instead of:
```
        private static object[] TestCaseData = new object[] {
            new object[] {"A1", "B1", new[] {"C1", "D1" } },
            new object[] {"A2", "B2", new[] {"C2", "D2" } },
        };

        [Test, TestCaseSource(nameof(TestCaseData))]
        public void Test(string providedValue1, string providedValue2, string[] expectedValues)
        {

        }
```

We could do something like this:
```
        private static object[] TestCaseData = new object[] {
            (
                providedValue1: "A1",
                providedValue2: "B1",
                expectedValues: new [] {"C1", "D1" }
            ),
            (
                providedValue1: "A2",
                providedValue2: "B2",
                expectedValues: new [] {"C2", "D2" }
            ),
        };

        [Test, TestCaseSource(nameof(TestCaseData))]
        public void Test(string providedValue1, string providedValue2, string[] expectedValues)
        {

        }
```

**Comment by jnm2** [comment]
I love this idea!

With tuple syntax, we won't be able to obtain the element names unless either the TestCaseSource member is visible to external assemblies (in which case we read the [`TupleElementNamesAttribute`](https://msdn.microsoft.com/system.runtime.compilerservices.tupleelementnamesattribute.aspx) which the compiler emits for external assemblies), or else we'd have to parse the PDB to determine the element names, or else fallback to referring to them as `Item1`, etc.

From that standpoint, anonymous types might be more robust.

Would we require the names to match the parameter names of the method? It would be very confusing of order mattered once you name them.

**Comment by Dreamescaper** [comment]
I wasn't thinking about any kind of validation, but i like your suggestion about anonymous types to enforse names matching.
Even though I don't really understand why would anyone reorder them.

**Comment by jnm2** [comment]
I'm bringing it up because it's a thing that was discussed in the dotnet/csharplang repo before the tuple feature came out. You might reorder parameters because you think it looks better than way in Test Explorer, and you might expect that the test case source element names would still hold.

Especially if we do support tuples. The philosophy behind tuples is that they parallel argument lists as closely as possible. Order doesn't matter in an argument list if you name every element, so I'd expect it to not matter when NUnit maps a tuple to a parameter list.

What do you think about starting with only anonymous type support? I'm a bit worried about what happens if the user specifies element names but there is no `TupleElementNamesAttribute`. It would be great to not have to depend on access to a PDB in order to test the assembly properly.

**Comment by Dreamescaper** [comment]
Yeah, wasn't thinking about test explorer. 
Sometimes I even add unused string argument simply to make it more readable in TestExplorer or TeamCity.

I'm totally fine with anonymous types only!

**Comment by Dreamescaper** [comment]
Sounds good to me.

Is it okay to send PR? Or do we need to discuss something else?

**Comment by CharliePoole** [comment]
Suggest adding some tests that take a ValueTuple as an argument. You will need to keep those tests passing as you add the ability to use the ValueTuple as a carrier for multiple arguments. This is the same problem we have with tests that take an object array as an argument and it makes our code more complex than it would otherwise be.

**Comment by Dreamescaper** [comment]
@CharliePoole

According to latest discussion with @jnm2, it was decided not to support valueTuples, but use anonymous types instead (to have the ability to retrieve element name).

Are you ok with that?

**Comment by CharliePoole** [comment]
I've been staying out of the feature discussion and will continue to do so. 😸 

To generalize what I am saying: be careful if the thing you use to hold a list of arguments (e.g. object[]) can also be an argument by itself. We spent a lot of time on supporting tests with signatures like `public void MyTest(object o)` and `public void MyTest(object[] o)`.

If you use anonymous types then you probably only have to worry about methods taking an object as the sole argument.

It seems like the title of the issue should change along with going from being an idea to a feature. Otherwise, the current title will eventually end up in the release notes, adding to everyone's confusion in addition to mine. 😈

**Comment by Dreamescaper** [comment]
Got that, will add corresponding test!

**Comment by CharliePoole** [comment]
In the case of `public void Test(object)` we probably have several for you to break already. 😈

**Comment by jnm2** [comment]
> Is it okay to send PR? Or do we need to discuss something else?

I don't want to hold you up, but I want to hear what @CharliePoole or other @nunit/framework-team members think of the pros and cons of adding this feature.

**Comment by CharliePoole** [comment]
@jnm2 See my earlier comment.

**Comment by jnm2** [comment]
@Dreamescaper Because of the added conceptual overhead that we'd have to carry forward, I'm not comfortable signing off on this unless there was interest from the team lead (Rob) or another team member. However in the meantime, I could assist you in writing your own TestCaseSource attribute to trial the splatting and see how you like it.

**Comment by Dreamescaper** [comment]
I prefer to stick with framework functionality unless absolutely needed.
If it is decided that it's not what we want - I'll be able to live without it

**Comment by rprouse** [comment]
I am closing old Idea issues that have not had comments or made progress in several years. If anyone comes back with a compelling argument for these issues, we can reopen.
