### ISSUE TITLE
TestCaseSource is created when unrelated test is debugged

### ISSUE THREAD

**Issue by lbalasko** [nunit/nunit#2877]
Hello. 
I apologize in advance if there is a documentation for this problem or a similar issue, but I could not find anything.

I do not know how to explain our problem without example so I will use a simplified example:

Lets say that in Test project we have two test classes: GoodTestClass and NaughtyTestClass. They are in different files and folders and have nothing in common. Both classes have TestFixture property. 
GoodTestClass has following code:
```
[TestFixture]
public class GoodTestClass
{
        [Test]
        public void GoodTest()
        {
            // do something
            Assert.Pass();
        }
}
```

NaughtyTestClass looks like this:

```
[TestFixture, Category("Naughty")]
public class NaughtyTestClass
{
        List<string> Ids = new List<string>(); 

        [TestFixtureTearDown]
        public void TearDown()
        {
               // take ids and remove data from database
        }

        private class NaughtyData : TestCaseData
        {
               public NaughtyData SetData()
               {
                     // create some data in database
                    // remember ids
               }
        }        

        public class NaughtyTestCases : IEnumerable 
        {
            public IEnumerato GetEnumerator()
            {
                      yield return new NaughtyData().SetData().SetName('NaughtyTest_DataSet_Pass');
            }
        }

        [TestCaseSource(typeof(NaughtyTestCases))]
        public void NaughtyTest()
        {
            // do something
            Assert.Pass();
        }
}
```

What is happening is that when we debug GoodTest, NaughtyTestCases are created also and data is written in database. TearDown from NaughtyTestCase is not called and data remains in database. 
Of course, this isn't behavior we would like. 

Why is NaughtyTestClass affected by something that is happening to GoodTestClass? What is the connection between them? How do we stop this behavior so that NaughtyTestClass is only created when tests from that class are run or debug? 

We use NUnit 2.6.4.

If you need any more explanations, let me know. 

Thanks :)

**Comment by CharliePoole** [comment]
`NaughtyTestClass` is well named. 😃 It's doing something bad.

When tests are loaded (discovered) __all test case sources__ have to be executed. Why? Because that's part of how we figure out how many tests there are. If you have 10000 tests and run the console runner with test name or category that only selects 5 of them, it is necessary to create all 10000 tests first because they are the __input__ to our filtering. SO...

 1. Create 10000 tests
 2. Filter them, giving 5 to execute

For that reason, you should __not__ be creating database entries in your data sources. You should not be doing any heavy duty, time-consuming work.

BTW, this also applies to your test class constructors: they should do next to nothing.

Your long-term solution is to stop doing what you are doing, I'm afraid.

There may also be some short-term workarounds, depending on how you actually execute your tests - console, gui, VS adapter, etc.

In NUnit 3, we are doing some work to pre-filter the loading of tests so that at least some types of filters are handled before the tests are created. However, until that work is finished, the same restrictions will apply to NUnit3 if you upgrade.

**Comment by lbalasko** [comment]
Thank you for your answer and explanation. 
We will change our tests to correspond with this logic. 
Would I be able to use TestFixtureSetUp property to create data in database?  
Something like this: 
```
[TestFixture, Category("Naughty")]
public class NaughtyTestClass
{
        List<string> Ids = new List<string>(); 
        NaughtyData[] NaughtyTestData;

        [TestFixtureSetUp]
        public void SetUp()
        {
                NaughtyTestData = 
                {
                         new NaughtyData().SetData().SetName('NaughtyTest_DataSet_Pass');
                }
        }

        [TestFixtureTearDown]
        public void TearDown()
        {
               // take ids and remove data from database
        }

        private class NaughtyData : TestCaseData
        {
               public NaughtyData SetData()
               {
                     // create some data in database
                    // remember ids
               }
        }        

        [TestCaseSource("NaughtyTestData")]
        public void NaughtyTest()
        {
            // do something
            Assert.Pass();
        }
}
```

**Comment by lbalasko** [comment]
Thank you for explaining in details. I will try your approach.

**Comment by CosminGramada** [comment]
> In NUnit 3, we are doing some work to pre-filter the loading of tests so that at least some types of filters are handled before the tests are created. However, until that work is finished, the same restrictions will apply to NUnit3 if you upgrade.

@CharliePoole  Do you have any updates on this?

I have a similar issue, the only difference is that I'm running a DB query (some heavier taking up to 3 seconds) that will return my test cases to be executed.
Having a lot of tests, this can take some time until it's executed everytime.
Having a lot of test

**Comment by CharliePoole** [comment]
See issue #2876. I added the basic capability of pre-filtering the tests for a run and implemented it in the nunitlite runner. Any other runners would need to be changed to take advantage of it. Best course us for you to file an issue in the relevant project for whatever runner you are using.
