### ISSUE TITLE
Higher precision for ITestResult DateTime fields

### ISSUE THREAD

**Issue by elv1s42** [nunit/nunit#2879]
Hello!

This is not an issue but a feature request.
If possible I want to be able to use test result Start and End DateTimes with higher precision. At the moment when I run tests I am getting such `.xml` results:
```
 ...
<test-case id="0-1002" name="SimpleFailedTest" fullname="NUnitTests.Tests.SimpleFailedTest" methodname="SimpleFailedTest" classname="NUnitTests.Tests" runstate="Runnable" seed="594743335" result="Failed" start-time="2018-05-31 16:30:21Z" end-time="2018-05-31 16:30:24Z" duration="2.275137" asserts="1">
...
```

As you can see both `start-time` and `end-time` have format `yyyy-MM-dd HH:mm:ss`.
Is it possible to increase time precision up to microseconds (start using format `yyyy-MM-dd HH:mm:ss.ffffff`)?
At the moment we don't know when exactly test started, so this enhancement will help me to build framework extensions with correct data.

Initially changes for using start and end datetimes were implemented in this pull request: https://github.com/nunit/nunit/pull/94 
This can give an idea of the amount of changes required to do this enhancement.

Thank you

**Comment by CharliePoole** [comment]
Note that the duration reported is __not__ based on the start and end times and is of a higher precision. That may not help your use case, however.

**Comment by elv1s42** [comment]
Hi @CharliePoole ,

Yes, but still `start-time` and `end-time` will be helpful becuase I need to know the exact time when test has started. 
Am I right that changing ITestResult will lead to increased precision in test results `.xml` file?

Thanks

**Comment by CharliePoole** [comment]
It might require some formatting changes when the XML representation is created. But the tests would tell us that.

Big question is whether we want to do that, possibly breaking clients of the XML result. @nunit/framework-team ?

**Comment by jnm2** [comment]
I'm not sure how much it will actually help to increase the formatting precision, since the DateTime.UtcNow resolution is somewhere around 15 ms. What will the sub-second precision be used for, exactly?

**Comment by CharliePoole** [comment]
Good point. We use ticks internally of course, but the DateTimes are just what the system gives us.

**Comment by elv1s42** [comment]
Hello

> What will the sub-second precision be used for, exactly?

@jnm2, the use case example is test run report that is created using `.xml` results file. In case tests are running very quickly (unit tests, API tests, etc.) the current precision of `start-time` will give us report where serveral tests have started at the same time.

**Comment by jnm2** [comment]
Can you help me understand why it's a problem for several tests to be reported to start at the same time? What goes wrong; for example, are you trying to use start time as a unique ID?
Keep in mind that for fast tests, the same thing will happen even if we expose the native 15 ms resolution. Multiple tests will appear to start at the same moment since they started within 15 ms of one another.

**Comment by elv1s42** [comment]
@jnm2, my case is not the common. I want to able to save some data (like screenshot as byte[]) into the database and later use it to generate tests run report. And the issue it that I can't assign the data to the specific test because I don't know the exact values of  `start-time` and `end-time`. 15 ms resolution will be enough for my case.

@siprbaum, agreed. Another problem that even if you know correct duration value you still can't calculate exact values for `start-time` and `end-time` becuase both of them are rounded to only seconds precision.

**Comment by jnm2** [comment]
@elv1s42 Ah! So why not save the data using `TestContext.CurrentContext.Test.ID` as the key, rather than the start or end times?

**Comment by CharliePoole** [comment]
Start and end time are fairly recent additions. We originally only gave start and end times for the entire run but somebody requested they be added on each test, which we did.

Duration of each test was always calculated in NUnit V2 using time differences but for NUnit 3 we decided that a higher precision was needed. We use `StopWatch.Ticks` at the start and end of each test and take the difference.

Problems I see with this request:

1. As requested by certain users, we are making use of a standard XML format for the start and end times. I'm concerned that changing it would break them.

2. As @jnm2 has explained, no matter how much precision we use, it will still only be accurate to 0.015 seconds.

3. Some tests are __actually__ running at the same time, assuming parallelism is in use.

To associate data with a specific test, you could simply use the unique id of that test, which is available to your test as `TestContext.CurrentContext.Test.ID` and is also available in the XML.

**Comment by elv1s42** [comment]
@CharliePoole and @jnm2, thank you for the idea, I'll try to implement this workaround.
This issue can be closed if it's ok to use "incomplete" information in `.xml` test results.

**Comment by jnm2** [comment]
@elv1s42 You can't consider the timing information to be incomplete unless there is a context which actually calls for that kind of wall time precision. I can't think of a scenario which naturally needs sub-second precision, but if someone has one, we can discuss what it would take to best suit that particular need.

The YAGNI principle should keep us from guessing at what theoretical people might need without having a real use case in front of us. There's a good chance not only of breaking parsers, but also of solving the wrong problem.
For example, if we had better precision, you might still be using wall clock time as a unique ID which prevents you from using parallelism and is still sensitive to collisions. Having a low resolution has been a net positive, so far, because it helped you get to a more idiomatic solution. :D
