### ISSUE TITLE
why N unit parallel execution not works for static webdriver

### ISSUE THREAD

**Issue by kumarbrandmuscle** [nunit/nunit#2890]
Hi Team,
why the parallel execution,not works properly for static webDriver.
If I declared as ``` public static IwebDriver driver``` as class level.
If you want ran parallel execution using static webdriver using N unit.In case,if there any approach,please suggest me this approach.
Thanks,
kumar.

**Comment by CharliePoole** [comment]
It doesn't work because `static` means there is only one web browser to use for all your tests.

Normally, web tests instruct the browser to do several things in sequence. For example, to log in, navigate to a certain page, select some page element, etc. If the browser is receiving these instructions from several different tests at the same time, this will clearly be a problem. To run tests in parallel, each test must have it's own browser.

I have to note here that this is __not__ really an NUnit question, but a pretty fundamental question about parallel programming. IF you write parallel tests, you are really doing parallel programming, something which, at least in the past, was always considered a pretty advanced skill. It's not possible to make code that was not written with parallelization in mind run in parallel by simply adding the `ParallelizableAttribute`.

**Comment by Noksa** [comment]
@kumarbrandmuscle 
If you want to use a static driver in parallel tests, you need to use `ThreadLocal<IWebDriver>`

**Comment by CharliePoole** [comment]
@Noksa That will work for some people on certain platforms. On platforms without ThreadLocal, it won't work, of course. 

Also, when your tests are parallelizable, __you don't actually know__ that they will run on separate threads. That's up to NUnit. They may end up running parallel or sequentially and in the latter case may run on the same thread. So you have to do all the correct initialization and cleanup anyway.

**Comment by kumarbrandmuscle** [comment]
@CharliePoole ,YES that was correct only in platform it will work.
Thanks,charlie for helping me out.

**Comment by Noksa** [comment]
@CharliePoole 
Yes, of course, the architecture of the tests should completely support parallelism.
Just putting IWebDriver in a ThreadLocal container is not enough :)

**Comment by mikkelbu** [comment]
@kumarbrandmuscle I'm marking this issue as closed/answered, since Carlie already has labeled it so 😄 . Note that we will still see additional comments to this issue.
