### ISSUE TITLE
Output of all runs of tests is not visible when Retry attribute is used

### ISSUE THREAD

**Issue by oviradoi** [nunit/nunit#2911]
In NUnit versions 3.5 and older, if you had a test with a Retry attribute, the output from all runs of the test would be printed to the console.

Starting from NUnit 3.6, only the output of the last run of the test will be written to the console.

For example, let's take this test:

    [TestFixture]
    class Fixture
    {
        private static int _times = 1;

        [Test, Retry(3)]
        public void Test()
        {
            TestContext.WriteLine("Retry nr " + _times);
            _times++;
            Assert.Fail();
        }
    }

In NUnit versions 3.5 and lower, it would print:

    Retry nr 1
    Retry nr 2
    Retry nr 3

But in NUnit versions 3.6 and newer, it prints:

    Retry nr 3

Is there any way to also get the output of the previous runs to be written to the console?

**Comment by CharliePoole** [comment]
Prior to 3.6, standard output would go directly to the runner. In the case of the console runner, it all gets displayed on the console.

With 3.6, standard output becomes part of the test result. Since `[Retry]` discards all the results except for the final one, that output is discarded.

If you want a message to appear even if the the result is discarded, use `TestContext.Progress`.

**Comment by oviradoi** [comment]
Thanks, using `TestContext.Progress` worked for us.
