### ISSUE TITLE
ValueSource ignores the TestCaseData name when generating the test name

### ISSUE THREAD

**Issue by GiottoVerducci** [nunit/nunit#2926]
For instance, if my source is (I simplified it to the minimum):

```
        private static IEnumerable<TestCaseData> Foo()
        {
            return new[] 
            {
                new TestCaseData("babar").SetName("babar {m}"),
                new TestCaseData("celeste").SetName("celeste {m}")
            };
        }

```

Then the case name is properly generated when using the TestCaseSource attribute, but not the ValueSource attribute:

```
        [TestCaseSource(nameof(Foo))]
        public void Test1(string value)
        {
            Assert.Fail();
        }

        [Test]
        public void Test2([ValueSource(nameof(Foo))]TestCaseData value)
        {
            Assert.Fail();
        }
```

I have: 

- babar Test1
- celeste Test1
- Test2:Test2(NUnit.Framework.TestCaseData)

**Comment by CharliePoole** [comment]
`TestCaseData` is intended for use by `TestCaseSource`, not for `ValueSource`. That's because a test case contains a __selection__ of arguments, whereas a value source merely provides one value for a test parameter, allowing NUnit to combine them. 

In your case, you have managed to use the same source for both methods by having the second method actually take NUnit's `TestCaseData` as an argument. NUnit does nothing with the `TestCaseData`, but merely passes it to your method to do what it wants with it. This would be an appropriate thing to do if you were actually testing `TestCaseData`, but it is not useful in the general case.

Imagine if we did provide a way for `ValueSource` to specify the name of the test. This could conceivably work in the case where a method has only one argument, but not with multiple arguments. You could have conflicting names specified by two different `ValueSources`.

@nunit/framework-team IMO this could be closed as "notabug". [I'm trying to stop closing things myself, since I'm departing.]

OTOH, I can imagine some attribute, either new or existing, that would specify a naming pattern to use for all the test cases generated from parameter values supplied. One thought would be to add a property to the `CombinatorialAttribute` and other joining attributes through their base class. I'll leave that to somebody else if it sounds interesting.

**Comment by jnm2** [comment]
@CharliePoole You said even better what I was getting ready to say. 👍

One thing I do if I want to control the display name of a [ValueSource] argument is to define a simple wrapper struct around the parameter type, override ToString, and pass in the wrapper type instead.

@GiottoVerducci Would that help, or is there a situation we should look into further?

**Comment by CharliePoole** [comment]
I think the argument display is a different matter, analogous to your `SetArgDisplay`. I was talking about how to do something equivalent to `SetTestName` (I'm not looking at code, so I hope I have the names right), which would apply to all the test cases constructed from a combination of individually specified argument values. Since the test can only have one combining attribute (Combinatorial, Pairwise, Sequential) that seemed like a good place.

Maybe we need an issue "Specify test name for cases generated from individual parameter values". In fact, I imagined we had one already, but couldn't find it.

**Comment by CharliePoole** [comment]
@jnm2 And possibly another issue for the equivalent of `SetArgDisplay`, specified on the `ValueSource` attribute itself.

**Comment by jnm2** [comment]
True, good ideas. I do like the cleanness of only customizing the part of the name which represents the argument values and leaving the method name and the parentheses alone, so I'm biased towards that type of solution.

**Comment by CharliePoole** [comment]
Right. We all have our ~~biases~~ preferences as to what features to use. I don't think that should always drive what we provide to users, however. 😄

**Comment by GiottoVerducci** [comment]
I was assuming that TestCaseSource and ValueSource would behave identically when it comes to TestCaseData, but I understand that ValueSource can't handle multiple parameters.
I am not familiar with the SetTestName / SetArgDisplay properties, so they could be a solution. I could also wrap my values into a custom struct (or a Tuple<string, MyType> to avoid creating a struct).
I thought that it could be a good idea anyway to have the .ToString() method of the TestCaseData being implemented to return the right value, but I realize that it is probably not possible since the test name is not known until the argument is processed (especially for the {m} placeholder).
Thanks for the insights.
