### ISSUE TITLE
Filter creation API

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#2931]
We had a [comment](https://github.com/nunit/nunit/pull/2532#issuecomment-404753752) from an NUnit user that the internal filter classes were easier to use than using C# to build XML. I've felt the same and @ChrisMaddock is [also](https://github.com/nunit/nunit/pull/2532#issuecomment-404866215) keen on this.

I propose a new builder API which does not expose concrete filter types. (Concrete types could be exposed later on with more planning if there was a need.)

Strawman:

```diff
namespace NUnit.Framework
{
+   public static class TestFilter
+   {
+       public static ITestFilter Empty { get; }

+       public static ITestFilter Not(ITestFilter operand);

+       public static ITestFilter And(params ITestFilter[] operands);

+       public static ITestFilter Or(params ITestFilter[] operands);

+       public static ITestFilter Category(string value, bool isRegex = false);

+       public static ITestFilter ClassName(string value, bool isRegex = false);

+       public static ITestFilter FullName(string value, bool isRegex = false);

+       public static ITestFilter Id(string value, bool isRegex = false);

+       public static ITestFilter MethodName(string value, bool isRegex = false);

+       public static ITestFilter Namespace(string value, bool isRegex = false);

+       public static ITestFilter TestName(string value, bool isRegex = false);

+       public static ITestFilter Property(string name, string value, bool isRegex = false);
+   }
}
```

Example usage:

```cs
ITestFilter filter = TestFilter.And(
    TestFilter.Property("Foo", "42"),
    TestFilter.Not(TestFilter.Category("ExcludedCategory")));
```

With C# 6's `using static NUnit.Framework.TestFilter`:

```cs
ITestFilter filter = And(Property("Foo", "42"), Not(Category("ExcludedCategory")));
```

VB.NET would be required to add `Imports NUnit.Framework.TestFilter` and escape most of the names:

```vb.net
Dim filter As ITestFilter = [And](
	[Property]("Foo", "42"),
	[Not](Category("ExcludedCategory")))
```

We'd probably want to implement this in terms of our existing `Internal` classes and eventually make them private and use the public API internally.

**Comment by CharliePoole** [comment]
Why do we want to make it easier for users to bypass the engine? This makes no sense to me. 

We made these classes internal in the first place because we __didn't__ want people doing this. It seems like we are thrashing back and forth between conflicting approaches here.

Note also: any runner that does this must reference a particular version of the framework. That's exactly what the existing framework API was intended to avoid.

**Comment by jnm2** [comment]
@CharliePoole I've run into this whenever I used NUnitLite. Trying to understand: would you encourage putting this API in NUnitLite and in the engine instead?

**Comment by CharliePoole** [comment]
OK... saw your corrected post. Calling into the framework programmatically is something we have always tried to discourage. This proposal tends to encourage it. My theory would be that you first should have a discussion as to whether you want to start encouraging this kind of usage. If you do, then your proposal makes sense.

If you don't, then analyze why such usage is happening. There are a number of ways to discourage it:

1. By making classes and methods internal if we don't want people to use them. You yourself have been a big fan of that, which is why I'm a bit confused here.

2. Figure out what use cases are not being taken care of by the two published (documented) APIs for running tests (engine and framework) and extend those APIs to deal with it.

3. Publish some sort of assembly that makes it easier to call the framework APIs... although that really doesn't discourage the usage, it makes it easier to do it correctly.

**Comment by CharliePoole** [comment]
On the side... is creating a tree of filters using factory methods actually easier than passing in a where clause?

**Comment by jnm2** [comment]
Any time I build my own runner but want parts of NUnitLite. Recent examples are running NUnitLite on the [Blazor](https://github.com/jnm2/nunit-blazor-test/blob/c1a03a9d137e56aa83534471bdbc580d63ff3bae/BlazorTest.Client/TestRunnerService.cs#L62) runtime and just for development when building the UWP test runner.

Here's an example of using the framework directly to debug quickly into tests via keyboard shortcut, maybe clearer because I'm not using NUnitLite: https://github.com/nunit/nunit/issues/2243#issue-235401713

**Comment by jnm2** [comment]
> By making classes and methods internal if we don't want people to use them. You yourself have been a big fan of that, which is why I'm a bit confused here.

So I'm a fan of keeping true internals internal, but if there's a reason for an API, then I'm a fan of designing and exposing it on very deliberately.

If folks like @jairbubbles or me find ourselves manually constructing filter XML by hand in order to use `NUnitTestAssemblyRunner`, are you saying we should stop using `NUnitTestAssemblyRunner` and start using NUnitLite?

> On the side... is creating a tree of filters using factory methods actually easier than passing in a where clause?

Yes, *iff* the filter is programmatically generated.

**Comment by CharliePoole** [comment]
@jnm2 In that case, since you are a user who wants to use NUnit in a way it was not intended to be used (constructing the test assembly runner yourself) you should be interested in having the discussion! Making a major change of direction by inserting incremental changes that compromise the current direction is IMO not something we ought to do.

Initial topic, as I interpret this, would appear to be "How can we support users on platforms where it is impossible or impractical to use the engine?" 

Specific questions: Does NUnitLite need to be extended? Is there a need for a new client (not engine) assembly? Can we do this in a way that allows use across multiple framework versions or do we have to make people reference the framework?

[BTW many of these use cases are things I'm thinking about in my new framework, so my interest here is two-pronged.]

**Comment by jairbubbles** [comment]
Hello guys, clearly my usage is not common. I run unit tests directly in my application where I compile .cs files on-the-fly. It allows super fast iteration time and I think it's pretty cool!

As I said I can now use `TestFilter.FromXml` but I a agree with @jnm2 and an API oriented for programmers would be better. 

If all this was not public, I would have probably written my own (bad) runner or copy / pasted the code from console runner. So I guess it's a good thing that everything was public 😄

**Comment by jnm2** [comment]
@CharliePoole 

> In that case, since you are a user who wants to use NUnit in a way it was not intended to be used (constructing the test assembly runner yourself) you should be interested in having the discussion! Making a major change of direction by inserting incremental changes that compromise the current direction is IMO not something we ought to do.

I wasn't aware this would be a change in direction (obviously). If only NUnitLite and the engine are intended to use `NUnitTestAssemblyRunner`, that functionally means that you are not allowed to write your own runner without being one of NUnitLite or the engine. Doesn't that mean there's a very tight coupling between the two projects? (This is specifically mediocre news for my Blazor runner where both NUnitLite and the engine are impractical.)

**Comment by CharliePoole** [comment]
@jnm2 NUnitTestAssemblyRunner was never intended to be directly constructed. See the framework API description at https://github.com/nunit/docs/wiki/Framework-Api

It's truly unfortunate that many users have fallen into constructing the class, because it was made public.* OTOH, the docs are there to read for anyone. I would make those classes internal except that I know it would make many folks unhappy. OTOH, making it __easier__ to do things in an unintended way doesn't seem to me like the right way to go.

* I made it public so the user constructing it through reflection would not need to use `BindingFlags` - that was probably a mistake.

ON generating filters, it's really hard to see why you find the tree approach easier than calling a method and passing in the text of the where clause, as we currently do. This could, of course, be exposed by NUnitLite for public use.

If there is a real need for running the framework directly on some platforms, my initial thought would be to try to make NUnitLite independent of framework version and use it to expose any methods that are needed. However, we should have a list of target platforms first so that we do it in a way that can work on all of them.

**Comment by CharliePoole** [comment]
@jnm2 The API docs tell you how to write your own engine that runs the framework directly. Did you click my link?

Don't understand why you say the engine and framework projects are tightly coupled. They are the opposite. The engine doesn't even reference the framework.

**Comment by jnm2** [comment]
I did click your link, which is posted after I made that comment. So I was incorrectly using the assembly runner instead of using `FrameworkController` and `RunTestsAction`. Let's start over. :D
I still need to construct an XML string programmatically. In order to do so generally, I'd have to reinvent the implementation that the proposed API would provide.

If *this* is not a supported use of the framework, then we have the coupling problem. If it is a supported use, what can we do about the fact that I don't want to reinvent a programmatic XML filter builder helper in each project?

> ON generating filters, it's really hard to see why you find the tree approach easier than calling a method and passing in the text of the where clause, as we currently do.

I would then have to programmatically construct a valid `--where` CLI value, which is worse IMO than constructing the XML.

**Comment by jnm2** [comment]
> Where do you get your input that leads to the construction of the filter?

In some cases, the input has been a `Type` or `MethodInfo` object. Other times, it has been ids of certain loaded tests. I'm curious what you're doing too, @jairbubbles?

> The easiest thing to do would be to publish a separate assembly that makes it easy to use the framework, just as the engine does.

This makes sense to me. Would it live in this repo and have the same version as NUnit and reflect the filters understood by that version of NUnit?

> My assumption is that you don't use the engine because it doesn't run on your platform, right?

It seemed like more moving parts to maintain. I have a feeling a lot of us ended up using `NUnitTestAssemblyRunner` because we started out using NUnitLite's AutoRun, then realized we needed to customize and started using TextRunner, then realized we needed to customize even further and just copied what NUNitLite does: use `NUnitTestAssemblyRunner` directly. If that's not a thing users should do, we should consider displaying the correct pattern in NUnitLite.

**Comment by CharliePoole** [comment]
I can see how that would happen. Thing is, NUnitLite gets updated every time the framework gets updated. If that's acceptable in a runner, then it can use the same approach as NUnitLite. I feel it's not acceptable in a lot instances however.

Thing is, when NUnitLite was written, I had the notion that use of reflection would make it too slow. Remember, I wrote it for use under the Compact Framework 1.0, running on pocket PCs and similar hardware. On modern platforms, the minimal use of reflection that we make in loading and running tests has hardly any performance impact. I'd now rewrite NUnitLite so it didn't reference the framework at all. Only issue: are there platforms that don't support constructing a Type via reflection?

**Comment by jairbubbles** [comment]
> I'm curious what you're doing too, @jairbubbles?

Originally we hardcoded the filter but recently we wanted to allow users to filter by using the command line. As we needed something very simple we ended with a symple syntax ("-runTests=foo" or "-runTests=!foo") and build an xml from this. My first choice would have been to allow NUnit format (`where` clause) even it's too complex for our use case but I couldn't find a way to get it as it's part of the NUnit.Engine.dll which seems shipped only with the console package.

I don't know about NUnitLite much but as it's a "Lite" version I didn't think it could be useful to me compared to the "full" version. My platform is windows so I could use the console runner but running it inside my process gives me more info (test count for instance) and I don't need to parse the log to report the errors. I didn't test but I also think it's quicker to run that way (no need to spawn a process, my tests assemblies are already loaded etc...).

**Comment by jnm2** [comment]
@jairbubbles Great, thank you!

In 3.0, NUnitLite is a lightweight version of the console runner which comes with the full NUnit framework. The NUnitLite NuGet package references the NUnit package. Using NUnitLite would actually give you the ability to specify a `--where` filter which you originally wanted. Does that look helpful?
(See more: https://github.com/nunit/docs/wiki/NUnitLite-Runner)

@CharliePoole Curious about this:

> The easiest thing to do would be to publish a separate assembly that makes it easy to use the framework, just as the engine does.

This makes sense to me. Would it live in this repo and have the same version as NUnit and reflect the filters understood by that version of NUnit?

**Comment by CharliePoole** [comment]
My assumption was that it would not be versioned with the framework, since the design goal would be to have it work with all versions.

A major overhaul of NUnitLite that was not versioned with the framework could also be used in this way, but that's a much bigger change. Perhaps it could be done incrementally.

Basically, I'm just throwing out ideas here. I haven't really analyzed the code to see how much effort it would take.

**Comment by jnm2** [comment]
Would we want to version it with the engine, maybe make it an engine feature?

**Comment by ChrisMaddock** [comment]
I will say, after initially being keen on the idea - Charlie’s point about us encouraging people to integrate via the engine, and provide this functionality there instead makes sense to me.

Passing filters directly to the framework is still possible, this feature is aimed to make that nicer. However - we already make one API available for this, through the engine - I feel like that should be the main ‘userfriendly’ API we support, with integration with the framework being for low-level and specialist cases. A separate assembly definitely sounds like a high maintenance cost to improve this experience, when we already provide a user-friendly api via the engine.

Of the two cases which started up this issue, as far as I can see - @jairbubbles’s could be using the engine. (There is a special nuget package which contains solely the engine - You’ll find a link in the nunit-console repo readme. This probably all points to a hole in our docs!) Joseph, your integration with Blazor will be somewhat experimental at this point - and I’m not too concerned if a manual xml string or two is necessary for this case! 😄 I think in the long run, we’d of course have an engine build.

**Comment by jnm2** [comment]
This is a good discussion. Closing since there's nothing to do for the framework. We can always open this proposal for the engine is there is interest.
