### ISSUE TITLE
Wrong message for Assert.AreSame

### ISSUE THREAD

**Issue by AlainDupont** [nunit/nunit#2932]
Wrong message when Assert.AreSame does not compare with different type.

            IDictionary<string, EventCode> expectedResult = new Dictionary<string, EventCode>();
            IDictionary<string, int> result = new Dictionary<string, int>();
            Assert.AreSame(expectedResult, result);

NUnit.Framework.AssertionException
  HResult=0x80131500
  Message=  Expected: same as <empty>
  But was:  <empty>
Should be something like:
NUnit.Framework.AssertionException
  HResult=0x80131500
  Message=  Expected: type ....
  But was:  type....

**Comment by jnm2** [comment]
@AlainDupont Hmm, I'm not sure. `SameAs` doesn't care about type, only reference equality. It seems like we should definitely keep the words "same as" because that's what the assertion is actually doing; it's concerned with object identity.

`Assert.AreSame(3, "test");` gives:

```
  Expected: same as 3
  But was:  "test"
```

Does this cause any problems, in practice? Maybe we could do something like this, if the types differ?

```
  Expected: same as 3 (int)
  But was:  "test" (string)
```

**Comment by rprouse** [comment]
I agree with @jnm2 on this one, same as is only interested in reference equality. The blanks after `Expected: same as` are a bit annoying, but the message clearly states that they are not the same reference. When a developer uses `SameAs`, they are only concerned with reference equality. If they are concerned with more, there are other appropriate constraints.

I'm going to close this as won't fix but can reopen if someone has a compelling argument to keep it open 😄
