### ISSUE TITLE
Warn.If in Assert.Multiple

### ISSUE THREAD

**Issue by ArvoX** [nunit/nunit#2979]
This test
`
[Test]
public void Test()
{
  Assert.Multiple(() => Warn.If(true));
}
`
gives this result: System.Exception : Warn.If may not be used in a multiple assertion block.

But the documentation of [Multiple Asserts](https://github.com/nunit/docs/wiki/Multiple-Asserts) says:

> 7. Use of Warnings (Assert.Warn, Warn.If, Warn.Unless) is permitted inside a multiple assert block. Warnings are reported normally along with any failures that occur inside the block.

So either the documentaion is worng or there is a worng check in the code.

**Comment by mikkelbu** [comment]
I just tried on the latest released code and I get the same behaviour (which also corresponds with the code) https://github.com/nunit/nunit/blob/6f806c61eb84f1fed0b47f9b90f1d1e21ec72e14/src/NUnitFramework/framework/Warn.cs#L511-L515

Also it is a bit misleading that it always write "Warn.If may not be used" even if the assertion was `Warn.Unless(false)`.

**Comment by ChrisMaddock** [comment]
I have memories that there’s a good reason for this, but I can’t remrmber what that reason was! I imagine it might be hidden in the git history when that line was added -afraid I’m on my phone again, so can’t check!

**Comment by CharliePoole** [comment]
Amazing that nobody has reported this up to now, since the code has been there since `Warn.If` and `Warn.Unless` were introduced!

Here's what happened: the original implementation was set up to work as it does - Warn not allowed in a Multiple Assert block. We had some discussion in the team and decided to allow it. Apparently, I only fixed `Assert.Warn` and not the `Warn` class.

You can find some past discussion about this in nunit/nunit-console#136. `Assert.Warn` does it the way we ultimately decided, while `Warn.If` and `Warn.Unless` don't.

Since I did the original work two years ago, I'll take this issue on.
