### ISSUE TITLE
TestCase not working for UnityTest

### ISSUE THREAD

**Issue by Xonoroff** [nunit/nunit#2989]
When I try to use TestCaseAttribute for methods that has returned value - it's doesn't work.
E.q 
This code works fine
```
[Test]
[TestCase(1)]
public void CustomTest(int i)
{
	Assert.AreEqual(1, i);
}
```
This - no
```
[UnityTest]
[TestCase(1)]
public IEnumerator CustomUnityTest(int i)
{
	yield return null;
	Assert.AreEqual(1, i);
}
```
In the last case I have error text 

> Method has non-void return value, but no result is expected

P.S. I'm using Unity 5.6.3p3

**Comment by Xonoroff** [comment]
PS. It's possible to use a little cheat code. And test will be passed, but in this case ExpectedResult isn't validated
```
        [UnityTest]
        [TestCase(1, ExpectedResult =  qweqweqwe)]
        public IEnumerator CustomUnityTest(int i)
        {
            yield return null;
            Assert.AreEqual(1, i);
        }
```

**Comment by ChrisMaddock** [comment]
From an Nunit point of view - this is all expected behaviour.

I know nothing about UnityTest I’m afraid - so don’t understand why you would return a value from a method like this. I’m assumkng unitytest is doing something with the return value?

I’m going to close this issue, as there’s no issue with nunit that I can see - and I think you may have better luck taking this issue up with the unitytest people. Feel free to comment further if I’ve missed something - we’ll still get the notification!

**Comment by mikkelbu** [comment]
> I know nothing about UnityTest I’m afraid - so don’t understand why you would return a value from a method like this. I’m assumkng unitytest is doing something with the return value?

Some googling gave [this document](https://docs.google.com/document/d/1SeNOAVYaq9HUjsKAC2ZvRwKLD2MCNyV4LwcsP3BXm0s/edit#heading=h.knefezjqd441) which states "`UnityTestAttribute` requires you to return `IEnumerator`." and also "Parameterized tests are not supported for `UnityTest` (except for ValueSource).", so the combination of the `TestCaseAttribute` and the `UnityTestAttribute` seems unsupported by the Unity Test Runner.

**Comment by pravusjif** [comment]
In Unity 2020.3.34f1 this hack actually works:

```
[UnityTest]
[TestCase(1, ExpectedResult =  null)]
public IEnumerator CustomUnityTest(int i)
{
    yield return null;
    Assert.AreEqual(1, i);
}
```
