### ISSUE TITLE
What is purpose of NUnit.Engine.API package

### ISSUE THREAD

**Issue by nvborisenko** [nunit/nunit#3017]
Hello guys, it's clear that this package should contain API aka interfaces, but it's unclear why this package doesn't have dependencies. Not critical for me, just wondering.

**Comment by CharliePoole** [comment]
It's the only assembly that a runner application needs because it seeks and finds the actual engine assembly and instantiates an engine. Earlier in development, we thought that people would be able to drop in a new engine and all runners would find it and update themselves. However, that turned out to be more complex than we had realized so currently runners come with an engine but that engine is never actually referenced by the runner - only the API assembly is referenced.

**Comment by nvborisenko** [comment]
Thanks for clarification.
