### ISSUE TITLE
ContainsConstraint ignores IgnoreCase in case of actual collection argument

### ISSUE THREAD

**Issue by Dreamescaper** [nunit/nunit#3039]
```
var items = new[]{"ABC", "dce"};
Assert.That(items, Does.Contain("abc").IgnoreCase);
```

Such assertion fails with message:
  Expected: some item equal to "abc"
  But was:  < "ABC", "dce" >

**Comment by CharliePoole** [comment]
Posting this on my phone from memory... someone should verify in the codebase.

I believe that containment checks that the __same__ object is included in the collection. IgnoreCase is allowed syntactically but since no equality operation is allowed it is ignored.

We could give a runtime error in this situation.

**Comment by Dreamescaper** [comment]
Currently it is equivalent to `new SomeItemsConstraint(new EqualConstraint(_expected));` in case of actual collection argument.
Any reason why it shouldn't be `new SomeItemsConstraint(new EqualConstraint(_expected).IgnoreCase);` for IgnoreCase?

**Comment by CharliePoole** [comment]
Never mind! Looking at the code, I see that the change to equality testing took place a long time back!

**Comment by EChaffraix** [comment]
FYI, I get this error on a linux with a new nunit project and only the following test :

```
[Test]
public void Test1()
{
    Assert.That("Hello World", Does.Contain("hello").IgnoreCase);
}
```

The problem was very different. The environment variable `LC_ALL` was set to `C.UTF-8` instead of `en_US.UTF-8`. Just changing it **solved** the problem.
