### ISSUE TITLE
3.11 breaking change

### ISSUE THREAD

**Issue by BrunoJuchli** [nunit/nunit#3050]
Note: not a big deal, just something I noticed when moving from 3.10.1 to 3.11:

I've implemented a custom attribute for test fixture discovery which implements `IFixtureBuilder`.
I've used to be able to do:

    var builder = new NUnitTestFixtureBuilder(
    builder.BuildFrom(typeInfo, fixtureParameters);

But now the method signature changed to require a `IPreFilter`, additionally. The implementation `PreFilter` is internal and I can't access `PreFilter.Empty` (which was the value used in 3.10 by `NUnitTestFixtureBuilder` in case no `IPreFilter` was passed).

I also see that `IFixtureBuilder2`s additional `BuildFrom(ITypeInfo typeInfo, IPreFilter filter);` method takes an `IPreFilter` as an argument. Should the other `BuildFrom` method maybe take the `IPreFilter` as an argument, too?

**Comment by CharliePoole** [comment]
I won't weigh in one way or the other about whether this should be changed, but I will explain why it is as it is.

`IFixtureBuilder` is an interface designed to be implemented by users, even though we make use of it internally as well. So, we couldn't change that interface but added a new one. To avoid breaking users, they are able to implement either `IFixtureBuilder` or `IFixtureBuilder2` and NUnit will use their custom attribute to discover tests.

On the other hand, `NUnitTestFixtureBuilder` was never created as a class for users to make use of, although you are far from the first one to use it. NUnit has a long history of public classes that are not intended for use by users. It's something we are tryingto change, which is why you find the new `PreFilter` implementation is internal. Really, `NUnitTestFixtureBuilder` should probably be internal as well unless we change the way we expect users to extend the framework.

That expectation, currently, is that the user will implement interfaces completely. With a few exceptions, NUnit provides no base classes to help you do that and no helper methods for your use. That's by design. The minute you use implementation code from within NUnit, your extension becomes dependent on a particular NUnit version. If you implement interfaces and we hold those interfaces constant, then it becomes possible to write extensions that work across multiple releases.

That said, it's entirely possible that the team will decide to change the way extensions are done. You could certainly make an argument that it would make your life easier.

Meanwhile, you can, of course completely implement `IFixtureBuilder` if you want a new type of fixture. Andi mplementing an empty pre-filter is pretty trivial.

**Comment by BrunoJuchli** [comment]
@CharliePoole thanks, makes sense.
I did indeed solve this by implementing `IPreFilter` myself (by just returning true...).
