### ISSUE TITLE
Add XSD file for each ITestEventListener event

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#3060]
Edit: I was confused—`<test-output>` and `<test-message>` don't go in the NUnit3 test results, so we'd need a separate XSD for each ITestEventListener event. I'll close this until there is demand.

**Comment by jnm2** [comment]
I was confused—`<test-output>` and `<test-message>` don't go in the NUnit3 test results, so we'd need a separate XSD for each ITestEventListener event. I'll close this until there is demand.

**Comment by jnm2** [comment]
I apologize, I don't follow. The point of using XML fragments as application interface is so that we don't need to use XSD to document the XML part of the interface?

**Comment by CharliePoole** [comment]
It needs to be documented. XSD is not used principally to document and is not, in fact, very useful as documentation for programmers. It's primary purpose is to permit automated validation of documents and, in some cases, automatic code generation for programs that  process the documents.

These fragments are not documents. They are message content between program components and are changeable. There is no restriction on what elements are used and the attributes and inner XML of any message may change. Driver programs and any others that choose to handle them (like our own console runner) need to be aware of that and be written accordingly.

I agree wholeheartedly that that last fact needs to be documented, along with the current known (because we don't know all of them)  formats. I just don't think XSD is very useful. Bluntly, if I were a programmer trying to use this XSD would be the worst possible documentation for me - worse even than searching the source code itself. What I would like to see is a list of known elements, their attributes and any inner elements. A set of general recommendations like "ignore any elements you don't recognize" would be useful to beginners as well.
