### ISSUE TITLE
TestCaseSource not loading attributes such as Category in TestContext

### ISSUE THREAD

**Issue by stokescomp** [nunit/nunit#3067]
I can get category for normal tests that don't use TestCaseSource. TestCaseSource runs a parameterized test. The TestContext.CurrentContext.Test.Properties does not have the category property. But it should.
If I want to have category I have to use this hack on the first line of the test which adds it to all the parameterized tests:
TestExecutionContext.CurrentContext.CurrentTest.Properties.Set("Category", "Header");

```
[TearDown]
public virtual void TestTearDown()
{
    //I want to access the category here. It is null when using TestCaseSource
    Console.WriteLine(TestContext.CurrentContext.Test.Properties.Get("Category").ToString());
}

[TestCaseSource("GetUsers"), Category("Header")]
public void VerifyChangeAssignmentButton(User user)
{
    //test body here
    Console.Write("code here");
}
```

**Comment by CharliePoole** [comment]
A parameterized test forms a suite of tests all using the same method. In NUnit both test cases and suites are known as "tests." The attributes you set on the test method become properties of __that__ test, i.e. the parameterized test suite that contains all the cases. They are __not__ properties of the individual test cases.

Properties of a suite can only be accessed from code that is running in the context of that suite. In this example, that would be any OneTimeSetUp or OneTimeTearDown because they are code of the parameterized method suite.

In order to set a property on an __individual__ test case generated from a TestCaseSource, you need to use the `TestCaseData` class and set the specific property. Using your example above, you would do it this way...

```c#
public IEnumerable<TestCaseData> GetUsers()
{
    ...
    yield return new TestCaseData(arglist).SetCategory("Header");
   ...
}
```

In your case, since you want the same category on every test case, use the second argument of `TestCaseSourceAttribute` to pass an argument to GetUsers().

NOTE: Even though the category is not set on the individual methods, running all the tests in the category works as you would expect. It's only if you try to access the applied category from the test itself that the problem arises.
