### ISSUE TITLE
CollectionAssert.AreEquivalent fails for ValueTuple Wrapped Dictionary

### ISSUE THREAD

**Issue by ecalder6** [nunit/nunit#3073]
The following code:

```C#
var a = new Dictionary<string, (string name, Dictionary<string, string> d)>()
{
    { "key", ("name", new Dictionary<string, string>())}
};

var b = new Dictionary<string, (string name, Dictionary<string, string> d)>()
{
    { "key", ("name", new Dictionary<string, string>())}
};

CollectionAssert.AreEquivalent(a, b);
```
fails the assert with message:

```
  Expected: equivalent to < ["key", ("name", <empty>)] >
  But was:  < ["key", ("name", <empty>)] >
  Missing (1): < ["key", ("name", <empty>)] >
  Extra (1): < ["key", ("name", <empty>)] >
```
I'm using the 3.10.1 release.

**Comment by mikkelbu** [comment]
Actually, I think that the problem can be simplified as follows:
```csharp
            var a = new ValueTuple<string, Dictionary<string, string>>("name", new Dictionary<string, string>());
            var b = new ValueTuple<string, Dictionary<string, string>>("name", new Dictionary<string, string>());
            Assert.That(a, Is.EqualTo(b));
```
which gives
```
  Expected: ("name", <empty>)
  But was:  ("name", <empty>)
```
The problem is that we try to compare the values with `EquatablesComparer` before `TupleComparer`/`ValueTupleComparer`, and `EquatablesComparer` does not use `NUnitEqualityComparer` for the individual elements of the tuple, but just regular comparison and for Dictionaries this is regular reference equality. So the current code only works for tuples with elements that are compared using value equality.

The problem can probably be solved by moving `EquatablesComparer` to after `TupleComparer` and `ValueTupleComparer` in the list of `IChainComparer`  in `NUnitEqualityComparer`, but it requires some more thought than just a quick brainstorm from my side.
