### ISSUE TITLE
Is.Ordered.By

### ISSUE THREAD

**Issue by NUnitTester** [nunit/nunit#3082]
Is.Ordered.By only works with Properties but it would be nice if it also works with fields.

`Assert.That(array, Is.Ordered.By("PropertyName"));`

FeatureRequest:
`Assert.That(array, Is.Ordered.By("FieldName"));`

Perhaps it would be nice to can use internal Properties / Fields also.

**Comment by mikkelbu** [comment]
I cannot see anything wrong with this request. It will require some changes in the code, but nothing major.

**Comment by kambleaa007** [comment]
Its predefined what properties respective array is holding.
So, Its easy for Property based ordering uses one or more properties that are common to every item in the enumeration like the Length.
To provide Field based need to make change in 
public class Is :- have static method :- public static CollectionOrderedConstraint Ordered { get; }
Need to change implementation there.
Unluckily i cant open that in my machine

Do you have any idea how to implement new one generic method so it will support old one as well as new.

**Comment by CharliePoole** [comment]
What do you mean by "can't open that in my machine?" If you have the source you can surely look at it. Are you trying to create a PR?

**Comment by kambleaa007** [comment]
When i control plus click it opens into declaration of class Is. shows [from metadata]. 
i cant find implementation there. Usually i get full code when i try control plus click on specific method.
Yes, i like to try to implement the is:idea of @NUnitTester 
Then this would be my first PR.
Not sure how to do contribution on open source projects.
and i have all basic idea about GitHub and its working.
Thanks

**Comment by CharliePoole** [comment]
I'll suggest some steps to contribute...

1. Open a GitHub account if you don't have one.
2. Use the Github site to fork the NUnit project so that there is a copy of it under your name on GitHub.
3. Clone your copy of NUnit onto your local machine (`git clone` if using command-line).
4. Make sure you can build NUnit yourself. Run the tests that come with NUnit using the command-line.
5. Create a new branch in your local machine for the feature or bug you want to work on.
6. Continue to work on and test your code until you feel it is ready for review.
7. Push the branch to your copy of NUnit on GitHub
8. Use the GitHub site to create a pull request (PR) for the NUnit team to review.

In building NUnit, refer to the BUILDING.md file in the root of the project.

Ask us if you have questions at any point along the way.

As a first item to fix, I suggest finding something smaller than this particular issue. That way, you can concentrate on the mechanics of doing a simple fix without worrying about the internal design of NUnit.

Good Luck!

**Comment by heshamamin** [comment]
I created a PR: #3214 to support fields. However I think supporting internal properties and fields need more discussion. As a side effect, private fields might be supported as well.
