### ISSUE TITLE
Add Exception Inspector Action To Throws.TypeOf When Using Constraints

### ISSUE THREAD

**Issue by JasonBock** [nunit/nunit#3090]
I'm using 3.10.1 of NUnit and it doesn't appear that this feature exists.

It doesn't seem like there's a way to inspect the exception when you use `Throws.TypeOf()`. It would be nice to not only verify the exception happened, but to also get a reference to it so you can check specific properties on it. Like this:
```
Assert.That(() => { ... }, Throws.TypeOf<MyCustomException>(e => { ... }));
```
In this case, `e` would be a reference to the `MyCustomException` exception that was thrown.

**Comment by CharliePoole** [comment]
You can do this in two styles right now...

```C#
var ex = Assert.Throws<MyCustomException>(() => {...});
Assert.That(ex, ...);
```

or

```C#
Assert.That(() => { ... }, Throws.TypeOf<System.Exception>().With.Property("x").EqualTo(5));
```

The second form is less general, since you can only use syntax that NUnit provides and not general C# syntax. The `TypeOf` operation may be followed by either `With` or `And` together with any NUnit constraint syntax.

The first form allows you to make any test you like on the exception itself or it's properties.

A new syntax, such as you suggest, would provide a third approach and some people would probably prefer it, but personally I'm not sure we need more ways to do the same thing.
