### ISSUE TITLE
NUnit getting stuck in a deadlock

### ISSUE THREAD

**Issue by karanjitsingh** [nunit/nunit#3102]
I have an issue, [azure-pipelines-tasks/issues#8838](https://github.com/Microsoft/azure-pipelines-tasks/issues/8838) where vstest gets stuck in a deadlock. I don't have much info regarding what's going on but I was able to take a dump of the process when it hung. https://1drv.ms/u/s!Ak6PtdH57mRsiFSP72gBEBkdQAfS

From the dump it seems NUnit is waiting on something, #2145 seemed like a similar issue.

The tests belong to https://github.com/github/VisualStudio. I was able to figure out that [PullRequestSessionManagerTests.cs](https://github.com/github/VisualStudio/blob/master/test/GitHub.InlineReviews.UnitTests/Services/PullRequestSessionManagerTests.cs) is the file that seems to be triggering the issue, maybe that could help you give you more insight about the issue.

**Comment by ChrisMaddock** [comment]
Hi @karanjitsingh - could you check this is still a problem in the latest version of the framework please? Looks like you're currently on 3.9.

**Comment by rprouse** [comment]
@karanjitsingh I don't see any of the usual suspects in the tests that you linked to. In the past, problems like this have been because of combinations of things like parallel test fixtures, STA threads and sometimes `OneTimeSetUp`. I don't see anything special in those tests other than `async` code.

Are you sure it isn't the code under test that is deadlocking? Are you able to reproduce using the NUnit Console? If you can, then you could debug the tests to see where they are deadlocked.

**Comment by grokys** [comment]
To give some extra context to this, here is a Azure Pipelines run that is hanging: https://github-editor-tools.visualstudio.com/VisualStudio/_build/results?buildId=608

NUnit reports:

```
Total tests: Unknown. Passed: 960. Failed: 0. Skipped: 3.
Test Run Aborted.
Test execution time: 2.0004 Minutes
```

> Are you sure it isn't the code under test that is deadlocking? Are you able to reproduce using the NUnit Console? If you can, then you could debug the tests to see where they are deadlocked.

I think that yes, this is the code under test that is deadlocking. The test run has a timeout of 2 minutes and times out, reporting that the test run was aborted as you can see above. However something hangs after this happens, causing the build to time out after 1 hour.

**Comment by CharliePoole** [comment]
Regarding the call stack... three threads are visible in theimage... from left to right...

1. This is the main thread that lauches execution and then waits for the tests to complete. It doesn't actually run tests so it's normal for it to be waiting.

2. This is the "event pump thread." As events such as test start, test complete, etc. occur, they are serialized to a queue, which this thread reads in order to dispatch the events. It too is normally in a wait state.

3. This is a worker thread, which is running one of your tests. It's an asynchronous test and NUnit is waiting for it to complete. If you don't have a large number of async tests, it may be possible to narrow the problem down a bit.

**Comment by Bakanych** [comment]
Having same issue with the NUnit 3.13.

**Comment by CharliePoole** [comment]
See my last comment on the original post. It's not an NUnit problem - a user test is hung. Not sure why this is still open.

Anyway, if you have the "same" issue then one of your tests is hung. But if you have different or additional information, we can take a look at it.

**Comment by Bakanych** [comment]
Thanks for the quick reply. I'll check again if it can be test issue.

**Comment by rprouse** [comment]
I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.

**Comment by johncrim** [comment]
In case it helps anyone: The Azure Pipelines VM only has 2 (virtual) CPUs - so it deadlocks quite easily, usually due to a synchronous method calling an async method and blocking. You should be able to reproduce the problem locally by configuring your test runner to only use 2 threads.

**Comment by Bouke** [comment]
@johncrim how are those 2 threads related to 2 (virtual) CPUs? Surely those 2 cores can run more than 2 threads.

**Comment by johncrim** [comment]
@Bouke - well, it depends on what the test runner does. Certainly 2 OS CPUs doesn't limit the number of threads in the process, but it seems that some test runners do limit the number of threads to match the OS CPUs.

I was experiencing this issue in Azure Pipelines on our xunit tests (we mostly use xunit), and I was able to reproduce it locally by setting the test runner max threads to 2. But it looks like xunit may have fixed this issue:

https://xunit.net/docs/running-tests-in-parallel#algorithms

Their old design was used a SynchronizationContext:

> This is the original parallelism algorithm, which starts as many tests as possible, regardless of your max parallel threads setting, and uses a [SynchronizationContext](https://learn.microsoft.com/en-us/dotnet/api/system.threading.synchronizationcontext) to limit the number of things that are running at any given time...

And a SychronizationContext can act as a lock, causing the deadlock. A synchronous method calling an async method will use up 1 of your threads; all you need are 2 of those for a deadlock to occur.

**Comment by CharliePoole** [comment]
NUnit uses the number of CPUs as a _default_. Alternatively, the user can set the maximum number of executing threads.
