### ISSUE TITLE
Support methods and etc. with TestOfAttribute

### ISSUE THREAD

**Issue by pantosha** [nunit/nunit#3113]
Right now, `[TestOf]` supports only type or type name. But often separate test case checks the behavior of only one method of a tested class and it can be useful to set it in the attribute.

```csharp
[TestOf(typeof(TestedClass), nameof(TestedClass.MethoOne))]
public void ShouldWork()
{
// some code...
}
```

**Comment by ChrisMaddock** [comment]
TestOfAttribute is an odd one, in that it really boils everything down to a string anyway.

Can you just clarify what you would want to see in the output with this? Would adding a ctor such as the below be more inclusive to anything people might want to do in future? What's the end output where you are using the TestOf results - is this for a GUI?

```
TestOfAttribute(params string[] values)
```

**Comment by ChrisMaddock** [comment]
With TestOf, everything boils down to a string anyway. What's your end use for this information - what would you like to see this new overload look like in the results? Could you explain the need for a new overload for TestOf, rather than just using the exsiting string constructor? e.g.

[TestOf(nameof(TestedClass) + nameof(TestedClass.MethodOne))]
public void ShouldWork()
{
// some code...
}

**Comment by mikkelbu** [comment]
I'm closing this, as we have not heard back from the reporter. We can reopen this issue, if more information arise.
