### ISSUE TITLE
Allow 'null' actual value for all constraints

### ISSUE THREAD

**Issue by Dreamescaper** [nunit/nunit#3116]
If for some reason my actual value is null, a lot of constraints simply crash (e.g. SomeItemsConstraint).
But that's not always desirable. I would prefer to see detailed assertion failure message, not thrown ArgumentException.

And it is quite annoying with DelayedConstraint. My actual value may be not-null after some time, but it doesn't check it - simply crash straight away, and I have to add `Is.Not.Null & Is.SomethingElse`

**Comment by CharliePoole** [comment]
In general, it's not true that constaints "crash" when given null values. They throw an exception, which is interpreted by NUnit as an error in the test and reported as such, rather than as a failure. In general, a failure indicates that the test "worked" but gave a negative result. An error indicates that there is something wrong with the test itself, not the thing being tested.

This has been discussed many times in the past. In general, it hasn't made sense to deal with the minority of cases where an error is inappropriate because the user can always deal with it by replacing `Is.SomeConstraint` with `Is.NotNull.And.SomeConstraint`. This has the added advantage that the code says specifically what it is you are testing for.

OTOH, there could be places where special handling of null is appropriate and `DelayedConstraint` might be one of them. Examples would help understand the problem in that case.

However, as a general thing, I don't believe we want all constraints to succeed on null values, especially as each individual constraint would have to be coded separately to deal with them.

**Comment by ChrisMaddock** [comment]
I agree with Charlie that DelayedConstraint is the may be the exception here, and examples would help understand what might be sensible.

**Comment by rprouse** [comment]
I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.
