### ISSUE TITLE
NUnit.Framework.AssertionException: shows previous scenario fail reason using specflow.

### ISSUE THREAD

**Issue by anfasansary** [nunit/nunit#3119]
I am using C#, Specflow and NUnit.
One of my feature file contains two scenarios. If both scenarios fails on executing, the last executing scenario's test explorer shows the error of first one also.
How do i remove the both errors and shows only the corresponding error only.

Note : Both error comes because of condition fail in NUnit Assert.

Please help me to resolve the case. I am attaching a screen here.

![error](https://user-images.githubusercontent.com/42206887/50267626-e1df2000-044d-11e9-994e-97b0009861b4.png)

**Comment by CharliePoole** [comment]
We need to see the code that leads to this outcome in order to help you.

**Comment by anfasansary** [comment]
> We need to see the code that leads to this outcome in order to help you.

[Tests.zip](https://github.com/nunit/nunit/files/2697706/Tests.zip)

![error1](https://user-images.githubusercontent.com/42206887/50269006-d93d1880-0452-11e9-8fc0-5d55c4c3058f.png)

**Comment by CharliePoole** [comment]
I have reviewed your code and it doesn't seem to use NUnit at all. All the references to test attributes, etc. are to Microsoft test (vstest). 

Did you attach the wrong zip file?

**Comment by mikkelbu** [comment]
Hi @anfasansary 
The code attached has the Nunit Assert.That commented out (and do no refer to NUnit in the using statements). Furthermore, the code does not metion `304177a` so I don't think that the attached code matches the images?

Which provider do you use to execute the tests? (from the attributes in the generated file I think MSTest, see e.g. https://specflow.org/documentation/Executing-SpecFlow-Tests/ for how to change the provider - I don't know if SpecFlow has a default provider).

Does the code work as expected when you use Assert.AreEqual (from Microsoft.VisualStudio.TestTools.UnitTesting and not the assertion from NUnit)?

**Comment by anfasansary** [comment]
> I have reviewed your code and it doesn't seem to use NUnit at all. All the references to test attributes, etc. are to Microsoft test (vstest).
> 
> Did you attach the wrong zip file?

Sorry i made a mistake. Please find the correct attachment.
[Tests.zip](https://github.com/nunit/nunit/files/2698052/Tests.zip)

**Comment by anfasansary** [comment]
> Hi @anfasansary
> The code attached has the Nunit Assert.That commented out (and do no refer to NUnit in the using statements). Furthermore, the code does not metion `304177a` so I don't think that the attached code matches the images?
> 
> Which provider do you use to execute the tests? (from the attributes in the generated file I think MSTest, see e.g. https://specflow.org/documentation/Executing-SpecFlow-Tests/ for how to change the provider - I don't know if SpecFlow has a default provider).
> 
> Does the code work as expected when you use Assert.AreEqual (from Microsoft.VisualStudio.TestTools.UnitTesting and not the assertion from NUnit)?

Sorry. The zip file wrong one. Here i attached the correct one. 
And the code works are expected using Assert.AreEqual and the provider is MSTEST.

![image](https://user-images.githubusercontent.com/42206887/50274605-a64f5080-0463-11e9-9096-4e77bed1a330.png)

[Tests.zip](https://github.com/nunit/nunit/files/2698065/Tests.zip)

**Comment by CharliePoole** [comment]
From LoginSteps.cs...

```C#
using IBAuroraFramework.Base;
using IBAuroraTests.Pages;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using TechTalk.SpecFlow;
using TechTalk.SpecFlow.Assist;

namespace IBAuroraTests.Steps
{
    [Binding]
    public class LoginSteps : BaseStep
    {
        //Context injection
        private readonly ParallelConfig _parallelConfig;

        public LoginSteps(ParallelConfig parallelConfig) : base(parallelConfig)
        {
            _parallelConfig = parallelConfig;
        }

        [Given(@"I see application opened")]
        public void GivenISeeApplicationOpened()
        {
            _parallelConfig.CurrentPage.As<LoginPage>().PageLoad();
        }

        [When(@"I enter UserName and Password")]
        public void WhenIEnterUserNameAndPassword(Table table)
        {
            dynamic data = table.CreateDynamicInstance();
            _parallelConfig.CurrentPage.As<LoginPage>().EnterUserDetails(data.UserName, data.Password);
        }

        [Then(@"I should verify the validation message")]
        public void ThenIShouldVerifyTheValidationMessage(Table table)
        {
            dynamic data = table.CreateDynamicInstance();
            Assert.AreEqual(data.ValidationMessage, _parallelConfig.CurrentPage.As<Dashboard>().GetLoginValidationMessage(), "Validation Message Mismatched");
        }

        [Then(@"I should see the username in User Menu")]
        public void ThenIShouldSeeTheUsername(Table table)
        {
            dynamic data = table.CreateDynamicInstance();
            Assert.AreEqual(data.ContactName, _parallelConfig.CurrentPage.As<Dashboard>().VerifyUserName(), "Contact Name Mismatched");
            //Assert.That(data.ContactName, Is.EqualTo(_parallelConfig.CurrentPage.As<Dashboard>().VerifyUserName()));
        }
    }
}
```

Note that the using statements do __not__ contain `using NUnit.Framework`. Instead, you have `using Microsoft.VisualStudio.TestTools.UnitTesting` 

Note that your assertions are `Assert.AreEqual` rather than `Assert.That` as shown in the image.

If this is the code you are executing, then it's absolutely guaranteed that NUnit is not running your tests!

We need code that matches the failure image.

**Comment by CharliePoole** [comment]
Your provider is MsTest. Additionally, you are using the MsTest `TestClassAttribute` in your features file. Your tests are run by MsTest and the fixtures are recognized because (1) you use the MSTest `TestClassAttribute` in your feature file and (2) you tell SpecFlow to generate code for MsTest, which it is happy to do. (This means that your generated steps class will contain MsTest `TestMethod` attributes.)

You are referencing the NUnit framework, but the only thing you are getting from it is the actual assertion. MsTest gets an `AssertionException` generated by NUnit and treats it as an unhandled exception rather than a simple test failure (which is how NUnit would treat it).

What is interesting is that the test seems to (sort of) work, which is surprising to me, but the results will be misleading. Decide on using either MsTest or NUnit, but don't try to combine them.

I'm closing this as an NUnit issue, but if you have further questions you can post them here and we'll see them.
