### ISSUE TITLE
Conditionally Ignore TestCase

### ISSUE THREAD

**Issue by brettwinters** [nunit/nunit#3165]
Hello

Previously in 2.x, the TestCase Ignore Attribute could be set using a boolean property. So if I wanted to ignore long running tests then:  `[TestCase(300, 20, Ignore =  MyTestSettings.IgnoreLongTests)]`

but now in 3.x the Ignore Attribute is set to a string property and trying either to empty string or null either ignores the TestCase (with empty reason) or throws an exception

How would I conditionally ignore (ie. toggle on/off) a TestCase in 3.x?

**Comment by CharliePoole** [comment]
You can conditionally ignore an individual test case, but not by use of a TestCaseAttribute.

If you use TestCaseSource Attribute referencing a source method or property, you may include logic to ignore the test conditionally.

This approach would actually give you a better solution. Rather than ignoring the tests, you could simply not return them, leaving yourself with success result rather than a warning.

**Comment by brettwinters** [comment]
Thanks for your quick reply! 

Yes, I saw that [here](https://github.com/nunit/docs/wiki/TestCaseData) and I can see the benefits - but that would mean that I would have to implement the class for each test (since different data) - and retro fitting that to a project with a million tests written in 2.x would not be easy....

Any other suggestions? otherwise lets close this question and I will do some more thinking...

**Comment by CharliePoole** [comment]
You could try making an attribute something like...

```C#
public class LongRunningTestCaseAttribute : TestCaseAttribute, IApplyToTest
{
    public ApplyToTest(Test test)
    {
        base:ApplyToTest(test);

        if (test.RunState == RunState.Runnable && MySettings.IgnoreLongTests)
        {
            test.RunState = RunState.Ignored;
            test.Reason = "Long-running test";
        }
    }   
}
```

WARNING: This is "forum code". I can't compile run or even compile it on the system I'm using. I just typed it in and I have almost certainly messed up somewhere. However, I think it gives you the idea and you'll be able to make it work if it looks useful.

Note, if you use this, you __could__ choose to skip rather than ignore the tests, which would mean they don't turn the  bar yellow at any point. That's up to you. Obviously, you would have to change each long-running test case to use this attribute.

I'll go ahead and close this but you can post any follow-up here and we'll respond.

**Comment by brettwinters** [comment]
Thanks very much for your help! Works ok in the case of only one testcase. 

However if I also have some 'short running' test cases as defined below when both are ignored/run

```
[TestCase(10, 10)] //normal, short running
[LongRunningTestCase(20, 10)]
public void GenerateSaveReport(int times, int duration){ ...

```
I think perhaps it's `test.RunState = RunState.Ignored` from your code that applies the whole test not just the single testcase? Another issue is that base does not implement `base.ApplyToTest(test);` so I dropped that from your code...

I have a feeling I'm going to have to go with TestCaseSource haha

**Comment by CharliePoole** [comment]
Sorry, I'm set up badly here, having to spin up code on one machine and use the internet on a different one, so I couldn't try it out. The interface I gave you is implemented by IgnoreAttribute, which is not actually relevant here. We want `ITestBuilder`.

If you are of a mind to keep trying, start with this...

```c#
public class LongRunningTestCaseAttribute : TestCaseAttribute, ITestBuilder
{
    IEnumerable<TestMethod> ITestBuilder.BuildFrom(IMethodInfo method, Test suite)
    {
        var cases = base.BuildFrom(method, suite);

        if (MySettings.IgnoreLongTests)
            // There's only one test, but iterate to avoid making assumptions about implementation
            foreach (var test in cases)
                if (test.RunState == RunState.Runnable)
                {
                    test.RunState = RunState.Ignored;
                    test.Properties.Set(PropertyNames.SkipReason, "Long-running test");
                }

        return cases;
    }
}
```

If you try it, let us know what happened. I'm going to edit the earlier post so the bad code doesn't confuse anyone in the future.

**Comment by brettwinters** [comment]
no, problem. Yes, I'm keen if you are 

tried again, but in this code both tests run regardless of whether IgnoreLongTests is true or false. It seems that 'test.RunState = RunState.Ignored;' is ineffective (code runs ok) on the actual test...

I also commented out the TestCase attribute, but makes no difference
```
[LongRunningTestCase(20, 10)]
public void GenerateSaveReport(int times, int duration){ ...

```

**Comment by CharliePoole** [comment]
Are you sure that code is actually executing? IgnoreLongTestCases has to be set before discovery begins. Where does that happen?

**Comment by brettwinters** [comment]
yes, the `LongRunningTestCaseAttribute' code is executing. It loops over the tests (only one) and I can set a breakpoint and see the test arguments, etc...

If you mean the `MySettings.IgnoreLongTests` - it's just a static property. But for good measure I commented out `if (MySettings.IgnoreLongTests) {..` so that the `test.RunState = RunState.Ignored' etc always runs and confirmed that the test runs anyway...

And just for my own sanity I also I commented out `[LongRunningTestCase(20, 10)]` and enabled `[TestCase(10, 10)]` and also confirmed that `LongRunningTestCaseAttribute' doesn't execute, but the test runs, of course...

**Comment by CharliePoole** [comment]
Wow! I'm almost sorry to have started this. :confused:  OTOH, I'm glad I did because I learned something. The code doesn't work because the individual tests returned from the enumeration are __not__ actual references to the tests that are built. I finally got to where I could actually build and test it and I updated the code.

NOTES:

1. The example is still a manual transcription from another machine and may have typos.

2. Success is still dependent on where and how you initialize your static switch. Has to take place before discovery, which eliminates doing it in any SetUp routine. I cheated and initialized at compile time. How you do it will depend on where the true/false value comes from in the first place.

**Comment by CharliePoole** [comment]
@nunit/framework-team I must say that what I tried here is a good example of something that seems like it should work but doesn't in any obvious way. Maybe a future standard should be that we use final on all classes unless we have actual tests of using inheritance.

**Comment by brettwinters** [comment]
thanks a lot Charlie it's working! I'm pleased to have stumped the NUnit guru for a minute haha
