### ISSUE TITLE
Teardown method in parallel test run is called on the same object for every test

### ISSUE THREAD

**Issue by DeBesten** [nunit/nunit#3173]
When running this underlying code example will print the same output for each of the 4 test runs. 
It would be my expectation that a teardown method would be called on the object which has just finished running the test. In this case the output would be different for every test run. 
The reason we expect this behavior is because we expect each test to be able to clean up or close the resources it has used while not affecting resources in use by other parallel tests. 
When running the same test without parrallisation this is not an issue; in other words the different output their respective parameter message. 

```
using NUnit.Framework;
using System;
using System.Collections.Generic;

namespace PrototypeMBT
{
    class Class
    {
        string message;

        [TestCaseSource("TestCases")]
        [Parallelizable(ParallelScope.All)]
        public void TestMethod(string message)
        {
            this.message = message;
            Assert.That(true, Is.True);
        }
        static List<string> TestCases()
        {
            return new List<string>() { "hello", "hi", "bonjour", "goeiendag" };
        }

        [TearDown]
        public void TearDown()
        {
            Console.WriteLine(message);
        }

    }
}
```

**Comment by CharliePoole** [comment]
It's a long-time feature of NUnit that a TestFixture runs all it's tests on the same object. This is different from some other frameworks and some people have even called it a mistake but it has been that way for almost 20 years.

Before parallel execution, it was harder, but still possible, to mess up by having tests interfere with one another. Now it's dead easy and some kind of backward-compatible change is clearly needed.

Issue #2574 addresses this problem. I'm closing this as a duplicate but if you have any further comments or questions you can ask them here and we'll reply.

**Comment by stevenaw** [comment]
@DeBesten If it matches your use case, you can also consider using the `[OneTimeSetUp]` and `[OneTimeTearDown]` attributes if you intend for it to run once before ANY of the  tests in the fixture run, or after ALL the tests in the fixture run

**Comment by CharliePoole** [comment]
@DeBesten Sorry, I intended to give you a workaround but didn't include it....

1. If parallel tests break with instance members, it's obviously because the tests are changing the values, so use of `[OneTimeSetUp]` as suggested by @stevenaw will probably not work.

2. If you are able to change your instance members to static and run successfully in the non-parallel situation, then try making them thread static for the parallel case.

3. Failing that, just don't run the cases in parallel for fixtures that exhibit this behavior. If you have enough such fixtures, running them in parallel at the fixture level may be all you need to give the tests a performance boost. Use `[Parallelizable]` on fixtures that cannot support parallel test cases and `[Parallelizable(ParallelScope.Self + ParallelScope.Children)]` on fixtures that can.
