### ISSUE TITLE
NUnit Console Runner hangs with 2 [Parallelizable] [SetUpFixture]'s in 2 different namespaces.

### ISSUE THREAD

**Issue by MatteS75** [nunit/nunit#3180]
Hi

I saw there's a few similar issues reported, but all closed for various reasons, but I couldnt see any fixes in regards to this.

To demonstrate my issue (which is ofcourse really a part of a bigger project) I have made a small project with a structure with 2 namespaces, each having its own parallelizable setupfixture. When running the tests using the console runner, it hangs. 

I attach the small project to easily reproduce the issue. Unpack the project, build it, run the tests using the Run.bat file included.

[FreezingTestRunner.zip](https://github.com/nunit/nunit/files/2919379/FreezingTestRunner.zip)

**Comment by mikkelbu** [comment]
Hi @MatteS75 
I just tried the example, and on my machine the the console hangs every 3rd run, but I think that this is actually a problem in the framework that was reported (and solved) in nunit/nunit#2772. At least on my machine the problem goes away when I use the build from master instead of Nunit version 3.11.0.

The build from master can be found via https://www.myget.org/feed/nunit/package/nuget/NUnit (currently version 3.12.0-dev-06150). Does this also solve the problem on your machine?

**Comment by MatteS75** [comment]
Yes, it is random in our larger solution. This small solution fails 100% on 2 boxes iv tried on here. In our larger project it fails more randomly, but cant reproduce that on my developer environment, only in our build environment. Maybe its interesting to know that adding --trace:Verbose will make it fail more often.

It does work for me with 3.12.0-dev-06150! Not sure I can test that on our larger project in our build environment though. Is there any plan for a 3.12 release?

**Comment by ChrisMaddock** [comment]
Closing - fixed in 3.12. 👍

**Comment by rprouse** [comment]
@MatteS75 we haven't set a date for the 3.12 release, but with issues like this outstanding it will be much closer to the quarterly cadence.

**Comment by ChrisMaddock** [comment]
You're living in the past, Rob - 3.12 has been released already! 😄 

This was just an older issue I came across yesterday, and closed. 🙂

**Comment by rprouse** [comment]
@ChrisMaddock since I built and released it, you would think I would know better 😄
