### ISSUE TITLE
Template Based Test Naming - Incorrect truncation for individual arguments

### ISSUE THREAD

**Issue by tonyhallett** [nunit/nunit#3181]
[Thought this could be a documentation issue - apparently not](https://github.com/nunit/docs/issues/300)

Apparently individual arguments should not truncate when not specifying a truncation length, but they do.  There is no test that covers this.

[Line to be changed](https://github.com/nunit/nunit/blob/8c8cc6c8ff8b24002a94a9457c4a10a4db9f26d2/src/NUnitFramework/framework/Internal/TestNameGenerator.cs#L157)
Should be 
`fragments.Add(new ArgumentFragment(index, 0));`

The additional test is simple to add but to get the tests to run require some effort due to missing .Net frameworks/ .NET Core as well as an msbuild error.  

@CharliePoole Please can you have a look

**Comment by CharliePoole** [comment]
@nunit/framework-team I want to make sure everyone agrees that this should be fixed, as I suggested to @tonyhallett on nunit/docs#360. It seems like a clear error to me.

1. As described in nunit/docs#300 it's inconsistent with `{a}`

2. Originally, all the class used a constant width of 40, which was changed so that there is no default limitation of length in the framework, but 40 was retained as a limit for each individual argument. The value `40` doesn't appear anywhere else.

3. I made the changes back in 2015, as well as originally creating the class, but I can't remember the reason, if I had one, to keep the intrinsic limit on `{o}`.

4. If the framework has no intrinsic limits, runners can still impose them by truncating the string. But there is no way for the runner to reconstruct the full argument if the framework truncates it.

What do you think?

**Comment by ChrisMaddock** [comment]
Sounds good to me 👍
