### ISSUE TITLE
Cannot debug nunit when started from test adapter

### ISSUE THREAD

**Issue by tonyhallett** [nunit/nunit#3183]
The debugger will be launched if DebugTests setting is true [DebugTests setting is true](https://github.com/nunit/nunit/blob/ad943eb94fe280e661fc6c690043fe8eb0a11e40/src/NUnitFramework/framework/Api/NUnitTestAssemblyRunner.cs#L299).  This can be specified when running from the nunit console and with an IProjectLoader extension ( nunit-project-loader allows for this ) but not through the v3 adapter.  Should this be [read from run settings](https://github.com/nunit/nunit3-vs-adapter/blob/4fbba48b20095c037414d91a38dc62311708d544/src/NUnitTestAdapter/AdapterSettings.cs#L211) and [applied to the TestPackage Settings ?](https://github.com/nunit/nunit3-vs-adapter/blob/4fbba48b20095c037414d91a38dc62311708d544/src/NUnitTestAdapter/NUnitTestAdapter.cs#L151)

**Comment by CharliePoole** [comment]
How are running tests? The IDE, of course supports debugging on its own. The console option exists as a simple way to break into the debugger because there is no easier way.

**Comment by tonyhallett** [comment]
I don't want to debug my tests. I want to debug nunit.  Of course I could use the console but...

**Comment by tonyhallett** [comment]
Also, shouldn't the debugger attach option also be available for [discovery ?](https://github.com/nunit/nunit/blob/ad943eb94fe280e661fc6c690043fe8eb0a11e40/src/NUnitFramework/framework/Api/NUnitTestAssemblyRunner.cs#L149)

**Comment by CharliePoole** [comment]
As the name suggests, the DebugTests option is for debugging tests under the console. When we debug NUnit components , we do it the same way as any other application... i.e. start it under Debug in VS after setting breakpoints. Further detail would depend on which NUnit component you are trying to debug. For example, I work differently on the framework versus the engine.

For debugging under the VS adapter, somebody else would have to jump in to advise you. I don't use it for working on NUnit because it introduces too many variables. In particular, the engine is used in a very particular way under the adapter, different from how it is normally used. OTOH if you wanted to test how the engine functions under the adapter, then that's what you may need.

**Comment by mikkelbu** [comment]
I'm closing this issue as answered. Please note that we will still see additional comments on this issue.
