### ISSUE TITLE
Nunit calls the TestFixtureSource getter in tests that aren't decorated with it

### ISSUE THREAD

**Issue by itaibh** [nunit/nunit#3200]
Create a project with 3 files:

Test1.cs
```
using NUnit.Framework;

namespace Tests
{
    [TestFixture]
    public class Test1
    {
        [Test]
        public void Test()
        {
            Assert.Pass();
        }
    }
}
```

Test2.cs
```
using NUnit.Framework;

namespace Tests
{
    [TestFixtureSource(typeof(TestDataProvider), nameof(TestDataProvider.FixtureArgs))]
    public class Test2
    {
        [Test]
        public void Test()
        {
            Assert.Pass();
        }
    }
}
```

TestDataProvider.cs
```
using NUnit.Framework;
using System.Collections;

namespace Tests
{
    public static class TestDataProvider
    {
        public static IEnumerable FixtureArgs => new TestFixtureData[]
                {
                    new TestFixtureData("a"), new TestFixtureData("b")
                };
    }
}
```

Try to run only `Test1.Test` using Visual Studio. The `TestDataProvider.FixtureArgs` getter is getting called, even though it is NOT decorated with `[TestFixtureSource]`.

Now comment out the attribute `[TestFixtureSource...]` in `Test2`. Try to run again. The `TestDataProvider.FixtureArgs` getter isn't getting called now.

Why does decorating one class with `[TestFixtureSource]` affect a different test?

**Comment by CharliePoole** [comment]
Marking this as a question...

The `TestFixtureDataSource` is not called __in__ any tests at all. It's called in the process of creating (discovering) tests, which has to happen in its entirety before any tests can be selected to run. If it didn't work that way, your tests would never be displayed in the Test Explorer.

However, your question is reasonable. Why would the `TestFixtureDataSource` be called __after__ you select a different test again? In fact, why would it be called __a second time__, no matter what you were running, since the tests were already discovered once?

As an experiment, you could try running the same tests in the gui runner available at https://github.com/testcentric/testcentric-gui. You will find that it __isn't__ run a second time after the initial display of tests unless you do something to modify and reload the tests. So, why is the Test Explorer different?

The answer is that Visual Studio performs discovery and execution using two different processes. The result is that the NUnit VS adapter, when it is executing the tests, has no knowledge of what tests have already been discovered! Consequently, it has to repeat the entire discovery process before it is able to run any tests. This approach (two processes) is basically baked into the way Test Explorer works and any adapter has to figure out a way to deal with it. For NUnit, we simply repeat the entire discovery.

There is a facility in the nunit framework that allows us to pre-filter tests that are not being run so that their discovery process (like test sources) does not have to take place. However, currently, the vs adapter code is unable to take advantage of it. An issue has been filed for this.

Hope this helps explain things. I'll close this but feel free to post follow-up questions here. We'll see and answer them.

**Comment by CharliePoole** [comment]
I can't give a precise answer solely from the description, but here is a general one.

You should not create such an object in code whose execution is out if your control and / or not totally predictable by you. With NUnit, that means

1. Not in a constructor because you do not know when or how many times the constructor may be called.

2. Not in a test case or fixture source, for the reasons already explained.

So what's left?

1. You could create it in the test itself, using a finally clause to close it, or under control of a using statement.

2. In a SetUp method, closing it in the TearDown.

3. In a OneTimeSetUp, closing it in the OneTimeTearDown.

4. In a SetUpFixture, but only if you do not need to make use of source arguments.

Best advice in using NUnit was to not do any significant work in a constructor toe many years. In later releases, many people made the assumption that TestCaseSource and TestFixtureSource were exempt from this advice but that's not so. They are equally part of the construction of tests.

One useful pattern is to pass the __arguments__ needed to construct your manager object in the data source but to only actually construct it in your OneTimeSetUp.
