### ISSUE TITLE
Need to run multiple assemblies as one

### ISSUE THREAD

**Issue by vanderkyl** [nunit/nunit#3202]
We are seeing multi assembly runs go through the OneTimeSetUp and OneTimeTearDown once for each assembly. Is it possible to run multiple assemblies as one overall assembly? 

To add some context, we are using the OneTimeSetUp and OneTimeTearDown methods to send updates to a web application that is used as a test manager GUI.

This means that when a group of tests coming from multiple assemblies is launched, our UI is receiving more than one update that the tests have started or finished. The number of updates obviously matches the number of assemblies in the test run.

Another related problem we are having is that when using the --workers console option, it is applied to each assembly instead of all of the tests. For instance if I set the workers value to 4, and run a group of 8 tests (4 in one assembly and 4 in another), all 8 tests will start running instead of just 4 at a time.

Any feedback is welcome. Thank you!

Environment:
VS 2017
.NET Framework 4.6.1
NUnit 3.11
NUnit3TestAdapter 3.13

**Comment by CharliePoole** [comment]
NUnit test attributes exist in the framework and only affect how the framework works. The framework is essentially capable of dealing with one assembly at a time and knows nothing of other tests that may be running under other frameworks or even other instances of the NUnit framework.

There is however one way to achieve what you want. It requires running all your assemblies in the same Process and AppDomain. Are you able to do that? (If not, there's no way, so I'm assuming the answer is yes in what follows) Also, you won't be able to do this running under TestExplorer, so what follows uses the nunit3-console runner

1. Run your tests under the console using `--process:Separate --domain:Single` options. This means that a single process with a single test AppDomain will be created and your test assemblies will be executed sequentially within that domain.

2. Use a static flag in your assembly-level SetUpFixture to ensure that the code only executes once. Because all the assemblies are running in the same AppDomain, the flag is shared among all of them. Code it something like this...

```c#
    static bool SetUpAlreadyRan = false;

    [OneTimeSetUp]
    public void GlobalSetup()
    {
        if (!SetUpAlreadyRan)
        {
            // your setup code
        }
    }
```

3. OneTimeTearDown is trickier. If you do't have it, so much the better. But if you do, modify the above to work something like this...

```c#
    static bool SetUpAlreadyRan = false;
    static int NumberOfAssemblies;

    [OneTimeSetUp]
    public void GlobalSetup()
    {
        NumberOfAssemblies++;

        if (!SetUpAlreadyRan)
        {
            // your setup code
        }
    }

    [OneTimeTearDown]
    public void GlobalTearDown()
    {
        if (--NumberOfAssemblies == 0)
        {
            // your teardown code
        }
    }
```

Does this look like a kluge to you? If so, good. That means you're paying attention. :smiley_cat: 

This is all very fragile. Any parallelism (between assemblies) would break it. Any premature termination of the run would break at least the teardown.

But it's the only way I can think of to emulate a feature that NUnit doesn't have at this point.

Repeating myself... there's no way for this to work under the Test Explorer. That's because test assemblies run in separate processes out of NUnit's control. If you really must have this for use with Test Explorer, then the only option is to combine all the assemblies into one.

I'm coding this as a question and marking it answered. If you have follow-up questions, post them here and we'll answer.

WRT adding the features you mentioned (cross-assemblyl one-time setup and allocation of threads), those would be new features of the engine itself, not of the framework, although the framework might need some changes as well in order for it to work. If you want to follow up I suggest two separate issues filed against https://github.com/nunit/nunit-console
