### ISSUE TITLE
How to set up running e2e tests consistently? 

### ISSUE THREAD

**Issue by Danfrid** [nunit/nunit#3226]
Hello to all! 
I have problem with running tests in the order I need.

### Environment: VS2019 + Webdriver 3.141 + Nunit 3.11 + VS Test Adapter 3.13

At the moment I used SingleThreaded Attribute, but without result..
Also have tried Order attribute, but this will create problems in the future.. 

The approximate structure of the tests:

**WebdriverSettings.cl**
```
[OneTimeSetUp Attribute]
..
Webdriver driver = new..
[OneTimeTearDown Attribute]
..
driver.Quit();
..
```
**Tests.cl**
```
[TestFixture, SingleThreaded]
-[Test]
public void Open( )..

-[Test]
public void Login( )..
..
```
The first running test is Login, in alphabetical order, but how to run them in writing order(synchronously)?

**Comment by CharliePoole** [comment]
Although running tests in a fixed order is generally not a great idea, NUnit does allow you to do it with the `OrderAttribute`. You are right that this can cause problems in the future, but any order-dependency, no matter how expressed, is likely to cause such problems as well.

The order of the tests as text is not available to NUnit, since NUnit is designed to work with test assemblies without reference to any source code.

Closing this as answered. If you have follow-up questions, you can add them here and we'll see them.

**Comment by Danfrid** [comment]
Clear.
Thanks for answer!
