### ISSUE TITLE
Catching assertion failure always fails tests

### ISSUE THREAD

**Issue by gregsdennis** [nunit/nunit#3242]
I would expect this to result in an inconclusive run:

```c#
[Test]
public void Test1()
{
	try
	{
		Assert.Fail();
	}
	catch (Exception e)
	{
		Assert.Inconclusive();
	}
}
```

however it fails.  Maybe I'm doing it wrong.

My scenario is that I'm reading test cases from a file.  Each test case has an expected result as well as a boolean to indicate whether the test is optional.  If the assertion fails but the test is optional, I want to get an inconclusive instead of the failure.

So my test is more like this:

```c#
[Test]
[TestCaseSource(TestCasesLoadedFromFile)]
public void Test1(Scenario scenario)
{
	try
	{
		var actualResult = RunTest(scenario);
		Assert.AreEqual(scenario.ExpectedResult, actualResult);
	}
	catch (Exception e)
	{
		if (scenario.IsOptional)
			Assert.Inconclusive();
		throw;
	}
}
```

How can I get the result I expect rather than it failing all the time?

**Comment by CharliePoole** [comment]
This was a deliberate change made from 3.5 to 3.6, which has been discussed in a lot of issues, most notably #2040. I'll summarize the logic here but you may want to review that issue and some of the others it points to.

1. The throwing of an AssertionException in order to designate failure is an __implementation detail__ in early versions of NUnit.

2. Catching the exception to prevent failure was an undocumented behavior, never guaranteed by the NUnit documentation.

3. As NUnit has matured, we have tried to separate the logical view of tests from their physical implementation as methods, classes,, etc. How we use exceptions is a big part of this.

4. There's unfortunately lots of advice on the internet telling you to code as you did. None of it is from us. :disappointed: 

What you are trying to do adds a new wrinkle to the cases that have come up in the past. You want to change the behavior to an inconclusive result rather than a passed result.

Using your simple example, you could do this as follows:

```c#
[TestCaseSource(TestCasesLoadedFromFile)]
public void Test1(Scenario scenario)
{
        if (scenario.IsOptional)
		Assert.That((scenario.ExpectedResult, Is.EqualTo(actualResult));
	else
		Assume.That(scenario.ExpectedResult, Is.EqualTo(actualResult), "Optional test failure");
}
```

In a more complex scenario, you might have to spell things out more, using Assert.Inconclusive.

**Comment by CharliePoole** [comment]
BTW, with the current implementation (which could change) catching the exception merely prevents the test from terminating after failure. The failure has __already been reported__. Your inconclusive result is also reported and NUnit uses the __worst case__ of all the reported results.

However, don't rely on this behavior either. :smile:

**Comment by gregsdennis** [comment]
You suggestion still results in a test failure, though now the message says it's optional.  This doesn't work for CI.  I need an inconclusive result so that the overall build passes.

> You want to change the behavior to an inconclusive result rather than a passed result.

No, I want to change the behavior to an inconclusive result rather than a **failed** result.  I want to downgrade the severity of the failure.  If I had an `Assert.Clear()` or something, I could clear the assertions detected during the `try`, and then the inconclusive assertion would take precedence.

Nevertheless, the workaround proposed in the opening comment of #2040 handles the scenario nicely.  Thanks for the link.

---

As a sidebar:

> This was a deliberate change made from 3.5 to 3.6...

A behavior change like this is breaking, mostly because it was widely used this way, whether it was documented or not.  As a result, it would have been better to make it a major version bump to be clear that this widely-used behavior is changing.

> However, don't rely on this behavior either.

This library is at version 3.x.  I would consider it to be fairly stable by now.  However statements like this lead me to believe it's not and could change at any time, shaking my faith in it and pushing me to use a different library.  This takes me back to the versioning comment above.  If a behavior changes in a way that breaks existing code, whether at compile time or run time, there should be a major version bump.  Within a major version, I should be able to rely on existing behaviors and functionality remaining unchanged.

**Comment by CharliePoole** [comment]
Did you try the suggestion? A failed Assume.That yields an Inconclusive result. That's its function.

WRT the quote, what I meant was "You want to change the behavior to an inconclusive result rather than to a passed result, as others asked for in past issues.

The point you make about our past decision is not unreasonable and was discussed at length when we made this decision. Every project has to decide how to handle such "accidental featured" on a case by case basis. We had been advising people not to try to catch AdsertionException for many years and the path we took enabled a large number of features like warnings and multiple asserts. Our versioning policy was not SemVer at the time, so we made it a minor release, while listing the change as breaking.

Anyway, if you try the alternative with Assume and it generates a failure, please file an issue. Note, however that an __error__ due to an unexpected exception is different from a failure. If your call itself throws, you need to catch that somewhere. Provide specifics if that's the case and I'll be glad to suggest something.

**Comment by CharliePoole** [comment]
Hmm... I would have hoped that __actually telling you__ what you can or can't consider stable would give you more, not less, confidence.

You can count on what's documented to work. It's guaranteed it we'll fix it. 

You can't count on internal behavior that's merely how we chose to implement a feature. In fact, it's bad practice to count on such things in any library.

You can ask for some accidental behavior to be made into a supported feature or exposed in some way like your suggested Assert.Clear. In fact if you look at the discussions I referenced you'll see that this was done for a number of use cases. You'll also see that we made it relatively hard for you to ignore an error or failure. That's because we believe ignoring failures in a test framework should be somewhat difficult.

I'm going on at length here to suggest that you might achieve more by helping us work towards a new feature that will help you rather than rehashing decisions made half a dozen releases back.

**Comment by gregsdennis** [comment]
You know what? I didn't see the subtlety of `Assume` vs `Assert`.  I'll give that a try.

**Comment by gregsdennis** [comment]
@CharliePoole I'd like to apologize for my saltiness.  I tried the `Assume` and it worked as you described.  Thank you.

I understand that the library was not under semver at the time of the change.  I trust that now that it is, such a change would trigger an appropriate update to the version.

**Comment by CharliePoole** [comment]
Glad it's working for you. Let us know if anything else comes up around this.
