### ISSUE TITLE
Should Assert.Pass() revert a failed test?

### ISSUE THREAD

**Issue by z002Holpp** [nunit/nunit#3245]
Considering the following test case

```csharp
[Test]
public void SomeTest()
{
    try
    {
        Assert.That(true, Is.False);
    }
    catch (AssertionException)
    {
        Assert.Pass();
    }
}
```

I observed that 
* the test **passes** when executed with nunit3-console.exe
* the test **fails** when executed with vstest.console.exe and the NUnit3 test adapter
```
Error Message:
   Expected: False
  But was:  True
[...]
Total tests: 1. Passed: 0. Failed: 1. Skipped: 0.
Test Run Failed.
```

When I remove the Assert.Pass() statement, the test fails in both cases. Thus, I guess it is a design decision that a failed assertion should not be able to be reverted by a catch block, an Assert.Pass or something similar. In this case, the console runner would be wrong. But I'm not sure about this, just seeing two different results.

**Could you clarify which is the expected behavior?**

_Additional Info:
nunit3-console.exe: v 3.10.0
vstest.console.exe: v 15.9.1
NUnit3 Test Adapter: v 3.13.0.0

**Comment by mikkelbu** [comment]
Closing this issue as Charlie has moved the issue to nunit/nunit-console.

**Comment by CharliePoole** [comment]
@mikkelbu Actually I moved it here from nunit-console!

**Comment by jnm2** [comment]
Considering that `Assert.Fail`, `Warn`, `Ignore`, `Inconclusive`, `Pass`, etc, may all be called in any order for a given test, can we say that items near the top of the list take precedence over items near the bottom?

- Error
- Failure
- Warning
- Inconclusive
- Ignored
- Pass

**Comment by CharliePoole** [comment]
If you mean a status of Error, Failure, etc. that is what we do (except that Inconclusive comes last).

However if we talk about Assert.Fail, Assert.Pass, Assert.Ignore or Assert.Inconclusive, we're on different ground. All of those are defined to end the test and then give the desired result. Each one has to be handled slightly differently. Assert.Fail is simplest, because it's the highest priority of the four. We end and fail. Assert.Pass is different.

If you issue Assert.Pass in a multiple Assert block that has pending failures, it's an error. The test ends with an error result. The catch situation is really similar to that so I think it should give an error too instead of just being ignored as it now is.

**Comment by manfred-brands** [comment]
Hi,

I tested the original code on NUnit4 and I get a green test.

**Comment by z002Holpp** [comment]
I can confirm. Ran with 

- vstest.console.exe
- dotnet test
- nunit3-console.exe
- VS TestExplorer
- NUnit Lite

under net8.0. 
All passing.

NUnit 4.1
NUnit3TestAdapter 4.5
NUnit.ConsoleRunner 3.17
NUnitLite 4.1

**Comment by stevenaw** [comment]
Thanks for checking back up on this @manfred-brands @z002Holpp 
I can also confirm the behaviour using the current latest of the adapter (4.5) in Visual Studio 2022 on both net462 + net8.0
