### ISSUE TITLE
Support TestName property on Test attribute

### ISSUE THREAD

**Issue by fergusonr** [nunit/nunit#3285]
To allow you greater control over the test name displayed in test explorer. Thus allowing characters that are illegal in a method name,

```c#
[Test(TestName = @"UAT\Test:2")]
public void UAT_Test_Part2()
{
}
```

**Comment by goblinmaks** [comment]
@CharliePoole It is matched with nunit `TestAttribute ` concept ?

**Comment by CharliePoole** [comment]
Sorry @goblinmaks can you explain what you mean?

**Comment by goblinmaks** [comment]
@goblinmaks If it in not implemented before maybe it have any limitation in implementation. 
If not, I will try to do it. 
Thanks,

**Comment by CharliePoole** [comment]
@goblinmaks I see no technical reason why it could NOT be implemented. However, this request has never been triaged by the @nunit/framework-team to indicate it would be accepted or not. I'm no longer part of that team, but perhaps @rprouse or someone else on it can advise as to whether this is a desired feature.

I will add one comment, however... the original request talks about running tests under Visual Studio. Whether changing the framework in this way will allow the Visual Studio NUnit adapter to display arbitrary names is a different matter, which @OsirisTerje may want to look at if that's the main reason for doing this.

**Comment by fergusonr** [comment]
While this feature is moderately useful on its own, its also tied to this:-

https://developercommunity.visualstudio.com/idea/591421/test-explorer-allow-testnames-to-create-heirarchy.html

When having many tests in the same namespace/class, allows you to introduce hierarchy for better clarity

**Comment by CharliePoole** [comment]
@fergusonr Actually, it seems somewhat less related as it only applies to TestAttribute, which is not used for tests with arguments.

**Comment by jnm2** [comment]
I don't see why not, since it's just shorthand for what TestCaseAttribute lets you do already and it looks like two people are interested in it. @nunit/framework-team?

**Comment by rprouse** [comment]
Personally, I've always found it odd and potentially confusing renaming tests unless you need clarity distinguishing the parameters as with TestCase. We do allow it to clarify test cases in that scenario, but we've never gone any further. For example, you can inject parameters using the `Value` and `ValueSource` attribute, but can't rename the names of the parameters used in the tests.

I also expect that doing this will break the real-time test discovery in Visual Studio until that team catches up and supports renaming tests in that way. Even after several releases of Visual Studio, it is still broken for `TestCaseSource`. I know "it isn't our problem", but it is @OsirisTerje who ends up dealing with the issues.

Can anyone comment on how R# discovers named tests?

Based on that, I'd be reluctant to add a feature like this since it is only a nice to have.

**Comment by goblinmaks** [comment]
@rprouse @OsirisTerje 
Visual studio 16.4.6
NUnit3TestAdapter 3.16.1

Displayed and executed `[Test(TestName = "blabla")]` correctly but as side effect we see same test twice in TestExplorer with different names. It is very similar to https://github.com/nunit/nunit3-vs-adapter/issues/729

**Comment by fergusonr** [comment]
The ultimate goal of this request, was to allow TestAttribute to introduce one further level of hierarchy in test explorer with the introduction of '\' in the testname. In a similar way that TestCaseSource does automatically. 

I don't even know where the hierarchy is created (NUnit adaptor or Visual studio) so this seems too lofty a goal for a nice to have. 

[Test(TestName = @"UAT\Subset1")]
public void UAT_Test_Part1()
{
}

**Comment by CharliePoole** [comment]
This issue only impacts test attribute so it wouldn't affect tests with data arguments, which use TestCase, TestCaseSource, etc.

Personally, I don't even see it as nice to have.

The hierarchy is created by NUnit itself, which is why other runners can display it already. Displaying it in test explorer requires work on both rest explorer and the adapter.

**Comment by goblinmaks** [comment]
Looks like no need any additional work on nunit3-vs-adapter, you can check it by getting my PR code.

**Comment by jnm2** [comment]
> The ultimate goal of this request, was to allow TestAttribute to introduce one further level of hierarchy in test explorer with the introduction of '\' in the testname. In a similar way that TestCaseSource does automatically.

This would not get you to that goal. The hierarchy is already settled before names are produced.

**Comment by CharliePoole** [comment]
@fergusonr If that was your goal in writing it, I'm afraid it's not implicit at all in the issue. As @jnm2 writes, allowing the name of a test to be changed doesn't change the hierarchy, just the name.

**Comment by fergusonr** [comment]
Understood, I'm going to close this issue - thanks all
