### ISSUE TITLE
Category attributes not being set when using the Values attribute

### ISSUE THREAD

**Issue by ocmyhome** [nunit/nunit#3293]
When I have a test method with Category attributes, and also a Values attribute set, the Categories aren't being set to the Properties property of the TestContext.

```csharp
[Test]
[Parallelizable(ParallelScope.None)]
[Category("SSO")]
[Category("API")]
public async Task Some_Test([Values(ProductType.Unknown, ProductType.Crm, ProductType.Inv, ProductType.Web)] ProductType y)
```

So it'll run through the test 4 times, and for none of those 4 times it'll show any of these category properties set ("SSO" or "API").  Not sure what I'm doing incorrectly or why the categories aren't available.

**Comment by mikkelbu** [comment]
Hi @ocmyhome 
You are not doing anything wrong. When you place a `CategoryAttribute` on a parametric test method, then the category is only placed on the parent parametric test method and not on the individual tests. If you inspect the XML of a test-run you will see that this is the case, and you are not the first to be surprised by this. I've tried to collect all issues about this in https://github.com/nunit/nunit/projects/3, but it is a larger task to change the behaviour, so none has taken on the job yet.

I'm going to close this issue as a duplicate, as I think that the content of this issue is captured by the existing issues, but we will still see comments in this issue.

Ps. I've added some backticks to your example to make the syntax highlighting work.

**Comment by CharliePoole** [comment]
Adding to @mikkelbu 's comments, the categories actually __work__ the same when set on the higher level suite. That is, your individual tests all get run if that category is selected. It only becomes a problem if you are examining the properties of the context, which is why we have not treated this as high priority up to now.
