### ISSUE TITLE
[HandleProcessCorruptedStateExceptions] has no effect unless we disable partial trust

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#3301]
@nunit/framework-team This question can stand on its own, even though https://github.com/nunit/nunit/issues/3295 is dependent on the decision we make here.

### Conflict

@ggeurts asked for partial trust support and added it in https://github.com/nunit/nunit/pull/1775 which shipped in NUnit Framework 3.5.

Later, @endrih asked for NUnit to handle exceptions such as AccessViolationException and added it in https://github.com/nunit/nunit/pull/2512 which shipped in NUnit Framework 3.9. However, we all missed the fact that it has no effect under partial trust:

> The HandleProcessCorruptedStateExceptionsAttribute attribute is ignored when it is encountered in partially trusted or transparent code, because a trusted host should not allow an untrusted add-in to catch and ignore these serious exceptions.

(https://docs.microsoft.com/en-us/dotnet/api/system.runtime.exceptionservices.handleprocesscorruptedstateexceptionsattribute#remarks)

### Looking ahead

The .NET team decided not to implement partial trust on .NET Core. The partial trust attributes are no-ops on .NET Core. (See e.g. `https://github.com/dotnet/corefx/issues/12592`.)
.NET 5 is where the .NET community is headed and it will be based on .NET Core. (https://devblogs.microsoft.com/dotnet/introducing-net-5/) Therefore, the future of .NET does not have a place for partial trust. In contrast, exceptions such as AccessViolationException will likely always be something we'll want to catch.

In addition, CPU exploits such as Spectre have made it clear that security boundaries cannot be more granular than shared memory address space. Effectively that means that less secure code must be run in a separate process, period. .NET Core embraced this perspective from the beginning when the team decided that AppDomains were too fraught with issues to carry them forward from .NET Framework.

It's worth pointing out that if we merge https://github.com/nunit/nunit-console/pull/660, we won't need `[HandleProcessCorruptedStateExceptions]` when running under console 3.11 and newer since the config element opts in globally. We'll still need `[HandleProcessCorruptedStateExceptions]` when running under any other test host process with its own config, such as VSTest, ReSharper's test host, NCrunch, etc.

### Action

Should we keep the partial trust attributes? If so, how long? E.g. until v4 of NUnit?

If we keep support for partial trust, I'd like to put comments on each current and future occurrence of `[HandleProcessCorruptedStateExceptions]` noting that on .NET Framework it will only come into effect if we stop supporting partial trust.

If we don't keep support and @ggeurts or others still need it, they will be unable to upgrade to newer NUnit versions.

**Comment by CharliePoole** [comment]
I would lean toward...

Adding the comments you suggested.

Eventually getting rid of partial trust entirely. (NUnit 4)

In the engine, eliminating all options to run in-process or to specify how domain usage. (NUnit 4)

Individual runners, which use the engine, can restrict access to some features earlier than NUnit 4. I am planning to do that for the Experimental GUI at least, maybe for the standard one. Running tests in a separate process makes the most sense from a security point of view.

**Comment by ggeurts** [comment]
Partial trust tests are/were useful for testing of code that is to run in a sandboxed environment. My use case was code that would run in SQL Server Reporting Services reports.

As the .NET world moves on to a simpler security model, I would not have an issue with dropping support for partial trust in a next major release.

**Comment by jnm2** [comment]
Sounds like we will not make a change for v3?@rprouse and @nunit/framework-team Can you confirm this to enable me to move forward in https://github.com/nunit/nunit/issues/3295?

**Comment by mikkelbu** [comment]
I don't know much about partial trust, but after googling, I think Charlie's approach sounds as a good solution.

**Comment by rprouse** [comment]
I agree with @CharliePoole that we shouldn't be dropping partial trust in 3.x. This and other changes make me think that we might want to start thinking about the next version of NUnit. .NET development has changed dramatically since @CharliePoole started working on NUnit 3 and even since the first full release of NUnit 3. It might be time to start thinking about what NUnit 4 will be.

My initial thoughts are to evolve in the direction that .NET is going with a .NET Core / .NET 5 only version and continue to maintain and release bug fixes only for NUnit 3 for the next few years for people that are still using the earlier versions of .NET Core or the full framework.

This isn't the place for that discussion though, so I'm creating #3325 for that.

**Comment by jnm2** [comment]
I read https://docs.microsoft.com/en-us/dotnet/api/system.runtime.exceptionservices.handleprocesscorruptedstateexceptionsattribute?view=netframework-4.8#remarks which says something I hadn't seen before:

> The CLR delivers the corrupted process state exception to applicable exception clauses only in methods that have both the HandleProcessCorruptedStateExceptionsAttribute and SecurityCriticalAttribute attributes.

This sounds like we can both support partial trust and catch these exceptions by applying `[SecurityCritical]` to every method that has `[HandleProcessCorruptedStateExceptions]`.

**Comment by stevenaw** [comment]
There's been some discussions in #3325 about removing partial trust support in a next/future major version bump due to a lack of .NET Core support and potential conflicts with `[HandleProcessCorruptedStateException]` - though it seems like that last one may have a workaround by applying `[SecurityCritical]` to all affected methods. This would also mean applying `[SecurityCritical]` to any methods using modern ref-like APIs such as `MemoryExtensions.AsSpan<T>(T[])` or, in general, any code which may attempt to load and operate on addresses. This last part also makes it much more difficult to use some modern language features such as readonly structs (see https://github.com/nunit/nunit/pull/3603) due to some compiler optimizations employed on them. One available workaround _there_ could be to compile with the `peverify-compat` flag, however that has the knock-on affect of disabling the relevant compiler optimizations (see  https://github.com/nunit/nunit/issues/3604 and https://minidump.net/verificationexception-in-net-framework-when-using-structs-6269eb3df448).

As a result there seems to be general consensus in #3325 to remove partial trust support.

@nunit/framework-team any objections if I were to take this on?

**Comment by jnm2** [comment]
I'm on board with removing support for partial trust. Thank you!

**Comment by manfred-brands** [comment]
Yes, please remove it.

**Comment by ggeurts** [comment]
No objection from me either.
