### ISSUE TITLE
Minimal unit of DateTime in the report when Test was started/ended

### ISSUE THREAD

**Issue by nvborisenko** [nunit/nunit#3311]
Now I see in the report:
```xml
start-time="2019-07-04 22:32:33Z"
```

So minimal unit of time is `seconds`. It would be nice to see here more concrete date/time with milliseconds.

**Comment by ChrisMaddock** [comment]
Sure, why not.

I haven't checked - but is this just in the `test-run` element, @nvborisenko? From memory, I thought the individual tests already specify milliseconds.

If that is the case, the test-run element is actually built in the NUnit Engine.

**Comment by CharliePoole** [comment]
IIRC the test run element is different form any eat elements. It's purpose is to identify a run and the time down to one second seems fine for that purpose. Tests are another matter of course.

**Comment by nvborisenko** [comment]
Each xml node has like
```
start-time="2019-07-04 22:32:33Z" end-time="2019-07-04 22:32:33Z" duration="0.004720"
```

**Comment by ChrisMaddock** [comment]
So it does...who knew?!

I fully agree with improving this - sub-one-second unit tests are the norm. Question is, what might break downstream if we change it.

I suggest we switch to a more specific, standard format to hopefully minimise disruption to 3rd party tools. "o" seems sensible to me:

![image](https://user-images.githubusercontent.com/4837132/60773831-4ec4b980-a103-11e9-9696-bbb38af85cd4.png)


@nunit/framework-team - what do people think? 

This will also want a corresponding change in the engine repo, and probably NUnit Lite, for the `test-run` element.

**Comment by jnm2** [comment]
I like the `o` format specifier. [TFS had issues](https://developercommunity.visualstudio.com/content/problem/196633/tfs-2018-failed-to-publish-test-results-the-value.html) when we used to fill start-time and end-time with DateTime.MinValue on tests that didn't run. It may break folks downstream if they use anything other than `DateTime.Parse(..., CultureInfo.InvariantCulture)`, but it's only a guess. We don't promise any specific format in https://github.com/nunit/docs/wiki/Test-Result-XML-Format#test-case:

> - **start-time** The UTC time that the test started.

What we could do is commit to the `o` format going forward so that the docs page would say the proper parsing code would be `DateTime.ParseExact(attributeValue, "o", CultureInfo.InvariantCulture)`.

**Comment by jnm2** [comment]
Though really you'd want to use this code to be compatible with NUnit 3.12 and below:

```cs
DateTime.Parse(attributeValue, CultureInfo.InvariantCulture)
```
