### ISSUE TITLE
Add CF to the Appveyor CI build

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#332]
As indicated by #331 we keep breaking the compact framework build without realizing it. We need to at least compile it in our CI and if possible run the tests. Without installing a bunch of stuff in Appveyor, we'll probably only be able to run it using assembly unification under desktop .NET for now.

**Comment by dicko2** [comment]
@CharliePoole I'd like to here more about the "assembly unification" option. And would be keen to get some info on the manual steps @oznetmaster 

How I would tackle this problem I see two options.

### 1. Appveyor 

I don't have much experience with Appveyor, but it looks like you can install things as a part of the build process as you have admin rights on the box, so an option here would be to download/install the missing CF components. Current error below when i enable the CF build:
```
C:\projects\nunit\src\NUnitFramework\framework\nunit.framework-netcf-3.5.csproj(463,11): error MSB4019: The imported project "C:\windows\Microsoft.NET\Framework\v3.5\Microsoft.CompactFramework.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
An error occured when executing task 'BuildAllFrameworks'
```

This would slow down the builds drastically though, and if a restart is required after install might be hard, but not impossible.

Just noting also that I have had bad experience when installing old version of vs/.net framework when the latest ones are already installed.

### 2. TeamCity

TC I do have a bit of experience with. I could run up a TC instance on my developer account allowance (1 core, 3.5Gb RAM, hosted in Azure VM) to run the builds from with all the software needed. TC offer a free license to Open Source projects, you just have to renew yearly and host it yourself :)

This is how I normally do it within our company, is just to have a custom agent for the CF builds that's built to suite. But this would require accounts to be created to access the TC server for all nunit members, so might be a bit cumbersome over time, we can enable guess access on it though for the wider public.

Lastly this isnt an option now, but if VSTS fixes their issues with building branches that might be a better option to TC, as its cloud hosted so will perform better, but a separate agent on a VM would still be required (maybe able to get away with mirco instance though), their cloud hosted pool of agents build agents have less software than appveyor (https://msdn.microsoft.com/library/vs/alm/build/services/hosted-agent-pool#software), this is doable though because VSTS support "on-premise agents", or ones external to their pool.

**Comment by CharliePoole** [comment]
@dicko2 I took the liberty of assigning this to you. :-)

Appveyor would work best because it's what we already rely on.

The build script would have to build CF in a completely different way. It might have to use the MSBuild that comes with VS2008 - not sure of that. It would definitely have to use the compiler from either VS2008 or the CF 3.5 SDK. Best thing would be to try to get a batch build working that doesn't depend on any pre-installed software, but only on things you can download or that Appveyor already has.

If you look at the old NUnitLite project, you will see that I had a NAnt build script that did a CF build.

Assembly unification relates to running tests. Using unification you can execute an assembly built for CF under a desktop environment. Clearly it's not a complete test. We already have this ability, simply by running the test executable.

**Comment by dicko2** [comment]
Ok great, i'll have a crack at Appveyor.

**Comment by dicko2** [comment]
Just making a note on this, installing the msi for the CF build takes <5 seconds on the appveyor agent, and after installing a few of the CF builds actually passed out of the box.

With the small time for installing i think it should be fine to run the CF builds in the same appveyor CI build as the rest, i was initially worried about the install time this but it seems not an issue.

**Comment by CharliePoole** [comment]
I can't see the build. Are you running this from your own fork rather than a branch on nunit?

We pretty much have to run it as a part of the one build so long as it's the same GitHub project - Appveyor only gives us one build. :-(

At some future point the CF version of the framework may be split to its own repo, at which point we would want to break out the build.

**Comment by dicko2** [comment]
Yep, i setup appveyor on my fork. I was testing some appveyor work via committing, so didn't want to end up pushing 30 commits or so, that i ended up with after testing. So have done another branch to push the changes through in a couple of rolled up commits. I'll break the changes for the build sub folder into another branch, i should have known not do do two tasks on one branch, i just go all OCD when there is too many files in the root, its like when there's too many files on your desktop for me.

The limit with AppVeyor is 1 concurrent running build yea? you can have multiple build configurations?

Sorry first time using it, I'm too used to TeamCity and TeamBuild :)

**Comment by CharliePoole** [comment]
Wait for comments before reorganizing the root. I'll go through and see if
there's stuff to delete as well.

On Appveyor you could do multiple builds by looking at the branch name or
using a tag. It complicates things though. At the moment, one is all we
need.
