### ISSUE TITLE
Problems when using a mixture of Not and Or filters in NUnit framework 3.12.0

### ISSUE THREAD

**Issue by okknudsen** [nunit/nunit#3328]
In short, the NUnit 3 framework does not select the correct tests when using a filter like `!(test!='Some.Namespace'|...)`.

To give a minimal example, suppose that I have an assembly (referencing NUnit framework 3.12.0) with 1 test, called `Namespace.Fixture.Test`, without any attributes (and hence no categories). Running the tests with the filter `!(test!='Namespace.Fixture'|cat=='X')` will execute 0 tests. However, if it references NUnit framework version 2.6.4, it runs the test `Namespace.Fixture.Test`.

This is, of course, a very contrived example, and an easy workaround is to apply De Morgan and use the filter `test=='Namespace.Fixture'&cat!='X'`.

I believe that this relates to issue #3231.

I have tested this with version 3.10.0 of the console runner, installed with Chocolatey, as well as version 3.7.0 of the NUnit V2 Framework Driver, installed the same way. Moreover, I have added [FilterTest.zip](https://github.com/nunit/nunit/files/3427218/FilterTest.zip) with projects producing assemblies `NUnit2FilterTest.dll` and `NUnit3FilterTest.dll` containing the test mentioned above and referencing NUnit framework 2.6.4 and NUnit 3.12.0, respectively.  After building the projects, the problem can be reproduced with:
```
nunit3-console.exe NUnit2\bin\Debug\NUnit2FilterTest.dll --where "!(test!='Namespace.Fixture'|cat=='X')"
nunit3-console.exe NUnit3\bin\Debug\NUnit3FilterTest.dll --where "!(test!='Namespace.Fixture'|cat=='X')"
```

**Comment by CharliePoole** [comment]
This is only somewhat related to #3231, which dealt with two Not filters directly nested. The fix for that was to simply drop both of them. Here we have `<not <or <not <test>> <cat>>>>` so a more substantial fix is probably needed.

We really need a test that demonstrates this to be a framework problem. Running through the console opens up the possibility that either the console is generating an incorrect filter from the `--where` clause or the framework is misinterpreting the filter. For the V2 example, the V2 driver, which translates the NUnit 3 filter to a a V2 filter, also comes into play. Ideally, we want a framework test that creates the filters programmatically and applies them directly. We already have some tests like that, but not for this specific case.

**Comment by mikkelbu** [comment]
Also sounds related (or at least similar) to nunit/nunit-v2-framework-driver#21.

**Comment by okknudsen** [comment]
@CharliePoole If it helps, I have tried debugging what happens, and the filter that the NUnit framework reciewes is `<filter><not><or><not><test>Namespace.Fixture</test></not><cat>X</cat></or></not></filter>`.

I just tested, and it also happens with the filter `!(cat!='Y'|cat='X')` if the test is given the category `Y`.

Come to think of it, I think that it might actually be closely related to #3231. Indeed, as the `cat=='X'` should return `false` on both its `Pass` and `Match` methods for every test, the actual functionality of the `OrFilter` is simply to forwards its `Pass` and match `Match` methods to the inner `NotFilter`, which produces the same effect as if it was two `NotFilter`'s in a row.

I'm new to the NUnit source, so I might have misunderstood something, but to me it seems like the problem is that the `Pass` method on filters inheriting from `TestFilter` searches through parent tests _and_ child tests in order to check whether there is a match, whereas the `NotFilter` only searches upwards through parent tests (as it calls the `Match` method and not the `Pass` method of the base filter).

I tried writing a test for it. So, with the possibility that I have misunderstood how the tests work, I wrote the following three tests with inspiration from `DoubleNegativeFilterTests`:
```
public class NotOrNotFilterTests : TestFilterTests
{
    private readonly TestFilter _filter;

    public NotOrNotFilterTests()
    {
        _filter = new NotFilter(new OrFilter(new NotFilter(new CategoryFilter("Dummy")), new CategoryFilter("NoExistingCategory")));
    }

    [Test]
    public void PassToplevel()
    {
        Assert.That(_filter.Pass(_topLevelSuite));
    }

    [Test]
    public void PassFixture()
    {
        Assert.That(_filter.Pass(_fixtureWithMultipleTests));
    }

    [Test]
    public void MatchTest()
    {
        Assert.That(_filter.Match(_fixtureWithMultipleTests.Tests[1]));
    }
}
```
The first two, `PassToplevel` and `PassFixture`, fail but the last one, `MatchTest`, succeeds. This seems like a mistake to me, and if I understand how the NUnit framework goes through the tests, this means that it simply skips namespaces/fixtures which should not have been skipped.

**Comment by CharliePoole** [comment]
@okknudsen I think your tests confirm this as a framework bug. Would you be interested in taking it a step further and doing a PR?

I think the failure of the Not filter to search child tests is probably the cause of the problem. It doesn't do so, because finding a child test that matches the filter wouldn't help, since the not would reverse that finding. However, it should do __something__. Off the top of my head it seams that it should expliclicitly search for child tests that pass the filter __under__ the not.

**Comment by cyanite** [comment]
The problem seems to be that, like intuitionistic logic, "not" isn't the opposite of "", and that "not not not" is semantically equivalent to "not", but "not not" isn't to "".

The reason is that "not" has different search behaviors, i.e. it would stop as soon as its inner condition matches, while "" continues searching.

One possible solution might be to detect a situation where a De-Morgan or similar would lead to "not not" and then execute that transformation (and remove the resulting "not not"). But it obviously changes semantics and might [break someone's workflow.](https://xkcd.com/1172/)

**Comment by okknudsen** [comment]
@CharliePoole I wouldn't mind trying at least :)
