### ISSUE TITLE
Does.Contain assertion returns false negative when using IEqualityComparer

### ISSUE THREAD

**Issue by thatcosmonaut** [nunit/nunit#3333]
An assertion of the form
`Assert.That(collection, Does.Contain(element).Using(myEqualityComparer))`
fails. 

Strangely, using the same data an assertion of the form
`Assert.True(collection.Contains(element, myEqualityComparer))`
will pass.

Even more strangely, using the same data an assertion of the form
`Assert.That(collection, Is.EquivalentTo(expectedCollection).Using(myEqualityComparer))`
will also pass.

**Comment by CharliePoole** [comment]
What is the Type of `collection` in your example?

**Comment by mikkelbu** [comment]
@thatcosmonaut which version of NUnit are you using, since I cannot find a version where the first variant compiles.

Given
```csharp
[TestFixture]
public class Class1
{
    readonly IEqualityComparer<string> myEqualityComparer = StringComparer.InvariantCultureIgnoreCase;
    readonly List<string> collection = new List<string> { "AAA", "BBB", "CCC" };
    readonly string element = "bbb";
    readonly List<string> expectedCollection = new List<string> { "aaa", "bbb", "ccc" };

    [Test]
    public void Test1()
    {
        Assert.That(collection, Does.Contain(element).Using(myEqualityComparer));
    }

    [Test]
    public void Test2()
    {
        Assert.True(collection.Contains(element, myEqualityComparer));
    }

    [Test]
    public void Test3()
    {
        Assert.That(collection, Is.EquivalentTo(expectedCollection).Using(myEqualityComparer));
    }
}
```
gives me the following error `CS1061	'ContainsConstraint' does not contain a definition for 'Using' and no accessible extension method 'Using' accepting a first argument of type 'ContainsConstraint' could be found (are you missing a using directive or an assembly reference?)`.

Your second example is just testing the framework method `Enumerable.Contains<TSource>(this IEnumerable<TSource> source, TSource value, IEqualityComparer<TSource> comparer)`.

**Comment by mikkelbu** [comment]
Closed due to lack of activity. Please note that we will still see new comments on this issue, so if more information is added we can reopen the issue.
