### ISSUE TITLE
TestContext.CurrentContext is showing null 

### ISSUE THREAD

**Issue by Anshika121** [nunit/nunit#3351]
Below is my code which i am using to generate extent report but when i call this method i could see **NUnit.Framework.Testcontext.CurrentContextResult = null** so code is not going to if loop at all.
![Capture](https://user-images.githubusercontent.com/25966271/63390016-747bea00-c362-11e9-81d0-26019a5f526e.PNG)

  public void GetResult()
        {

            var status = TestContext.CurrentContext.Result.Outcome.Status;
            var stackTrace = "<pre>" + TestContext.CurrentContext.Result.StackTrace + "</pre>";
            var errorMessage = TestContext.CurrentContext.Result.Message;

            if (status == TestStatus.Failed)
            {

                test.Log(Status.Fail, status + errorMessage + "Test Failed");

            }
            else if (status == TestStatus.Passed)

            {
                test.Log(Status.Pass, status + errorMessage + "This Test is Passed");

            }
            extent.Flush();
        }

**Comment by CharliePoole** [comment]
You have not said where you are calling this method. Result will vary, depending on whether a test is active at the point of call.

Your watch window shows that Result is not null. Message and Stack trace are null. Your code does not contain any checks for null.

We need more information in order to help you with this.

**Comment by Anshika121** [comment]
I am calling it here 

        [TestMethod]
        public void FindAgent()
        {
            lp.Log_in();
            fa.FindAgentFormFillerByZipCodeFilter();
            fa.FindAgentFormFillerByGenderFilter();
            fa.FindAgentFormFillerByStatusFilter();
            fa.FindAgentFormFillerByAgent();
            fa.FindAgentFormFillerByAgency();
        }

        [ClassCleanup()]
        public static void GenerateTestReport()
        {
            ExtentManager ex = new ExtentManager();
            ex.GetResult();
        }

**Comment by CharliePoole** [comment]
There are two pretty big problems here...

1. You are not using NUnit to run tests. `TestMethod` and `ClassCleanup`are not NUnit attributes. I believe they are from VSTest. You are apparently also referencing the NUnit framework assembly (because you are able to reference `NUnit.Framework.TestContext`) but since NUnit is not actually running the tests, no proper context is ever set up.

2. Even if you were to switch to using NUnit, replacing `TestMethod` by `Test` and `ClassCleanup` by `OneTimeTearDown`, the context you would access in the one-time teardown would be that of the fixture (i.e. the class) not that of any individual test.

I'm closing this as basically not being an NUnit problem at all. If I have misunderstood something, you can continue to comment here and we will respond. If I've got it wrong, then we can reopen.
