### ISSUE TITLE
Can I use SetCultureAttribute with custom CultureInfo?

### ISSUE THREAD

**Issue by Denis535** [nunit/nunit#3358]
I have my custom `CultureInfo`. Can I feed it to `SetCultureAttribute`? 

    var culture = new CultureInfo( CultureInfo.InvariantCulture.Name );
    culture.DateTimeFormat.LongTimePattern = "HH:mm:ss:fff";
    ...
    [SetCultureAttribute( "my custom culture" )]

Or I can only use predefined list of cultures?

**Comment by mikkelbu** [comment]
@Deni35 Since arguments to attributes needs to be compile-time constants this makes it difficult to use attributes in this way. So you can only use the cultures that are valid to pass to the constructor of `CultureInfo`, https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.-ctor?view=netframework-4.8#System_Globalization_CultureInfo__ctor_System_String_.

I think that the easiest approach would be to create your own attribute (inspired from https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Attributes/SetCultureAttribute.cs) where you define the custom cultureInfo.

One could also imagine that the argument to the attribute specified the name of a method that returned an instance of CultureInfo.

**Comment by Deni35** [comment]
Can I set culture to `TestExecutionContext.CurrentContext.CurrentCulture`?
I tried to do it in `OneTimeSetUp` but it didn't work.

**Comment by Deni35** [comment]
@mikkelbu Is it possible to set up culture in `OneTimeSetUp` method?

**Comment by mikkelbu** [comment]
As far as I can see it is possible, but note that we are using an internal namespace, `NUnit.Framework.Internal`, so it is possible that the code in this namespace will change at some time.
![image](https://user-images.githubusercontent.com/1007631/63981618-1ff21080-cac0-11e9-846f-a8986c82ff99.png)
I'm unsure if there is an alternative approach besides what I've mentioned above.

**Comment by Deni35** [comment]
Try it. Async OneTimeSetUp doesn't work. Is it bug?

    [OneTimeSetUp]
    public async Task OneTimeSetUp() {
        var culture = new CultureInfo( CultureInfo.InvariantCulture.Name );
        culture.DateTimeFormat.LongTimePattern = "HH:mm:ss:fff";
        TestExecutionContext.CurrentContext.CurrentCulture = culture;

        await Task.Delay( 1 );
    }

**Comment by CharliePoole** [comment]
That makes sense. The culture is set in the thread that is running.

**Comment by Deni35** [comment]
I can't understand why this doesn't work.
It doesn't work even without any `await`. Just `async` method.

    [OneTimeSetUp]
    public async Task OneTimeSetUp2() {
        var culture = new CultureInfo( CultureInfo.InvariantCulture.Name );
        culture.DateTimeFormat.LongTimePattern = "HH:mm:ss:fff";
        TestExecutionContext.CurrentContext.CurrentCulture = culture;
    }

**Comment by CharliePoole** [comment]
Because NUnit does the equivalent of await when calling your test. Making it async essentially tells NUnit that it has to wait for the method to finish rather than merely calling it.

Your example method doesn't need to be async anyway. If you have other one-time initialization that requires async, then the workaround would be to have two OneTimeSetUp methods. Note however that the order they are called is not guaranteed. If you need ordering, we can give you a slightly more complex approach.

**Comment by Deni35** [comment]
I don't need ordering. But I wonder what is more complex approach?
Does OrderAttribute work for SetUp methods?

**Comment by CharliePoole** [comment]
For ordering, you would need to use either a SetUpFixture or an extra level of inheritance. If you don't need it, I wouldn't bother.

OrderAttribute applies to test cases, not to individual pieces of a test like SetUp.

**Comment by Deni35** [comment]
Okay, thank you. Looks like I need to understand how `Thread.CurrentThread.CurrentCulture` and `async` methods works.
P.S. I think you should make OrderAttribute work with SetUp methods.

**Comment by mikkelbu** [comment]
Closing this issue as answered. Note that we will still see comments on this issue and can reopen it if it is not the case.
