### ISSUE TITLE
Is there no way to make tests run in parallel when using a library without assemblyinfo.cs?

### ISSUE THREAD

**Issue by Mech0z** [nunit/nunit#3373]
I have started migrating projects to the new .csproj SDK style and these new projects do not contain the AssemblyInfo.cs

Is there still no way to specify that all tests in that project should be run in parallel?

**Comment by agray** [comment]
@CharliePoole  Does `ParallelScope.Fixtures` mean that tests within a single Fixture will run in parallel?

**Comment by Mech0z** [comment]
> 
> 
> @CharliePoole Does `ParallelScope.Fixtures` mean that tests within a single Fixture will run in parallel?

I have created this file 
`using NUnit.Framework;

[assembly: Parallelizable(ParallelScope.Fixtures)]
[assembly: LevelOfParallelism(8)]

namespace SharedUnittests
{
    class UnittestSetup
    {
    }
}

and then on single tests inside that project that I do not want run in parallel I put this
```
    [TestFixture]
    [Parallelizable(ParallelScope.None)]
    public class SomeTestClass
```

**Comment by CharliePoole** [comment]
@agray No. Used at the assembly level it means that all fixtures default to running in parallel with other fixtures. The tests within each fixture would run sequentially.

IMO, we should have forbidden use of `ParallelScope.Fixtures` anyplace __except__ on the assembly level. However, by the time the potential ambiguities became clear, it was already in use in lots of codebases. I suggest avoiding it except at the assembly level, as a default setting.

I should also add that I'm not a big fan of default parallelism anyway. In most teams, it leads to errors because the devs must all be aware that the default places added burdens on the tests they write.

**Comment by vyakaa** [comment]
@CharliePoole is there a way to exclude some classes or features (SpecFlow) for parallel scope on assembly info level?

**Comment by CharliePoole** [comment]
@vyakaa Sorry, but no. NUnit leans toward attributes __on__ the elements they refer to and only has a few (like `TestCaseSource`) that refer to other elements. This is error-prone because it usually involves a non-type-safe string.

As I answered elsewhere, the best answer is for the program that generates your test code (like SpecFlow) to provide some escape mechanism that lets you provide attributes. If you can't get it from the tool you are using, you might consider switching tools.

**Comment by vyakaa** [comment]
Please see how I solved this issue by this [LINK](https://github.com/nunit/nunit/issues/3440#issuecomment-567101013)
