### ISSUE TITLE
Driver is not available in TestFixtureTearDown after exception in Test

### ISSUE THREAD

**Issue by munjalanju** [nunit/nunit#3374]
I have executed a test method and the methods executed in the order -
OneTimeSetUp
SetUp
Test Method
TearDown
OneTimeTearDown

But during the execution, If an exception occured in my test method which redirected the excecution-control to TearDown immediately. Here, TearDown (contains code to write message in report, take screenshot etc) executed successfully. but when OneTimeTearDown (contains code to quit the driver) start executing, it didn't find the driver object.
Note - webdriver instance (instantiated in OneTimeSetUp) is available throughout the execution. But when an exeception occurs, OneTimeTearDown don't get that driver object.

**Comment by CharliePoole** [comment]
Please provide some code. Also, what do you mean by "is not available?" Is their an instance variable that holds the driver? Is it null? Or does some error occur when you call it?

**Comment by munjalanju** [comment]
I am using ThreadLocal for parallel execution. So, an instance of ThreadLocal is holding the instance of WebDriver. Whenever I need WebDriver instance, I retrieve that from ThreadLocal instance. This is working properly throughout the execution. But when the control comes to OneTimeTearDown and I am retrieving WebDriver instance from the ThreadLocal instance, it is throwing an exception i.e., object reference not set to an instance

**Comment by CharliePoole** [comment]
If you design a TestFixture in such a way that all test cases plus one-time SetUp and TearDown must run on the same thread, then NUnit has to be told to do it that way. Otherwise, NUnit may run some things on one thread and some things on another, because it is designed on the assumption that tests are completely independent from one another.

The attribute on your TestFixture class that tells NUnit to run everything on the same thread is `SingleThreadedAttribute`. See https://github.com/nunit/docs/wiki/SingleThreaded-Attribute.

Of course, if you use this, your test cases obviously cannot run in parallel, but the fixture as a whole can still run in parallel with other fixtures.

**Comment by mikkelbu** [comment]
I'm closing this issue as answered, please note that we will still see additional comments on this issue, so if new information appear, then we can reopen the issue.
