### ISSUE TITLE
Assert.AreNotEqual for ValueTuple

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#3394]
Perhaps I am confused as to what Equal/NotEqual should mean for a ValueTuple.

I have always thought that ValueTuple comparer would first compare the types of the to ValueTuples, and then their contents.

Currently, it appears that the comparer only confirms that they are both ValueTuples, and then compare their contents.

This means that a `ValueTuple<int>` and a `ValueTuple<short>` which both contain the value 1 currently are equal.

I would have assumed that since the two value tuples are different types, they would never be equal.

Am I confused, or is the current implementation incorrect?

**Comment by mikkelbu** [comment]
Hi @oznetmaster 

Are you talking about _named_ value tuples? Because I think it makes sense for unnamed value tuples. For named value tuples the name is only available as an attribute, but this is not CLS-compliant, and I'm unsure if we can read the information from tests/equality checks, see e.g. `TupleElementNames` in http://mustoverride.com/tuples_names/ for more information.

The Microsoft documentation contains the following about equality of valuetuples
https://docs.microsoft.com/en-us/dotnet/csharp/tuples#equality-and-tuples
> The names of the tuple members do not participate in tests for equality. However, if one of the operands is a tuple literal with explicit names, the compiler generates warning CS8383 if those names do not match the names of the other operand. In the case where both operands are tuple literals, the warning is on the right operand as shown in the following example:
```csharp
(int a, string b) pair = (1, "Hello");
(int z, string y) another = (1, "Hello");
Console.WriteLine(pair == another); // true. Member names don't participate.
Console.WriteLine(pair == (z: 1, y: "Hello")); // warning: literal contains different member names
```

**Comment by oznetmaster** [comment]
No.  Just plain value tuples.

I was given a unit test suite which had many tests of the form:

```
var vt1 = new ValueTuple<short>  (100);
var vt2 = new ValutTuple<int> (100);

Assert.AreNotEqual (vt1, vt2);  // this fails because of the problem I described.
```

**Comment by mikkelbu** [comment]
I was confused by the following sentence, but I thought that it was some missing words (and did not consider that GitHub removes tags). I've now edited your message
> This means that a ValueTuple and a ValueTuple which both contain the value 1 currently are equal.

Regarding the issue, then I think it is standard behaviour in our comparers (that we use the comparer recursively for common generic types). So since we treat 100 as a short as equal to 100 as an int, then we also treat the list that contains a single 100 as short as equal to a list that contains a single 100 as an int - see `Test2` below.

All the following tests fail - as expected -on my machine
```csharp
        [Test]
        public void Test1()
        {
            var vt1 = new ValueTuple<short>(100);
            var vt2 = new ValueTuple<int>(100);

            Assert.AreNotEqual(vt1, vt2);
        }

        [Test]
        public void Test2()
        {
            var vt1 = new List<short> { 100 };
            var vt2 = new List<int> { 100 };

            Assert.AreNotEqual(vt1, vt2);
        }

        [Test]
        public void Test3()
        {
            short vt1 = 100;
            int vt2 = 100;

            Assert.AreNotEqual(vt1, vt2);
        }

        [Test]
        public void Test4()
        {
            var vt1 = new KeyValuePair<string, int>("string", 100);
            var vt2 = new KeyValuePair<string, short>("string", 100); ;

            Assert.AreNotEqual(vt1, vt2);
        }
```

**Comment by mikkelbu** [comment]
But `KeyValuePair` above in `Test4` is not a collection or list either, and we also use the comparer recursively on this class. 

I'm a bit unsure about the source of the text in the code block, but I don't consider ValueTuple more strongly typed than e.g. a generic List.

**Comment by jnm2** [comment]
@oznetmaster I think it makes sense to do elementwise comparisons with tuples just like with enumerables. A lot of types are special-cased with NUnit equality. Tuples are even more important than lists because the standard syntax is e.g.:

```cs
(short, object) foo = ...;
Assert.That(foo, Is.EqualTo((1, "hi")));
```

A leading principle behind C# tuples is that operations on the tuple distribute to the individual elements, so the behavior of the previous code sample should match the behavior here:

```cs
short foo;
Assert.That(foo, Is.EqualTo(1));
```

```cs
object foo;
Assert.That(foo, Is.EqualTo("hi"));
```

**Comment by mikkelbu** [comment]
Closing this, as the behaviour matches how we handle equality for other generic types (by using the NUnit equality recursively on nested data). Please note that we will still see additional comments on this issue.
