### ISSUE TITLE
Tests are not canceled using NUnitLite Runner and launched from nunit3-console

### ISSUE THREAD

**Issue by mizumen** [nunit/nunit#3412]
I run Nunit tests via nunit3-console runner when I call CTRL+C on PS console Nunit doesn't stop tests execution but just continues until all tests are finished
Looks like the problem is connected to NUnitLite Runner, after I removed it tests are being stopped after CTRL+C command in console mode.

**Comment by mikkelbu** [comment]
@mizumen You will have to be more precise for us to help you. I can cancel the console using CTRL+C when I run it from Powershell. How exactly are you executing the console (I'm guessing PS is shorthand for Powershell, but I'm not sure), which version of the console are you using, which tests are you running etc. The more information the better we can help.

Note that the nunitlite-runner is not part of the console, but part of the NUnit framework, so there should not be any connection between these except that they both can execute the tests.

**Comment by mizumen** [comment]
@mikkelbu the cause was in external process which is launched in my tests and cannot be stopped by nunit. Not connected to topic, but I need to find a way to pass something like a cancellationtoken into tests during execution, to stop this external process so the tests could be cancelled, not sure if it is possible though.

I really apologize for this post and inconvenience made for you guys.

**Comment by CharliePoole** [comment]
Although you have closed the issue, let me add this bit of advice. NUnitLite and nunit3-console are both runners. You should normally not be using __both__ of them at the same time! If you want to run tests through nunitlite some of the time and through nunit3-console at other times, that's fine.

**Comment by mizumen** [comment]
Thank you for advice @CharliePoole
I start tests the following way from CMD or PowerShell console:
_nunit3-console TestConsoleApp.exe --test=TestsCategory_
assume this is the nunit3-console way.

**Comment by CharliePoole** [comment]
That's correct... In that case, you are not actually using nunitlite runner. That is, the `exe` has a `Main()` which __would__ invoke__ nunitlite, but it is not called by `nunit3-console`. OTOH, if you run the `exe` itself rather than `nunit3-console`, then you are using nunitlite.

Any difference in cancellation behavior relates to the fact that `nunit3-console`, by default, runs your tests in a separate process. `NUnit3-console` does not have any built-in way to cancel itself, so it's obviously being done externally. If you were to kill the initial process manually, you would have to specify that child processes also be killed. If it's being done programmatically, the same is true.

**Comment by CharliePoole** [comment]
@mikkelbu Seems like we should have a test somewhere of running an nunitlite executable test assembly under the console runner, no?
