### ISSUE TITLE
EnumValuesExcept attribute

### ISSUE THREAD

**Issue by seanblue** [nunit/nunit#3431]
Right now we have the `Values` attribute, which allows us to specify all `bool`, `bool?`, `enum`, and `enum?` values, or specific values of those or other types. I have often found it useful to instead *start* with all enum values, and then exclude those that are not relevant to a given test. In cases where an enum value is the exception by being excluded from production behavior, it is sometimes preferable to have a test run for all values except that one, so that newly added enum values will automatically be covered by the test.

Given the subtractive approach, only `enum` and `enum?` types makes sense for this. `bool` and `bool?` already have a guaranteed fixed number of options, so `Values` is sufficient, and starting from the infinite set available for other types like `int` or `string` doesn't make sense. I have already implemented such an attribute and used it for several months for tests in a production system. If there is interest, I'd like to add this to NUnit directly.

---
Example:
```c#
public enum MyEnum
{
    A,
    B,
    C,
    D,
    E
}

[Test]
public void TestEnum([EnumValuesExcept(MyEnum.A, MyEnum.C)] MyEnum val)
{
    // Results in test cases for B, D, and E.
}

[Test]
public void TestNullableEnum([EnumValuesExcept(MyEnum.A, MyEnum.C)] MyEnum? val)
{
    // Results in test cases for B, D, E, and null.
}
```

**Comment by mikkelbu** [comment]
Hi @seanblue 

Thanks for starting this discussion. I can see the value in an attribute like this, but personally, I would prefer it be part of a extension/helper library rather than part of NUnit. An alternative to `EnumValuesExcept` could be to use `Assume.That` to filter the unwanted values (although VS and the console will show these as Inconclusive).

```csharp
[Theory]
public void TestEnum(MyEnum val)
{
    Assume.That(val, Is.Not.EqualTo(MyEnum.A).And.Not.EqualTo(MyEnum.C));
    // Results in test cases for B, D, and E.
}
```

**Comment by seanblue** [comment]
Hi @mikkelbu. One problem with that approach (besides inconclusive tests appearing in the test runner) is if the test `SetUp` is expensive. In that case extra work would be done for no reason.

**Comment by stevenaw** [comment]
Hi @seanblue 
Very interesting idea. As far as current framework attributes, could using the `ValueSource` attribute also meet this need?

I've linked some documentation below
https://github.com/nunit/docs/wiki/ValueSource-Attribute

**Comment by seanblue** [comment]
Hi @stevenaw. I personally prefer the succinctness of things like `Values` and `TestCase` over `ValueSource` and `TestCaseSource` when possible. But there's no reason `ValueSource` couldn't be used to achieve the same thing as my proposal.

**Comment by CharliePoole** [comment]
@mikkelbu I'd personally tend to use `Assume` as you suggest but I don't think I'd use `[Theory]` because it tends to confuse the issue. I think `[Theory]` is best reserved for its purpose of __testing a theory__ rather than being used for it's implementation details. And anyway, the same code is supposed to work with [Test] as well, since `Assume` is not limited to theories.

That said I'd say this is very easy to create as a custom attribute already.

**Comment by siprbaum** [comment]
I would have used such an attribute if it exists in nunit, becsuse we often have the use case to test all enum values besides a few ones.
Currently we mostly use TestCaseSource but it seems to be a bit overkill from what we want from an implementation standpoint.

**Comment by CharliePoole** [comment]
This currently gives all values...

```c#
[Test]
public void TestEnum([Values]MyEnum val)
{
}
```

If we __wanted__ to support this, rather than a new attribute, I think I'd prefer

```c#
[Test]
public void TestEnum([Values(Exclude=MyEnum.A, MyEnum.C)]MyEnum val)
```

In the end, however, I'd generally want to just list the values we __want__ to use because that makes the test easier to read. Of course, that's already supported.

**Comment by siprbaum** [comment]
Commenting your statement:

> In the end, however, I'd generally want to just list the values we **want** to use because that makes the test easier to read. Of course, that's already supported.

I think this depends heavily on the test goal.
Often there are some special enum values, e.g. like
an `Undefined` for the first value in the enum to ensure when you don't initalize a variable of
the enums type it gets automatically set to `Undefined`
```csharp
enum SomeEnum {
   Undefined = 0,
   A,
   B,
   C
}

SomeEnum foo; /* This will initialized to Undefined by the compiler */
```

So from a test design standpoint I want to express that all enum values except the `Undefined` one need to be treated the same, even when adding new values to the enum.

If I follow your suggestion and list every enum value in a `TestCase(...)` above the test, this test design goal is  no longer expressed by simply reading test test. A reader of the test needs to
figure out that **all enum values** (besides the special ones) are listed and it is also error prone when
adding a new enum value, because one might *forget* to add the new `TestCase(...)` with the new enum value.

So often I find myself writing it like this
```csharp
static IEnumerable<SomeEnum> AllEnumsExceptUndefined() {
   return Enum.GetValues(typeof(SomeEnum))
              .Cast<SomeEnum>()
              .Except(new SomeEnum[] { SomeEnum.Undefined });
}

[TestCaseSource(nameof(AllEnumsExceptUndefined))]
void TestSomeEnum(SomeEnum value) {
   ...
}
```
which is IMHO just a little too much boiler plate code for my taste.

Concerning the actual syntax for the feature, I don't have a clear preferation.

**Comment by CharliePoole** [comment]
Point taken! I would say that the `Assume` approach can give equal visibility, if used in each test. If the Assume is buried in a SetUp method, then that's not helpful... it needs to be the first line of each test. However, it's a more wordy, procedural approach and the declarative approach of a properly designed attribute constructor would probably be better.

It could be that the use of `[Values]` to represent all the values of an enum is less clear than it should be. Perhaps we should have defined an `AllValuesAttribute, derived from `ValuesAttribute`.
It would have taken no arguments, while Values would require one.

This could still be done - except for requiring an attribute for Values - and we could enhance `AllValues` with an `Except` property.

**Comment by seanblue** [comment]
@CharliePoole If you try to exclude the enum values with a property instead of the constructor, is it even possible to use the syntax you showed?
```c#
[Values(Exclude=MyEnum.A, MyEnum.C)]
```

In the case of the `Values` attribute, this is achieved with a `params` array in the constructor, so I don't see how that would still work for assigning to the property. My concern is that with the property approach, it would be too verbose.
```c#
[Values(Exclude=new[] { MyEnum.A, MyEnum.C })]
```

It's not terrible, but certainly doesn't look as nice as
```c#
[Values(MyEnum.A, MyEnum.C)]
```

Please let me know if I'm mistaken.

**Comment by CharliePoole** [comment]
Yes, that's a good point... we're constricted by the limitations of attribute construction syntax. :disappointed:

**Comment by SinsteinM** [comment]
Although this issue seems to be somewhat inactive, I thought it might be helpful for others seeking the described functionality to share my approach. Following up on the proposal of @mikkelbu, I ended up writing the following custom parameter attribute
```
[AttributeUsage(AttributeTargets.Parameter)]
public class AllEnumValuesExceptAttribute : NUnitAttribute, IParameterDataSource
{
    private readonly object[] exceptValues;

    public AllEnumValuesExceptAttribute(object exceptValue)
    {
        exceptValues = new[] {exceptValue};
    }

    public AllEnumValuesExceptAttribute(params object[] exceptValues)
    {
        this.exceptValues = exceptValues;
    }

    public IEnumerable GetData(IParameterInfo parameter)
    {
        return new ValuesAttribute()
            .GetData(parameter)
            .Cast<object>()
            .Except(exceptValues);
    }
```
Example usage:
`[AllEnumValuesExcept(MyEnum.A, MyEnum.C)] MyEnum val`

**Comment by rprouse** [comment]
This issue is marked as an idea/design/discussion but hasn't had contributions in years so I am closing. Thanks for your code @SinsteinM, hopefully people that want the functionality will find it and use it.

**Comment by nthornton2010** [comment]
@rprouse I'm not sure where "years" comes from in your closing remark. You closed this April 2021 and the last comment was in Nov 2020, only 5 months prior... hardly years. There may have been even more comments if this wasn't closed.
