### ISSUE TITLE
Legacy NUnit: Different Keys used for signing <= 2.6.4 and >= 2.6.6

### ISSUE THREAD

**Issue by deenairn** [nunit/nunit#3448]
It appears that packages <= 2.6.4 have been signed with a public key token "96d09a1eb7f44a77" and versions >= 2.6.6 have been signed with public key "2638cd05610744eb".

This causes issues where using a signed binary and trying to use an assembly binding redirect, as assembly binding redirects will only work when the assembly has the same public key token. Unfortunately I've got this issue with some assemblies at work where I don't own another library that references NUnit 2.5.9 but would like to upgrade our local project assemblies to 2.7.1 in order to facilitate a future move to NUnit 3+.

I wonder if this was an oversight? I can see why a new public key token was used for NUnit 3.0 assemblies, but those on the legacy line should have the original public key token?

**Comment by mikkelbu** [comment]
Hi @deenairn I cannot answer your question, but this issue should probably be raised in https://github.com/nunit-legacy/nunitv2 which is for NUnit V2.

**Comment by deenairn** [comment]
It definitely should be. I wasn't aware of the other project.

**Comment by CharliePoole** [comment]
Because I publish NUnit V2 Legacy (versions after 2.6.4) independent of the NUnit Project, they use a different public key token. Another reason is that the legacy releases are built with newer tools, requiring generation of a new key.

For convenience, both projects are using the same nuget id.

Congrats on being the first person to notice! :smiley:
