### ISSUE TITLE
Assert.AreEqual overloads for nullable double are not useful

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit#3449]
We've had these four methods as far back as NUnit source history goes. The `double?` overloads are the same as the first two overloads except that they throw InvalidOperationException if you pass `null`. Since they can't be used to pass `null`, they don't do anything that the safer `double` overloads don't do.

Should we obsolete them or fix them? What would fixing them look like?

```cs
namespace NUnit.Framework
{
    public abstract class Assert
    {
        public static void AreEqual(double expected, double actual, double delta, string message, params object[] args);
        
        public static void AreEqual(double expected, double actual, double delta);
        
        public static void AreEqual(double expected, double? actual, double delta, string message, params object[] args);
        
        public static void AreEqual(double expected, double? actual, double delta);
    }
}
```

**Comment by CharliePoole** [comment]
The double? overloads were added in April 2008, and released with NUnit 2.5.1. See https://github.com/nunit-legacy/nunitv2/commit/c50f287d2d9c5044b92e30ef13e0fbedaa6009c0#diff-b2261783c755ae0aa95cb67fd6162517R1019

I agree they don't make sense.

**Comment by stevenaw** [comment]
I agree that if you intend to compare two `double`/`double?` values based on a delta, you expect both `expected` and `actual` to be non-null, and that obsoleting the `double?` overload makes the most sense. 

Though the `double?` for me strikes less as a "doesn't make sense" method and more a convenience method, in case a user's data (or class properties) are of type `double?`. I'm guessing that's why only the `actual` parameter is a `double?`. Though if we take this approach, we still don't need both, and might as well remove the non-nullable overload (since `double` is implicitly converted to `double?`). Though that wouldn't seem terribly clear to me as a user (or future maintainer) to have the `expected` and `actual` params be different data types.

I guess I'm thinking that while it could be disruptive to some users to eventually remove the `double?` overload, the simplicity it gives to the API (as well as the consistency with other floating-point equality assert APIs) would be worth it.

**Comment by jnm2** [comment]
I'm also thinking that because the overloads we would remove don't behave as you would expect when passed `null`, if they are used it is probably by accident.

**Comment by stevenaw** [comment]
Would it make sense to obsolete these now, and remove them in NUnit 4?

**Comment by jnm2** [comment]
Sounds good to me. @rprouse?

**Comment by jnm2** [comment]
Obsoleting sounds good to me. /cc @nunit/framework-team

**Comment by rprouse** [comment]
Sounds good to me.

**Comment by Antash** [comment]
@stevenaw, @rprouse, I want to fix this in case this is not in progress yet.

**Comment by rprouse** [comment]
Sure, but how do you propose to fix? We'd decided to obsolete the method, but we could remove in 4.0.

**Comment by jnm2** [comment]
Would it be best to do both?

**Comment by rprouse** [comment]
I would agree with @jnm2. We should remove from the master branch (4.0) and obsolete it in the v3.13 branch.

Do you want to do one or both of these @Antash?

**Comment by Antash** [comment]
@rprouse Will do, no problem!

**Comment by mikkelbu** [comment]
Thanks. I've assigned the issue to you @Antash

**Comment by 2r2d** [comment]
This feature makes this code
```
Assert.AreEqual(1, myObject?.X);
```
1 line longer to this:
```
Assert.NotNull(myObject);
Assert.AreEqual(1, myObject.Value.X);
```

**Comment by jnm2** [comment]
@2r2d `Assert.AreEqual(1, myObject?.X);` was already exactly equivalent in behavior to `Assert.AreEqual(1, myObject.Value.X);` *without* the NotNull assert, which is why we got rid of it. It appeared to do one thing but actually did something different.
