### ISSUE TITLE
Visibility of SetUp/TearDown Methods

### ISSUE THREAD

**Issue by KinNeko-De** [nunit/nunit#3453]
Hello,
i created non-public SetUp and TearDown methods.
That makes the test fail.
The error message is :
**"OneTimeSetUp: SetUp and TearDown methods must be public or internal: SetUp"**

But internal does not work.
Public works perfect.

Is only the error message wrong or should it work with internal methods?

Versions:
NUnit 3.12.0
NUnit3TestAdapter 3.15.1
Test run out of Visual Studio with the NUnit3TestAdapter.

Repro:
```
        public class SetupFixture1
	{
		[OneTimeSetUp]
		public void OneTimeSetUp()
		{          
		}

		[OneTimeTearDown]
		public void OneTimeTearDown()
		{
		}

		[SetUp]
		internal void SetUp()
		{       
		}

		[TearDown]
		internal void TearDown()
		{
		}

		[Test]
		public void Test()
		{
			Console.WriteLine("Test");
			Assert.Pass();
		}
	}
```

**Comment by ChrisMaddock** [comment]
I think this is a simple bug here, looks like the below check should be checking `IsAssembly` rather than `IsFamily`.

https://github.com/nunit/nunit/blob/1eb24591cdc9835b91d2258b979cef9e9d4bc829/src/NUnitFramework/framework/Internal/Tests/TestSuite.cs#L311

Out of interest, does `protected` currently work? Maybe we should also maintain that, for backwards compatibility.

We'd appreciate a pull request to fix this, if you'd be willing? It would be great to add a couple of unit tests around this, to prevent regression in the future.

**Comment by CharliePoole** [comment]
I think it's the message that's wrong. It was introduced in https://github.com/nunit/nunit/commit/8df37f2024108b8d53d5dbbd7a8d3e518ad2e54a#diff-2db1dd498edafd51b9c83f1e99f5e0d5 without any change to the logic itself. I believe public and protected are all we ever supported.

**Comment by KinNeko-De** [comment]
I am fine with public methods. you did a great job with nunit.
I changed the message to from "public or internal" to "public or protected" and created a pull request.
Thx for your help.
