### ISSUE TITLE
Assert.NotNull should have a ValidatedNotNullAttribute on the anObject parameter

### ISSUE THREAD

**Issue by Corniel** [nunit/nunit#3473]
Take the following example:

``` C#
public static void MySmartAssert(MyComplexModel model)
{
    Assert.NotNull(model, nameof(model));
   if (model.WhatEver)
   {
       Assert.Fail("What ever!");
   }
}
```

Static code analyzers like Sonar will generate a warning on the `model.WhatEver` call, arguing that model could be `null`. Since the early days of FxCop the `[ValidatedNotNullAttribute]` was introduced to help with the analysis, saying: if a parameter was decorated with that, it could be safely assumed that no null reference exception could occur on later references to it.

It would be nice if `Assert.IsNotNull`  and `Assert.NotNull` would have such an attribute on the `object AnObject` parameter.

**Comment by CharliePoole** [comment]
I understand the perceived need, but this seems like a bit of a slippery slope, in several ways...

1. Many nunit assertions and constraints could take a null argument. As a test framework, nunit looks for such stuff and doesn't normally throw an NRE when it gets one. Rather, it fails a test. As an example, what about `Assert.That(model, Is.Not.Null)`? Does it pass the analyzer? I'm afraid we would have to add the attribute to lots of methods.

2. Assuming we added it wherever needed, which analyzers will it satisfy. Are there analyzers that want something else? Do we need to support them as well?

3. As a specific example, if I understand the issue correctly, this approach apparently won't work for Roslyn-based analyzers. See https://github.com/dotnet/roslyn-analyzers/issues/2215

I guess I'm saying that NUnit needs to figure out how much of a burden this could eventually become before taking the first step toward supporting it.

Meanwhile, can't you define the attribute in your own test code and use it where you need it?

**Comment by jnm2** [comment]
There's another problem that means it's not obviously the right annotation. If the parameter is null and you are inside a multiple-assert block, the method will return and execution will continue.

**Comment by Corniel** [comment]
@CharliePoole : Let met start with point 3: (Sonar Analyzer)[https://github.com/SonarSource/sonar-dotnet] is one of the bigger Roslyn analyzers out there. The adopted this because the classic FxCop (built by Microsoft) introduced this. I'm therefor under the impression that a common/advised way doing so. So from that perspective I don't think it is a slippery slope.

Obviously, the should only be set on method parameters that indeed will always throw on null values. So, as @jnm2 pointed out, if that is not the case it should not be done. Although I guess, that such a multiple assert block is beyond what (Roslyn) analyzers a capable of. 

I like the discussion on this, and understand that this Issue (and the attached pull request #3474 ) are not a walk in the park and should be considered wisely. Also for me, it hard to just which burden it will turn out to be.

Obviously this is not blocking my local development. I think it could be a nice improvement of NUnit.

**Comment by jnm2** [comment]
On the question of whether we should indicate to static analyzers that Assert.NotNull always throws for `null`, even though it never throws inside a multiple assert block, I think we will need input from @nunit/framework-team.

My own comfort zone and the view taken by the .NET Core team as they continue to annotate .NET Core is that we should only add annotations that are strictly true no matter how rare of a  circumstance you are in. Their view and the C# designers' view is that by design there are always going to be a healthy amount of suppressions with `!` where the compiler doesn't have a guarantee. The presence of `!` doesn't mean there's a compiler or API deficiency; it means a programmer vouched for the part that the compiler couldn't.

But I'm also not entirely sure that it would be a bad thing for us to take a different position with our APIs. Maybe it's a caveat we could document that goes with the use of Assert.Multiple. Maybe our analyzer could help fill the gap. In any case, nullability warnings don't tend to be as helpful in test code as in product code. An NRE in test code is almost as good as an assert.

**Comment by rprouse** [comment]
>  we should only add annotations that are strictly true no matter how rare of a circumstance you are in.

Personally, that is how I feel. The team has also stated that new development is going into the constraint-based asserts in the `Assert.That` syntax. Those are where we should be handling this, bu we can't. Adding this to the classic asserts breaks our stance of not enhancing the classic asserts.

I vote to close this and the related PR unless any other @nunit/framework-and-engine-team member has a strong opinion on this, but it sounds like we are close to consensus.

**Comment by Corniel** [comment]
Well, I can live with that. I thought it could be nice improvement, but was not aware of the multi assert.
