### ISSUE TITLE
Data-driven tests using data created in the [SetUp] method

### ISSUE THREAD

**Issue by cvetomir-todorov** [nunit/nunit#3477]
I have data generated in my setup method:
```C#
[SetUp]
public void SetUp()
{
    // populating the db context here
    dbContext.SaveChanges();
    int entityId = someEntity.Id;
}
```

I need to use the `entityId` in my data-driven test. Sometimes there would be more than one ID generated, so I cannot access this from a private field, and sometimes I would need a dummy value (e.g. 0, -1 etc.).

```C#
[Test]
public void GetEntityTest(int entityId, HttpStatusCode expectedResult)
{
    // use the entityId here
}
```

I tried using the `[TestCaseSource]` attribute but that requires static property/method. I could only make this work if I use some delegates like this:

```C#
private static int existingEntityId; // this is now being set in the SetUp

public static object[] GetEntityTestData =
{
    new object[] { (Func<int>)(() => existingEntityId), HttpStatusCode.OK },
    new object[] { (Func<int>)(() => -1), HttpStatusCode.NotFound }
}

[TestCaseSource(nameof(GetEntityTestData))]
public void GetEntityTest(Func<int> getEntityId, HttpStatusCode expectedResult)
{
    int entityId = getEntityId();
    // use the entityId here
}
```

How can I achieve this without using delegates (which result in less readable code)?

**Comment by CharliePoole** [comment]
To make NUnit work for - rather than against you - it's necessary to understand how NUnit wants to work. Generation of test arguments takes place before the test is executed. `SetUp` OTOH is part of that execution - part of the test itself. Trying to provide the data for the test from setup will be awkward at best. At worst, it's impossible unless you duplicate a good bit of the functionality of NUnit inside the test itself.

A `TestCaseSource` that is within the same class as the test must be static. That's a rule. However, that source may be a static method rather than a simple data array. By using a static method, you can accomplish pretty much anything you need so long as it is unchanging for the duration of the run.

Since I don't know your application, the following may not be a complete solution, but it should give you a start...

```
public static IEnumerable<TestCaseData> GetEntitiyTestData()
{
    yield return new TestCaseData(existingEntity, HttpStatusCode.OK);
    yield return new TestCaseData(-1, HttpStatusCode.NotFound);
}

[TestCaseSource(nameof(GetEntityTestData))]
public void GetEntityTest(int entitiyID, HttpStatusCode expectedResult)
{
    // Your test code
}
```

In addition to using a method, you'll see that I switched from raw object arrays to use of `TestCaseData`. While you could do the same thing populating an object array, which the method would return, that usually takes more code in the end and lacks the flexibility of using `TestCaseData`. I also find the user of an IEnumerable and yielding results to be more readable.

**Comment by cvetomir-todorov** [comment]
This issue is that in the `GetEntitiyTestData` I don't know the value of `existingEntityId`. I know it **after** the `dbContext.SaveChanges();` call.

In this specific case it was possible to enable temporarily the SQL Server `IDENTITY_INSERT` via a lot of Entity Framework infrastructure code, so that some IDs are passed instead of auto-generated by SQL Server. For the ones not passed I used test data builders which generate IDs manually. So in the end the `existingEntityId` was declared as a constant and used in both the test data and the `[SetUp]` method.

```C#
private static const int ExistingEntityId = 121;

[SetUp]
public void SetUp()
{
    someEntity.Id = ExistingEntityId;
    // populating the db context here
    dbContext.SaveChanges();
}

public static object[] GetEntityTestData =
{
    new object[] { ExistingEntityId, HttpStatusCode.OK },
    new object[] { -1, HttpStatusCode.NotFound }
}

[TestCaseSource(nameof(GetEntityTestData))]
public void GetEntityTest(int entityId, HttpStatusCode expectedResult)
{
    // use the entityId here
}
```

This seemed to me the other solution to make it work with the static data used in the data-driven test apart from the already provided one relying on delegates. In both cases it was hard to do so.

**Comment by CharliePoole** [comment]
OK... Yes, I was assuming you would know the ids you intended to use in advance.

Key thing to remember is the order of execution.

1. Your tests are created through TestCaseSource (or similar)
2. Any OneTimeSetUp is run
3. Each test is run using SetUp+Test+TearDown
4. Any OneTimeTearDown is run

In thinking about this, I find it useful to imagine that (1) happens a __very long time__ before (2). In fact, if you were using a GUI, it would probably be many minutes.

I think what I would do in this situation is to have a set of ids that are always used in the test database. Then you can assume they are present in your tests. In fact, it's useful to set things up so that you can create an alternative fake database containing the same items when you are testing business logic.

**Comment by cvetomir-todorov** [comment]
Oh, if I knew them I would be using the delegates solution in the first place. So from what I understand considering the order of execution it would be hard to do what I need without one of the two approaches (delegates and known IDs). So I am closing this I guess.
