### ISSUE TITLE
Q: Dev efficient setup of path

### ISSUE THREAD

**Issue by NoxArt** [nunit/nunit#3479]
Hi, we've just upgraded to NUnit3 and faced the breaking change where environmental path is no longer set. Now the path may afaik be prefixed on each respective place, or in a fixture setup, or using the special test class that sets it for the whole project (though this is brittle as this would execute only when running the whole project and not individual test, right?). And we still have maybe even hundreds of test projects here. Is there a better / easier / more global way?
The change may have made it cleaner, but so far it seems like a hit to practicality.
Thank you for help

**Comment by CharliePoole** [comment]
I'm assuming you mean the Current Directory as NUnit has never set the Path.

There is no.global workaround since it's possible to run multiple assemblies in parallel now. If those assemblies were running in the same Process, they could interfere with one another.

If you have a large number if tests, which rely on the CD, that's a bit unusual. Can you explain why that's the case?

**Comment by NoxArt** [comment]
Yes, sorry, Current directory.
Not all those test projects use this, but I was considering utilizing this for all of them to prevent wasting fellow devs they'd burn for new tests when they'd want to use paths.

I think most of those files are testing data (bundled with tests) which seemed impractical to embed into C# code. I'm not sure if this is a good or bad practice or somewhere in the middle, but probably difficult to solve this via a github issue.
I guess the bottom line is there's no known better approach anyway. So unless something from this comment sparks any idea it can be closed
Thank you

**Comment by CharliePoole** [comment]
In this situation, I think I would make an effort to simplify using TestContext.CurrentDirectory.TestDirectory through inheritance from a base class. Rather than having test fixtures read the data directly, provide some sort of "GetData(string name)" interface to allow you to change where the data is located.

Are you converting all projects at once? Do you need advice about how to do it incrementally?

**Comment by NoxArt** [comment]
That's a good idea, thank you
Yes, but we've already managed to do it, in the end there weren't that many needed changes. Where needed I used the solution suggested here https://github.com/nunit/nunit/issues/1072#issuecomment-218725978 and for the rest and as improvement/future purposes I'll consider gradually adopting what you've described
Thank you
