### ISSUE TITLE
Latest nUnit test dispatcher performance

### ISSUE THREAD

**Issue by replaysMike** [nunit/nunit#3509]
We recently tried upgrading a large solution (100 projects) that referenced nUnit `3.4.1` to `3.16.1`. Our total test times went from 8 minutes to 45 minutes running with a max concurrency of 18.

I did some investigation using [NUnit.Commander](https://github.com/replaysMike/NUnit.Commander) (indispensable for us, you should give it a whirl) and noticed that on latest `3.16.1` after the first 5 minutes or so, the number of concurrent tests drops frequently to 1. From there it kinda goes up and down occasionally, but the level of concurrency is practically dissipated. I would have expected to see if dispatch as many tests as it can to fill up the max 18 agents.

What could be related was our use of the `[NonParallelizable]` attribute. We had to mark certain test fixtures with it as some of the tests shared data among different test cases in the same fixture and this would fail with newer nUnit dispatching behavior. But my assumption was that using this attribute would get us the same level of concurrency as seen in 3.4.1, perhaps my understanding of its usage is incorrect.

@CharliePoole

**Comment by CharliePoole** [comment]
Assuming only one copy of nunit3-console is running at a time, the `--agents` setting controls how many of your test assemblies will run concurrently. The `[Parallelizable]` and `[NonParallelizable]` attributes are another matter entirely. They control parallelism __within__ each assembly using worker threads. The number of worker threads per assembly defaults to the number of cores you have or uses the value you set for `[LevelOfParallelism]`on each assembly.

For example, if you run 18 assemblies at time with four worker threads per assembly, then your max concurrency is 72 rather than 18. As you probably know, trying to run too many things at once can slow you down.

The other thing that can happen is that you reach a point where most of the assemblies have completed and there are only a few left running. Naturally, your run can't complete untill all the last assembly finishes. Since you are seeing the level of concurrency dropping as the run progresses, I suspect that may be what is happening to you.

**Comment by replaysMike** [comment]
That's also what I was trying to track, but it seems NUnit 3.4.1 has a bug in the event extension support and never sends start events for assemblies and fixtures - they are all StartSuite events even though the end events are correct.

I usually don't see more than 4 agents running at a time, and we aren't passing `--agents` at all to the console only `--workers=18`. `[LevelOfParallelism]` isn't being used either. Is there a way to get the same dispatching behavior seen in `3.4.1` in `3.16.1` using a particular configuration?

**Comment by CharliePoole** [comment]
@replaysMike You used the word "agents" in the original issue description and again here. An "agent" is an instance of `nunit-agent.exe` or `nunit-agent-x86.exe`. That's different from a "worker". If you are not specifying `--agents` and are running with multiple process, then you will have as many agents as you have test assemblies. Again: agents are processes, workers are threads.

I doubt anyone can tell you definitively what has changed over the course of 12+ releases! We'll just have to look at the behavior you are getting versus the behavior you want to see.

Info that would help us:
 * What is your actual command-line?
 * How many test assemblies do you run together?
 * What specifically are you observing that shows reduced parallelism?

**Comment by rprouse** [comment]
I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.
