### ISSUE TITLE
Is it possible to call Assert.Ignore() using reflection?

### ISSUE THREAD

**Issue by owenniblock** [nunit/nunit#3515]
We have a test framework which often uses NUnit as the test runner (but not always) and we're looking for a way to ignore tests under certain circumstances (for example where tests are run on iOS devices but the test targets Android).

If I add the following line to a test it works as expected:

```
Assert.Ignore("Reason for ignoring");
```

However when I try to call this method via reflection - it looks like the IgnoreException doesn't get handled by the test runner?

```
var method = nunitType.GetMethod("Ignore", new[] { typeof(string), typeof(object[]) });
method.Invoke(null, new string[] { exceptionText, null });
```

Results in:

```
Running RotateTests.RotateTests(Android).Rotation ...
Result message:
System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> NUnit.Framework.IgnoreException : Reason for ignoring
```

Is there any way I we can use reflection to call the `Ignore` method so we can keep the framework agnostic?

**Comment by mikkelbu** [comment]
From which context are you calling the Ignore and why cannot you call it directly? (Perhaps a minimal example would make it easier to pinpoint the problem)

**Comment by CharliePoole** [comment]
@mikkelbu beat me to the punch, but I'll enlarge on the question. When your framework is using NUnit, exactly how does your code load and run the tests? What do you call?

**Comment by CharliePoole** [comment]
Also... do you really want to __Ignore__ the tests (very specific meaning to NUnit) or do you merely want them to be skipped (not run)?

**Comment by owenniblock** [comment]
Our code sits within the Tests themselves - so the actual code here is checking whether you've selected the right OS (Android or iOS) for the App that's being run.

The Test is already running when we hit this code (there's no way around that) and currently when this occurs we throw an Exception which we later remove from our own test reports (no-one cares that the test didn't run because you sent it both Android and iOS tests) however users who are using the generated NUnit report xml (from CI generally) still see thes as failures so it would be a much better experience for the user to see that these tests have been ignored.

So - to expand on how tests are run: we don't run the tests, that's done by either the user's local test runner or when we do it ourselves we use the nunit-console.

This occurs frequently because the most common way of sharing a test between both Android and iOS is to annotate the test fixture:

```
    [TestFixture(Platform.Android)]
    [TestFixture(Platform.iOS)]
    public class RotateTests : BaseTests
```

I can simulate this by creating a simple test and adding some code in to the `BeforeEachTest()` method which we run as a `SetUp` method.

We definitely want to `Ignore` - it would solve this problem perfectly for us.

We don't want to add a direct reference since the framework doesn't currently have a reference to any test framework (you can use any locally) so we want to check if NUnit exists in the AppDomain and if it does, handle this scenario gracefully. Other test frameworks will exhibit the existing Exception behaviour unless we have a lot of user requests to change it.

**Comment by owenniblock** [comment]
I can probably create a little project to demonstrate what I mean if it's not clear from the above?

**Comment by CharliePoole** [comment]
Randomly ordered thoughts...

If I were doing this, I would want to see "Skipped" behavior rather than "Ignored" since "Ignored" is a type of warning in NUnit, which means the run doesn't quite succeed. What you are doing seems to be intentional skipping like what our built-in `PlatformAttribute` does. (Too bad we never got to the point of making that attribute extensible.) In any case, you can have whichever behavior you prefer.

May I take it that you __never run__ both platforms in the same execution? If that's so, I would simply pass an execution parameter to the run that specifies which platform is to be used. The `OneTimeSetUp` of your fixture could look at that parameter and act accordingly. The fixture would no longer need to be parameterized at all.

If you prefer using two instances of the fixture for some reason, I can tell you how to do it in NUnit. However, there's still one thing I don't get that I need to understand first.

Your code is in the tests. The tests contain NUnit attributes and (I presume) Asserts. So the tests reference NUnit In that case, how is it possible for other non-NUnit runners to execute them? What runners, for example, might some of your users be using?

**Comment by CharliePoole** [comment]
And, by the way, it is of course possible to call Assert.Ignore by reflection. However, you shouldn't do it unless you are running in an NUnit `TestExecutionContext`. Easiest way: create a `OneTimeSetUp`method. I believe that's unique to NUnit so other runners would hopefully ignore the attribute. NUnit will create a proper context and then call it.

Within that method, check if NUnit is loaded and, if so use reflection to call either `Assert.Ignore` or `Assert.Inconclusive` (my preference). That way, you only have to get the assembly, then the Type and finally the method to call. There are other ways but they would require even more reflection.

**Comment by owenniblock** [comment]
Sorry - in any normal scenario our code is called by our user's code (which sits in a `SetUp` method) so our code doesn't have the Tests - it simply gets called from a user's code:

```
[TestFixture(Platform.Android)]
[TestFixture(Platform.iOS)]
public class UserClassTests {

  [SetUp]
  public void UserTestSetUp()
  {
    OurFramework.CallsSomethingThatWantsToSkipThisTest();
...
```

I'm trying to simplify my explanation and in doing so comfusing you :)

**Comment by CharliePoole** [comment]
So... your code is in a separate assembly... the user test references both your code and some framework but your code doesn't reference any framework? If so, I understand.

Seems like it would be better for an NUnit user to make use of `OneTimeSetUp` so the entire fixture could be skipped in one call, but that's minor.

Your code, once called could
1. GetCallingAssembly
2. Check that assemblies references to see if NUnit is referenced.
3. If so, Load the NUnit framework (which is a no-op since it's already loaded)
4. Get the Assert Typeinfo
5. Get the Ignore or Inconclusive methodinfo.
6. Invoke the method, probably passing a message.

OTOH, I'm still wondering... Assuming you only make a run for one platform at a time, why not just set up a parameter that is passed to initialize the test run. That is, just tell the test run what is actually being used in the first place.  The tests could use the setting to act differently if necessary but would not need to call your code - at least for this purpose. Am I missing something?

**Comment by owenniblock** [comment]
Running locally - it's perfectly possible to run against both Android and iOS - it's only when the system runs in the cloud (because each execution host is sandboxed to a device) that we cannot run against both OSs).

Although we could get users to add some logic to test if they're in the cloud and then respond appropriately I've found in the past that relying on users to diagnose their issues, find the correct documentation and fix an issue like this will still take up support time - whereas what I'm trying to do is just make it work with what gets sent to us now :)

I'm going to create a little test project with the above - I'll link it here if it's ready. If it works - hopefully it'll help future developers who want to do similar - if it doesn't, it'll give us a good point of reference for further discussion.

Thanks for your help so far!

**Comment by owenniblock** [comment]
OK! I managed to work out the confusion some more.

[Here's a demo project showing what I've found out](https://github.com/owenniblock/nunit-ignore-by-reflection/blob/master/Example.NUnitIgnoreByReflection/Test.cs)

When you run this, everything runs as expected in the constructor but when you run the same code in the `SetUp` method, calling out to Ignore or Inconclusive fails when it's done via reflection.

<img width="1030" alt="Screenshot 2020-03-30 at 13 59 52" src="https://user-images.githubusercontent.com/4696224/77915872-1916c080-7290-11ea-8061-bdc8cd86fc6c.png">

**Comment by jnm2** [comment]
@owenniblock The problem you're seeing is due to MethodInfo.Invoke wrapping all exceptions in TargetInvocationException. My rule of thumb is to avoid MethodInfo.Invoke by creating caching a delegate instead. Delegate invocation is much faster than reflection invocation and it doesn't have the downside of wrapping exceptions.

```cs
// Binding flags both help with correctness and improve performance.
var ignoreMethod = nunitType.GetMethod("Ignore", BindingFlags.Public | BindingFlags.Static | BindingFlags.DeclaredOnly, null, new[] { typeof(string), typeof(object[]) }, null);

var ignoreDelegate = (Action<string, object[]>)ignoreMethod.CreateDelegate(typeof((Action<string, object[]>));

// Throws IgnoreException
ignoreDelegate.Invoke("Test", null);
```

**Comment by jnm2** [comment]
This is what I would do:

```cs
private static readonly Action<string, object[]>? AssertIgnore =
    nunitAssertType.CreateStaticMethodDelegateIfExists<Action<string, object[]>>("Ignore");

private void DoSomething()
{
    AssertIgnore?.Invoke();

    // Implement fallback behavior
    throw new NotImplementedException("NUnit's Assert.Ignore method was not found or did not throw an exception.");
}
```

```cs
internal static class ReflectionExtensions
{
    public static T? CreateStaticMethodDelegateIfExists<T>(this Type declaringType, string staticMethodName) where T : Delegate
    {
        var method = declaringType.GetMethod(
              entryPointMethodName,
              BindingFlags.Public | BindingFlags.Static | BindingFlags.DeclaredOnly,
              binder: null,
              GetInvocationParameterTypes<T>(),
              modifiers: null);

        return method is null
            ? null
            : (T)Delegate.CreateDelegate(typeof(T), method);
    }

    private static Type[] GetInvocationParameterTypes<T>() where T : Delegate
    {
        var method = typeof(T).GetMethod("Invoke", BindingFlags.Public | BindingFlags.Instance)
            ?? throw new NotSupportedException("Delegate types must have an Invoke method.");

        return Array.ConvertAll(method.GetParameters(), p => p.ParameterType);
    }
}
```

**Comment by jnm2** [comment]
And, of course, I'm only speaking to the mechanics of your direct question. I agree with Charlie that at a higher level, Ignore is most likely not the thing you want.

**Comment by owenniblock** [comment]
That works perfectly, thanks @jnm2 - I'll use `Inconclusive` - I hadn't really thought about the difference until Charlie mentioned it (I guess I was too focussed on just getting _something_ to work).

Thanks both!
