### ISSUE TITLE
I wanted to get the data that can be passed as an argument to Test case source from OneTimeSetUp Attribute

### ISSUE THREAD

**Issue by sourcecode14** [nunit/nunit#3519]
I wanted to get the data that can be passed as an argument to Test case source from OneTimeSetUp Attribute

I wanted to read test data for all the test cases from the fixture in One Timesetup so that with the help of test case source the data can be passed to the test cases. Is it possibe  , if yes , let me know how ?

**Comment by CharliePoole** [comment]
It's not possible because the data is used to create the tests. It's only after the tests are created that they can be executed. OneTimeSetUp is part of test execution.

Rather than pass your data as an argument to the test case source, you can use a method as your source and create the data there. That is...

```c#
static IEnumerable<TestCaseData> SourceMethod()
{
    // Create one or more TestCaseData items and return each one using yield return
}

[TestCaseSource(nameof(SourceMethod))]
public void YourTestMethod(...args...)
{
    // Run each test case
}
}

**Comment by rprouse** [comment]
I am closing this as a question.
