### ISSUE TITLE
TestCaseSource fails to match signature for strings which are not constants

### ISSUE THREAD

**Issue by krosn** [nunit/nunit#3521]
NUnit Version: 3.12.0
NUnit3TestAdapter Version: 3.16.1

I noticed an issue when using the TestCaseSource attribute in method format. When a string value is not a constant (Test Case 1), it will not match a signature that should otherwise match (Caller 1). However, changing the test parameter from a string (caller 1) to an object (caller 2) and converting it back to a string inside the method seems to work fine and both test cases run.

This behavior seems odd. It feels like a bug that the string value is not recognized properly, but if this behavior is expected, the docs should be updated to reflect this. With no error it is hard to figure out that this is why the test isn't running.

```c#
private static IEnumerable<TestCaseData> MyTestCaseData()
{
    var usingVariable = "whatever";

    // Test Case 1
    yield return new TestCaseData(
        new List<Guid>() { },
        $"{usingVariable}");

     // Test Case 2
    yield return new TestCaseData(
        new List<Guid>() { },
        "thisIsAStringLiteralConstant");
}
```

```C#
// Caller 1
// Only one test case is run
[Test]
[TestCaseSource(nameof(MyTestCaseData))]
public async Task MyTest(List<Guid> guids, string words)
{
}
```

```C#
// Caller 2
// Both test cases are run
[Test]
[TestCaseSource(nameof(MyTestCaseData))]
public async Task MyTest(List<Guid> guids, object words)
{
}
```

**Comment by krosn** [comment]
I am running these tests in VS 2019 16.5.2 from the Test Explorer

**Comment by mikkelbu** [comment]
On my machine both tests run (same version of NUnit and adapter, but using a newer preview of VS).

Questions/comments:
* When you say that "will not match a signature that should otherwise match" does that mean that the test case is not shown as a test in the test explorer, or that the test is shown, but not run?
* Disable "Discover tests in real time..." in Tools => Options => under Test
* Increase the logging in the test execuion and report the results here. Also perhaps try out DumpXmlTestDiscovery and DumpXmlTestResults - see https://github.com/nunit/docs/wiki/Tips-And-Tricks - and see if they give any hints.

**Comment by krosn** [comment]
It is shown in the test explorer, but does not run when selected. I can
give those a try. Which preview version are you using? It's possible that
the problem is with Visual Studio.

**Comment by mikkelbu** [comment]
It work for me in Version 16.6.0 Preview 2.1. I also tried on VS 16.4 Preview 1.0 and there it also worked. I think the best approach is to follow the last item above 
> Increase the logging in the test execuion and report the results here. Also perhaps try out DumpXmlTestDiscovery and DumpXmlTestResults - see https://github.com/nunit/docs/wiki/Tips-And-Tricks - and see if they give any hints.

**Comment by rprouse** [comment]
@krosn I'm going to close this issue because we can't confirm it. Please reopen if you have more info.
