### ISSUE TITLE
Add .NET Core 2.1 build of Framework

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit#3526]
There's currently a problem with running tests on .NET Core, that they can only be run successfully if the test assembly and runner are located in the same directory. This hasn't been too much of a problem yet, as for the adapter that's always the case, but it is a problem for users of the engine  (https://github.com/nunit/nunit-console/issues/710), and will be for the .NET Core Console.

We currently have some reflection-based code which attempts to access .NET Core specific functionality from .NET Standard to correctly load the assemblies - although it's not working for the engine's case, due to the above assumption. It's also tricky in terms of maintenance - and at this point, I suggest we should just add a .NET Core build and remove the reflection.

https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/AssemblyHelper.cs#L90

I'm suggesting this as an additional build rather than a replacement for .NET Standard 2.0, to continue supporting our Xamarin users. I'm suggesting .NET Core 2.1 as the oldest current LTS version that I think the required AssemblyLoadContext APIs are available on.

This is a bit of a blocker for the console, so I'm happy to try and look at it. (Although anyone else who'd like to take this on would be very welcome! 😄)

**Comment by CharliePoole** [comment]
I'm in favor of this feature (I think it's a feature rather than a bug, btw) but I have a bit of a side comment, which might impact the console project...

"There's currently a problem with running tests on .NET Core, that they can only be run successfully if the test assembly and runner are located in the same directory. "

I'm currently running .NET Core tests using the .NET Standard 2.0 engine. I find I need to have the nunit framework in the same directory, but nothing else. We should probably go elsewhere to discuss why this is working for me.

**Comment by ChrisMaddock** [comment]
You're probably right there - it's been a long time since I last tried to debug this. 🙂

**Comment by ChrisMaddock** [comment]
I've come to the conclusion that this is the wrong approach, and we should instead be approaching this at the point we load the framework, in the engine.

This issue is superceded by a number of PR's attached to https://github.com/nunit/nunit-console/issues/710
