### ISSUE TITLE
Question: is there a way to get parallel assembly execution with dotnet core?

### ISSUE THREAD

**Issue by fluffynuts** [nunit/nunit#3562]
Typically, I've used nunit-console to run tests, however, I'd like to be able to run tests on !windows, so I have an optional dotnet core test strategy, which works, but takes a lot longer, primarily because tests are run in series.

I've had a look at https://github.com/nunit/docs/wiki/Framework-Parallel-Test-Execution -- this looks like it deals with parallelisation _within_ the same test assembly. Is there a way to emulate the nunit-console parallel assembly test option from `dotnet test`?

I have some assemblies which run quickly, and others (eg tempdb, which spins up mysql instances, or simple http server, which takes a second to spin up) which take a little longer per-test. Ideally, I'd like to run these test assemblies in parallel.

I could figure out custom parallelization by spawning `dotnet test` per assembly, throttled, from my build pipeline, but I'd really like to know if there's a better way (:

**Comment by CharliePoole** [comment]
If you are only needing to run in parallel on your desktop, rather than in a CI environment, allow me to call your attention to `testcentric-gui`, which runs .NET Frameowork and/or core tests on the desktop. The GUI itself requires .NET 4.5  or highter, but the processes it spawns may use any installed version of the .NET Framework as well as .NET Core 2.0 or higher.

This feature is being worked on for the nunit3-console as well so you may want to wait for that. As for .NET test, I don't think it's currently possible and I don't know what's being worked on.

Your understanding of framework parallel execution is correct. That's only related to what happens within an assembly. We can transfer your issue to the nunit3-console if you'd like to get some feedback there.

**Comment by fluffynuts** [comment]
@CharliePoole thanks for the details. I kinda need this to run on !windows, so unless nunit-console has a netcore target, that's not going to help. I haven't seen another way to run tests for .net core other than `dotnet test`, but would be glad to be proven wrong. I'm considering adding manual parallel support to my own build pipeline to facilitate this requirement.

**Comment by CharliePoole** [comment]
@fluffynuts Out of curiosity, what is your primary development environment, as opposed to Windows?

Here are the options I'm familiar with for running .NET Core Tests. All approaches use the nunit framework and .NET core runtime, in addition to what is listed.

Command | Parallelism | Additional Software Used
---------- | ----------- | ------------
dotnet test | Single assembly only. | NUnit VS Adapter
nunitlite | Single assembly only | NUnitLite
nunit3-console | Yes (**not yet released**) | nunit3-console
testcentric | Yes. | testcentric-gui

If I were in your position and looking to create my own parallel testing pipeline, I would base it on NUnitLite because it's a lighter-weight approach, with an executable test assembly. Of course, if you need need specific features provided by `dotnet test` and the VS adapter, then that might be a better choice.

I was suggesting transferring your issue because it's not necessarily an NUnit Framework issue and you will reach the people working on the particular project that affects you by having the issue there. Of the above, only the NUnitLite approach is provided by the project repo we're now in. The other three each have their own projects, issues and - barring some overlap - developer teams.

**Comment by CharliePoole** [comment]
@nunit/framework-team As a question, this seems to be answered already. Suggest closing unless @fluffynuts wants it transferred elsewhere.

**Comment by fluffynuts** [comment]
I run and test on multiple platforms, so usually what I'm looking for is platform agnosticism, wherever possible.

Right now, I'm getting GitHub actions running tests for me at push and investigating Windows host vs Linux host. I'd like, where possible, not to require a specific OS for dev or testing so I'm comparing dotnet test against nunit console - the former runs anywhere, the latter does parallelism.
Also, I've found that the windows CI environments I've found on GitHub CI as well as other places (eg CircleCI) run server 2019 and I'm seeing odd behavior from nunit console (and opencover): it appears that the OS is providing more than one variant for some environment variables, only different by casing (eg HOME vs home), which trips up `new Process` - apparently Environment.GetEnvironmentVariables returns all of them but StartInfo.Envrionment is backed by a case-insensitive HashSet so I get both nunit console (and opencover) throwing an exception at runtime and bailing out early. Since `dotnet test` isn't starting new processes, it doesn't hit this, so that's also guiding me in that direction - and if I'm using `dotnet test`, perhaps I can test on a Linux host, which spins up faster.

Anyways, I'm happy for you to close this out. I don't think the nunit framework can make `dotnet test` do what I want and it's looking like nunit console may be a non-starter due to the crash at startup (again, not the fault of nunit console, but this is going to become someone's problem at some point).

Btw, I've investigated a possible fix for the above, but I haven't gotten very far - the crash is happening in framework land and nunit console isn't even manipulating env vars on the startupinfo :pensive:

**Comment by fluffynuts** [comment]
Just for reference, the projects involved target both netstandard and net4x - on Linux hosts, mono fills in for net framework.

**Comment by CharliePoole** [comment]
Hmm... my table didn't list platform support. 

NUnit3-console runs on both platforms, but the functionality you want is not yet released... 

NUnitLite is part of the NUnit framework and released with it. It runs on both platforms. I tend to like working as close to the metal as I can, so it's a favored approach of mine. Once upon a time, I also wrote it, so that no doubt influences me. :smile: 

TestCentric is from a different publisher, who oddly enough is me. it also supports both platforms, using mono on linux. Unfortunately, it isn't regularly tested on linux because I haven't been able to run it headless in it's own CI builds as I do on Windows. It will eventually have a .NET Core build and then migrate to .NET 5.

**Comment by mikkelbu** [comment]
I agree with Charlie about closing this issue. Please note that we will still see additional comments to this issue. Thanks for the question @fluffynuts.

I was curious about the duplicate environment variable (as I think I've also encountered it some time ago), and I found dotnet/runtime#19142 and dotnet/corefx#33194. So I think that this issue is solved from .NET Core 3.0 if I read the PR correct.
