### ISSUE TITLE
Assert.NotNull with C# nullable

### ISSUE THREAD

**Issue by NN---** [nunit/nunit#3569]
It would be nice to have this code compiling without error.
Is it possible ?

```cs
string? x = f();

Assert.NotNull(x);

UseX(x);


void UseX(string x ) { ... }
```

**Comment by NN---** [comment]
Proposal:

```cs
void NotNull<T>([NotNull] T t) => _ = t ?? throw new ArgumentNullException();
```

**Comment by CharliePoole** [comment]
Perhaps you could describe the problem you are trying to solve? It's not clear from reading this so far.

**Comment by NN---** [comment]
I would like to have some ability to say value is not null and type is not nullable after the Assert.NotNull call.

**Comment by CharliePoole** [comment]
In your initial example what kind of error are you getting when you compile? Is it on the `Assert.NotNull`? I get that you think we should just try the code, but that's a lot to expect if you don't provide some motivation by saying what's happening. Everyone who works on this is a volunteer.

Your suggestion to use a generic makes sense if that's where the problem is. However, throwing an NRE indicates an error in the test to the user rather than a test failure.

What happens if you use `Assert.That(x, Is.Not.Null)` instead?

**Comment by NN---** [comment]
I mean something like these annotations 
https://github.com/xunit/assert.xunit/pull/36/files

**Comment by mikkelbu** [comment]
@NN--- Work like this have been started in nunit/nunit#3376, but due to `Assert.Multiple` we cannot be sure that `Assert.NotNull(x)` throws when `x` is `null`. Inside `Assert.Multiple` the flow continues. See e.g. https://github.com/nunit/nunit/issues/3376#issuecomment-563227083

Also we are planning to suppress some of these warnings using NUnit Analyzers, see e.g. nunit/nunit.analyzers#157. 

I don't think this issue provides any information not already in existing issues, so I'm proposing that we close this as a duplicate.

**Comment by NN---** [comment]
Thanks

**Comment by jnm2** [comment]
In the next version of NUnit, you will see documentation clarifying these expectations on all Assert methods:

> Returns without throwing an exception when inside a multiple assert block.
