### ISSUE TITLE
NUnit can't determine the generic type for null argument

### ISSUE THREAD

**Issue by Denis535** [nunit/nunit#3576]
I'm getting error when running generic test with null argument.
`Unable to determine type arguments for method`
Why did NUnit not assume that this is an object?

**Comment by CharliePoole** [comment]
If you have a generic test with argument of type T and pass in null, the compiler is unable to determine the Type to use. For example...

```c#
void SomeMethodT(T arg)
{
    ...
}
```

If you try to call `SomeMethod(null)` the compiler gives you an error: "The type arguments for method 'SomeClass.SomeMethod<T>(T)' cannot be inferred from the usage. Try specifying the type arguments explicitly."

That's exactly what is happening here.

To avoid this, you will most likely need to create a different test to handle null arguments. If you post an example of your code, someone may have other suggestions.

**Comment by CharliePoole** [comment]
@Denis535 An alternative I forgot to mention is to use `T?`

**Comment by Denis535** [comment]
The compiler is unable to determine the type.
But NUnit could assume that null is object type.
I think it would be good for many cases.

**Comment by mikkelbu** [comment]
Can you provide some cases? Because, most cases I can think of can be handled in other ways (but I've not thought a lot about this)

**Comment by Denis535** [comment]
Here I'd like `T` to be `Object` when value is null.

        [TestCaseSource( nameof( Args_Serialization ) )]
        public string Test_00_Serialization<T>(T value) {
            var obj = new FakeJsonObject<T>( value );
            return ObjectSerializer.Serialize( obj );
        }

**Comment by CharliePoole** [comment]
NUnit (and the compiler) can't tell what the user wants here. Some might like us to assume `object`. For others that would be a  problem.

We didn't make a choice in this case for the same reason the compiler authors didn't: there's no info in the code to indicate what the user would like to happen. Making a guess that's right part of the time does the user a disservice because it leads to silent errors.

In the case of the compiler seeing a direct call to a method, you can clarify this by casting the null to a specified type. That won't work for the NUnit attributes, unfortunately, because the value is ultimately passed in as an object argument.

We could, however, give the user another way to specify Type parameters rather than merely deducing them from the actual arguments. This is already implemented in the case of fixture constructors. The `TestFixture` attribute gives you the option of either speciying the Type parameters ahead of the actual parameters or using a named property. I did this because we needed to be able to instantiate generic fixtures through a default constructor.

Pretty much identical code to that in `TestFixtureAttribute` could be added to `TestCaseAttribute` and `TestCaseData` allowing the user to specify the Type parameter where needed. I'd favor limiting the change to use of a named property. The double use of the arg list for TestFixture has turned out to be a little confusing to users.

**Comment by CharliePoole** [comment]
BTW, we envisioned the possible need for this back when parameterized test cases were introduced in NUnit 2.5. On the principle that added features can never be removed, we decided to wait and see if issues arose that required a way to "manually" specify Type parameters. That was in 2009, which seems to say that it's not a high priority need.

It's up to the framework project team to decide if a PR would be accepted to introduce this feature. I'd only argue against doing anything "automatically" because it would introduce an unexpected quirk in how arguments are interpreted and violate the principle of "least surprise."

The workaround would, of course, be to write a separate test for the case of a null argument. Some would argue that it's better to put special cases in separate tests anyway, so as to highlight them.

**Comment by jnm2** [comment]
> I'd only argue against doing anything "automatically" because it would introduce an unexpected quirk in how arguments are interpreted and violate the principle of "least surprise."

This is exactly what I wanted to say too.

I'd prefer to solve this by looking at how you'd solve this if you were calling the Test_00_Serialization method yourself in C#, and then seeing if we can map that back onto how TestCaseSource works.

Calling from C# would look like this:

```cs
Test_00_Serialization<object>(null);
```

We already do something that looks somewhat similar:

```cs
[TestFixture(typeof(object), null)]
class SomeFixture<T>
{
    public SomeFixture(T value) { }
}
```

I would propose making TestCase and TestCaseSource consistent with TestFixture so that type arguments may be specified as a series of System.Type values before the method arguments.

**Comment by CharliePoole** [comment]
@jnm2 You who work on this will have decide, but I'd lean towards the other choice of the two available in `TestFixtureAttribute`, a `TypeArgs` named property.

It's admittedly more verbose, but is eminently clear to somebody reading the code. Using the initial typeof arg makes it look like the fixture takes two arguments, the first being Type.

And, of course, if you support the initial type argument, then you have to __also__ provide TypeArg in order to allow for a method like `MyMethod(Type type, int int)`. So if you want to pick one way to do it, then I believe you are forced to use the named property.

Of course, you could provide both ways, to be consistent with TestFixture, which certainly has advantages.

**Comment by Denis535** [comment]
I would prefer that generics and arguments to be passed as one constructor argument.
I'm sure it will be clear enough to the anybody.

```
[TestCase( typeof(int), 777      )]
[TestCase( typeof(float), 77.7f  )]
[TestCase( typeof(string), "777" )]
VS
[TestCase( 777,   TypeArgs = new [] { typeof(int) }    )]
[TestCase( 77.7f, TypeArgs = new [] { typeof(float) }  )]
[TestCase( "777", TypeArgs = new [] { typeof(string) } )]
```

**Comment by CharliePoole** [comment]
@Denis535 As noted, you can't __only__ do that because it precludes any test method taking a Type as it's first argument.

**Comment by Denis535** [comment]
You mean a such case?
```
[TestCase( typeof( int ), 777 )]
public void Test<T>(Type type, T value) {
}
```
Yes, this can be interpreted in two ways:
1) type is argument.
2) type is generic.

But can't this be checked by comparing the number of parameters and arguments?
In the previous example type is argument.
In the next example type is generic.
```
[TestCase( typeof( int ), 777 )]
public void Test<T>(T value) {
}
```

**Comment by CharliePoole** [comment]
If the team wanted to do that, it's possible. Past philosophy was to give errors whenever there is ambiguity. 

I spent a long time on getting fixture arguments to work. There were corner cases where there was not enough info to decide. Test cases are a bit different but I think that's still the case. Off the top of my head, optional args and params arrays come to mind.

**Comment by jnm2** [comment]
Here's another example of an ambiguity:

```cs
[TestCase(typeof(int))]
public void Test<T>(object value = null) { }
```

**Comment by Denis535** [comment]
Okey. How to set up generic types is a topic for other issues: https://github.com/nunit/nunit/issues/1215 and https://github.com/nunit/nunit/issues/2562
I think this issue should be closed.

**Comment by CharliePoole** [comment]
@Denis535 I'm surprised. As compared to the other two, which need design, this is something we solved once already! Your call, however.

**Comment by jnm2** [comment]
Isn't https://github.com/nunit/nunit/issues/2562 an exact duplicate?

**Comment by CharliePoole** [comment]
I guess it is! I saw that it was still labeled as needing design and didn't read through it again. The original requester asked to do a PR but that was going on three years ago!!!

**Comment by CharliePoole** [comment]
Well no, because (1) I didn't say that and (2) what I said is just one guy's opinion.

Because I no longer work on this project, I try to be very careful about the kind of comments I make. In this case,   I gave some history about why it works as it does and suggested a way to fix it as a relatively small change, with only a small chance of breaking anyone.

Of course the guys who actually work on the framework have to decide what is acceptable.

I did say, about your proposed change "you can't do only that" meaning I think you also have to add the named property for use by those whose code is broken by your change... i.e anyone with tests having a Type as the first argument.
