### ISSUE TITLE
considered dropping support for some older frameworks?

### ISSUE THREAD

**Issue by SimonCropp** [nunit/nunit#3578]
currently net35, net40, and net45 are supported

 * net35 released in 2007
 * net40 released in 2010
 * net45 released in 2012

there seems to be a reasonable amount of complexity related to supporting them.

Is it time to drop support for any of those? People using them can continue to use older versions

**Comment by jnm2** [comment]
We dropped support for .NET 2.0 when faced with having to solve a very difficult puzzle with NUnit.System.Linq. We aren't facing similar cliffs with the other framework versions presently that I'm aware of. Our code would become cleaner for sure mainly if we dropped net40 because of the quirks of TaskEx and the pre-4.5 compiler polyfill, but even to clean that up is extra work, not avoiding work. The benefits would have to be very clear and concrete. Even then, NUnit has historically made it a point to support old versions, including fixing bugs and providing enhancements. There are users that may be using NUnit for that reason.

Of the frameworks you mention, .NET 3.5 (SP1) and .NET 4.5.2 are still under active support by Microsoft as Windows OS components.

Some of the projects at my day job use .NET Framework 3.5 because they are loaded as modules into a large, slow-moving third party software package.

**Comment by jnm2** [comment]
@nunit/framework-team Until the [GitHub Discussions feature](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions) has a beta for all public repositories, should we add `is:discussion` on issues like this? I guess `is:question` could work.

**Comment by OsirisTerje** [comment]
@jnm2   +1 from me.  Adding the same to the adapter repos

**Comment by mikkelbu** [comment]
I don't mind "is:discussion", but we already have "awaiting:discussion". Couldn't we just reuse that?

**Comment by CharliePoole** [comment]
Is:question works if the question itself is worded well...   if a team member asks the test of the team a question, it's the same as a discussion.

**Comment by jnm2** [comment]
`is:suggestion` maybe? "Awaiting" makes it sound like this thread can't proceed until a separate discussion happens.

Anyway, anyone else want to chime in on dropping or keeping support at the current time?

**Comment by CharliePoole** [comment]
There's already is:idea as well. Maybe the problem is failure to __have__ the discussion rather than one of coding.

**Comment by mikkelbu** [comment]
I still think we should support these versions. I know several companies that are stuck on old frameworks due to other constraints.
