### ISSUE TITLE
SetUp/TearDown and C# 8 nullability

### ISSUE THREAD

**Issue by drauch** [nunit/nunit#3613]
This issue is more of a question than a bug report.

Do you have a good strategy for C# 8 nullability annotations and tests? Unfortunately, even if we assign all fields in the SetUp method, it is not in a ctor and therefore the compiler thinks that all the fields are potentially null. We have to use the ! operator quite a lot to overcome the issue.

We don't want to ignore the warning either, because in the TearDown method it is actually possible that the fields are still null.

What's your take on this? Is there some feature missing from NUnit to overcome the problem in a "clean code" way?

Best regards,
D.R.

**Comment by jnm2** [comment]
Because C# 8 has no special knowledge of NUnit, class fields have to be analyzed from the standpoint that the class methods might run in any order. I have personally avoided class fields at all costs because it means that the tests within the fixture can't usually run in parallel with each other. I use private static helper methods to get things set up in variables within each test, or to avoid even more repetition, I declare a private nested Fixture class that sets things up for me and every test starts with `var fixture = new Fixture("optional params");`. If there is teardown, then `using var fixture = new Fixture("optional params");`.

All of this changes with #2574 though. Once this feature is available, parallelism is no longer in conflict with having class state, and the class constructor becomes the equivalent of [SetUp] rather than its current equivalent of [OneTimeSetUp]. Then you can initialize all the class fields in the constructor.

Nice avatar. That was a good game!

**Comment by drauch** [comment]
> All of this changes with #2574 though. Once this feature is available, parallelism is no longer in conflict with having class state, and the class constructor becomes the equivalent of [SetUp] rather than its current equivalent of [OneTimeSetUp]. Then you can initialize all the class fields in the constructor.

Uh, that sounds like exactly what we're looking for. Unfortunately that issue is in-review for quite some time now, let's hope it will finally get merged soon. You're a member of the Core team if I read correctly, do you have a time horizon for the merge? Is there anything the OpenSource community could do to decrease the time-to-market? :-)

Thank you also for your workaround idea, but I feel that it is exactly that, a workaround.

> Nice avatar. That was a good game!

Hehe, yes, also liked the soundtrack very much.

**Comment by rprouse** [comment]
Closing as an answered question.

**Comment by drauch** [comment]
@rprouse : Actually there is still the following question open:

> You're a member of the Core team if I read correctly, do you have a time horizon for the merge? Is there anything the OpenSource community could do to decrease the time-to-market? :-)

Maybe you can help me out here @rprouse 

Best regards,
D.R.

**Comment by rprouse** [comment]
@drauch we just need to make time to get the PR properly reviewed and tested. It is a big change from a first-time contributor, so we've been overly cautious with it. I'd like to get it merged soon though, so I'll take another look at it.
