### ISSUE TITLE
Replace Remoting with a Portable Networking Protocol

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#362]
NUnit currently uses .NET Remoting to communicate between the runner and agents. .NET Remoting is not supported by portable libraries or Silverlight, so it would be good to move to form of network communications that is supported by all platforms.

One minor complication is that NUnit makes use of client activated objects. These are effectively two-way communications between the client and the server. We will need to simulate this with some sort of polling by the agents. I see this working like,
1. Runner launches an agent with the URI to connect back to
2. Agent starts, connects back to the runner and registers
3. Agent polls the runner for work (Run, Explore, etc) and performs any work received. Polling continues until the Stop event is received.
4. Agent reports the results of all work back to the runner.

This is not radically different than the current communications. The only difference is that all communications are initiated by the client.

This just leaves the choice of which protocol to use for the communications. As far as I know, the options that will work with the portable framework are,

**TcpListener**

This will be the hardest option to implement. It is basically just a raw TCP socket. We will need to handle serialization and routing of all data.

**HttpListener**

This is a much nicer option as it allows us to create a very portable REST like interface. The HttpClient is portable and can be used on any platform. The problem is that unless you open the port using netsh as admin, the runner would require admin privileges to run. This is not acceptable.

There are 3rd Party HttpListener like options, but they would require taking a dependency on an external library. This might not be a serious issue since it is a dependency in the engine, not in the framework.

**WCF**

I am pretty sure that WCF is supported in portable libraries. This is a good option because it is closest to Remoting, but unfortunately it is only supported by .NET 3.0+. I don't think we are willing to drop support for .NET 2.0, so I don't think this is an option.

**Recommendation**

I think that using a 3rd Party HTTP library in the Engine and System.Net.HttpClient for the clients is our best option. It gives us a very portable and flexible networking protocol that is supported by all platforms.

If I have missed options or made a mistake in my assessment of the presented options, please add to the discussion. 

This could be a fairly big change, so I want to get some consensus on the approach before I start.

**Comment by CharliePoole** [comment]
In spite of the earlier discussion, nobody ever assigned it to 3.0 before!

**Comment by oznetmaster** [comment]
I have been working with a third party HTTP/WebSocket client/server package that is published under the MIT license.

 

I have it running on the Crestron system, and hence, CF.  It is designed for .NET 3.5 and up :(

 

It is one possible solution to the portable networking protocol.  And since it supports WebSocket, it can easily be interfaced using HTML5 as the GUI.

 

However, I am leaving for China for the month of February, and will be unavailable to work on this until I return.

**Comment by oznetmaster** [comment]
As a progress report, I have the webserver/websocket library fully running on CF (and on Crestron).  It is the websocket-sharp library (https://github.com/sta/websocket-sharp), published under the MIT license.

 

I am currently designing an HTML5/Javascript based gui using websockets as the communications protocol.

 

This has the advantage of making the gui/engine totally platform independent, and never having to be built for a specific platform, since it will run on any browser which supports websockets (which is pretty much all of them).

 

On the NUnit side, I am currently working with a wrapper for the existing framework controller.  I am not sure if this will be able to become a prototype for a generic framework driver or not.

 

One issue with this is that the gui will not be able to use any of the existing source files.  All new .js file are being developed that mirror the important .cs files (for example, for options).

 

The gui also has a command line in it, so that the gui can be used as a command line interface if desired.  One of the WebSocket commands is “commandline”.

 

For those not familiar with websockets, they are a fully asynchronous communications protocol, and are initiated from the client.  Once the connection is established, data transfers can be initiated by either the client or the server.

 

One issue is that this library is .NET 3.5 based.  I have not yet investigated whether it can be back ported to 2.0 or not.

 

Since I am leaving for China in a few days, there will be little if any further progress on this until I return in March.

**Comment by oznetmaster** [comment]
As an additional benefit, this will mean that this gui can be used on any ios or android device, as well as on a mac on osx.  So NUnit test will be able to be controlled from an iPhone…

**Comment by oznetmaster** [comment]
I should also mention that I use the Json.NET JSON framework to serialize/deserialize JSON.

 

This is an open source library, which is the most widely used JSON library for .NET (MIT license).

**Comment by CharliePoole** [comment]
@rprouse How come this is pending? What's the dependency?

**Comment by rprouse** [comment]
I have removed the pending tag. I am not sure why I added it in the first place.

**Comment by CharliePoole** [comment]
@rprouse This seems to belong to the milestone

**Comment by rprouse** [comment]
For the same reasons mentioned in #1138, I am going to move this out of the 3.4 milestone and wait to see how things pan out with the .NET Core release which is coming out at about the same time as 3.4.

**Comment by oznetmaster** [comment]
Not sure why the .NET Core release is relevant.  If the transport is totally encapsulated, should it make any difference?

**Comment by rprouse** [comment]
.Net Core changed my priority for this. I had originally thought you would run core tests through the engine by launching an agent compiled against Core. That didn't turn out to be the case though. Testing is built into the .NET Core tooling so we needed to implement their interface and communication. 

If I had stuck with this approach, it would have forced a dependence on a full .NET framework like Mono. With the new runner, you can run tests on Linux or Mac without Mono installed, just .NET Core.

**Comment by oznetmaster** [comment]
So there are no longer any plans to encapsulate the communications protocol so that it can be any protocol on any platform?

The only support will be for the .NET Core approach?

I am confused :(

**Comment by CharliePoole** [comment]
@oznetmaster if there were no plans, then this issue would not be here any longer. It's possible to disagree about priority but with limited resources we tend to focus on some things over others.

I view this one as high priority but even so I didn't find time to focus on it in the last release cycle. Rob is focused on .NET Core right now. I'm focused on splitting out the framework

I do think that putting this back in the product backlog already deprioritized

**Comment by rprouse** [comment]
The .NET Core release lowered the priority for this because that was my solution to running .NET Core tests. It turned out that was not the recommended way to run .NET tests since testing is a first class citizen in .NET Core. I thought it was better to go with what is available rather than fight it. With Xamarin also supporting `netstandard` now, we can also run those tests using the core runner.

That does not mean that this issue is not a good idea and it may become another way to run .NET Core tests and could open up SL and CF, but I was planning on seeing how everything settles with `netstandard` so that we can plan changes like this more intelligently.

**Comment by tom-dudley** [comment]
Any news on progress of this? I've been investigating https://github.com/nunit/nunit/issues/1834 and have come to the (possibly incorrect) conclusion that there isn't a way to 100% reliably avoid a `RemotingException` due to a hard TCP reset without changing how the engine/agent handle lifetimes/disposals, and given that this is already in the works, thought I'd check the progress.

**Comment by CharliePoole** [comment]
Unfortunately, nobody has taken this issue on as an actual assignment With nobody in charge of moving it forward it's sadly not progressing. 😥
