### ISSUE TITLE
IEqualityComparer is ignored on objects that implement IEnumerable and IEquatable<T>

### ISSUE THREAD

**Issue by Dimension4** [nunit/nunit#3631]
Given a class that implements **both** `IEnumerable` and `IEquatable<T>` and a custom comparer that implements `IEqualityComparer`, NUnit ignores the custom comparer and calls `IEquatable<T>.Equals` instead.

Here is a simple test:

```cs
[TestFixture]
public class TestClass
{
    [Test]
    public void TestComparer()
    {
        var a = new MyClass();
        var b = new MyClass();

        // This assertion does not fail, unexpected
        Assert.That(a, Is.EqualTo(b).Using(new MyComparer()));
    }

    [Test]
    public void TestLambda()
    {
        var a = new MyClass();
        var b = new MyClass();

        // This assertion fails, as expected
        Assert.That(a, Is.EqualTo(b).Using<MyClass>((x, y) => false));
    }
}

class MyClass : IEnumerable, IEquatable<MyClass>
{
    class MyEnumerator : IEnumerator
    {
        public bool MoveNext()
        {
            return false;
        }

        public void Reset()
        {
        }

        public object Current => null;
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return new MyEnumerator();
    }

    public bool Equals(MyClass other)
    {
        return true;
    }
}

class MyComparer : IEqualityComparer
{
    bool IEqualityComparer.Equals(object? x, object? y)
    {
        return false;
    }

    public int GetHashCode(object obj)
    {
        throw new NotImplementedException();
    }
}
```

`IEquatable<T>.Equals` will always return `true` while `IEqualityComparer.Equals` will always return `false`. However, the test that uses the comparer is green, meaning the comparer hasn't been used here but the Equals method. Note that this is only reproducible if `MyClass` implements **both** interfaces and is compared using an `IEqualityComparer`. Using a lambda produces the expected outcome, the test fails.

Reproducible on NUnit 3.12.0.

**Comment by stevenaw** [comment]
This is a bit of an interesting edge case you've found @Dimension4 

NUnit does a lot of magic internally to help make comparisons easier, one of which is that if the objects being compared implement IEnumerable then NUnit will enumerate and compare the contained values _unless the type is `string`_ . With your code sample, what that means is that NUnit will not apply the custom comparer immediately but will instead call `MyClass.GetEnumerator().MoveNext()` on `a` and `b`. Since both return false, NUnit detects that they are both empty and will treat them as equal. In other words, `MyClass.Equals()` is never called! If, on the other hand, `GetEnumerator().MoveNext()` returned true, then the value of `Current` would be compared (in your case, a hardcoded `null` value for each would also return true without actually calling `MyClass.Equals()`).

The PredicateComparer used when providing a lambda to `Using()` seems to skip this string/IEnumerable check which is why it fails as expected in your scenario. It's certainly a slightly inconsistent behaviour, though I'm not sure if it was intentional or not. Someone else on the @nunit/framework-team may know a bit more about any edge cases which led to that decision.

**Comment by Dimension4** [comment]
Interesting. Thanks for the detailed explanation!

**Comment by siprbaum** [comment]
@stevenaw :
> This is a bit of an interesting edge case you've found @Dimension4
> 
> NUnit does a lot of magic internally to help make comparisons easier, one of which is that if the objects being compared implement IEnumerable then NUnit will enumerate and compare the contained values _unless the type is `string`_ . With your code sample, what that means is that NUnit will not apply the custom comparer immediately but will instead call `MyClass.GetEnumerator().MoveNext()` on `a` and `b`. 

But isn't this handling the problem? E.g. why does NUnit try to do the IEnumerable when the class itself implements `IEquatable`?
There might be reason why the `IEquatable<T>.Equals(T)` doesn't take the `IEnumerable` part into consideration when making the decision if the two instances are equal,  although I think it indicates a code smell when they don't

**Comment by manfred-brands** [comment]
I agree with @siprbaum. NUnit should first check if a type implements `IEquatable` before checking for `IEnumerable` or more specific it should check if it has a comparer for the actual instance type, specified by the user or implemented by the class.

Is does get problematic when specifying a non-typed Comparer on a class that implements non-typed `IEnumerable`. Is that comparer indicated for the collection or for the members of the collection. NUnit assumes the latter.

In the first case where the comparer is generic `IEqualityComparer` it is not deterministic. But as the `IEnumerable` if also on object, the comparer matches the enumeration.

The second example where the lambda explicit mentions the "collections class type, NUnit should not enumerate. And it doesn't.

Similar if the comparer would implement `IEqualityComparer<MyClass>`
I tried the latter and that behaves as I hoped. 

The differences is that the latter uses NUnit's Generic version of the `EqualityAdapter` which checks if the type matches the comparer and because it does, it will call that comparer.
In the  non-generic `object` version of the `EqualityAdapter` it only uses the comparer of the instance is non-enumerable.

So if you want to use specific type comparers make sure the comparer is typed.

**Comment by stevenaw** [comment]
Revisiting this, I am inclined to agree and close as not a bug.
[The documentation](https://docs.nunit.org/articles/nunit/writing-tests/constraints/EqualConstraint.html#comparing-arrays-collections-and-ienumerables) suggest using the `AsCollection` equality modifier in this case, where both `IEnumerable` and `IEquatable<>` are implemented and collection semantics are desired.

When I do this on the sample repro the test still does not fail as expected, however this is because both `IEnumerable`s are being treated as empty since `MoveNext()` in the custom enumerator returns false. NUnit defines empty collections as equal. Changing this to return `true` the first time it is called and changing `Current` to return a unique value per instance instead of `null` will in turn cause the comparer to be used (see below)

I think the null vs customer comparer discussion is a separate issue which we're currently discussing in https://github.com/nunit/nunit/issues/3842

```diff
[TestFixture]
        public class TestClass
        {
            [Test]
            public void TestComparer()
            {
                var a = new MyClass();
                var b = new MyClass();

-                // This assertion fails, as expected
-                Assert.That(a, Is.EqualTo(b).Using(new MyComparer()));
+                // This assertion now passes
+                Assert.That(a, Is.EqualTo(b).AsCollection.Using(new MyComparer()));
            }

            [Test]
            public void TestLambda()
            {
                var a = new MyClass();
                var b = new MyClass();

                // This assertion fails, as expected
                Assert.That(a, Is.EqualTo(b).Using<MyClass>((x, y) => false));
            }
        }

        class MyClass : IEnumerable, IEquatable<MyClass>
        {
            class MyEnumerator : IEnumerator
            {
+                private int _moveCount = 0;

                public bool MoveNext()
                {
-                     return false;
+                    return (_moveCount++ == 0);
                }

                public void Reset()
                {
                }

-                public object Current => null;
+                public object Current => this;
            }

            IEnumerator IEnumerable.GetEnumerator()
            {
                return new MyEnumerator();
            }

            public bool Equals(MyClass other)
            {
                return true;
            }
        }

        class MyComparer : IEqualityComparer
        {
            bool IEqualityComparer.Equals(object? x, object? y)
            {
                return false;
            }

            public int GetHashCode(object obj)
            {
                throw new NotImplementedException();
            }
        }
```
