### ISSUE TITLE
Nunit v3 - Get number of tests of specific category

### ISSUE THREAD

**Issue by NadeemBader** [nunit/nunit#3722]
Hi
Is that possible to get the number of tests that belongs to specific category using nunit3-console.exe? 
if so, can you please assist?
Best Regards,
Nadeem Bader

**Comment by rprouse** [comment]
I don't have time to test this right now, but you could use the explore option and parse the resulting XML. There may be an easier option like combining explore with `--where`

**Comment by mikkelbu** [comment]
Similar suggestion as @rprouse. You can do something like this 
```
.\nunit3-console.exe --explore="tests.txt;format=cases" --where "cat == DataBase" C:\src\NUnit\nunit.nunit\bin\Release\net35\nunit.testdata.dll
```

The `--explore` option only discovers the tests, it does not run them. We specify both an output file and the option `cases` to list the tests line-by-line (otherwise it is formatted as XML). The `--where` option tages the tests with the category `DataBase` and the last part is the specification of the test assembly. Note that if you just want the tests to be output you can use 
```
.\nunit3-console.exe --explore --where "cat == DataBase" C:\src\NUnit\nunit.nunit\bin\Release\net35\nunit.testdata.dll
```

**Comment by NadeemBader** [comment]
Hi
Thank you for your inputs.
Assuming I already run the command line and the test started, can I get the number of tests in that selected category\ies in OneTimeSetup method?
Best Regards,
Nadeem Bader

**Comment by NadeemBader** [comment]
Hi
Thank you for your inputs.
Assuming I already run the command line and the test started:

* Can I get the number of tests in that selected category\ies in OneTimeSetup method?
* Can I know the index of the current running test? For example, in case this is the first test running after running the nunit3-console.exe, then the index is 0, etc...


Best Regards,
Nadeem Bader

**Comment by rprouse** [comment]
- I can't think of a way to get the number of tests in a category in the OneTimeSetup.
- I also don't know of any way to know the index of the currently running test without managing it yourself somehow. This isn't something we would build into NUnit because it doesn't make sense when running parallel tests where multiple tests could be running at the same time.

**Comment by NadeemBader** [comment]
Ok, thanks
Is there anyway from (In c# code) to know if the tests are running from nunit3-console.exe or VS Test Explorer?
I mean, to know which tool triggered the tests (nunit3-console.exe or VS Test Explorer)?

**Comment by mikkelbu** [comment]
I don't think that there is a direct way to do this. Some Googling gave the hacky approach to call `AppDomain.CurrentDomain.GetAssemblies()` and then scan for certain MS assemblies, like `Microsoft.TestPlatform....` or `Microsoft.VisualStudio.TestPlatform...`). I don't think that these will appear when test are run from the nunit3-console.exe, but I have not verified this.
