### ISSUE TITLE
Mark Assert.IsNotNull param with NotNull attribute

### ISSUE THREAD

**Issue by pepone** [nunit/nunit#3808]
https://github.com/nunit/nunit/blob/af52b9a3b93edb5e54442ed6121b718532202a8f/src/NUnitFramework/framework/Assert.Conditions.cs#L219

```
public static void IsNotNull([NotNull]object? anObject, string? message, params object?[]? args)
```

I think this will be helpful as you don't need to use `!` after checking `IsNotNull`

Similarlly IsTrue/IsFalse can also take advantage of `DoesNotReturnIf` attribute

**Comment by jnm2** [comment]
The lines just above that one explain why we didn't add `NotNull`. This method can return and continue executing the test when the value is null, due to the Multiple Asserts feature.

https://github.com/nunit/nunit/blob/af52b9a3b93edb5e54442ed6121b718532202a8f/src/NUnitFramework/framework/Assert.Conditions.cs#L212-L215

If you install the NUnit.Analyzers package, we suppress the warnings for you when you're not inside a Multiple Asserts block so that you don't have to use `!`.

Existing discussion: https://github.com/nunit/nunit/issues/3717

**Comment by pepone** [comment]
thanks @jnm2 I didn't knew about Assert.Multiple
