### ISSUE TITLE
Exceptions in async EventHandlers are not counted as failures

### ISSUE THREAD

**Issue by trampster** [nunit/nunit#3816]
Exceptions that occur in an async method even if it doesn't await doesn't fail the test.

Consider the following code:

```
   public class AsyncEventTests
   {
      public event EventHandler MyEvent;
      bool _shouldAwait = false;

      [Test]
      public void TestAsyncEvent()
      {
         MyEvent += Handler;
         MyEvent?.Invoke(this, EventArgs.Empty);
      }

      async void Handler(object sender, EventArgs args)
      {
         if(!_shouldAwait)
         {
            // NOTE: this is unreachable so this handler never awaits
            await Task.Delay(100);
         }
         throw new Exception("async Handler failed");
      }
   }
```

If you run this from Visual Studio Test Explorer the tests passes and no exception/error is reported, However tests after this tests may not run (show as light green)

If you debug the test then it doesn't stop on the Exception line.

If you run this test using 'dotnet test' then an exception message is printed to standard error (but only if you test run is long enough for it to get printed), but the test isn't reported as a failure and  'dotnet test' doesn't return a failure exit code, this causes our CI to think the test run was successful.
```
Microsoft (R) Test Execution Command Line Tool Version 16.9.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: 4 ms - AyncTests.dll (net5.0)
```

The result of this is very bad, We simply don't notice that lots of our tests are not running / are failing

I am using .net 5.0

Nunit Versions are as follows:
```
<PackageReference Include="NUnit" Version="3.13.1" />
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.0.1" />
<PackageReference Include="NUnit3TestAdapter" Version="3.17.0" />
```

Although async void methods are bad, this example is in line with microsoft guidlines which is to avoid async void unless it is an event handler, This is an event handler and this usage scenario is very common in most .net codebases I have seen.

**Comment by rprouse** [comment]
Microsoft warns against `async void` methods because they are "Fire and Forget", as in, the calling code cannot catch the exceptions being thrown.

> With async void methods, there is no Task object, so any exceptions thrown out of an async void method will be raised directly on the SynchronizationContext that was active when the async void method started. [1](https://docs.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming#avoid-async-void)

We could catch the exceptions in `AppDomain.UnhandledException`, but we would have no way to know which test they came from.

As you state, that article goes on to say that they are useful for events, but that you should design them with testability in mind,

>It’s clear that async void methods have several disadvantages compared to async Task methods, but they’re quite useful in one particular case: asynchronous event handlers. The differences in semantics make sense for asynchronous event handlers. They raise their exceptions directly on the SynchronizationContext, which is similar to how synchronous event handlers behave. Synchronous event handlers are usually private, so they can’t be composed or directly tested. An approach I like to take is to minimize the code in my asynchronous event handler—for example, have it await an async Task method that contains the actual logic. The following code illustrates this approach, using async void methods for event handlers without sacrificing testability:

The code in that article is a good way to make the event handlers testable;

```csharp
private async void button1_Click(object sender, EventArgs e)
{
  await Button1ClickAsync();
}
public async Task Button1ClickAsync()
{
  // Do asynchronous work.
  await Task.Delay(1000);
}
```

My practice is to never let exceptions escape `async void` event handlers. I'm curious, how are you handling those exceptions in production? Do you handle them in the `SynchronizationContext`?

I am going to mark this as a question. This is not something we will be changing in NUnit, but we can help you make those methods testable.

**Comment by trampster** [comment]
In production we are happy to let exceptions that occur in take down our app. (which is what happens)

However we would like to know about them in the unit tests.

**Comment by trampster** [comment]
As a work around we have made our own AsyncEvent that can be awaited

   public delegate Task AsyncEventHandler();

```
   public class AsyncEvent
   {
      readonly List<AsyncEventHandler> _handlers = new List<AsyncEventHandler>();
      public void Subscribe(AsyncEventHandler handler) => _handlers.Add(handler);
      public void Unsubscribe(AsyncEventHandler handler) => _handlers.Remove(handler);

      public async Task RaiseAsync()
      {
         foreach(var handler in _handlers)
         {
            await handler();
         }
      }

      public async void Raise()
      {
         foreach (var handler in _handlers)
         {
            await handler();
         }
      }
   }
}
```

**Comment by jnm2** [comment]
@trampster Can you think of a way NUnit could find out about these exceptions being thrown and report the problem? Keep in mind that NUnit may have already written out complete success results for each test by the time an exception is thrown from outside the bounds of an NUnit test this way. This is only one of many ways that code invoked by NUnit can return to NUnit after having scheduled an exception to be thrown outside the bounds of NUnit. Another example is if you start a new thread and delay and then throw an exception.

I used to do exactly what you're doing, but the inherent testing limitations missed so much that I created (and recommend) https://github.com/Techsola/AmbientTasks instead of async void. (I tried [
AsyncVoidVerificationScope](https://gist.github.com/jnm2/9c2b5d74d144852718e5b788d22b7fc0) first but it's still kinda gross because it makes all tests that use it nonparallelizable.)

**Comment by rprouse** [comment]
Closing as a dormant/answered question.
