### ISSUE TITLE
Make ArgDisplayNames public

### ISSUE THREAD

**Issue by Sergey-Terekhin** [nunit/nunit#3822]
Hello!

We have scenario where we want to enrich same `TestCaseData` with different additional arguments to use it in different test cases. The main problems is that we can't get access to its description in original test data, because `ArgDisplayNames` property is internal

 For example, we have two tests like:
```c#
[Test, TestCaseSource(nameof(GetTestModels))]
public void Test1(SomeModel model){}

[Test, TestCaseSource(nameof(GetTestModels2))]
public void Test2(SomeModel model, SomeModel2 model2){}

private static IEnumerable<TestCaseData> GetTestModels()
{
    yield return new TestCaseData(new SomeModel()).SetArgDisplayNames("Some model description");
}

private static IEnumerable<TestCaseData> GetTestModels2()
{
    var items = GetTestModels();
    foreach (var item in items)
    {
         var model = (SomeModel)item.Arguments[0];
         var modelDescription = //here we want to reuse description of the model from test data, but we can't without reflection

         yield return new TestCaseData(model, new SomeModel2()).SetArgDisplayNames(modelDescription , "Model 2 description");
    }
}

```

**Comment by rprouse** [comment]
You could just add a third method that returns a tuple to create the `SomeModel`.

```c#
public static IEnumerable<TestCaseData> GetTestModels() =>
    new GetTestModelsInternal().Select(i => new TestCaseData(i.model).SetArgDisplayNames(i.description));

public static IEnumerable<TestCaseData> GetTestModels2()
{
    var items = GetTestModelsInternal();
    foreach (var item in items)
    {
         var model = item.model;
         var modelDescription = item.description;

         yield return new TestCaseData(model, new SomeModel2()).SetArgDisplayNames(modelDescription , "Model 2 description");
    }
}

private static IEnumerable<(SomeModel model, string description)> GetTestModelsInternal()
{
    yield return new (new SomeModel(), "Some model description");
}
```

I am marking as a question and an idea because I'm not sure we will make this change and I think this solves your problem.

**Comment by Sergey-Terekhin** [comment]
Thank you. I'll use it :)

**Comment by rprouse** [comment]
Closing as a dormant/answered question.

**Comment by paulirwin** [comment]
I'd like to request that this issue be reopened and adopted.

At the Lucene.NET project, we provide a TestFramework library that allows users to build upon our test suite for things like building their own randomized search tests. We cannot know in advance the TestFixtureData arg display names like the earlier example listed here, because it is not specified in our code (it's in our users' code). We are currently having to resort to using reflection to get the ArgDisplayNames value. It also doesn't make much sense for us to have to reimplement TestFixtureData/TestParameters and have a fully custom solution just to accomplish this.

Making either the `TestParameters.ArgDisplayNames` property getter public (can leave setter internal, if desired), or adding a `GetArgDisplayNames` method to `TestFixtureData` (at a minimum; `TestCaseData` we don't currently use for this functionality but it should be updated too if so) would prevent us from having to resort to brittle reflection. 

I'd be happy to PR this if the team is open to it. Thanks!

**Comment by OsirisTerje** [comment]
I can't see why not, it is a get'er.   @manfred-brands @stevenaw Any concerns ?

It should be done in the `TestParameters` class, and as you say,  get'er public, set stay internal..     

PS:  Actually, not sure why the setter can't be protected, as that is the only use - from the  `SetArgDisplayName ` methods in derived classes.  Now some tests are using it, but those can use the  `SetArgDisplayName` instead.

A PR is welcome!

**Comment by stevenaw** [comment]
Agreed, I think this is a great idea as it seems we now have a use case to add it. Thanks for the idea @paulirwin a PR would absolutely be welcome.
