### ISSUE TITLE
dynamic parameterization

### ISSUE THREAD

**Issue by dstaraster-pw** [nunit/nunit#3873]
I found a draft spec for dynamic parameterization at https://docs.nunit.org/articles/nunit/technical-notes/nunit-internals/specs/Dynamic-Test-Cases-Spec.html. Is there a timeline for implementation? Thanks!

**Comment by mikkelbu** [comment]
Hi @dstaraster-pw 
I don't know when the draft spec was written (as I don't know if it existed before being added to the wiki and later to the new documentation site), but I think this is quite old - at least it has been discussed since 2013 - see e.g. nunit#7, so there is no timeline for this implementation (and at this time I - and other people - have only little time to work on NUnit).

I'm closing this issue as we already have several issue regarding dynamic loading of tests, but please note that we will still see additional comments in this issue.
