### ISSUE TITLE
nunit.framework.dll is built in debug mode

### ISSUE THREAD

**Issue by ghelyar** [nunit/nunit#3878]
I'm not sure if this is intentional for some reason, but I used https://github.com/bruno-garcia/unoptimized-assembly-detector and found that nunit.framework.dll is built in the debug configuration for [NUnit 3.13.2](https://www.nuget.org/packages/NUnit/3.13.2)

Just raising this in case it's not intentional.

**Comment by mikkelbu** [comment]
I just took a loot at https://github.com/bruno-garcia/unoptimized-assembly-detector and it checks whether assemblies are compiled without the `-optimized` flag. For NUnit this is intentional - it was introduced in #3464.

I'm closing this issue as answered, but please note that we will still see additional comments.
