### ISSUE TITLE
Is there an option to prevent NUnitLite from swallowing exceptions?

### ISSUE THREAD

**Issue by myocytebd** [nunit/nunit#3907]
version: nuget 3.13.2  
NUnitLite by default swallows exception, and I could not find an option to disable this behavior.  
Option "--stoponerror" does not help, because runner stops after test ends and exception site is lost.
For example:
```
	[TestFixture]
	class Foo {
		[Test]
		public void bar() {
			throw new ArgumentException("bar");
		}
	}
```
Expected result:  
There is an option to disable exception catching, so that exception site is kept untouched, and debugger can exactly stop on the exception site.  
Actual result:  
NUnitLite swallows exceptions.  

BTW "--stoponerror" does not work as I expected, either.  
I expected the behavior to be that runner immediately crash itself at assertion failure, instead of let current test end and lost call site.

**Comment by mikkelbu** [comment]
Hi @myocytebd 

The `--stoponerror` flag specifies that the console runner (or the adapter) should stop after the first failing test or error (rather than the normal flow which is to continue with the remaining tests and then at the end report on the failures and errors). 

Currently, it is not possible change this behaviour via a setting.

What if you start the nunitlite process with a debugger attached and have enabled "Break On All Exceptions" turned on in visual studio (if you are debugging from VS). Then I guess it would stop at the exception.

**Comment by mikkelbu** [comment]
Closing this issue, due to inactivity. Note that we will still see additional comments on this issue.
