### ISSUE TITLE
Test run will not start when using [SetUpFixture] as base class

### ISSUE THREAD

**Issue by RenePeuser** [nunit/nunit#3937]
What we want to test:
* We want to run Integrationtest with an AspNet Core API - And we will not start and tear down our API every test scenario - Just start once run all test then tear down
* Another aspect would be nice to avoid use static properties in the class which use the [SetUpFixture]
* Would be nice to derive from the a base class which use [SetUpFixture] + [OneTimeSetUp]

What is working
* Like in your description a standalone class for "OneTimeSetup" works - As long you dont derive from this class

What is not working (or maybe not expected behavior)
[Sample](https://softwaresolutions-my.sharepoint.com/:i:/g/personal/rene_peuser_softwaresolutions_onmicrosoft_com/ERKfKMhVADREiqo66UeBZl4B2OMPA7ZzR5mHEJLizUsxZQ?e=m3bxuS)

```csharp
[SetUpFixture]
public class TestEnvironment
{
    [OneTimeSetUp]
    public void Setup()
    {
        Console.WriteLine(nameof(Setup));
    }

    [OneTimeTearDown]
    public void Teardown()
    {
        Console.WriteLine(nameof(Teardown));
    }
}
```

Current behavior:
* The test runner will not run the tests (sample below)*

```csharp
[SetUpFixture]
public abstract class TestEnvironment
{
    protected ApiEnvironment ApiEnvironment {get; private set;}

    [OneTimeSetUp]
    public void Setup()
    {
        Console.WriteLine(nameof(Setup));
        // ApiEnvironment = new ApiEnvironment()....
    }

    [OneTimeTearDown]
    public void Teardown()
    {
        Console.WriteLine(nameof(Teardown));
        // ApiEnvironment?.Dispose();
    }
}

public class Test_A : TestEnvironment
{
    [Test]
    public void Test_1()
    {
        Assert.Pass();
        // APIEnvironemt.Client....
    }

    [Test]
    public void Test_2()
    {
        Assert.Pass();
        // APIEnvironemt.Client....
    }
}
```

**Comment by RenePeuser** [comment]
Hi something new about this issue ?

**Comment by CharliePoole** [comment]
FWIW a SetUpFixture was never intended to be used as a base class. In the past year I have noticed several people doing that so I updated the docs for that purpose.

**Comment by denis-sklyarov** [comment]
I develop integrated tests and i need to execute some code exactly after all test cases. Is there are wa y to do this using nunit 3 ?

I tried to put separate class qith SetupFixture but it does not work with filters

**Comment by stevenaw** [comment]
@CharliePoole You mentioned having updated the documentation, but I admit I'm having a hard time finding where we document it. At least nothing on https://docs.nunit.org/articles/nunit/writing-tests/attributes/setupfixture.html jumps out to me. Do you recall where it was?

I think one of the other confusing things here is that, unlike some other attributes in the framework, `SetupFixture` is actually decorated with an `AttributeUsage` of `Inherited = true`. We should probably change this.

**Comment by CharliePoole** [comment]
@stevenaw I'll try to figure out what happened to that documentation change. I remember that I submitted a one-line note added to that page but I don't know what happened to it. If I have to redo it I'll try a straight PR  rather than using the web update feature. I seem to always run into problems with that.

Regarding `AttributeUsage`, I don't think it's related to this problem but I agree we could probably change it.

**Comment by stevenaw** [comment]
Thanks @CharliePoole ! Agreed, it won't "fix" or change anything here, but I noticed that the `AttributeUsage` props are sometimes mentioned in issues as a way some infer how the attributes are intended to be used. I'm hoping changing it could better document intent. I'll make another issue for that though :)

**Comment by CharliePoole** [comment]
Right, many folks are not aware that `AttributeUsage` with `Inherited=true` merely indicates whether the attribute is intended to be "seen" when looking at derived classes. Whether or not a class "inherits" test behavior from a base class is a function of NUnit internals, i.e. what calls NUnit makes to find the attributes. For example, TestFixtures "inherit" setups and teardowns because NUnit actually examines the chain of base classes, allowing it to control the _order_ in which setups and teardowns are  run.

**Comment by chipplyman** [comment]
I'm still not seeing anything related to inheritance or base class on the SetUpFixture documentation page FWIW

**Comment by CharliePoole** [comment]
I made a change to the docs way back and submitted it to the docs project. Perhaps someone with access can look.

**Comment by AndrewParkerTechnicalTester** [comment]
I've come through to this issue from a bing search so yes - I'm aware I'm probably in the wrong place.
My issue is incidental to the issue of inheritance. I already know I can't have a TestFixture inherit from a SetUpFixture without the OneTimeSetUp/OneTimeTearDown running twice, which isn't what I want. Hence, the lack of ability to share data between the SetUpFixture and TestFixture is frustrating. It basically means that there is no way I can access test configuration properties from the SetUpFixture and I'm not aware that they can be passed in via any method, particularly as the value of one or more of the properties will change from test to test.
Fortunately, I can think of a workaround and that is to write all the needed data into my test results, which comprise multiple static members in a static class but it's a pain to have to do this.
Is there any other way of sharing data between the two?

**Comment by manfred-brands** [comment]
@AndrewParkerTechnicalTester 

I had a similar need and used a pattern where I used a static SetUpFixture class that initialises a DB and sets static properties. The actual TestFixture then can use those properties.

Or you can have a common base class with static properties. The SetupFixture derives from it to sets them and the TestFixture uses them.

**Comment by AndrewParkerTechnicalTester** [comment]
HI manfred-brands, thanks very much for your reply. 
The reason that wouldn't work for me is that I have various values that are tied to the tests themselves and that change on a fixture or namespace hierarchy basis; hence, the only way I could get at them would be via inheritance or via some other data sharing mechanism. 
For now, I'm incorporating the values in the in-memory results, which are static, so that the report will be generated with the correct values when called via the SetUpFixture's OneTimeTearDown. 
I guess it's time I learned xUnit :)
