### ISSUE TITLE
Switch default branch to main

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#3981]
https://github.com/github/renaming for info

**Comment by stevenaw** [comment]
Thanks for opening this 👍

**Comment by stevenaw** [comment]
@rprouse This is assigned to you but would you mind if someone else picked this up?

**Comment by rprouse** [comment]
Take it 😁

**Comment by stevenaw** [comment]
Thanks!

**Comment by stevenaw** [comment]
Update as I see this is in next milestone.

I've tried peeking at github settings for this. I think we need to do this through the repo settings in order to get the best contributor experience with various PR and CLI messaging about the new branch name, however I don't think I have the permissions to make the change. Fortunately, I think we've done most of the pre-work for the CI changes.

@OsirisTerje   I'm not 100% certain, but I am wondering if you have to be the one to click these buttons. Not sure if this changes our timing as I know you are pretty busy yourself.

**Comment by OsirisTerje** [comment]
@stevenaw Have renamed the branch now.  Also added a PR to fix up some files that mentioned "master".
