### ISSUE TITLE
Store Timeout interval as a `TimeSpan` instead of an `int`

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit#4138]
Something I noticed today is that we store timeout intervals as an `int`. Newer .NET framework guidelines suggest instead using `TimeSpan` to disambiguate the represented time interval (seconds vs milliseconds). It would be relatively trivial to update the private member in `TimeoutAttribute` for this: https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Attributes/TimeoutAttribute.cs#L19

But nunit also publicly exposes this on `TestExecutionContext`:
https://github.com/nunit/nunit/blob/b34eba3ac1aa6957157857bddd116256c634afab/src/NUnitFramework/framework/Internal/TestExecutionContext.cs#L325

This would be a breaking change, though in practice I don't see many external places it's used: https://grep.app/search?q=TestCaseTimeout&filter[lang][0]=C%23
- NUnit itself
- Point-in-time copy of nunit stored in xamarin source
- TestCentric GUI (as logged output)

@nunit/framework-team @CharliePoole Thoughts?

**Comment by CharliePoole** [comment]
Of course, it's in the nature of a public API that we __don't__ know who is using it or how. :-)

In the specific case of the TC GUI, the framework is only referenced by its tests, not by the GUI itself.

Since it is breaking, I assume you are referring to the 4.0 release. As folks know, I'm generally in favor of breaking things early in preparing a major release. By doing that, you get them out of the way and also get feedback from users of your dev, alpha and beta releases. However, Rob has indicated a desire to minimize breaking changes in the V4.0 framework API.

**Comment by stevenaw** [comment]
I'm starting to realize that a grep.app could only show a partial list of all open source references, let alone all references. I'm still curious about thoughts here, though. I agree it'd be good not to break things unnecessarily.

**Comment by CharliePoole** [comment]
I'd say that the largest use of NUnit is probably in private, corporate code bases.

**Comment by stevenaw** [comment]
Yes, somehow I'd forgotten that despite that in my day job we use and have extended nunit 😅

I'd like to reframe the question to focus on updating this to use `TimeSpan` internally while keeping `TestExecutionContext.TestCaseTimeout` publicly as an `int`.

**Comment by stevenaw** [comment]
It doesn't sound like there's much interest for this and my own opinion on it has changed a bit after my discussion with @CharliePoole  above. I'd like to close it as a wont do
