### ISSUE TITLE
CollectionAssert.Contains has misleading parameters and/or output

### ISSUE THREAD

**Issue by MaxAtoms** [nunit/nunit#4185]
For a while I have been wondering about the `CollectionAssert.Contains` method and its parameters.
Why is the `actual` parameter the one that is output as `expected`?

Am I just confused or is this kept because of broader implications or because it would introduce a breaking change?

```csharp
[Test]
public void Test1()
{
	var someTestResult = new[] { 1, 2, 3 };
	
	// Fine
	//CollectionAssert.AreEqual( expected: new [] { 1, 2 },  actual: someTestResult );
	
	// Misleading output / evaluation order
	CollectionAssert.Contains( collection: new [] { 1, 2 }, actual: someTestResult );
}
```

Result:

```
Expected: some item equal to < 1, 2, 3 >
  But was:  < 1, 2 >
```

Version:  NUnit 3.13.3

**Comment by manfred-brands** [comment]
`Contains` expects the _actual_ element in the _collection_.
So `Expected` is the _actual_ parameter and it shows the contents of the _collection_ at `But was`

Maybe it is clearer if using an element as the actual parameter instead of another collection:
```csharp
[Test]
public void ContainUsingCollectionAssert()
{
    CollectionAssert.Contains(collection: new[] { 1, 2 }, actual: 3);
}
```

The error message is then:
```
Expected: some item equal to 3
But was:  < 1, 2 >
```

It is much clearer if rewriting the test, replaing the `CollectionAssert`with one of the Assert constraints:
```csharp
[Test]
public void ContainUsingAssertThat()
{
    Assert.That(new[] { 1, 2 }, Does.Contain(3));
    Assert.That(new[] { 1, 2 }, Has.Member(3));

}
```

**Comment by stevenaw** [comment]
I think the confusing thing here is in the parameter naming. As @manfred-brands pointed out, the following output the same failure message:

```csharp
   CollectionAssert.Contains(collection: new[] { 1, 2 }, actual: 3);
   Assert.That(new[] { 1, 2 }, Does.Contain(3));
```

However the first receives `3` in a parameter named "actual" but the second receives `3` in a parameter named "expected". In both cases the `3` is output as the "expected" part of the failure message. In essence, I'd suggest that the second parameter in `Collection.Contains()` is misnamed and should actually be named `expected` as that's how it's treated.

```diff
public static class CollectionAssert
{
- public static void Contains (IEnumerable collection, Object actual);
+ public static void Contains (IEnumerable collection, Object expected);
}
```

My guess is that the original function was written to be consistent with the other "classic" assertion APIs each of which pass an`expected` value first and and `actual` value as the second parameter. The problem is that changing a parameter name now is a breaking change and so the opportunities to do it are few and far between without the risk of disrupting a user. Most uses of this likely don't pass it as a named parameter, but the chance of breaking _someone_ is still non-zero.

**Comment by stevenaw** [comment]
I'd consider this as a bug (misnamed parameter on `Collection.Contains()` and potentially other set-based assertions in that class, though I haven't tested their output). I know we'd like to minimize disruptive changes in the next major release, but I'd be curious to hear @rprouse 's thoughts on if this is worth it.

**Comment by rprouse** [comment]
Considering that most of the classic asserts date back to the NUnit 2 days and nobody has noticed AND that we consider the classic asserts as legacy I'm not sure it is worth risking the change. We could just note the discrepancy in the docs?

**Comment by stevenaw** [comment]
Thanks @rprouse appreciate your input here. I've created https://github.com/nunit/docs/issues/672 for the docs update.
