### ISSUE TITLE
Data driven tests using TestCaseSource attribute with >= 1840 iterations cannot be run without running every other test method in the suite

### ISSUE THREAD

**Issue by GaryMalk** [nunit/nunit#4189]
I'm doing data-intensive testing, with 16 test methods in a suite, run in Visual Studio 2022 in C#.  The tests depend on private static methods returning List\<TestCaseData\>, with the data consumed from CSV files.  Each method has anywhere from 400 to 10,000 test cases, so the total number of iterations in the suite is 31k.

I have noticed that there is a magic number 1840; if my test has fewer total iterations than that, then I can run just that test if desired.  If there are 1840 or more iterations, then when I select only that test or even only a specific iteration, it runs my entire suite of tests.  I can stop and restart, but with the same result.  If I have the time to wait for all 31k to run - which is hours - then on subsequent runs after that, I can run just the one specific test I wanted.  However, if I change my build configuration from "Test" to "QA", for example, to run in a different environment, the problem happens again.  And switching back will then have the same problem.

The only solutions I've found are breaking my CSV into separate files and editing my code between runs or creating duplicate test methods, or dumping the nunit framework entirely and using the old MS TestFramework DataSource attribute.

**Comment by mikkelbu** [comment]
Since you are running the tests in VS then the problem can be in several components:
* This repository the framework
* The NUnit Engine that is responsible for how and where the tests are run
* vstest - Visual Studio Test Platform that is the component you interact with in VS
* The NUnit Adapter that sits in between the NUnit Engine and vstest

When you run a single test in VS then VS sends a test filter that specifies the test to the adapter that then sends this filter to the engine (probably in another format). So I'm guessing that either the problem is in vstest or the adapter - that if the number of tests is too high, then they default to run all tests.

You can configure the NUnit adapter to dump XML files via DumpXmlTestDiscovery and DumpXmlTestResults in a .runsettings file - see https://docs.nunit.org/articles/vs-test-adapter/Tips-And-Tricks.html . That might highlight where the problem is.

CC: @OsirisTerje as he might know more about the limitations in vstest / nunit adapter

**Comment by OsirisTerje** [comment]
@GaryMalk Sorry for noticing this a "bit" late, I assume you have worked around this by now - or figured out the setting to change this ( :-) ) , but just for documentation:  The magic number is actually 2000, and is a runsetting named [AssemblySelectLimit](https://docs.nunit.org/articles/vs-test-adapter/Tips-And-Tricks.html#assemblyselectlimit) which has a default value of 2000.
