### ISSUE TITLE
Results for outer class are not reported in since version 3.13.2

### ISSUE THREAD

**Issue by estrizhok** [nunit/nunit#4298]
nunit.framework 3.13.2

I often write tests like this:

```
[TestFixture]
public abstract class Base {}

internal class OuterFixture : Base
{
  public class SomeInnerScenario : OuterFixture
  {
    [Test] public void Should_something() { }
  }

  public class AnotherInnerScenario : OuterFixture
  {
    [Test] public void Should_something_else() { }
  }

  /* helper methods */
}
```

And in R#/Rider this would be presented like this:

![image](https://user-images.githubusercontent.com/463971/220883268-86db5e30-84b0-427d-88b8-dd4a138652a0.png)
(ignore the planet glyphs - I am testing localization)

Note that the outer fixture does not have any tests in it, otherwise they would be duplicated in every inheritor, and I do want the inheritance so as to easily access helper methods local for the feature being tested.

Up until version 3.13.2 NUnit used to discover AND report OuterFixture when running tests. In the last two versions it *does* discover those classes, but does not report results for them anymore.

Now, I could, of course, in our runner fabricate those events, but guys... stop breaking things! (sorry, it's been many weird issues with NUnit lately)

**Comment by rprouse** [comment]
Have you tested this with the Visual Studio test runner and the NUnit test adapter? We don't have much visibility into how Rider discovers and runs NUnit tests so we don't know what they are relying on in the framework.

**Comment by mikkelbu** [comment]
@rprouse I think @estrizhok work on Resharper (at least that is how I read the report). I checked that the XML we expose have not changed the last couple of releases with the example above, but we might have changed the events we send out (I've not had time to look into this yet).

**Comment by OsirisTerje** [comment]
Visual Studio reports this as:
![image](https://user-images.githubusercontent.com/203432/231126665-af9f7bc2-cd0c-473b-88c1-3b92ca6de644.png)

Resharper and Rider reports this in their way like (difference marked)
![image](https://user-images.githubusercontent.com/203432/231126930-39706947-8fa6-4ae5-a6b5-2a44a118fdb4.png)
![image](https://user-images.githubusercontent.com/203432/231127046-2d4c167f-61c3-472a-b0d4-73227d457990.png)

Looking at the Xml being returned it does have a node for the OuterFixture
![image](https://user-images.githubusercontent.com/203432/231127208-a11da69b-2397-4ab3-8edd-83c186bfad2a.png)

But, it is 1)  Not a parent of the others and 2) Since it is not a parent it doesn't count up the number of child tests either.

To me this looks like a bug, possibly a regression:   

I've tried changing versions of NUnit and the adapter, but can't really find differences.  Also, the latest Visual studio has the RTD which, if enabled, is not making this easier, as it doesn't report this Outerfixture either.  But that is Test Explorer.
I've also tried adding a test to the OuterFixture, it then appears but is still a separate sibling node instead of a parent node (suite).

So the XML doesn't in any case look correct as it is. 

Repro is here:  https://github.com/nunit/nunit.issues/tree/main/Issue4298

**Comment by manfred-brands** [comment]
Note that `OuterFixture` itself doesn't have any tests on its own, so why should it be reported.
I would find that a strange scenario where a class has tests and then it has inner classes that depend on that class.
If I add a test to the `OuterFixture`, it will show up in `Test Explorer`:

![image](https://github.com/nunit/nunit/assets/8655218/653738f6-099b-4d97-9904-097c41e9d9e6)

I don't see anything wrong.

The difference is that NUnit reports inner tests as "Outer+Inner" at the same level as other "Outer" classes.
Whilst Resharper must analyze the name and create the Inner tests under Outer.

**Comment by manfred-brands** [comment]
I tried with Nunit 13.2.0 and the result is the same.

**Comment by OsirisTerje** [comment]
@estrizhok We can't repro any change from 3.12.0 to 4.1.
