### ISSUE TITLE
Allow to set `TestName` on `Test` attribute

### ISSUE THREAD

**Issue by wtorricos** [nunit/nunit#4309]
Currently we can se the `TestName` only in the `TestCase` attribute, we should be able to set the `TestName` in a `Test` as well.
This would allow to set better and more descriptive names for our tests, something like:

```dotnet
[Test(TestName = "A descriptive name with spaces")]
public void SimpleName()
{
    // body
}
```

**Comment by stevenaw** [comment]
@wtorricos Would the `Description` property suit your needs for this? If not, can you explain a little bit about how you would be looking to use a `TestName` with spaces and why `Description` wouldn't work for you?

**Comment by wtorricos** [comment]
Correct me if I'm wrong but it looks to me that `Description` is useful for documentation purposes but nothing else. On the other hand `TestName` is used to display the name of the test in IDEs, the console and other tools. 
I know it probably won't be a top priority, but I think it would be a nice enhancement to allow us to set the `TestName` to improve the readability of our test suits.

**Comment by OsirisTerje** [comment]
@wtorricos Changing the test name open a box of worms, called FQN.  The Microsoft runners depend on these names following the C# FQN, and also, if you have Real Time Discovery on in Visual Studio, they will not find a match.  Further, any "invalid" characters, spaces included, will not be valid and cause crashes.  See https://github.com/nunit/nunit3-vs-adapter/issues?q=is%3Aopen%20is%3Aissue%20project%3Anunit%2Fnunit3-vs-adapter%2F1

**Comment by wtorricos** [comment]
I though this one was going to be an easy one. Thank you for the update @OsirisTerje

**Comment by OsirisTerje** [comment]
On the other hand, could be interesting to add an option to the adapter to use Description instead of test names in the test explorer :-)  There is already a possibility to use either Name or FullName there, so could add Description too. I would not work with Real Time Discovery, and not work with the filters (you would still have to use the FQN testnames there), but it might work for display purposes.

**Comment by mr-russ** [comment]
I would argue against using Description in the Test Explorer.  We use Custom extensions to set the TestName on TestCaseSource items, to give descriptive names test that take complicated objects.
eg;  ```ThisTest(Person1, null, Activity7)```

What we discovered using the normal pattern is that there seem to be edge cases the runner did not like.  At least in VS2017.  If you had;  ```ThisTest(Person1, null ``` and forgot the closing parenthesis it would not show the test at all in the test explorer.

So possible, but I'm concerned about the danger level as it's caught us out a number of times.

**Comment by OsirisTerje** [comment]
Good point, but allowing Description would be an option, default has to be the current behavior.  That said, I am not sure it is workable, since it will require all tests to have descriptions. 
The issue we do have is the FQN name requirement from Test Explorer, so attempts with Description would only be experimental.  But, not sure it is worth the bother.

**Comment by OsirisTerje** [comment]
If there are a real need for setting test names (deliberately ignoring the warnings above), that can be done using TestCase, and TestCase can be used as a replacement for Test anyway (just don't add parameters), so there is no need to add this to the Test attribute.
