### ISSUE TITLE
MacOS build really slow for some tests

### ISSUE THREAD

**Issue by manfred-brands** [nunit/nunit#4381]
I had several PRs failing on MacOs with:

![image](https://user-images.githubusercontent.com/8655218/236128373-872038e8-8991-405b-8bb2-51c2d62fde77.png)

As the comment above the timeouts says the tests are much faster locally:

```
        // The following tests are each running in 14ms to 46ms on my machine. Based on that,
        // warn at 100ms and fail at 500ms
```

It this because the MacOS runner is underspec'd?

Should we increase the timeout, but then we won't detect deterioration under other OS?
Should we disable the test on MacOS as these are pure performance tests?

The warning time doesn't do much good as there is so much output of our test run that it will get lost and nobody notices.

**Comment by stevenaw** [comment]
I could be mistaken, but I think I recall this being added around the time of some performance regressions in the 3.11 or 3.12 time range.
The performance of these tests seems to vary but they'd been good for a while. I don't think this issue is related to any recent changes within nunit, so perhaps another external factor. I have long wondered if perhaps some noisy neighbour load contributes to these occasionally and temporarily take longer than expected.

I'm not sure the best approach here, but I'm curious to hear others thoughts. I like the idea of keeping the test in some form or another to warn against future issues.  I _think_ the macos machine tests mono though I haven't checked recently. Typically the big perf pitfall we hit here in the past was algorithmic, which would present regardless of OS or runtime.

It's also worth mentioning #4254 aims to make some fast-path optimizations which could help here too.

**Comment by manfred-brands** [comment]
Would this work: `[Platform(Exclude = "MACOSX", Reason = "MacOS github runner is very slow")]`
