### ISSUE TITLE
Unexpected SEHException using Nunit 2.6 version.

### ISSUE THREAD

**Issue by reddyashish** [nunit/nunit#4388]
Hello NUnit team,

We are using NUnit 2.6 to run the tests for Autodesk Dynamo: https://github.com/DynamoDS/Dynamo. We get the System.Runtime.InteropServices.SEHException exception with external error code -2147467259 for some random tests(which pass normally) and it is not consistent on every job.

Stacktrace:
SetUp : System.Exception : Could not load geometry library binaries from : 
<DynamoPath>\bin\AnyCPU\Release\libg_229_0_0 
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.SEHException: External component has thrown an exception.
— End of inner exception stack trace —
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at DynamoShapeManager.Utilities.PreloadAsmFromPath(String preloaderLocation, String asmLocation) in c:\WorkspaceDynamo\src\Tools\DynamoShapeManager\Utilities.cs:line 444 System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.external error code -2147467259

We are not able to find the cause of this yet and were wondering if you could shed some light on it. 
Has this issue been reported by any of the users? Thanks in advance. 

FYI: @mjkkirschner

**Comment by stevenaw** [comment]
@reddyashish While I'm not as familiar with the specifics of NUnit 2, I did find an old issue from the early NUnit 3 days detailing another SEHException case. In that case, and potentially in yours, the root cause of the issue laid not in NUnit but in something the system under test was doing within native code. Rob wrote some very detailed debugging notes at the time which may also help you, though it is possible you may have already tried some: https://github.com/nunit/nunit/issues/736#issuecomment-121230819

Based on your stack trace it looks like you might be trying to load an assembly into memory from a path on the filesystem and then invoking a method from it via reflection. Is it possible that it might be picking up an unexpectedly different version of the assembly, or that a different version of the assembly with the same assembly identity may already be loaded?

If either of those are the cause then you may also have luck by loading the target assembly via `Assembly.Load` instead of `Assembly.LoadFrom` as `Assembly.LoadFrom` has a few edge cases which result in its use being discouraged (https://learn.microsoft.com/en-us/dotnet/api/system.reflection.assembly.loadfrom?view=netframework-3.5#system-reflection-assembly-loadfrom(system-string))

**Comment by manfred-brands** [comment]
The Autodesk libraries have issues with cleanup. When we were using if for file conversions we could only use it one. It required use to use an separate process to do the conversion.
Not sure if this is the problem you're seeing.
