### ISSUE TITLE
Automatic selection of Test Engine to use

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#440]
The design of NUnit 3.0 includes the notion that the TestEngine should be loadable without a direct reference and without the runner knowing where it is located. Runners link with the nunit.engine.api assembly, which is distributed with them, and the api assembly will follow a set of rules to select the engine to be located. This issue covers both designing those rules and implementing them.

Considerations:
* What we do must work on all OS platforms we support.
* It must work under .NET 2.0 and higher.
* It doesn't have to work on devices or under Silverlight, since the engine is not used in those cases.
* It should allow flexibility of installation.
* It should allow for multiple engine versions being present, even though we will try to encourage most users to replace the engine on upgrades.
* Features of an upgraded engine should be immediately available to any runner using the api.
* It may be desireable to add an option to the api specifying the minimum engine version needed.
* Once we decide on our addin platform, it may be possible to combine some of the code for finding the engine with the code for locating addins.

**Comment by rprouse** [comment]
From high level overview email by @CharliePoole for reference,

>Runners are supposed to be able to use the best version of the TestEngine that is installed on a system without knowing where they are located. The nunit.engine.api assembly, which is referenced by runners, should locate the engine, instantiate it and return an interface to the runner.

**Comment by rprouse** [comment]
Capturing email chain between @CharliePoole  and myself,

From @CharliePoole 

The intent in the design of NUnit 3.0 is that the engine api assembly
will remain unchanged - or at least changed very infrequently - and
that it will find and load the engine, wherever it is installed. I
think if this as the true heart of the NUnit 3.0 architecture.

This approach is only mildly useful to NUnit itself, but very
important for third party developers. They can create runners that
will work no matter what engine is installed and will gain new
function automatically if the engine is updated.

Easy to say. Harder to implement. Right now the engine must be located
in the application base of the runner or installed in the GAC. As far
as I know, we won't find it in any other location.

We need to design the specific method by which the EngineActivator
class in the API will find and load instances of the engine. My
thinking is that the first place it should look is in the appbase and
the last is in the GAC. In between, it can look at the registry or at
something in the NUnit settings file - maybe both. We could also
consider using the runner config file.

I'm thinking you could first test the limits of what now works, try
out a few rough approaches, come up with a spec for how it should work
and finally implement it.

**Comment by rprouse** [comment]
Further email between @CharliePoole and myself,

> I think I understand the vision behind this, although I wonder how practical
> it is in the real world. If I was writing a 3rd party runner, I would
> include all of NUnit with my runner because I would not want to rely on the
> user having installed the engine. You state that the first place we should
> look is in the appbase, so 3rd party vendors will never get an engine other
> than the one they ship.

Hmmm... and yet Jetbrains and (AFAIK) Jamie Cansdale's app don't do that.

>
> If we reverse the search order, then I think it would be useful. My initial
> thoughts are,
>
> Check API version that the current runner is using.

OK... bearing in mind that I have hopes that we won't change the API version
for a long time.

> Check GAC and/or registry and/or install locations - find the newest engine
> that is compatible with the API version

Good. That means we probably need some optional arg or args to
TestEngineActivator.CreateInstance.

> If no compatible engine found, fall back on the engine shipped with the
> runner in AppBase

Hmmm... maybe we could have a policy setting of some kind, so that
the user can decide what to check first. It seems odd to me that we
would not use the engine that is explicitly put in the appbase for us.

I guess it really depends on what third-party folks really want to do.
In the current situation, they have to write their own code to find all
the installed engines and pick one. If we provide a standard mechanism,
maybe that will motivate them to change what they do.

I think that after we refine this a bit and you start working on it, we
should touch bases with the third parties.

> Some of the options for search locations are;
>
> GAC
>
> This has the advantage that it is a well known location that is easy to
> install to and to load from. It requires signing and versioning,
> Disadvantage is that I don't think mono on linux/mac has a concept of a GAC,
> do they? It is also difficult to probe for the newest compatible version and
> iterate over versions. Requires admin to install.

In the Gac, you get the version you ask for, so I guess you would need a list
of known versions and just keep asking till you got one.

Mono has a GAC, but there are some seriious differences. We would need to
experiment to see if side by side versions are supported. Ultimately, we may
need to follow a whole different search sequence on Linux, which is OK.

Up to now, we haven't used the GAC for 3.0. For 2.x, we used it a long time
ago but stopped due to some old Windows issues. We do "guarantee" that
NUnit will work if the assemblies are stored in the GAC.

Admin access for installation may be a problem. If the GAC is not a key part
of our plans for installation, then I think we could just deal with it
if we find it
but not provide any way to put it there.

> Registry
>
> It would be easy for our installer to add the install location to the
> registry. Can point to multiple engines and easy to work with. We could work
> with non-admin installs. Not available on any platform but Windows.
>
> Configuration File
>
> I don't see this as terribly useful. It points at a specific location, so
> does not give us the advantage of supporting newer versions. It could be
> useful for pointing at a non-appbase directory. Did you have other ideas
> here?

I'm not in love with it either. Just added it for completeness.

> AppBase
>
> Obviously :)
>
> If this is mainly a feature for Windows 3rdParty runners which I would guess
> are the majority, then I think I would prefer the registry to the GAC. We
> can have keys for every version of the engine that is installed and can
> easily iterate through them to find the most appropriate. Based on this, I
> would ignore the GAC and probe in the following order, Registry -> Config
> File -> App Base.
>
> Am I thinking along the same lines as you? If not, where I am deviating?
>

You skipped the NUnit Settings file, which seemed to me to have more promise
than either the registry or the config file. The advantage of it is
that we control
it completely, so it will work on all platforms. However, in writing
this, I realized
it has a fatal flaw... see next paragraph!

Reading the NUnit settings file is curently a function of the engine. So we need
the engine loaded to read the config file so we can load the engine! I see a few
possible answers here:

1. Put the info in some other XML or Text file that's easy to read and is in a
well-known location - probably right next to the Settings file.

2. Move all or part of the code for reading the settings file into the
api assembly.

3. Read the settings file right in EngineActivator on an adhoc basis.

I do like the idea that there would be some dedicated place of our own to track
where the engine is installed. Now that I think about it, it might be
easiest if it were
a simple file, separate from the settings, so we could update it on
install or on
first run.

Finally, there is a possibility that mono-addins will give us some way
to deal with
this. I'm starting to experiment now, but I wanted to give you a head
start on this
task at the same time.

**Comment by rprouse** [comment]
@CharliePoole, back to one of your points,

>> I think I understand the vision behind this, although I wonder how practical
>> it is in the real world. If I was writing a 3rd party runner, I would
>> include all of NUnit with my runner because I would not want to rely on the
>> user having installed the engine. You state that the first place we should
>> look is in the appbase, so 3rd party vendors will never get an engine other
>> than the one they ship.

> Hmmm... and yet Jetbrains and (AFAIK) Jamie Cansdale's app don't do that.

I just checked Resharper and TestDriven.NET, both include the framework, core, etc. In fact, TestDriven.NET actually includes NUnit 2.2, 2.4, 2.5 and 2.6.

I expect that they will continue to do the same thing with NUnit 3.0, so we will need to decide if we want to change the search order for loading the engine so that 3rd Party Runners get access to the newest engine if it is available. I would like to get some feedback on this, so I would like to contact the developers of a few of the 3rd Party runners. 

From our point of view, using the latest engine is what we want, but the developers of 3rd Party runners might feel differently. They might want to always use the version of the engine that they ship and they have tested with.

I also don't think it is reasonable for 3rd Party developers to expect users to install an engine, so I think they will always include one. One possibility is for us to provide an MSI merge module that they can include with their install.

We aren't getting any feedback from 3rd Party developers on our mailing lists. @CharliePoole, do you mind if I reach out to a few to get their opinions on this?

**Comment by CharliePoole** [comment]
That's odd. My impression of what they do is due to having fielded
questions from both of them about how to locate the NUnit installation.

My thinking is that the presence of the engine in the installation of a
third-party runner is proof enough that the third-party developer wants to
use it, so we should normally use it. What should the user do if he wants
to force the runner to use a newer version?

One possibility is that the user simply replaces the one that's in the
runner directory. But it seems like a heavy-handed way to do it. Another is
that we support some setting to tell us where to look and that we check
that before doing a normal load. Of course, any runner that actually
_references_ the engine will be broken but they would soon learn not to do
it. :-)

Please contact Jamie and whomever seems most likely at JetBrains and cc me.
I think you should have at least a straw-man proposal of the order to check
things first.

Charlie

**Comment by rprouse** [comment]
I was planning on creating a list of places we will check for the engine (registry, app dir, etc) and have one or two search orders before I contact anyone.  I will add that to this issue before I reach out to anyone.

**Comment by CharliePoole** [comment]
We could even consider having the search order - or at least part of it -
depend on a user setting.

One other thing for you to keep in mind is addins. In the past, NUnit
searched for addins in a directory located relative to the location of
nunit.core.* We'll have more ability to locate addins based on a list of
directories kept in the NUnit Settings file, but this could still be a
consideration.

It may be useful in talking with developers to ask how we can encourage
them _not_ to copy the engine. They could still bundle it, but install it
in a place where we will find it rather than in their own directory and not
install it if a usable version is already there. That would be a good
reason for us to provide a merge module as you suggest.

Charlie

* The actual 2.x algorithm is as follows: if xxx (the directory containing
nunit.core) is named lib and it's parent is bin, look in bin/addins,
otherwise look in xxx/addins.

**Comment by rprouse** [comment]
Once we decide on how we should search for the engine, in addition to the coding changes for engine discovery, the install will need to be changed to register the engine.
