### ISSUE TITLE
Analyzer message NUnit2005 is annoying

### ISSUE THREAD

**Issue by gregsdennis** [nunit/nunit#4401]
"Consider using the constraint model..."

I have.  I don't want to use it, at least not for every test.  And now I have compiler messages and little squigglies everywhere in my tests.

I should be able to "got it"-style dismiss this for every one of my projects.  Having this pushed at me everywhere is very annoying.  I get it.  A new assertion model exists.  I don't want to use it.

I know I can [suppress warnings](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-suppress-compiler-warnings?view=vs-2022), but I shouldn't have to do this for every test project.

If I can't globally ignore this, please remove it.

**Comment by OsirisTerje** [comment]
Have you tried to remove the NUnit.Analyzers package?

**Comment by gregsdennis** [comment]
I shouldn't have to forego all of the analyzers in the package simply because this one is annoying.

This suggestion in particular is a code-style preference.  This library (or rather the analyzers package, I suppose) should not be suggesting code style.

This new constraint model is little more than "FluentAssertions mode."  It's more verbose, and I don't want to use it.

**Comment by OsirisTerje** [comment]
Actually, the old style you prefer is something we discuss moving into a legacy project and thus being a separate package.  The "new" constraint model is now some 8 years old, so not really new anymore, and yes, it is a fluent style. That's the way this is going.  E.g. we are no longer accepting PRs that add to the legacy asserts, focusing only on the constraint model. 

There are several code style preferences in the analyzer (like in a lot of other analyzers). If you don't like a style you should just add it into your editorconfig or analyzerconfig and use that in your projects.  

Looking at one of your github projects, I do see that you have a modified editorconfig file, so there should not be an issue adding a single NUnit rule to that.
 
```
dotnet_diagnostic.NUnit2005.severity = none
```

**Comment by stevenaw** [comment]
One added usability note I could add here is that, since editorconfig is hierarchal, you could conceivably specify this once in a root directory housing all your repos and it should then apply to all of them provided the repo-specific editorconfig doesn't explicitly define itself as a "root" (either by omitting the `root` property from it or by explicitly specifying `root = false`)

https://learn.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2022#file-hierarchy-and-precedence

**Comment by gregsdennis** [comment]
Personally, I don't see how

```c#
Assert.That(actual, Is.EqualTo(expected));
```

is easier to read than

```c#
Assert.AreEqual(expected, actual);
```

The constraints model is more verbose and doesn't improve readability.  This shouldn't be forced upon developers.  Make it available, sure, but don't push it with an analyzer.  If anything, recommend it in docs.  But leave the decision to the devs.

**Comment by SeanKilleen** [comment]
@gregsdennis you are welcome to your opinion, of course. But by adding the analyzers package to your solution, you are asking for the opinion of the NUnit developers who build the analyzer, which analyzes for the best / most correct usage of the library according to the authors of the library. We are not pushing a syntax on developers; developers, by installing the NUnit analyzers package, are asking for the automated analysis of our recommendations.

The opinion of the NUnit team, and thus the subsequent analysis and effort that goes into the analyzers, is that the `Assert.That` is the preferred usage and we recommend projects to utilize it.

You're welcome to disagree, and your remedies include ignoring the specific warning as @OsirisTerje suggested, or removing the analyzers package altogether.

FWIW, my personal experience of embracing the `Assert.That` syntax comes from continually remedying situations in which developers mixed up the `actual` and `expected` values, causing incorrect output messages and confusion when tests failed.

**Comment by OsirisTerje** [comment]
@gregsdennis   About readability,  as @SeanKilleen says, I share the same confusion with actual and expected, and have seen many developers doing the same mistake.    
The point is to read from left to right, which is a faster way to read (in English at least) than having some terms reversed.  With other classic asserts, we have got the sequence  that way, like `Assert.Greater(actual,expected)`, but this does not exist in the other test frameworks, so it is an NUnit unique.  We could have had an XUnit like `Assert.Equal(actual,expected)`, but that never came, as the constraint model evolved instead. (And XUnit Equal also have the order reversed)
Btw, a good discussion on this here:  https://stackoverflow.com/questions/9331259/unit-testing-why-is-the-expected-argument-always-first-in-equality-tests

The classics asserts have a big problem with extensibility.  We can't easily add more to them.  E.g. with tolerances that had to be an overload for AreEqual for doubles.  But it works only for doubles and float, not for decimals or other types.  This is but on example.
The constraint model was designed to solve these issues, as the constraints can be chained.  E.g, that gives `Assert.That(actual,Is.EqualTo(42.0).Within(0.1)`   This also gives us the ability to construct better error messages.  The syntax becomes more verbose, but it should be easier to think around this when things gets more complex. 

About the analyzer, we have chosen an opt-out approach instead of an opt-in.  We don't know what the developer really want to use,  we don't stop them from opt-out, but I do see we could possibly make that easier.  There is nothing much we can do about the Roslyn behavior, that is outside our scope, but we could in NUnit 4 do something.

In the plan for NUnit version 4, there is a point of extracting out the classic asserts into a separate package.  We could then do two things:  1) Add an extra  template for creating a classic NUnit project using this new package.  2) The analyzer could detect this and then suppress the 2005 warning, since the analyzer then **knows** the developers intention.

**Comment by SimonORorke** [comment]
This has been a very helpful discussion.  It has convinced me to use the new Asserts going forward, even though I've used classic Asserts forever (and made sure I had expected and actual the right way round!).

One thing I like about the new Asserts is that the NUnit analyzer lets me know if I accidentally put a constant in actual when, of course, a constant should only be something expected.  Actual and expected are in reverse order compared with what I'm used to.  However, I agree, its more like natural language English and therefore probably better for programmers who are new to NUnit.

**Comment by dca00** [comment]
The That syntax is more time-consuming to read.
