### ISSUE TITLE
OneTimeSetup is invoked more-than-once when using ParallelScope.All

### ISSUE THREAD

**Issue by ramonsmits** [nunit/nunit#4462]
Methods with the `OneTimeSetup` attributes are invoked more-than-once when using `[Parallelizable(ParallelScope.All)]`

The following will show the method being invoked multiple times:

```c#
[Parallelizable(ParallelScope.All)]
[FixtureLifeCycle(LifeCycle.InstancePerTestCase)]
public class BaseFixture
{
    [OneTimeSetUp]
    static async Task CreateDatabaseAndSchema()
    {
        Trace.WriteLine("CreateDatabaseAndSchema");
    }
}
```

It seems there is no locking involved to prevent this.

## Workaround

Use a static contructor:

```c#
[Parallelizable(ParallelScope.All)]
[FixtureLifeCycle(LifeCycle.InstancePerTestCase)]
public class BaseFixture
{
    static BaseFixture()
    {
        Trace.WriteLine("CreateDatabaseAndSchema");
    }
}
```

**Comment by stevenaw** [comment]
Thanks @ramonsmits 

Since your class is named `BaseFixture` I'm assuming you may have multiple subclasses? Do you find that it is invoked once per type of subclass? Do you find it still happens if you remove the `InstancePerTestCase` part?

I'm curious if this behaviour is described in #4418 but it's tough to tell based on the code you've provided

**Comment by ramonsmits** [comment]
@stevenaw I think you are right. Based on #4418 it seems this is expected behavior. I looked at https://docs.nunit.org/articles/nunit/writing-tests/attributes/onetimesetup.html before creating the issue. I now see SetUpFixture mentioned at the top. I think the docs can be clarified a bit so created:

- https://github.com/nunit/docs/pull/786

**Comment by OsirisTerje** [comment]
PR is merged, so closing this now.
