### ISSUE TITLE
Allow easier substring constrain when using `StringComparison`

### ISSUE THREAD

**Issue by RenderMichael** [nunit/nunit#4468]
Today the canonical way of doing a substring assertion is
```csharp
Assert.That(str1, Does.Contain(str2));
```
However, that doesn't allow us to use a `StringComparison`. The workaround way to do that is
```csharp
Assert.That(str1, new SubstringConstraint(str2).Using(StringComparison.Ordinal));
```
Even though `Does.Contain` has a string-specific overload, it returns a `ContainsConstraint` instead of a `SubstringConstraint`, which does not allow the use of `StringComparison`.

Could the `Does.Contain(string expected)` return `new SubstringConstraint(expected)` instead of `new ContainsConstraint(expected)`?

**Comment by RenderMichael** [comment]
the only special member that `ContainsConstraint` has is `IgnoreCase`, which `SubstringConstraint` also has, so unless I'm missing something, this isn't a source-breaking change

**Comment by stevenaw** [comment]
Thanks @RenderMichael this is a good usability point, one that also applies to a few other cases such as https://github.com/nunit/nunit/issues/3922 and https://github.com/nunit/nunit/issues/2492

We'd have to be a bit careful here not to affect one of the other ways `Does.Contain()` can be called, which is to search for items in an array. For example:

```csharp
Assert.That(new[] { "Hello", "World"}, Does.Contain("Hello"));
```

A another idea which could work here have `ContainsConstraint` extend `EqualConstraint` instead of `Constraint`, though I'm unsure off the top of my head which edge cases we may need to contend with there

**Comment by RenderMichael** [comment]
Looking deeper into it, looks like `SubstringContraint` is exposed directly with the pattern
```csharp
Assert.That(str1, Contains.Substring(str2));
```

So it seems like `Does.Contain` supports substrings but that's not the idiomatic approach. In that case, I'll close this issue since it's core is addressed. Thanks!
