### ISSUE TITLE
NUnit 2.6.3 ExpectedException

### ISSUE THREAD

**Issue by Diogomrol** [nunit/nunit#449]
Hi there,

I was using NUnit 2.4.8 framework. I tried to migrate this 2.4.8 to 2.6.3, and just by doing that my tests with ExcpectedException started to fail (not passing, raising the exception instead of "hiding" it).

I searched a lot and couldn't find any change in the framework that could lead to the change of my code.

All my tests look like:

        [Test]
        [ExpectedException(typeof(MyExceptionType))]
        public virtual void ThisIsMyTest() {
            ThisIsTheFunctionThatRaisesTheException();
        }

Any ideas about this?

Thanks!

**Comment by rprouse** [comment]
Is the exception that you are expecting the exact same type as the exception being thrown, or is it a base type? The exception needs to be the same. For example, the following will fail,

```C#
[Test]
[ExpectedException(typeof(Exception))]
public void ThrowsException()
{
    throw new ArgumentException( );
}
```

That said, you should also consider migrating to `Assert.Throws<T>`. It is safer because it asserts that the specific code you are testing throws the exception, not some other call within your test method. `ExpectedException` is also being removed in 3.0.

```C#
[Test]
public void ThrowsException()
{
    Assert.Throws<ArgumentException>( MethodThatThrows );
}

private void MethodThatThrows()
{
    throw new ArgumentException();
}
```

**Comment by CharliePoole** [comment]
I'm closing this as an issue for a number of reasons, but will try to give you a few pointers as well.

Reasons for closing this...
 * This is the repository for NUnit 3.0, not for NUnit 2.6.3 -- the nunitv2 project.
 * ExpectedExceptionAttribute works in NUnit 2.6.3 (and 2.6.4 btw) although it has been removed from NUnit 3.0.
 * It's most likely that you simply need some help in doing this migration and this isn't the best place to get it.

Suggestions...
 * Ask for help on the nunit-discuss forum. This problem has never been reported before and 2.6.3 has been out for over a year, so it's most likely a migration issue that will benefit from community discussion.
 * Make sure you don't have any NUnit 3.0 components downloaded, since ExpectedException does not exist in that release. This is unlikely, however, since your code would not compile against the 3.0 framework.
 * Be sure to tell us how you are running your tests: nunit-console, gui, third-party, etc.
 * If you're going all the way from 2.4.8 to 2.6.3 in one jump, it seems a bit silly not to use 2.6.4!
