### ISSUE TITLE
Should Tolerance be a record type?

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit#4506]
1) The Tolerance class is not something that is changed after creation.
2) It should not be null.

The code here in the Equal Result constraint causes a warning, and the parameter is `Tolerance?` but it is initialized as Default, and possibly later set to another Tolerance (through new), so it can't be null.
![image](https://github.com/nunit/nunit/assets/203432/6efdf221-c339-4968-ba44-6cdf23e866da)

It doesn't seem to change at all, so could it be a record type?

@manfred-brands @stevenaw  Comments?

Are there other classes that are better suited as records?

**Comment by mikkelbu** [comment]
It can be that Tolerance cannot be null in this class, but it can be null in other classes. Also I'm not sure how much we gain by making it into a record. I usually use records for smaller (immutably) types with only/mostly data, but it seems like `Tolerance` is already immutable. I guess we get value equality, but I guess we don't equate Tolerance at the moment, since it does not override `Equals`.

**Comment by manfred-brands** [comment]
@mikkelbu Actually `Tolerance` is never `null` as none of the fields are declared `nullable`.
@OsirisTerje The only comparison done is the one you introduced in PR #4507  `Tolerance.Default`
I therefore don't see a need for a `record`.

**Comment by OsirisTerje** [comment]
@manfred-brands Thanks!  Then I'll keep the nullable changes and revert the record back to class.
