### ISSUE TITLE
Portable version of NunitLite shouldn't reference System.Windows

### ISSUE THREAD

**Issue by cwensley** [nunit/nunit#460]
The PCL version of NUnitLite (in 3.0 alpha 3 from nuget) currently references System.Windows.dll, and includes the Silverlight TestPage runner.  This should be removed to provide a truly portable runner that can be used for all platforms, including Xamarin.

**Comment by CharliePoole** [comment]
Our intention is that the portable framework build will be used with various runners, which are non-portable by nature. A test that wants to use NUnitLite must reference some version of it, along with a portable runner.

Currently, only console and siverlight versions of the nunitlite runner exist, so we used the silverlight runner to test the framework itself. Eventually, there will be runners for other platforms.

Additionally, it will be possible to run tests on some platforms from the desktop using the NUnit console and gui runners, although we are a long way from that.

We'll hold this issue as a reminder that we need to add other runners and possibly reorganize the directory structure so it's clear that the nunitlite runner is not actually portable.

**Comment by cwensley** [comment]
Ah that makes it more clear, thanks for the explanation!

That being said, would it be possible to have a fully PCL version of nunitlite?  Basically without any GUI runner baked in.  This would make it much easier to use it in platforms that nunit/nunitlite might not have a platform-specific runner for yet.  Of course I imagine the intention would be to have support for all platforms, but that would mean a delay in using the latest greatest platform with nunit until such a runner is created.  For example, right now Xamarin.Mac 2.0 doesn't have a runner, but I'd like use nunit with it.

Thanks for hearing me out!  I really appreciate it.

**Comment by CharliePoole** [comment]
What would a PCL runner look like? As you say, it could not have any GUI. In fact, it could have no UI at all, even console-oriented, since not all platforms have a console. 

Perhaps I'm missing something, but I can't see what's left for a "runner" to do!

**Comment by cwensley** [comment]
The idea is to be able to use the API to write your own custom runner without having platform-specific stuff get in the way.. e.g.

```C#
var builder = new DefaultTestAssemblyBuilder();
// use builder to show custom UI
var runner = new NUnitTestAssemblyRunner(builder);
var test = runner.Load(assembly, new Dictionary<string, object>());
var listener = new MyTestListener(); // shows results in custom UI
var result = runner.Run(listener, new CategoryFilter());
```

This is working really well for me, but the platform-specific stuff in the dll means I can't do my UI tests when building Xamarin.Mac / Xamarin.iOS unified due to the System.Windows.dll reference.

I was very hopeful with 3.0's goal of exposing an API to run tests, but it may not be usable in all current (and especially future) platforms unless the API is unencumbered by platform-specific UI code.  It would also be especially useful for platforms such as .NET Core, where there is no UI other than web (unless you are also planning on building a nunitlite UI for that as well?).

It might be very simple to provide this, which is to have the PCL version of nunitlite have no UI, whereas the platform-specific nunitlite dll's would include the UI.  This really is all about flexibility.  Providing the core test running API without UI will make nunit much more portable when new platforms arise.

Thanks again for hearing me out!

**Comment by CharliePoole** [comment]
Let me clarify a few things we're doing...

The public API for running tests is the engine api. That's what the console
runner and the (coming) gui use. That's  what we hope 3rd party runners
will use. The way that a particular platform and framework get hooked up to
the engine is via a driver. Currently, we have drivers for NUnit 3.0 and
NUnit 2.x, running on the desktop. We don't yet have drivers for devices.

NUnitLite is conceived of as an alternative way to run tests and see the
results directly _on_ the target platform. So any UI has to be supported by
that platform. For example, the compact framework has a system Console, so
our CF version of nunitlite for that platform uses the console. Silverlight
has it's own runner for the same reason. Any version of NUnitLite, in order
to do it's job, would have to have some kind of UI. Without a UI, it would
not be "an alternative way to run tests and see the results."

The engine drivers have nothing to do with NUnitLite. They talk to the
framework assembly. Current drivers use Remoting to do that, but future
drivers will use other protocols like TCP or HTTP. A driver that targets
the framework on a device has to be specific to that device because one of
it's jobs is to launch the test assembly on the device. Creating drivers
for devices is our main focus, because we believe the greatest need is to
be able to launch tests on the desktop, connecting to any device for
execution where needed. Having the actual UI _on_ the device can work, but
it usually has to be fairly primitive.

That said, we will be creating nunitlite runners for the platforms you
mention. They just are not yet done.

So, coming back to your request: the framework itself contains a low-level
"core test-running api." Your code example above uses it. Originally,
NUnitLite was a version of the framework (see nunitlite 1.0) but no longer
exists as a framework. The nunit framework contains all the non-UI stuff
and nunitlite contains the UI. So a UI-free nunitlite doesn't make sense
any longer.

What we probably should do is to refactor nunitlite so that the
framework-independent part (counting tests, for example) is clearly
separate from the framework-dependent part (displaying results). We might
be able to end up with a set of abstract methods that need to be
implemented to port nunitlite to a particular platform.

**Comment by cwensley** [comment]
Hi Charlie, thanks for the clarification on the API.  I think I had the wrong idea of what that meant.  I would certainly love to see nunitlite refactored into a framework-independent part separate from the results display as you suggest.

**Comment by rprouse** [comment]
I think what you are asking for is a portable version of the test engine which we are working on in #571. We are doing this to provide the skeleton of a runner for Xamarin, for the Visual Studio test adapter, etc.

@cwensley, if this is what you are thinking, let us know. We can close this issue as a duplicate and continue the discussion there.

**Comment by cwensley** [comment]
@rprouse Yes, that is exactly what I'm looking for.  I have noticed that NUnit 3 (beta 2) has a built-in engine inside nunit.framework.dll, is that part of this?

**Comment by rprouse** [comment]
@cwensley, Yes, that is part of this, although there is still more work to do. If you want to start playing with it, we released a NuGet package with it with the last beta. It isn't PCL yet, but I am currently working at modifying it to be PCL.

I am going to close this issue. If you have additional ideas or want to help out, please do so in #571.
