### ISSUE TITLE
PropertiesComparer should have default Depth limit, and compare breadth first, to reduce chances of StackOverflow

### ISSUE THREAD

**Issue by RobSwDev** [nunit/nunit#4604]
Using NUnit and NSubstitute, it's easy to inadventantly cause a stackoverflow if you compare recursive types (such as a TreeNode).

If the PropertiesComparer worked breadth-first, rather than depth first, the test below would pass not crash.

Also, it would be better if the comparer would only work to a set depth, with a sensible default (one that the user can increase where circumstances demand - but I don't write many unit tests that require comparison 1000s of objects deep)

[Additionally, it would be good if VS highlighted crashed tests better, and NSubstitute does not need to build infinite object hierarchies on demand, but those complaints are for another forum]

``` csharp
    [Test]
    public void CrashingTest()
    {
        var x = Substitute.For<IRecursive>();
        x.Value.Returns(1);
        var y = Substitute.For<IRecursive>();
        y.Value.Returns(2);
        Assert.That(x, Is.Not.EqualTo(y)); // Clearly, because 1 != 2
    }

    public interface IRecursive
    {
        IRecursive? Parent { get; }

        int Value { get; }
    }
```

**Comment by manfred-brands** [comment]
I agree the PropertiesComparer needs some work. It was mainly intended to work on DTO classes that don't  implement IEquality themselves.

Note that older versions of NUnit only did reference comparison, meaning even if your substitutes both returned 1, NUnit would still compare them as not equal.

I'll see what I can do here.

**Comment by manfred-brands** [comment]
I can repeat your problem, but when trying to add it in a test inside nunit using a real class, things behaved nicely.
The problem here is the automocking of Substitute which I my opinion is not realistic. Any other code using the instances will go on forever as well. Adding `x.Parent.Returns(default(IRecursive));` and equivalent for `y` causes the test to pass without errors.

**Comment by RobSwDev** [comment]
Agreed - there are issues with NSubstitute (and with Visual Studio, which all but conceals the fact a test has crashed)

But I think NUnit could also improve. 
This test also crashes, even though the NUnit analyzers can see that the list is being compared against itself.

If the PropertyComparer checked for reference equality first (before reflecting over properties) then it would pass, as would comparing a list against a copy of itself. It would also be more efficient for many use cases.

``` csharp
    [Test]
    public void AnotherCrashingTest()
    {
        var list = new[] { Substitute.For<IRecursive>(), Substitute.For<IRecursive>() };
        Assert.That(list, Is.EquivalentTo(list));
        Assert.That(list, Is.EquivalentTo(list.ToList());
    }
```

**Comment by manfred-brands** [comment]
> If the PropertyComparer checked for reference equality first (before reflecting over properties) then both tests would pass. It would also be more efficient for many use cases.

It only falls into the `PropertyComparer` if the references are not the same.
The first test is `NUnitEqualityComparer.AreEqual` which contains:
```
            if (object.ReferenceEquals(x, y))
                return EqualMethodResult.ComparedEqual;
```

I see that those tests indeed fail and will investigate why.

**Comment by manfred-brands** [comment]
@RobSwDev Your tests pass if using `Is.EqualTo` instead of `Is.EquivalentTo`. The latter fails because it doesn't compare elements in order and the `Substitute` does keep creating classes which bring us back to my original statement that one needs to mock every part of code that is called.

As the code has cyclic reference detection in place, the only time where this will fail is with auto-generated endless structures.

**Comment by manfred-brands** [comment]
@OsirisTerje I'm inclined to close this as answered.
