### ISSUE TITLE
TimeoutAttribute causes context in TearDown to have incorrect info.

### ISSUE THREAD

**Issue by gedefran** [nunit/nunit#4619]
In this example, the old Timeout attribute causes the incorrect test status in teardown.

```
public class Tests 
{
	[Test, Timeout(240_000)]
	public void Test1()
	{
	}

	[TearDown]
	public void TearDown()
	{
		TestContext.WriteLine($"Status: {TestContext.CurrentContext.Result.Outcome.Status}");
	}
}
```

If you change the Timeout to CancelAfter or go back to the 3.X libraries the status is reported correctly.

Pretty sure its from the changes to TimoutCommand.cs in #4499 

@stevenaw let me know if you need more details of have any issue reproducing.

**Comment by stevenaw** [comment]
@gedefran I've pushed your repro to https://github.com/nunit/nunit.issues/tree/main/Issue4619
I've assumed you're using .NET Framework since you're using `Timeout` but please let me know if that's incorrect.

When running the repro and using the `Timeout` attribute on either NUnit 3.14.0 or 4.0.1 I see the same status of `Passed`. Can you please explain a bit more about what you're seeing vs what you'd expect? Confirming the specific framework versions and runtimes you're using would also be a big help.

Please feel free to put up a PR against that repo to help us better run your repro if any adjustments are needed to it.

**Comment by manfred-brands** [comment]
@gedefran As @stevenaw said, for .NET Framework, the results are the same, for .NET Core not, but `TimeoutAttribute` is not supported there see #4021 for more information.

**Comment by gedefran** [comment]
Yeah we're using .net core, and I've converted things to use the new
CancelAfter attribute so things are fine for me now.

**Comment by stevenaw** [comment]
Great to hear @gedefran and thanks for raising this!

Normally I would suggest improving the docs, but given the change in behavior here is on an unsupported runtime for this attribute I'm instead leaning towards closing.

@manfred-brands @OsirisTerje feel free to reopen if you prefer
