### ISSUE TITLE
Add custom conditions on `[IgnoreAttribute]`

### ISSUE THREAD

**Issue by RenderMichael** [nunit/nunit#4660]
Often times I have to ignore tests given certain conditions (a feature is only enabled on the staging environment, etc).

It would be nice to include that in the `[Ignore]` attribute, something like so:

```csharp
public class TestClass
{
  public bool EnvironmentIsStaging => string.Equals(TestContext.Parameters["env"], "STG", StringComparison.Ordinal);

  [Test]
  [Ignore("Test only works on staging", typeof(TestClass), nameof(EnvironmentIsStaging))]
  public void TestOnlyOnStaging()
  {
  }
}
```

`bool`-type properties and `bool`-returning parameterless methods could be supported. A `calleeType` parameter could be optional (in which case it is assume to be on the fixture) or it could be required.

I am happy to take a crack at this. Or maybe the above could already be accomplished by an NUnit feature I am not aware of.

**Comment by OsirisTerje** [comment]
The Ignore attribute is intended to be used on tests that are not ready to be run yet, because something has to be fixed.

From the docs:

> Ignored tests are displayed by the runners as warnings in order to provide a reminder that the test needs to be corrected or otherwise changed and re-instated.

So using it to create conditional running will change the semantics of this attribute.

But, why can't you use a category to achieve this?  The parameter for this would then be handled in the runner script.

 In order to make the code above work, you would need to set a parameter. Then, you could just as well set a category. 

We do have some other attribute that is used conditionally, like [Platform](https://docs.nunit.org/articles/nunit/writing-tests/attributes/platform.html), but none for environment.  

If this is something that others believe should be included (never seen this ask before though), I  believe this functionality should be in its own attribute.

**Comment by OsirisTerje** [comment]
I'm closing this for now.
