### ISSUE TITLE
Overflow exception and DivideByZero exception from the RangeAttribute

### ISSUE THREAD

**Issue by pvlakshm** [nunit/nunit#472]
Specific data values fed to the RangeAttribute can trigger a DivideByZero exception and/or an OverflowException. These values have been pointed out by the Smart Unit Tests feature from Visual Studio 2015, and an image with the data values is attached.

The DivideByZero may happen by the user entering 0 as a step value.
The OverflowException is more serious as it highlights an implicit constraint saying “to > from” that is not stated anywhere. There should there be any need for that.
![exceptions](https://cloud.githubusercontent.com/assets/9894334/5914081/b1bd6452-a5a3-11e4-82a2-ca760b9dac52.jpg).

These issues are seen for all the RangeAttribute overloads.
Please let me know if you need any further information.

Pratap Lakshman

**Comment by CharliePoole** [comment]
On what version of NUnit are you seeing these errors?

**Comment by pvlakshm** [comment]
This is on the NUnit 3.0 framework. I ran Smart Unit Tests directly on nunit-master\nunit-master\src\NUnitFramework\framework\Attributes\RangeAttribute.cs.

**Comment by CharliePoole** [comment]
We'll treat this as a bug for now and check it out further.

For the divide by zero exception, that has always seemed like a reasonable thing to happen if the user happens to specify a step of zero!

The issue of ordering of arguments has already been discussed extensively. This fix: https://github.com/nunit/nunit/pull/77 created code to throw an ArgumentException with an appropriate message if the order is incorrect. I'll have to check the code to see how an OverflowException is generated instead.

**Comment by CharliePoole** [comment]
It would be helpful if you could provide an actual test that demonstrates the overflow.

**Comment by pvlakshm** [comment]
OK, here is such a test case:

    public class UnitTests
    {
        [TestCase]
        public void TestIfLessthan10(
            [Range(826, 33, 50)] int n)
        {
            NUnit.Framework.Assert.AreEqual(true, (n >= 0));
        }
    }

I have used the values as reported in the table I pasted into the bug report earlier. Please let me know if you need any further information.

**Comment by CharliePoole** [comment]
The earlier comment about ArgumentException was incorrect. It applies to the RangeConstraint not the RangeAttribute. RangeAttribute gives the errors as reported:

A step of zero causes a DivideByZeroException. I think this could be replaced by an ArgumentException but is also OK as it stands. It should be clear to the developer.

Reversing from and to causes an OverflowException. We should at least throw an Argument exception with an appropriate message. Alternatively, we could make it work in various ways, as shown below.

Additionally, use of a negative step with from < to will cause an overflow. Again, we should either throw an ArgumentException or make it work.

Proposed Resolution (please comment):

A step of zero should give an argument exception. Even though DivideByZero is logical, it takes a moment to figure it out. A message like "Zero step not allowed" is much simpler.

An invalid combination of from, to and step should give an argument exception. An invalid combination occurs if from > to and the step is positive or if from < to and the step is negative.

A valid combination of from, to and step should just work. This will require a bit of change in the code for negative steps.

**Comment by rprouse** [comment]
The three proposed solutions all make sense. It is how I would expect it to work.

That said, if it is a major rework to allow a negative step, we could just throw an argument exception and document it. I think that since no-one has ever reported it before it isn't a common thing people would think of doing. It was only reported now because of an automated testing tool.

**Comment by CharliePoole** [comment]
@rprouse I agree. I lowered the priority.

**Comment by OsirisTerje** [comment]
I believe this can be done in steps of improvement.  
1) The documentation for RangeAttribute at http://www.nunit.org/index.php?p=range&r=2.6.3 is a bit overly optimistic "creates test cases from all possible combinations of the datapoints ".  It should be rephrased, and the limits stated.  It should also state that with wrong parameters you may get these two exceptions.
2) There is obviously something that always will go wrong, from>to & step negative and to>from and step positive.  Those two can be excluded with a guard clause throwing an argument exception.  
3) If negative steps need rework of the code, just guard that out for now, and state that in the documentation.  
3) Since it can operate on floating point numbers, a step may be too small compared to the range it operates on, causing overflow, then this could be attacked later.  I would not prioritize this, as I am fine with an overflow exception as long as it is documented.
