### ISSUE TITLE
[Parallelizable] attribute at textfixture level is not running test parallel

### ISSUE THREAD

**Issue by tallamravi** [nunit/nunit#475]
I have updated to NUnit3.0 and added [Parallelizable] attribute to 2 test fixtures at same level . When I run them in my local machine and when checked using Resharper unit test sessions they are running one after the other not starting parallel. What am I missing?  Could you please assist. Please do let me know if you require additional details.

**Comment by rprouse** [comment]
The Resharper runner still uses the NUnit 2.6 code so it does not support any of the new features in NUnit 3.0. Did you try running the tests with the NUnit 3.0 console runner? Also, what `ParallelScope` did you use?

It should also be noted that the default behaviour in NUnit 3 is to run all test fixtures in parallel, so `Parallelizable` isn't really needed for that. There is also the assembly level `LevelOfParallelism` attribute to control that. The default is to run tests in as many threads as there are processors on the machine.

These features are not well documented yet. You may also want to look at the design spec at https://github.com/nunit/dev/wiki/Framework-Parallel-Test-Execution

**Comment by CharliePoole** [comment]
Actually, NUnit 3.0 _supports_ parallel execution by default (we #define
PARALLEL) but the default behavior at runtime is that all fixtures are
non-parallelizable. Our own tests appear to run in parallel by default
because we put a ParallelizableAttribute on the assembly itself.

As stated, however, running through Resharper will not get you those
features. In fact, a number of NUnit 3.0 features won't work and tests may
disappear due to breaking changes in 3.0. The same problem exists if you
try to run 3.0 tests using nunit.exe or nunit-console.exe from an earlier
release of NUnit. The NUnit 2.6.4 release solves this problem by refusing
to run the tests and Resharper will give the same result once they upgrade
to 2.6.4.

We are working with JetBrains and other third-party runner creators to try
to accelerate their adoption of NUnit 3.0.

**Comment by tallamravi** [comment]
Thanks for the reply and update. I have a followup question, then how can I see that tests are running in parallel after using Nunit3.0, teamcity build will help?

**Comment by CharliePoole** [comment]
If you need verification beyond the reduction in runtime, look at the internal trace.

Just like any other 3rd party runner, Teamcity still knows nothing about NUnit 3.0. So you can only run it if your teamcity job launches the 3.0 console.

For further discussion, I suggest you use the nunit-discuss list.
