### ISSUE TITLE
nunit-console has multiple errors related to -framework option

### ISSUE THREAD

**Issue by xplicit** [nunit/nunit#482]
If you run `nunit-console.exe --framework=net-4.159 assembly.dll` (set the framework version to non-existing one)

you'll see the header output, and test will be run

`Execution runtime: net-4.159`

expected result: there should be an error "The net-4.159 framework is not available"

**Comment by CharliePoole** [comment]
Definitely a bug.

**Comment by CharliePoole** [comment]
Several problems:
1. There is no check on the value passed in the command-line, since the runner doesn't actually know what frameworks are available - the test engine does not have a public method to find out.
2. The engine should be throwing an exception, but doesn't. There is an error in the method that checks whether a given framework is supported. See the Supports method of RuntimeFramework.
3. Even if the error is fixed, the engine is not distinguishing between a specifically requested framework and the target framework for which an assembly is built. A specifically requested framework should be found exactly as specified. For a target framework, we simply need to find a runtime under which it can be executed, so for example 4.0 will do for a 2.0 target.
4. Not quite related, but I notice that the framework option is not even looked at when process:Single is specified. In fact, we should give an error if NUnit is not already running under that framework.

I changed the title to reflect multiple errors.
