### ISSUE TITLE
Can I set `[Apartment]` from an `ITestAction`?

### ISSUE THREAD

**Issue by chucker** [nunit/nunit#4859]
I have a test that works when correctly when configuring it as STA:

    [Test]
    [NonParallelizable]
    [Apartment(System.Threading.ApartmentState.STA)]
    public void MyTest()
    {
        var window = new AboutBox();
        window.Show();
    }

I'd now like to wrap that (and some other setup) in an `ITestAction`.

From the debugger, I gather that the attributes have an effect on the property bag.

However, _setting_ the same properties doesn't seem to have any effect:

    [AttributeUsage(AttributeTargets.All, Inherited = false, AllowMultiple = true)]
    sealed class WpfTestAttribute : Attribute, ITestAction
    {
        public ActionTargets Targets => ActionTargets.Default;

        public void BeforeTest(ITest test)
        {
            test.Properties["ApartmentState"] = new List<object> { nameof(ApartmentState.STA) };
            test.Properties["ParallelScope"] = new List<object> { "None" };

            // …more set-up
        }

        public void AfterTest(ITest test)
        {
            // …some tear-down
        }
    }

    [Test]
    [WpfTest]
    public void TestImageSnapshot()
    {
        var window = new AboutBox();
        window.Show();
    }

This gives me `System.InvalidOperationException : The calling thread must be STA, because many UI components require this.`, suggesting that merely putting the property in the property bag does not cause the thread to be run in a different apartment state.

Is there something else I can do to apply this from an `ITestAction`?

**Comment by stevenaw** [comment]
I suspect that the action is applied "too late". `BeforeTest`, like the `SetUp` method, are run in the same context as the associated test by design. This means that the test must already be described as STA in order for NUnit to run it on a correctly configured thread.

The `Apartment` attribute itself implements the [`IApplyToTest` ](https://docs.nunit.org/api/NUnit.Framework.Interfaces.IApplyToTest.html)interface. While I haven't tested it myself, but have you tried having your custom attribute implement both interfaces? Note that NUnit can't guarantee the same instance of the class will be used in both cases.

```csharp
[AttributeUsage(AttributeTargets.All, Inherited = false, AllowMultiple = true)]
sealed class WpfTestAttribute : Attribute, ITestAction, IApplyToTest
{
}
```

What is it that your custom attribute is trying to do? Action attributes [aren't really recommended for new work](https://docs.nunit.org/articles/nunit/extending-nunit/Action-Attributes.html) and that, depending on what you are trying to do, something like the [ITestBuilder interface](https://docs.nunit.org/articles/nunit/extending-nunit/ITestBuilder-Interface.html) or the proposed [HooksExtension](https://github.com/nunit/nunit/issues/4744) may be better.

**Comment by chucker** [comment]
>I suspect that the action is applied "too late".

I was wondering if it might be something like that.

> have you tried having your custom attribute implement both interfaces

Indeed, that fixes it! Thanks.

>What is it that your custom attribute is trying to do?

Mostly "do some set-up and tear-down after each test of this kind". Sure, I could do that in the test fixture, but marking it with an attribute seemed a little more intuitive to me.

I'll have a look at `ITestBuilder`, though.

**Comment by stevenaw** [comment]
Happy to have helped! 😀
