### ISSUE TITLE
Resolve possible dependency to nunit in nunitlite package

### ISSUE THREAD

**Issue by xplicit** [nunit/nunit#495]
NUnitLite package does not have dependency to NUnit package. If create empty console application and add NUnitLite package solution won't compile, you have to add manually NUnit package too. If NUnitLite package had the dependency to NUnit package it would be added automatically.

**Comment by CharliePoole** [comment]
As indicated in the title change for the issue, we haven't yet figured out whether there should be such a dependency. As things stand in the alpha, your tests reference both the framework and nunitlite and nunitlite references the framework. If it remains that way, then I think you are right and we should add the dependency. OTOH, if we modify nunitlite to use reflection, allowing it's version to vary from that of the framework, it's uncertain whether we would want a package dependency. If we modify it to be itself an exe and to run tests by name, then it will be a tool and the packages should definitely be independent.

**Comment by rprouse** [comment]
This has been fixed since this was reported. I checked the [package on Nuget.org](https://www.nuget.org/packages/NUnitLite/3.0.0-beta-4) and it has the dependency. I also checked the nuspec file, the dependency was added for the alpha-3 release.

![image](https://cloud.githubusercontent.com/assets/493828/10036192/e43580c4-6171-11e5-9887-4416abde589f.png)
