### ISSUE TITLE
explicit and ignore

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#50]
First the problem:
We make a test, that could not be satisfied up to now, because the implementation of the functionality is not ready. We give him the attribute explicit, so the developer can run the test while he implements the functionality. But for the person who looks at the tests, he didn't see the test. So we make a empty copy of the test and give hin the attribute ignore.
If we give the test both attributes, explicit and ignore, the test is not runable under the gui.

A possibility would be that ignored tests can be run if a special option is set (perhaps on the tab for categories or command line).
This would be a very nice feature!

See discussion at https://bugs.launchpad.net/nunit-3.0/+bug/777810

**Comment by isaacllopisaracil** [comment]
Hm... Either I'm doing something wrong or it does not work as expected. My unit test suite is using NUnit 3.0.1 and one test is marked with the ExplicitAttribute. The effect is that it appears as a warning rather than ignored in Visual Studio NUnit3 Test Adapter v3.0.8.0 and my list of tests shows in yellow (warning) rather than green.

**Comment by CharliePoole** [comment]
@isaacllopisaracil Before 3.0, NUnit didn't return any information about explicit tests. Now it does, indicating that the test was skipped because it's explicit. We probably need to modify how we are giving VS information about those tests. The basic problem is that VS has a much more limited set of outcomes than NUnit, so we have to map different things together.

Please note that your comment is not related to this issue or even to NUnit itself. If you would like to remind us to follow up on the problem, you should file an issue on the nunit3-vs-adapter project.

**Comment by isaacllopisaracil** [comment]
Hi @CharliePoole and thanks. I will do that. However, my point is it probably shouldn't as by doing it it breaks the expected functionality. Take for example the comment of @rprouse above:

> Ignore - **Skipped** during normal test runs, can be explicitly run when selected, if not selected, shows up as a warning in the test report.

> Explicit - **Skipped** during normal test runs, can be explicitly run when selected, if not selected, **does not show up in the test report**.

By this statement, only if I used *IgnoreAttribute* a warning message should be shown. The *ExplicitAttribute* is expected to behave as it did before 3.0. The UI, however, shows both as warnings (which thing I will report in the appropriate place, BTW, thanks for the tip).

Now check what the wiki for 3.0 says at https://github.com/nunit/nunit/wiki/Explicit-Attribute:

> If a test or fixture with the Explicit attribute is encountered in the course of running tests, it is **skipped** unless it has been specifically selected by one of the above means. The test does not affect the outcome of the run at all: **it is not considered as ignored and is not even counted in the total number of tests. In the gui, the tree node for the test remains gray and the status bar color is not affected.**

Putting together the two references, the expected behavior of the *ExplicitAttribute* should not be different to the behavior it had before 3.0 and it should definitely not be returning any information. IMO either the doc is wrong or the implementation should be changed so that it works according to spec.

**Comment by CharliePoole** [comment]
@isaacllopisaracil You mention a couple of things...

1. @rprouse 's comment above is part of a discussion about **changing** how Explicit and Ignore work. It's not how they now work. The main change he proposes is that users should be able to explicitly select ignored tests. He wasn't proposing any change in Explicit and he describes exactly the way it worked **when he wrote the comment**, which was in February, 2014. Explicit no longer works as he described there. It does not effect the overall result of the run but it does show up in the test report.

2. The documentation for the wiki should definitely reflect the way Explicit actually works. As you point out it doesn't. The paragraph you cite was copied from V2 of NUnit and needed to be corrected. I just did that. One point of clarification: where the docs talk about the gui, it is referring to our NUnit gui, not to the VS adapter.

**Comment by rprouse** [comment]
@CharliePoole I think we can close this, do you agree?

**Comment by CharliePoole** [comment]
Agree.
