### ISSUE TITLE
Separate assembly for constraints

### ISSUE THREAD

**Issue by vgrigoriu** [nunit/nunit#502]
and nuget package, obviously. Are there any chances of this happening? Any way I can help?

**Comment by CharliePoole** [comment]
First, let's try to understand why you think this is a good idea.

Why would it be useful? Who would use it? Are you thinking that constraints could be used for something other than nunit tests?

How would it work? I guess folks have to reference two assemblies in order to write tests. That's slightly "un-nice" for those guys. :-)

**Comment by vgrigoriu** [comment]
I like the syntax of constraints, and the fact that they can be combined, and I would like to be able to use them with other testing frameworks such as Fixie.

Referencing two assemblies wouldn't be such a big deal for people using nuget to add nunit references - they'd add the NUnit package, which would depend on the NUnit.Constraints package, and both references would be automatically added (it's how xUnit.net does it in 2.0).

**Comment by CharliePoole** [comment]
Interesting. I didn't realize that xunit had been split into multiple
assemblies.

We'll keep this as a future idea for now.

**Comment by CharliePoole** [comment]
So let's assume we do this. We have a user.test assembly referencing both nunit.framework and nunit.asserts. The user runs tests:

1. The NUnit runner invokes nunit.framework, which actually executes the tests in user.test
2. User.test executes an assertion located in in nunit.assert - or in some other assertion framework.
3. Let's say that assertion fails. How does it signal it's failure? How does nunit.framework find out about the failure.
4. Same goes if it is ignored dynamically via Assert.Ignore.
5. In fact, even if it passes, how does nunit.framework know an assert was executed, given that it counts assertions.

I'd be happy to hear how others have dealt with this, if anyone knows.

**Comment by vgrigoriu** [comment]
Well, number 3 is easy, the assertion throws an exception to signal failure. The only complication is that the runner might want to recognize it as a special exception, in order to hide the part of the stack trace that's not relevant.

5 seems more difficult. NUnit seems to use exceptions to also signal successful asserts, and I assume there is special logic in the runner to recognize `SuccessException`, right? I mean, if the test assembly references both nunit.framework and nunit.asserts, then everything works as it does now. The problem is if we use a different runner, which might not recognize `SuccessException` as a successful assert. And the converse, other assert libraries probably don't throw exceptions when asserts pass, so they didn't have to deal with this.

Off the top of my head, maybe nunit.asserts can be configured as to whether it throws `SuccessException` (and `IgnoreException`) or not? What about now, could someone use NUnit with a different assert library that doesn't signal success?

**Comment by CharliePoole** [comment]
@vgrigoriu You've gone a bit deeper. I'll come back to that later in this post.

This comes up periodically and I have never really grasped what people were expecting to happen. From your response, I think it's probable that the expectation is for the assert assembly to throw an exception on failure and for everything else to pass. That makes some sense if we believe that a test has to either pass or fail when it is run.

There are a couple of things that work against this, however:

1. NUnit makes a distinction between failures and errors. Essentially, anything other than a known NUnit exception (Assertion, Success, Failure, Inconclusive) is counted as an error and processed a little differently. Basically, we want a more complete stack trace on errors.

2. Reporting via an exception is kind of primitive and we have some ideas about eliminating their use to report failures. Unexpected exceptions would still need to be handled.

Essentially, it seems like one of the two assemblies needs to know something about the other in order for them to work together. In the model you were discussing, the framework knows that the assert throws an exception on failure (disregarding the error/failure distinction). It's definitely possible to work that way. In fact, that's what NUnit does when a mock framework throws an exception. The mock failure is treated as an "Error" by nunit, but most users only look at the message and don't notice the difference. We could do the same thing for a separate special-purpose assertion framework used within NUnit. So long as the assertion framework only threw on failure, the reporting would work out OK. We could even create a special list of Type names in the settings for those exceptions that should be reported as failures rather than errors.

Now for the other exceptions. All NUnit exceptions that derive from ResultException set the result of a test. That includes AssertionException, SuccessException, IgnoreException and InconclusiveException.

SuccessException is pretty rare. The only way to get it is to use Assert.Pass. NUnit would work fine with any 3rd party assertion framework that didn't do this.

IgnoreException is slightly more common. It is only thrown by Assert.Ignore. Again, a 3rd party couldn't do this unless they actually referenced the NUnit framework. Users's would be limited to ignoring tests statically. That's not a terribly big loss.

InconclusiveException is another matter. All Assumptions can throw it. Theory testing is based around it. A 3rd party assertion framework would be severly handicapped by the fact that it's assertions could not be used as assumptions.

Nevertheless, NUnit can still be used in a limited fashion with 3rd party assertion frameworks. The story is a bit different if you want to use the NUnit assertions for some other purpose. The framework with which you are using it would definitely need to understand all the exceptions that NUnit can throw. This doesn't have to require a reference: you could recognize the exceptions by their names. But the 3rd party test framework would need to understand some things about NUnit.

Looking briefly at Fixie, which you wanted to use with NUnit asserts, I'm suspecting that it can be customized to handle those particular exceptions. Take a look at how ExpectedExceptionAttribute is handled in some of the examples. A similar approach might be used with SuccessException. I don't know enough about it to say whether IgnoreException can be handled and I'm guessing that it doesn't really have a concept of Inconclusive.

Maybe the author can help us...

@plioi I really like what you've done. At times I miss the simplicity of NUnitLite. I do especially like the idea of making the framework configurable by establishing conventions in each test - maybe I'll do something with that!

Anyway, if @vgrigoriu is willing to spend time trying to get NUnit assertions to work with Fixie, I'll build him an assembly that just has the assertions. Would you be willing to work with us on this as well?

Charlie

**Comment by vgrigoriu** [comment]
@CharliePoole it would be great if you could do that. I already tried using NUnit assertions in Fixie tests and it worked, so having a separate assembly would be even better. Let me know if I can help in any way.

I don't entirely understand how theories & assumptions work, but it seems that making _that_ work with another testing framework would be considerable more work.

**Comment by CharliePoole** [comment]
@vgrigoriu We're working to get the second NUnit 3.0 beta out right now, so it will be a few days before I can spend any time on this. Here's what I suggest.

1. I'll create an experimental branch that splits the assertions from the framework. This isn't essential, of course, but it will eliminate the possibility of naming collisions.

2. You create a branch that contains all sorts of NUnit tests that should work under Fixie. IOW, it will be an integration test assembly.

3. We try to identify _precisely_ what works and what doesn't.

4. For stuff that doesn't work, we can consider patches to NUnit and/or Fixie to make it work. I have a feeling that many things, which don't work immediately, will be fixable through custom conventions in Fixie.

@plioi Does this sound to you like it makes sense?

**Comment by vgrigoriu** [comment]
Sounds good. Thanks for your support!

**Comment by plioi** [comment]
Short version: Your plan makes sense, and you've accurately identified the likely "impedance mismatch" between NUnit's and Fixie's kinds of test results.

Long version:

So far, Fixie has 3 possible results for a test: skipped (it was never run in any way), passed (it was executed and didn't throw), or failed (it was executed and did throw).  Custom convention authors can step in to say "hold on, this looks like a failure so far but I know better", as you see with the [ExpectedException] sample.  I have a similar plan for supporting Inconclusive soon, and in that case the Fixie convention author will similarly express some opinion of whether a test result should be characterized as Inconclusive.

Fixie's notion of "test failure" == "exception thrown" may just be too simplistic to motivate splitting NUnit into two assemblies.  It sounds like there are quite useful bits of information (like assertion counts) and quite useful features (distinguishing errors from failures) that NUnit framework can take advantage of, knowing its asserts are a "first class" citizen.

As you point out, SuccessException could be handled in a Fixie convention much the way that my samples mimic [ExpectedException].

I don't have a concept of IgnoreException. The closest concept I have is that convention authors can identify a test as skippable, in which case it literally does not run.  That doesn't really match up well with the idea of IgnoreException.

**Comment by CharliePoole** [comment]
@vgrigoriu It looks like splitting the two parts is more complex than I imagined. Which build do you want to use? I can limit the amount of work by only splitting that one.

**Comment by vgrigoriu** [comment]
I’d rather use 3.0, if it's the same to you.

**Comment by CharliePoole** [comment]
@vgrigoriu Yes, I meant what build of the 3.0 framework. We have builds for .NET 2.0, 4.0 and 4.5 plus portable, silverlight 5.0 and compact framework 3.5. All the files have to be linked or copied for each one, so I prefer to start with a single version.

**Comment by vgrigoriu** [comment]
Oh, I see. 4.5 then.

**Comment by CharliePoole** [comment]
@vgrigoriu OK, I'll focus on 4.5 in that case.

I'm leaving on a trip in a few days and will be travelling for a month. Having looked at this moreclosely, I can see that splitting the two assemblies in NUnit is more than a few days work. So what I'll do is create a standalone assertion assembly without worrying about how NUnit would use it. IOW, it will use NUnit code but be entirely separate and won't have any reference to the framework. Or so I hope. :-)

@plioi Thanks for your comments. I'm sure @vgrigoriu will appreciate any help you can give him in creating custom conventions for working with NUnit. Maybe they can eventually be published somewhere.

NUnit as you know has four basic outcomes, with the possibility of subtypes: Passed, Failed, Inconclusive, Skipped.

Passed is always good (green)

Failed is always bad (red). It has subtypes Failed:Error, Failed:NotRunnable and Failed:Cancelled.

Inconclusive is neither good nor bad and is often hidden in the UI.

Skipped is a mixed bag, which leds to confusion: Skipped:Ignored is a warning while just plain Skipped is continued neutral. (You get Skipped, for example, if a Platform is excluded by the test.)

We used to worry about whether a test actually ran. We no longer do that. A test can be Ignored via an attribute or via an exception. In either case, we record it as not having run and the assumption is that the result is the same. Normally, you would use Assert.Ignore in the SetUp after checking something that needs to be checked.

When I get to the point of making the nunit framework use a separate assertion library, I'll undoubtedly be looking at how you do it in Fixie.

**Comment by CharliePoole** [comment]
@vgrigoriu I have created a branch with an additional standalone nunit.assertions assembly. As I explained above, NUnit is not actually using it. It is purely intended for your experiments.

It's at
    https://github.com/CharliePoole/nunit/tree/separate-asserts
which you will need to build, of course.

**Comment by rprouse** [comment]
@JakeGinnivan, based on #1243, you would prefer that NUnit be split in two so that you have the option of not referencing the asserts assembly to prevent your team from using the standard NUnit asserts and force them to use the Shouldly asserts?

Shouldn't this be a problem of coding standards and code reviews? We don't ask Microsoft to turn off language features like goto that we don't want our team to use :smile:

**Comment by JakeGinnivan** [comment]
@rprouse it comes down to the fact that choosing the test framework and the assertion library are two separate decisions.

I currently do use code reviews to pick this up but it is something that I don't think I should need to. And often it is easier to switch to xunit.core to reduce the surface area of the test framework than to pick up these things after the fact then get someone to change.

**Comment by CharliePoole** [comment]
@rprouse Like you, it bothers me that somebody would want to have a feature in order to force the team to work in a certain way. In fact, the word team shouldn't really be used in such a situation, except in the case of a team of draught horses. :-(

That said, how @JakeGinnivan might make use of the feature is separate from the value of the feature itself. It was requested originally because the requestor wanted to use NUnit assert syntax in a non-nunit context. I like it based on the principal of separation of concerns and what it might do for future development of NUnit. It's a fairly big thing, however.

**Comment by JakeGinnivan** [comment]
> it bothers me that somebody would want to have a feature in order to force the team to work in a certain way

It isn't about forcing people to work in a certain way, it is about codebase consistency. I just don't see why if the team has chosen to use a different assertion library over the bundled assertions that it is strange to ask for those assertions to not be bundled.

**Comment by CharliePoole** [comment]
Sorry @JakeGinnivan I only commented about how it sounded to me, in your description. It independently struck @rprouse the same way, so there was something communicated, whether intended or not, whether correct or not. This is basically email, after all.

That's all beside the point of whether we will have the feature, as I also tried to make clear in my comment. It remains an "idea" because we have not really looked into what it will take to do it. My gut feel is that it will take non-trivial effort. The two potential components have been growing into each other for a long time. Separating them would probably improve the code, but would take time away from other stuff. I think a bit of separation internally might be the first step.

**Comment by JakeGinnivan** [comment]
No problems, my response wasn't meant to sounds defensive either, I was just clarifying.

Another example of when separation is useful is if I want to use xUnit's assertions but nUnits test framework. At any rate, I just wanted to open a discussion to let you know this is something which would be nice but not critical. It is just one of the factors I think about when choosing a test framework at the beginning of a project.

**Comment by rprouse** [comment]
@nunit/contributors do you think we should promote this from an idea to the backlog?

My vote is to close.

**Comment by CharliePoole** [comment]
I think splitting up the framework in a way that is similar to what the xunit.net guys have done would serve us well in the future. However, it's a big job and only has limited payback directly to users. In some ways, this is like the concepts involved with developing NUNit 3. It required a complete rewrite of many things just to get to the same place as NUnit 2.6.4. Maybe this is an idea for some vague future NUnit 4. :-)

**Comment by ChrisMaddock** [comment]
I agree. There doesn't seem to be enough motivation behind it to justify the work right now.
