### ISSUE TITLE
OSPlatform.IsMacOSX doesn't work

### ISSUE THREAD

**Issue by chrisvire** [nunit/nunit#515]
The implementation of OSPlatform.IsMacOSX depends on Environment.OSVersion.Platform == 6 on MacOSX.  As of Mono 2.2, the implementation changed to NOT return this value:

http://www.mono-project.com/docs/faq/technical/#how-to-detect-the-execution-platform

"Notice that as of Mono 2.2 the version returned on MacOS X is still 4 for legacy reasons, too much code was written between the time that the MacOSX value was introduced and the time that we wrote this text which has lead to a lot of user code in the wild to not cope with the newly introduced value."

Here is a discussion about this issue and a solution to call uname libc function to determine Mac vs. Linux.
https://mhut.ch/journal/2010/01/25/integrating_gtk_application_mac

**Comment by chrisvire** [comment]
Also, there is an internal class in Mono that determine whether on MacOSX

https://github.com/mono/mono/blob/master/mcs/class/System/System/Platform.cs

**Comment by rprouse** [comment]
Thanks for the info. I am setting up a Mac for iOS work, so will take a
look at this when it is ready.

**Comment by chrisvire** [comment]
We are still using NUnit 2.6.4 for our projects.  Could I submit a PR for nunitv2?

**Comment by CharliePoole** [comment]
Please do. You should submit it to the nunitv2 project, of course, not this
one. If it looks good, we'll merge it but it's unlikely that it will ever
see a binary release. NUnit 2.6.4 is currently the last binary release we
plan - although that could always change.

Of course, we'll probably also port the fix to NUnit 3.0, which will gain
it wider use. Be aware that the fix has to work on all our platforms,
including Windows and Linux, Mono and .NET. The checks need to be done at
run time, since we don't do separate builds for those platforms. For
Silverlight and CF, they should be conditioned out, since neither of those
builds can be run on a Mac.

**Comment by CharliePoole** [comment]
Correction: the comments about Silverlight and CF only apply to NUnit 3.0.

**Comment by oznetmaster** [comment]
It should probably not be commented out, but should be conditioned to return false?  That is what I currently do in my CF build.

**Comment by CharliePoole** [comment]
As I said, it doesn't really apply to NUnit 2.6.4, which is what he is working on. 

When we get to 3.0, any special code for unix, such as the uname call, should be conditioned out of the CF build.

IsMacOSX and IsXbox don't even exist in our current 3.0 CF build. You're welcome to create a fix that makes them return false as in your private build.

**Comment by oznetmaster** [comment]
Does not compile under CF build.
