### ISSUE TITLE
Investigate Generic Usage in CF builds

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#523]
There seems to be some discrepancies between the actual implementation of generics (and generic related reflection) in CF and the documentation of that implementation.

There is a need to reconcile the two so that the maximum functionality around generics is available in the CF build.

**Comment by CharliePoole** [comment]
I'll use this issue to document differences.

The issue arose because I was using Type.GetGenericTypeDefinition() in the CF build. There is some no reference we can find in the docs to the method existing in CF and CF has issues with open generic types. However, the code works.

Among things you can't do with open generic types in CF, we know that calls to GetGenericArguments throws an exception when called on a generic type. That has led to many workarounds in the CF code.

Here are some references about the implementation of generics in CF:

  * http://blogs.msdn.com/b/romanbat/archive/2005/01/06/348114.aspx

  * https://msdn.microsoft.com/en-us/library/ms172523%28v=vs.90%29.aspx

**Comment by CharliePoole** [comment]
@oznetmaster Any progress on this issue?

**Comment by CharliePoole** [comment]
@oznetmaster  I'm leaving this on the backlong, but let's discuss what you want to do about it and if it should really stay here.

**Comment by CharliePoole** [comment]
@oznetmaster You assigned this to yourself about 14 months ago. If there's nothing you want to do with it, please close it.

**Comment by rprouse** [comment]
This issue has been inactive and no further comments despite requests. Closing.
