### ISSUE TITLE
NUnit should provide navigation data for tests

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#535]
As suggested in #534 it would be desireable for NUnit to provide the file and line number of the source where a test is defined.

**Comment by rprouse** [comment]
@CharliePoole, with the work that you did for the adapter with Cecil, this might be easier now and would make it unnecessary to do in each of the adapters. Admittedly, the .NET Core adapter was easy since it provides an interface, but...

If we decide to do this, we should evaluate the performance cost. I also think we need PDB's, so the info may not always be available.

**Comment by CharliePoole** [comment]
Right... the first part is why it's here. The second is why it's merely an Idea. :-)

The negative side is that it's the framework that discovers tests, while it's the engine that uses cecil. So the engine would either have to intercept and add info to every test that passes through it (not so good) or we would simpy provide it as a service. The adapters would not change fundamentally, they would just ask the engine where they now ask an internal class.

**Comment by rprouse** [comment]
@CharliePoole does this belong in the console repo now?

**Comment by CharliePoole** [comment]
@rprouse It does... moving...

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit-console #115](https://github.com/nunit/nunit-console/issues/115) via [**ZenHub**](https://www.zenhub.com/)
