### ISSUE TITLE
Assert.ThrowsAnyAsync

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#547]
Xunit has some asynchronous assertions, like Assert.ThrowsAnyAsync.

Is 3.0 going to have a similar capability?

**Comment by CharliePoole** [comment]
There are no plans. Nobody has requested the feature yet. ;-)

As a question, I think we could close this, but I suspect you actually want the feature after more. Why not edit the description to indicate what you want to have added and we can treat this as a feature request. You should describe how it works and why it might be needed, otherwise we would all have to read the xunit code or docs to understand the request and - what is worse - we might come up with different interpretations. Let's get on the same page and if everyone agrees we can schedule it for a milestone.

**Comment by oznetmaster** [comment]
Actually, I have no idea what it does :(  I am migrating a very large Xunit test suite to NUnit, and it contains a lot of these.  I was hoping someone here would know what it meant…

**Comment by CharliePoole** [comment]
In that case, let's take a look at xUnit (they just released version 2.0) to see if we want to adopt any features, including this one. Given the workload, I think that has to be after 3.0.

**Comment by oznetmaster** [comment]
I have been trying to find the Xunit documentation.  Do you happen to know where it lives?

**Comment by oznetmaster** [comment]
We actually seem to have the same thing, only implicitly, not explicitly.  We detect that the code provided is async code, and handle it accordingly.  Adding these explicit asserts would only be for documentation and strict type confirmation.

This may be unnecessary or undesirable?

**Comment by CharliePoole** [comment]
In that case, it does seem unnecessary to me. I wonder if they implemented it this way because it was easier or because they felt it was better.

**Comment by rprouse** [comment]
I am going to close this. We can reopen if there is any demand for the feature.
