### ISSUE TITLE
Strange behavior in PARALLEL build

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#552]
As I have been testing the PARALLEL CF build, I observed a inconsistent result.

A number of tests were failing sometimes, and working others, seemingly randomly.

I then ran the same test on the full desktop build, and saw the identical problem!

These test are in the Attributes.TimeoutTests.

I then ran the tests with -workers=0.  The problem did not go away.  In the desktop build, it actually occurred more often.

In debugging, I see that the testfixture (with the timeout, for example "InfiniteLoopWith50msTimeout"), is run on one thread, and the test itself is running on another thread, which is correct (test fixtures with timeouts always run on a new thread).

The problem seems to be that the TestBuilder.RunTest method returns before the thread running the test fixture completes.  So any assertions after the RunTest call that reference the test fixture have random results, depending on where the thread running the test fixture has gotten to.

Has anyone else seen this?

Is the normal desktop build test ever run with -workers=0?

**Comment by CharliePoole** [comment]
We do have periodic problems with the timeout tests. 

TestBuilder.RunTest could be the culprit for any tests where we initiate a second level test using that method. I'm surprised it's returning prematurely though, since it does a busy wait on the test status.

I use the -workers=0 quite a bit when debugging. Are you seeing different behavior in when this is used?

**Comment by rprouse** [comment]
I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.
