### ISSUE TITLE
Test-Suite name in result xml for parameterized test  generated by nunit-console runner is incorrectly taken as method name

### ISSUE THREAD

**Issue by shreyasGit** [nunit/nunit#569]
We are using parameterized tests with TestCase Attribute.

After executing theparameterized  test cases using  nunit-console ,in the result xml generated , in the test-suite tag  name  attributes comes as "Method name". for e.g

If i have a class named "Moduletests"  marked with TestFixture attribute, all the test cases in the class appear in result xml under suite named as "ModuleTests".

but if i have a parameterized test method named  ""ParametrerizedMethod" in class , the suite name in result xml comes as "ParametrerizedMethod".

this causes problem while reporting coz all tests for a module are in this same class, but they appear in report under different suites.

Please help

**Comment by CharliePoole** [comment]
The "ParameterizedMethod" suite is nested under the "ModuleTests" suite. We create a suite for any method with multiple test cases. We don't actually have to do it that way, but it's the way NUnit has historically saved results in V2. It comes from the fact that we display the tests grouped in the same way in the GUI.

I take it you are trying to issue a report that lists test methods under classes. In the latest builds, the test has "classname" and "methodname" attributes. Does that help with your problem?

**Comment by shreyasGit** [comment]
Ya it would help. Thanks for you reply

**Comment by shreyasGit** [comment]
in which version of Nunit will these attributes be available? i am using 2.6.3. and site has 2.6.4 latest

**Comment by CharliePoole** [comment]
My reply related to NUnit 3.0, since this issue is against the repository for NUnit 3.0. "Latest build" meant the latest source code in the repository as well as  the NUnit 3.0 beta 1 release.

For NUnit 2.x, there's really no option except to program around the problem. If the method you are looking at is under a suite with type="ParameterizedMethod" then go up one suite further to find the fixture. A more general approach would look at the parent suite recursively until one with type "TestFixture" is found.
