### ISSUE TITLE
Test Ids Are Not Unique

### ISSUE THREAD

**Issue by chris-smith-zocdoc** [nunit/nunit#582]
When using multiple processes or multiple domains, the test ids are not unique.  This is an issue for identifying unique tests from the GUI and in the TC service messages. 

One possible solution would be to prefix the id with some kind of process/domain id. 

For example using the default single process, separate app domain you could get the following pattern
`p1-d1-testId`

Running `process=Multiple` or `process=Parallel` you might see the following
`p1-d1-testId`
`p2-d1-testId`

If you used a mixture of project files and assemblies, where the project creates additional processes/domains, for 1 project w/ one assembly and two addition assemblies you might see
`p1-d1-testId` // project created additional process and domain
`p2-d1-testId` // assembly in its own process also has a d1

Another solution could be to prefix the test id with a identifier for the assembly that the test resides in. A hash of the assembly or a guid could be potentially be used here. This solution should require less coordination between processes/domains.

**Comment by CharliePoole** [comment]
I called this a task since it really doesn't give any benefit by itself, but merely enables us to do other things that require a unique id for each test within a run.

Currently, id is unique to each AppDomain in which we run, because it is based off the static field Test.nextID in the framework. If we use a prefix, we need to at least give a separate prefix to each AppDomain. However, if we give a separate prefix to each assembly, no particular harm is done even if several assemblies are running in a common AppDomain. That approach would mean that we would not have to vary the algorithm depending on the process and domain options selected by the user, which I think is a useful simplification.

There is a one-to-one correspondence between drivers and assemblies, so the prefix would have to be passed to the driver. Every driver would have to know what to do with it, so this requires changing the IFrameworkDriver interface as well as every implementation. Since the value has to be an int for the NUnit V2 runnerId, it should be an int for every case. NUnit 3 can create test ids like
"mmm-nnn".

Since the driver is initialized by use a runner that is executing a test package. We will have to associate the runner id or prefix with every test package.

It's all pretty complex, so it should be implemented a step at a time, with tests. I can see doing it top-down, starting with the master runner, or bottom-up, starting with the framework.

@chris-smith-zocdoc If this seems like more than you care to tackle right now, someone else (probably me) can look at it. We definitely need it.

**Comment by chris-smith-zocdoc** [comment]
@CharliePoole This is certainly more involved and requires a more comprehensive understanding of the codebase than I currently have. If you want to take a look into this I would appreciate it!

**Comment by CharliePoole** [comment]
I'll work on this myself.

**Comment by CharliePoole** [comment]
The framework now uses any prefix passed to it to create ids - on the issue-582 branch, that is.

Now it's a matter of uniquely identifying each assembly and passing the correct identifier to the framework. This is tricky because the creation of the driver for each assembly may take place in a separate process or AppDomain from the original one. So the identification has to be done early and passed down the line. 

After trying a few other things, I think I've hit on an approach: Each TestPackage created should get a new id. So long as all packages are created up front, this will result in unique identifiers. We don't currently create all packages up front, but I think that's how it should be done.
