### ISSUE TITLE
Xamarin Studio nunit paired down? 

### ISSUE THREAD

**Issue by bfloydgsn** [nunit/nunit#596]
http://www.nunit.org/index.php?p=testCaseSource&r=2.5.10

Allot of features of NUnit aren't available in the version shipped with Xamarin Studio, but the assembly says it's nunit 2.6.

Do you have paired down versions? Also, if I want to use the full version should I just include a local copy with my project? Is there anyway to update it within Xamarin/MonoDevelop without needing to include it with each project?

**Comment by CharliePoole** [comment]
NUnit 2.6 is not the latest version of NUnit. So if that's what is being used, then it could easily be missing some features. Xamarin / MonoDevelop comes with an integrated NUnit extension.  AFAIK, you have to use the version of NUnit they integrated.

OTOH, you can certainly install NUnit separately under Mono and run tests with it outside of MonoDevelop.

**Comment by rprouse** [comment]
The version of NUnit that currently ships with Xamarin is a modified version of Nunitlite that the Xamarin team ported. I am currently working on a version that uses the full NUnit 3 portable assembly. It is currently working, but still needs some work to productize it. If you want to start using it, let me know and I will get you started. I could use the help and feedback.

**Comment by CharliePoole** [comment]
I believe you end up with both versions of NUnit, used for different purposes. At least the Open Source version of MonoDevelop ships with an addin that runs regular NUnit tests. The modified NUnitLite is used for Android and IoS. Since he referred to NUnit 2.6, I assumed that's the one he was using. 

@bfloydgsn If you're developing for IoS or Android, pay attention to Rob. If for desktop, to me. :-) If you're developing for devices, the 2.6 assembly you saw has nothing to do with it.
