### ISSUE TITLE
Improve missing or boilerplate xmldoc

### ISSUE THREAD

**Issue by sean-gilliam** [nunit/nunit#600]
A lot of the xmldoc is great, succinct and very informative. However there is still GIANT swathes of missing or bolierplate xmldoc that could be greatly improved. Most of the boilerplate look to be stubs to be filled in later.

Not to pick on one class in particular, but if you take a look at for example src/NunitFramework/framework/Constraints/MsgUtils.cs

``` csharp
/// <summary>
/// Clip the expected and actual strings in a coordinated fashion, 
/// so that they may be displayed together.
/// </summary>
/// <param name="expected"></param>
/// <param name="actual"></param>
/// <param name="maxDisplayLength"></param>
/// <param name="mismatch"></param>
public static void ClipExpectedAndActual(ref string expected, ref string actual, int maxDisplayLength, int mismatch)
```

I know there are more pressing issues at hand, but it would be nice to have clean API docs :)

**Comment by rprouse** [comment]
I agree with you, but I think our first priority should be the XMLDOCS for the APIs that consumers of NUnit use like the assertions, attributes and constraints.

MsgUtils is public so that we can test it, but I am pretty sure it is only intended to be used internally. It should still have proper documentation to make it easier for contributors to NUnit, but that is lower priority.

Expanding on this idea, it might be a good idea to reduce the framework's public facing API by making utility classes like this internal and exposing them to the test projects using `[assembly: InternalsVisibleTo(...)]`.

**Comment by oznetmaster** [comment]
Yes, they should be internal and exposed by usin the InternalsVisibleTo attribute.

---Sent from my iPad

On April 21, 2015 at 4:57:11 AM GMT+8, Rob Prouse <notifications@github.com> wrote:I agree with you, but I think our first priority should be the XMLDOCS for the APIs that consumers of NUnit use like the assertions, attributes and constraints.  MsgUtils is public so that we can test it, but I am pretty sure it is only intended to be used internally. It should still have proper documentation to make it easier for contributors to NUnit, but that is lower priority.  Expanding on this idea, it might be a good idea to reduce the framework's public facing API by making utility classes like this internal and exposing them to the test projects using [assembly: InternalsVisibleTo(...)] .  —Reply to this email directly or view it on GitHub.

**Comment by CharliePoole** [comment]
@sean-gilliam The example class is easy to understand if you know the history. NUnit has many methods with public visibility that are not considered a "published" API. With NUnit 3.0, many of those methods and classes moved into the framework assembly from the core assembly, which no longer exists. That means they fall under the requirement to have XmlDocumentation, even though they are not targetted at users. We have often dealt with that by providing empty doc comments, to avoid getting a warning message on compile.

Bear in mind that it was only last year that we stopped building NUnit for .NET 1.1. So using InternalsVisibleTo has never been an option for us. I think it is now. @rprouse and @oznetmaster can you confirm that it works on all our platforms?

It seems to me that providing detailed xml comments for internal classes is usually not necessary, but it should probably be done where the comments will help us.

It's also my view that we should _not_ follow a strict template for Xml docs, but should only include those elements that actually add value.

What do others think? If we want  to go the route suggested by @rprouse should we do it all at once or a bit at a time as we make other changes?

**Comment by CharliePoole** [comment]
An additional comment: If we add API-style docs to classes not intended to be used that way, might we not be sending the wrong message?

**Comment by rprouse** [comment]
I will try InternalsVisibileTo in the Portable version of the framework. If it works there, it works on all supported platforms except possibly CF. @oznetmaster, can you confirm for your platform?

**Comment by oznetmaster** [comment]
I think that making these internal and then using the InternalsVisibleTo attribute makes a lot of sense.

**Comment by CharliePoole** [comment]
I'll do a small experiment and push a branch so we can see how it works out.

**Comment by sean-gilliam** [comment]
Let me start of by saying that I use NUnit daily at work and what a great framework it is. I'm a stickler when it comes to documentation as my github contributions mainly show :) So when I was looking through the NUnit source I noticed these irregularities in the xmldocs and wanted to shine a light on it.

Leave it to me to pick a horrible example but I think that illustrates how a newcomer developer can get confused. Looks like this has sparked a discussion at least which was what I was hoping.

**Comment by CharliePoole** [comment]
You managed to illustrate the fact that it's confusing, looking at the code, to determine what methods are intended for public consumption. I realize now that the presence of XML documentation is a part of that confusion. So, you've done a good thing. :-)

It's possible that we may want to generate part of our documentation from the XML comments at a future point. If we were to do that, the presence of documentation for methods like the one you chose would be especially confusing, although I suppose we could remove them as a part of the process of generating the docs.

Be that as it may, we'll use this issue to come ot some general conclusion and then apply the standards we decide on to reviewing your PR.

**Comment by elbaloo** [comment]
I do not think that by adding API-style docs to classes not intended for public usage would send a wrong message. I'm all for adding it and we can always include a note "not intended for consumers" or something like that in case you don't want to go with InternalsVisibleTo or even if you do.
Good documentation does no harm at all, even if internal.

**Comment by CharliePoole** [comment]
Hi Victor,

Be aware that the alternative to triple-slash Xml doc comments is not no
good docs. :-)

I think of the Xml doc comments as being for folks who work without seeing
the source code. Anyone working on the NUnit source code needs to have
documentation for everything they might call, but not necessarily in that
format. Users of NUnit, OTOH, are programmers who don't (necessarily) look
at NUnit's code. They need the docs that come up in Intellisense.

Of course, we could use /// comments for developers as well and that
wouldn't be a problem _except_ possibly in the nunit framework, which has
both categories of user.

That said, I do like your point that we can simply add something right in
the comments that says "not intended for consumers." In fact, we frequently
have a comment that says "Public for testing only" but it's usually just a
normal comment. Probably, it should be a doc comment in many cases.

Charlie

**Comment by CharliePoole** [comment]
I took a look and found that the framework is the only assembly we are currently signing. For NUnit 2.x we signed most things but so far not signing the console or engine or nunitlite assemblies has not caused any issue. Perhaps we should stop signing the framework as well, making it much simpler to use InternalsVisibleTo.

**Comment by rprouse** [comment]
I think we need to sign at least the framework. Check the following user story and let me know if the logic is incorrect. It is similar to what we are proposing for NUnit and it is the case where I work unless I am missing something.

1. I am working on a project were the code is signed.
2. I have internal methods that I want to test. I do not want to make them public.
3. To test those internal methods, I make them InternalsVisibleTo my test assembly.
4. Because my assembly is signed, my test assembly must be signed for the InternalsVisibleTo.
5. A signed assembly can only reference other signed assemblies therefore nunit.framework must be signed because my test assembly is signed.

I think testing internal classes from strong-naming (signing) is common enough that we need to support it. We don't have to like it though :smile:

**Comment by CharliePoole** [comment]
Yes! I'd forgotten about that use case. I agree we have to support it.

**Comment by CharliePoole** [comment]
@rprouse I think we need to look through this and see if we have either done or created a separate issue for each sub-item proposed. If we have, we can close this.

**Comment by rprouse** [comment]
@CharliePoole isn't this up to one of us going through the API and deciding what to make internal now that we allow InternalsVisibleTo for our tests? Either that, or we could just opt to do nothing in this issue and clean up code as we find it while working on other issues. That would probably be my preference.

**Comment by CharliePoole** [comment]
Me too. I just wanted to point out it's still sitting here.

**Comment by rprouse** [comment]
Since we both agree, I am going to close this issue.
