### ISSUE TITLE
Create New NUnit Website on Github

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#617]
The existing NUnit.org website has been significantly reduced in size by removal of the documentation. We would now like to move to hosting it on GitHub using Jekyll for stylistic compatibility across pages.

The current site at http://nunit.org uses html fragments to represent each page. We use PHP to embed those fragments in the html page we emit. We also have the capability to generate static html from the fragments if necessary, but most probably the html fragments themselves would be the best thing to use to create the new pages on GitHub.

The site currently has four top level pages: Home, Download, Documentation and Contact.

The Home page contains the news items. It would be most convenient if the news could be placed in a separate file to facilitate editing. It also links to the Donations page and contains a Donate button. The Donations page should also be converted.

The Download page needs to be re-designed. It uses too much space for listing very old downloads and gives much more explanation than is needed about the different types of downloads. It may make more sense to link to a separate page for older downloads.

The Documentation page will no longer be needed since the documentation has now been moved to the wiki (current docs) or to a separate website (archival documentation). We could have a separate page to link to these two locations, but that seems like one click too many for the most common use case. The wiki docs could, of course, link to the archived documentation or we can discuss other options.

The contact page needs to be reviewed but it probably contains what we want.

**Comment by agray** [comment]
@CharliePoole.  Which repository contains the content for http://nunit.github.io/nunitv2 ?

I am not seeing a ghpages branch anywhere.

**Comment by CharliePoole** [comment]
Like I said: nunitv2: https://github.com/nunit/nunitv2/tree/gh-pages

Given any repo rrrr, belonging to organization oooo, the url for a gh_pages website will always be http://oooo.github.io/rrrr

Note, however, that that site is not connecterd with this issue. We want the nunit 2.x archival pages under the nunitv2 repository but we don't want the nunit website there.

**Comment by agray** [comment]
I have done some more work on this this morning.

[http://agray.github.io/nunit](http://agray.github.io/nunit)

The structure is in place. I open it up to everyone else to add content to it.

I switched from the red to the green theme as I think it better suits the new logo.

**Comment by rprouse** [comment]
@agray, I like the general theme, but with some modifications.

- The hero image at the top is very large and we should think of something that is more NUnit/coding specific
- Documentation link should go to the wiki documentation
- Recent news should probably just go to the recent news on the front page
- Not a requirement, but it would be nice to have a GitHub pages based blog section for longer form announcements.
- We should probably remove the pictures in the recent news entries. We could also delete the 'by author'
- We can probably strip out the links part of the footer since the only thing there that is not redundant is the Follow Us. Those could be moved elsewhere. I would like the Twitter link to be more prominent. I am trying to revive it's usage.
- Should Download just go to the GitHub releases page? Do we need to maintain old releases?

**Comment by rprouse** [comment]
We could also use the space in the hero image more effectively. Maybe move the What is NUnit text up and replace the "C# Unit Testing Framework" with it. Then we could add a series of buttons for Download, GitHub, Learn More (About?).

Actually, I wonder if the Learn More should just lead to the documentation and we can add the info about donations, contributors, the license, etc there? We could then pull the recent news up to just below the hero image to make it more prominent.

Maybe I will fork and make the changes there so people can see what I am thinking.

**Comment by ChrisMaddock** [comment]
This is now done and live!
