### ISSUE TITLE
ExpectedException Message should be compared like Assert.AreEqual for Strings.

### ISSUE THREAD

**Issue by salsolatragus** [nunit/nunit#626]
Assert.AreEqual has this nice feature that it displays whitespace characters to make it easier/possible to find differences between the expected and the actual string. For the expected message this is unfortunately not the case. Wich leads to situations like the following (hint: there's an additional newline at the end of the actual message):
![screenshot 2015-04-30 08 24 16](https://cloud.githubusercontent.com/assets/154050/7407521/b510ef20-ef13-11e4-9ca6-45ebc5af32a2.png)
Would be great if that could be fixed!
Thanks very much for you work.

**Comment by rprouse** [comment]
This sounds reasonable. I have set it as low priority because I think it is much less likely to happen than in equality assertions. Feel free to argue the point :smile:

I have put it in the future milestone only because I want to limit the 3.0 release so that we can get it out as soon as possible. Anyone is welcome to submit a PR for this.

**Comment by salsolatragus** [comment]
Don't know if I'll ever run into that problem again ;) but I'll see if I can find the time to create a patch!

**Comment by CharliePoole** [comment]
Actually, based on the message, I think that this is NUnit 2.x and the message in question is specified on an ExpectedExceptionAttribute. Is that correct, @salsolatragus?

Since the attribute no longer exists in 3.0, I would either mark this Won't Fix or at the maximum add a test to verify that Assert.Throws and ThrowsConstraint both give a message similar to EqualConstraint. In fact, I have little doubt they do, since you use EqualConstraint to compare the message with the fluent syntax.

**Comment by voloda** [comment]
@CharliePoole This is a little bit off-topic. 

We have a code base using deprecated ExpectedExceptionAttribute and it will take some effort to edit existing tests to become compatible with new NUnit which I would see to happen.

Is there a way how to write a custom extension to support the obsoleted ExpectedException?

**Comment by CharliePoole** [comment]
@voloda https://github.com/nunit/nunit-csharp-samples/tree/master/ExpectedExceptionExample will get you started! See also https://github.com/nunit/nunit/wiki/Upgrading for a general guide to upgrading.

**Comment by CharliePoole** [comment]
@voloda Also: I think NUnit itself had a few hundred such tests. It took me an afternoon to upgrade them.

**Comment by oznetmaster** [comment]
After I had converted over 3000 of these tests, I got fed up, and added the ExpectException attribute sample into every subsequent test conversion.  Saved me days of work.  Should have done it initially.

 

I still think it should be in NUnit 3.0.  I find that I never have need for the specificity of the Assert.Throws.  All I ever seem to need to care about is the entire test.  But this has been decided :(

**Comment by salsolatragus** [comment]
Yes, it is. I followed a series of “repository has moved” hints from some former project website to this repository. Sorry if some changes between 2.x and 3.0 made this request obsolete. I didn’t check that.

Best, Sven

**Comment by CharliePoole** [comment]
@salsolatragus No problem. As you can see, this is a bit of a hot issue. 

When you get to the point of upgrading, you may want to consider using the sample code to create your own attribute if you have an extremely large number. But if it's not in the thousands, just do the rather mechanical conversion. The sample doesn't support anything except checking the type of exception, so you'll want to get rid of those message checks first.

**Comment by voloda** [comment]
@CharliePoole Thanks - that sounds great as a temporary solution

@oznetmaster We have this attribute in few integration style tests and it is rather a curse. When trying to convert some of them to the Assert.Throws() I realized that it after ages started throwing exceptions on different places. So while whole test worked at expected, the originally desired behavior was lost in dust.
