### ISSUE TITLE
Mono 4.0 Support

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#635]
Mono just released version 4.0 which supports C# 6 features and drops support for targeting 2.0, 3.5 and 4.0 assemblies. Older assemblies will still run under mono, but you cannot create them.

http://www.mono-project.com/docs/about-mono/releases/4.0.0/

Once this goes into widespread release, we are not going to be able to build NUnit for those targets on Mono. It will also likely break many of our CI environments.

We will need to decide how we build using mono going forward. Do we pare the nunit.linux.sln down to just targeting 4.5? Do we drop support for older frameworks?  At the least, we will need to modify our build targets for our CI servers once they update.

**Comment by CharliePoole** [comment]
Copied from my separate email:

Users of mono on Linux seem to mostly use the version of mono packaged with their distro. In fact, that's what I do. A smaller number try to keep up with the latest versions of they are available on the distro they use from some secondary source. Others build from source. This spread of usage is a consequence of the separation of packaging from program development in the Linux world.

My guess, based on the past, is that it could take a year or two for this change to reach the majority of users. That actually makes our job harder. I believe we will need to support both types of users.

For the framework, this means more builds. For the engine and runner it means multiple builds.

I'd like to get 3.0 and maybe even 3.2 out before trying to deal with this. We will have to decide whether to treat this as a variant build or go to v4 and continue to do maintenance on v3.

**Comment by akoeplinger** [comment]
While it's true that Mono 4.0 dropped the 2.0, 3.5 and 4.0 assemblies for runtime, they are still available to compile against (i.e. they are reference assemblies without runnable IL) when Mono is installed via the official Xamarin repositories. It might not be worth the pain modifying the build when people can just use the official Mono instead of what the distro packages.

**Comment by CharliePoole** [comment]
@akoeplinger The difficulty with developing a test application is that it has to support legacy stuff for a reasonable period of time, because users still have to test that stuff. So, my question is "Would that scenario support people who need to test 2.0-targeted apps under 2.0?

**Comment by akoeplinger** [comment]
@CharliePoole not sure I follow completely, but yes you can compile a library against the 2.0 profile on Mono 4.0.

**Comment by CharliePoole** [comment]
@akoeplinger So let's say we do that for the NUnit framework. Sombody installs NUnit on a machine that is using Mono 3.2.8 and uses it to run tests. Does that then work?

I ask because this seems different from building against a "real" (non-reference) assembly, but maybe that's because I haven't used them in this context before.

My experience with people working in IT (as opposed to startups and product companies) is that they are often constrained by company policy to use stuff that's a fair bit older than they would like to use.

**Comment by akoeplinger** [comment]
@CharliePoole It is no different than building against a real assembly. In the end all that gets embedded in the IL when you reference an assembly is this:
```
.assembly extern mscorlib
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 2:0:0:0
}
```

**Comment by CharliePoole** [comment]
That's good news. :-)

The bad news is if we want to support the scenario, we need to test it as well.

**Comment by akoeplinger** [comment]
Well you can continue to run your tests on Mono 3.2.8 on Travis, that should give the most confidence ;)

**Comment by CharliePoole** [comment]
Sure, but the most confidence would come from building under Mono 4 and then running under 3.2.8, in keeping with the principle that nothing is known to work unless you test it. :-) I doubt it's a real problem, however.

**Comment by CharliePoole** [comment]
@rprouse Have we basically resolved this? If not, what more should we do.

**Comment by rprouse** [comment]
I think we have. I believe our Travis build is currently building on the distro version of mono and the latest.

**Comment by CharliePoole** [comment]
I'll report this in the 3.0 release notes.
