### ISSUE TITLE
Config file name should be created according to specific rules and priorities

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/nunit#666]
Steps by priority to create name of the config file:
1. We use the config file from settings
2. We create the config file by path in the assembly name, if it exists
3. We use appBaseDir as path to the config file and use assembly name as a base for config file name

**Comment by CharliePoole** [comment]
I'd want to know what is being fixed here or what is changing - if anything - from the docs. Did some of the new tests previously fail?

Of course we can figure it out in review but if it's not in the issue everyone after us will have to figure it out as well.

**Comment by NikolayPianikov** [comment]
Hi, Charlie
My test shows that compatibility with previous versions was broken. This test checks case when appBase is defined but the config files for the test assemblies are located near with test assemblies. Test failed because AppDomain was configured to find config file in the appBase directory. I found following document: http://www.nunit.org/index.php?p=configFiles&r=2.2. It contains explanation: _if a single assembly is being loaded, then the configuration file is given the name of the assembly file with the config extension. For example, the configuration file used to run nunit.tests.dll must be named nunit.tests.dll.config and located in the same directory as the dll._ We could check existence of dll file before the defining app domain's configuration file (near dll, appBase dir, private bin dir), but I am not sure we can do this check. Also for multiple test assemblies we could recommend to use mode "--domain=Multiple" to load specific config file. And we could write to console output some information about AppDomain which are using for testing (may be it is working now). What do you think?

**Comment by CharliePoole** [comment]
For 3.0 the default is to run each assembly in a separate process. The default domain setting is also Multiple so the issue of multiple assemblies in a domain can only come up if the user forces them into a domain.

**Comment by NikolayPianikov** [comment]
What about compatibility?

**Comment by CharliePoole** [comment]
@NikolayPianikov Regarding compatibility... NUnit 3.0 is a major version change and it has been announced since 2008 (an embarrassingly long time ago) as having _some_ breaking changes.

The change in defaults for the ProcessModel and DomainUsage values has been decided explicitly because it simplifies use of the options for users. Most users should not have to change the options except when debugging, which is simpler using a single process.

The problem you address here, having to do with the location of the config file is not a planned change but only an error.

I'm not sure... does that answer your question?

**Comment by CharliePoole** [comment]
@rprouse I haven't reviewed the code but I can if you need a second person.

We should be sure to check what happens if the user specifies the config file in the settings as just the file name without a full path. First, what do we want to happen in such a case? Second, what is happening?

**Comment by NikolayPianikov** [comment]
As I mentioned from my point of view we should have following order of analyse:
1. We use the config file from settings if it exists - it goes without saying
2. We create the config file by path in the assembly name, if the path of testing assembly exists (if there is invalid path we can't run any tests for this assembly)
3. We use appBaseDir as path to the config file and use assembly name as a base for config file name in other cases

Here are the cases which I found:

[TestCase(@"file.config", @"file.dll", @"d:\", true, @"file.config")]
[TestCase(@"file.config", @"", @"d:\", false, null)]
[TestCase(@"file.config", null, @"d:\", false, null)]
[TestCase(@"file.config", @"", @"d:\", true, "file.config")]
[TestCase(@"file.config", null, @"d:\", true, "file.config")]
[TestCase(@"", @"c:\file.dll", @"d:\", true, @"c:\file.dll.config")]
[TestCase(null, @"c:\file.dll", @"d:\", true, @"c:\file.dll.config")]
[TestCase(null, @"c:\file.dll", @"", true, @"c:\file.dll.config")]

First param is config file from settings
Second is assembly name (with or without path)
Next is: string appBaseDir
Last is expected config file name

We should check several cases and one of of these cases is:

- there are several testing assemblies in the different directories
- each assembly has own configuration file in the different directories
- we assume that each assembly will be loaded in a separated app domain by default

User should have ability to run tests without the process of copying of configuration file to the some directory (appBaseDir). appBaseDir - from my point of view it is just current directory for specific application domain. And .net believes the configuration file has the same name like the related assembly, including the path (plus .config extension).

If we leave it as it is there is no simple ways to run tests in the several directories. This is only my subjective opinion of course

**Comment by rprouse** [comment]
This sounds reasonable, let me review the PR.

**Comment by CharliePoole** [comment]
I continue to wonder about the use of the appbase. This isn't consistent with what the docs call for and I still haven't seen an explanation as to why this should be the default.


Of course the "same directory" as the assembly will usually be the appbase but not always.

**Comment by NikolayPianikov** [comment]
@CharliePoole could you suggest way how I can sort out the following scenario:
- User can specify more then one test assembly
- User sometimes would like to start test related to the config files for some assemblies
- User can specify path to the NUnit-console.exe (and we should not forget about all dependencies, config files, and sub-directories of NUnit directory)

TC starts nunit-console using following command line:
<path to NUnit>\nunit-console.exe <temp path>\project.nunit --work=<path to NUnit> --noresult --framework=4.0

Sample of file "project.nunit":
<NUnitProject><Settings activeconfig="active" appbase="<path to NUnit>"/><Config binpathtype="auto" name="active"><assembly path="<full Path to test assembly 1>"/><assembly path="<full Path to test assembly 2>"/></Config></NUnitProject>

**Comment by CharliePoole** [comment]
Let's start with one assembly on the command line. If the user specifies no config, we use file.dll.config in the same directory as the assembly. This may or may not be the appbase. Do you agree?

If the user specifies a file name, without a path, then I think this should also be found in the same directory as the assembly, since that is the normal case.

I believe you are saying that IF the user specifies an appbase on the command-line, then the above cases should be relative to the appbase. Am I right? I think this would be a change from NUnit 2.x behavior, which is OK only if we are convinced it's better. If so, we would have to add it to breaking changes.

I think NUnit projects are an entirely different issue. We have said we are changing the naming of the config in this case to be project.nunit.config but other issues are not resolved. According to our old practice, it is _not_ possible to have separate configs for each assembly under an NUnit project. We may want to change this, but I think it's a separate issue.

@NikolayPianikov It's very good that you are thinking so far ahead. OTOH, we seem to have learned in this project that we function best if we subdivide issues and solve them one at a time with a closer focus. So I suggest getting a solution for assemblies first and to worry about projects after we finalize any enhancements to what an nunit project may contain. So long as what we do only adds to what has gone before I think this is OK (i.e. it's not wasted effort).

**Comment by NikolayPianikov** [comment]
OK, let's leave it as is - we will not merge this PR. I turn off the NUnit test for several assemblies with their config files. If a user wants to use this scenario he divides this build step and he uses own config files for each build step. If there are any issues, we will think how to solve them.

**Comment by CharliePoole** [comment]
@NikolayPianikov I hesitate to drop the PR before I have even understood what problem you are trying to solve! Can you tell me exactly what is incompatible with 2.x? I see your test cases above but I don't understand which ones are failing for you that passed in the older version.

Beyond compatibility, we can of course make improvements, but I am trying to separate the two things in my mind.

**Comment by NikolayPianikov** [comment]
Let it be as it is, I think we can close this issue

**Comment by rprouse** [comment]
@NikolayPianikov, thanks, I am going to close the issue and the PR then.
