### ISSUE TITLE
Running from console on visual studio solution fails due to non test assemblies

### ISSUE THREAD

**Issue by tburnett80** [nunit/nunit#668]
I am running my tests via mono on ubuntu and the tests are being found and passed just like they are from windows when I run them in NCrunch or the test runner in visual studio, the problem is my tests are being marked as failed because of the non-test assemblies containing the code being tested. Is there a way to ignore these NotRunnable assemblies to keep it from failing the tests?

![capture](https://cloud.githubusercontent.com/assets/4324080/7869542/ff137ec6-0548-11e5-8ca3-79c44b96790a.PNG)

The xml from the "Invalid" test is :

``` xml
<test-suite type="Assembly" id="68-1" name="OutsideSources.DomainServices.dll" fullname="/home/toburn/Desktop/OutsideSources/OutsideSources.DomainServices/bin/Debug/OutsideSources.DomainServices.dll" testcasecount="0" runstate="NotRunnable" result="Failed" label="Invalid">
      <properties>
        <property name="_SKIPREASON" value="Unable to locate a driver for /home/toburn/Desktop/OutsideSources/OutsideSources.DomainServices/bin/Debug/OutsideSources.DomainServices.dll" />
      </properties>
      <reason>
        <message>Unable to locate a driver for /home/toburn/Desktop/OutsideSources/OutsideSources.DomainServices/bin/Debug/OutsideSources.DomainServices.dll</message>
      </reason>
</test-suite>
```

**Comment by CharliePoole** [comment]
Is there a reason you prefer to execute the solution rather than the
assemblies directly? Understanding why folks use this approach may help us
decide how to fix it.

**Comment by tburnett80** [comment]
I am seeking a generic way to run all the tests I have for a particular solution. I have automation that I have no choice on that generates jenkins jobs and not having to know what all the test assemblies names are up front helps me considerably. 

This is the model I used with prior versions of Nunit and am not sure why now it considers non-test assemblies as a reason to mark the test run as failed. 

Typically I build a solution with multiple projects, if the tests fail nothing gets released, if the tests pass everything gets released.

**Comment by tburnett80** [comment]
I'm attempting to use a test config, but having the ability to specify a .sln file seems counter productive if it will fail when assemblies are present that contain no tests. 

Maybe Im the only one who keeps their unit tests separated from production code its testing?

**Comment by rprouse** [comment]
You are definitely not the only one who has tests in the same solution as production code, I think it is quite common. Personally, I never use the solution file, so I don't have much experience in how it worked in the past. 

@CharliePoole, did this work in 2.6? Could you specify a solution file with a mix of test and non-test projects?

As a workaround, you could use an nunit project file to specify the tests. It doesn't give you auto-discovery of tests, but I prefer it because it is more explicit and faster since NUnit does not have to inspect every project/assembly looking for tests.

**Comment by tburnett80** [comment]
Yeah I am going to try the nunit project file as it could be easily maintained in the solution under source control and trigger tests based on a naming convention for the project in place of the solution. I just thought it was odd considering it had worked in 2.6 for me on windows last time I sat it up on our build servers about a year ago. I had been forced to use VS unit test suit for the better part of the last 6 months but moved back to nunit because its easier to run on mono on linux and refactoring from VS to nunit is super simple.

I just thought I would point out this use case ( used in my last 3 contracts ) was common and likely to always result in failed results.

**Comment by CharliePoole** [comment]
@rprouse It worked with exceptions. Certain rarely used project types will throw an exception.

We have discussed in the past discontinuing support for solutions since they may contain many kinds of non-test projects and since we have no control over the addition of new types by microsoft.

If we decide to handle them, I think we should have a list of project types we understand and ignore others. We should also resolve the problem of known project types that are not test projects. This is not an entirely simple problem.

@tburnett80 

I'll try to address your "surprise." :-)

Of course, since NUnit 3.0 is new code, basically a new app as compared to 2.x, we can expect things to work differently in many cases. But there are also specific reasons here.

With 3.0, the code that detects and executes tests is in the framework. If your assembly doesn't reference the nunit framework, then we can't even begin to detect tests. There is nothing to do except return an error. OTOH, NUnit 2.x keeps this code separate from the framework. It can examine an assembly and determine that there are no tests in it.

When NUnit cannot locate a driver (because the assembly does not reference any known framework) there are two possibilities. Either it's not a test assembly or it uses a framework for which no plugin has been installed. Since the engine has no way to decide which is true, it returns an error saying that no framework driver can be selected. We could ignore this error, but that would cause silent failure in cases where the user entered the wrong assembly on the command line.

A possible solution would be to have a setting that indicates this error should be ignored - or possibly to ignore it if there are other assemblies without the error. The runner could apply that setting to any solution files. Another "solution" is to remove support for solution files entirely.

**Comment by tburnett80** [comment]
Yes I agree, I think removing the .sln support might make sense. 

I am moving to using a .nunit project file but having some mixed results but I think I can make it work. Thanks for the advice guys and keep up the good work.

**Comment by CharliePoole** [comment]
Here's what I propose on this issue...

1. Remove current support for VS solutions as "project files" That means we will no longer be able to open them from the command line.

2. Provide a standalone program to convert solutions to nunit projects, which can then be edited by the user.

@nunit/core-team Comments?

**Comment by CharliePoole** [comment]
@nunit/core-team Maybe this is a failure in our process, but when I ask for comments on an "is:idea" and nobody comments, then it never gets addressed. As a matter of personal policy, I pretty much **never** add a feature to NUnit because **I** think it's a good idea.

In this case, I'd appreciate both your comments on the proposal as well as any ideas about how to handle such things better. Should they go to a wider audience? In order of increasing size, that could be (1) contributors, (2) developer list or (3) discussion list.

**Comment by OsirisTerje** [comment]
Sorry Charlie.  Promise to behave better :-)
I am a VS guy, so I prefer to use the VS solution files, and not the nunit Project files.  Using NUnit Project files With VS solutions, how does that work ?
So I am opposed to 1), and I don't see how 2) should work out.
My reason for not commenting on this is that the question seems outside my area of interest, but I see it may affect it.

Further, I don't see how removing support for sln files will solve anything.  This seems more to be an issue on how to ignore non-runnable assemblies.  The adapter do ignore them, and can this be an issue With the console runner itself ?   

On your escalation strategy, that makes sense to me.

**Comment by CharliePoole** [comment]
@OsirisTerje You raise several pointss...

"Using NUnit Project files with VS solutions, how does that work?"
Not "with" - they are alternatives.

You can enter the name of an NUnit project file on the command line and it gets "expanded" to the assemblies contained in it. You can enter the name of a VS project file and it gets expanded to the assembly it creates. You can enter the name of a VS solution file and it gets expanded to all the assemblies created by all the projects in it. The first two work precisely and correctly. The third doesn't. The feature has never been really useful and I'm frequently surprised to find people using it instead of creating an NUnit project file.

So, one approach is to make it work as one would expect, whatever that means. :-) Another is to stop giving the appearance that we support it. 

Do you run NUnit using solution files in your work? If so, how come and how well does it work for you?

" I don't see how 2) should work out."
I should have explained better. Traditionally, we have told users to load a VS solution in the gui, save it as an NUnit project and then edit that project. Our support for actually executing tests out of a solution has always been incidental. As I said above, I have always been surprised that people use it. Nothing new there though: it's always surprising how stuff gets used as opposed to how it was initially intended!

"I don't see how removing support for solution files will solve anything. This seems to be more an issue on how to ignore non-runnable assemblies. The adapter do ignore them, and can this be an issue With the console runner itself ?"

Traditionally, NUnit has always tried to show all problems, rather than hide them. If the console runner is told that a particular assembly is non-runnable, that is reported as an error. We do this because we can't know what the user intended at the console level. In the adapter, it's not the user telling us what to load and run, but VS itself. We treat the call from VS as saying "These assemblies may or may not have tests."

We could do something like that with solution support. The support would probably have to be internal to the addin that implements VS Solution support rather than the runner. We would have to base this on either a white list or a black list. Currently, we use a black list - that is, a list of those project types which are known in advance to not contain tests. Either kind of list suffers from two problems:
1) it has to be kept up to date as Visual Studio invents more project types
2) it doesn't allow for new kinds of runners and drivers that are able to handle tests we don't handle.
That said, it's definitely possible to expand the VS solution code rather than remove it. This would affect all runners that use solutions, of course.

BTW, I'm taking "ignore" to mean "silently skip over" rather than flag as Ignored, which generates a warning.

Regarding escalating issues: I think I'll start going to a broader audience in the first place unless there is a clear reason to limit it to committers. In any case, I guess I need to spell things out better when asking for comments.

Charlie

**Comment by CharliePoole** [comment]
One possible workaround: Flag assemblies that we are trying to load because they come from a solution file. For such assemblies, when no driver can be found, just show them as having no tests rather than as not-runnable. This might require a new driver to compement the one we use for non-runnable assemblies.

**Comment by gboer** [comment]
I very much like the possibility to have a solution be loaded using Nunit. I wanted to use it, but because of the problem the tburnett80 described, I had to resort to do it a little bit differently. I know that this is not answering or adding to the discussion Charlie, but because other people might be interested in a solution (right now) I thought I'd post it here.

What I'm doing is first running Nunit3-console in explore mode, run the output through an XSLT to generate an Nunit test project XML file that only contains runnable assemblies. The XSLT I'm using is [this](https://github.com/nunit/nunit/files/70183/nunit3-output-to-nunit-project.txt), should someone else want to use it as well. (not really an XSLT expert, so there might be better ways to do it)

And this is the way you run nunit3-console:
`nunit3-console.exe solution.sln --explore:testProjects.nunit;transform=nunit3-output-to-nunit-project.xslt`

**Comment by CharliePoole** [comment]
@gboer Clever trick! In NUnit 2.6.4, the way to do this was through the gui. You could open the solution file, save an nunit project file and then manually edit out the non-test assemblies. Unfortunately, we don't have a gui for NUnit 3.0 yet.

Maybe the NUnit Project Editor should be extended to create project files from VS solutions!

**Comment by novaterata** [comment]
In 2.6.4 I could just tell nunit to run the solution file and it just worked. Because of that I never had to have nunit project files or maintain them or write XSLT or NAnt code to generate them or otherwise control the process outside of a single command line parameter. I honestly don't understand why it isn't obvious why someone would want to take the simplest approach. Anyway that involves creating an nunit project file is more complicated because you also need a tool to debug and write your test code.

**Comment by CharliePoole** [comment]
@novaterata Yes, I suppose there are many people for whom it worked. Unfortunately, there were other people for whom it didn't work because the solution contained unsupported project types.

My idea of removing this feature came from not wanting to have it fail some of the time. I see from the comments that removing it would penalize folks use simple VS solutions without any unsupported projects.

I guess what we have to do is recognize when we are trying to expand an unsupported project type and do something sensible with it, just as we do when an assembly cannot be found. The special wrinkle here is that we would not want such a case to be treated as an error, just as an ignored assembly.

There are implementation details that make this a bit tricky, some of which are described above. That, however, is our problem. :-)

I'm retitling this issue and making it a feature rather than an "idea."

**Comment by novaterata** [comment]
@CharliePoole Thanks!

**Comment by pcalin** [comment]
I would like to be able to pass a regex filter like --ProjectsFilter=regex to limit projects that are considered unit tests from the solution.

This setting could then be used inside VsSolution.cs to limit assemblies loaded.

I have already implemented this locally. If you think it's a good way forward I can create a pull request.

Cheers,
Calin

**Comment by CharliePoole** [comment]
@pcalin A ProjectsFilter is certainly a possible approach, but it will only work if the projects that are to be included happen to match some regular expression. I'd prefer to see us take the approach described above: where the solution loading extension incorporates what is needed and other components of NUnit don't have to get involved.

There are two kinds of projects that we need to exclude from the list provided by the solution...
1. Those that don't contain a reference to NUnit.
2. Those that are of an invalid project type.
I think this logic needs to be localized in the vs project loader.

**Comment by kalanbates** [comment]
> Is there a reason you prefer to execute the solution rather than the
assemblies directly? Understanding why folks use this approach may help us
decide how to fix it.

Concisely, because when I say "execute NUnit against my solution" the least surprising result would be for it to execute the tests in my solution and report back on whether they succeeded or failed.  It provides me no value for NUnit to fail the run and report back "Hey. Did you know you have an assembly in your solution without tests in it?? I went ahead and failed everything for you." I was _irate_ the first time I encountered this passive aggressive behavior. 

> There are two kinds of projects that we need to exclude from the list provided by the solution...
1. Those that don't contain a reference to NUnit.
2. Those that are of an invalid project type.
I think this logic needs to be localized in the vs project loader.

To my thought processes, that seems to be the backwards approach. 
Why does "Assembly contains no tests" result in an Overall Failure in the first place with no way to override?  

If there were an override to have this error not fail the entire run and implement with an `--ignore-no-test-error` or something to that effect, then wouldn't it "just work" without having to meddle with determining which assemblies are in and which assemblies are out? 

Why is the default behavior _not_ just run my tests??

**Comment by CharliePoole** [comment]
@kalanbates The first quote you comment on is almost a year old. If you read the full discussion, you will see it has been dealt with before.

Regarding why "Assembly contains no tests" results in an overall failure...

1. That's not what happens. NUnit doesn't know the assembly contains no tests. It only knows that no suitable driver has been found. Bear in mind that the NUnit test engine is not especially oriented toward running NUnit 3 - or any version of NUnit - tests. It's designed to handle other test frameworks and will in the future. This makes it a bit more complicated than you are imagining, but hopefully with a payoff in the future.

2. It has been long ago agreed in this discussion and a few other parallel discussions that NUnit should not fail the entire run in this situation. We have been discussing how to do it. Several solutions have been proposed. Your suggestion is the most recent.

3. Your idea of --ignore-no-test-error would actually be more like --ignore-framework-not-found-error, of course. I personally dislike adding an option to deal with this. As I have said previously in the discussion, it seems to me that the solution project loader - a separate component - should be responsible for doing the intelligent thing. In the case of a VS solution, it is to be expected that some files will contain no tests. We should simply deal with that. Adding an option that essentially says "deal with it" doesn't make much sense.

Strongly suggest reading all the info available about this rather long-winded discussion.

**Comment by kalanbates** [comment]
Thanks for the very quick reply.

> The first quote you comment on is almost a year old.

I think I missed your Aug 10, 2015 comment in my reading.

> Regarding why "Assembly contains no tests" results in an overall failure...
> [Your Point 1]

That at least explains why it's not an easy thing to accommodate. My reading of the error messages that are generated was what I provided in my initial comment. I always read that as "Hey. Did you know you have an assembly in your solution that doesn't contain any tests? I failed the test run for you. You're welcome." I somewhat assumed the implementation details would not be that trivial, but never looked into it any further.

> [Your Point 2]

Was not aware of any parallel discussions. I was researching ways to override the current behavior, saw this item was still open, saw your first comment about "Understanding why folks use this approach may help us decide how to fix it." I then saw your "We have discussed in the past discontinuing support for solutions." I read further to see your proposal: "Remove current support for VS solutions as 'project files' That means we will no longer be able to open them from the command line." and that was when I stopped reading and decided to provide my 2 cents on why being able to execute all tests in a solution without failing the entire run upon a non-test assembly would add significant value to me and why I feel support for solution files need to be expanded.

>[Your Point 3]

Thanks for providing that. It expands my understanding of why this is an item that requires a non-trivial amount of care.  The implementation details of my "suggestion" notwithstanding, the main reason I commented was to say "NOOOES!11111!!!!!! DON'T DROP SUPPORT FOR SLN FILES!!!!" 

Well...the thing that adding an "ignore" switch would do would at least give a temporary workaround.  I would be able to manually run the solution naively through the console runner, inspect the results, verify that the failure occurred on non-test assemblies, then update my command to ignore these errors.  

My major point that probably got lost in my wall of test is that I want a way to instruct NUnit that automatically failing the test run for anything other than a Failed Test is the wrong thing to do.

**Comment by CharliePoole** [comment]
Sometimes, the only way to get users to comment is to suggest dropping a feature. ;-)

Seriously though, this feature has never worked perfectly but does work for a large number of users who don't have exotic project types and (in V3) only use the nunit v3 framework. We figured out quite a while back in this discussion that we need the feature and we already added the project filtering workaround which helps some folks even if it's rather inelegant.

A more permanent solution has been proposed - I think on the PR discussion for the project filtering fix - that involves giving the solution loader knowledge of all frameworks supported so it can check project reference. That will still give a confusing error message if you reference an external frameworks but don't have the extension that supports it but at least it won't mess up general users.

**Comment by kalanbates** [comment]
> A more permanent solution has been proposed - I think on the PR discussion for the project filtering fix - that involves giving the solution loader knowledge of all frameworks supported so it can check project reference.

I saw that.  Can you provide any insight into when the project filtering fix will be made available to the chocolatey feed?

**Comment by CharliePoole** [comment]
The 3.2.1 release will be out on a few days. Even though I'm listed as one of the chocolatey packagers, we don't actually do that. It's automatically created sometime after our release.

**Comment by LirazShay** [comment]
I also think that it would be great to remain the functionality of sln file as is.  
I also have 1 solution with multiple projects (some are tests and some are test framework for automated testing)  
And I want to have 1 job in jenkins for all projects and pass the project name as argument in the 'where' section - for example: --where "class =~ 'PlacementTest.Specs'" (PlacementTest.Specs is the project name)  
And I want to pass the project name as parameter.  
Currently I could not do it because of this error.

I suggest that if user has passed the sln as file - then do not throw this exception at all, it is not relevant if at least 1 project has tests it should be good. if user has passed a dll as file - remain the errors as is. no need for special configuration or flag

**Comment by rprouse** [comment]
Nobody has picked this up and nobody else has asked for this so closing.
