### ISSUE TITLE
Portable NUnit "Engine"

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#677]
We need a portable engine for use with the portable framework. It's not clear if this component will really be an "engine" since it's functionality is so reduced, but that's the working title for now.

There are a number of big issues with a portable engine:

1. It isn't possible to open test assemblies as files, so we can only run in the NUnitLite style, where the component runs tests from the assembly that calls it.

2. There is no AppDomain creation, so tests must load and run wherever the engine is already running.

3. XmlNode is not available for return values or parameters, so a new interface is needed.

4. Engine Services as currently defined are not needed and many are not possible to implement.

**Comment by CharliePoole** [comment]
After some review of the code, it's clear we need less than a full engine - much less- but also more than just an engine. The portable framework build doesn't include FrameworkController, so it's not possible to call into the framework without having a direct reference.

FrameworkController will need to be included in the portable build in some modified form.

@rprouse As the "Customer" for this task, let me know what you need in addition to what you are now using. As far as I can see, you are using two methods of the ITestAssemblyRunner interface.

1. You use the form of Load that takes an assembly rather than a file name. This doesn't currently have an equivalent in FrameworkController, so it will have to be added.

2. You use Run without any listener or filter.

Have I missed anything? Any ideas for further development?

Charlie

**Comment by rprouse** [comment]
Charlie,

At the airport and about to board,  so I am not looking at the code.  Your
evaluation sounds pretty much right though.  On mobile,  I might not have
access to the file,  but I can always get the assembly,  so I need to load
using assembly.

I currently don't use filters,  but I may decide to in the future.
Eventually,  I might like to explore tests and allow the user to run
specific tests.

I don't think I need a listener.  I found it easier to take all of the test
results,  flatten them then create the control heirarchy from that.

That might be a problem for longer test runs though since I don't get the
results until the end.  Maybe switching to a listener would be better?

Boarding now,  I will read through the code on the flight if I get a
chance.

Rob

**Comment by CharliePoole** [comment]
I think the key question is whether we will need to open assemblies with tests other than the original assembly that calls into the runner. In fact, I think that this is the main distinction between an nunitlite-style driver/runner and an engine/runner.

However, it turns out this is a can of worms, so I'm temporarily putting this issue on hold in order to work on getting the FrameworkController class to work in a portable library. It turns out that it all revolves on what facilities are available for parsing and manipulating XML. I'll describe it in detail in the new issue I'm creating.

**Comment by rprouse** [comment]
I am going to close this as won't fix. My investigation so far has highlighted that a proper portable engine won't be possible. The other issues in this milestone that allow us to run portable tests from the desktop engine will fill the same role as this issue.
