### ISSUE TITLE
NUnit agent cannot resolve test dependency assemblies when mixed mode initialization runs in the default AppDomain

### ISSUE THREAD

**Issue by rationull** [nunit/nunit#681]
I've run into an issue where NUnit fails to load a mixed mode test assembly due to code running during managed assembly initialization (in the "cctor" as covered here: https://msdn.microsoft.com/en-us/library/ms173266.aspx) which is dependent on another, collocated assembly. Part of the assembly initialization process (controlled by the mixed mode C runtime library) is forced to run in the default AppDomain, which in this case prevents dependent assembly resolution since the application base directory is nunit-agent's, not the test assembly's.

To reproduce, create a test assembly with a mixed mode static global variable whose initialization depends on code in a collocated assembly. I've created a minimal repro solution which should be simple to build and demonstrate the problem (may require tweaking the reference to nunit.framework.dll to build). The repro solution can be found here: https://github.com/rationull/NUnitReferenceFailure

To work around this problem, I've copied the NUnit binaries into the same directory as my test assembly, mingling the NUnit launcher's application base directory with my test assembly's.

I propose that to fix the issue, the NUnit launcher (nunit-agent in my case but I'm not clear on whether the agent is the only context in which tests are run at this point) should allow optional installation of an AppDomain.AssemblyResolve event handler which would probe the test assembly's directory. This could have unexpected side effects in the general case, but as an opt-in feature any complications could be avoided except when this functionality is required. I have hacked on my own build of nunit-agent as a proof of concept to verify that this does fix the problem, although I have not done any kind of exhaustive testing.

I have reproduced the problem, the workaround, and the suggested fix in NUnit 2.6.4 and the current 3.0 build.

If you consider my fix proposal valid, but it does not meet the priority bar for implementation by the core team, then any design suggestions which might help an external pull request be accepted are welcome.

Note: For additional context see the later parts of the discussion here: https://groups.google.com/forum/#!topic/nunit-discuss/7ZBQ02dcIBg

**Comment by CharliePoole** [comment]
Thanks for filing this. It helps to nail down what has been a long-standing but poorly understood problem. We'd welcome a pull request to resolve this issue, some ideas on implementation follow...

The agent is not the only runner that may launch tests. They are launched by both the console runner and the gui directly, depending on the options chosen. Any fix for 2.6.4 has to be in the nunit.util assembly, which is loaded in the primary AppDomain. In fact, NUnit 2.x already installs an AssemblyResolve event handler in it's DomainManager code. See line 151 where it creates an instance of DomainInitializer into the dependent AppDomain. DomainInitializer in turn sets up the event handler. Of course, this code does the reverse of what you are trying to do: it makes it possible to load parts of NUnit into the test assembly.

Note that we don't currently plan to release a new version of NUnit 2.x. Any fix we accepted from you would be available to folks who are willing to build from source. If we accumulate enough changes, we might very well do a release.

For NUnit 3.0, the change would need to be in the engine assembly, since that's what is loaded in the primary AppDomain, whether the test is run in the same process or a separate process. We don't currently do any assembly resolution in NUnit 3.0 for our own purposes because of differences in the architecture.

You're talking about simply providing an opportunity for a hook to be called, where you would set up the resolution. I wonder if we couldn't simply do it for the user, based on a passed in option. It seems as if you want to be able to load any assembly found in the appbase or probingpath specified for the test assembly.

If you decide to work on this, either for 2.6.4 or 3.0, I'll be glad to answer questions as they come up. We won't be working on it for 2.6.4 but I'm accepting it as a low-priority issue for 3.0 or beyond.

**Comment by rationull** [comment]
In the Google Groups thread (linked in the original report), @rprouse suggested adding an assembly attribute to the framework to allow opt-in to this behavior, but I don't think that solution will work. In order to analyze assembly attributes, the assembly must be loaded, and even loading into the reflection-only context requires loading dependent assemblies, which circles back to the original problem. It's too bad because an assembly attribute would've been a clean way to use this.

Another option would be a launcher setting which would presumably have to be a command line option for the console launcher and a GUI setting for the GUI launcher. This is obviously much more invasive.

Any better ideas? I'm still assuming this is too niche and too risky for anything other than opt-in although I'm not sure how high the risk is in practice.

**Comment by rationull** [comment]
Do you think a setting in the test assembly's .config file would be an appropriate place for this, given the problems with using an assembly reference?

**Comment by CharliePoole** [comment]
Since NUnit 3.0 now pre-loads assemblies using Mono.Cecil, it's likely we could use an assembly attribute in the fix.

**Comment by rationull** [comment]
Thanks for pointing that out, looks promising!

**Comment by rationull** [comment]
Interestingly, I noticed that when running with --domain=NONE this assembly resolution problem does not occur. I haven't figured out why yet, since the default AppDomain's base directory should not allow the referenced assembly to be resolved -- however both the test assembly and its referenced assembly are clearly loaded into the nunit agent process after the test is run (verified with Process Explorer). Verified in NUnit 2 and 3.

I have not found the mechanism that causes this to work, but I have reproduced the behavior with a minimal project so I don't think it's anything NUnit is doing. That is, loading my test assembly in the default AppDomain in a minimal project does not trigger the referenced assembly problem, but running the same code in the same project but in a newly created AppDomain does trigger the problem.

This may provide a workaround for cases where AppDomain isolation is not required. I don't think this will solve the original case I hit but it might work for some people hitting this issue (presumably there are not many in that camp though!)

**Comment by rationull** [comment]
For reference [this StackOverflow post](http://stackoverflow.com/questions/17993010/dlls-loaded-from-wrong-appplicationbase-when-trying-to-load-mixed-c-sharp-and-c/18499944#18499944) seems to cover the same problem and says of the behavior "This appears to be a bug in .NET 4.5." I'm not sure I'd go that far since the stack traces on the repro seem pretty intentional (LanguageSupport::InitializeDefaultAppDomain() -> DefaultDomain::Initialize() -> DoCallbackInDefaultAppDomain()).

**Comment by rationull** [comment]
I have a fix implemented for this although I could use some feedback on how it's organized. The hook is managed by NUnit3FrameworkDriver with help from a couple of utility classes. Opt-in is handled by an assembly attribute as @rprouse suggested in the Google Groups thread.

Ironically, one thing I haven't been able to figure out is automated testing. Theoretically I could add my new attribute to the mock-nunit-assembly and verify that the resolver hook gets installed, but without adding an additional mock test assembly, we cannot verify both the attribute and no-attribute cases. This is a disadvantage of using an attribute instead of a parameter, although I think the attribute is more user friendly since the condition that triggers this problem is intrinsic to the assembly under test.

Worse, since the hook must be installed in the default AppDomain, it cannot effectively be installed by an NUnit3FrameworkDriver created in the NUnit3FrameworkDriverTests, in a test AppDomain. Code could be added to handle this context, but this context does not really make sense in terms of the real production use case.

Probably some of the smaller utility components could be unit tested but I have not written such tests at this point.

This is of course still a fringe issue and I don't have a good feel for whether the fix is something you'd actually want to accept into the codebase or not. If you're willing to take a look I will clean it up a bit and make a pull request if that's the most convenient way for you to evaluate it.

**Comment by CharliePoole** [comment]
It would probably be easier to talk about this if we were all looking at the same code. I'll make some comments anyway, hoping I have understood you right. :-)

1. It seems more likely that the code for this initialization should be part of DirectRunner, which selects the correct framework driver. In that case, it could potentially work for future alternative drivers as well as the current V3 and V2 drivers. However, we could start by evaluating the code you put into the V3 driver.

2. I wonder if it's possible to detect the problem assemblies directly, using Cecil, rather than relying on an attribute?

3. We would definitely take a look at a PR, which would also serve as a good place to continue this discussion.

**Comment by rationull** [comment]
Thanks for the pointer about DirectRunner -- it looks like the solution can be moved there fairly easily. I will do that as part of some general cleanup and submit a PR in the next few days. Sorry for the delay so far as my time to work on this has been sporadic!

I'm not sure about detecting this condition without intervention since the problem just comes down to the behavior of the test assembly during initialization time rather. It's possible we could activate this behavior for all mixed mode assemblies or always when an assembly load fails due to a file-not-found condition (the latter might amount to just installing the hook all the time) although that seems far-reaching. I'm not sure that Cecil could meaningfully detect the core trigger (a dependency in mixed mode static initialization) without some pretty advanced analysis. Would be very cool though.

**Comment by CharliePoole** [comment]
A pointer about PRs: we use them a lot for work that is not yet complete. Feel free to post something even if you know it needs more work. We usually put something like **Do Not Merge Yet** on the first line of the description in that case.

**Comment by rationull** [comment]
PR #1137 in with some notes attached on what I think could stand to be cleaner.

**Comment by rationull** [comment]
FWIW I've discovered that this situation can also be triggered by vtable initialization for native (/clr) concrete classes with virtual functions whose signatures reference managed types from referenced assemblies that reside next to the test assembly. This is insidious -- mixed mode C++ class hierarchies that take managed arguments are a legitimate interop scenario and harder to cleanly avoid than the more straightforward mixed mode static initialization case.

**Comment by rationull** [comment]
PR #1272 created with the fix modified to use Mono.Cecil and analyze the test package in RuntimeFrameworkService.

**Comment by rationull** [comment]
@CharliePoole Now that the initial fix here is merged will this be marked resolved after the 3.2 release? Is there anything further that I should be planning to do as far as the possible design changes discussed in the PR?

**Comment by CharliePoole** [comment]
I think this is closed now. The PR didn't have the proper format reference to this issue so it didn't close automatically. I plan on creating AssemblyResolver as a service, probably after 3.2.
