### ISSUE TITLE
Assigning friendly names to unit-tests

### ISSUE THREAD

**Issue by shytikov** [nunit/nunit#688]
Hi,

I really like `xUnit` feature of assigning unit tests custom names, that more clear for user than method names. But so far I haven't found something similar in `NUnit` (I'm working with most recent stable version in 2.6.x branch).

So my first question, is it possible to implement this feature natively?

And  the second question, meanwhile this feature is not present in the `NUnit` can I extend `[TestActionAttribute]` in the way to achieve the same effect?

I've posted [question on SO](http://stackoverflow.com/q/30799691/1047741), but there is no suitable answer so far.

I would appreciate some help in getting vision, clue how this feature could be implemented.

Thank you in advance for your help!

**Comment by CharliePoole** [comment]
As you probably know, NUnit supports renaming parameterized test cases. There is no way to rename a "normal" non-parameterized test.

An action attribute won't help here because the test already exists before it is run We would have to support this internally.

For NUnit 3.0 you may be able to create a custom attribute that implements IApplyToTest. I'm not absolutely sure but I think it should work.

**Comment by CharliePoole** [comment]
I labeled this as idea, which means we will think about and discuss whether to do it.

We could add a Display Name property to TestAttribute but we ha e to consider if it replaces the test name or is separate. We might also have to changetest cases.

What do folks think about this?
=

**Comment by rprouse** [comment]
I would like to understand the use case a bit more. You state that a replaced name would be more clear for the user than the method name. Is that not a problem of poorly named methods?

If more information is needed to fully understand the purpose of the test, then I tend to use the `DescriptionAttribute` to add the information. This way, I have the test method name so that I can quickly navigate to failing tests, but I have more detailed information about the intent of the test in the description.

Another thing that can be done is to add more detailed failure messages to Asserts.

Personally, I would find renaming the tests to be more confusing than adding the information needed, but I am open to being convinced :smile:

**Comment by CharliePoole** [comment]
@rprouse I noticed this one while reviewing our outstanding issues. Since there is no answer from the OP for almost a year, I am closing it. Feel free to re-open if you think there's anything here.

**Comment by flcdrg** [comment]
I was hoping that this might be possible too. 

I've been playing around with SpecFlow (with NUnit). SpecFlow takes a scenario name eg. "Add two numbers" and generates an associated NUnit test method named `AddTwoNumbers()`.

In this case, I think it would be nice to have the option for Test Explorer (or other test runner) to actually display "Add two numbers" as the test name for this test.

I note that [MSTest v2](https://github.com/microsoft/testfx/issues/515) and [xUnit](https://github.com/xunit/xunit/blob/master/src/xunit.core/FactAttribute.cs) have such a feature too (for use case references)

**Comment by aokhonchenko** [comment]
> I would like to understand the use case a bit more. You state that a replaced name would be more clear for the user than the method name. Is that not a problem of poorly named methods?
> 
> If more information is needed to fully understand the purpose of the test, then I tend to use the `DescriptionAttribute` to add the information. This way, I have the test method name so that I can quickly navigate to failing tests, but I have more detailed information about the intent of the test in the description.
> 
> Another thing that can be done is to add more detailed failure messages to Asserts.
> 
> Personally, I would find renaming the tests to be more confusing than adding the information needed, but I am open to being convinced 😄

May be you can explain how to use spaces in method's names? Or another languages (I know, team of unity has no time for localization, but there are a lot of people in the world who use 2-3 languages. Thats not a problem to read documents in foreign language, but I want to see cases in my native language with spaces, may be marks like special symbols.
It not a poor idea. It's a poor functionality of the editor.
