### ISSUE TITLE
Release NUnit-agent as a service

### ISSUE THREAD

**Issue by mklemarczyk** [nunit/nunit#690]
Can you provide NUnit-agent as a windows service?
It can provide testing on many virtual machines.

**Comment by NikolayPianikov** [comment]
Hi @mklemarczyk You could use [TeamCity](https://www.jetbrains.com/teamcity/) :)

**Comment by CharliePoole** [comment]
I'm interpreting this to mean: Have a long-running server that functions sort of like nunit-agent except that nunit-agent terminates after running a test. I'm assuming this server would need to be reusable and would be contacted by (multiple) clients to run tests. Is that right?

We once had such a component but set it aside to work on other things. In fact, that component shared a base class with NUnit-agent. It's possible we could bring that back to life if there were an important reason to do it.

Can you explain why such a component would be useful to you? How would it help you as compared to nunit-agent?

**Comment by mklemarczyk** [comment]
The main reason is to automate test execution from any build server system. (Like Jenkins-CI).
NUnit-agent should be as a service that able to respond on request from network.
It also should queue test execution requests.

Test results can be distributed as file on local hard drive or some network drive.

**Comment by CharliePoole** [comment]
If you want a server, then you definitely don't want to use nunit-agent.

Reasons:
1. NUnit-agent is a client! It calls into the TestAgency component of the NUnit (which is a service) and asks for work. Once it gets the work, it completes it and then exits.

2. NUnit-agent does not understand any of the options of nunit-console. Anyone using it directly has to process some sort of command line or other source of options and create a package.

3. NUnit-agent is expressly written to do what it does and nothing more. It links directly to the engine, so only one version can be used.

4. NUnit-Server, the component I mentionned, ran as a service (not a Windows Service however) It could be contacted by clients wanting to run tests.

5. NUnit-console is the NUnit batch component that we develop for use with build server systems as well as directly by developers. It understands a set of options and is able to deal with agents, servers, other machines etc. on behalf of the client that is using it. This centralizes all the logic that would otherwise have to be repeated by every build server system.

It sounds to me as if you want us to develop a test execution server, which we already are planning to do. If I have understood correctly, I will close this issue.

**Comment by mklemarczyk** [comment]
Yes, It is the way I need.
Can I help you to develop this solution?

**Comment by CharliePoole** [comment]
To avoid confusion, I created a new issue for this: #701

You would certainly be welcome to help with this. However I don't think we will be working on it till after 3.0 and it's a pretty complex feature for your first contribution to NUnit. Would you want to spend some time working on a few bugs or improvements in the meantime?
