### ISSUE TITLE
Deprecate / Remove TestCaseSourceAttribute Constructors

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#698]
According to our documentation, two of the constructors are deprecated. Currently, however, they are not. Neither is this change noted in BreakingChanges. We need to either implement this or decide to do something different and document it.

There were two main reasons for making these changes: 

1. Having the TestCaseSource value in the same class causes problems when constructing parameterized or generic fixtures at loadtime.

2. Use of a string parameter is not automatically refactorable.

Options:
1. Follow the docs. I.e., mark constructors TestCaseSourceAttribute(Type, string) and TestCaseSourceAttribute(string) as Obsolete.

2. Reverse the planned change: Leave both in and update the docs. Fix all the issues caused by the construction of the fixture.

3. Compromise: Mark only TestCaseSourceAttribute(string) as obsolete, since it causes more problems. Update the docs.

4. Forbid use of the same class for TestCaseSource in specific situations. This would probably mean generic and parameterized fixtures. This will require coding to test the type argument to TestCaseSource and to examine the fixture. The constructors would not be marked obsolete so we would have to use a runtime error, marking the tests using such sources as nonrunnable. This is a bit complicated.

5. Stronger than 1: Remove rather than deprecate the constructors.

6. Speculative: Combine 5 with the creation of a new way to simply express a set of data inline without the need to construct the class. This might be limited to static members, for example.

A bit about motivation for examining alternatives.

The two constructors cause a ripple effect that has generated a lot of bugs. We'd like to get rid of them completely. OTOH, they provide a very quick way to specify test data using types that can't be used as attribute arguments.

Here's an example. Current way:

```C#
[TestCaseSource("mydata")]
public void TestMethod...

TestCaseData[] mydata = { ...
```

If constructors are removed:

```C#
[TestCaseSource(typeof MyData)]
public void TestMethod...

class MyData : IEnumerable
{
    TestCaseData[] mydata = {...

    IEnumerator GetEnumerator()
    {
      return mydata.GetEnumerator();
    }
}
```

The second example could use yield if desired, of course. In either case it's much more wordy than the first. Ideally, we'd like a way to replace the first that doesn't require constructing the test class at load time.

**Comment by CharliePoole** [comment]
Note that the same issue applies to ValueSourceAttribute, which should be resolved in the same way as TestCaseSourceAttribute.

**Comment by CharliePoole** [comment]
@nunit/core-team @nunit/contributors Looking for comments on this issue before I work on the code.

**Comment by agray** [comment]
I have code that relies on valuesource, were not talking about removing these constructs I hope.  Could you possibly provide more examples  of how it would work in the proposed new ways for us to comment further?

**Comment by CharliePoole** [comment]
@agray Take a look at the documentation page for TestCaseSource on the wiki. It shows two forms as deprecated. We've been planning this for a long time, but now it's time to really decide whether to do that, keep them or do even more - i.e. remove them.

So... ValueSource(Type, string) and ValueSource(string) would be removed or deprecated. They would be replaced by the existing ValueSource(Type) form which requires an extra class to be created. Or you guys will come up with a short form way to do this that doesn't require construction of the test class - which is the reason it's a problem.

**Comment by acco32** [comment]
If the new scheme is to follow a data driven approach shouldn't the data source live outside of the compiled source? We could define a standard xml file (or another key/value source type) that is referred to data in the test(s). Some examples:

TestCaseSource('data1',  int[])....
look for id 'data1' in standard file and interpret as an array of int

TestCaseSource('data.txt', 'data1', int[])
Same as above but we can explicitly refer to the file with data

Main advantage of this is no recompile and we have clear boundaries between data and test engine. Also test data may reside in single standard location (that we define) or can be separated per the user's preference. Main problems is that for reference types this can get messy. Also it is more work to implement than the other options.

**Comment by CharliePoole** [comment]
@acco32 I think I would see that as a new feature rather than a modification of TestCaseSource, which is designed for getting internal data. The new feature could build on it though.

It seems to me we once (maybe back on Sourceforge) had a request for such a feature but it seems to be lost now. I suspect we are very close to the point of being able to implement such a feature as an extension, using the interfaces that NUnit's attributes implement.

**Comment by rprouse** [comment]
It is interesting that the docs state that `TestCaseSourceAttribute(Type sourceType, string sourceName);` is deprecated, but then we use it in the very next example. Personally, I like this form and think we should leave it in. If there are issues with the sourceType being the same as the test fixture itself, can we state that is not allowed in the docs and throw if it is used that way? We could add to this your final option that you can use properties in the test fixture if they are static.

As for the string only constructor, I am fine with deprecating that. It encourages the use of properties within the test class. We could however add the same guard clause that the member must be static and leave it in.

If we add the guard clauses, then the only outstanding objection is that the string arguments are not automatically refactorable, but that has been addressed by the nameof operator that has been added to C#. Since it is backwards compatible to all versions of C# if you are using Rosyln and most people will be soon, we could use that in our example code in the docs.

With the guard clauses, are there any other issues with these attribute constructors?

@acco32, I like your idea of an external data source. Other test frameworks can pull from external data like CSV, Excel or even a database. I agree with @CharliePoole that it should be a new attribute though. Would you like to enter an enhancement for it and maybe come up with an appropriate name for the attribute?

**Comment by CharliePoole** [comment]
@rprouse Can you check that cname will work as the string arg to a  TestCaseSourceAttribute? There are lots of restrictions on attribute args, so I'm wondering.

**Comment by rprouse** [comment]
@CharliePoole, you mean nameof don't you? If so, then yes it works, I tried code like this and it works as expected.

```C#
        [TestCaseSource(typeof(TestDataProvider), nameof(TestDataProvider.TestData))]
        public void TestThrows(int x)
        {
            MustBeGreaterThanZero(x);
        }
    }

    public class TestDataProvider
    {
        public IEnumerable<object> TestData
        {
            get
            {
                yield return 1;
                yield return 2;
            }
        }
    }
```

**Comment by CharliePoole** [comment]
Yes that's what I meant. Ok, let me sleep on it.

**Comment by CharliePoole** [comment]
After thinking about this, I've come up with a simplification, which I hope will work for us.

Suppose we just say that the second (Type, string) and third (string) constructor forms can only refer to a static field, property or method? This would apply whether the class being used were the test class itself or some other class.

As it now stands, the data source has to stand on it's own anyway, only depending on values set up by the default constructor at most. But any logic that can be applied in a default constructor can also be used in a static method. In fact, in past discussions, we have referred to these test cases as "static" in contrast to the dynamic cases, created at execution time, which we hope to create in a future release.

This would certainly be an easy approach to explain to users. It would also allow us to remove a fair bit of code that is used to instantiate and cache instances of classes that provide data to these attributes.

NUnit uses both attributes extensively so we would have to convert a lot of our own tests. This is a mechanical process, however, and should not pose a big problem.

The biggest drawback, of course, is that it requires users to convert a lot of tests. To prevent this, we could issue a warning for any tests that use instance members, but that would mean retaining all the infrastructure that currently supports this usage. My inclination would be to bite the bullet and make the change now.

More comments?

**Comment by CharliePoole** [comment]
I just found that there's an undocumented form of TestCaseSource:

TestCaseSource(Type sourceType, string methodName, params object[] args);

The args are used for the constructor of the sourceType. I'll have to research this a bit to see how and where it's used. We don't seem to use it directly ourselves except in order to test it. Must have been added in the past for some reason. Since it's not documented, it seems likely we can remove it.

**Comment by CharliePoole** [comment]
Went back and changed the title to reflect what we actually decided to do instead of deprecating the constructors.

**Comment by HelloKitty** [comment]
It's possible to abuse generic static ctors, they run for each closed generic Type in C#, to provide unique test data to the static property. My needs were being able to create an abstract collections and have children Types provide test case inputs. This was to automate/tests against a generic interface. Since non-static wasn't allowed the workaround was a slightly hacky reflection-based approach.

To avoid reflection you could alternatively create an abstract generic Type with a Type arg that is constrainted to new() and something like IProvidesTestCaseData. Then on inheriting types you can provide the concrete implementation and create it in the static ctor and initialize it the static property.
