### ISSUE TITLE
Can I write the trace, console and error outputs into my XML report file?

### ISSUE THREAD

**Issue by Andrey-Bushman** [nunit/nunit#699]
Thank you for NUnit existing! 
I have some problem with the output saving. I publish my question here: http://stackoverflow.com/questions/30938178/how-can-i-write-the-trace-console-and-error-outputs-into-my-xml-report-file
After the XML generation I use the ReportUnit.exe ( http://relevantcodes.com/reportunit-report-generator/ ) for the HTML report generating. Therefore I want to have the output info in that XML and HTML.
Is it possible?

Best regards, 
Andrey

**Comment by CharliePoole** [comment]
I'll answer with respect to NUnit 2.6.4 first and then relate to the current NUnit 3.0 beta.

NUnit 2.6.4 does not put text output from the test into the XML file and does not give you any way to write it their yourself. It's conceivable that a report generator could take the XML result plus the text output files and generate some sort of combined output but it wouldn't be easy to figure out which output goes with which test. Since NUnit 2.6.4 is the final release of its series, it probably isn't worth anybody's time.

The NUnit 2.6.4 GUI does capture trace and console output and displays them together in a window. The output is not associated with test results but you can select an option to cause a header to appear for each test.

NUnit 3.0 includes text output in the XML. However, it uses an entirely new (and still in development) format that report generators are not yet familiar with. You can tell NUnit 3.0 to create an XML file in NUnit 2 format, but then of course the new information won't be present. I hope to see third-party report generators that work with the new format but that may not happen until we are past the beta stage. It's likely that we will provide some reporting customization as part of NUnit as well.

Even in NUnit 3.0, however, we do not make any effort to capture trace output for the XML result file. Only standard console output is included.

For the longer term, my suggestion is that you first get familiar with NUnit 3.0 and then create issues asking for any additional features you feel you need.

Charlie

PS: The nunit-discuss list on google is the normal place for asking questions about NUnit. The developers of NUnit don't make any concerted effort to answer questions on SO, although you will often find knowledgable users there to answer questions.
