### ISSUE TITLE
Provide a data source attribute at TestFixture Level

### ISSUE THREAD

**Issue by agray** [nunit/nunit#715]
Gallio MbUnit supports the following syntax on the TestFixture attribute:

[TestFixture, Factory(typeof(MyFactory), "MethodInMyFactoryThatReturnsIEnumerable")]
public class MyTestFixtureClass {
        public MyTestFixtureClass(MyFactory factory) {
            //Do stuff
        }
}

For every item in the factory IEnumerable the MyTestFixtureClass constructor is called.

As far as I've been able to determine so far, while NUnit can do factories at the [Test] level it does not support factories at the [TestFixture] level.

This is a massively useful feature that should be implemented in NUnit 3.

**Comment by agray** [comment]
Having TestCaseSource for an individual test is not enough. The requirement implicit in the issue is for it to be at the TestFixture level.

So if MethodInMyFactoryThatReturnsIEnumerable() return an IEnumerable containing 10 records and there are 5 tests in the TestFixture, the end result needs to be 50 tests are spawned.

Additionally if a testcase is datadriven itself tests should be spawned combinatorally with the 10 records returned by MethodInMyFactoryThatReturnsIEnumerable().

This is how the MbUnit implementation works.

**Comment by CharliePoole** [comment]
This is how Test Fixtures in NUnit already work. The only thing that's lacking is the level of indirection that is provided for test cases. 

That is, test cases can be specified directly (TestCaseAttribute), Indirectly (TestCaseSourceAttribute) and combinatorally via direct (Values, Range, Random) or indirect (ValueSource) sources annotated on the test parameters. 

OTOH, fixtures only currently provide for direct specification of arguments on the TestFixtureAttribute itself.

Provision of indirect sources for fixture arguments has been in the work plan for NUnit for the past few years. It's currently represented by Issue #2. 

What you are proposing is already planned and has been the subject of much discussion on the mailing lists over time. It's not yet implemented.

I am taking the time to lay this out because we look back at these issues over time and it can often take a bit of effort to figure out the point. In this case, you seem to be asking for three things:

1. That NUnit generate multiple fixtures for a given test fixture class. This is already implemented for parameterized, generic and parameterized-generic fixtures.

2. That the generation of fixtures include all generated tests combinatorially. Again, that's how it works.

3. That we provide a data source (this is the NUnit terminology - you used "factory") for Test Fixtures that works in a similar way to TestCaseDataSource. This is a new feature and seems to be the essence of this request. I'm renaming the issue to reflect this.

**Comment by CharliePoole** [comment]
Although this duplicates #2, I decided to keep it open since it expresses what is needed differently.

**Comment by agray** [comment]
As long as it is understood that the data source at the Test Fixture level "multiplies out" at the test case level then I am currently satisfied that item 3 (in Charlie's comment) as I understand it is the essence of this feature request.

**Comment by agray** [comment]
I would also like to see this feature implemented in a 2.6.5 release of NUnit.

**Comment by CharliePoole** [comment]
Re "multiplying out": Have you experimented with parameterized fixtures? A fixture is created for each set of arguments, as specified on a TestFixture attribute. Test cases are created independently, based on methods within the fixture. Since each fixture contains all the tests, the total number of tests might be said to be "multiplied" although it's more like creating a bunch of houses from the same plan. Each house has the same rooms. Similarly, if we use the same class as a fixture multiple times, but with different arguments, then all the same tests appear in it each time.

I'm feeling that there's still some chance I have misunderstood what you want. So please look at the already-existing feature in 2.6.4 or 3.0 beta 2 and see if it's going in the direction you intend.

**Comment by CharliePoole** [comment]
We are not planning a 2.6.5 release but I don't rule it out. If we did it,
it would only include bug fixes. This is a new feature and implementing it
for an obsolete version of NUnit would simply be lost time for the current
version.

**Comment by agray** [comment]
If you're able to share the syntax of how to achieve in NUnit 3 what can be done with a factory in MbUnit  I would love to see it.  

I have tried everything I can think of based on what I have read in the documentation.  It appears unsupported currently, which I thought you confirmed in a previous comment in point 3.

**Comment by CharliePoole** [comment]
@agray I didn't mean to suggest that NUnit already does what you asked for, but only that you don't seem to understand what NUnit already does. Having an understanding of NUnit would make it easier for you to articulate what you want changed so that we deal with your request correctly.

In an earlier post, I listed three things you were asking for and explained that NUnit already does two of them. If that statement raises any questions for you, please ask them.

Bear in mind that I have no experience with MbUnit. I'm not going to download, install and run experiments with it - especially not when I have you here to explain things to me. :-)

I _do_ understand how mbunit factory works on a test method. It's pretty much the same as TestCaseSourceAttribute in NUnit. I guess I do _not_ understand what it means to put a FactoryAttribute on a test fixture.

Originally, I was assuming the factory would generate constructor arguments for the test fixture. From your comments, it sounds  like that isn't what it does or what you want. Am I right? Can you articulate more precisely what is done with the data generated by a "Factory" attribute on the fixture?

I understand that - from a user perspective - you want the tests to "multiply."  But we are discussing the implementation here, which means we need to decide exactly how that happens. An implementation in the nunit style would give you 3 fixtures with 3 or 4 tests each. You seem to be describing one fixture with 12 tests and I'm not sure how the extra parameter is supposed to get to all the tests.

**Comment by agray** [comment]
Hi Charlie.  Happy to be shown where I may have a misunderstanding.  Lets try this again with code.

NUnit needs to support the following:

Let's say we have a TestFixture like so:

[TestFixture, Factory(typeof(MyTestData), "GetTestData")]
public class TestBase {
	protected readonly MyTestData MyTestData;
		
	static TestBase() {
	}

	public TestBase(MyTestData myTestData) {
		MyTestData = myTestData;
	}

	[SetUp]
	public void Init() {
		
	}

	[TearDown]
	public void Cleanup() {
	}
}

and let's say GetTestData returns an IEnumerable of 3 records (a record being a class with attributes of its own).  Lets call these three records R1, R2, R3.

Furthermore we have some tests:

public class MyTests : TestBase {
	public MyTests(MyTestData MyTestData) : base(MyTestData) {
	}
	
	[Test]
	public void Test1() {
	}
	
	[Test]
	public void Test2() {
	}
	
	[Test]
	public void Test3() {
	}
}

What I get in MbUnit as executed tests with that Factory attribute on TestBase is (order agnostic):
Test1 with R1
Test2 with R1
Test3 with R1
Test1 with R2
Test2 with R2
Test3 with R2
Test1 with R3
Test2 with R3
Test3 with R3

I know that in Nunit I can list out the test data in a hardcoded fashion like so:

[TestFixture("dataattr1val1", "dataattr2val1", "dataattr3val1", "dataattr4val1", "dataattr5val1")]
[TestFixture("dataattr1val2", "dataattr2val2", "dataattr3val2", "dataattr4val2", "dataattr5val2")]

which calls the TestFixture constructor with matching attributes.

but I need to be able to do the same thing with a "Factory" class (or whatever we need to call it in NUnit parlance), which NUnit doesn't seem to support.

Is there some other syntax by which NUnit supports this that I am yet to discern?

**Comment by CharliePoole** [comment]
@agray I think it's more like _we_ have a misunderstanding - not _you_. :-)

First of all, I have been saying that NUnit does _not_ yet have this feature but it has two sub-features that you mentioned. So you aren't missing anything.

However, with this new example, I see that we have been talking about two different things. We have plans for new ways to call the constructor. Think of it as TestCaseSource for fixtures.

We do _not_ have plans for anything like what you are describing and I would want to understand it better before agreeing to it.

The key thing i'm missing in your example is how do the tests, which have no arguments, get access to R1, R2, and R3?

I think you are learning that simply referring to MbUnit isn't saving you the effort of actually explaining how you want it to work. :-)

**Comment by agray** [comment]
Hi Charlie,

The individual tests don't need or use the MyTestData records.  They are just passed up to the TestFixture to create the multipling effect.

The individual tests can independently have their own TestCase[] annotations.

Test1 above could be:
    [TestCase("12345678")]
    [TestCase("98765432")]
    public void Test1(string text) {
    }

So with R1,R2 and R3 at the TestFixture level, Test1 would execute 6 times.

Indeed, if I were to use the hardcoded fashion TestFixtures I described above in NUnit 2.6.4. I do get 6 executions of Test1 as I expect.

I am requesting to have the ability to, as an alternative to hardcoding the TestFixture TestCases, be able to acheive the same thing with a TestCaseSource / "Factory" class on the TestFixture that returns an IEnumerable which contains the TestCases.

Does that make it clearer?

**Comment by CharliePoole** [comment]
Yes, I see we _are_ talking about the same thing. NUnit will have some attribute that can feed data to a TestFixture class constructor without hardcoding. :-)

**Comment by agray** [comment]
Great, thanks Charlie.  More than happy to participate in the implementation so this is reality sooner rather than later. However, will need to be guided by your superior knowledge of the code base.

**Comment by CharliePoole** [comment]
A general question for all: what would be a could name for an attribute
that works like TestCaseSource but applies to fixtures? Alternatively, what
would be a good name for an attribute that applies to both.

The MbUnit folks used "Factory" which I dislike because (a) it's not
generally used as a factory, although it can be and (b) the name doesn't
say what it creates. So far, in NUnit, we have standardized on certain
suffixes:

XxxxxData is data, like TestCaseData and ITestCaseData

XxxxxSource is a source of data, like TestCaseDataSourceAttribute and
ValueSourceAttribute

XxxxxProvider is a class that can combine multiple sources into a single
source, like ParameterDataProvider

[Not all classes follow this rubric. It's a growing standard, however.]

Ideally, the attribute we're talking about would be
SomethingSourceAttribute for consistency.

Thoughts, folks?

**Comment by agray** [comment]
My first thought is:  What's wrong with TestCaseSourceAttribute?  The point being that it potentially behaves differently (i.e. appropriately) when placed against a [Test] or a [TestFixture]

    [TestFixture, TestCaseSource(typeof(MyTestData), "GetTestData")]

If we do decide it is better to call it something different, here are some suggestions:
# FixtureCaseSource (If I had to pick one)
# FixtureTestCaseSource
# TestCaseFactory (I know Charlie might not like this one but I think "factory" fits.)

**Comment by CharliePoole** [comment]
Because it's not a source of tests cases. It's a source of test  fixture instances. Your third suggestion would be a good alternative name for the existing attribute.

The first seems reasonable if we don't mind calling each class instance a case.

**Comment by CharliePoole** [comment]
A specification for this feature is available at https://github.com/nunit/dev/wiki/Parameterized-Test-Fixtures

**Comment by agray** [comment]
Request that this important feature be backported to a 2.6.5 release of NUnit 2

**Comment by CharliePoole** [comment]
Sorry, that's not happening. All our effort is devoted to getting 3.0 done.
