### ISSUE TITLE
OneTimeSetup working under NUnit 2.6.4 but not NUnit3

### ISSUE THREAD

**Issue by agray** [nunit/nunit#716]
Under NUnit 2.6.4 my Console.WriteLine statements that appear in a method annotated with [SetUp] in a class annotated with [SetUpFixture] execute and write to the Jenkins console as expected.

Under NUnit 3.0 Beta 3 the Console.WriteLine statements that appear in a method annotated with [OneTimeSetup] in a class annotated with [SetUpFixture] do not write to the Jenkins console. Other statements do write to the Jenkins console.

It appears to be a bug with the [OneTimeSetup] annotation functionality.

**Comment by agray** [comment]
Is this issue related to #71 ?

**Comment by CharliePoole** [comment]
Are you creating an AppDomain?

**Comment by agray** [comment]
No, I don't think so

**Comment by CharliePoole** [comment]
Then I'd say no. :-)

**Comment by CharliePoole** [comment]
@agray Can you provide a simple repro? We have tests of this in NUnit itself, and they are passing.

**Comment by agray** [comment]
namespace Tester.Tests {
        [SetUpFixture]
        public class GlobalSetup {
            [OneTimeSetUp]
            public void RunBeforeAnyTests() {
                Console.WriteLine("This should be printed once for the whole fixture, but doesn't");
            }
        }
    }

and in the same package (TestBase provides the [TestFixture])...

    public class MyTests : TestBase {
        public MyTests() : base() {
        }

        #region Tests
        [Test]
        public void TestMethod() {
            //do something
            //assert something
        }
        #endregion

**Comment by CharliePoole** [comment]
Does anything change if TestBase is in the same namespace? Or if there is no base?

**Comment by CharliePoole** [comment]
I'll set up a dummy test like yours and see what happens. I don't think any of our existing tests use a base class.

**Comment by agray** [comment]
did your dummy test replicate my experience with [OneTimeSetup]?

**Comment by CharliePoole** [comment]
Does your TestBase have any NUnit attribute on it?

**Comment by CharliePoole** [comment]
I'm suspecting that your TestBase (which I have not seen) is somehow indicating to NUnit that it should be executed independently, not just as the base of the tests. If that's the case, then the SetUpFixture wouldn't be used, since it's in another namespace.

Ways to tell NUnit to treat it as an independent test class, not just a base, include:
1. Putting a TestFixtureAttribute on it
2. Putting any inherited tests in it without marking it abstract.

You should not normally do any of the above.

**Comment by agray** [comment]
What if I want to put [TestFixture] in the base class. Can this be
supported by [OneTimeSetup]?

**Comment by CharliePoole** [comment]
I don't understand. Why would you want to do that? What is it intended for
NUnit to do as a result?

In NUnit terms , what is in your base class? (Setup, etc.) Is it abstract?

It seems you are wanting this worked on but are hesitant to provide the
info. If your base is proprietary, then you need to create a sanitized
example that you are able to share.

**Comment by agray** [comment]
Hi Charlie, NUnit is intended to loop through all the combinations.  The fix for Issue 715 helped a lot in this regard.

My Base class is quite simple:

    namespace MyNameSpace {
        [TestFixtureSource(typeof(MyClass))]
        public class TestBase : TestBaseBase {
            protected SauceryRemoteWebDriver Driver;

            public TestBase(MyClass myclass) : base(myclass) {
            }

            static TestBase() {
            }

            [TearDown]
            public void Cleanup() {
            }
    }

TestBaseBase is in the same namespace, MyNameSpace, and has the [SetUp] method among other things.  The Setup and Teardown methods are called successfully as expected.  The only thing that isn't working in the Console.WriteLine statements the in the [OneTimeSetup] method.

**Comment by agray** [comment]
Let me know if I can clarify any further.

**Comment by CharliePoole** [comment]
For both of our understandings, I suggest you set a breakpoint on one of the methods of TestBase. Easiest would be a OneTimeSetUp, which you could create temporarily for this experiment. From what you have described, I suspect that you will see it called twice, once for the derived class and once for the fixture itself. That's because you have told NUnit to do it, by identifying TestBase as a TestFixture. The TestFixtureSource attribute has that effect, just as TestFixture does. It says to NUnit "Treat this as a TestFixture!"

When TestBase is being used independently, rather than as a base class, the SetUpFixture does not wrap it because it's not in the right namespace. 

As far as I understand you, you really do not want NUnit to treat TestBase as a fixture. The established way to _not_ treat it as a TestFixture is to make it abstract. Is there any reason you can't do that?

If I'm wrong about what's happening, then I'll set this up to work on after I finish my current tasks.

**Comment by agray** [comment]
I really do want to treat TestBase as a TestFixture: I am thus providing a service to the developer who uses it to write their tests .

**Comment by CharliePoole** [comment]
In NUnit, treating it as a test fixture means...

1. You want NUnit to instantiate it independently of any derived classes.
2. You want it to be run by itself, without regard to any derived classes.
3. If it contains setup, teardown or tests, they will be run independently.

Treating it as a base for test fixtures means...

1. You want NUnit to instantiate any non-abstract derived classes.
2. You want to execute tests in those derived classes, including any setup, teardown or tests that are contained in the base class.

The traditional name in unit testing for the second pattern is "Abstract Test Fixture" this is represented in NUnit by an abstract class annotated as a test fixture.

Based on what I have seen of your code, you are telling NUnit to do both things: (1) run the base class independently and (2) use it as a base for any derived classes. I don't see the point of (1) for your users.

If you can't give me any more info about why you want to do (1) then I have to close this issue for insufficient information. So far it just doesn't make sense that you would want to have the base class used by NUnit n + 1 times for n derived classes.
