### ISSUE TITLE
Need a way to get test-specific command-line arguments at runtime

### ISSUE THREAD

**Issue by rswarup** [nunit/nunit#720]
We are trying to implement NUnit in our project and hit a road block because of 2 things:

1. There is no way in which we can pass any parameter from command line to the test called.
2. We tried exploring "Category" feature if that can help in achieving the above point but again hit a roadblock as there is no way in which I can get the list of Categories passed using console runner.

Considering the below scenario, if I can get the list of all Categories which are passed during execution then I can write my own logic in code. This can also work as a minimal way of achieving the command line custom parameter passing (as explained in point#1).

[Test]
[Category("PDF")]
[Category("DOC")]
Public void SomeTest()
{
       string[] myCategories=TestContext.CurrentContext.Test.SelectedCategories;

            if (myCategories.Contains("PDF"))
            {
                ParsePDF();
            }
            else
            {
                if(myCategories.Contains("DOC")))
                {
                    ParseDoc();
                }
                else
                {
                    ParseHTML();
                }
            }
}

Proposed Syntax:
TestContext.CurrentContext.Test.SelectedCategories
- Should return list of string having each selected categories.

**Comment by rprouse** [comment]
In NUnit 3, the categories and many other meta-data type attributes like
Description are implemented as properties of the test, so the code you want
looks like this,

[Test]
[Category("PDF")]
[Category("DOC")]
public void CanGetCategory()
{
    IPropertyBag properties = TestContext.CurrentContext.Test.Properties;
    var cat = properties["Category"];
    Assert.That(cat, Contains.Item("PDF"));
    Assert.That(cat, Contains.Item("DOC"));
}

Notice that I use the [string key] indexer to access the collection of
properties, not the Get(string key) method which returns the first property
of that name. The Get method is for attributes like Description which only
allow one copy on a test. Also note that the properties themselves are
objects so that attributes like TestOf can return the type being tested.

On 2 July 2015 at 01:18, rswarup <notifications@github.com> wrote:

> We are trying to implement NUnit in our project and hit a road block
> because of 2 things:
>
>    1. There is no way in which we can pass any parameter from command
>    line to the test called.
>    2. We tried exploring "Category" feature if that can help in achieving
>    the above point but again hit a roadblock as there is no way in which I can
>    get the list of Categories passed using console runner.
>
> Considering the below scenario, if I can get the list of all Categories
> which are passed during execution then I can write my own logic in code.
> This can also work as a minimal way of achieving the command line custom
> parameter passing (as explained in point#1).
>
> [Test]
> [Category("PDF")]
> [Category("DOC")]
> Public void SomeTest()
> {
> string[] myCategories=TestContext.CurrentContext.Test.SelectedCategories;
>
>         if (myCategories.Contains("PDF"))
>         {
>             ParsePDF();
>         }
>         else
>         {
>             if(myCategories.Contains("DOC")))
>             {
>                 ParseDoc();
>             }
>             else
>             {
>                 ParseHTML();
>             }
>         }
>
> }
>
> Proposed Syntax:
> TestContext.CurrentContext.Test.SelectedCategories
>
>    - Should return list of string having each selected categories.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nunit/nunit/issues/720>.
>



-- 

Rob Prouse



I welcome VSRE emails. Learn more at http://vsre.info/

**Comment by CharliePoole** [comment]
@rprouse That doesn't solve his problem of wanting to know the _selected_ categories.

I'm not in favor of providing a test with any information about _why_ it is being run. That violates the independence of the test. We have previously rejected the same request for a test to know what categories caused it to be run, so that it could behave as a different test depending on the category. While that's not the motive here, I would still reject this request.

However, what @rswarup really wants is to pass command-line arguments in for the test to use and is attempting to use Categories as a workaround. That's a valid request. In fact, I thought we already had an issue for this but I can't find it. If it turns up, we can mark one or the other duplicate.

@rswarup I have retitled this issue to reflect what I believe you actually want. Is that OK?

**Comment by rswarup** [comment]
Thanks @CharliePoole. Yes you are absolutely right. I need to get Selected categories only because currently there is no other way of passing command line arguments to my test. If that is taken care of in some way, then that would be great.

Such a feature can really bolster this framework further as it can enhance the data driven capability to a major extent.

**Comment by CharliePoole** [comment]
We keep getting duplicates of this issue, so it must have some interest to people.

Most recently, @oznetmaster proposed a specific design approach in #1533. I'm marking this as in design status. Please comment on the approach proposed, which I am summarizing below.

As a general notice to users: When you see an issue, particularly one that has already been accepted like this one, please add your comments and suggestions to the issue rather than creating a new one. It's hard enough to track all the issues without duplicating them. FYI you can tell this is an accepted issue because it's categorized as a feature and assigned to the Backlog milestone.

Anyway... #1533 proposes both a command-line format for the feature and a method to access arguments from your test. Those are the two design decisions we need to make. Please read #1533 but put your comments here to get the most attention.

**Comment by CharliePoole** [comment]
Since nobody has taken it up, I will handle the design phase at least...

Seems like there are three user-facing design issues to resolve right now
1. How parameters are accessed by tests
2. How parameters are entered on the command line

On top of that there is an internal issue
3. How the parameters are passed along to tests

My thoughts follow...

**1. How parameters are accessed by tests.**

Going along with @oznetmaster 's suggestion, I would propose we add a new property
to TestContext...

```C#
  IDictionary<string, string> Parameters { get; }
```

The available parameters would remain unchanged for the run,
One could argue that it should be "Arguments" - I'm OK either way.

This approach implies that all parameters are named. If somebody sees a real need for positional parameters, we can look at that, but it seems like extra work for no particular benefit.
 
**2. How parameters are entered on the command line**

I'd like a command-line option that takes a string defining either a single or multiple test parameters. 
```
  --params:name1=value[;name2=value2]*
```

I'd be OK with `,` in place of or in addition to `;`. For an abbreviated form, `-D`, as suggested by @oznetmaster would work well.

I think the values should be strings only, with any further parsing done by the test.

**3. How the parameters are passed along to tests**

The key implementation issue seems to be whether to use static or instance properties in TestContext and TestExecutionContext. Since the parameters remain the same for the entire test run, they could easily be static. However, if we want to be able to test this feature, it may be preferable to make the properties part of the CurrentContext for each class.

Comments invited... once there is concensus, I'll take off the design label.

**Comment by oznetmaster** [comment]
I think that both string and numeric parameters should be allowed.  It seems like the majority of the use of these parameters will be numeric.  String could be in single or double quotes and numerics unquoted.  Numerics could be long or decimal or double, not sure which is best.  Parameters would be `IDictionary<string, object>`, in this case.

However, because the Parameters are read only, I would prefer that Parameters be exposed as an indexed property with a string indexer (Parameters[<name>]) and only a getter, no setter.

**Comment by CharliePoole** [comment]
I'm OK with typed retrieval from the TestContext, similar to what we already do with TestPackage, but I think it's cleaner if the console doesn't deal with typing and just passes the strings along.

Exposing as an indexer only is a good idea. Alternatively, to deal with the typing, we could use a generic method.

**Comment by CharliePoole** [comment]
I did some experimenting on this and ran into a problem.

Currently, our APIs have no way to pass test parameters to the driver for a run. We pass in all the option settings when we load the tests and only pass an event listener and filter to the run.

If we pass the test run parameters to the load method, users of the console runner or of nunitlite won't notice a problem. Those runners do a load, run and exit.

But with the gui it could be inconvenient. Normally, you load the tests once and run multiple times, only reloading if you have changed the code. It's a minor inconvenience but you would have to reload any time you changed the run parameters.

I think we should still go ahead with this but looking forward there may need to be an API change to make it work the way it really should.

**Comment by argha007** [comment]
Can I get in C# code in [SetUp]  RunBeforeAnyTests() method the categories passed from command line argument? I am using nunit 2.6.2 version. 

Please let me know if I can get the category name passed to the nunit runner from console as getting the property name i want to do dome customization in setup... Please help..

TestContext.CurrentContext.Test.Properties["_CATEGORIES"]).Contains("Mobile"));

Will this work in setup method in setup fixture to get the command line argument. i want to get in setup method the argument not in the test method itself.

**Comment by CharliePoole** [comment]
@argha007 This is a closed issue. Asking questions here is not generally useful. You should ask on the nunit-discuss list or - if you think there is a bug - file a new issue. That said... here's a short answer. Please try the discussion list if you need to continue the discussion.

No version of NUnit allows your test to know __why__ it is being run. It may have been selected by category, by name, by multiple categories or by some combination. The reason we don't do this is twofold:
1. It's incredibly complex, since you can use boolean expressions to combine categories.
2. It would encourage tests to do different things depending on who ran them and why. That's a really bad idea, since a test should always do what it is designed to do.

If there are parameters for the test, they need to be passed in using attributes. Run parameters (command-line) may also be used in NUnit 3.4 and higher, which is what this closed issue is about.

**Comment by argha007** [comment]
ok thanks for your reply @CharliePoole ... appreciate it... just want to know that could i access the command line arguments passed from the command line in test setup method? if yes could u let me know how?

**Comment by argha007** [comment]
For example, to start a test:
  nunit-console NUnitDemo.dll /run=STR /err=STR //myparameter:abc

And then, from the test code I can do this:

[TestFixtureSetUp]
For Example:
$nunitRunner = "C:\Program Files (x86)\NUnit 2.6.2\bin\nunit-console.exe"
#----- get latest report----#
$testReport = "c:/tmp/TestResult_" + $(get-date -f yyyy_MM_dd_HH_mm_ss) + ".xml"
#----- get latest test exe ----#
$latestExe ="C:\\Test.dll"

 & $nunitRunner /xml=$testReport $latestExe /include:Mobile

in code:
public void setup(){
  string[] args = Environment.GetCommandLineArgs();
  foreach (string arg in args)
  {
    // process my command line arguments
    if (arg.Contains("//"))
      // do something
  }
}

want to get xml and include values... @CharliePoole

**Comment by CharliePoole** [comment]
OK... I'll go one more answer here... The answer is no, for the same reason that you can't get the operating categories. The test does not know what program is running it. Maybe it's nunit-console, maybe it's the gui, maybe it's resharper, etc. The runner may not even have a command-line.

Run Parameters were invented to  solve this problem. Command-line programs have options to supply them while other kinds of programs supply them in other ways, but the test can access them in the same way in every case.
