### ISSUE TITLE
Does nunit.nuspec require dependency on Microsoft.Bcl.Async?

### ISSUE THREAD

**Issue by jcansdale** [nunit/nunit#723]
I noticed that when compiling for net40, the NUnit NuGet package takes a dependency on Microsoft.Bcl.Async. This seems like a heavy dependency for a relatively lightweight framework assembly.

Looking at the 'nunit.framework-4.0' project, it doesn't appear to reference System.Runtime, System.Threading.Tasks, Microsoft.Threading.Tasks or any of the other Microsoft.Bcl.Async associated assemblies. The nunit.framework.tests-4.0 project does however reference these assemblies.

Is the Microsoft.Bcl.Async dependency really required by nunit.framework? What would happen if it was removed? Could it be left to the test implementer to decide whether or not to reference it?

**Comment by rprouse** [comment]
Jamie,

It has been on our todo list to check if it is actually needed, but we
never got around to it. I am pretty sure it isn't. I will get it removed
for the next release if it isn't needed.

Rob

**Comment by jcansdale** [comment]
That's great, thanks. :)

**Comment by CharliePoole** [comment]
Thinking about it, I wonder if we really should be distributing this in _any_ of our packages. We include it in the packages that have tests, so that any user can run the tests. However, the intent is that Tasks should work on those systems that have 4.5 or have the 4.0 with the async package. It's not to modify the system on which NUnit is installed.

There is one hitch here. If we don't include the async package, then those 4.0 tests that depend on it will fail. Maybe that's acceptable though. A longer-term solution could be to make the PlatformAttribute sensitive to the presence of async.
