### ISSUE TITLE
AreEqual overload that takes an equalitycomparer

### ISSUE THREAD

**Issue by JohanLarsson** [nunit/nunit#725]
Would look like this:

```
public static void AreEqual<T>(T expected, T actual, IEqualityComparer<T> comparer)
{
    ...
}
```

A couple of useful default comparers are:
- BinaryEqualsComparer
- XmlEqualsComparer
They would serialize expected and actual and compare the bytes.

Should I write a PR for this?

**Comment by CharliePoole** [comment]
We are not in general creating new features in the "classic" (aka legacy) Asserts. The prefered way to do this would be to allow use of the Using modifier on the constraint-based assert with an IEqualityComparer...

   Assert.That(expected, Is.EqualTo(actual).Using(comparer));

This already supports use of IEqualityComparer as well as other options.

**Comment by JohanLarsson** [comment]
The legacy asserts are much cleaner imo. In fact I don't know of any project that uses the fluent asserts, perhaps because of noise or just a matter of taste.
What is the harm in adding this?

**Comment by CharliePoole** [comment]
From a different perspective, the addition might be considered noise. :-)

Here are some considerations:

* We have to maintain both the classic asserts and the constraint-based asserts. Even though the former is based on the latter, situations arise where a separate change is needed. Your other recent PR is a good example.

* The interface becomes crowded for users, particularly novices. Admittedly, this is mitigated to some extent by the existence of Intellisense nowadays.

* Many features can easily be added to the classic assert by a user who really wants it. This one is a good example. In addition, I have plans to make this even easier.

* Based on the posts I see, most users (comment below) seem to have moved on to constraint-based asserts, with the exception of a few extra classic assertions for simple cases - generally simple equality and the basic asserts (True, False, Null, NotNull) where the constraint-based approach doesn't add any benefit. AreEqual, in fact, appears to be used less than the others because of the long-standing confusion between expected and actual.

* Not really a reason, but fwiw we once had a comparer argument for equality. It was removed many years ago without a whimper of complaint from users. :-) Of course, we could still re-implement it, but the lack of negative feedback tells me it was not a widely known or used feature.

Folks often tell me that everyone they know uses NUnit in a certain way. Sometimes, different folks tell me completely opposite things. I can only guess that we all tend to know and work with a set of people who work the same way we do. This isn't a criticism - I'm know I'm guilty of the same attitude sometimes.

While this issue remains a "won't fix" I don't want to be unilateral. Consequently, I will start a discussion on the developer list, which you are of course welcome to join.

**Comment by JohanLarsson** [comment]
Sounds great that you will consider reopening it.
Here is a scenario that is not uncommon where it would be nice:

```
[Test]
public void Test1()
{
    ... arrange & act
    Assert.AreEqual(expected.Prop1, actual.Prop1);
    Assert.AreEqual(expected.Prop2, actual.Prop2);
    ...
}

then Test2, Test3... with the same asserts.
```
This comes up quite often where it does not make sense to override equality for a type.

**Comment by MgSam** [comment]
I definitely agree this overloads with IEqualityComparer should be added. `Assert.AreEqual` is superior to other assertions since it understands "expected" vs "actual" and the UI can report these things. The methods on Assert are also, by far, the most commonly used in NUnit.

I think rather than making things easier for novices by not adding overloads, you're making them harder. Most developers do not want to go and read end-to-end documentation in order to figure out exactly how to get the assertion they need. They just want to let Intellisense show them what options are available.

In addition, in my anecdotal experience, I've been using NUnit for nearly 10 years and written/read thousands of unit tests and in that time I think I've seen the fluent syntax used only a handful of times.
