### ISSUE TITLE
how to use Assert.AreEqual() to compare an object with another?

### ISSUE THREAD

**Issue by Benjamin4git** [nunit/nunit#730]
I know AreEqual(object expected,object actual) can be called when you want to compare one object with another.
But,actually,things are not that easy like I thought before.
When I checked definition of AreEqual(object expected, object actual),I saw these:

 public static void AreEqual(object expected, object actual);
        //
        //     Verifies that two unsigned ints are equal. If they are not, then an NUnit.Framework.AssertionException
        //     is thrown.
        //
        // parameters:
        //   expected:
        //     The expected value
        //
        //   actual:
        //     The actual value

I find that "object" actually refers to "unsigned int" . It's a really confusing function!
So , I want to know ,how can I use Assert to compare two real object?

**Comment by CharliePoole** [comment]
NUnit 3.0 uses only double and object overloads for Assert.AreEqual. NUnit 2.6.4 uses a number of other overloads, including object. The comparison works for any type that defines AreEqual correctly.

Of course, it's possible for the comments to get out of sync with the  code. However, I looked at the code and the documentation pages for both NUnit 3.0 and NUnit 2.6.4 and that's not the case. Everything matches correctly.

Can you tell us what version of NUnit you are using? Can you tell us where you found the documentation you quoted? The comment lines you quoted don't appear to match any format we use.

**Comment by Benjamin4git** [comment]
I'm using NUnit 2.6.4 in VS2013.
![x g6k c 8l actc459 w](https://cloud.githubusercontent.com/assets/8764482/8634240/ea350a30-2823-11e5-9343-dacd1fafe826.png)
As shown in the picture,the confusing documentation is in nunit.framework.dll v.2.6.4.14350 (by the way, I;m a Chinese :)

And in fact , I know if two instances that both refer to one same object, and Assert.AreEqual(instance1,instance2) will pass the unit test.
But , if I have code like this:
 public class EmailInfo
    {
        public string Body{get;set;}
        public string To { get; set; }
        public string Subject { get; set; }
   }
 [TestFixture]
    public class UnitTest1
    {
 [Test]
        public void EmailIsEqual_ReturnTrue()
        {
            EmailInfo email1 = new EmailInfo
            {
                Body = "fake exception",
                To = "someone@somewhere.com",
                Subject = "can't log"
            };
            EmailInfo email2 = new EmailInfo
            {
                Body = "fake exception",
                To = "someone@somewhere.com",
                Subject = "can't log"
            };
            Assert.AreEqual(email1, email2);
        }
    }
Yeah, they have the same values,but Assert.AreEqual(email1,email2) will not pass the unit test . 
Thanks for your replying,I'm just a new guy in NUnit or in unit test, if I have something  wrong,please forgive me :)

**Comment by CharliePoole** [comment]
From the image, it seems the file you are displaying is named UnitTest1.cs. It contains Chinese characters in the comments. Also, it doesn't have the code for the asserts! Each definition simply ends with a semicolon. So this is definitely not a file from NUnit.

My guess is that somebody made this file to document NUnit for you. Possibly someone in your company? In any case, it is correct. The comment about unsigned ints appears before the definition for the uint entry point, which is the normal location for comments.

Your example code doesn't work because EmailInfo does not define equality in any way. I understand that you want the two to be equal if each of the properties is equal, but that's not the way equality works. For each class you create, you have to define equality. This is a C# issue.

In fact, we have a request that NUnit should figure out equality in a case like yours, based on properties. However, it is not implemented in any current version.

I'm closing this issue, since it's not really a problem in NUnit. In general, it's better to address questions for discussion to the nunit-discuss list on google. However, I'm happy to answer any further questions about this particular code issue here.

Make sure you have the current documentation for NUnit 2.6.4 and use it rather than the file you are looking at!
