### ISSUE TITLE
Workers number in xml report file cannot be found

### ISSUE THREAD

**Issue by constructor-igor** [nunit/nunit#735]
When run console with "--workers=4" parameter
```
nunit-console.exe InfraTests.dll  --workers=4
```
it shows the paremeter on display
![image](https://cloud.githubusercontent.com/assets/1849690/8669938/43255b14-2a21-11e5-9871-8ecf5db0447d.png)
but I cannot find the information (number of workers) in genereate report file "TestResult.xml".

Also, if user doesn't set number of workers, console "nunit-console.exe" doesn't show actual number of used workers.

**Comment by CharliePoole** [comment]
This partially duplicates #713

**Comment by CharliePoole** [comment]
This isn't as easy as it might appear. The number of threads to be used is not known to the console runner. The default value is calculated by the engine based on it's own formula. We only display options that are set by the user because we know those will be used.

It would be useful to know the resolved value of various settings and display them on the console. This would require an engine function to retrieve those settings after the test is loaded.

**Comment by CharliePoole** [comment]
Either we should move this out of the beta or move #713 into it. Both should be in the same milestone.

**Comment by rprouse** [comment]
Move both out of beta 4?

**Comment by CharliePoole** [comment]
I moved both of them to 3.0. Since they impact the XML format, they should probably be in the release.

**Comment by CharliePoole** [comment]
Looking solely at the console display portion of this issue... One way to resolve it would be to take certain "policy" decisions out of the hands of the engine.

Right now, the code to decide what default values to use for number of thread workers, as well as a number of other things, is contained in the engine. The idea is that each runner would be subject to the Engine default values, although it could override them.

Of course, right now, we only have one runner, so it's somewhat academic. However, I have tried to keep this logical separation in mind by not letting the console runner "predict" what the engine will do in the absence of specific parameters.

We **could** do this differently. We could decide that each runner sets its own default policies. For example, if the runner **always** told the engine how many worker threads to use, then the engine would have that information to display. Any engine default would become a sort of "default default."

Other settings to which this could apply are --process and --domain. If I spend time on it, I may find others. @nunit/core-team Does this approach make sense? The alternative seems to be that we would add an engine function that is able to return the default value used for any setting, which sounds like an unnecessary complication to me.

**Comment by rprouse** [comment]
I don't like the potential for different default behavior depending on the runner you are using. If I run a set of tests in any runner with a set of settings, I would expect them to run the same way in each runner.

I also don't like the code duplication of moving the decisions out to every runner.

As an alternative, could we move the responsibility for setting the defaults out the the API layer? The API could set the defaults and pass them in to the engine through the settings while at the same time making them available to the runners?

**Comment by CharliePoole** [comment]
What if a runner requires a certain setting in order to work at all? Shouldn't the runner still be able to override the defaults, if they don't meet its requirements? Think about our ongoing NCrunch discussion.

That said, I can see that two runners using a similar command-line should probably have the same defaults.

If we put it into the API layer, then the API layer will have to understand settings. Right now all it knows is that the TestPackage contains some kinds of settings. It just passes them on.

I can imagine an interface or service that would take a TestPackage and update it with the default settings. We do that internally already, so it wouldn't take much to expose it.

**Comment by CharliePoole** [comment]
This is basically resolved by PR #834 

The issue of "unknown framework settings" will have to be resolved when we actually have other frameworks to deal with.
