### ISSUE TITLE
Unexpected time in report file

### ISSUE THREAD

**Issue by constructor-igor** [nunit/nunit#737]
File "TestResult.xml" has **correct local time**  "**2:01 PM**"
![image](https://cloud.githubusercontent.com/assets/1849690/8671809/dacb9aaa-2a30-11e5-9400-2e40b7913bc0.png)

but file contains other times (**11:01**).
I expect, by default, local time in reports file.

```
start-time="2015-07-14 11:00:20Z" end-time="2015-07-14 11:01:05Z" duration="45.305610"
```

**Comment by CharliePoole** [comment]
The XML results file uses UTC NY design. Future versions of NUnit will allow running tests across multiple servers, which could be located in different time zones.

**Comment by constructor-igor** [comment]
I understand, but when we execute all our tests on our servers (placed in same time zone) we prefer see local time.
Probably, it can be implemented via some plugin system? Does nunit v3. support plugins?

**Comment by CharliePoole** [comment]
The engine (which is what runs the tests) supports plugins, but there isn't a defined extension point for controlling the time format. There is an extension point for defining a complete new output format, but that seems like overkill for this problem.

Let me think about this and discuss with the team. Maybe a command-line option would be a reasonable course here.

**Comment by CharliePoole** [comment]
We have had a discussion about this among the developers. We considered several options and decided to maintain the UTC time format in the primary XML output format.

Secondary output files and reports generated from the primary file can easily support a change in format, so long as the desired Time Zone is provided as an input.

To clarify the terminology, by primary format we mean the format of the native NUnit3 XML that is sent by the framework, through the engine, to the console or other runner. This is known as the nunit3 format. The console is capable of writing this XML to disk if requested.

By a secondary format, we mean some sort of transformation based on the primary format. The console currently supports the nunit2 format for this purpose as well as a format that makes use of a user xslt transform. Formats can be added as extensions. Note that a format can produce any sort of output that is desired: text, XML, HTML, etc.

With that general direction in mind, I think we should close this issue and create additional issues for specific reports and output files if any are needed.

@constructor-igor What do you think?

**Comment by constructor-igor** [comment]
Looks OK. Please, could you create repository for extensions and place existing extensions?

**Comment by CharliePoole** [comment]
We're still working on the technology to be used for extensions. The current beta uses mono.addins but that will probably be replaced with a simpler plugin design of our own. Once the extension tech is firmed up and the interfaces are stable, we'll think about a repo for user extensions.

At the moment, you could do one of two things:

1. Use the existing facility to transform the nunit3 file using xslt. Not being an xslt guy, I don't know if that would work for this case, since it involves some calculation to change the times.

2. Write a console app that does the same thing after NUnit has run. You would need to rewrite the file, one element at a time, changing all the times. Tedious but not hard in C#.
