### ISSUE TITLE
Environment.CurrentDirectory not the same as with NUnit2

### ISSUE THREAD

**Issue by stffabi** [nunit/nunit#742]
The Environment.CurrentDirectory is not equivalent in NUnit3 as with NUnit2. The following Test passes with NUnit2 but fails with NUnit3

```
    [TestFixture]
    public class Class1
    {
        [Test]
        public void CurrentDirectory()
        {
            var lCodeBase = new Uri(this.GetType().Assembly.CodeBase);
            var lCodeBaseDirectory = System.IO.Path.GetDirectoryName(lCodeBase.LocalPath);
            Assert.AreEqual(lCodeBaseDirectory, Environment.CurrentDirectory);
        }
    }
```

NUnit Console Runner 3.0.5674
Copyright (C) 2014 Charlie Poole

Test Files
    D:\Framework\01_Source.git\NUnitFailers\NUnitFailers\bin\Debug\NUnitFailers.dll

Runtime Environment
   OS Version: Microsoft Windows NT 6.3.9600.0
  CLR Version: 4.0.30319.0

Options
    ProcessModel: Default    DomainUsage: Default
    Execution Runtime: Not Specified
    Work Directory: D:\Framework\01_Source.git\References\NUnit
    Internal Trace: Off

Test Run Summary
    Overall result: Failed
   Tests run: 1, Passed: 0, Errors: 0, Failures: 1, Inconclusive: 0
     Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0
  Start time: 2015-07-16 06:35:00Z
    End time: 2015-07-16 06:35:00Z
    Duration: 0.201 seconds

Errors and Failures

1) Failed : NUnitFailers.Class1.CurrentDirectory
  Expected string length 62 but was 43. Strings differ at index 27.
  Expected: "D:\\Framework\\01_Source.git\\NUnitFailers\\NUnitFailers\\bin\\Debug"
  But was:  "D:\\Framework\\01_Source.git\\References\\NUnit"
  -----------------------------------------^
at NUnitFailers.Class1.CurrentDirectory() in D:\Framework\01_Source.git\NUnitFailers\NUnitFailers\Class1.cs:line 18

**Comment by CharliePoole** [comment]
This change is by design. See https://github.com/nunit/nunit/wiki/Breaking-Changes

In previous versions of NUnit, we guaranteed that the current directory when running a test would be set to the directory containing the test assembly. We found that having NUnit mess with the current directory caused other kinds of problems so for 3.0, we do not set the current directory at all.

If you need to know the directory containing the test assembly, use TestContext.CurrentContext.TestDirectory.

If you need the directory where NUnit will save the XML result and other output files, use TestContext.CurrentContext.WorkDirectory.
