### ISSUE TITLE
NUnit 2.6.4 stable version - Src.zip unavailable.

### ISSUE THREAD

**Issue by Aviage-Uma** [nunit/nunit#743]
Hi Nuint Team, 

Since i am not able access your google.groups link, I am posting this here.

Why there is no source code zip (src.zip) available for 2.6.4 current stable version ?.What do we need do to get the src.zip for 2.6.4 version ? do you have plans to publish in your site soon? If so, how long will it take? We may need src.zip for project specific purpose. Please suggest a solution to this issue.

Thanks & Regards,
Uma

**Comment by rprouse** [comment]
You can get a source Zip of the 2.6.4 source from GitHub at https://github.com/nunit/nunitv2/releases/tag/2.6.4. We did not post it to nunit.org because it is just a Zip of the repository, not the version we normally package.

You can also fork or clone the git repository for 2.6.4 from https://github.com/nunit/nunitv2 using the 2.6.4 tag.
