### ISSUE TITLE
Review Use of Mono.Addins for Engine Extensibility

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#749]
Mono.Addins provides extensibility for the engine. The purpose of this issue is to review it's use and decide if we are getting enough benefit from mono.addins to justify the effort of using it. At the same time, we will try to evaluate options for replacing it.

**Comment by rprouse** [comment]
I agree that this seems like overkill for our needs. I think that the extendable attributes will be the majority of the NUnit 'addins'. Even if we don't use Cecil, it would be fairly easy to inspect assemblies in a given set of addin directories that implement a given interface. We could even make that less expensive by requiring an assembly level attribute so that we don't have to inspect all of the types if the attribute does not exist. The attribute could even specify which of the interfaces that addin supports and maybe add meta information for display in a GUI like author, `NUnitAddinAttribute( Type interface, string author, string description )` for example.

This isn't as efficient as caching the results, but if we are not going deep into every type in every assembly, I think it light enough. I'm sure we've all done it as a simple plugin architecture many times :smile:

We also won't get any of the hard to diagnose problems where the cache is invalid. It has only happened to me once when I was working on loading the engine from multiple install locations, but once we release and 3rd party runners start installing engines in multiple locations, it could start happening more.

**Comment by rprouse** [comment]
@CharliePoole, you've assigned this to yourself, but if we decide to go with a plugin model as above, I would be happy to take it.

**Comment by CharliePoole** [comment]
@rprouse I reassigned it to you but left it is:design to indicate that a little bit of up-front design is called for. Would you review how we did it in NUnit 2.x and see if some of that can be reused? I think it would be advantageous for users who have written addins in the past if this were similar, at least superficially.

Some thoughts for you... although I know you have done this before...

 * In NUnit 2.x there is a lot of code having to do displaying the addins and controlling their activation from the gui. I don't think we need any of that. We may want to allow activating and deactivating addins in the future, but I think either editing a file or running a small app should be sufficient for the job without cluttering the gui. Also, some people don't use the gui but might need this feature.

 * The biggest weakness of the addin approach in NUnit 2.x is that they have to be in a particular directory and that directory is located relative to the location of the library directory - equivalent in 3.0 to the location of the engine. I think we need another level of indirection so that we can have addins in various places and they need to be accessible to all runners. That's probably the trickiest bit.

 * Consider using the extension point concept we used in NUnit 2.x. It's a useful model and interfaces can be individualized for each type of extension.

 * Consider using some version of the NUnitAddinAttribute because it's familiar to people.

 * I like your idea of having some assembly-level attribute to qualify assemblies for inclusion as addins.

Charlie

**Comment by CharliePoole** [comment]
@rprouse If you have not had time to get going on this, I can take a shot.

**Comment by rprouse** [comment]
Feel free to grab it, sorry.

**Comment by CharliePoole** [comment]
Closing this issue now that the initial implementation is done. There is more work to do on addins, but we'll use separate issues for the enhancements.
