### ISSUE TITLE
xbuild and Frameworks work not very well together

### ISSUE THREAD

**Issue by ArsenShnurkov** [nunit/nunit#777]
https://gist.github.com/ArsenShnurkov/ca947ccb8e027e646f06

Project ".../src/NUnitEngine/mono-addins/Mono.Addins.csproj"
CSC:  warning CS1685: The predefined type `System.Runtime.CompilerServices.ExtensionAttribute` is defined multiple times. Using definition from `mscorlib.dll`
Compatibility/ExtensionAttribute.cs(32,22): (Location of the symbol related to previous warning)
/usr/lib64/mono/4.5/mscorlib.dll (Location of the symbol related to previous warning)
Compatibility/Grouping.cs(29,25): warning CS0436: The type `System.Linq.IGrouping<TKey,TElement>` conflicts with the imported type of same name'. Ignoring the imported type definition
...

error CS0121: The call is ambiguous between the following methods or properties
...

**Comment by ArsenShnurkov** [comment]
http://stackoverflow.com/questions/546819/strange-warning-about-extensionattribute

**Comment by rprouse** [comment]
Like many other libraries, the version of NUnit Framework that targets .NET 2.0 defines `ExtensionAttribute` so that we can write extension methods to make the code cleaner. If you reference that version of the NUnit Framework in a project that targets a newer .NET framework, you will see this warning which as the StackOverflow question says, you can safely ignore.

I believe that Mono.Cecil which we have started using in NUnit 3 does the same thing, so the warning may be coming from there.

**Comment by ArsenShnurkov** [comment]
What I don't understood, it is why I don't receive this errors when I build the solution with monodevelop on the same machine (with the only framework installed)

**Comment by CharliePoole** [comment]
@rprouse That would only explain that specific duplication. He has dozens of others, which are related to the System.Linq classes whose code I duplicated out of mono in order to build Mono.Addins for 2.0.

@ArsenShnurkov I'm surprised if it doesn't happen in all builds using the same compiler. Are you perhaps targeting 2.0 under MonoDevelop?

As previously stated, I think it's a waste of your time to worry about Mono.Addins building, since we are in the process of dropping it. The problems you see are one of the reasons it is going. See issue #774.

**Comment by ArsenShnurkov** [comment]
gentoo-specific bug -
https://github.com/gentoo/dotnet/issues/106
