### ISSUE TITLE
Make it easier to debug tests as well as NUnit itself

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#794]
In order to debug easily, it's necessary to do one of two things:

1. Run nunit-console under debug, specifying --process:Single so the test runs in process.

2. Attach to the agent while the test is running.

Generally, it's simpler to run in process when you can. However, it may not be possible if the test assembly needs to run under a different runtime from that used by NUnit. So we need to have the ability to do it both ways.

Additionally, it's often simpler to debug if tests are not running in parallel. However, some errors may only come up when running in parallel, so it's again important to have the choice.

Here's a proposal for review:

1. Add a --debug option to the command line, taking the same arguments as --process. However, different from --process, the default value is Single.

2. The --debug will option set the process model just like --process. In addition, it sets --workers:0

3. Any --process or --workers option __following__ --debug on the command line will override it.

4. If an agent is started with --debug in effect, we will attach the debugger automatically, if possible. If it's not possible, we'll break so that the user can attach.

I'm flagging this as an idea, so please comment. I scheduled it for the RC so we don't forget to discuss it, but we may decide to schedule implementation later.

**Comment by rprouse** [comment]
I think that --debug having the same options as --process, but --process being able to override is confusing. I would prefer --debug to have no options and respect either the default process or the --process command line.

I also think that --debug should set the --workers to 1 so that it is single threaded. That can be overridden on the command line.

The simplest option is to just call Debug.Break to allow attaching, but that might cause problems on some machines and will drop the user into our code, not theirs.

Attaching the debugger can be problematic too. I worked on that code for MbUnit and it was fairly tightly coupled to versions of Visual Studio and needed to be updated with each new VS release. Users also tend to want to attach to the instance of Visual Studio that is already running and loaded with their solution, not a new blank solution. This can be difficult if there are multiple copies of Visual Studio running.

Lastly, if we attach the debugger, we should set the debug targets to both managed and native in case the user is debugging down into native code. The user can't switch on the fly, so in MbUnit, we decided to always do both. That could also be part of the command line.

**Comment by rprouse** [comment]
I've been playing with `Debugger.Launch()` and it seems to be more reliable than I thought it was. It allows you to pick a running instance of Visual Studio and override which debuggers get attached. It isn't as seemless as the Visual Studio automation code that MbUnit used which automatically selected and attached to the running instance, but I think it is good enough and probably more reliable.

**Comment by CharliePoole** [comment]
I agree. I've been using Debugger.Launch myself and it takes care of a lot
of stuff for us. The key issue is whether we need to do something different
for debugging tests versus debugging NUnit. I'll try to do it with one,
but, if necessary, we can even have a special option for NUnit development,
possibly undocumented.

Charlie

**Comment by CharliePoole** [comment]
@rprouse Any particular reason you prefer workers:1 to workers:0?

**Comment by rprouse** [comment]
Completed with PR #808
