### ISSUE TITLE
`TestContext.CurrentContext.Test.Properties` from TestFixture should be available from `TestContext` for Test

### ISSUE THREAD

**Issue by jho1965us** [nunit/nunit#796]
`TestContext.CurrentContext.Test.Properties` from TestFixture should be available from `TestContext` for Test. Probably in an new member TestContext.CurrentContext.TestFixture.Properties

**Comment by CharliePoole** [comment]
This issue is similar to #548, which relates to individual cases accessing properties of the method.

In general, NUnit is designed to keep tests as separate as possible. This includes tests like TestFixtures, which contain other tests.

That said, many properties are of a nature that they should probably be passed down to or inherited by the lower level tests. The problem for NUnit is that properties may be created by users and it's hard to know which ones are intended to be inherited.

The options listed for resolving #548 also apply to this issue.

**Comment by nadvolod** [comment]
Hello all,
Was this issue ever resolved? From everything that I read, seems like it's still open. Or is there a work around? I'm running into this issue now and it's a bit frustrating as I can't read any data from my tests. Thanks for all your help in advance :+1:

**Comment by CharliePoole** [comment]
It was triaged and added to our backlog, which is where it remains. You can see most of this if you view the issues online on GitHub, since we use labels to categorize them.

**Comment by nadvolod** [comment]
I'm actually looking at it on Github. But I guess now I see the enhancement and normal priority Labels. I just wasn't sure if those Labels would change if this issue was fixed.

Do you know of a possible work around for being able to read properties from the methods?

**Comment by CharliePoole** [comment]
Tracking on GitHub, you'll eventually see it moving assigned to somebody who may leave comments about progress. Additionally, if you have ZenHub installed, you'll see it move from Backlog to To Do to In Progress and finally Done.

The simplest workaround would be to use a OneTimeSetUp method to store the value of the property in an instance variable. When you are in that method, you are running in the context of the fixture rather than any individual test.
