### ISSUE TITLE
Ignore attribute not work properly with TestCase attribute

### ISSUE THREAD

**Issue by darthKwisatzHaderach** [nunit/nunit#815]
Hi,

I have six test cases. I want to ignore two of them. When I do it as described below, I get error "Duplicate Ignore attribute.

	[TestCase("03/03/20166"), Ignore("PRX-1000")]
	[TestCase("03 03/2016"), Ignore("PRX-1000")]
	[TestCase("0303/2016")]
	[TestCase("033/03/2016")]
	[TestCase("03/033/2016")]
	[TestCase("03/03/201")]
	public void InvalidDeadlineDateFormat(string dateFormat) {}

I am not exactly understand how to ignore these tests. Maybe it is a bug?

NUnit Version 3 3.0.0-beta-4

Best regards, Dmitrii

**Comment by rprouse** [comment]
Sounds like a bug to me :)

**Comment by darthKwisatzHaderach** [comment]
The same situation with NUnit 2.6.4.14350

**Comment by CharliePoole** [comment]
Actually, it's not a bug, but I'll warrant it's confusing. Here is what happens:

The textual layout of your attributes means nothing to .NET. When you use
   [TestCase("03/03/20166"), Ignore("PRX-1000")]
   [TestCase("03 03/2016"), Ignore("PRX-1000")]
   [TestCase("0303/2016")]
it's just the same as
   [TestCase("03/03/20166")]
   [Ignore("PRX-1000")]
   [TestCase("03 03/2016")]
   [Ignore("PRX-1000")]
   [TestCase("0303/2016")]
Or even...
   [TestCase("03/03/20166")]
   [TestCase("03 03/2016")]
   [TestCase("0303/2016")]
   [Ignore("PRX-1000")]
   [Ignore("PRX-1000")]
The ignore attributes apply to the method and so would cause every test case to be ignored. But since you had two of them, you got a compiler error instead.

Since you are trying to ignore the individual test cases, you want this:
   [TestCase("03/03/20166", Ignore="PRX-1000")]
   [TestCase("03 03/2016", Ignore="PRX-1000")]
   [TestCase("0303/2016")]
Here, the "Ignore" is a named property of the TestCase attribute. We made the named property match the name of the IgnoreAttribute because they serve the same purpose, but I can see that this creates confusion as well.

**Comment by rprouse** [comment]
@CharliePoole, good catch, I totally missed the fact that the Ignore wasn't inside the TestCase.

**Comment by darthKwisatzHaderach** [comment]
Thanks for the detailed explanation!

**Comment by mateusz-dobrowolny** [comment]
Please add this example to the documentation:
   [TestCase("03 03/2016", Ignore="PRX-1000")]
https://github.com/nunit/docs/wiki/Ignore-Attribute

It is hard to search here for the solution, and the usage is far from obvious... :)
Thanks!

**Comment by CharliePoole** [comment]
Moving this to the documentation repository.

I think we need to figure something out here, but putting an example like yours on the IgnoreAttribute page seems strange, since it's not an example of the IgnoreAttribute, but of the Ignore property of TestCaseAttribute. Perhaps what we need is a section that explains how IgnoreAttribute actually works when used with a TestCase.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/docs #172](https://github.com/nunit/docs/issues/172) via [**ZenHub**](https://www.zenhub.com/)
