### ISSUE TITLE
Remove unnecessary using directives all over the code

### ISSUE THREAD

**Issue by elbaloo** [nunit/nunit#839]
While working on #824 I noticed other unnecessary using directives that I didn't remove in #836. If you want I can go ahead and create a new PR to remove those as well from all assemblies.

I also noticed that some files like [InvalidDataSourceException.cs](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/InvalidDataSourceException.cs) have using directives within the namespace while the majority of files have them out of/before it. Let me know if you would like me to standardize these as well.

**Comment by rprouse** [comment]
This is pretty low priority, but if you want to continue to get your feet wet, you can go ahead an remove the unused usings. I would ask that you only do this if you have Visual Studio 2008 and Compact Framework installed so that you can build the CF solution and that you have the Silverlight SDK for building the main solution. 

There are quite a few #ifdef's in our code, so using statements can appear to be unused, but actually refer to code that is only defined in the CF solution. We tend to be not as careful #ifdef'ing the using directives unless they outright break a build target.

If you would like to help with other issues or even other areas of the release, we would welcome that too. We are getting close to the 3.0 release and need a lot of help to pull it off. Feel free to email me at rob@prouse.org and we can talk offline.

**Comment by JinaJita** [comment]
Hey :) Is this still up for grabs? If it is I would like to do this :)

**Comment by rprouse** [comment]
@JinaJita this is an extremely low priority and I think I am going to close this issue. There is plenty of cleanup that could be done in the code that is just visual changes and so probably not worth it. I would rather see some of the other help wanted issues worked on. Please take a look around, there are plenty of other issues that we could use help with 😄
