### ISSUE TITLE
'Exclude' console option is not working in NUnit Lite

### ISSUE THREAD

**Issue by JSGuy7** [nunit/nunit#851]
When using exclude option, tests are not executed:
![2015-09-30 07_28_12-administrator_ c__windows_system32_cmd exe](https://cloud.githubusercontent.com/assets/14164233/10195902/e1006aee-6744-11e5-933a-fe73abf53012.png)

The code looks like this:
"Test.cs":
<pre><code>
namespace Test
{
    [TestFixture]
    public class Test
    {
        [Test, Category("C1")]
        public void TestMethod()
        {
            Console.WriteLine("Hello!");
        }

        [Test, Category("C2")]
        public void TestMethod2()
        {
            Console.WriteLine("Hello - 2!");
        }
    }
}
</code></pre>

"Program.cs":
<pre><code>
namespace NUnitLite.Tests
{
    public class Program
    {
        public static void Main(string[] args)
        {
            new AutoRun().Execute(args);
        }
    }
}
</code></pre>

Am I doing something wrong?

**Comment by CharliePoole** [comment]
@NikolayPianikov has confirmed this using nunit-console as well.

**Comment by oznetmaster** [comment]
This does not happen on my CF build.

Exclude works correctly in all cases.

It also passes the nunitlite.runner test suite which tests excluding classes.

```
Test Files
    SSharpNUnitLiteTests

Runtime Environment
   OS Version: Microsoft Windows CE 3.5
  CLR Version: 3.5.7283.0

Options
    Work Directory: \nvram\app08
    Internal Trace: Off

Selected test(s) -
    \SIMPL\app08\SSharpNUnitLiteTests.dll

Excluded categories: Extra

Test Run Summary
   Overall result: Passed
   Tests run: 109, Passed: 109, Errors: 0, Failures: 0, Inconclusive: 0
     Not run: 1, Invalid: 0, Ignored: 0, Explicit: 0, Skipped: 1
  Start time: 2015-10-01 18:11:43Z
    End time: 2015-10-01 18:11:47Z
    Duration: 4.586 seconds

Tests Not Run

1) Skipped : NUnitLite.Runner.Tests.TextUITests.ErrorsAndFailuresReportTest
Not supported on NETCF
```

**Comment by oznetmaster** [comment]
However, my command line is:

`"-result:SSharpNUnitLiteTests.xml;format=nunit3" "-out:SSharpNUnitLiteTests.txt" "-work:\nvram\app08" -noh -full "-test:\SIMPL\app08\SSharpNUnitLiteTests.dll" -exclude:Extra`

I do not know if explicitely specifying the -test option makes a difference?

**Comment by CharliePoole** [comment]
It could make a difference since both -test and -exclude contribute to the
filter. With only exclude, we run into the special case where a 'not'
filter is created as the topmost filter.

**Comment by JSGuy7** [comment]
The same thing happens for me when executed test is explicitly specified:
<code> -test:Test.Test.TestMethod -exclude:C2</code>

**Comment by oznetmaster** [comment]
This could be the crux of the problem:

```
		// TODO: Not yet clear how explicit match should work for NotFilter
```

Researching further....

**Comment by oznetmaster** [comment]
JSGuy7: try:

`
-test:Test.Test.Test.TestMethod -exclude:C2
`

or

`
-test:Test -exclude:C2
`

**Comment by oznetmaster** [comment]
This is actually an interesting philosophical issue.

Currently, the NotFilter, used for the excludes, simple returns the inverse of the base filter for that list.

This means that the current test, its parent test, and its descendant tests are checked for a filter match.

Therefore, if no test is specified, then ALL tests in the assembly are implicitly selected.  When the NotFilter is applied, every test in the assembly is checked against the filter, and if ANY test matches, the result is a false, skipping the implicitly selected top level test that contain the excluded category in some test in its hierarchy.

This seems to be the wrong result, although it philosophically could be correct.

I think that what should happen is that the NotFilter should check only for an ExplicitMatch with the current test, and not walk the test tree.

Perhaps Exclude should generate a different filter then the NotFilter?

Before I implement the change, comment would be appreciated.

**Comment by oznetmaster** [comment]
BTW... I was misinterpreting my output.  The -exclude was actually excluding an entire branch of the testing hierarchy.  The results were from all the branches that did not contain any tests with a category of "Extra".

**Comment by CharliePoole** [comment]
The last time I worked on this, I eliminated a lot of checking for Explicit within the filters with the presence of Explicit determining whether a test was selected. That simplified things a lot. I created IsExplicitMatch so that the program calling the filter could determine, where necessary, whether the match was explicit or not. Apparently, I left in that comment intending to return to the code but didn't.

Right now, IsExplicitMatch returns the negation of the base IsExplicitMatch. That does not seem right. Depending on how we use IsExplicitMatch, it seems to me that it should either return the same thing, or always return false.

So... looking at how we use it... It doesn't appear that IsExplicitMatch should be called at all if nothing is marked Explicit. So that "shouldn't" be the problem. :-)

The way things should work is that a workitem is only created if the filter passes. Can you determine whether a work item  is being created? Once there is a workitem, it should be executed unless it is explicit and not explicitly selected. This code is in both SimpleWorkItem and CompositeWorkItem.

That's not to say we don't have a problem with IsExplicitMatch... just that it's not what this bug is about.

**Comment by oznetmaster** [comment]
You are not understanding the problem.  I guess I was not clear.  I precisely understand why it is not working.  I was asking about how we wanted it to work.

 

The problem is in the use of the TestFilter.Pass method.  It does the tree walk for the matches.

 

So if TestSuite A has 20 Tests, and one of them has a Class C1, and –exclude:C1 is specified, the entire TestSuite A is excluded, because the filter does not pass.

**Comment by CharliePoole** [comment]
I was replying to your having pointed out a To do comment on
IsExplicitMatch.

On the question of what we want it to do, the filter should pass on the
fixture and only fail on the method with the excluded category.

**Comment by oznetmaster** [comment]
Sorry.

 

I had moved beyond that in the following comments.

**Comment by CharliePoole** [comment]
I tend to work my way down and reply to each comment where I have something
to say. Unfortunately, unless one is using email, as I am now but usually
don't, there is no indication as to what is being replied to.

**Comment by oznetmaster** [comment]
Since the NotFilter is currently only used with a CategoryFilter as its BaseFilter, is there any problem with "redefining" NotFilter to function as an "exclude filter"?  It would localize the fix to just the code in NotFilter.  Otherwise, a new filter type has to be added, and that affects multiple projects and source files.

**Comment by oznetmaster** [comment]
Actually, it appears that NotFilter should always return true for Pass, and then it will work as expected.

Making the change.

**Comment by oznetmaster** [comment]
It is interesting that the NotFilter tests actually test for the current functionality.  That is, they expect the entire test suite to not Pass if any test in the suite matches the exclude!

This must have been the desired result at some point in time?
