### ISSUE TITLE
Extensions support for third party runners in NUnit 3.0

### ISSUE THREAD

**Issue by serjic** [nunit/nunit#856]
Hi,
I'm implementing NUnit 3.0 support in ReSharper test runner. Everything is fine so far and I like the new APIes but there is one problem.
I'm using nunit.core.engine and it doesn't seem to support extensions. Extensions are important because test adapter for previous versions of nunit.framework is implemented as an extensions and we'd like to bundle at least this extension.

**Comment by CharliePoole** [comment]
Why not use the full runner?

It may include some features that you don't need, but I expect many of those to be moved to extensions anyway. The original motivation for a non-extensible core engine was the large footprint of mono.addins. Since we no longer use mono.addins, that's no longer a problem and the core engine will probably disappear as soon as we stop using it for the Visual Studio adapter.

To use the full engine, you will want to reference the engine api assembly and probably allow the api to acquire the engine for you rather than actually reference it. You can specify in your call to the api that you want to use a private copy of the engine, if you feel that's necessary. That would be the case if there are engine capabilities you do _not_ want to have available, although I can't really see why it would be a problem - you simply don't have to use them. You don't actually have to distribute the engine if you are willing to assume it's available but we are expecting that most 3rd party runners will want to include a copy of the engine with which they have tested.

I'll keep this issue open so we can discuss any other changes that may impact your use of (whichever) engine.

**Comment by serjic** [comment]
I would use engine.api but it doesn't have strong name so I can't load it form ReSharper test runner.

**Comment by CharliePoole** [comment]
AFAIK, that's just an oversight. I'll look into it.

**Comment by serjic** [comment]
Thanks)

**Comment by CharliePoole** [comment]
@serjic The beta 5 release contains strongly named nunit.engine.api and nunit.engine assemblies. You can use this issue to request any further changes.

**Comment by serjic** [comment]
Thanks, I've updated ReSharper to use Beta 5 with support for plugins.
I've got some more issues currently:
1. Reporting for tests from base class is different in NUnit 3 (compared to NUnit 2.6):
I've got test defined like this:

	[TestFixture]
	public class BaseClass
	{
		[Test]
		public void Foo()
		{
		}
	}

	class TestImpl : BaseClass
	{
	}
When I reference 3.0 framework I get:

        <test-case id="0-1001" name="Foo" fullname="TestReferencing30.BaseClass.Foo" methodname="Foo" classname="TestReferencing30.BaseClass" runstate="Runnable" seed="798259755" result="Passed" start-time="2015-10-19 15:35:32Z" end-time="2015-10-19 15:35:32Z" duration="0.004738" asserts="0" />

When I reference 2.6 framework I get:

        <test-case id="1-1005" name="BaseClass.Foo" fullname="TestReferencing26.TestImpl.BaseClass.Foo" runstate="Runnable" result="Passed" duration="0.000160" asserts="0" />

In 3.0 base test class is not mentioned anywhere. In ReSharper we perform test discovery basing on our code model and we need to pass ids that match ids of NUnit to receive test results correctly. The main questing here is: was this change intentional? 
I've been thinking why such names were reported in 2.6 and came up with the following sample:

	[TestFixture]
	public class BaseClass
	{
		[Test]
		public void Foo()
		{
		}
	}

	class TestImpl : BaseClass
	{
		[Test]
		public void Foo()
		{
		}
	}

In this example when using 2.6 adapter we can distinguish between base and derived class methods and report following test result:

![image](https://cloud.githubusercontent.com/assets/6841790/10583272/af50640e-7694-11e5-9bdb-837621399725.png)
 
When running with NUnit 3 we can only rely on 'seed' which doesn't exist in ReSharper test discovery process.

          <test-case id="0-1003" name="Foo" fullname="TestReferencing30.TestImpl.Foo" methodname="Foo" classname="TestReferencing30.TestImpl" runstate="Runnable" seed="1801850340" result="Passed" start-time="2015-10-19 16:04:51Z" end-time="2015-10-19 16:04:51Z" duration="0.000162" asserts="0" />
          <test-case id="0-1004" name="Foo" fullname="TestReferencing30.TestImpl.Foo" methodname="Foo" classname="TestReferencing30.TestImpl" runstate="Runnable" seed="17143493" result="Passed" start-time="2015-10-19 16:04:51Z" end-time="2015-10-19 16:04:51Z" duration="0.000031" asserts="0" />

**Comment by CharliePoole** [comment]
First off, I want to ask you to remember that we are doing "3.0" a major release with breaking changes. If we had wanted to retain much greater compatibility, we would have done an NUnit 2.7!

In other words, there are a lot of things about NUnit 2, with it's long history since 2000, that we wish we had done differently. The 3.0 release is our chance to change them. If we don't change them now, we believe we are obligated to wait for 4.0 and we don't want to do that!

So, for the specifics...

BaseClass... 

We have heard people complain about this oddity in NUnit 2.x for many years. It was very quickly after we introduced it that we decided it was a mistake to include the implementing base class in the Name of the test. However, looking at the output, I think there may be a different error. Methodname and classname should tell you exactly where the test is defined. I'm not sure it does.

Note that NUnit considers the test name and fullname as completely abstract strings. Any resemblance to class and method names is accidental. Users can completely rename the test in a parameterized test case. The methodname and classname attributes are provided for any runners that care how the tests match up with actual source code. Can you use these fields?

Seed... 

This is not intended for identification of tests. Since it's a random number, it will __usually__ be unique, but (since it's a random number) it will sometimes be the same. :-)

The id field is intended to identify tests in a run uniquely and does so.


Does this help?

**Comment by serjic** [comment]
Thanks for explanation. I completely agree that 2.6 notation seems archaic. I do use classname and methodname. And if there was one more parameter like originclassname (a class where a test methods is actually defined) - that would help us to match tests with source code even better.

**Comment by CharliePoole** [comment]
That's what classname is supposed to be. If it isn't, it's a bug.

**Comment by CharliePoole** [comment]
Specifically, classname and methodname together should allow you to find the code for a test.

**Comment by serjic** [comment]
OK, seems to be a but then. Looking forward to a fix)

**Comment by CharliePoole** [comment]
Closing this as fixed, since the strong-naming issue was fixed and the core engine no longer exists.

See #1011 regarding Engine packaging. Please comment there if you have any requests for how we package it.

**Comment by serjic** [comment]
I've got one more quick question. What is the proposed way to (explicitly in UI runner) run Ignored and Explicit test?
