### ISSUE TITLE
nunit-console output - move Test Run Summary to end

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit#859]
If you have a lot of errors, ignored or explicit tests, the Test Run Summary scrolls off the screen and you need to scroll up to see it. To me, this summary is the first thing I want to see, so I think it should be the last thing output.

**Comment by CharliePoole** [comment]
This is a change to what people are accustomed to seeing. They would get
all failures followed by skipped tests followed by the summary. It's
backwards from what you would expect on a printed report but may be better
for the console. It may also be justified since we are now listing more
things.

Anyway, let's wait and see what comments appear on this issue.

Folks, if you (want | don't want) this change, please comment!!!

**Comment by rprouse** [comment]
Along those lines, I would also like to see the errors output after the skipped/ignored tests :smile: 

To me, the summary is like a footer and therefore should be there...

**Comment by CharliePoole** [comment]
Ok, let's see what others think. If we don't  get feedback we can either
ask on one of the lists or just do it.

**Comment by CharliePoole** [comment]
Well, no feedback but it's annoying me too. Let's do it.
