### ISSUE TITLE
Review skipped tests

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#868]
We have a fairly large number of tests skipped on certain platforms. We should review all these and determine if the exclusions are still proper or if they can be corrected. Searching tests for use of the PlatformAttribute should locate most of these.

Lacking a better category, I marked this as a (potential) bug.

**Comment by rprouse** [comment]
`CultureSettingAndDetectionTests.SettingInvalidCultureOnFixtureGivesError` and `CultureSettingAndDetectionTests.SettingInvalidCultureOnTestGivesError` are valid excludes on Windows 10 because an unknown culture on Win10 creates a user defined culture. We could probably remove these tests since they are effectively just testing the underlying behavior of the `CultureInfo` class. We already have code in these tests to change the expected exception based on the framework version.

If agreed, I will remove.

**Comment by CharliePoole** [comment]
I'm OK with this.
