### ISSUE TITLE
Allow file references anywhere in the command line.

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#890]
Currently, the --testlist option allows a file containing a list of tests to be specified in the command line.

It may make sense to provide a more general mechanism for allowing files of arbitrary text to be specified on the command line.

This would replace the --testlist option.

One possibility would be to allow something like `[<filepath>]` to be used anywhere on the command line, and would result in the entire contents of the file being inserted in the command line at that point.  All newlines in the file would be converted to spaces.

In fact, the only thing on the command line could be a file reference, and the entire command line would then be retrieved from the file.

As an extension, it might be useful to allow an extension to this syntax `[<filepath>,<delimiter>]`, where `<delimiter>` would specify the string that newlines would be replaced with in the file (for instance a comma).

File references should be nestable up to some limit (three, perhaps).

The processing of the file references would occur at the top level, before any actual parsing of the command line occurred.

**Comment by CharliePoole** [comment]
I like the idea of allowing options - and possibly even the names of assemblies -  to be placed in some sort of response file. I don't want to over-engineer it however, especially since we would be originating this feature ourselves, rather than in response to user request.

Some thoughts...

What about the user of @filename, which is used by some other programs? The contents of filename would simply be inserted in the command-line, just as you are suggesting.

We may not want to completely replace --testlist, since it is used for simple lists of tests, one per line, usually generated by external programs. Although... it would only require such programs to put --test at the start of each line.

Nesting seems unnecessary as does the specification of delimiters.

**Comment by CharliePoole** [comment]
We will, of course, have to decide what command-line we are talking about: console, nunitlite or both.

**Comment by oznetmaster** [comment]
Well, I am a user, and I need it badly, since CF has such a short command line limit.

Almost all my tests already use the --testlist option if there are more then two or three tests in the list (using full names), and that has hit the command line limit on a couple of occasions.

**Comment by oznetmaster** [comment]
@filename is fine for me, as long as it will not be confused with any other commandline object element.

Reason for the delimiter is that it allows things like --testlist to be emulated, where the tests can be listed one per line, and they are processed correctly.  Without it, the tests listed in the file would have to all have commas after them, except for the last one.

**Comment by oznetmaster** [comment]
Nesting is required if we allow entire command lines in the file.  The command line may well need to reference a list of test generated elsewhere, for instance.

**Comment by oznetmaster** [comment]
I would think we would want to be consistent across both console and nunitlite?

**Comment by CharliePoole** [comment]
Most likely, we would in this case. I don't think it's so obvious that we
should make it an assumption, that's all.

We can deal with the details when we work this issue for 3.2.

**Comment by oznetmaster** [comment]
With the addition of the --p option, this has become more of an issue.  On CF, command lines are overflowing even faster.

We obviously did not get to this for 3.2, but it is a real necessity.

**Comment by CharliePoole** [comment]
Nor for 3.4. :-) We'll try again.

**Comment by CharliePoole** [comment]
You and I left it with differing, unresolved questions about how it should be implemented. Somebody needs to take it on, resolve the differences and code it.

**Comment by oznetmaster** [comment]
As you said "We can deal with the details when we work this issue for 3.2".  Well, I guess we still need to deal with the details :)  Maybe @rprouse might have some thoughts?

I am happy to take it on if we have agreement on what "it" is.

The fact that apparently there will have to be three versions of "it" is a pain as well :(

**Comment by oznetmaster** [comment]
One new thought I had was to allow an xml file that contains all the command line info be used.  We use xml for out, why not for input as well?

Then there could be a single --xml=filename option, and that would do it all.  Could be useful for alternative remote runners as well, ones that do not use remoting.

**Comment by CharliePoole** [comment]
Let's not assume 3 versions... I think a feature has to prove itself needed by each command-line program before we need it. We shouldn't add it just to be "consistent."

That said, I suspect that so long as we don't over-engineer it we will want it in multiple places.

**Comment by CharliePoole** [comment]
Of course, we do already use XML to tell the framework what to do. Both the console and gui runners do that. Making users create XML files sounds cruel, however. :-)

**Comment by CharliePoole** [comment]
More seriously, I remain in favor of a simple text file, containing exactly what the user would have typed on the command line - what was once called a response file. By doing that, we would simply be providing a way to have a longer command line, without having to add a bunch of extra code.

**Comment by oznetmaster** [comment]
Off the subject.. where is that xml file processed on the framework side?  In the engine?

I would love to be able to use any existing xml processing in my new WebSocket remote interface.

**Comment by oznetmaster** [comment]
And actually, I would much rather create an xml file that can be validated than a long, unclear, command line.  All the tools are there for creating one in most environments.  Could even provide intellisense in VS for it.

Create xml files for everything else (web.config, app.config, ..) in .NET.

But that is me :(

**Comment by ChrisMaddock** [comment]
Should any xml file just be an expansion of the .nunit project file functionality? It sounds like there would be a bit of overlap there - or am I missing something?

**Comment by oznetmaster** [comment]
nunitlite does not have .nunit project files.

However, that might be the best format to use if this was the way we decide to go.

**Comment by ChrisMaddock** [comment]
> nunitlite does not have .nunit project files.

That would be what I'm missing! I agree, implementing that existing format in NUnitLite sounds like a preferable solution that file based command lines...although it does mean the project format perhaps needs to be kept better up to date with new command line options. :-)

**Comment by rprouse** [comment]
I also think that xml is cruel. If we add it to the project file, we will also want to update the project editor to match. 

You say XML is used for web.config, etc, but actually, Microsoft is switching all of that to JSON. 

I would also prefer to just see this in the console. Nunitlite is supposed to be Lite. I suppose you want it for CF though. We should really consider spinning a separate CF runner off, I think it has conflicting needs.

**Comment by oznetmaster** [comment]
I plan to use the full gui with the cf build, so I am not sure what to spin off.

**Comment by oznetmaster** [comment]
And supposedly Json is better then xml?  I (and many others) are certainly not convinced.

**Comment by CharliePoole** [comment]
The NUnit project file is supposed to represent a piece of work that you come back to repeatedly, combining one or more assemblies with some settings required when loading them. Adding general run settings, like test selection to this file, would change it's purpose and require the user to repeatedly modify it while working.

Additionally, it's a legacy format and we need to decide whether to migrate it to a v2 format or come up with an entirely new format that allows nesting of projects. Such a new format might be json rather than xml.

We are coming very far afield in discussing an issue that pertains to the command line!

**Comment by CharliePoole** [comment]
@oznetmaster We have talked about spinning the CF build off from the framework itself. How exactly we do that depends on whether we want to keep the CF build in sync with the framework, keep it more or less stable or let it develop in its own direction.

Whether the gui supports it is another matter, since the gui is already a separate project.

IMO, this would only come after a number of other things outlined in #1589

**Comment by oznetmaster** [comment]
I do know that my user base wants it kept in sync with the regular framework, since many use both.

**Comment by CharliePoole** [comment]
Closed by #1846
