### ISSUE TITLE
Probably, Tuple has not consistent behavior.

### ISSUE THREAD

**Issue by constructor-igor** [nunit/nunit#893]
Next test fails (NUnit 2.6.4 and 3.0 Beta 4)

``` c#
        [Test]
        public void TupleIntVsDouble()
        {
            Tuple<int, int> actual = Tuple.Create(1, 2);
            Tuple<double, double> expected = Tuple.Create(1.0, 2.0 );

            Assert.That(actual, Is.EqualTo(expected));
        }
```

with unclear message (R#):
![image](https://cloud.githubusercontent.com/assets/1849690/10482804/e5bd23ac-7283-11e5-9cbe-cd1ee0b39368.png)

VS adapter:
![image](https://cloud.githubusercontent.com/assets/1849690/10482843/37222c06-7284-11e5-90dd-9a6ccfac0447.png)

But "same" tests pass:

``` c#
        [Test]
        public void IntVsDouble()
        {
            int actual = 1;
            double expected = 1.0;

            Assert.That(actual, Is.EqualTo(expected));
        }
        [Test]
        public void ListIntVsDouble()
        {
            List<int>actual = new List<int>{1, 2};
            List<double> expected = new List<double>{1.0, 2.0};

            Assert.That(actual, Is.EquivalentTo(expected));
        }
```

**Comment by rprouse** [comment]
I've moved this out to 3.2 because comparing two Tuples of different types isn't valid C#. In other words, `Assert.That(actual == expected)` will not compile.

It highlights a sort of problem with NUnit in that we try to be much more lenient with equality so people expect the same amount of leniency with all types.

I think that Tuples are a valid extension of our leniency, but when we work on this issue, I would like to see us refactor `NUnitEqualityComparer`. It is becoming a monster of a class. I would prefer to see it as the central coordinator of a series of equality types that each handles specific equality conversions.

**Comment by CharliePoole** [comment]
@rprouse Good approach. Let's do that for 3.2.

**Comment by CharliePoole** [comment]
I removed easyfix because refactoring NUnitEqualityComparer is not something I'd like a first-time contributor to try. Granted, @rprouse , it's easy for you or me... :-)

**Comment by jnm2** [comment]
@nunit/framework-team We just had the same discussion on the `ValueTuple` type now that C# has that type backing its tuple language feature. Would we be in agreement that the same purposes apply to `Tuple`? I was under the impression that `Tuple` plays a similar role in F#'s tuple language feature that `ValueTuple` now does in C#.

@mikkelbu Would you have any interest in this? I'm thinking it's going to be almost identical to https://github.com/nunit/nunit/pull/2290. If not, we can put it up for grabs since the implementation spec would be https://github.com/nunit/nunit/pull/2290. 😄

**Comment by mikkelbu** [comment]
@jnm2 Sure. I can take a look at it.
