### ISSUE TITLE
The NUnit 3 beta 5 broken compatibility

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/nunit#908]
"The console runner no longer accepts the –include and –exclude options." Do we have a strong vision to do it in the release version. Could we retain these arguments for compatibility for few versions?

**Comment by rprouse** [comment]
The command line in 3.0 has many differences to 2.6.x, so we wanted to make a clean break with the release so that people do not rely on functionality that we will end up removing. The functionality is still available with the new --where command line.

Not supporting include/exclude along with the new where filters simplified the code, reducing potential bugs and conflicts between the two sets of competing command line arguments.

Why do you want us to maintain compatibility? Are these command line arguments used internally by TeamCity?

**Comment by NikolayPianikov** [comment]
Yes, TC has fields: "NUnit categories include" and "NUnit categories exclude".
See https://confluence.jetbrains.com/display/TCD9/NUnit

**Comment by NikolayPianikov** [comment]
We could retain arguments in the TeamCity mode for example for few versions. Is it possible?

**Comment by CharliePoole** [comment]
It's actually broken for you in two ways: NUnit 3.0 has never had the expression syntax that is supported by 2.6.4 in the include and exclude arguments. We only supported commas.

The omission was deliberate. The alpha and earlier beta support for include and exclude was very rudimentary because the plan has always been to remove it once we supported a more general way of selecting tests. Now we finally have that ability.

We also planned to remove the --test option, but decided to retain it along with --testlist. The --testlist option is generally used by people who generate lists of tests to run programmatically and we felt we had to keep supporting that. Since we have --testlist, --test doesn't require any extra code.

I notice that you allow people to select whether they will run tests using NUnit 2.x or 3.0. Could you simply support include and exclude for 2.x and add a box for the "where" clause in 3.0?

Alternatively, you could accept include and exclude and generate TSL for the selection. For example:
  include: C1, C2
  exclude: C3
would give
  --where (cat==C1 ||cat == C2) && cat != C3

**Comment by NikolayPianikov** [comment]
Ok, thank you
