### ISSUE TITLE
Give warning message if SetUpFixture has no OneTimeSetUp or OneTimeTearDown

### ISSUE THREAD

**Issue by MaceWindu** [nunit/nunit#911]
In project that use nunit2 I had SetUpFixture class with [SetUp]/[TearDown] methods.
During migration to v3 I've noticed that extension for Visual Studio failed to load tests from assemblies without any errors in log.

I was lucky that one of assemblies had no SetupFixture class so I guessed where I had a problem and replaced method attributes with OneTime* versions.

I think it makes sense to detect such issues and provide descriptive error message (or at least mention it in migration notes/breaking changes)

**Comment by CharliePoole** [comment]
In general, we don't detect and report on attributes that we don't use,
because their number is potentially unlimited. However, in this special
case, we might be able to give a message about the **absence** of either of
the OneTime* attributes, since it doesn't make any sense to have a
SetUpFixture without one of them.

We do have a "Breaking Changes" document, which is prominently listed in
the documentation menu. It's at
https://github.com/nunit/nunit/wiki/Breaking-Changes Scan down to the third
table for this particular item.

**Comment by CharliePoole** [comment]
We will have to figure out how to handle this. If we make the SetUpFixture non-runnable, that will cause all fixtures under that namespace to fail. This may be what is wanted, since the SetUpFixture is not doing the setup that those fixtures need. Currently, we have no way to issue a warning except by causing the fixture to be ignored.

**Comment by CharliePoole** [comment]
It turns out that you can have a useful SetUpFixture with neither a OneTimeSetUp nor a OneTimeTearDown if you put an ActionAttribute on it. This will require a bit more design, so I'm postponing it.

**Comment by CharliePoole** [comment]
Actually, I wrote a test and determined we already set the SetUpFixture RunState as not runnable if there is a setup, teardown, testfixturesetup or testfixtureteardown attribute present.

However, this is not being displayed in the output and the tests in that namespace are being run. The SetUpFixture is simply ignored. We will need to define what is supposed to happen before we can really fix this.

**Comment by CharliePoole** [comment]
Well, I ran a test with a setup fixture containing only a setup method. It shows up on the console as an error. This appears to not be a valid bug, at least in the current build.

**Comment by rprouse** [comment]
@CharliePoole, you added the closed:notabug tag to this, so I assume you meant to close it. If not, we can reopen.

**Comment by CharliePoole** [comment]
Yes, I changed my mind a few times, but in the end it didn't seem to be a
valid bug.
