### ISSUE TITLE
Unclear error message from console runner when assembly has no tests

### ISSUE THREAD

**Issue by MaceWindu** [nunit/nunit#914]
Currently console runner gives following error when you try to run it with assembly without tests:
```
Unable to locate a driver for <ASSEMBLY_PATH>
```

**Comment by CharliePoole** [comment]
To be more precise, this does not happen with a test assembly (one referencing NUnit.Framework) containing no tests. The problem only arises when an assembly **either** has no tests **or** has tests for a framework that is unknown to NUnit.

Let's say you have created a new test framework, called "my.test.framework" and you wrote an extension so that NUnit could run those tests. Now somebody tries to run tests that use "my.test.framework" without installing your extension. In that case, "Unable to locate a driver" makes perfect sense as a message.

The problem is that NUnit has no way to tell the difference between the two situations: an assembly without tests and an assembly with an unknown "brand" of tests. So we need a message that works in both situations.

**Comment by michal-franc** [comment]
My proposition:
No suitable tests found in <assembly_name>.
\n Either assembly contains no tests or proper test driver has not been found.

**Comment by CharliePoole** [comment]
Sounds reasonable.
