### ISSUE TITLE
console runner --where parameter is case sensitive

### ISSUE THREAD

**Issue by MaceWindu** [nunit/nunit#918]
It looks like at least category filter property is case sensitive and must be spelled "Category". Spent some time trying to figure this out becase help use "category" in examples :)

I think one of those must be done:
- make properties, available for filtering, case-insensitive
or
- update help to use capitalized properties and add note that properties must be capitalized

**Comment by CharliePoole** [comment]
Please indicate where the docs are in error so we can fix.

The Category attribute has always had a capital C. is that what you mean?

As regards the where clause, it would be a mistake to treat a category as a property.

You may have looked at the NUnit code and seen we treat Category as a property internally but you can't really use it as such in TSL because it has multiple values. That's why there's a cat keyword.

Property names can't be treated as case-insensitive because we allow users to create them without restricting them. A user may have created properties that different only by case.

In case I've missed something, I'll leave this open so you can elaborate.

**Comment by CharliePoole** [comment]
I looked through the documentation for the Test Selection Language used with the --where option, which is located here: https://github.com/nunit/nunit/wiki/Test-Selection-Language

I can't find any issue there. Is this the page you were looking at?

NUnit does create a few properties for it's own use. However, there is actually no documentation published about what those are, since they are implementation details. You could use some of those properties to select on, but in general it would not be very useful. The intention was that you might want to select on user-created properties. For example, you might create a property called Priority and give it various values. Then you could select Priority == High, priority=hi, etc. depending on how you had defined the property.

**Comment by MaceWindu** [comment]
Sorry, I was talking about help from console runner:
```
 The --where option is intended to extend or replace the earlier
      --test, --include and --exclude options by use of a selection expression
      describing exactly which tests to use. Examples of usage are:
          --where:category==Data
          --where "method =~ /DataTest*/ && cat = Slow"
```

**Comment by MaceWindu** [comment]
I've checked document you linked:
- in console  help category specified like "category" (doesn't work) and "cat" (works)
- use of "Category" (works) not mentioned in console help and document

Maybe the same issue exists for some other properties, but I don't use them so I cannot tell right now.

**Comment by CharliePoole** [comment]
OK, sorry. You said "help" originally and I took it to mean the documentation. This is the help message displayed by NUnit-console. It's wrong, reflecting an earlier state of the code when we accepted category as a synonym for cat. We made a decision to simplify the syntax, eliminating aliases, but didn't reflect it in the help message.

What do you mean when you say use of "Category" works? I understand that the syntax is accepted, but I would be surprised if the filtering actually works for you.

Generally, I see this is shaping up as a documentation issue. We should give you a list of the properties we support and explain better that filters involving a non-existent property simply fail to match.

For example, you could use Priority==High and it would be accepted, because the syntax is valid. But if you have not created a property Priority, no tests will ever be run.

**Comment by MaceWindu** [comment]
Yes, use of "Category" filters tests the same way as with "cat" in last release

**Comment by CharliePoole** [comment]
I'm not looking at the code here, but I would predict that if you apply
several categories to the test, only one of them will work. :-)

I make the prediction on the basis that the value of the property Category
is an enumeration of categories. I believe the code for property filtering
uses the first property value only.

We distinguish properties that users are not expected to reference by use
of special names - all caps with a leading underscore. In NUnit 2, the
Category property was called _CATEGORY, which would at least tell you it
might be something special. Perhaps we should go back to that. Or perhaps
we should try to make it work. Hmm...

When you use cat, we actually fetch the Category property and iterate over
all it's values. However, that's more info than a user should need to have
in order to use it. :-)

**Comment by MaceWindu** [comment]
If I understood you correctly, that fixture with following attributes:
```
 [Category("one")]
    [Category("two")]
    [Category("three")]
```
will work only with one of categories if I use "Category".
But I tried
--where:Category=one
and
--where:Category=two
and both of them executed tests from that fixture only

**Comment by CharliePoole** [comment]
It has only been a week since I wrote that code, but I can't figure out why
that works. Maybe I was smarter last week!

I'm on my phone now so I'll check in the morning.

**Comment by CharliePoole** [comment]
OK... it's actually sort of obvious. Internally, all properties are multi-valued, without distinction. It's only by convention that some, like the process id, are unique.

So my code had to iterate through all the values and compare to each of them, succeeding if any one of them succeeded. This will, in fact, work for any user-created, multi-valued property.

So I'm back to this being just a matter of documentation.

**Comment by CharliePoole** [comment]
The documentation page has now been updated and the console help fix has been merged. Closing this now.
