### ISSUE TITLE
Allow comma delimited lists in --where option

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#925]
It would both be consistent with the --tests option, and would be simplifying, to allow comma delimited lists wherever they made sense in the --where option (e.g. cat=C1,C2,C3).

**Comment by CharliePoole** [comment]
If we allow it for cat, that means a category name can't contain a comma.
Ditto for property names. For methods and classes, we are safe. For test
names, we have code we use to detect commas outside of the argument list,
which we could reuse here.

When the user creates a category or property, we don't currently restrict
the name in any way. Would we need to do that? I don't want to go back to a
similar situation where we allowed categories to contain a hyphen but using
it broke our category expressions. Admittedly, hyphens are handy in names
and commas are not, so maybe it's less of an issue.

**Comment by oznetmaster** [comment]
I would think that it would not be an issue, Have you ever seen a category name with a comma in it?

If you want to get fancy, there are a number of syntaxes where the delimiter for the list can be specified .

I have seen
`/<delimiter><item1><delimiter><item2>`
for one example.

**Comment by CharliePoole** [comment]
I agree that it's not much problem for categories, provided we want to do
it at all. And we do have three different quotes that can already be used.
I worry slightly more about the user-side complexity that arises if some
comparisons can use comma in this way and some cannot.

**Comment by oznetmaster** [comment]
Different quotes do not really help with the list delimiter issue.

Are there any comparisons for which lists make no sense?  If not, then allow them for all comparisons.  No complexity.

**Comment by CharliePoole** [comment]
Hey @nunit/core-team ...

@oznetmaster and I were discussing his desire for this feature being added back to TSL (it was in an earlier version) so I asked him to create an issue. Let's hear what you think about it.

It doesn't make the code much more involved but it does present the users with some added complexity - or at least I think it does.

The idea is that the comma on the right hand side represents "any of these" and works with all operators.

So...

IMO the reasonable options are

1. Don't do it.
2. Do it for cat and property only
3. Do it for everything, (test, method and class, cat, prop).

For the third one, we would have to deal with the fact that test names can contain commas - and so would the user.

My thinking is to do it for everything if at all, otherwise it's confusing. For tests whose name contains a comma, it may present a problem though, requiring that the name be placed in quotes so it isn't split.

**Comment by oznetmaster** [comment]
Since comma delimited lists of test names are already allowed in the --tests option, and test names with commas in them have to be enclosed in quotes for that option, it does not seem to really be an issue to require any list element that contains a comma to be enclosed in quotes.

**Comment by rprouse** [comment]
I would lean towards don't do it, but I never create complicated test filters. For me, it is almost always limiting the run to a small subset of the tests that reflect the part of the software that I am working on.
