### ISSUE TITLE
Add DNX test command

### ISSUE THREAD

**Issue by roji** [nunit/nunit#927]
Following work on .NET Core in #575, nunit needs to expose a DNX command which would be used to run tests. This should work more or less like xunit.

**Comment by rprouse** [comment]
That is the plan. Once we get the updated NuGet packages out you should be able to do it now by making your tests self-executing. I still need to test and document though, so this issue is good for tracking that.

**Comment by rprouse** [comment]
I've been testing the latest code (yet to be released) and the NUnitLite runner is working. I created a new dnx `Console Application (Package)`, added a reference to NUnitLite which pulls in NUnit, added tests to that assembly and modified Program.cs as follows,

```C#
    public class Program
    {
        public int Main(string[] args)
        {
#if DNXCORE50
            return new AutoRun().Execute(typeof(Program).GetTypeInfo().Assembly, Console.Out, Console.In, args);
#else
            return new AutoRun().Execute(args);
#endif
        }
    }
```

The #if is unfortunate. Currently NuGet is pulling in the .NET 4.5 assembly for dnx451 which is probably more correct, but it has a different interface.

I modified the command in `project.json` and then I can execute the tests at the command line with the following series of commands,

```
dnvm use 1.0.0-beta8 -r coreclr -a x86
dnu restore
dnx test
```

Using clr instead of coreclr also works.

Once we get the final release of 3.0 out, I will create a more full featured runner for DNX. Until then, NUnitLite should be able to stand in.

**Comment by roji** [comment]
That's really great to hear, am looking forward to seeing this at work.

**Comment by oshalygin** [comment]
@rprouse  are you saying we can use NUnitLite today to get this going or is the latest code to is pending?  With RC released today any idea on DNX command support?

**Comment by rprouse** [comment]
For those that are interested, I have documented how to test .NET Core using NUnit at http://www.alteridem.net/2015/11/04/testing-net-core-using-nunit-3/

@oshalygin, you say that a console app is required which is true. What do you see as the alternative? The ability to run tests in Visual Studio?

**Comment by CharliePoole** [comment]
Nice. Unfortunately, I've been making it harder to create an NUnitLite test in my work on #922. :-( We can try to resolve that when I push it.

You seem to be double-escaping in your first example, so I actually see &amp;gt; rather than &gt;

**Comment by rprouse** [comment]
Good catch on the escaped greater-thans, fixed. Thanks @CharliePoole.

As for #922 making it harder, I expected that since we will have to wrap the console on the platform and then pass that in. I had hoped to solve that complexity either by adding the console wrapper to a project template, or by creating a new NuGet package that provides all the required console wrappers for each targeted platform.

**Comment by rprouse** [comment]
Everything has moved on with .NET Core, so I am closing this in favour of the currently more correct enhancement #1371.
