### ISSUE TITLE
Define PARALLEL in CF build of nunitlite

### ISSUE THREAD

**Issue by oznetmaster** [nunit/nunit#970]
Is the PARALLEL build being officially supported in nunitlite?

If so, setting it cause a build error in the CF build.

I had not noticed earlier because I always have supported it in my CF builds.

Specifically, in DisplayRunSettings: Environment.ProcessorCount is not supported in CF.

**Comment by CharliePoole** [comment]
We have been building CF with PARALLEL support for a long time. I think you are out of sync with master. There are two uses of Environment.ProcessorCount in the NUnitLite build and both are controlled by an #if statement. We use 2 threads in CF.

**Comment by oznetmaster** [comment]
#region DisplayRunSettings

#if !SILVERLIGHT
        public void DisplayRunSettings()
        {
            WriteSectionHeader("Run Settings");

            if (_options.DefaultTimeout >= 0)
                WriteLabelLine("    Default timeout: ", _options.DefaultTimeout);

#if PARALLEL
            WriteLabelLine(
                "    Number of Test Workers: ", 
                _options.NumberOfTestWorkers >= 0
                    ? _options.NumberOfTestWorkers
                    : Math.Max(Environment.ProcessorCount, 2));
#endif

            WriteLabelLine("    Work Directory: ", _options.WorkDirectory ?? NUnit.Env.DefaultWorkDirectory);

            WriteLabelLine("    Internal Trace: ", _options.InternalTraceLevel ?? "Off");

            if (_options.TeamCity)
                _outWriter.WriteLine(ColorStyle.Value, "    Display TeamCity Service Messages");

            SkipLine();
        }
#endif


From the currently synced master branch.

Is git broken somehow?

**Comment by oznetmaster** [comment]
From github itself:

```
        #region DisplayRunSettings

#if !SILVERLIGHT
        public void DisplayRunSettings()
        {
            WriteSectionHeader("Run Settings");

            if (_options.DefaultTimeout >= 0)
                WriteLabelLine("    Default timeout: ", _options.DefaultTimeout);

#if PARALLEL
            WriteLabelLine(
                "    Number of Test Workers: ", 
                _options.NumberOfTestWorkers >= 0
                    ? _options.NumberOfTestWorkers
                    : Math.Max(Environment.ProcessorCount, 2));
#endif

            WriteLabelLine("    Work Directory: ", _options.WorkDirectory ?? NUnit.Env.DefaultWorkDirectory);

            WriteLabelLine("    Internal Trace: ", _options.InternalTraceLevel ?? "Off");

            if (_options.TeamCity)
                _outWriter.WriteLine(ColorStyle.Value, "    Display TeamCity Service Messages");

            SkipLine();
        }
#endif

        #endregion
```

**Comment by CharliePoole** [comment]
I see the problem! PARALLEL is defined on the CF framework build, but not on NUnitLite. In every other platform build, it's either defined on both or on neither.

In fact, the PARALLEL define was originally added in order to support displaying the number of test workers - it should not be displayed for a framework that doesn't support it. 

I changed the title of this issue to reflect the fact that we should define PARALLEL. We'll also have to condition out the user of ProcessorCount.

As a longer term fix, I think NUnitLite should actually be querying the framework to find out whether or not it supports parallel execution. In fact, it should probably be asking the framework for the default number of threads.
