### ISSUE TITLE
Console closes immediately

### ISSUE THREAD

**Issue by Evosoul** [nunit/nunit#979]
Hello Guys,

i am new here and have a problem with the NUnit Console.
Everytime i want to start it just closes without an error message.
Is there anything else i need to install except the NUnit Framework and 
the developement environment?
I hope that you can help a newbie

regards
Evosoul

**Comment by CharliePoole** [comment]
What version of NUnit are you using? How did you install it? What command
line do you enter?

**Comment by Evosoul** [comment]
I use NUnit 2.6.4.
I installed it with the msi installer
I try to enter the 64 bit Command Line because I have a 64 bit Windows.
nunit-console.exe is the filename

**Comment by CharliePoole** [comment]
I'm not sure what you mean by the "64-bit command-line." What is the full
command you type?

**Comment by Evosoul** [comment]
Sorry, I misunderstood you. I can't type a command because the console opens up and immediately close. I never get a chance to insert a command

**Comment by CharliePoole** [comment]
How are you running it then? What do you do to run nunit-console if you are
not at the command-line? Are you trying to double-click it or something?
That would not work because it would simply display help and close.

Normally, to run nunit-console, you would open a command window, change
into the correct directory and type the command. NUnit-console would have
to be on your path or you would have to enter the full path to it.
Alternatively, if you are using some IDE to develop programs, you can set
it up to run nunit-console when you run the tests.

By the way, you should ask future "how-to" questions on our mail list -
nunit-discuss on google groups. This is for bugs and feature  requests. But
we can continue here now that we started.

**Comment by Evosoul** [comment]
I never run a Console of another programm, so I thought that it was enough to open the .exe file via double-click^^ But that was wrong. I got it working now.
Thanks for your help and sorry that I wrote this topic in the wrong section.

**Comment by CharliePoole** [comment]
No problem. I'm glad this was helpful.
