### ISSUE TITLE
Re-Rename nunit-console runner?

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit#987]
In resolving issue #929 we renamed nunit-console to nunit3-console. We did it pretty fast and not everyone is 100% happy. We have had some discussion but it's still hanging.

I'm creating this issue to force us to make a decision about the name before RC2, which is due out in a few days. I don't want to make the change past RC2, so a decision is critical.

Pros  and Cons of the original rename: (Feel free to edit this comment with more of them)

PRO 
It's a different program, with differnet options, let's give it a different name.
It will help some tools.
We have renamed some nuget packages, so we should rename the exe.

CON
Command-line users are used to typing nunit-console and know how to set the path.
It will hurt some tools.
We have renamed some nuget packages, so that should be sufficient.
We have not renamed other things, like nunitlite or the framework.

If I were doing this for me, based on personal preference, I'd revoke the change. We know that @NikolayPianikov was bothered by it. Feel free to include personal preferences.

If you don't care, I'm taking that as an indication we should not have changed it.

**Comment by rprouse** [comment]
I don't have a strong preference. The main problem I see is that many people will likely have to maintain a mix of NUnit 2 and 3 tests going forward. I like to add the NUnit bin directory to my path and it would be nice to have 2.6.4 and 3.0 available without having to modify my path.

The second problem I see is that some runners and build tools (like Cake) determine if NUnit is installed using the executable name. They would see that nunit-console.exe is installed, but running it would likely fail because it is being passed arguments for the other version. This will be very confusing for users who don't know any better. It would be better that tools like that just reported NUnit3 not found.

**Comment by oznetmaster** [comment]
I agree with @rprouse

**Comment by CharliePoole** [comment]
The ability to put both on the path is a good point.

**Comment by rprouse** [comment]
The path is the biggest annoyance for me right now. Most of our tests at work are 2.6.x, but we have begun migrating some of our test suites to 3.0. I am always typing the full path to one console or the other depending on my current path.

**Comment by CharliePoole** [comment]
@nunit/core-team I'll wait till tomorrow to decide about this. If you have comments, please post them!

**Comment by NikolayPianikov** [comment]
From other side, if we found some examples for other public build/test tools like NAnt, MSBuild, xNUnit, ngen, jsc.exe and csc.exe we could make a conclusion that is best solution :) Yes I know about the totally new console runner but why others did not do the same thing?

**Comment by Guson** [comment]
Most other tools don't change name. Better to qualify full path or use environment variables `%nunit%` v.s `%nunit3%`.

**Comment by rprouse** [comment]
@NikolayPianikov, which of the tools that you mentioned redid most of their command line arguments between versions so that old command line arguments would cause the tool to report an error and exit? I am not sure, but I think all of those tools continued to support the command line arguments from previous versions. I could be wrong though...

**Comment by rprouse** [comment]
MbUnit v2 was called MbUnit.Cons.exe which changed to Gallio.echo.exe in v3.

**Comment by CharliePoole** [comment]
@rprouse That's an example that goes both ways. They changed the name but they didn't put a '3' into it. I think that's what is bothering me about "nunit3-console version 3.0.0."

**Comment by CharliePoole** [comment]
At the moment, I don't see a clear path forward, so let's keep the status quo for rc2. OTOH, I'm not closing the issue, just pushing it forward.

**Comment by CharliePoole** [comment]
We'll keep the (current) status quo - nunit3-console. Closing this.
